Repository trinodb/trino, pull requests merged in 2019-12, with the labels that each got.

#2154 Don't synchronize on stats update in ThriftHiveMetastore
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#2141 Extract JdbcDiagnosticModule
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcConnectorFactory.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcDiagnosticModule.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcModule.java
Labels: cla-signed

#2038 Do not allocate resources within test constructor
  presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestSpatialJoins.java
  presto-google-sheets/src/test/java/io/prestosql/plugin/google/sheets/TestGoogleSheets.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedAggregations.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedJoinQueries.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedJoinQueriesWithDynamicFiltering.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedOrderByQueries.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedQueries.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedWindowQueries.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestShowStats.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergMetadataListing.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSystemTables.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlDistributedQueries.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestAggregations.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIndexedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestOrderByQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestWindowQueries.java
  presto-tests/src/test/java/io/prestosql/connector/system/TestSystemConnector.java
  presto-tests/src/test/java/io/prestosql/execution/TestBeginQuery.java
  presto-tests/src/test/java/io/prestosql/tests/TestDistributedQueriesIndexed.java
  presto-tests/src/test/java/io/prestosql/tests/TestDistributedSpilledQueries.java
  presto-tests/src/test/java/io/prestosql/tests/TestInformationSchemaConnector.java
  presto-tests/src/test/java/io/prestosql/tests/TestSpilledAggregations.java
  presto-tests/src/test/java/io/prestosql/tests/TestSpilledJoinQueries.java
  presto-tests/src/test/java/io/prestosql/tests/TestSpilledOrderByQueries.java
  presto-tests/src/test/java/io/prestosql/tests/TestSpilledWindowQueries.java
Labels: cla-signed, maintenance

#2153 Remove .travis.yml
  .travis.yml
  travis-buddy-failure-template.md
Labels: cla-signed

#2171 Remove Travis badge from README
  README.md
Labels: cla-signed

#2174 Remove unused, out of date, REST api docs
  presto-docs/src/main/sphinx/rest.rst
  presto-docs/src/main/sphinx/rest/node.rst
  presto-docs/src/main/sphinx/rest/query.rst
  presto-docs/src/main/sphinx/rest/stage.rst
  presto-docs/src/main/sphinx/rest/statement.rst
  presto-docs/src/main/sphinx/rest/task.rst
Labels: cla-signed

#2176 Remove unused StageResource and stage self uri
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestProgressMonitor.java
  presto-main/src/main/java/io/prestosql/execution/LocationFactory.java
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
  presto-main/src/main/java/io/prestosql/execution/SqlStageExecution.java
  presto-main/src/main/java/io/prestosql/execution/StageInfo.java
  presto-main/src/main/java/io/prestosql/execution/StageStateMachine.java
  presto-main/src/main/java/io/prestosql/execution/scheduler/SqlQueryScheduler.java
  presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
  presto-main/src/main/java/io/prestosql/server/StageResource.java
  presto-main/src/main/java/io/prestosql/server/remotetask/HttpLocationFactory.java
  presto-main/src/test/java/io/prestosql/execution/TestSqlStageExecution.java
  presto-main/src/test/java/io/prestosql/execution/TestSqlTaskManager.java
  presto-main/src/test/java/io/prestosql/execution/TestStageStateMachine.java
  presto-main/src/test/java/io/prestosql/execution/scheduler/TestSourcePartitionedScheduler.java
  presto-product-tests/src/test/resources/io/prestosql/tests/querystats/single_query_info_response.json
Labels: cla-signed

#2169 Do not log all plugin files per each product test setup
  presto-main/src/main/java/io/prestosql/server/PluginManager.java
Labels: cla-signed

#2163 Use testcontainers for MongoDB test
  presto-mongodb/pom.xml
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/MongoQueryRunner.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/MongoServer.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/SyncMemoryBackend.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoPlugin.java
Labels: cla-signed, maintenance

#2168 Remove redundant JsonTypeInfo include property assignment
  presto-main/src/main/java/io/prestosql/operator/OperatorInfo.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/PlanNode.java
  presto-spi/src/main/java/io/prestosql/spi/connector/LocalProperty.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/ValueSet.java
Labels: cla-signed

#2191 Continue running jobs even if another job fails
  .github/workflows/main.yml
Labels: cla-signed

#2186 Remove unused typeManager from HivePartitionManager
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#2101 Verify java version during RPM tests
  presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Labels: cla-signed

#2138 Use testcontainers for TestingPostgreSqlServer
  pom.xml
  presto-postgresql/pom.xml
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#2156 Add support for accessing MongoDB view
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#2194 Use testcontainers-bom to define testcontainers dependencies
  pom.xml
Labels: cla-signed

#2195 Enable non-integration tests for Kudu
  .github/workflows/main.yml
  presto-kudu/pom.xml
Labels: cla-signed

#2193 Allow using Maven profiles in test-modules matrix job
  .github/workflows/main.yml
Labels: cla-signed

#2192 Add doc for renaming view
  presto-docs/src/main/sphinx/sql.rst
  presto-docs/src/main/sphinx/sql/alter-view.rst
Labels: cla-signed

#2203 Use FileBodyGenerator from Airlift
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/backup/HttpBackupStore.java
Labels: cla-signed

#2189 Implement rename view in Hive connector
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#2181 Set system properties cautiously
  presto-client/src/main/java/io/prestosql/client/SpnegoHandler.java
  presto-kinesis/src/test/java/io/prestosql/plugin/kinesis/TestMinimalFunctionality.java
  presto-main/src/main/java/io/prestosql/server/security/KerberosAuthenticator.java
Labels: cla-signed

#2211 Announce all data sources on coordinator
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
Labels: cla-signed

#2200 Reduce Memory Used by Finished AsyncQueue Instances
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/AsyncQueue.java
Labels: cla-signed

#2201 Run TestFullParquetReader on CI
  .github/workflows/main.yml
  presto-hive/pom.xml
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/TestFullParquetReader.java
Labels: cla-signed

#2207 Run single test in TestOrcReader with full tester
  presto-orc/src/test/java/io/prestosql/orc/AbstractTestOrcReader.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcReader.java
Labels: cla-signed

#2208 Be verbose when exiting from test suite
  presto-product-tests/bin/product-tests-suite-1.sh
  presto-product-tests/bin/product-tests-suite-2.sh
  presto-product-tests/bin/product-tests-suite-3.sh
  presto-product-tests/bin/product-tests-suite-5.sh
  presto-product-tests/bin/product-tests-suite-6-non-generic.sh
  presto-product-tests/bin/product-tests-suite-7-non-generic.sh
Labels: cla-signed

#2219 Fix type used for calculation HiveTypeName estimated bytes size
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTypeName.java
Labels: cla-signed

#2198 Use eventual assertion in ServerIT
  presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Labels: cla-signed

#2142 Add info about unicode and binary literal usage
  presto-docs/src/main/sphinx/language/types.rst
Labels: cla-signed

#2234 Move functions doc to earlier than sql
  presto-docs/src/main/sphinx/index.rst
Labels: cla-signed

#2238 Remove outdated javadoc
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
Labels: cla-signed

#2239 Using JAVA_HOME bugfix in rpm
  presto-server-rpm/src/main/resources/dist/etc/init.d/presto
Labels: cla-signed

#2243 Remove Unnecessary Block Creation in ParquetPageSource
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSource.java
Labels: cla-signed

#2151 Add .editorconfig
  .editorconfig
Labels: cla-signed

#2248 Add orc_use_column_names hive session property
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSessionProperties.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveTestUtils.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestOrcPageSourceMemoryTracking.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
Labels: cla-signed

#2247 Add execution time to QueryStatistics class in SPI
  presto-main/src/main/java/io/prestosql/event/QueryMonitor.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryStatistics.java
Labels: cla-signed

#2249 Add error_type and error_code columns to system.runtime.queries
  presto-main/src/main/java/io/prestosql/connector/system/QuerySystemTable.java
  presto-product-tests/src/main/java/io/prestosql/tests/TestSystemConnector.java
  presto-product-tests/src/main/resources/sql-tests/testcases/system/selectInformationSchemaColumns.result
Labels: cla-signed

#2261 Update docker images version to 24
  presto-product-tests/conf/product-tests-defaults.sh
Labels: cla-signed

#2276 Fix formatting
  .editorconfig
Labels: cla-signed

#2250 Report offending location
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
Labels: cla-signed

#2159 Remove misleading TODO
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
Labels: cla-signed

#2275 Rename config toggle for work processors
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
  presto-tests/src/test/java/io/prestosql/tests/TestLateMaterializationQueries.java
Labels: cla-signed

#2267 Check for null before reading mask value
  presto-main/src/main/java/io/prestosql/sql/gen/CompilerOperations.java
  presto-main/src/test/java/io/prestosql/operator/TestAggregationOperator.java
Labels: cla-signed

#2266 Consistent naming for CLI
  presto-cli/src/main/java/io/prestosql/cli/Console.java
Labels: cla-signed

#2244 Add doc about version usage
  presto-docs/README.md
Labels: cla-signed

#2139 Add introductions and links to SQL chapters
  presto-docs/src/main/sphinx/functions.rst
  presto-docs/src/main/sphinx/language.rst
  presto-docs/src/main/sphinx/sql.rst
Labels: cla-signed

#2245 Remove bullets from ToC lists
  presto-docs/src/main/sphinx/themes/presto/static/presto.css_t
Labels: cla-signed

#2259 Fix and improve error message
  presto-orc/pom.xml
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/DateStatistics.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/DecimalStatistics.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/DoubleStatistics.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/IntegerStatistics.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/StringStatistics.java
  presto-orc/src/test/java/io/prestosql/orc/metadata/statistics/TestStringStatistics.java
Labels: cla-signed

#2231 Use ArrayBlockingQueue instead of LinkedBlockingQueue
  presto-cli/src/main/java/io/prestosql/cli/OutputHandler.java
Labels: cla-signed

#2253 kudu: use in-list predicate if ranges are all single values
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
Labels: cla-signed

#2281 Fix CSS selector to only hide release notes
  presto-docs/src/main/sphinx/index.rst
  presto-docs/src/main/sphinx/themes/presto/static/presto.css_t
Labels: cla-signed

#2284 Add oneliner example with doc version
  presto-docs/README.md
Labels: cla-signed

#2270 Find preferred bash locally
  presto-hive-hadoop2/bin/common.sh
  presto-hive-hadoop2/bin/run_hive_s3_tests.sh
  presto-hive-hadoop2/bin/run_hive_tests.sh
  presto-hive-hadoop2/bin/start_hive.sh
  presto-kudu/bin/run_kudu_tests.sh
  presto-main/bin/check_webui.sh
  presto-product-tests/bin/lib.sh
  presto-product-tests/bin/run_on_docker.sh
  presto-product-tests/bin/run_presto_cli_on_docker.sh
  presto-product-tests/bin/run_tempto_on_docker.sh
  presto-product-tests/bin/stop_all_containers.sh
Labels: cla-signed

#2295 Remove unnecessary UUID
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#2291 Fix misleading credential of MongoDB
  presto-docs/src/main/sphinx/connector/mongodb.rst
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientConfig.java
Labels: cla-signed

#2319 Added one-liner for resource group 'softConcurrencyLimit'.
  presto-docs/src/main/sphinx/admin/resource-groups.rst
Labels: cla-signed

#2310 Fix predicate pushdown for Elasticsearch
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/BuiltinColumns.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchColumnHandle.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchQueryBuilder.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
Labels: cla-signed

#2313 Fix Joni regexp functions for multi-byte characters and empty pattern
  presto-main/src/main/java/io/prestosql/operator/scalar/JoniRegexpFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/JoniRegexpReplaceLambdaFunction.java
  presto-main/src/test/java/io/prestosql/operator/scalar/AbstractTestRegexpFunctions.java
Labels: bug, cla-signed, ready to merge

#2326 Revert "Enable Maven stacktrace for workflow errors"
  .github/workflows/main.yml
Labels: cla-signed, ready to merge

#2322 Test aggregation filter with subquery
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestAggregations.java
Labels: cla-signed, maintenance, ready to merge, test

#2317 Do not allocate resources in AbstractTestDistributedQueries' constructors
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloDistributedQueries.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergDistributed.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorDistributedQueries.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorDistributedQueriesBucketed.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed, ready to merge

#2314 Minor test refactor
  presto-main/src/test/java/io/prestosql/cost/TestFilterStatsCalculator.java
Labels: cla-signed, ready to merge

#2325 Update testcontainers to 1.12.4
  pom.xml
Labels: cla-signed

#2335 Add documentation for password file authentication
  presto-docs/src/main/sphinx/release/release-327.rst
  presto-docs/src/main/sphinx/security.rst
  presto-docs/src/main/sphinx/security/password-file.rst
Labels: cla-signed

#1874 Add support for creating schema in JDBC connector
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloIntegrationSmokeTest.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcIntegrationSmokeTest.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraIntegrationSmokeTest.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationSmoke.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
  presto-redis/src/test/java/io/prestosql/plugin/redis/TestRedisIntegrationSmokeTest.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/TestThriftIntegrationSmokeTest.java
Labels: cla-signed

#2327 Use same docker image for Kafka in product tests
  presto-product-tests/conf/docker/singlenode-kafka/docker-compose.yml
  presto-product-tests/src/main/resources/tempto-configuration.yaml
Labels: cla-signed

#2336 Move singlenode-kafka files to its directory
  presto-product-tests/conf/docker/singlenode-kafka/docker-compose.yml
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka.properties
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/all_datatypes_avro.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/all_datatypes_avro_schema.avsc
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/all_datatypes_csv.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/all_datatypes_json.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/all_datatypes_raw.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/all_null_avro.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/simple_key_and_value.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/structural_datatype_avro.json
  presto-product-tests/conf/docker/singlenode-kafka/presto-master/etc/presto/catalog/kafka/structural_datatype_avro_schema.avsc
Labels: cla-signed

#2339 Allow committing empty transaction
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoConnection.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
Labels: cla-signed

#2340 Allow restoring autocommit mode
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoConnection.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
Labels: cla-signed

#2342 Remove `-q` flag from `command | grep -q` and ignore output
  presto-hive-hadoop2/bin/common.sh
  presto-product-tests/bin/run_on_docker.sh
Labels: cla-signed

#2061 Support narrowing type coercions during INSERT
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloDistributedQueries.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergDistributed.java
  presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
  presto-main/src/main/java/io/prestosql/type/TypeCoercion.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#2345 Fix bad merge
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Labels: cla-signed

#1969 Fix RemoveUnreferencedScalarSubqueries rule
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveUnreferencedScalarSubqueries.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/QueryCardinalityUtil.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestRemoveUnreferencedScalarSubqueries.java
  presto-main/src/test/java/io/prestosql/sql/query/TestSubqueries.java
Labels: cla-signed

#2354 Add support for LDAP referrals
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java
  presto-product-tests/bin/product-tests-suite-6-non-generic.sh
  presto-product-tests/conf/docker/singlenode-ldap-referrals/compose.sh
  presto-product-tests/conf/docker/singlenode-ldap-referrals/docker-compose.yml
  presto-product-tests/conf/docker/singlenode-ldap-referrals/presto-master/etc/password-authenticator.properties
Labels: cla-signed

#2357 Remove unused Metadata parameter
  presto-main/src/main/java/io/prestosql/cost/FilterStatsCalculator.java
  presto-main/src/main/java/io/prestosql/sql/DynamicFilters.java
  presto-main/src/main/java/io/prestosql/sql/planner/DistributedExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionInterpreter.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilter.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/DynamicFiltersChecker.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFilter.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/DynamicFilterMatcher.java
Labels: cla-signed

#2331 Avoid retrying permanent errors for S3-related services
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
Labels: cla-signed

#2136 Add regexp_position and regexp_count functions
  presto-docs/src/main/sphinx/functions/regexp.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/JoniRegexpFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/Re2JRegexpFunctions.java
  presto-main/src/main/java/io/prestosql/type/Re2JRegexp.java
  presto-main/src/test/java/io/prestosql/operator/scalar/AbstractTestRegexpFunctions.java
Labels: cla-signed

#2146 Update tempto to 168
  pom.xml
  presto-product-tests/src/main/java/io/prestosql/tests/TemptoProductTestRunner.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/AllSimpleTypesTableDefinitions.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
  presto-product-tests/src/main/java/io/prestosql/tests/querystats/QueryStatsClientModuleProvider.java
Labels: cla-signed

#2364 Make Re2JRegexp fields private
  presto-main/src/main/java/io/prestosql/operator/scalar/Re2JRegexpReplaceLambdaFunction.java
  presto-main/src/main/java/io/prestosql/type/Re2JRegexp.java
Labels: cla-signed

#2365 Use AstUtils in ExpressionTreeUtils
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionTreeUtils.java
Labels: cla-signed

#2333 Update to Parquet 1.11.0
  pom.xml
  presto-parquet/src/test/java/io/prestosql/parquet/reader/TestMetadataReader.java
Labels: cla-signed

#2369 Remove unused method
  presto-main/src/main/java/io/prestosql/sql/planner/Partitioning.java
Labels: cla-signed

#2362 Fix test class name
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3select/TestUnrecoverableS3OperationException.java
Labels: cla-signed

#2323 Fix planning failure due to incomplete pushdown
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/UnwrapCastInComparison.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java
Labels: cla-signed
