Repository trinodb/trino, pull requests merged in 2019-10, with the labels that each got.

#1598 Make MySQL Driver's useInformationSchema configurable
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClientModule.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlConfig.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlConfig.java
Labels: cla-signed

#1627 Remove unused method
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/StringStatisticsBuilder.java
Labels: cla-signed

#1492 Use dockerized testing PostgreSql server
  presto-postgresql/pom.xml
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/PostgreSqlQueryRunner.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlDistributedQueries.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#1625 Add support for Glue metastore cache
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreModule.java
Labels: cla-signed

#1613 Temporarily force bucketing v1 in test
  presto-hive/src/test/sql/create-test.sql
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
Labels: cla-signed

#1624 Introduce a builder for Identity
  presto-atop/src/test/java/io/prestosql/plugin/atop/TestAtopSecurity.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileBasedSecurity.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveRoles.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergMetadataListing.java
  presto-kinesis/src/test/java/io/prestosql/plugin/kinesis/TestMinimalFunctionality.java
  presto-main/src/main/java/io/prestosql/Session.java
  presto-main/src/main/java/io/prestosql/SessionRepresentation.java
  presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/testing/TestingSession.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
  presto-main/src/test/java/io/prestosql/server/TestHttpRequestSessionContext.java
  presto-main/src/test/java/io/prestosql/server/TestSessionPropertyDefaults.java
  presto-main/src/test/java/io/prestosql/sql/query/TestSessionFunctions.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestCredentialPassthrough.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/security/TestRaptorFileBasedSecurity.java
  presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/SqlServerQueryRunner.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
  presto-tests/src/test/java/io/prestosql/execution/sessionpropertymanagers/TestDbSessionPropertyManagerIntegration.java
Labels: cla-signed

#1633 Add information schema logging
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSourceProvider.java
Labels: cla-signed

#1645 Remove obsolete artifacts deployin by Travis
  .travis.yml
Labels: cla-signed

#1647 Remove unused variable
  presto-tests/src/test/java/io/prestosql/connector/informationschema/BenchmarkInformationSchema.java
Labels: cla-signed

#1649 Remove empty files left behind after mounting with different name
  presto-product-tests/bin/lib.sh
  presto-product-tests/bin/run_on_docker.sh
Labels: cla-signed

#1650 Update example EXPLAIN output in documentation
  presto-docs/src/main/sphinx/sql/explain.rst
Labels: cla-signed

#1651 Improve numbers legibility in CLI
  presto-cli/src/main/java/io/prestosql/cli/InputHighlighter.java
Labels: cla-signed

#1658 Minor correction in docs related to Web Interface
  presto-docs/src/main/sphinx/admin/web-interface.rst
Labels: cla-signed

#1628 Code cleanup in SqlTime* classes
  presto-spi/src/main/java/io/prestosql/spi/type/SqlTime.java
  presto-spi/src/main/java/io/prestosql/spi/type/SqlTimeWithTimeZone.java
  presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestamp.java
  presto-spi/src/main/java/io/prestosql/spi/type/SqlTimestampWithTimeZone.java
Labels: cla-signed

#1662 Add support for Elasticsearch query string syntax
  presto-docs/src/main/sphinx/connector/elasticsearch.rst
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchClient.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchErrorCode.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchQueryBuilder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchTableHandle.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
Labels: cla-signed

#1644 Rename H2 testing JdbcQueryRunner to H2QueryRunner
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/H2QueryRunner.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcDistributedQueries.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcIntegrationSmokeTest.java
Labels: cla-signed

#1612 Add at_timezone and with_timezone functions
  presto-docs/src/main/sphinx/functions/datetime.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
Labels: cla-signed

#1677 Fix CLI special command handling
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-cli/src/main/java/io/prestosql/cli/InputParser.java
Labels: cla-signed

#1676 Add 320 release notes
  presto-docs/src/main/sphinx/connector/elasticsearch.rst
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-320.rst
Labels: cla-signed

#1678 Fix handling of backslash characters
  presto-cli/src/main/java/io/prestosql/cli/InputParser.java
Labels: cla-signed

#1682 Cleanup documentation for date/time functions
  presto-docs/src/main/sphinx/functions/datetime.rst
Labels: cla-signed

#1653 Extract suite with non-generic product tests
  .travis.yml
  presto-product-tests/bin/product-tests-suite-3.sh
  presto-product-tests/bin/product-tests-suite-4.sh
  presto-product-tests/bin/product-tests-suite-6-non-generic.sh
  presto-product-tests/bin/product-tests-suite-7-non-generic.sh
Labels: cla-signed

#1669 Improve usage of run_on_docker.sh
  presto-product-tests/bin/lib.sh
  presto-product-tests/bin/run_on_docker.sh
  presto-product-tests/bin/run_presto_cli_on_docker.sh
  presto-product-tests/bin/run_tempto_on_docker.sh
Labels: cla-signed

#1687 Add support for Cassandra cluster using SSL
  presto-cassandra/pom.xml
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientConfig.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientModule.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraErrorCode.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraClientConfig.java
  presto-docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed

#1572 Add support for wildcard patterns in JMX dump tables configuration
  presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxErrorCode.java
  presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxHistoricalData.java
  presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxMetadata.java
  presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxHistoricalData.java
  presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxMetadata.java
Labels: cla-signed

#1693 Add support for ES nodes without public address
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchClient.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchSplit.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/NodesSystemTable.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchNode.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/NodesResponse.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/Shard.java
Labels: cla-signed

#1660 Change nextUri slug for every request
  presto-main/src/main/java/io/prestosql/dispatcher/DispatchManager.java
  presto-main/src/main/java/io/prestosql/dispatcher/DispatchQueryFactory.java
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQueryFactory.java
  presto-main/src/main/java/io/prestosql/dispatcher/QueuedStatementResource.java
  presto-main/src/main/java/io/prestosql/execution/DataDefinitionExecution.java
  presto-main/src/main/java/io/prestosql/execution/QueryExecution.java
  presto-main/src/main/java/io/prestosql/execution/QueryManager.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
  presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
  presto-main/src/main/java/io/prestosql/server/protocol/Query.java
  presto-main/src/main/java/io/prestosql/server/protocol/Slug.java
  presto-tests/src/test/java/io/prestosql/execution/TestQueryRunnerUtil.java
  presto-tests/src/test/java/io/prestosql/tests/TestMetadataManager.java
  presto-tests/src/test/java/io/prestosql/tests/TestQueryManager.java
Labels: cla-signed

#1603 Consolidate and bump the snappy-java version
  pom.xml
  presto-product-tests/pom.xml
  presto-record-decoder/pom.xml
Labels: cla-signed

#1704 Add support for LazyBlock in columnar decompose helpers
  presto-main/src/main/java/io/prestosql/operator/PageUtils.java
  presto-spi/src/main/java/io/prestosql/spi/block/Block.java
  presto-spi/src/main/java/io/prestosql/spi/block/ColumnarArray.java
  presto-spi/src/main/java/io/prestosql/spi/block/ColumnarMap.java
  presto-spi/src/main/java/io/prestosql/spi/block/ColumnarRow.java
  presto-spi/src/main/java/io/prestosql/spi/block/LazyBlock.java
Labels: cla-signed

#1705 Code cleanup
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketing.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestHiveBucketing.java
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
Labels: cla-signed

#1668 Allow configuring hive directory listing cache with table prefixes
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/CachingDirectoryLister.java
Labels: cla-signed

#1701 Support .lzo files
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-product-tests/bin/product-tests-suite-1.sh
  presto-product-tests/bin/product-tests-suite-2.sh
  presto-product-tests/src/main/java/io/prestosql/tests/TestGroups.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestCompression.java
Labels: cla-signed

#1713 Removed predicate sort by name
  presto-main/src/main/java/io/prestosql/sql/planner/DomainTranslator.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestDomainTranslator.java
Labels: cla-signed

#1712 Add equals and hashcode methods to ConnectorExpression
  presto-spi/src/main/java/io/prestosql/spi/expression/ConnectorExpression.java
  presto-spi/src/main/java/io/prestosql/spi/expression/Constant.java
  presto-spi/src/main/java/io/prestosql/spi/expression/FieldDereference.java
  presto-spi/src/main/java/io/prestosql/spi/expression/Variable.java
Labels: cla-signed

#1728 Add LazyBlock javadoc regarding lazy block loader
  presto-spi/src/main/java/io/prestosql/spi/block/LazyBlockLoader.java
Labels: cla-signed

#1667 Remove legacy serialization for ClientTypeSignature
  presto-client/src/main/java/io/prestosql/client/ClientTypeSignature.java
  presto-client/src/main/java/io/prestosql/client/ClientTypeSignatureParameter.java
  presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java
  presto-client/src/main/java/io/prestosql/client/ParameterKind.java
  presto-client/src/test/java/io/prestosql/client/TestClientTypeSignature.java
  presto-client/src/test/java/io/prestosql/client/TestParameterKind.java
Labels: cla-signed

#1727 Remove redundant Hive dynamic filtering test
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedJoinQueriesWithDynamicFiltering.java
Labels: cla-signed

#1752 Update release notes
  presto-docs/src/main/sphinx/release/release-318.rst
Labels: cla-signed

#1753 Update units to 1.4
  pom.xml
Labels: cla-signed

#1749 Simplify Docker build by removing hardlink command
  docker/Dockerfile
Labels: cla-signed

#1745 Add 321 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-321.rst
Labels: cla-signed

#1521 Add KeyStore based CredentialProvider for JDBC based connectors
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/CredentialProviderModule.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/CredentialProviderType.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/keystore/KeyStoreBasedCredentialProviderConfig.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/keystore/KeyStoreUtils.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/credential/TestCredentialProvider.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/credential/keystore/TestKeyStoreBasedCredentialProviderConfig.java
  presto-base-jdbc/src/test/resources/credentials.jceks
Labels: cla-signed

#1760 Add test for nested uncorrelated subqueries
  presto-main/src/test/java/io/prestosql/sql/query/TestSubqueries.java
Labels: cla-signed

#1754 Validate that equi join clauses are normalized according to join sides
  presto-main/src/main/java/io/prestosql/sql/planner/plan/JoinNode.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestEliminateCrossJoins.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestReorderJoins.java
Labels: cla-signed

#1765 Restore removed TODO
  presto-main/src/main/java/io/prestosql/sql/planner/EffectivePredicateExtractor.java
Labels: cla-signed

#1694 Extract BaseJdbcAuthenticationConfig
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcAuthenticationConfig.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcConfig.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/CredentialProviderModule.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/ExtraCredentialProvider.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestBaseJdbcAuthenticationConfig.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestBaseJdbcConfig.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingDatabase.java
Labels: cla-signed

#1770 Remove default Maven settings for Travis
  .travis.yml
Labels: cla-signed

#1769 Use provisio for RPM instead of maven-dependency-plugin
  pom.xml
  presto-server-rpm/pom.xml
  presto-server-rpm/src/main/provisio/presto.xml
Labels: cla-signed

#1773 Add 322 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-321.rst
  presto-docs/src/main/sphinx/release/release-322.rst
Labels: cla-signed

#1725 Support Hive materialized view
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveMaterializedView.java
Labels: cla-signed

#1761 Unnest dictionary blocks on compaction
  presto-main/src/test/java/io/prestosql/block/TestDictionaryBlock.java
  presto-spi/src/main/java/io/prestosql/spi/block/DictionaryBlock.java
Labels: cla-signed

#1758 Product tests for bucketing versions
  presto-product-tests/src/main/java/io/prestosql/tests/hive/BucketingVersion.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
Labels: cla-signed

#1768 Update docs for RPM based installation
  presto-server-rpm/README.md
Labels: cla-signed

#1789 Fix property name in documentation
  presto-docs/src/main/sphinx/develop/password-authenticator.rst
Labels: cla-signed

#1740 Graduate array-mapping from experimental
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlConfig.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlConfig.java
Labels: cla-signed

#1783 Remove redundant call to getTable when altering table
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#1744 Simplify LazyBlockLoader interface
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rcfile/RcFilePageSource.java
  presto-main/src/main/java/io/prestosql/operator/PageUtils.java
  presto-main/src/main/java/io/prestosql/operator/project/DictionaryAwarePageProjection.java
  presto-main/src/main/java/io/prestosql/operator/project/InputPageProjection.java
  presto-main/src/test/java/io/prestosql/operator/TestPageUtils.java
  presto-main/src/test/java/io/prestosql/operator/TestScanFilterAndProjectOperator.java
  presto-main/src/test/java/io/prestosql/operator/project/TestDictionaryAwarePageFilter.java
  presto-main/src/test/java/io/prestosql/operator/project/TestDictionaryAwarePageProjection.java
  presto-main/src/test/java/io/prestosql/operator/project/TestInputPageProjection.java
  presto-main/src/test/java/io/prestosql/operator/project/TestMergePages.java
  presto-main/src/test/java/io/prestosql/operator/project/TestPageProcessor.java
  presto-orc/src/main/java/io/prestosql/orc/OrcBlockFactory.java
  presto-spi/src/main/java/io/prestosql/spi/block/LazyBlock.java
  presto-spi/src/main/java/io/prestosql/spi/block/LazyBlockLoader.java
  presto-tpch/src/main/java/io/prestosql/plugin/tpch/LazyRecordPageSource.java
Labels: cla-signed

#1785 Make client compatible with older servers
  presto-client/src/main/java/io/prestosql/client/ClientTypeSignatureParameter.java
Labels: cla-signed

#1796 Fix column aliases handling in RelationType
  presto-main/src/main/java/io/prestosql/sql/analyzer/RelationType.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
Labels: cla-signed

#1788 Add integration test for server RPM
  .travis.yml
  presto-server-rpm/pom.xml
  presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Labels: cla-signed

#1795 Remove unused fields in ORC readers
  presto-orc/src/main/java/io/prestosql/orc/reader/BooleanColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/ByteColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/DecimalColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/DoubleColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/FloatColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/LongColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/SliceDictionaryColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/TimestampColumnReader.java
Labels: cla-signed

#1800 Remove more uses of parseTypeSignature
  presto-main/src/main/java/io/prestosql/operator/aggregation/DecimalAverageAggregation.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/DecimalSumAggregation.java
  presto-main/src/main/java/io/prestosql/type/DecimalCasts.java
  presto-main/src/main/java/io/prestosql/type/DecimalInequalityOperators.java
  presto-main/src/main/java/io/prestosql/type/DecimalOperators.java
  presto-main/src/main/java/io/prestosql/type/DecimalSaturatedFloorCasts.java
  presto-main/src/test/java/io/prestosql/metadata/TestPolymorphicScalarFunction.java
  presto-main/src/test/java/io/prestosql/metadata/TestSignatureBinder.java
  presto-main/src/test/java/io/prestosql/operator/TestAnnotationEngineForAggregates.java
  presto-main/src/test/java/io/prestosql/operator/TestAnnotationEngineForScalars.java
  presto-main/src/test/java/io/prestosql/operator/TestTypeSignature.java
Labels: cla-signed

#1806 Update docker images version to 21
  presto-product-tests/conf/product-tests-defaults.sh
Labels: cla-signed

#1778 Embed Presto version into main thread
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
Labels: cla-signed

#1594 Add Alluxio client jar to hive-hadoop2 as a library
  pom.xml
  presto-hive-hadoop2/pom.xml
Labels: cla-signed

#1816 Disable TestPhoenixDistributedQueries.testLargeIn
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java
Labels: cla-signed

#1810 Remove unused classes
  presto-main/src/test/java/io/prestosql/util/InfiniteRecordSet.java
  presto-main/src/test/java/io/prestosql/util/MockPowerOfTwo.java
  presto-main/src/test/java/io/prestosql/util/Numbers.java
Labels: cla-signed

#1818 Remove LengthLimitedIterator
  presto-jdbc/src/main/java/io/prestosql/jdbc/LengthLimitedIterator.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
Labels: cla-signed, maintenance

#1793 Avoid redundant getTable call in updateTableStatistics
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#1794 Avoid redundant getPartitionsByNames call in updatePartitionStatistics
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#1822 Produce fallback value lazily
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQuery.java
Labels: cla-signed

#1813 Move JsonUtils to util package
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/util/JsonUtils.java
Labels: cla-signed

#1561 Iceberg predicate pushdown
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed

#1831 Fill ORC's MAGIC in PostScript
  presto-orc/src/main/java/io/prestosql/orc/metadata/OrcMetadataWriter.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed

#1821 Calrify javadoc
  presto-spi/src/main/java/io/prestosql/spi/block/Block.java
Labels: cla-signed

#1815 Fix Unicode rendering in CLI pager in Docker image
  docker/Dockerfile
Labels: cla-signed

#1784 Document default max rows in Google Sheets Connector
  presto-docs/src/main/sphinx/connector/googlesheets.rst
  presto-google-sheets/src/main/java/io/prestosql/plugin/google/sheets/SheetsClient.java
Labels: cla-signed

#1845 Add 323 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-323.rst
Labels: cla-signed

#1860 Run two hives product tests with non generic suite
  presto-product-tests/bin/product-tests-suite-5.sh
  presto-product-tests/bin/product-tests-suite-7-non-generic.sh
Labels: cla-signed

#1844 Add support for datetimes exposed as numbers in Elasticsearch
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/TimestampDecoder.java
Labels: cla-signed

#1846 Parquet Dictionary Predicate Pushdown Fixes
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/Predicate.java
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/PredicateUtils.java
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
  presto-parquet/src/test/java/io/prestosql/parquet/TestTupleDomainParquetPredicate.java
Labels: cla-signed

#1857 Remove unnecessary throws declaration
  presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestInsertIntoCassandraTable.java
  presto-product-tests/src/main/java/io/prestosql/tests/cli/TestPrestoCli.java
  presto-product-tests/src/main/java/io/prestosql/tests/kafka/TestKafkaAvroSmokeTest.java
Labels: cla-signed

#1881 Fix broken TestHiveIntegrationSmokeTest#testNullPartitionValues
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
Labels: bug, cla-signed

#1887 Adjust argument layout to code style
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkDriver.java
  presto-benchmark/src/main/java/io/prestosql/benchmark/HandTpchQuery1.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestOrcPageSourceMemoryTracking.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/write/TestMapredParquetOutputFormat.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaRecordSet.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaTableDescriptionSupplier.java
  presto-kinesis/src/main/java/io/prestosql/plugin/kinesis/KinesisTableDescriptionSupplier.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduConnector.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduMetadata.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSplitManager.java
  presto-main/src/main/java/io/prestosql/dispatcher/FailedDispatchQuery.java
  presto-main/src/main/java/io/prestosql/execution/MemoryTrackingRemoteTaskFactory.java
  presto-main/src/main/java/io/prestosql/execution/RemoteTaskFactory.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/metadata/SessionPropertyManager.java
  presto-main/src/main/java/io/prestosql/operator/ScanFilterAndProjectOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableWriterOperator.java
  presto-main/src/main/java/io/prestosql/operator/TaskContext.java
  presto-main/src/main/java/io/prestosql/operator/index/IndexBuildDriverFactoryProvider.java
  presto-main/src/main/java/io/prestosql/operator/index/IndexLoader.java
  presto-main/src/main/java/io/prestosql/operator/window/WindowPartition.java
  presto-main/src/main/java/io/prestosql/server/HttpRemoteTaskFactory.java
  presto-main/src/main/java/io/prestosql/server/remotetask/HttpRemoteTask.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analyzer.java
  presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java
  presto-main/src/main/java/io/prestosql/sql/gen/JoinCompiler.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PlanOptimizer.java
  presto-main/src/test/java/io/prestosql/execution/MockRemoteTaskFactory.java
  presto-main/src/test/java/io/prestosql/operator/TestExchangeClient.java
  presto-main/src/test/java/io/prestosql/sql/gen/TestExpressionCompiler.java
  presto-orc/src/main/java/io/prestosql/orc/StripeReader.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/Footer.java
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/PageReader.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/ParquetColumnChunk.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestingPrestoClient.java
Labels: cla-signed

#1869 Support for creating skewed StorageDescriptor
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestMetastoreUtil.java
Labels: cla-signed

#1842 Swallow HiveViewNotSupportedException for SHOW GRANTS
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControlMetadata.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestGrantRevoke.java
Labels: cla-signed

#1890 Fixing logging verbosity for gsheets plugin
  presto-google-sheets/src/main/java/io/prestosql/plugin/google/sheets/SheetsClient.java
Labels: cla-signed

#1517 Adding access control check in show create table
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
Labels: cla-signed

#1889 Remove confusing notSupportedException helper
  presto-main/src/main/java/io/prestosql/sql/analyzer/SemanticExceptions.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/SubqueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/CheckSubqueryNodesAreRewritten.java
Labels: cla-signed

#1895 Disable testLargeIn in plan determinism tester
  presto-tests/src/test/java/io/prestosql/tests/TestQueryPlanDeterminism.java
Labels: cla-signed

#1691 Add escape character in like predicate for SHOW CATALOGS
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/ShowCatalogs.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java
Labels: cla-signed

#1894 Support insert for Postgres hstore
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-tests/src/main/java/io/prestosql/tests/datatype/CreateAndPrestoInsertDataSetup.java
Labels: cla-signed

#1902 Fix test method overrides
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestIntegrationSmokeTest.java
Labels: cla-signed

#1897 Add convenience constructor for JdbcColumnHandle
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcColumnHandle.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcColumnHandle.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcMetadata.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcQueryBuilder.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcRecordSet.java
Labels: cla-signed

#1901 Enable PR notifications when Travis fails
  .travis.yml
Labels: cla-signed

#1859 Update S3 tests
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#1920 Add release notes for bucketing v2
  presto-docs/src/main/sphinx/release/release-321.rst
Labels: cla-signed

#1914 Handle mixed-case columns in Elasticsearch
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
Labels: cla-signed
