Repository trinodb/trino, pull requests merged in 2019-02, with the labels that each got.

#112 Remove unused class ConnectorAnalyzeMetadata
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAnalyzeMetadata.java
Labels: cla-signed

#133 Add physical* and internalNetwork* stats to QueryStatistics
  presto-main/src/main/java/io/prestosql/event/QueryMonitor.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryStatistics.java
Labels: cla-signed

#140 Use class reference for BlockMissingException
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/HdfsOrcDataSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rcfile/RcFilePageSourceFactory.java
Labels: cla-signed

#92 Document note about LDAPS and JDK Upgrade
  presto-docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed

#32 Cleanup code in ORC module
  presto-orc/src/main/java/io/prestosql/orc/OrcDataSourceUtils.java
  presto-orc/src/main/java/io/prestosql/orc/OrcRecordReader.java
  presto-orc/src/main/java/io/prestosql/orc/OrcWriter.java
  presto-orc/src/main/java/io/prestosql/orc/checkpoint/StreamCheckpoint.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/DwrfMetadataReader.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/OrcMetadataReader.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/OrcType.java
Labels: cla-signed

#151 Use passed FeaturesConfig in LocalQueryRunner
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
Labels: cla-signed

#146 Make service principal hostname configurable in Kerberos auth
  presto-docs/src/main/sphinx/security/server.rst
  presto-main/src/main/java/io/prestosql/server/security/KerberosAuthenticator.java
  presto-main/src/main/java/io/prestosql/server/security/KerberosConfig.java
  presto-main/src/test/java/io/prestosql/server/security/TestKerberosConfig.java
Labels: cla-signed

#80 Preserve quotedness for Identifier when formatting Query
  presto-main/src/main/java/io/prestosql/metadata/MetadataUtil.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/sql/TestSqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/DereferenceExpression.java
  presto-parser/src/main/java/io/prestosql/sql/tree/QualifiedName.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
  presto-verifier/src/main/java/io/prestosql/verifier/QueryRewriter.java
  presto-verifier/src/main/java/io/prestosql/verifier/VerifierConfig.java
Labels: cla-signed

#153 Fix inconsistencies in hostname configuration property for Kerberos auth
  presto-docs/src/main/sphinx/security/server.rst
  presto-main/src/main/java/io/prestosql/server/security/KerberosConfig.java
  presto-main/src/test/java/io/prestosql/server/security/TestKerberosConfig.java
Labels: cla-signed

#152 Make Git quite when running tests in Travis
  .travis.yml
Labels: cla-signed

#117 Add CLI option --trace-token to set the trace token
  presto-cli/src/main/java/io/prestosql/cli/ClientOptions.java
  presto-cli/src/test/java/io/prestosql/cli/TestClientOptions.java
Labels: cla-signed

#155 Fix starvation while waiting for minimum number of workers
  presto-main/src/main/java/io/prestosql/execution/ClusterSizeMonitor.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
Labels: cla-signed

#75 Handle S3 empty directories as directories
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#157 Add support for boolean type in EXPLAIN IO
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/QueryExplainer.java
  presto-main/src/main/java/io/prestosql/sql/planner/planPrinter/IoPlanPrinter.java
  presto-tests/src/test/java/io/prestosql/tests/TestLocalQueries.java
Labels: cla-signed

#176 Rename GCS_ACCESS_KEY_CONF
  presto-hive/src/main/java/io/prestosql/plugin/hive/gcs/GcsAccessTokenProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/gcs/GcsConfigurationProvider.java
Labels: cla-signed

#179 Lowercase "and" in documentation title
  presto-docs/src/main/sphinx/language/timestamp.rst
Labels: cla-signed

#178 Improve tests for reserved word identifiers
  presto-main/src/test/java/io/prestosql/sql/TestSqlFormatter.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
Labels: cla-signed

#194 Fix typo in reporting ThriftHiveMetastore#listTablePrivileges
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreStats.java
Labels: cla-signed

#195 Fix char value padding with respect to UTF-16 surrogate pairs
  presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java
  presto-main/src/test/java/io/prestosql/type/TestCharType.java
  presto-spi/src/main/java/io/prestosql/spi/type/CharType.java
Labels: cla-signed

#202 Update presto-maven-plugin version
  pom.xml
Labels: cla-signed

#59 Document LATERAL join
  presto-docs/src/main/sphinx/sql/select.rst
Labels: cla-signed

#192 Add hidden columns to information_schema tables to make Hue happy
  presto-main/src/main/java/io/prestosql/connector/informationSchema/InformationSchemaMetadata.java
  presto-main/src/main/java/io/prestosql/connector/informationSchema/InformationSchemaPageSourceProvider.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataUtil.java
  presto-tests/src/test/java/io/prestosql/tests/TestLocalQueries.java
Labels: cla-signed

#188 Add PushLimitThroughOuterJoin rule
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/QueryCardinalityUtil.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/Patterns.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/LimitMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/Matcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushLimitThroughOuterJoin.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#211 Fix documented default value for query.max-total-memory
  presto-docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed

#215 Implement IS DISTINCT FROM for MongoDB ObjectId
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/ObjectIdFunctions.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#197 Add missing generics in S3SelectRecordCursor
  presto-hive/src/main/java/io/prestosql/plugin/hive/S3SelectRecordCursor.java
Labels: cla-signed

#221 Remove obsolete logo files
  presto-docs/src/main/resources/logo/print/dark/Presto_Logo_PRINT_DarkBG.ai
  presto-docs/src/main/resources/logo/print/light/Presto_Logo_PRINT_LightBG.ai
  presto-docs/src/main/resources/logo/web/fb/Presto_FB_System_Lockups.ai
  presto-docs/src/main/resources/logo/web/fb/black/Presto_FB_Lockups_BLACK_BG-25.svg
  presto-docs/src/main/resources/logo/web/fb/black/Presto_FB_Lockups_BLACK_BG-26.svg
  presto-docs/src/main/resources/logo/web/fb/black/Presto_FB_Lockups_BLACK_BG-27.svg
  presto-docs/src/main/resources/logo/web/fb/black/Presto_FB_Lockups_BLACK_BG-28.svg
  presto-docs/src/main/resources/logo/web/fb/black/Presto_FB_Lockups_BLACK_BG-29.svg
  presto-docs/src/main/resources/logo/web/fb/blue/Presto_FB_Lockups_FB_BLUE_BG-17.svg
  presto-docs/src/main/resources/logo/web/fb/blue/Presto_FB_Lockups_FB_BLUE_BG-18.svg
  presto-docs/src/main/resources/logo/web/fb/blue/Presto_FB_Lockups_FB_BLUE_BG-19.svg
  presto-docs/src/main/resources/logo/web/fb/blue/Presto_FB_Lockups_FB_BLUE_BG-20.svg
  presto-docs/src/main/resources/logo/web/fb/blue/Presto_FB_Lockups_FB_BLUE_BG-21.svg
  presto-docs/src/main/resources/logo/web/fb/dark-blue/Presto_FB_Lockups_DARKBLUE_BG-09.svg
  presto-docs/src/main/resources/logo/web/fb/dark-blue/Presto_FB_Lockups_DARKBLUE_BG-10.svg
  presto-docs/src/main/resources/logo/web/fb/dark-blue/Presto_FB_Lockups_DARKBLUE_BG-11.svg
  presto-docs/src/main/resources/logo/web/fb/dark-blue/Presto_FB_Lockups_DARKBLUE_BG-12.svg
  presto-docs/src/main/resources/logo/web/fb/dark-blue/Presto_FB_Lockups_DARKBLUE_BG-13.svg
  presto-docs/src/main/resources/logo/web/fb/dark-grey/Presto_FB_Lockups_DARKGREY_BG-33.svg
  presto-docs/src/main/resources/logo/web/fb/dark-grey/Presto_FB_Lockups_DARKGREY_BG-34.svg
  presto-docs/src/main/resources/logo/web/fb/dark-grey/Presto_FB_Lockups_DARKGREY_BG-35.svg
  presto-docs/src/main/resources/logo/web/fb/dark-grey/Presto_FB_Lockups_DARKGREY_BG-36.svg
  presto-docs/src/main/resources/logo/web/fb/dark-grey/Presto_FB_Lockups_DARKGREY_BG-37.svg
  presto-docs/src/main/resources/logo/web/fb/light-grey/Presto_FB_Lockups_LIGHTGREY_BG-41.svg
  presto-docs/src/main/resources/logo/web/fb/light-grey/Presto_FB_Lockups_LIGHTGREY_BG-42.svg
  presto-docs/src/main/resources/logo/web/fb/light-grey/Presto_FB_Lockups_LIGHTGREY_BG-43.svg
  presto-docs/src/main/resources/logo/web/fb/light-grey/Presto_FB_Lockups_LIGHTGREY_BG-44.svg
  presto-docs/src/main/resources/logo/web/fb/light-grey/Presto_FB_Lockups_LIGHTGREY_BG-45.svg
  presto-docs/src/main/resources/logo/web/fb/white/Presto_FB_Lockups-01.svg
  presto-docs/src/main/resources/logo/web/fb/white/Presto_FB_Lockups-02.svg
  presto-docs/src/main/resources/logo/web/fb/white/Presto_FB_Lockups-03.svg
  presto-docs/src/main/resources/logo/web/fb/white/Presto_FB_Lockups-04.svg
  presto-docs/src/main/resources/logo/web/fb/white/Presto_FB_Lockups-05.svg
  presto-docs/src/main/resources/logo/web/main/black/Presto_Logo_BlackBG-01.svg
  presto-docs/src/main/resources/logo/web/main/black/Presto_Logo_BlackBG.ai
  presto-docs/src/main/resources/logo/web/main/blue/Presto_Logo_DarkBlueBG.ai
  presto-docs/src/main/resources/logo/web/main/blue/Presto_Logo_DarkBlueBG.svg
  presto-docs/src/main/resources/logo/web/main/white/Presto_Logo_WhiteBG-01.svg
  presto-docs/src/main/resources/logo/web/main/white/Presto_Logo_WhiteBG.ai
  presto-docs/src/main/resources/logo/web/variants/Presto_System_Lockups.ai
  presto-docs/src/main/resources/logo/web/variants/black/Presto_Lockups_BLACK_BG-30.svg
  presto-docs/src/main/resources/logo/web/variants/black/Presto_Lockups_BLACK_BG-31.svg
  presto-docs/src/main/resources/logo/web/variants/black/Presto_Lockups_BLACK_BG-32.svg
  presto-docs/src/main/resources/logo/web/variants/blue/Presto_Lockups_FB_BLUE_BG-22.svg
  presto-docs/src/main/resources/logo/web/variants/blue/Presto_Lockups_FB_BLUE_BG-23.svg
  presto-docs/src/main/resources/logo/web/variants/blue/Presto_Lockups_FB_BLUE_BG-24.svg
  presto-docs/src/main/resources/logo/web/variants/dark-blue/Presto_Lockups_DARKBLUE_BG-14.svg
  presto-docs/src/main/resources/logo/web/variants/dark-blue/Presto_Lockups_DARKBLUE_BG-15.svg
  presto-docs/src/main/resources/logo/web/variants/dark-blue/Presto_Lockups_DARKBLUE_BG-16.svg
  presto-docs/src/main/resources/logo/web/variants/dark-grey/Presto_Lockups_DARKGREY_BG-38.svg
  presto-docs/src/main/resources/logo/web/variants/dark-grey/Presto_Lockups_DARKGREY_BG-39.svg
  presto-docs/src/main/resources/logo/web/variants/dark-grey/Presto_Lockups_DARKGREY_BG-40.svg
  presto-docs/src/main/resources/logo/web/variants/light-grey/Presto_Lockups_LIGHTGREY_BG-46.svg
  presto-docs/src/main/resources/logo/web/variants/light-grey/Presto_Lockups_LIGHTGREY_BG-47.svg
  presto-docs/src/main/resources/logo/web/variants/light-grey/Presto_Lockups_LIGHTGREY_BG-48.svg
  presto-docs/src/main/resources/logo/web/variants/white/Presto_Lockups-06.svg
  presto-docs/src/main/resources/logo/web/variants/white/Presto_Lockups-07.svg
  presto-docs/src/main/resources/logo/web/variants/white/Presto_Lockups-08.svg
Labels: cla-signed

#217 Fix format in checkArgument/checkState calls
  presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/conf/AccumuloTableProperties.java
  presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/Row.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraTokenSplitManager.java
  presto-client/src/main/java/io/prestosql/client/ClientTypeSignature.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/PartitionUpdate.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationFromAnnotationsParser.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationMetadata.java
  presto-main/src/main/java/io/prestosql/operator/project/MergingPageOutput.java
  presto-ml/src/main/java/io/prestosql/plugin/ml/ModelUtils.java
  presto-ml/src/main/java/io/prestosql/plugin/ml/StringClassifierAdapter.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/ParquetReader.java
  presto-spi/src/main/java/io/prestosql/spi/connector/InMemoryRecordSet.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimeZoneKey.java
Labels: cla-signed

#213 Change Server stating state at the end of startup.
  presto-main/src/main/java/io/prestosql/metadata/StaticCatalogStore.java
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
  presto-main/src/main/java/io/prestosql/server/ServerInfoResource.java
Labels: cla-signed

#225 Introduce named constant to clarify intent
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ColumnMapping.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
Labels: cla-signed

#227 Remove double function calls in TestHiveClientConfig
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveClientConfig.java
Labels: cla-signed

#232 Remove import of Builder
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/IonSqlQueryBuilder.java
  presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxMetadata.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/PlanFragment.java
  presto-main/src/test/java/io/prestosql/type/TestMapOperators.java
  presto-orc/src/test/java/io/prestosql/orc/AbstractTestOrcReader.java
  presto-tests/src/test/java/io/prestosql/tests/TestQueryManager.java
Labels: cla-signed

#226 Use predictable collections in classes that participate in planning
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/metadata/TestShardPredicate.java
  presto-spi/src/main/java/io/prestosql/spi/connector/GroupingProperty.java
  presto-spi/src/main/java/io/prestosql/spi/connector/LocalProperty.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/TupleDomain.java
  presto-spi/src/main/java/io/prestosql/spi/statistics/TableStatistics.java
  presto-spi/src/main/java/io/prestosql/spi/statistics/TableStatisticsMetadata.java
Labels: cla-signed

#199 Add test to verify extra credential delivery to ConnectorIdentity
  presto-jdbc/pom.xml
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
Labels: cla-signed

#237 Fail build if one of the invocations of Kudu tests fails
  .travis.yml
Labels: cla-signed

#231 Report offending table name when metadata invalid
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
Labels: cla-signed

#234 Remove exists check when creating a file in S3
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
Labels: cla-signed

#238 Remove incorrect check in QueryBuilder
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
Labels: cla-signed

#242 Replace anonymous classes with lambda in TestDriver
  presto-main/src/test/java/io/prestosql/operator/TestDriver.java
Labels: cla-signed

#250 Fix failure when resolving fully qualified column from view
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#240 Make thrift metastore client retry configurable
  presto-hive/src/main/java/io/prestosql/plugin/hive/RetryDriver.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreModule.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveClient.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftHiveMetastoreConfig.java
Labels: cla-signed

#286 Disallow bucket filter for bucket evolution
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
Labels: correctness

#81 Map PostgreSQL JSON to Presto JSON
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcConnectorFactory.java
  presto-main/src/main/java/io/prestosql/testing/MaterializedResult.java
  presto-postgresql/pom.xml
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-tests/src/main/java/io/prestosql/tests/H2QueryRunner.java
  presto-tests/src/main/java/io/prestosql/tests/TestingPrestoClient.java
Labels: cla-signed

#296 Prefetch Parquet footer to reduce the number of read calls
  presto-parquet/src/main/java/io/prestosql/parquet/reader/MetadataReader.java
Labels: cla-signed

#300 Move ClassLoaderSafeConnectorPageSink to correct package
  presto-spi/src/main/java/io/prestosql/spi/connector/classloader/ClassLoaderSafeConnectorPageSink.java
  presto-spi/src/main/java/io/prestosql/spi/connector/classloader/ClassLoaderSafeConnectorPageSinkProvider.java
  presto-spi/src/test/java/io/prestosql/spi/connector/classloader/TestClassLoaderSafeWrappers.java
Labels: cla-signed

#305 Allow PrestoS3FileSystem to support skipping Glacier files
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/HiveS3Config.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3ConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/MockAmazonS3.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestHiveS3Config.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#252 Skip unsupported types when pushing down in Cassandra
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPartitionManager.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraType.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/CassandraTestingUtils.java
Labels: cla-signed

#294 Remove unused enum
  presto-main/src/main/java/io/prestosql/operator/LookupOuterOperator.java
Labels: cla-signed

#295 Add missing @VisibleForTesting annotation
  presto-main/src/main/java/io/prestosql/operator/exchange/LocalExchange.java
Labels: cla-signed

#310 Limit access to ThriftMetastoreUtil methods
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
Labels: cla-signed

#311 Remove unused isTableOwner method
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/HiveMetastore.java
Labels: cla-signed

#223 Add system.sync_partition_metadata procedure to sync Hive table partitions
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveProcedureModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/SyncPartitionMetadataProcedure.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSyncPartitionMetadata.java
Labels: cla-signed

#306 Remove deprecated datasources config property
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
  presto-main/src/main/java/io/prestosql/server/ServerConfig.java
  presto-main/src/main/java/io/prestosql/server/ServerMainModule.java
  presto-main/src/test/java/io/prestosql/server/TestServerConfig.java
  presto-tests/src/main/java/io/prestosql/tests/DistributedQueryRunner.java
  presto-tests/src/main/java/io/prestosql/tests/StandaloneQueryRunner.java
Labels: cla-signed

#267 Updated RPM installation & removal behavior
  presto-server-rpm/pom.xml
  presto-server-rpm/src/main/rpm/postremove
Labels: cla-signed

#320 Always run full RCFile tests
  presto-rcfile/pom.xml
  presto-rcfile/src/test/java/io/prestosql/rcfile/TestFullRcFileReader.java
Labels: cla-signed

#318 Avoid repeated JsonCodec creation in RemoteNodeState
  presto-main/src/main/java/io/prestosql/metadata/RemoteNodeState.java
Labels: cla-signed

#289 Use case sensitve user and role name for access control
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/ExtendedHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HivePrincipal.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HivePrivilegeInfo.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/UserTableKey.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/PermissionMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveClient.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestRecordingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/UnimplementedHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/InMemoryHiveMetastore.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSqlStandardAccessControlChecks.java
  presto-product-tests/src/main/resources/tempto-configuration.yaml
Labels: cla-signed

#327 Document Cassandra smallint, tinyint and date types
  presto-docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed

#333 Add 304 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-304.rst
Labels: cla-signed

#335 Fix issue link in 304 release notes
  presto-docs/src/main/sphinx/release/release-304.rst
Labels: cla-signed

#344 Use safe concurrent access to local Maven repository
  .mvn/extensions.xml
Labels: cla-signed

#337 Right and outer join should produce unordered global streams
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PropertyDerivations.java
Labels: cla-signed

#325 Remove unused path variable
  presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
Labels: cla-signed, ready to merge

#351 Use correct artifact name for Takari local repository
  .mvn/extensions.xml
Labels: cla-signed

#324 Add Hive file format test for SequenceFile
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
Labels: cla-signed
