Repository trinodb/trino, pull requests merged in 2019-09, with the labels that each got.

#1417 Fix exponential behavior during error reporting
  presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java
  presto-parser/src/main/java/io/prestosql/sql/parser/SqlParser.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java
Labels: RELEASE-BLOCKER, cla-signed

#1394 Fix error reporting for invalid executionPolicy value
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
Labels: cla-signed

#1425 Uppercase SQL keywords in a test class
  presto-main/src/test/java/io/prestosql/sql/TestExpressionInterpreter.java
Labels: cla-signed

#1426 Simplify calling structure
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionTreeUtils.java
  presto-main/src/main/java/io/prestosql/sql/planner/EqualityInference.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEqualityInference.java
Labels: cla-signed

#1427 Remove CLIENT_VERSION Dockerfile arg
  docker/Dockerfile
Labels: cla-signed

#1432 Minor cleanup
  presto-main/src/main/java/io/prestosql/util/DisjointSet.java
Labels: cla-signed

#1436 Upgrade MySQL driver to 5.1.48
  pom.xml
Labels: cla-signed

#1437 Remove duplicate test
  presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
Labels: cla-signed

#1429 CLI will not ignore empty execute statement
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-product-tests/src/main/java/io/prestosql/tests/cli/PrestoCliTests.java
Labels: cla-signed

#1430 Do not enumerate all metadata objects when catalog is wrong
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
  presto-tests/src/test/java/io/prestosql/tests/TestInformationSchemaConnector.java
Labels: cla-signed

#1356 Report table owner when denying DROP TABLE
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
Labels: cla-signed

#1440 Access insert-only tables when HMS compatibility check is enabled
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClient.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#1444 Verify nonnullness using dedicated method
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchClient.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchSplitManager.java
  presto-geospatial-toolkit/src/main/java/io/prestosql/geospatial/serde/JtsGeometrySerde.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/statistics/MetastoreHiveStatisticsProvider.java
  presto-main/src/main/java/io/prestosql/cost/TableScanStatsRule.java
  presto-main/src/main/java/io/prestosql/memory/ClusterMemoryManager.java
  presto-main/src/main/java/io/prestosql/memory/QueryContext.java
  presto-main/src/main/java/io/prestosql/operator/DistinctLimitOperator.java
  presto-main/src/main/java/io/prestosql/operator/LookupJoinOperator.java
  presto-main/src/main/java/io/prestosql/operator/OrderByOperator.java
  presto-main/src/main/java/io/prestosql/operator/PagesRTreeIndex.java
  presto-main/src/main/java/io/prestosql/operator/PagesSpatialIndexSupplier.java
  presto-main/src/main/java/io/prestosql/operator/RowNumberOperator.java
  presto-main/src/main/java/io/prestosql/operator/SpatialJoinOperator.java
  presto-main/src/main/java/io/prestosql/operator/project/PageProcessor.java
  presto-main/src/main/java/io/prestosql/sql/planner/StatisticsAggregationPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/SimplePlanRewriter.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/StatisticAggregationsDescriptor.java
  presto-main/src/main/java/io/prestosql/transaction/InMemoryTransactionManager.java
  presto-main/src/main/java/io/prestosql/util/FastutilSetHelper.java
  presto-memory-context/src/main/java/io/prestosql/memory/context/MemoryTrackingContext.java
  presto-orc/src/main/java/io/prestosql/orc/reader/BooleanStreamReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/ByteStreamReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/DecimalStreamReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/DoubleStreamReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/FloatStreamReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/LongStreamReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/SliceDictionaryStreamReader.java
  presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/AbstractResourceConfigurationManager.java
  presto-spi/src/test/java/io/prestosql/spi/TestPage.java
Labels: cla-signed

#1299 Some preparatory commits for the lazy data loading feature of Information Schema Connector
  presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxQueries.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSourceProvider.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaTable.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaTableHandle.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaTableHandle.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
Labels: cla-signed

#1443 Update gcs jars to v2.0.0
  pom.xml
Labels: cla-signed

#1458 Make BlockBuilder fields final
  presto-spi/src/main/java/io/prestosql/spi/block/ArrayBlockBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/block/ByteArrayBlockBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/block/IntArrayBlockBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/block/LongArrayBlockBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/block/ShortArrayBlockBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/block/VariableWidthBlockBuilder.java
Labels: cla-signed

#1453 Fix bug in Planner
  presto-main/src/main/java/io/prestosql/sql/planner/ReferenceAwareExpressionNodeInliner.java
  presto-main/src/main/java/io/prestosql/sql/planner/SubqueryPlanner.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
Labels: cla-signed

#1479 Remove ununsed jsonType field
  presto-docs/src/main/sphinx/connector/elasticsearch.rst
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchClient.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchColumn.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchColumnHandle.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/test/resources/queryrunner/nested.data.json
  presto-elasticsearch/src/test/resources/queryrunner/test.person.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.customer.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.lineitem.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.nation.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.orders.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.part.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.partsupp.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.region.json
  presto-elasticsearch/src/test/resources/queryrunner/tpch.supplier.json
Labels: cla-signed

#1485 Enable TestAllDatatypesFromHiveConnector.testSelectAllDatatypesAvro
  presto-product-tests/bin/product-tests-suite-1.sh
  presto-product-tests/bin/product-tests-suite-3.sh
  presto-product-tests/src/main/java/io/prestosql/tests/TestGroups.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAllDatatypesFromHiveConnector.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAvroSchemaEvolution.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAvroSchemaUrl.java
Labels: cla-signed

#1442 Allow treating forwarded HTTPS requests over HTTP as secure
  presto-docs/src/main/sphinx/develop/password-authenticator.rst
  presto-docs/src/main/sphinx/security/ldap.rst
  presto-main/src/main/java/io/prestosql/server/security/AuthenticationFilter.java
  presto-main/src/main/java/io/prestosql/server/security/SecurityConfig.java
  presto-main/src/test/java/io/prestosql/server/security/TestSecurityConfig.java
Labels: cla-signed

#1481 Correct jdbc url in TestDbResourceGroupConfig
  presto-resource-group-managers/src/test/java/io/prestosql/plugin/resourcegroups/db/TestDbResourceGroupConfig.java
Labels: cla-signed

#1343 Compatibility fix for Athena Glue
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/converter/GlueToPrestoConverter.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueToPrestoConverter.java
Labels: cla-signed

#1463 Introduce DockerContainer#Builder
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/DockerizedMySqlServer.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestingSqlServer.java
  presto-testing-docker/src/main/java/io/prestosql/testing/docker/DockerContainer.java
Labels: cla-signed

#1363 Enable instance and custom credential provider for glue
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
Labels: cla-signed

#1473 Change default hive metastore refresh interval
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
Labels: cla-signed

#1455 Consume pushed predicate is new table scan domain is equal or wider
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java
Labels: cla-signed

#1415 Decorrelate subqueries with Limit or TopN
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/TransformCorrelatedJoinToJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/TransformExistsApplyToCorrelatedJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PlanNodeDecorrelator.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ScalarAggregationToJoinRewriter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
  presto-main/src/test/java/io/prestosql/sql/query/TestSubqueries.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
Labels: cla-signed

#1420 Reuse node ids from original nodes
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/TransformCorrelatedJoinToJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/TransformExistsApplyToCorrelatedJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PlanNodeDecorrelator.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ScalarAggregationToJoinRewriter.java
Labels: cla-signed, ready to merge

#1494 Fix testConvertTableWithoutTableType
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueToPrestoConverter.java
Labels: cla-signed

#1498 Fix rebase conflict
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#1459 Fix fetching Hadoop configuration in Iceberg
  presto-iceberg/README.md
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HdfsFileIo.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HiveTableOperations.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitManager.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergUtil.java
Labels: cla-signed

#1424 Remove unnecessary builder abstraction
  presto-main/src/main/java/io/prestosql/sql/planner/EffectivePredicateExtractor.java
  presto-main/src/main/java/io/prestosql/sql/planner/EqualityInference.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ReorderJoins.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEqualityInference.java
Labels: cla-signed

#1509 Reuse node ids in PushPredicateIntoTableScan
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
Labels: cla-signed

#1511 Reduce logging verbosity
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
Labels: cla-signed

#1520 Update formatting
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#1514 Continue product tests when a test run fails
  presto-product-tests/bin/product-tests-suite-1.sh
  presto-product-tests/bin/product-tests-suite-2.sh
  presto-product-tests/bin/product-tests-suite-3.sh
  presto-product-tests/bin/product-tests-suite-4.sh
Labels: cla-signed

#1524 Add option to set default catalog and schema
  presto-main/src/main/java/io/prestosql/server/QuerySessionSupplier.java
  presto-main/src/main/java/io/prestosql/sql/SqlEnvironmentConfig.java
  presto-main/src/test/java/io/prestosql/server/TestQuerySessionSupplier.java
  presto-main/src/test/java/io/prestosql/sql/TestSqlEnvironmentConfig.java
  presto-tests/src/test/java/io/prestosql/tests/tpch/TpchQueryRunner.java
Labels: cla-signed

#1525 Offload TEST_OTHER_MODULES
  .travis.yml
Labels: cla-signed

#1523 Wait more before dumping threads in tests
  presto-main/src/test/java/io/prestosql/tests/LogTestDurationListener.java
Labels: cla-signed

#1530 Support backward-compatible Driver classname in JDBC
  presto-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDriver.java
Labels: cla-signed

#1531 Move non-contextual state from Context to field
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionExtractor.java
  presto-main/src/main/java/io/prestosql/sql/planner/SchedulingOrderVisitor.java
Labels: cla-signed

#1486 Remove unused JOL references from JDBC driver
  presto-jdbc/pom.xml
  presto-jdbc/src/main/resources/META-INF/license/LICENSE.jol.txt
Labels: cla-signed

#1536 Pass metadata and types on use
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
Labels: cla-signed

#1538 Place simple predicates at front of expression
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#1537 Rename record_count to row_count in Iceberg partitions table
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTable.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#1540 Fix product tests volume
  presto-product-tests/conf/docker/common/compose-commons.sh
Labels: cla-signed

#1544 Make planner test more robust
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
Labels: cla-signed

#1548 Simplify expression
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#1539 Verify aggregation argument count matches function signature
  presto-geospatial/src/main/java/io/prestosql/plugin/geospatial/SpatialPartitioningAggregateFunction.java
  presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestRewriteSpatialPartitioningAggregation.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/AggregationNode.java
  presto-main/src/test/java/io/prestosql/cost/TestCostCalculator.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestAddIntermediateAggregations.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneCountAggregationOverScalar.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestTransformCorrelatedScalarAggregationToJoin.java
Labels: cla-signed

#1512 Fix multiple entries failure in HashGenerationOptimizer
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
  presto-main/src/test/java/io/prestosql/sql/query/TestPrecomputedHashes.java
Labels: cla-signed

#1553 Fix function type in docs
  presto-docs/src/main/sphinx/functions/geospatial.rst
Labels: cla-signed

#1532 Fix insert-only tables access when HMS compatibility check is enabled
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#1565 Disallow null treatment clause for non-value functions
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/FunctionCallBuilder.java
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ExpressionRewriteRuleSet.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/FunctionCallProvider.java
  presto-parser/src/main/java/io/prestosql/sql/ExpressionFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/ExpressionTreeRewriter.java
  presto-parser/src/main/java/io/prestosql/sql/tree/FunctionCall.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
  presto-spi/src/main/java/io/prestosql/spi/StandardErrorCode.java
Labels: cla-signed

#1566 Fix Search Guard property name in documentation
  presto-docs/src/main/sphinx/connector/elasticsearch.rst
Labels: cla-signed

#1569 Add 319 release notes
  presto-docs/src/main/sphinx/admin/properties.rst
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-319.rst
Labels: cla-signed

#1441 Support Hive metastore impersonation
  .travis.yml
  presto-docs/src/main/sphinx/connector/hive-security.rst
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestSpatialJoins.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/CreateEmptyPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSinkProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/SyncPartitionMetadataProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/HiveIdentity.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HivePageSinkMetadataProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/MetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControlMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/statistics/MetastoreHiveStatisticsProvider.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveLocal.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveBenchmarkQueryRunner.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestRecordingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/UnimplementedHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftHiveMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/statistics/TestMetastoreHiveStatisticsProvider.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HiveTableOperations.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergUtil.java
  presto-product-tests/bin/product-tests-suite-1.sh
  presto-product-tests/bin/product-tests-suite-3.sh
  presto-product-tests/bin/product-tests-suite-5.sh
  presto-product-tests/conf/docker/singlenode-hive-impersonation/compose.sh
  presto-product-tests/conf/docker/singlenode-hive-impersonation/docker-compose.yml
  presto-product-tests/conf/docker/singlenode-kerberos-hive-impersonation/compose.sh
  presto-product-tests/conf/docker/singlenode-kerberos-hive-impersonation/docker-compose.yml
  presto-product-tests/conf/presto/etc/environment-specific-catalogs/singlenode-hive-impersonation/hive.properties
  presto-product-tests/conf/presto/etc/environment-specific-catalogs/singlenode-kerberos-hive-impersonation/hive.properties
  presto-product-tests/src/main/java/io/prestosql/tests/TestGroups.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAvroSchemaEvolution.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAvroSchemaUrl.java
Labels: cla-signed

#1550 Update from Guava to Java streams
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkResultsPrinter.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/NativeCassandraSession.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/StaticMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileFormats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestOrcPageSourceMemoryTracking.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaConnectorConfig.java
  presto-main/src/main/java/io/prestosql/execution/SqlTaskManager.java
  presto-main/src/main/java/io/prestosql/operator/index/IndexLoader.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/RelationType.java
  presto-main/src/main/java/io/prestosql/sql/planner/EqualityInference.java
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ActualProperties.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
  presto-main/src/main/java/io/prestosql/util/Failures.java
  presto-main/src/main/java/io/prestosql/util/GraphvizPrinter.java
  presto-main/src/test/java/io/prestosql/metadata/TestFunctionRegistry.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/OrcFileWriter.java
  presto-redis/src/main/java/io/prestosql/plugin/redis/RedisConnectorConfig.java
  presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
Labels: cla-signed

#1557 Decouple OrcPageSource from HiveColumnHandle
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
Labels: cla-signed, ready to merge

#1380 Update JLine
  pom.xml
  presto-cli/pom.xml
  presto-cli/src/main/java/io/prestosql/cli/AbstractWarningsPrinter.java
  presto-cli/src/main/java/io/prestosql/cli/AlignedTablePrinter.java
  presto-cli/src/main/java/io/prestosql/cli/Completion.java
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-cli/src/main/java/io/prestosql/cli/ConsolePrinter.java
  presto-cli/src/main/java/io/prestosql/cli/InputHighlighter.java
  presto-cli/src/main/java/io/prestosql/cli/InputParser.java
  presto-cli/src/main/java/io/prestosql/cli/InputReader.java
  presto-cli/src/main/java/io/prestosql/cli/KeyReader.java
  presto-cli/src/main/java/io/prestosql/cli/LineReader.java
  presto-cli/src/main/java/io/prestosql/cli/Query.java
  presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java
  presto-cli/src/main/java/io/prestosql/cli/TableNameCompleter.java
  presto-cli/src/test/java/io/prestosql/cli/TestConsoleHistory.java
  presto-cli/src/test/java/io/prestosql/cli/TestInsecureQueryRunner.java
  presto-cli/src/test/java/io/prestosql/cli/TestQueryRunner.java
  presto-cli/src/test/java/io/prestosql/cli/TestTableNameCompleter.java
  presto-product-tests/src/main/java/io/prestosql/tests/cli/PrestoCliProcess.java
Labels: cla-signed

#1574 Update 319 release notes
  presto-docs/src/main/sphinx/release/release-319.rst
Labels: cla-signed

#1560 Recommend IDE configuration
  README.md
Labels: cla-signed

#1578 Prevent open client leak
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#1555 Minor warnings cleanup in StatementAnalyzer
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#1515 Fix predicate pushdown for identity projections
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdown.java
Labels: cla-signed

#1579 Improve Kinesis documentation
  presto-docs/src/main/sphinx/connector.rst
  presto-docs/src/main/sphinx/connector/kinesis.rst
Labels: RELEASE-BLOCKER, cla-signed

#1535 Log full stacktrace in TaskExecutor
  presto-main/src/main/java/io/prestosql/execution/executor/TaskExecutor.java
Labels: cla-signed

#1582 Propagate access control exception from metastore
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed

#1554 Verify LazyBlockLoader not called twice
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rcfile/RcFilePageSource.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/OrcPageSource.java
Labels: cla-signed

#1599 Remove unused method + reduce method visibility
  presto-main/src/main/java/io/prestosql/operator/PartitionedConsumption.java
Labels: cla-signed

#1590 Microoptimizations in CachingHiveMetastore
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
Labels: cla-signed

#1584 Use delegation token for kerberized metastore
  presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/HiveMetastoreAuthentication.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/KerberosHiveMetastoreAuthentication.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/NoHiveMetastoreAuthentication.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/MetastoreLocator.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/StaticMetastoreLocator.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClient.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClientFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/Transport.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClientFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestStaticMetastoreLocator.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestingMetastoreLocator.java
Labels: cla-signed

#1596 Add join type and filter to UnnestNode
  presto-main/src/main/java/io/prestosql/sql/planner/EffectivePredicateExtractor.java
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionExtractor.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/SubqueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ExtractSpatialJoins.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PropertyDerivations.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/StreamPropertyDerivations.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/UnnestNode.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/ValidateDependenciesChecker.java
  presto-main/src/main/java/io/prestosql/util/GraphvizPrinter.java
Labels: cla-signed

#1608 Fix index out of bounds during parser error handling
  presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java
Labels: cla-signed

#1605 Add OrcReaderOptions to simplify OrcReader construction
  presto-hive/src/main/java/io/prestosql/plugin/hive/SortingFileWriter.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/HdfsOrcDataSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcFileWriterFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcReaderConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/TempFileReader.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestOrcPageSourceMemoryTracking.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
  presto-orc/src/main/java/io/prestosql/orc/AbstractOrcDataSource.java
  presto-orc/src/main/java/io/prestosql/orc/FileOrcDataSource.java
  presto-orc/src/main/java/io/prestosql/orc/OrcReader.java
  presto-orc/src/main/java/io/prestosql/orc/OrcReaderOptions.java
  presto-orc/src/main/java/io/prestosql/orc/OrcRecordReader.java
  presto-orc/src/test/java/io/prestosql/orc/BenchmarkOrcDecimalReader.java
  presto-orc/src/test/java/io/prestosql/orc/BenchmarkStreamReaders.java
  presto-orc/src/test/java/io/prestosql/orc/OrcTester.java
  presto-orc/src/test/java/io/prestosql/orc/TestCachingOrcDataSource.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcLz4.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcReaderPositions.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcWriter.java
  presto-orc/src/test/java/io/prestosql/orc/TestReadBloomFilter.java
  presto-orc/src/test/java/io/prestosql/orc/TestStructStreamReader.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorPageSourceProvider.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/OrcStorageManager.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/ReaderAttributes.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/StorageManager.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/StorageManagerConfig.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/StorageModule.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/organization/ShardCompactor.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/storage/OrcTestingUtil.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/storage/TestOrcStorageManager.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/storage/organization/TestShardCompactor.java
Labels: cla-signed

#1595 Fix misleading 'Table not found' message
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#1611 Remove duplicate configuration
  presto-hive-hadoop2/bin/run_hive_tests.sh
Labels: cla-signed

#1619 Improve catalog creation methods name
  presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
  presto-main/src/main/java/io/prestosql/connector/system/SystemConnectorModule.java
  presto-main/src/main/java/io/prestosql/metadata/StaticCatalogStore.java
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
Labels: cla-signed

#1618 Deprecate SqlTimeWithTimeZone constructor with j.u.TimeZone
  presto-spi/src/main/java/io/prestosql/spi/type/SqlTimeWithTimeZone.java
Labels: cla-signed

#1621 Remove duplicate binding in Iceberg
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergModule.java
Labels: cla-signed

#1617 Remove redundant `else`
  presto-main/src/main/java/io/prestosql/type/TimeOperators.java
  presto-main/src/main/java/io/prestosql/type/TimeWithTimeZoneOperators.java
  presto-main/src/main/java/io/prestosql/type/TimestampOperators.java
  presto-main/src/main/java/io/prestosql/type/TimestampWithTimeZoneOperators.java
Labels: cla-signed

#1616 Update docker images to 20
  presto-product-tests/conf/product-tests-defaults.sh
Labels: cla-signed

#1623 Rename ThriftHiveMetastoreConfig to ThriftMetastoreConfig
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClientFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreModule.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
Labels: cla-signed

#1552 Decouple ParquetPageSource from HiveColumnHandle
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetColumnIOConverter.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSourceProvider.java
Labels: cla-signed
