Repository trinodb/trino, pull requests merged in 2020-09, with the labels that each got.

#4956 Add support for TopN to cost
  presto-main/src/main/java/io/prestosql/cost/StatsCalculatorModule.java
  presto-main/src/main/java/io/prestosql/cost/TopNStatsRule.java
  presto-main/src/test/java/io/prestosql/cost/TestTopNStatsRule.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#5032 Update product tests docs
  presto-product-tests/README.md
Labels: cla-signed

#4994 Fix IndexOutOfBounds non-nested-loop joins with no columns on build side
  presto-main/src/main/java/io/prestosql/operator/PagesIndex.java
  presto-main/src/test/java/io/prestosql/operator/TestPagesIndex.java
Labels: cla-signed

#4961 Fix punctuation in the Prometheus documentation
  presto-docs/src/main/sphinx/connector/prometheus.rst
Labels: cla-signed

#4931 Allow to use cluster default role in hive S3 Security Mapping
  presto-docs/src/main/sphinx/connector/hive-s3.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/S3SecurityMapping.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/S3SecurityMappingConfigurationProvider.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestS3SecurityMapping.java
  presto-hive/src/test/resources/io/prestosql/plugin/hive/s3/security-mapping-with-fallback-to-cluster-default.json
  presto-hive/src/test/resources/io/prestosql/plugin/hive/s3/security-mapping-without-fallback.json
  presto-hive/src/test/resources/io/prestosql/plugin/hive/s3/security-mapping.json
Labels: cla-signed, docs

#5055 Remove unused method
  presto-main/src/main/java/io/prestosql/server/remotetask/ContinuousTaskStatusFetcher.java
Labels: cla-signed

#4306 Allow custom keystore and truststore types
  presto-cli/src/main/java/io/prestosql/cli/ClientOptions.java
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-cli/src/main/java/io/prestosql/cli/QueryRunner.java
  presto-cli/src/test/java/io/prestosql/cli/TestQueryRunner.java
  presto-client/src/main/java/io/prestosql/client/OkHttpUtil.java
  presto-docs/src/main/sphinx/installation/jdbc.rst
  presto-jdbc/src/main/java/io/prestosql/jdbc/ConnectionProperties.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriverUri.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverUri.java
  presto-main/src/test/java/io/prestosql/server/security/TestResourceSecurity.java
  presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java
Labels: cla-signed

#4855 Added documentation for Salesforce authentication password plugin.
  presto-docs/src/main/sphinx/security.rst
  presto-docs/src/main/sphinx/security/salesforce.rst
Labels: cla-signed

#5004 Added new timezone configuration properties for the Hive connector.
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#5058 Remove tested version information from user docs
  presto-docs/src/main/sphinx/connector/postgresql.rst
Labels: cla-signed, docs

#5057 TupleDomain small improvements
  presto-spi/src/main/java/io/prestosql/spi/predicate/TupleDomain.java
Labels: cla-signed

#4972 Standardize on "classpath" spelling.
  presto-docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#4904 Add Output Formats section to command line doc.
  presto-docs/src/main/sphinx/installation/cli.rst
Labels: docs

#5067 Remove redundant 'throws' clause from TestOrcPageSourceFactory
  presto-hive/src/test/java/io/prestosql/plugin/hive/orc/TestOrcPageSourceFactory.java
Labels: cla-signed

#5070 Ensure transaction cleanup does not fail in transitionToFailed
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
Labels: cla-signed

#5063 Allow to suppress testng checks
  presto-testng-services/src/main/java/io/prestosql/testng/services/ReportUnannotatedMethods.java
  presto-testng-services/src/test/java/io/prestosql/testng/services/TestReportUnannotatedMethods.java
Labels: cla-signed

#5042 Restore setting HADOOP_PRESTO_INIT_SCRIPT
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/configs/ConfigEnvBased.java
Labels: cla-signed

#5074 tablesample handling code cleanup
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-tests/src/test/java/io/prestosql/tests/TestTablesample.java
Labels: cla-signed

#5077 Allow to override product tests launcher
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/Launcher.java
Labels: cla-signed

#4996 Attach product test execution to existing environment
  presto-product-tests-launcher/pom.xml
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/testcontainers/ExistingNetwork.java
Labels: cla-signed

#5080 Update development guidelines
  DEVELOPMENT.md
Labels: cla-signed

#5083 Fix parquet predicate pushdown for INT96 timestamp values
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
  presto-parquet/src/test/java/io/prestosql/parquet/TestTupleDomainParquetPredicate.java
Labels: cla-signed

#5065 Update PostgreSQL versions used in tests
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSetTimezone.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodePostgresql.java
Labels: cla-signed

#5076 Load native libraries in createKerberosHadoopAuthentication
  presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/KerberosHadoopAuthentication.java
Labels: cla-signed

#5084 Configure product tests
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/Launcher.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteDescribe.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
Labels: cla-signed

#5082 Do not translate epoch to local when reading Parquet timestamp
  presto-parquet/src/main/java/io/prestosql/parquet/reader/Int64TimestampMillisColumnReader.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/PrimitiveColumnReader.java
Labels: cla-signed

#5096 Add missing negation in a comment
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#5095 Add missing config description for GlueHiveMetastoreConfig
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
Labels: cla-signed

#5079 Set X-Presto-User header to retrieve CPU usage
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java
Labels: cla-signed

#5093 Fix run-launcher env list
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentModule.java
Labels: cla-signed

#5097 Simplify structure of DeleteDeltaInfo
  presto-hive/src/main/java/io/prestosql/plugin/hive/AcidInfo.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcDeletedRows.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveSplit.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/orc/TestOrcDeletedRows.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/orc/TestOrcPageSourceFactory.java
Labels: cla-signed

#5091 Remove unused parameter
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
Labels: cla-signed

#5069 Simplify fetching max file descriptor count
  presto-main/src/main/java/io/prestosql/server/PrestoSystemRequirements.java
Labels: cla-signed

#5107 Remove limitation around impersonation and access rights
  presto-docs/src/main/sphinx/connector/hive-caching.rst
Labels: cla-signed, docs

#4537 Iceberg connector documentation
  presto-docs/src/main/sphinx/connector.rst
  presto-docs/src/main/sphinx/connector/iceberg.rst
  presto-iceberg/README.md
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
Labels: cla-signed, docs

#5108 Remove unused WILDCARD_EXPRESSION
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed

#5087 Fix compiler error for lambda parameter with non-letter
  presto-main/src/main/java/io/prestosql/sql/gen/BytecodeUtils.java
  presto-main/src/main/java/io/prestosql/sql/gen/LambdaBytecodeGenerator.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestLambdaExpression.java
  presto-main/src/test/java/io/prestosql/sql/query/TestLambdaExpressions.java
Labels: cla-signed

#5100 Update hive catalog configuration for development
  presto-server-main/etc/catalog/hive.properties
Labels: cla-signed

#5115 Update caching limitations
  presto-docs/src/main/sphinx/connector/hive-caching.rst
Labels: cla-signed

#5098 Update reference link
  presto-docs/src/main/sphinx/language.rst
Labels: cla-signed

#5118 Enable Cassandra insert test
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java
Labels: cla-signed

#5105 Add support for precision for TIMESTAMP W/TZ in Postgresql type mapping
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/TypeUtils.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#5119 Cleanup around Oracle type mapping tests
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleTypeMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#5125 Fix Atop predicate pushdown
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopSplitManager.java
  presto-atop/src/test/java/io/prestosql/plugin/atop/TestAtopSmoke.java
Labels: cla-signed

#4925 Resolving Inconsistent error with DESCRIBE
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveSchema.java
Labels: cla-signed

#5113 Remove incorrect default conversion
  presto-record-decoder/src/main/java/io/prestosql/decoder/json/AbstractDateTimeJsonValueProvider.java
Labels: cla-signed

#5099 Make DynamicFilter future resilient to cancel
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFiltersCollector.java
  presto-main/src/test/java/io/prestosql/server/TestDynamicFilterService.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
Labels: cla-signed

#5017 Dynamic filtering for semi-joins: execution and testing
  presto-main/src/main/java/io/prestosql/operator/JoinUtils.java
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
  presto-tests/src/test/java/io/prestosql/execution/AbstractCoordinatorDynamicFilteringTest.java
  presto-tests/src/test/java/io/prestosql/execution/TestLazyCoordinatorDynamicFiltering.java
Labels: cla-signed

#5129 Remove not applicable entry from release notes
  presto-docs/src/main/sphinx/release/release-341.md
Labels: cla-signed

#5114 Update some usages of deprecated TIMESTAMP_WITH_TIME_ZONE
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopTable.java
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopTableHandle.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryResultPageSource.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryType.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraType.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveColumnHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSource.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveRecordCursor.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HistoryTable.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/test/java/io/prestosql/type/TestDateTimeOperators.java
  presto-main/src/test/java/io/prestosql/type/TestTimestamp.java
  presto-main/src/test/java/io/prestosql/type/TestTimestampWithTimeZone.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSink.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSource.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestObjectIdFunctions.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/OracleDataTypes.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-record-decoder/src/main/java/io/prestosql/decoder/json/AbstractDateTimeJsonValueProvider.java
Labels: cla-signed

#5043 Add DynamicFilter#isAwaitable method
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFiltersCollector.java
  presto-main/src/test/java/io/prestosql/server/TestDynamicFilterService.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
  presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryPageSourceProvider.java
  presto-spi/src/main/java/io/prestosql/spi/connector/DynamicFilter.java
  presto-tests/src/test/java/io/prestosql/execution/TestLazyCoordinatorDynamicFiltering.java
Labels: cla-signed

#5134 Wait for final QueryInfo before using in test
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#5133 Make TestOracleTypeMapping extensible
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/AbstractTestOracleTypeMapping.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleTypeMapping.java
Labels: cla-signed

#5140 Fix JDBC driver compatibility regarding TIME WITH TIME ZONE
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
Labels: cla-signed

#5142 Fix performance regression when hive SerDe doesn't prefer Writables
  presto-hive/src/main/java/io/prestosql/plugin/hive/GenericHiveRecordCursor.java
Labels: cla-signed

#5138 Remove redundant supression
  presto-array/src/main/java/io/prestosql/array/BigArrays.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/groupby/AggregationTestInput.java
Labels: cla-signed

#5145 Add timestamp timezone configuration properties for HDP3 environment
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/configs/ConfigHdp3.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hadoop-presto-init-hdp3.sh
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAllDatatypesFromHiveConnector.java
Labels: cla-signed

#4846 Allow INSERT null for SQL Server varbinary type
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerTypeMapping.java
Labels: cla-signed

#5152 Use static imports for Preconditions
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed, maintenance

#5166 Fix environment startup retries
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environments.java
Labels: cla-signed

#5161 Remove duplicate tpc-ds queries
  presto-benchto-benchmarks/src/main/resources/benchmarks/presto/tpcds.yaml
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q14.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q14_2.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q23.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q23_2.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q24.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q24_2.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q39.sql
  presto-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q39_1.sql
  presto-benchto-benchmarks/src/test/java/io/prestosql/sql/planner/TestTpcdsCostBasedPlan.java
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q24.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q24_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q39.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q39_2.plan.txt
Labels: cla-signed

#5148 Add tests for semi-join dynamic filtering in hive
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDynamicPartitionPruning.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#5174 Change dynamic partition pruning tests to avoid failures
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDynamicPartitionPruning.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#5175 Fix misuse of HashSet::new
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
Labels: cla-signed

#5090 Use task status version for task status long polling notifications
  presto-client/src/main/java/io/prestosql/client/PrestoHeaders.java
  presto-main/src/main/java/io/prestosql/execution/SqlTask.java
  presto-main/src/main/java/io/prestosql/execution/SqlTaskManager.java
  presto-main/src/main/java/io/prestosql/execution/TaskManager.java
  presto-main/src/main/java/io/prestosql/execution/TaskStatus.java
  presto-main/src/main/java/io/prestosql/server/TaskResource.java
  presto-main/src/main/java/io/prestosql/server/remotetask/ContinuousTaskStatusFetcher.java
  presto-main/src/test/java/io/prestosql/execution/TestSqlTask.java
  presto-main/src/test/java/io/prestosql/execution/TestSqlTaskManager.java
  presto-main/src/test/java/io/prestosql/server/remotetask/TestHttpRemoteTask.java
Labels: cla-signed

#4995 Create temporary tables in mysql without key constraints
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
Labels: cla-signed

#5184 Remove flaky assertions in DF test
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDynamicPartitionPruning.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#5186 Fix flaky TestSqlTask tests
  presto-main/src/test/java/io/prestosql/execution/TestSqlTask.java
Labels: cla-signed

#5187 Hide setting HDFS user/group behind a toggle
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsEnvironment.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHdfsConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveLocationService.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
Labels: cla-signed

#5193 Update docker images to version 33
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentDefaults.java
Labels: cla-signed

#5141 Cleanup join distribution code
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q44.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q64.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q09.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q21.plan.txt
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineJoinDistributionType.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestDetermineSemiJoinDistributionType.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#3871 Implement collection of min/max values in DynamicFilterSourceOperator
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDynamicPartitionPruning.java
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/operator/DynamicFilterSourceOperator.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/test/java/io/prestosql/block/BlockAssertions.java
  presto-main/src/test/java/io/prestosql/operator/BenchmarkDynamicFilterSourceOperator.java
  presto-main/src/test/java/io/prestosql/operator/TestDynamicFilterSourceOperator.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
Labels: cla-signed

#3644 Document support for insecure LDAP connection
  presto-docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed

#5052 Add support for ABFS OAuth 2 authentication
  .github/workflows/ci.yml
  presto-hive-hadoop2/bin/run_hive_abfs_oauth_tests.sh
  presto-hive-hadoop2/conf/files/core-site.xml.abfs-oauth-template
  presto-hive-hadoop2/pom.xml
  presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveFileSystemAbfsOAuth.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/azure/HiveAzureConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/azure/PrestoAzureConfigurationInitializer.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/azure/TestHiveAzureConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/azure/TestPrestoAzureConfigurationInitializer.java
Labels: cla-signed, needs-docs

#5206 Require project version to be known
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/Launcher.java
Labels: cla-signed

#5200 Deprecate isCharType, isVarcharType
  presto-spi/src/main/java/io/prestosql/spi/type/Chars.java
  presto-spi/src/main/java/io/prestosql/spi/type/Varchars.java
Labels: cla-signed, maintenance

#5154 More Oracle integration tests
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/BaseOracleIntegrationSmokeTest.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleIntegrationSmokeTest.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOraclePoolIntegrationSmokeTest.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestSynonym.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestView.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
Labels: cla-signed

#5213 Deprecate isVarbinaryType
  presto-spi/src/main/java/io/prestosql/spi/type/VarbinaryType.java
Labels: cla-signed

#5215 Reuse Marker object
  presto-spi/src/main/java/io/prestosql/spi/predicate/Range.java
Labels: cla-signed

#5216 Validate char/varchar values read in JDBC connectors
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
Labels: cla-signed

#5221 Fix using of session parameter in test
  presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java
Labels: cla-signed

#5229 Update deprecation notices
  presto-spi/src/main/java/io/prestosql/spi/type/TimeType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimeWithTimeZoneType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimestampType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimestampWithTimeZoneType.java
Labels: cla-signed

#5220 Reduce size of serialized Range (and TupleDomain)
  presto-main/src/main/java/io/prestosql/server/RangeJsonSerde.java
  presto-main/src/main/java/io/prestosql/server/ServerMainModule.java
  presto-main/src/test/java/io/prestosql/server/TestRangeJsonSerde.java
Labels: cla-signed

#5236 Provide versionless link to server in product tests
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/run-presto.sh
Labels: cla-signed

#5247 Remove commented out code
  presto-prometheus/src/main/java/io/prestosql/plugin/prometheus/PrometheusRecordCursor.java
Labels: cla-signed

#5250 Update documentation for time and timestamp types
  presto-docs/src/main/sphinx/language/types.rst
Labels: cla-signed

#5239 Close postgres test resources in order
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlDistributedQueries.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-testing/pom.xml
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#5245 Document sqlserver aggregate function pushdown
  presto-docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#5048 Add from_iso8601_timestamp_nanos operation
  presto-docs/src/main/sphinx/functions/datetime.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java
Labels: cla-signed, needs-docs

#5226 Update to Avro 1.9.2
  pom.xml
Labels: cla-signed

#5060 Support Domain Expressions for GlueHiveMetastore
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/MetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueExpressionUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveLocal.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/PartitionFilterBuilder.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueExpressionUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed

#5274 Remove FloatingPointEquality warning no longer valid
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionInterpreter.java
Labels: cla-signed

#5249 Test RDBMS connectos large IN capabilities
  presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlIntegrationSmokeTest.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlIntegrationSmokeTest.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
Labels: cla-signed

#5237 Update task status on broadcast buffer blocking
  presto-main/src/main/java/io/prestosql/execution/SqlTask.java
  presto-main/src/main/java/io/prestosql/execution/buffer/BroadcastOutputBuffer.java
  presto-main/src/main/java/io/prestosql/execution/buffer/LazyOutputBuffer.java
  presto-main/src/test/java/io/prestosql/execution/MockRemoteTaskFactory.java
  presto-main/src/test/java/io/prestosql/execution/buffer/TestBroadcastOutputBuffer.java
Labels: cla-signed

#5266 Fix property value in documentation
  presto-docs/src/main/sphinx/optimizer/cost-based-optimizations.rst
Labels: cla-signed, docs

#5248 Simplify dynamic filter matching in plans
  presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdown.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/DynamicFilterMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/JoinMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
Labels: cla-signed

#5243 Propagate replicated dynamic filters by single task
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilterConsumer.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFilterConsumer.java
Labels: cla-signed

#5254 Allow to pass AutoCloseable to closeAfterClass
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#5264 Test LIMIT pushdown
  presto-druid/pom.xml
  presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidIntegrationSmokeTest.java
  presto-memsql/pom.xml
  presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlIntegrationSmokeTest.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/BaseMySqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
Labels: cla-signed, maintenance

#5273 Match Iceberg transforms for negative epoch values
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTransforms.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestPartitionTransforms.java
Labels: cla-signed

#5269 Coerce strings to boolean
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/BooleanDecoder.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#5282 Remove unused field from IcebergSplitManager
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitManager.java
Labels: cla-signed

#5277 Remove unused method
  presto-main/src/main/java/io/prestosql/testing/MaterializedResult.java
Labels: cla-signed

#5285 Update docs for variable precision timestamp support in Hive connector
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#5286 Add docs for ABFS OAuth support
  presto-docs/src/main/sphinx/connector/hive-azure.rst
Labels: cla-signed, docs

#5163 Add WITH RECURSIVE documentation
  presto-docs/src/main/sphinx/sql/select.rst
Labels: cla-signed, docs

#5066 Adding ulimits guidance to deployment doc
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#5214 Fix standard mapping for char exceeding allowed length
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#5267 Add LongTimestamp#toString
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestamp.java
  presto-spi/src/test/java/io/prestosql/spi/type/TestLongTimestamp.java
Labels: cla-signed

#5291 Fix flaky test
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#5296 Report offending precision when invalid
  presto-main/src/test/java/io/prestosql/operator/scalar/time/TestTime.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestamp.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timetz/TestTimeWithTimeZone.java
  presto-main/src/test/java/io/prestosql/type/TestDecimalOperators.java
  presto-main/src/test/java/io/prestosql/type/TestDecimalParametricType.java
  presto-spi/src/main/java/io/prestosql/spi/type/DecimalType.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongDecimalType.java
  presto-spi/src/main/java/io/prestosql/spi/type/ShortDecimalType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimeType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimeWithTimeZoneType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimestampType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimestampWithTimeZoneType.java
Labels: cla-signed

#5297 Fix accessing bucketed table with timestamp column
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketing.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#5287 Use ordinary compare for picos value
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestamp.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestampType.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestampWithTimeZone.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestampWithTimeZoneType.java
Labels: cla-signed

#5301 Add 343 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-343.md
Labels: cla-signed

#5305 Add docs for additional aggregate pushdown functions for sql server
  presto-docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed

#5304 Fix logger declaration
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentProvider.java
Labels: cla-signed

#5309 Clarify use of timezone in tests
  presto-main/src/test/java/io/prestosql/operator/scalar/time/TestTime.java
Labels: cla-signed

#5054 Add murmur3_hash function
  presto-docs/src/main/sphinx/functions/binary.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestVarbinaryFunctions.java
Labels: cla-signed

#5308 Use non-deprecated createPageSource() in HivePageSourceProvider
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
Labels: cla-signed

#5289 Fix potential deadlock when HttpPageBufferClient exceeds memory limit
  presto-main/src/main/java/io/prestosql/operator/HttpPageBufferClient.java
  presto-main/src/test/java/io/prestosql/operator/TestHttpPageBufferClient.java
Labels: cla-signed

#5311 Fix rounding in long timestamp to long timestamp cast
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamp/TimestampToTimestampCast.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestamp.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestamp.java
Labels: cla-signed

#5322 Revert "Use non-deprecated createPageSource() in HivePageSourceProvider"
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
Labels: cla-signed

#5324 Document @SqlNullable
  presto-spi/src/main/java/io/prestosql/spi/function/SqlNullable.java
Labels: cla-signed

#5307 Add support for setting column comment in PostgreSQL
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/JdbcClientStats.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Labels: cla-signed

#5314 Mark ACID tests as Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#5260 Clamp BackgroundHiveSplitLoader concurrency to usable parallelism
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java
Labels: cla-signed

#5338 Use non-deprecated createPageSource() in HivePageSourceProvider
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
Labels: cla-signed

#5325 Rename and expose method in BaseJdbcClient
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#5224 Allow to use camel case environment name
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentConfigFactory.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentFactory.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environments.java
  presto-product-tests-launcher/src/test/java/io/prestosql/tests/product/launcher/env/TestEnvironments.java
Labels: cla-signed

#5341 Make number of DynamicFilterService threads configurable
  presto-main/src/main/java/io/prestosql/execution/DynamicFilterConfig.java
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/test/java/io/prestosql/execution/TestDynamicFilterConfig.java
  presto-main/src/test/java/io/prestosql/execution/TestSqlStageExecution.java
  presto-main/src/test/java/io/prestosql/execution/scheduler/TestSourcePartitionedScheduler.java
  presto-main/src/test/java/io/prestosql/server/remotetask/TestHttpRemoteTask.java
Labels: cla-signed

#5344 Cancel scheduled futures used for container statistics reporting
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentListener.java
Labels: cla-signed

#5340 Do not simplify dynamic filters when these are fetched by coordinator
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDynamicPartitionPruning.java
  presto-main/src/main/java/io/prestosql/execution/DynamicFilterConfig.java
  presto-main/src/main/java/io/prestosql/execution/DynamicFiltersCollector.java
  presto-main/src/test/java/io/prestosql/execution/TestDynamicFilterConfig.java
  presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java
Labels: cla-signed

#5358 Add main() to PhoenixQueryRunner
  presto-phoenix/pom.xml
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/PhoenixQueryRunner.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixIntegrationSmokeTest.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixSqlTypeMapping.java
Labels: cla-signed
