Repository trinodb/trino, pull requests merged in 2020-04, with the labels that each got.

#3286 Add Project-off rule for EnforceSingleRowNode
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneEnforceSingleRowColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneEnforceSingleRowColumns.java
Labels: cla-signed

#2841 Add Project-off rule for AssignUniqueId
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneAssignUniqueIdColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneAssignUniqueIdColumns.java
Labels: cla-signed

#3287 Fix symbol pruning in set operation nodes
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
Labels: cla-signed

#3290 Add access control check while listing views
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSource.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataListing.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
Labels: cla-signed

#3239 Add support for Glue endpoint URL
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
Labels: cla-signed

#3273 Remove unused bindings from IcebergModule
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergModule.java
Labels: cla-signed

#3301 Add extension point for Glue custom request headers
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreModule.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed

#3308 Avoid calling toIntExact on int
  presto-main/src/main/java/io/prestosql/execution/buffer/PagesSerdeUtil.java
  presto-main/src/main/java/io/prestosql/sql/gen/InCodeGenerator.java
  presto-main/src/main/java/io/prestosql/util/FastutilSetHelper.java
  presto-orc/src/main/java/io/prestosql/orc/OrcRecordReader.java
  presto-orc/src/main/java/io/prestosql/orc/StripeReader.java
  presto-orc/src/main/java/io/prestosql/orc/stream/AbstractDiskOrcDataReader.java
  presto-orc/src/main/java/io/prestosql/orc/stream/UncompressedOrcChunkLoader.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/PageReader.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/ParquetReader.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/organization/TemporalFunction.java
  presto-rcfile/src/test/java/io/prestosql/rcfile/RcFileTester.java
Labels: cla-signed

#3307 Use type adequate to payload
  presto-main/src/main/java/io/prestosql/server/PagesResponseWriter.java
  presto-main/src/main/java/io/prestosql/server/TaskResource.java
Labels: cla-signed

#3318 Capitalize title for Group Provider
  presto-docs/src/main/sphinx/develop/group-provider.rst
Labels: cla-signed

#3319 Add ref anchors
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#3315 Remove redundant Kudu tests
  .github/workflows/module-tests.yml
Labels: cla-signed

#3327 Free disk space in checks workflow
  .github/workflows/checks.yml
Labels: cla-signed

#3335 Test configuration cleanup
  presto-main/etc/log.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/tpch.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/log.properties
Labels: cla-signed, maintenance

#3339 Handle empty and arbitrary slices in Parquet reader
  presto-parquet/src/main/java/io/prestosql/parquet/dictionary/BinaryDictionary.java
Labels: RELEASE-BLOCKER, bug, cla-signed

#3332 Report field name when decoding Elasticsearch value fails
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/ArrayDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/BigintDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/BooleanDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/DoubleDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/IntegerDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/RealDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/RowDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/SmallintDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/TimestampDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/TinyintDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/VarbinaryDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/VarcharDecoder.java
Labels: cla-signed

#3331 Add instructions on how to start Elasticsearch
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/ElasticsearchQueryRunner.java
Labels: cla-signed

#3305 Call applyProjection during table scan column pruning
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneTableScanColumns.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/BasePlanTest.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneTableScanColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestEliminateSorts.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestMergeWindows.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestSetFlatteningOptimizer.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/TestThriftProjectionPushdown.java
Labels: cla-signed

#3343 Use unique table name in test
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3341 Add session token support to PrestoS3FileSystem
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#3342 Plugin class loader
  presto-main/src/main/java/io/prestosql/server/PluginClassLoader.java
Labels: cla-signed

#3346 Use unique table names in distributed tests
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#2975 Reduce instance size and block copies in Page class
  presto-spi/src/main/java/io/prestosql/spi/Page.java
  presto-spi/src/main/java/io/prestosql/spi/PageBuilder.java
Labels: cla-signed

#3349 Update outdated comment
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#3360 Add main() to PostgreSqlQueryRunner
  presto-postgresql/pom.xml
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/PostgreSqlQueryRunner.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlDistributedQueries.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#3363 Cleanup toString for JdbcColumnHandle
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcColumnHandle.java
Labels: cla-signed

#3367 Skip setting admin role if it's already enabled
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed

#3359 Bind NodeManager and VersionEmbedder in base JDBC connector
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcConnectorFactory.java
Labels: cla-signed

#3371 Remove default for hive.cache.location
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixConfig.java
Labels: cla-signed

#3252 Add tip about reverse parameters for date diff
  presto-docs/src/main/sphinx/functions/datetime.rst
  presto-docs/src/main/sphinx/migration/from-hive.rst
Labels: cla-signed

#3347 Add to Elastic connector IpAddress field
  presto-docs/src/main/sphinx/connector/elasticsearch.rst
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/IpAddressDecoder.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
  presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Labels: cla-signed

#3249 Add info about login page
  presto-docs/src/main/sphinx/admin/properties.rst
  presto-docs/src/main/sphinx/admin/web-interface.rst
Labels: cla-signed

#3111 Add note about parallel reads from topics
  presto-docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed

#3365 Merge CI suites into one
  .github/workflows/checks.yml
  .github/workflows/ci-tests.yml
  .github/workflows/product-tests.yml
Labels: cla-signed

#3366 Disallow reading from Delta Lake tables in hive connector
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveDeltaLakeTable.java
Labels: cla-signed

#3351 Allow using configured S3 credentials with IAM role
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#3288 Fix incorrect pushdown in Kudu when value can be NULL.
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduDistributedQueries.java
Labels: cla-signed

#3323 Add SHOW CREATE TABLE test
  presto-accumulo/pom.xml
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloIntegrationSmokeTest.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraIntegrationSmokeTest.java
  presto-elasticsearch/pom.xml
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
  presto-kudu/pom.xml
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/AbstractKuduIntegrationSmokeTest.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlIntegrationSmokeTest.java
  presto-phoenix/pom.xml
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixIntegrationSmokeTest.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTestBucketed.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Labels: cla-signed, maintenance, test

#3357 Allow to modify Presto in product tests
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/run-presto.sh
Labels: cla-signed

#3309 Remove launcher help output from documentation
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed

#3382 Cleanup usages of Iceberg schema and table properties
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSchemaProperties.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergTableProperties.java
Labels: cla-signed

#3372 Update to Airlift 0.195
  pom.xml
Labels: cla-signed

#3362 Add 332 release notes
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-332.rst
Labels: cla-signed

#3390 Ensure OrcDataSink is closed when flush fails
  presto-orc/src/main/java/io/prestosql/orc/OrcDataSink.java
  presto-orc/src/main/java/io/prestosql/orc/OrcWriter.java
Labels: cla-signed

#3218 Fix planning failure when lambda expressions are repeated
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionSymbolInliner.java
  presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
  presto-main/src/test/java/io/prestosql/sql/query/TestLambdaExpressions.java
Labels: cla-signed

#3402 Release notes fixes
  presto-docs/src/main/sphinx/release/release-332.rst
Labels: cla-signed

#3178 Add sample node output symbols pruning rule
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneSampleColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneSampleColumns.java
Labels: cla-signed

#3409 Depend connectionUrl on JdbcIdentity
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/DriverConnectionFactory.java
Labels: cla-signed

#3408 Fix NPE in pushdown to NULL expression
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionInterpreter.java
  presto-main/src/test/java/io/prestosql/sql/query/TestExpressions.java
Labels: cla-signed

#3392 Add starts_with function
  presto-docs/src/main/sphinx/functions/list.rst
  presto-docs/src/main/sphinx/functions/string.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java
Labels: cla-signed

#3424 Fix missing cast in generated serialize of StateCompiler
  presto-main/src/main/java/io/prestosql/sql/gen/SqlTypeBytecodeExpression.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/minmaxby/TestMinMaxByAggregation.java
Labels: RELEASE-BLOCKER, bug, cla-signed

#3421 Enable tests to construct new LDAP object definitions
  presto-product-tests/src/main/java/io/prestosql/tests/ImmutableLdapObjectDefinitions.java
Labels: cla-signed

#3350 Cleanup in PushProjectionThroughExchange rule
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushProjectionThroughExchange.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushProjectionThroughExchange.java
Labels: cla-signed

#3413 Optimize TupleDomain.columnWiseUnion during dynamic filtering partition collection
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilter.java
Labels: cla-signed

#2705 Session property for setting source tasks count to be used while plan…
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/cost/CostCalculatorUsingExchanges.java
  presto-main/src/main/java/io/prestosql/cost/CostCalculatorWithEstimatedExchanges.java
  presto-main/src/main/java/io/prestosql/cost/TaskCountEstimator.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineJoinDistributionType.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
Labels: cla-signed

#2935 Change the way mongo connector infers schema for nested bson docs
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#3355 Use listCollections command to find MongoDB view
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
Labels: cla-signed

#3412 Restore development log level for com.ning.http.client
  presto-main/etc/log.properties
Labels: cla-signed

#3444 Disable HTTP/2 for CLI and JDBC on pre JDK 11
  presto-client/src/main/java/io/prestosql/client/OkHttpUtil.java
Labels: cla-signed

#3451 Remove unused methods from MongoDB TypeUtils
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/TypeUtils.java
Labels: cla-signed

#3452 Fix comment in LocalExecutionPlanner
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
Labels: cla-signed

#3446 Fix incorrect computation of reader columns for S3SelectRecordCursor
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3select/S3SelectRecordCursorProvider.java
Labels: cla-signed

#3428 Add ping endpoint handler
  presto-main/src/main/java/io/prestosql/failuredetector/HeartbeatFailureDetector.java
  presto-main/src/main/java/io/prestosql/server/StatusResource.java
  presto-main/src/test/java/io/prestosql/server/TestServer.java
Labels: cla-signed

#3448 Pass ConnectorSession to JdbcClient.isLimitGuaranteed
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClient.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-redshift/src/main/java/io/prestosql/plugin/redshift/RedshiftClient.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#3458 Enforce ClusterMemoryManager is bound on coordinator only
  presto-main/src/main/java/io/prestosql/memory/ClusterMemoryManager.java
Labels: cla-signed

#3449 Update running instructions
  README.md
Labels: cla-signed

#3465 Add book badge
  README.md
Labels: cla-signed

#3459 Use ConnectorFactory class to setup ThreadContextClassLoader
  presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
Labels: cla-signed

#3475 Remove unused field
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneIndexSourceColumns.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/IndexJoinOptimizer.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/IndexSourceNode.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/IndexSourceMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneIndexSourceColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#3473 Push down even for large IN
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#3463 Add generic column names test
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedQueries.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduDistributedQueries.java
  presto-mongodb/pom.xml
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoDistributedQueries.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed, test

#3487 Ignore asList(expression) warning
  README.md
Labels: cla-signed

#3481 Refactor visitJoin in PruneUnreferencedOutputs
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
Labels: cla-signed

#3447 Support composite publish_address in Elasticsearch
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/client/TestExtractAddress.java
Labels: cla-signed

#3493 Add rule to remove redundant OffsetNode
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveRedundantOffset.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestRemoveRedundantOffset.java
Labels: cla-signed

#3495 Free disk space before CI checks
  .github/workflows/ci-tests.yml
Labels: cla-signed

#3485 Timestamp tests minor cleanup
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#3478 Add support for CREATE TABLE in Cassandra
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraMetadata.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java
Labels: cla-signed

#3324 Verify connector's applyProjection result
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/sql/planner/ConnectorExpressions.java
  presto-spi/src/main/java/io/prestosql/spi/expression/ConnectorExpression.java
  presto-spi/src/main/java/io/prestosql/spi/expression/Constant.java
  presto-spi/src/main/java/io/prestosql/spi/expression/FieldDereference.java
  presto-spi/src/main/java/io/prestosql/spi/expression/Variable.java
Labels: cla-signed

#3099 Add support for SHOW CREATE SCHEMA.
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHoleMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSchemaProperties.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataUtil.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryMetadata.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/CreateSchema.java
  presto-parser/src/main/java/io/prestosql/sql/tree/ShowCreate.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#3440 Add SSL/TLS support for Hive Metastore
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/pom.xml
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClientFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
Labels: cla-signed

#3396 Add support for dereference pushdown to parquet reader
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-parquet/src/main/java/io/prestosql/parquet/ParquetTypeUtils.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/ParquetReader.java
Labels: cla-signed

#3504 Remove shared mutable state from test
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestReadRowsHelper.java
Labels: cla-signed

#3506 Disable flaky test temporarily
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#3505 Test code cleanup
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestBigQueryConnectorModule.java
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestBigQueryPlugin.java
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestTypeConversions.java
Labels: cla-signed

#3502 Fix property description
  presto-main/src/main/java/io/prestosql/dispatcher/DispatcherConfig.java
Labels: cla-signed

#3514 Add timestamp with UTC time zone support to Parquet column reader
  presto-parquet/src/main/java/io/prestosql/parquet/reader/TimestampColumnReader.java
Labels: cla-signed

#3519 Expose static method for creating parquet page source
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
Labels: cla-signed

#3404 Add check to ensure server tar.gz and RPM do not go above 1GB
  presto-server-rpm/pom.xml
  presto-server/pom.xml
Labels: cla-signed

#3520 Use unique tableName in testInsert
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3529 Add requireNonNull in constructor
  presto-main/src/main/java/io/prestosql/sql/planner/plan/MarkDistinctNode.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/OutputNode.java
Labels: cla-signed

#3531 Rename rule
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneOutputSourceColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneOutputSourceColumns.java
Labels: cla-signed

#3530 Use helper method
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
Labels: cla-signed

#3516 Cleanups in Planner
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/test/java/io/prestosql/sql/query/TestCorrelatedJoin.java
Labels: cla-signed

#3509 Fix flaky TestCassandraTokenSplitManager.testNonEmptyTable
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraTokenSplitManager.java
Labels: cla-signed

#3532 Put getter before the setter
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
Labels: cla-signed

#3515 Smoke test column name with comma
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3455 Generate multiple splits for Hive buckets
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/InternalHiveSplitFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#3541 Fix string statistics recovery logic
  presto-parquet/src/main/java/io/prestosql/parquet/reader/MetadataReader.java
  presto-parquet/src/test/java/io/prestosql/parquet/reader/TestMetadataReader.java
Labels: cla-signed

#3547 Fix mishandled case
  presto-parquet/src/main/java/io/prestosql/parquet/reader/MetadataReader.java
  presto-parquet/src/test/java/io/prestosql/parquet/reader/TestMetadataReader.java
Labels: cla-signed

#3500 Support LDAP without TLS
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapConfig.java
  presto-password-authenticators/src/test/java/io/prestosql/plugin/password/ldap/TestLdapConfig.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdapInsecure.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-without-ssl/password-authenticator.properties
  presto-product-tests/bin/product-tests-suite-6-non-generic.sh
Labels: cla-signed

#3526 Ensure proper memory visibility in RubixConfigurationInitializer
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
Labels: cla-signed

#3527 Add FQDN configuration property
  presto-docs/src/main/sphinx/security/server.rst
Labels: cla-signed

#3552 Fix planning failure when LATERAL is used on left of join or without join
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/test/java/io/prestosql/sql/query/TestLateral.java
Labels: cla-signed

#3557 Properly initialize Hdfs configuration in RubixInitializer
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
Labels: cla-signed

#3479 Fix stats collection for JDBC based connector
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcDiagnosticModule.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJmxStats.java
Labels: cla-signed

#3562 Add random suffix to all tables in TestDistributedQueries
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3496 Minor cleanups in planner
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
Labels: cla-signed

#3020 Add Like predicate to SHOW COLUMNS
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/ShowColumns.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
Labels: cla-signed

#3564 Verify support for correlation during analysis
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analyzer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/CorrelationSupport.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/SubqueryPlanner.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
Labels: cla-signed

#3576 Check Limit with ties rewritten
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/ValidateDependenciesChecker.java
Labels: cla-signed

#3546 Support order sensitivity in RowNumberNode
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ImplementOffset.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/AddLocalExchanges.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PlanNodeDecorrelator.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/WindowFilterPushDown.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/RowNumberNode.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchangesPlans.java
Labels: cla-signed

#3437 Allow reading ORC files which do not have row-group information
  presto-orc/src/main/java/io/prestosql/orc/OrcReader.java
  presto-orc/src/main/java/io/prestosql/orc/OrcRecordReader.java
  presto-orc/src/main/java/io/prestosql/orc/OrcWriter.java
  presto-orc/src/main/java/io/prestosql/orc/StripeReader.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/Footer.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/OrcMetadataReader.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/OrcMetadataWriter.java
  presto-orc/src/test/java/io/prestosql/orc/OrcTester.java
  presto-orc/src/test/java/io/prestosql/orc/TestReadBloomFilter.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#3591 Do not used Rubix parallel warmup by default
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixConfig.java
Labels: cla-signed

#3592 Replace hive.cache.parallel-warmup-enabled with hive.cache.read-mode
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixConfig.java
Labels: cla-signed

#3590 Fix wrong return value in geospatial document
  presto-docs/src/main/sphinx/functions/geospatial.rst
Labels: cla-signed

#3588 Add data mapping tests with padding to TestDistributedQueries
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3438 Verify data integrity in exchanges
  presto-main/src/main/java/io/prestosql/execution/buffer/PagesSerdeUtil.java
  presto-main/src/main/java/io/prestosql/operator/ExchangeClient.java
  presto-main/src/main/java/io/prestosql/operator/ExchangeClientFactory.java
  presto-main/src/main/java/io/prestosql/operator/HttpPageBufferClient.java
  presto-main/src/main/java/io/prestosql/server/PagesResponseWriter.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/test/java/io/prestosql/operator/MockExchangeRequestProcessor.java
  presto-main/src/test/java/io/prestosql/operator/TestExchangeClient.java
  presto-main/src/test/java/io/prestosql/operator/TestExchangeOperator.java
  presto-main/src/test/java/io/prestosql/operator/TestHttpPageBufferClient.java
  presto-main/src/test/java/io/prestosql/operator/TestMergeOperator.java
  presto-main/src/test/java/io/prestosql/operator/TestingExchangeHttpClientHandler.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
Labels: cla-signed
