Repository trinodb/trino, pull requests merged in 2020-07, with the labels that each got.

#4289 Enable more error prone checkes
  pom.xml
Labels: cla-signed

#4268 Update README for enable error prone check in IDEA
  README.md
Labels: cla-signed

#4282 Document query.max-stage-count
  presto-docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed

#4284 Remove unnecessary flexibility
  presto-spi/src/main/java/io/prestosql/spi/session/PropertyMetadata.java
Labels: cla-signed, maintenance

#4222 Split Hive transactional tests to separate job
  presto-product-tests/bin/product-tests-suite-8-non-generic.sh
Labels: cla-signed

#4304 Authorize internal requests to mangement endpoints
  presto-main/src/main/java/io/prestosql/server/security/ResourceSecurityDynamicFeature.java
Labels: cla-signed

#2990 Avoid S3 eventual consistency race condition
  presto-hive/src/main/java/io/prestosql/plugin/hive/SortingFileWriter.java
Labels: cla-signed

#4305 Fix incorrect comparison for timestamp with time zone
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestampWithTimeZoneType.java
Labels: cla-signed

#4300 Simplify condition
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilterConsumer.java
Labels: cla-signed

#4299 Revert benchto packaging changes
  presto-benchto-benchmarks/pom.xml
Labels: cla-signed

#4202 Remove use of EquatableValueSet from the Iceberg connector
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/DomainConverter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/ExpressionConverter.java
Labels: cla-signed, ready to merge

#4319 Invalidate predicates for reused symbols
  presto-main/src/main/java/io/prestosql/sql/planner/EffectivePredicateExtractor.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
Labels: cla-signed

#4198 Test missing nested array in Parquet files
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#4330 Unimplement Comparable in KafkaColumnHandle
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaColumnHandle.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaInternalFieldDescription.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaTopicFieldDescription.java
Labels: cla-signed

#4316 Update to docker images 30
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
  presto-product-tests/conf/product-tests-defaults.sh
Labels: cla-signed

#4296 Try compacting table multiple times if compaction has failed
  presto-product-tests/pom.xml
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#4332 Reduce number of runs of TestHiveTransactionalTable
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed, maintenance, test

#4337 Remove redundant configuration
  docker/default/etc/node.properties
Labels: cla-signed

#4338 Fix dependency scope
  presto-mongodb/pom.xml
Labels: cla-signed

#4342 Ensure to check peak task total memory in QueryStatistics
  presto-tests/src/test/java/io/prestosql/execution/TestEventListener.java
Labels: cla-signed

#4353 Update benchto to 0.11
  presto-benchto-benchmarks/pom.xml
Labels: cla-signed

#4340 Continue testing even if some intermediate modules fail
  .github/workflows/ci.yml
Labels: cla-signed

#4315 Eliminate the redundant control flow
  presto-main/src/main/java/io/prestosql/sql/planner/Symbol.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/OptimizeMixedDistinctAggregations.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/PlanFragmentId.java
Labels: cla-signed

#4355 Fix time resolution in comparison
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#3834 Filter table names in hidden schema for JDBC connector
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClient.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Labels: cla-signed

#4341 Coerce string values to numeric types
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/BigintDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/DoubleDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/IntegerDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/RealDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/SmallintDecoder.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/TinyintDecoder.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#3784 Filter internal schemas in Oracle connector
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleIntegrationSmokeTest.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
Labels: cla-signed

#4354 Add physicalInputDataSize to BasicQueryStats.
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
  presto-main/src/main/java/io/prestosql/server/BasicQueryStats.java
  presto-main/src/test/java/io/prestosql/execution/MockManagedQueryExecution.java
  presto-tests/src/test/java/io/prestosql/memory/TestClusterMemoryLeakDetector.java
Labels: cla-signed

#4373 Fix ExpressionEquivalence for long timestamp
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ExpressionEquivalence.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestExpressionEquivalence.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestamp.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestampWithTimeZone.java
Labels: cla-signed

#4356 Make LocalDynamicFiltersCollector#dynamicFilterDomainsResult final
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFiltersCollector.java
Labels: cla-signed

#4358 Truncate compaction start time to seconds resolution
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#4360 Ignore exception when deleting non existing network
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/ContainerUtil.java
Labels: cla-signed

#4258 Replace HiveQlTranslation with a non-regex-based parser
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveErrorCode.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveQlToPrestoTranslator.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveQlTranslation.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveQlTranslation.java
Labels: cla-signed

#4366 Add documentation for data integrity verification
  presto-docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed

#4320 Add documentation about contributing
  presto-docs/README.md
Labels: cla-signed, docs

#4349 Fix old client compatibility with parametric timestamp type
  presto-main/src/main/java/io/prestosql/FullConnectorSession.java
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSource.java
  presto-main/src/main/java/io/prestosql/connector/system/jdbc/ColumnJdbcTable.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/main/java/io/prestosql/testing/TestingConnectorSession.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
  presto-pinot/src/test/java/io/prestosql/pinot/TestPinotSplitManager.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorSession.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimestampType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimestampWithTimeZoneType.java
  presto-spi/src/test/java/io/prestosql/spi/block/TestingSession.java
Labels: cla-signed

#4247 Update hive caching documentation
  presto-docs/src/main/sphinx/connector/hive-caching.rst
Labels: cla-signed

#4377 Support omitting timestamp precision in DESCRIBE OUTPUT
  presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeOutputRewrite.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#4367 Add 338 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-338.rst
Labels: cla-signed

#4308 Remove non-sensical time vs interval operations
  presto-main/src/main/java/io/prestosql/type/DateTimeOperators.java
  presto-main/src/test/java/io/prestosql/type/TestDateTimeOperatorsBase.java
Labels: cla-signed

#4339 Replace PruneUnreferencedOutputs with iterative rules
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
Labels: cla-signed

#4383 Fix failure for IN expression in join criteria
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java
  presto-main/src/test/java/io/prestosql/sql/query/TestJoin.java
Labels: cla-signed

#4310 Remove unused AggregationStateSerializerFactory
  presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationFromAnnotationsParser.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationImplementation.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/ParametricAggregation.java
  presto-main/src/test/java/io/prestosql/operator/TestAnnotationEngineForAggregates.java
  presto-spi/src/main/java/io/prestosql/spi/function/AggregationStateSerializerFactory.java
Labels: cla-signed

#4389 Move TestingSessionContext to presto-testing
  presto-testing/src/main/java/io/prestosql/testing/TestingSessionContext.java
  presto-tests/src/test/java/io/prestosql/execution/TestQueryRunnerUtil.java
  presto-tests/src/test/java/io/prestosql/tests/TestMetadataManager.java
  presto-tests/src/test/java/io/prestosql/tests/TestQueryManager.java
Labels: cla-signed

#4326 Upgrade avatica jdbc version : 1.16.0 -> 1.17.0
  presto-druid/pom.xml
Labels: cla-signed

#4391 Remove unused methods
  presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
Labels: cla-signed

#4384 Trim white spaces for rowkey definition in Phoenix connector
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixTableProperties.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixIntegrationSmokeTest.java
Labels: cla-signed

#4390 Add section anchors to allow ref linking
  presto-docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed, docs

#4408 Fix incorrect column type for legacy clients
  presto-main/src/main/java/io/prestosql/server/protocol/Query.java
Labels: cla-signed

#4317 Assorted language changes
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientConfig.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientModule.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPartitionManager.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraClientConfig.java
  presto-docs/src/main/sphinx/connector/cassandra.rst
  presto-docs/src/main/sphinx/include/PrestoThriftService.thrift
  presto-docs/src/main/sphinx/release/release-0.153.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/RetryDriver.java
  presto-main/src/main/java/io/prestosql/metadata/DiscoveryNodeManager.java
  presto-main/src/main/java/io/prestosql/sql/planner/DomainTranslator.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/systemtables/PreparedStatementBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/DiscreteValues.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
  presto-spi/src/test/java/io/prestosql/spi/predicate/TestEquatableValueSet.java
  presto-thrift-api/src/main/java/io/prestosql/plugin/thrift/api/valuesets/PrestoThriftEquatableValueSet.java
  presto-thrift-api/src/test/java/io/prestosql/plugin/thrift/api/valuesets/TestPrestoThriftEquatableValueSet.java
  presto-verifier/src/main/java/io/prestosql/verifier/Validator.java
  presto-verifier/src/main/java/io/prestosql/verifier/Verifier.java
  presto-verifier/src/main/java/io/prestosql/verifier/VerifierConfig.java
  presto-verifier/src/test/java/io/prestosql/verifier/TestVerifierConfig.java
Labels: cla-signed

#4399 Use actual table location in TestImpersonation
  presto-product-tests/src/main/java/io/prestosql/tests/TestImpersonation.java
Labels: cla-signed

#4416 Move column handle validation for Kafka encoders into constructor
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/AbstractRowEncoder.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/csv/CsvRowEncoder.java
Labels: cla-signed

#4309 Bump Iceberg version to 0.8.0-incubating
  presto-iceberg/pom.xml
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#4420 Update Alluxio client version to 2.3.0
  pom.xml
Labels: cla-signed

#4422 Remove unnecessary function references
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
Labels: cla-signed

#4436 Remove unused declaration
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriver.java
Labels: cla-signed

#4393 Fix fails query if bucket number exceeds declared bucket size
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#4423 Fix failure when WITH subquery contains hidden columns
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q01.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q02.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q04.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q05.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q11.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q24_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q24_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q30.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q31.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q33.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q39_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q39_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q47.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q51.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q54.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q56.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q57.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q58.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q59.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q60.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q64.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q74.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q75.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q78.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q81.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q83.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q95.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q15.plan.txt
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/test/java/io/prestosql/sql/query/TestWith.java
Labels: cla-signed

#4441 Document fixed management user configuration
  presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
Labels: cla-signed

#4429 Fix flaky testParquetTimestampPredicatePushdown
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#4283 Add support for Iceberg snapshot rollback
  presto-iceberg/README.md
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergConnector.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergModule.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/InternalIcebergConnectorFactory.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/RollbackToSnapshotProcedure.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#4438 Improve test coverage for raw decoder
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
Labels: cla-signed

#4425 Support omitting timestamp precision in DESCRIBE INPUT
  presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeInputRewrite.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeOutputRewrite.java
  presto-main/src/main/java/io/prestosql/type/TypeUtils.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#3425 Add approx_most_frequent aggregation function
  pom.xml
  presto-docs/src/main/sphinx/functions/aggregate.rst
  presto-main/pom.xml
  presto-main/src/main/java/io/prestosql/metadata/FunctionRegistry.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/ApproximateMostFrequentBucketDeserializer.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/ApproximateMostFrequentBucketSerializer.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/ApproximateMostFrequentFunction.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/ApproximateMostFrequentHistogram.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/BucketConsumer.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/LongApproximateMostFrequentStateFactory.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/LongApproximateMostFrequentStateSerializer.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/StringApproximateMostFrequentStateFactory.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/StringApproximateMostFrequentStateSerializer.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/TestApproximateMostFrequentHistogram.java
  presto-phoenix/pom.xml
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestAggregations.java
Labels: cla-signed

#3715 Add grouped_execution to kudu connector
  presto-kudu/pom.xml
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduBucketFunction.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduBucketedSplitSource.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientConfig.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduConnector.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduConnectorFactory.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduHandleResolver.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduMetadata.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduModule.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduNodePartitioningProvider.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPartitionHandle.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPartitioningHandle.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSessionProperties.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSplit.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSplitManager.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduTableHandle.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/schema/KuduRangePartition.java
  presto-kudu/src/main/java/org/apache/kudu/client/KeyEncoderAccessor.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/KuduQueryRunnerFactory.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationGroupedExecution.java
Labels: cla-signed

#4471 Fix resource warning in KafkaPageSink#appendPage
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/AbstractRowEncoder.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/RowEncoder.java
Labels: cla-signed

#4463 Add "America/Nuuk" time zone
  pom.xml
  presto-spi/src/main/resources/io/prestosql/spi/type/zone-index.properties
  presto-spi/src/test/java/io/prestosql/spi/type/TestTimeZoneKey.java
Labels: cla-signed

#4464 Inline Rubix version
  pom.xml
Labels: cla-signed

#4465 Fix a configuration issue with the alluxio connector
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/alluxio/AlluxioMetastoreModule.java
Labels: cla-signed

#4233 Fix case-sensitivity failure for DISTINCT + ORDER BY
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/test/java/io/prestosql/sql/query/TestDistinctWithOrderBy.java
Labels: cla-signed

#4364 Support large timestamp [tz] values in JDBC
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSet.java
Labels: cla-signed

#4297 Run Iceberg product test once
  presto-product-tests/conf/product-tests-config-cdh5.sh
  presto-product-tests/conf/product-tests-config-hdp3.sh
Labels: cla-signed

#4478 Add tests for ORDER BY + DISTINCT
  presto-main/src/test/java/io/prestosql/sql/query/TestDistinctWithOrderBy.java
Labels: cla-signed

#4475 Fix nested parametric timestamp compatibility with older clients
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSource.java
  presto-main/src/main/java/io/prestosql/server/protocol/QueryResultRows.java
  presto-main/src/main/java/io/prestosql/type/TypeUtils.java
Labels: cla-signed

#4415 Upgrade mongo driver
  presto-mongodb/pom.xml
Labels: cla-signed

#4474 Add test environment with hive.hdfs.data-transfer-protection=privacy
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeKerberosHdfsImpersonationWithDataProtection.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-data-protection/core-site.xml
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-data-protection/hdfs-site.xml
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-data-protection/hive-data-protection-site.xml
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-data-protection/hive.properties
  presto-product-tests/bin/product-tests-suite-3.sh
Labels: cla-signed

#4076 Add support for scanned bytes limit on queries
  presto-main/src/main/java/io/prestosql/ExceededScanLimitException.java
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/execution/QueryManagerConfig.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryManagerConfig.java
  presto-spi/src/main/java/io/prestosql/spi/StandardErrorCode.java
  presto-tests/src/test/java/io/prestosql/tests/TestQueryManager.java
Labels: cla-signed

#4454 Register partition from default location when location is missing in registerPartition procedure
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHivePartitionProcedures.java
Labels: cla-signed

#4481 fix typo in json property
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
Labels: cla-signed

#4467 Handle NaN in Parquet statistics
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
  presto-parquet/src/test/java/io/prestosql/parquet/TestTupleDomainParquetPredicate.java
Labels: cla-signed

#4485 Avoid creating tiny splits at the end of block boundaries
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitSource.java
Labels: cla-signed

#3939 Add support for writing BloomFilters in ORC
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcFileWriterFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcWriterConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-orc/src/main/java/io/prestosql/orc/OrcWriteValidation.java
  presto-orc/src/main/java/io/prestosql/orc/OrcWriter.java
  presto-orc/src/main/java/io/prestosql/orc/OrcWriterOptions.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/CompressedMetadataWriter.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/MetadataWriter.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/OrcMetadataWriter.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/BloomFilter.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/BloomFilterBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/DateStatisticsBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/DoubleStatisticsBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/IntegerStatisticsBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/NoOpBloomFilterBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/StringStatisticsBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/metadata/statistics/Utf8BloomFilterBuilder.java
  presto-orc/src/main/java/io/prestosql/orc/writer/BooleanColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/ByteColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/ColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/ColumnWriters.java
  presto-orc/src/main/java/io/prestosql/orc/writer/DecimalColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/DoubleColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/FloatColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/ListColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/LongColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/MapColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/SliceDictionaryColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/SliceDirectColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/StructColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/TimestampColumnWriter.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcBloomFilters.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcWriter.java
  presto-orc/src/test/java/io/prestosql/orc/TestSliceDictionaryColumnWriter.java
  presto-orc/src/test/java/io/prestosql/orc/metadata/statistics/TestDateStatisticsBuilder.java
  presto-orc/src/test/java/io/prestosql/orc/metadata/statistics/TestDoubleStatisticsBuilder.java
  presto-orc/src/test/java/io/prestosql/orc/metadata/statistics/TestIntegerStatisticsBuilder.java
  presto-orc/src/test/java/io/prestosql/orc/metadata/statistics/TestStringStatisticsBuilder.java
Labels: cla-signed

#4495 Recommend Redundant 'else' inspection
  README.md
Labels: cla-signed

#4497 Verify output type consistently
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementCount.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementCountAll.java
Labels: cla-signed

#4501 Use smooth scrolling
  presto-docs/src/main/sphinx/themes/presto/static/presto.css
Labels: cla-signed

#4502 Update Iceberg libraries to release 0.9.0
  presto-iceberg/pom.xml
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/ManifestsTable.java
Labels: cla-signed

#4506 Improve timezone normalization
  presto-spi/src/main/java/io/prestosql/spi/type/TimeZoneKey.java
  presto-spi/src/test/java/io/prestosql/spi/type/TestTimeZoneKey.java
Labels: cla-signed

#4515 Ensure to merge all buckets in the stream summary
  presto-main/src/main/java/io/prestosql/operator/aggregation/ApproximateMostFrequentHistogram.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/TestApproximateMostFrequentHistogram.java
Labels: cla-signed

#4376 Interpret JDBC ResultSet dates and timestamps in client JVM time zone
  pom.xml
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkDriverOptions.java
  presto-cli/src/main/java/io/prestosql/cli/ClientOptions.java
  presto-cli/src/test/java/io/prestosql/cli/TestQueryRunner.java
  presto-client/src/main/java/io/prestosql/client/ClientSession.java
  presto-client/src/main/java/io/prestosql/client/StatementClient.java
  presto-client/src/main/java/io/prestosql/client/StatementClientV1.java
  presto-docs/src/main/sphinx/installation/jdbc.rst
  presto-jdbc/pom.xml
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/ConnectionProperties.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoConnection.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriverUri.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSetTimezone.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriver.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverUri.java
  presto-oracle/pom.xml
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestingPrestoClient.java
  presto-tests/src/test/java/io/prestosql/execution/TestFinalQueryInfo.java
Labels: cla-signed, ready to merge

#4411 Fix JDBC metadata for timestamp types
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDatabaseMetaData.java
  presto-main/src/main/java/io/prestosql/connector/system/jdbc/ColumnJdbcTable.java
Labels: cla-signed

#4484 Add 339 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-339.rst
Labels: cla-signed

#4525 Allow using markdown
  presto-docs/Dockerfile
  presto-docs/build
  presto-docs/requirements.txt
  presto-docs/src/main/sphinx/conf.py
  presto-docs/src/main/sphinx/release/release-338.md
  presto-docs/src/main/sphinx/release/release-338.rst
  presto-docs/src/main/sphinx/release/release-339.md
  presto-docs/src/main/sphinx/release/release-339.rst
Labels: cla-signed

#4424 Change Iceberg to use the new ParquetFileWriter
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetFileWriter.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetFileWriterFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/ParquetTester.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/DomainConverter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/ExpressionConverter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergFileWriter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergFileWriterFactory.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergOrcFileWriter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSink.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergParquetFileWriter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergRecordFileWriter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSessionProperties.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionData.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/util/PrimitiveTypeMapBuilder.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/IcebergQueryRunner.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestDomainConverter.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/MessageTypeConverter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriters.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/DecimalValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/PrimitiveValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/TimestampValueWriter.java
Labels: cla-signed

#4476 Wrap arguments for Error Prone
  pom.xml
Labels: cla-signed

#4518 Add debug log for Cassandra query
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraSession.java
Labels: cla-signed

#4483 Add max idle time as a configurable property for the mongodb connector
  presto-docs/src/main/sphinx/connector/mongodb.rst
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientConfig.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientModule.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoClientConfig.java
Labels: cla-signed

#4468 Fix loading of PartitionFieldSummary in ManifestsTable
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/ManifestsTable.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSystemTables.java
Labels: cla-signed

#4522 Make TimeZoneKey case-sensitive
  presto-spi/src/main/java/io/prestosql/spi/type/TimeZoneKey.java
  presto-spi/src/test/java/io/prestosql/spi/type/TestTimeZoneKey.java
Labels: cla-signed

#4279 getTableDefaultLocation should not called if external_location present
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Hadoop.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive_with_external_writes.properties
  presto-product-tests/bin/product-tests-suite-2.sh
  presto-product-tests/src/main/java/io/prestosql/tests/TestGroups.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java
Labels: cla-signed

#4417 Add Kafka raw encoder
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/EncoderModule.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/raw/RawRowEncoder.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/raw/RawRowEncoderFactory.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/raw/TestRawEncoderMapping.java
  presto-kafka/src/test/resources/write_test/all_datatypes_raw.json
Labels: cla-signed

#4532 Simplify a product test
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestExternalHiveTable.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateExternalTable.java
Labels: cla-signed

#4503 Fix TestQueryStateInfoResource setup hang
  presto-main/src/test/java/io/prestosql/server/TestQueryStateInfoResource.java
Labels: cla-signed

#4542 Remove layouts from statistics docs
  presto-docs/src/main/sphinx/optimizer/statistics.rst
Labels: cla-signed, docs

#4473 Ensure to pushdown the aggregation for count(const)
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Labels: cla-signed

#4549 Update tempto to 180
  pom.xml
Labels: cla-signed

#4517 Fix flaky TestOracleIntegrationSmokeTest
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
  presto-oracle/src/test/resources/init.sql
Labels: cla-signed

#4511 Add remote Host info to PageTransportErrorException
  presto-main/src/main/java/io/prestosql/operator/HttpPageBufferClient.java
  presto-main/src/main/java/io/prestosql/operator/PageTransportErrorException.java
  presto-main/src/test/java/io/prestosql/operator/TestHttpPageBufferClient.java
Labels: cla-signed

#4571 Remove omitDatetimeTypePrecision from SPI
  presto-main/src/main/java/io/prestosql/FullConnectorSession.java
  presto-main/src/main/java/io/prestosql/connector/system/jdbc/ColumnJdbcTable.java
  presto-main/src/main/java/io/prestosql/testing/TestingConnectorSession.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorSession.java
  presto-spi/src/test/java/io/prestosql/spi/block/TestingSession.java
Labels: cla-signed

#4559 Remove redundant local variable
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/LambdaCaptureDesugaringRewriter.java
Labels: cla-signed

#4575 Use global high memory split source counter
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java
Labels: cla-signed

#4574 Support CTAS for Hive transactional tables v2
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveInsertTableHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveOutputTableHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSinkProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTableProperties.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWritableTableHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWriterFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveWriterFactory.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/BucketingType.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TransactionalTableType.java
Labels: cla-signed

#4557 Change name of Kafka createTopics to match parameter type
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestMinimalFunctionality.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/util/TestingKafka.java
Labels: cla-signed

#4569 Use consistent title for limitations section
  presto-docs/src/main/sphinx/connector/kudu.rst
  presto-docs/src/main/sphinx/connector/memory.rst
  presto-docs/src/main/sphinx/connector/memsql.rst
  presto-docs/src/main/sphinx/connector/mysql.rst
  presto-docs/src/main/sphinx/connector/oracle.rst
  presto-docs/src/main/sphinx/connector/postgresql.rst
  presto-docs/src/main/sphinx/connector/redshift.rst
  presto-docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed

#4561 Add security policy
  SECURITY.md
Labels: cla-signed

#4585 Remove unused ElasticsearchColumn class
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchColumn.java
Labels: cla-signed

#4573 Reduce data size in TestCsv
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestCsv.java
Labels: cla-signed

#4552 Ignore empty folder placeholder files on S3
  presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystemS3.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/MockAmazonS3.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#4388 Add toggle for specifying dynamic filtering refresh interval
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/test/java/io/prestosql/server/TestDynamicFilterService.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
Labels: cla-signed

#4540 Avoid checking isSplittable for files smaller than the split max size
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/InternalHiveSplitFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#4604 Remove redundant Iceberg smoke test
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#4011 Add LuhnCheck function
  presto-docs/src/main/sphinx/functions/string.rst
  presto-main/src/main/java/io/prestosql/metadata/FunctionRegistry.java
  presto-main/src/main/java/io/prestosql/operator/scalar/LuhnCheckFunction.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestLuhnCheckFunction.java
Labels: cla-signed

#4535 Ignore ES indexes without mappings
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#4582 Minor refactor of relation coercion
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
Labels: cla-signed

#4598 Removed Auth Token from Exception Message
  presto-main/src/main/java/io/prestosql/server/security/KerberosAuthenticator.java
Labels: cla-signed

#4612 Update log4j dependency version to 2.13.3
  presto-elasticsearch/pom.xml
Labels: cla-signed

#4592 Expose QueryType in QueryContext
  presto-main/src/main/java/io/prestosql/dispatcher/FailedDispatchQuery.java
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQueryFactory.java
  presto-main/src/main/java/io/prestosql/event/QueryMonitor.java
  presto-main/src/main/java/io/prestosql/execution/QueryInfo.java
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
  presto-main/src/main/java/io/prestosql/server/BasicQueryInfo.java
  presto-main/src/test/java/io/prestosql/execution/MockManagedQueryExecution.java
  presto-main/src/test/java/io/prestosql/execution/TestCallTask.java
  presto-main/src/test/java/io/prestosql/execution/TestCommitTask.java
  presto-main/src/test/java/io/prestosql/execution/TestDeallocateTask.java
  presto-main/src/test/java/io/prestosql/execution/TestPrepareTask.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryStateMachine.java
  presto-main/src/test/java/io/prestosql/execution/TestResetSessionTask.java
  presto-main/src/test/java/io/prestosql/execution/TestRollbackTask.java
  presto-main/src/test/java/io/prestosql/execution/TestSetPathTask.java
  presto-main/src/test/java/io/prestosql/execution/TestSetRoleTask.java
  presto-main/src/test/java/io/prestosql/execution/TestSetSessionTask.java
  presto-main/src/test/java/io/prestosql/execution/TestStartTransactionTask.java
  presto-main/src/test/java/io/prestosql/server/TestBasicQueryInfo.java
  presto-main/src/test/java/io/prestosql/server/TestQueryStateInfo.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryContext.java
  presto-tests/src/test/java/io/prestosql/execution/TestEventListener.java
  presto-tests/src/test/java/io/prestosql/memory/TestClusterMemoryLeakDetector.java
Labels: cla-signed

#4560 Fix NPE when listing schemas in Phoenix connector
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
Labels: cla-signed

#4446 add tpcds test suite
  .github/workflows/ci.yml
  presto-product-tests/bin/product-tests-suite-tpcds.sh
  presto-product-tests/src/main/resources/sql-tests/testcases/tpcds/q85.result
Labels: cla-signed

#4606 Use Presto logo in project README.md file
  README.md
  presto-docs/src/main/resources/logo/web/main/white/Presto_Logo_WhiteBG-01.png
Labels: cla-signed

#4628 Simplify negative anyMatch usage
  presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/AccumuloClient.java
  presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/StaticSelector.java
Labels: cla-signed

#4621 Remove unused constant
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
Labels: cla-signed

#4631 Remove unnecessary TODO
  presto-main/src/main/java/io/prestosql/type/Timestamps.java
Labels: cla-signed

#4563 Handle dates preceding the introduction of the Gregorian calendar calendar
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSet.java
Labels: cla-signed

#4611 Add max error retry config option to glue client
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
Labels: cla-signed

#4625 Order GHA job exclusions
  .github/workflows/ci.yml
Labels: cla-signed

#4541 Clarify Java 11 min requirement
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#4556 Add known limitations
  presto-docs/src/main/sphinx/connector/mongodb.rst
Labels: cla-signed, docs

#4477 Add Kafka Json encoder
  presto-kafka/pom.xml
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/EncoderModule.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/JsonRowEncoder.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/JsonRowEncoderFactory.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestJsonEncoder.java
  presto-kafka/src/test/resources/write_test/all_datatypes_json.json
Labels: cla-signed

#4633 Fix BenchmarkPlanner
  presto-main/src/test/java/io/prestosql/sql/planner/BenchmarkPlanner.java
Labels: cla-signed

#4194 Ensure that older JDBC clients are compatible with current Presto server
  .github/workflows/ci.yml
  pom.xml
  presto-test-jdbc-compatibility/bin/run_tests.sh
  presto-test-jdbc-compatibility/pom.xml
  presto-test-jdbc-compatibility/src/test/java/io/prestosql/JdbcDriverCapabilities.java
  presto-test-jdbc-compatibility/src/test/java/io/prestosql/TestJdbcCompatibility.java
  presto-test-jdbc-compatibility/src/test/java/io/prestosql/TestJdbcResultSetCompatibility.java
  presto-test-jdbc-compatibility/src/test/java/io/prestosql/TestingServerUtils.java
Labels: cla-signed

#4652 Throw specific exception when conversion fails
  presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamp/WithTimeZone.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamptz/AtTimeZone.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
  presto-spi/src/main/java/io/prestosql/spi/type/DateTimeEncoding.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimeZoneKey.java
Labels: cla-signed
