Repository trinodb/trino, pull requests merged in 2020-08, with the labels that each got.

#4635 Fix unaliasing of ExchangeNode outputs
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
Labels: cla-signed

#4655 Restore customizable QueryBuilder#getRelation
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
Labels: cla-signed

#4648 Add user mapping to insecure authenticator
  presto-docs/src/main/sphinx/security/user-mapping.rst
  presto-main/src/main/java/io/prestosql/server/security/AuthenticationFilter.java
  presto-main/src/main/java/io/prestosql/server/security/InsecureAuthenticator.java
  presto-main/src/main/java/io/prestosql/server/security/InsecureAuthenticatorConfig.java
  presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java
  presto-main/src/test/java/io/prestosql/server/security/TestInsecureAuthenticatorConfig.java
  presto-main/src/test/java/io/prestosql/server/security/TestResourceSecurity.java
Labels: cla-signed

#4432 Fallback to FileInputStream if PemReader fails to read certificates
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
Labels: cla-signed

#4667 Handle reused symbols in ProjectNode
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
Labels: cla-signed

#4669 Apply DomainTranslator to STARTS_WITH function
  presto-main/src/main/java/io/prestosql/sql/planner/DomainTranslator.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestDomainTranslator.java
Labels: cla-signed

#4682 Fix benchto dependency
  presto-benchto-benchmarks/pom.xml
Labels: cla-signed

#4686 Fix formatting
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
Labels: cla-signed

#4688 Extend Parquet timestamp support
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetSchemaConverter.java
Labels: cla-signed

#4578 A couple fixes related to complex data types in Iceberg connector
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/TypeConverter.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
  presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Labels: cla-signed

#4249 SPI and optimizer rule for connectors that can support complete topN …
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/sql/planner/OrderingScheme.java
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushTopNIntoTableScan.java
  presto-main/src/test/java/io/prestosql/connector/MockConnectorFactory.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushTopNIntoTableScan.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/TopNApplicationResult.java
Labels: cla-signed

#4472 Check permission for create table like
  presto-main/src/main/java/io/prestosql/execution/CreateTableTask.java
  presto-main/src/test/java/io/prestosql/execution/TestCreateTableTask.java
Labels: cla-signed

#4701 Fix adaptation from Slice to Object stack type
  presto-main/src/main/java/io/prestosql/metadata/ScalarFunctionAdapter.java
  presto-main/src/test/java/io/prestosql/metadata/TestScalarFunctionAdapter.java
Labels: RELEASE-BLOCKER, cla-signed

#3967 Avoid type coercion when a dereferenced field is same type
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSource.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: bug, cla-signed

#4705 Improve performance of reading Hive JSON tables
  pom.xml
Labels: cla-signed

#4709 Remove unused variable
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorSplitManager.java
Labels: cla-signed

#4712 Remove redundant Glue catalogid from documentation
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#4710 Add missing synchronize
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorSplitManager.java
Labels: cla-signed

#740 Support bitwise shift functions
  presto-docs/src/main/sphinx/functions/bitwise.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/BitwiseFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestBitwiseFunctions.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
Labels: cla-signed

#4649 Disable JIT byte code recompilation cutoffs in default jvm.config
  docker/default/etc/jvm.config
  presto-docs/src/main/sphinx/installation/deployment.rst
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config
  presto-server-rpm/src/main/resources/dist/config/jvm.config
Labels: cla-signed

#4458 Expose CachingHiveMetastore metrics via JMX
  presto-hive/pom.xml
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
Labels: cla-signed

#4651 Add IF EXISTS and IF NOT EXISTS checks to ALTER TABLE
  presto-docs/src/main/sphinx/sql/alter-table.rst
  presto-main/src/main/java/io/prestosql/execution/AddColumnTask.java
  presto-main/src/main/java/io/prestosql/execution/DropColumnTask.java
  presto-main/src/main/java/io/prestosql/execution/RenameColumnTask.java
  presto-main/src/main/java/io/prestosql/execution/RenameTableTask.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/AddColumn.java
  presto-parser/src/main/java/io/prestosql/sql/tree/DropColumn.java
  presto-parser/src/main/java/io/prestosql/sql/tree/RenameColumn.java
  presto-parser/src/main/java/io/prestosql/sql/tree/RenameTable.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#4617 Add data_block_encoding parameter to Phoenix connector.
  presto-docs/src/main/sphinx/connector/phoenix.rst
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixTableProperties.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixIntegrationSmokeTest.java
Labels: cla-signed

#4729 Use "HDFS" instead of "Hdfs" in error message
  presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveHadoop2Plugin.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixModule.java
Labels: cla-signed

#4730 Prevent retrieving same value twice in 128-bit multiplication
  presto-spi/src/main/java/io/prestosql/spi/type/UnscaledDecimal128Arithmetic.java
Labels: cla-signed

#4738 Adjust code font size for contents navigation
  presto-docs/src/main/sphinx/themes/presto/static/presto.css
Labels: cla-signed

#4530 Update Kafka docs with encoder info
  presto-docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#4660 Add push down documentation
  presto-docs/src/main/sphinx/connector/postgresql.rst
  presto-docs/src/main/sphinx/optimizer.rst
  presto-docs/src/main/sphinx/optimizer/pushdown.rst
Labels: cla-signed, docs

#4547 Update hive procedures docs
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#4696 Enable HTTP/2 by default
  presto-main/src/main/java/io/prestosql/server/InternalCommunicationConfig.java
  presto-main/src/main/java/io/prestosql/server/InternalCommunicationModule.java
  presto-main/src/test/java/io/prestosql/server/TestInternalCommunicationConfig.java
Labels: cla-signed

#4579 Add Iceberg smoke tests for partitioning transforms
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTable.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#4733 Use static imports for Preconditions and Verify
  presto-main/src/main/java/io/prestosql/operator/DriverStats.java
  presto-main/src/main/java/io/prestosql/operator/SetBuilderOperator.java
  presto-main/src/main/java/io/prestosql/sql/planner/SubPlan.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/OutputNode.java
  presto-main/src/main/java/io/prestosql/testing/MaterializedRow.java
  presto-main/src/main/java/io/prestosql/util/GraphvizPrinter.java
  presto-main/src/test/java/io/prestosql/metadata/TestScalarFunctionAdapter.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/AbstractTestApproximateCountDistinct.java
  presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArrayDistinct.java
  presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArrayFilter.java
  presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArraySort.java
  presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArrayTransform.java
  presto-main/src/test/java/io/prestosql/sql/gen/TestExpressionCompiler.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEqualityInference.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetSchemaConverter.java
  presto-parser/src/main/java/io/prestosql/sql/tree/BooleanLiteral.java
  presto-pinot/src/main/java/io/prestosql/pinot/PinotMetrics.java
  presto-tpch/src/test/java/io/prestosql/plugin/tpch/TestTpchMetadata.java
Labels: cla-signed

#4656 Update JDK links in documentation
  presto-docs/src/main/sphinx/functions/conversion.rst
  presto-docs/src/main/sphinx/functions/regexp.rst
  presto-docs/src/main/sphinx/security/server.rst
  presto-docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#4250 Support recursive CTEs
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/Scope.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/NodeAndMappings.java
  presto-main/src/main/java/io/prestosql/sql/planner/PlanCopier.java
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/SubqueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushTableWriteThroughUnion.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PlanNodeDecorrelator.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/SymbolMapper.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestRecursiveCTE.java
  presto-main/src/test/java/io/prestosql/sql/query/TestRecursiveCTE.java
  presto-spi/src/main/java/io/prestosql/spi/StandardErrorCode.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#4746 Fix config for HTTP/2
  presto-main/src/main/java/io/prestosql/server/InternalCommunicationConfig.java
  presto-main/src/main/java/io/prestosql/server/InternalCommunicationModule.java
  presto-main/src/test/java/io/prestosql/server/TestInternalCommunicationConfig.java
Labels: cla-signed

#4753 Return TIMESTAMP WITH TIME ZONE from JMX connector
  presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxMetadata.java
  presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxRecordSetProvider.java
  presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxMetadata.java
  presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxSplitManager.java
Labels: cla-signed

#4752 Return TIMESTAMP WITH TIME ZONE from Local File connector
  presto-local-file/src/main/java/io/prestosql/plugin/localfile/LocalFileRecordCursor.java
  presto-local-file/src/main/java/io/prestosql/plugin/localfile/LocalFileTables.java
  presto-local-file/src/test/java/io/prestosql/plugin/localfile/MetadataUtil.java
  presto-local-file/src/test/java/io/prestosql/plugin/localfile/TestLocalFileColumnHandle.java
Labels: cla-signed

#4683 Fix error when delete by a decimal primary key column.
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/RowHelper.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationDecimalColumns.java
Labels: cla-signed

#4670 Support missingColumnsOnInsert in the Phoenix Connector.
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixOutputTableHandle.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixIntegrationSmokeTest.java
Labels: cla-signed

#4740 Fix documentation versions dropdown
  presto-docs/pom.xml
  presto-docs/src/main/sphinx/conf.py
  presto-docs/src/main/sphinx/static/javascripts/version_dropdown.js
  presto-docs/src/main/sphinx/static/presto.css
  presto-docs/src/main/sphinx/static/pygments.css
  presto-docs/src/main/sphinx/themes/presto/theme.conf
Labels: cla-signed

#4758 Fix release note for version 340
  presto-docs/src/main/sphinx/release/release-340.md
Labels: cla-signed

#4761 Various small Phoenix Connector fixes.
  presto-docs/src/main/sphinx/connector/phoenix.rst
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixTableProperties.java
Labels: cla-signed

#4765 Generate reports dir automatically
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests/bin/product-tests-suite-1.sh
  presto-product-tests/bin/product-tests-suite-2.sh
  presto-product-tests/bin/product-tests-suite-3.sh
  presto-product-tests/bin/product-tests-suite-5.sh
  presto-product-tests/bin/product-tests-suite-6-non-generic.sh
  presto-product-tests/bin/product-tests-suite-7-non-generic.sh
  presto-product-tests/bin/product-tests-suite-8-non-generic.sh
  presto-product-tests/bin/product-tests-suite-tpcds.sh
Labels: cla-signed

#4759 Remove support for Hive bucketing on timestamp
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketing.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketingV1.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketingV2.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestHiveBucketing.java
Labels: cla-signed

#4772 Return TIMESTAMP WITH TIME ZONE from Cassandra connector
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraRecordCursor.java
  presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraType.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraConnector.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraDistributedQueries.java
  presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraIntegrationSmokeTest.java
  presto-docs/src/main/sphinx/connector/cassandra.rst
  presto-product-tests/src/main/java/io/prestosql/tests/cassandra/DataTypesTableDefinition.java
  presto-product-tests/src/main/java/io/prestosql/tests/cassandra/MultiColumnKeyTableDefinition.java
  presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestInsertIntoCassandraTable.java
  presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestSelect.java
  presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestSelectMultiColumnKey.java
Labels: cla-signed

#4780 Fix serializing row type with null field values
  presto-main/src/main/java/io/prestosql/server/protocol/QueryResultRows.java
  presto-main/src/test/java/io/prestosql/server/protocol/TestQueryResultRows.java
Labels: cla-signed

#4779 Configure Oracle UCP inactive connection timeout
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClientModule.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleConfig.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OraclePoolConnectorFactory.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleConfig.java
Labels: cla-signed

#4775 add orai18n jar to Oracle ZHS16GBK character
  presto-oracle/pom.xml
Labels: cla-signed

#4741 Add reverse function for varbinary
  presto-docs/src/main/sphinx/functions/binary.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestVarbinaryFunctions.java
Labels: cla-signed

#4766 Remove product test environment startup timeout
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
Labels: cla-signed

#4790 Remove unused class
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamp/TimeToTimestampCast.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamptz/TimeToTimestampWithTimeZoneCast.java
Labels: cla-signed

#4794 Remove redundant condition check in LongOutputStreamV2
  presto-orc/src/main/java/io/prestosql/orc/stream/LongOutputStreamV2.java
Labels: cla-signed

#4781 Fix serialization of NULL values in ARRAY and MAP types for legacy values
  presto-main/src/main/java/io/prestosql/server/protocol/QueryResultRows.java
  presto-main/src/test/java/io/prestosql/server/protocol/TestQueryResultRows.java
Labels: cla-signed

#4786 Remove outdated comments in LdapSslSocketFactory
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapSslSocketFactory.java
Labels: cla-signed

#4787 Deduplicate ValuesNode output symbols
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
Labels: cla-signed

#4800 Remove unused Raptor property
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/StorageManagerConfig.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/storage/TestStorageManagerConfig.java
Labels: cla-signed

#4818 Correct limitation
  presto-docs/src/main/sphinx/connector/hive-caching.rst
Labels: cla-signed, docs

#4695 Changes to History and Diagnostic sections in CLI file
  presto-docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs

#4602 Fix ordering of LIMIT in documentation
  presto-docs/src/main/sphinx/sql/select.rst
Labels: cla-signed, docs

#4798 Update Config connection-url
  presto-docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#4668 Add schema access rules documentation
  presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
Labels: cla-signed, docs

#4822 Correct limitation
  presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
Labels: cla-signed, docs

#4801 Fix functions in pinot passthrough queries
  presto-pinot/src/main/java/io/prestosql/pinot/query/FilterToPqlConverter.java
  presto-pinot/src/test/java/io/prestosql/pinot/query/TestDynamicTable.java
Labels: cla-signed

#4827 Edit connection url
  presto-docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#4829 Fix Javadoc for ShortTimestampWithTimeZoneType
  presto-spi/src/main/java/io/prestosql/spi/type/ShortTimestampWithTimeZoneType.java
Labels: cla-signed

#4804 Only request client certificate when using certificate authentication
  pom.xml
  presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java
  presto-main/src/main/java/io/prestosql/server/ui/WebUiAuthenticationModule.java
Labels: cla-signed

#4830 Add missing cast in CursorProcessorCompiler
  presto-main/src/main/java/io/prestosql/sql/gen/CursorProcessorCompiler.java
Labels: cla-signed

#4831 Update BigQuery timestamp parsing to new semantics
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryType.java
Labels: cla-signed

#4551 Update Rubix version to 0.3.16
  pom.xml
  presto-hive-hadoop2/pom.xml
  presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveHadoop2Plugin.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/DummyBookKeeper.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCaching.java
Labels: cla-signed

#4842 Remove misplaced tests
  presto-main/src/test/java/io/prestosql/operator/scalar/time/TestExtract.java
Labels: cla-signed

#4843 Fix incorrect description
  presto-main/src/main/java/io/prestosql/operator/scalar/time/TimeFunctions.java
  presto-product-tests/src/main/resources/sql-tests/testcases/horology_functions/checkHorologyFunctionsRegistered.result
Labels: cla-signed

#4845 Rename to OraclePoolConnectionFactory
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClientModule.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OraclePoolConnectionFactory.java
Labels: cla-signed

#4600 Add physicalInputDataSize to Statement/Stage stats
  presto-client/src/main/java/io/prestosql/client/StageStats.java
  presto-client/src/main/java/io/prestosql/client/StatementStats.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestProgressMonitor.java
  presto-main/src/main/java/io/prestosql/server/protocol/Query.java
Labels: cla-signed

#4639 Add support for Iceberg metadata delete
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#4451 Support Iceberg table and column statistics
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/Partition.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTable.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/TableStatisticsMaker.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#4744 Avoid using shaded classes
  presto-druid/pom.xml
  presto-druid/src/test/java/io/prestosql/plugin/druid/TestingDruidServer.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSetTimezone.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/properties/KuduTableProperties.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/BaseOracleIntegrationSmokeTest.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/Commands.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environments.java
  presto-server-rpm/pom.xml
  presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Labels: cla-signed

#4867 Fix extract timezone hour/minute for timestamp with time zone
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamptz/TestExtract.java
Labels: cla-signed

#4878 Remove redundant TIME tests
  presto-main/src/test/java/io/prestosql/operator/scalar/time/TestTime.java
Labels: cla-signed

#4873 Override getCompletedBytes method in KafkaPageSink
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaPageSink.java
Labels: cla-signed

#4854 interpolation support for access-control.properties
  presto-plugin-toolkit/pom.xml
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
Labels: cla-signed

#4871 Do not use presto-main in product tests
  presto-product-tests/pom.xml
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCaching.java
  presto-product-tests/src/main/java/io/prestosql/tests/jdbc/TestJdbc.java
  presto-product-tests/src/main/java/io/prestosql/tests/utils/QueryAssertions.java
Labels: cla-signed

#4671 Demonstrate Spark/Iceberg and Presto/Iceberg compatibility
  presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergBasic.java
  presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestSparkCompatibility.java
Labels: cla-signed

#4880 Ignore external errors in HiveMetadata::listTableColumns
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
Labels: cla-signed

#4874 Add a test case for parse_datetime
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java
Labels: cla-signed

#4856 Make Iceberg smoke tests more consistent and less verbose
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/util/PrimitiveTypeMapBuilder.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/IcebergQueryRunner.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergOrcSmoke.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergParquetSmoke.java
Labels: cla-signed

#4536 Support the TIME type in the Iceberg connector
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/ExpressionConverter.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSink.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSource.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionData.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTable.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTransforms.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/TypeConverter.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
  presto-orc/src/main/java/io/prestosql/orc/TupleDomainOrcPredicate.java
  presto-orc/src/main/java/io/prestosql/orc/reader/ColumnReaders.java
  presto-orc/src/main/java/io/prestosql/orc/reader/LongColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/reader/TimeColumnReader.java
  presto-orc/src/main/java/io/prestosql/orc/writer/ColumnWriters.java
  presto-orc/src/main/java/io/prestosql/orc/writer/LongColumnWriter.java
  presto-orc/src/main/java/io/prestosql/orc/writer/TimeColumnWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/PrimitiveColumnReader.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/TimeMicrosColumnReader.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/MessageTypeConverter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriters.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/TimeMicrosValueWriter.java
Labels: cla-signed

#4869 Update hive-caching documentation for Rubix 0.3.16
  presto-docs/src/main/sphinx/connector/hive-caching.rst
Labels: cla-signed

#4440 Report dynamic filtering stats in QueryStats
  presto-main/src/main/java/io/prestosql/dispatcher/FailedDispatchQuery.java
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
  presto-main/src/main/java/io/prestosql/execution/QueryStats.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/test/java/io/prestosql/execution/MockManagedQueryExecution.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryStats.java
  presto-main/src/test/java/io/prestosql/server/TestBasicQueryInfo.java
  presto-main/src/test/java/io/prestosql/server/TestDynamicFilterService.java
  presto-main/src/test/java/io/prestosql/server/TestQueryStateInfo.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/SortedRangeSet.java
Labels: cla-signed

#4870 Show default values of benchmark driver options
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkDriverOptions.java
Labels: cla-signed

#4825 Implement PrestoS3FileSystem#listFiles for direct recursive listings
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#4890 Limit size of PagesIndex
  presto-main/src/main/java/io/prestosql/operator/PagesIndex.java
Labels: cla-signed

#4897 Add authentication info and reword
  presto-docs/src/main/sphinx/connector/druid.rst
Labels: cla-signed, docs

#4861 Document CTAS functionality for transactional Hive tables
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#4899 Support overriding Object methods in tests
  presto-testng-services/src/main/java/io/prestosql/testng/services/ReportUnannotatedMethods.java
  presto-testng-services/src/test/java/io/prestosql/testng/services/TestReportUnannotatedMethods.java
Labels: cla-signed

#4866 Fix AT TIME ZONE for TIMESTAMP
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/DesugarAtTimeZoneRewriter.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestamp.java
Labels: cla-signed

#4928 Mark TestHiveTransactionalTable::testReadFullAcidBucketed as flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#4924 Short circuit lazy dynamic filters on Domain.all
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilterConsumer.java
  presto-main/src/test/java/io/prestosql/server/TestDynamicFilterService.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFilterConsumer.java
Labels: cla-signed

#4945 Retry flaky tests on CI only by default
  .github/workflows/ci.yml
  presto-testng-services/pom.xml
  presto-testng-services/src/main/java/io/prestosql/testng/services/FlakyTestRetryAnalyzer.java
Labels: cla-signed

#4944 Mark flaky Hive product tests
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#4955 Support jdbc-types-mapped-to-varchar in Oracle connector
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
Labels: cla-signed

#4823 Use separate page for file based system access control
  presto-docs/src/main/sphinx/release/release-331.rst
  presto-docs/src/main/sphinx/release/release-335.rst
  presto-docs/src/main/sphinx/release/release-336.rst
  presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
  presto-docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#4954 Test for removed dynamic filters explicitly
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
Labels: cla-signed

#4963 Use grey theme for documentation
  presto-docs/src/main/sphinx/conf.py
Labels: cla-signed

#4959 Report illegal nested directory path
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveFileIterator.java
Labels: cla-signed

#4949 Require identifying flakiness's exception
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
  presto-testng-services/src/main/java/io/prestosql/testng/services/Flaky.java
  presto-testng-services/src/main/java/io/prestosql/testng/services/FlakyTestRetryAnalyzer.java
  presto-testng-services/src/test/java/io/prestosql/testng/services/TestFlakyTestRetryAnalyzer.java
Labels: cla-signed

#4952 Mark flaky PostgreSQL test
  presto-postgresql/pom.xml
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#4969 Fix logical merge conflict
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#4938 Increase AWS Glue get partition max results to 1000
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed

#4915 Test connector when running join with empty build side
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Labels: cla-signed

#4971 Rename nextTaskInfoVersion to nextTaskStatusVersion
  presto-main/src/main/java/io/prestosql/execution/SqlTask.java
Labels: cla-signed

#4344 Add human_readable timestamp function
  presto-docs/src/main/sphinx/functions/datetime.rst
  presto-main/src/main/java/io/prestosql/metadata/FunctionRegistry.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamp/HumanReadableSeconds.java
  presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestHumanReadableSeconds.java
Labels: cla-signed, syntax-needs-review

#4957 Implement JDBC ResultSet.getStatement
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/InMemoryPrestoResultSet.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoStatement.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSet.java
Labels: cla-signed

#4967 Add more aggregation pushdown test cases
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Labels: cla-signed

#4970 Improve error reporting when verification fails
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#4980 Remove unused omitTimestampPrecision field
  presto-main/src/main/java/io/prestosql/testing/TestingConnectorSession.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java
  presto-pinot/src/test/java/io/prestosql/pinot/TestPinotSplitManager.java
Labels: cla-signed

#4983 Fix CONVERT_TO_VARCHAR with arrays
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlSessionProperties.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#4985 Cleanup TestRubixCaching
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
Labels: cla-signed

#4926 Support implementing interface in tests
  presto-testng-services/src/main/java/io/prestosql/testng/services/ReportUnannotatedMethods.java
  presto-testng-services/src/test/java/io/prestosql/testng/services/TestReportUnannotatedMethods.java
Labels: cla-signed

#4982 Make testJoinWithEmptySides parametric
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Labels: cla-signed

#4887 Fix unauthorized error by the benchmark driver
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkDriver.java
  presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java
Labels: cla-signed

#4943 Add Spark/Iceberg compatibility test for nested data
  presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestSparkCompatibility.java
Labels: cla-signed

#4989 Deprecate ConnectorPageSourceProvider#createPageSource method
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorPageSourceProvider.java
Labels: cla-signed

#4987 Move noJoinReordering() to AbstractTestQueryFramework
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#4986 documentation for hive.metastore-timeout config
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#4942 Dynamic filtering for semi-joins: planner
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/TransformUncorrelatedInPredicateSubqueryToSemiJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/LimitPushDown.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ReplicateSemiJoinInDelete.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/SemiJoinNode.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/DynamicFiltersChecker.java
  presto-main/src/test/java/io/prestosql/sql/planner/AbstractPredicatePushdownTest.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestQuantifiedComparison.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/SemiJoinMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
  presto-main/src/test/java/io/prestosql/sql/planner/sanity/TestDynamicFiltersChecker.java
Labels: cla-signed

#4906 Add limitation to Session Property Manager file
  presto-docs/src/main/sphinx/admin/session-property-managers.rst
Labels: cla-signed, docs

#5003 Allow SuiteConfig to extend/configure Environment
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Hadoop.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/suite/SuiteConfig.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/suite/configs/ConfigDefault.java
Labels: cla-signed

#4748 Refactor HiveMetastore API and Implementations
  presto-hive/pom.xml
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetastoreClosure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/MetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/PartitionFilter.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/alluxio/AlluxioHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/DropStatsProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/BlockJsonSerde.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBlockEncodingSerde.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveInMemoryMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestRecordingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/UnimplementedHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergMetadataListing.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergOrcMetricsCollection.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSystemTables.java
Labels: cla-signed

#5005 Allow configuring all containers
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
Labels: cla-signed

#5009 Fix scan limit in SqlQueryManager
  presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
  presto-tests/src/test/java/io/prestosql/tests/TestQueryManager.java
Labels: cla-signed

#5010 Allow PrestoS3FileSystem to skip DeepArchive files
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/MockAmazonS3.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#5016 Update testing PostgreSQL Server to latest 12.4
  presto-docs/src/main/sphinx/connector/postgresql.rst
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#5000 Update Failsafe to 2.4.0
  pom.xml
Labels: cla-signed

#5030 Fix race condition in unregisterDynamicFilteringQuery listener
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
Labels: cla-signed

#4403 Don't implement and call deprecated ConnectorPageSourceProvider.createPageSource
  presto-pinot/src/main/java/io/prestosql/pinot/PinotPageSourceProvider.java
Labels: cla-signed

#5027 Remove reorder_joins session property
  presto-benchmark/src/main/java/io/prestosql/benchmark/SqlConsecutiveJoinBenchmark.java
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
  presto-tests/src/test/java/io/prestosql/tests/TestDictionaryAggregation.java
Labels: cla-signed

#5031 Log Presto version on startup
  presto-main/src/main/java/io/prestosql/server/Server.java
Labels: cla-signed

#4933 Add documentation for system table optimizer_rule_stats
  presto-docs/src/main/sphinx/connector/system.rst
Labels: cla-signed
