Repository trinodb/trino, pull requests merged in 2020-05, with the labels that each got.

#3598 Skip whitespace padded char data mapping test for Kudu
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduDistributedQueries.java
Labels: cla-signed

#3389 Fix SHOW CREATE TABLE if row type column contains special character
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/TypeSignatureTranslator.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestTypeSignatureTranslator.java
Labels: bug, cla-signed

#3439 Add link to book and paper pages
  presto-docs/src/main/sphinx/overview/concepts.rst
Labels: cla-signed

#3025 Move CacheStatsMBean to Airlift
  presto-main/src/main/java/io/prestosql/sql/gen/CacheStatsMBean.java
  presto-main/src/main/java/io/prestosql/sql/gen/ExpressionCompiler.java
  presto-main/src/main/java/io/prestosql/sql/gen/JoinCompiler.java
  presto-main/src/main/java/io/prestosql/sql/gen/JoinFilterFunctionCompiler.java
  presto-main/src/main/java/io/prestosql/sql/gen/OrderingCompiler.java
  presto-main/src/main/java/io/prestosql/sql/gen/PageFunctionCompiler.java
Labels: cla-signed

#3559 Accumulo type mapping cleanup
  presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/Field.java
  presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/Row.java
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/model/TestField.java
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/model/TestRow.java
Labels: cla-signed

#3585 Move some tests to appropriate place
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#3609 Preserve first close exception
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
Labels: cla-signed

#3295 Add catalog session property details
  presto-docs/src/main/sphinx/sql/set-session.rst
Labels: cla-signed

#3595 Reduce RPM size using symlinks
  presto-server-rpm/pom.xml
  presto-server-rpm/src/main/script/symlink.groovy
Labels: cla-signed

#3616 Validate that user mapping rules list is not empty
  presto-main/src/main/java/io/prestosql/server/security/UserMapping.java
Labels: cla-signed

#3625 Update to Airlift 0.196
  pom.xml
Labels: cla-signed

#3619 Remove redundant declaration
  presto-main/src/main/java/io/prestosql/operator/ExchangeOperator.java
  presto-main/src/main/java/io/prestosql/operator/MergeOperator.java
  presto-main/src/main/java/io/prestosql/operator/NestedLoopJoinOperator.java
  presto-main/src/main/java/io/prestosql/operator/PageSourceOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableScanOperator.java
  presto-main/src/test/java/io/prestosql/operator/TestDriver.java
Labels: cla-signed, maintenance

#3453 Support case insensitive identifiers in MongoDB
  presto-docs/src/main/sphinx/connector/mongodb.rst
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientConfig.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/MongoQueryRunner.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoClientConfig.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#3628 Enable tests related to DROP TABLE in MongoDB
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoDistributedQueries.java
Labels: cla-signed

#3610 Skip valueIsNull to ShortArrayBlock if possible
  presto-spi/src/main/java/io/prestosql/spi/block/ShortArrayBlockBuilder.java
Labels: cla-signed

#3617 Change Hive $file_modified_time column to timestamp with timezone type
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveColumnHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#3579 Add basic Domain, ValueSet, Range and Marker #toString
  presto-spi/src/main/java/io/prestosql/spi/predicate/AllOrNoneValueSet.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/Marker.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/Range.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/SortedRangeSet.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/ValueSet.java
Labels: cla-signed

#3633 Remove unused RowNumberNode with non empty partitionBy
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneRowNumberColumns.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneRowNumberColumns.java
Labels: cla-signed

#3651 Move delete analysis to the analyzer
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#3660 Constraint cleanup
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/Constraint.java
Labels: cla-signed

#3581 Handle decimals with 0 scale
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/PredicateUtils.java
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
  presto-parquet/src/test/java/io/prestosql/parquet/TestTupleDomainParquetPredicate.java
  presto-parquet/src/test/java/io/prestosql/parquet/predicate/TestPredicateUtils.java
Labels: cla-signed

#3642 Minor cleanup of BigQuery connector
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryClient.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryCredentialsSupplier.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryMetadata.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryPageSourceProvider.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryResultPageSource.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQuerySplitManager.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryType.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryUtil.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/Conversions.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/ReadRowsHelper.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/ReadSessionCreator.java
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/MockResponsesBatch.java
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestReadRowsHelper.java
Labels: cla-signed, maintenance

#1848 Add random-functions with range
  presto-docs/src/main/sphinx/functions/math.rst
  presto-main/src/main/java/io/prestosql/operator/scalar/MathFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestMathFunctions.java
Labels: cla-signed

#3669 Embed version in commit stacktrace
  presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
  presto-main/src/main/java/io/prestosql/transaction/InMemoryTransactionManager.java
Labels: cla-signed

#3667 Add project-off rule for SortNode
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneSortColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneSortColumns.java
Labels: cla-signed

#3653 Prune all unreferenced symbols in PruneUnreferencedOutputs.visitWindow()
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
Labels: cla-signed

#3639 Remove usage of Unsafe from UnscaledDecimal128Arithmetic
  presto-spi/src/main/java/io/prestosql/spi/type/UnscaledDecimal128Arithmetic.java
Labels: cla-signed

#3678 Use signal support from jline
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-cli/src/main/java/io/prestosql/cli/Query.java
  presto-cli/src/main/java/io/prestosql/cli/QueryPreprocessor.java
Labels: cla-signed

#3512 Optimize Elasticsearch queries that fetch no columns
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/CountQueryPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSourceProvider.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ScanQueryPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/CountResponse.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/RowDecoder.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Labels: cla-signed

#3603 Avoid adding local exchanges around trivial projection
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/AddLocalExchanges.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/RowNumberMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchangesPlans.java
Labels: cla-signed

#3375 Add overwrite insert for Hive connector
  presto-docs/src/main/sphinx/migration/from-hive.rst
Labels: cla-signed

#3632 Improve Domain#overlaps
  presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/SortedRangeSet.java
Labels: cla-signed

#3713 Fix typo on drop-schema docs
  presto-docs/src/main/sphinx/sql/drop-schema.rst
Labels: cla-signed

#3717 Prefix dynamic filter IDs
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#3708 Remove configuration for Presto version
  presto-main/etc/config.properties
  presto-main/src/main/java/io/prestosql/execution/executor/TaskExecutor.java
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
  presto-main/src/main/java/io/prestosql/server/ServerConfig.java
  presto-main/src/main/java/io/prestosql/server/ServerMainModule.java
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
  presto-main/src/main/java/io/prestosql/testing/TestingConnectorContext.java
  presto-main/src/main/java/io/prestosql/version/EmbedVersion.java
  presto-main/src/test/java/io/prestosql/server/TestServer.java
  presto-main/src/test/java/io/prestosql/server/TestServerConfig.java
  presto-main/src/test/java/io/prestosql/version/TestEmbedVersion.java
Labels: cla-signed

#3729 Refactor RubixConfigurationInitializer into dynamic provider
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixModule.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
Labels: cla-signed

#3738 Switch back to platform class loader for plugins
  presto-main/src/main/java/io/prestosql/server/PluginClassLoader.java
Labels: cla-signed

#3686 Add Remote exchange forcefully if aggregation has empty grouping set
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/AddExchanges.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestAggregations.java
Labels: cla-signed

#3604 Fix document: result type precision of Decimal operations (Add and Subtract) is wrong
  presto-docs/src/main/sphinx/functions/decimal.rst
Labels: cla-signed

#3743 Add memsql plugin to server
  presto-server/src/main/provisio/presto.xml
Labels: cla-signed

#3747 Use expression lambdas
  presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveHadoop2Plugin.java
Labels: cla-signed

#2619 Flattening optimizer for set operations
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/MergeExcept.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/MergeIntersect.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/MergeUnion.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneDistinctAggregation.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/SetOperationMerge.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/SetOperationNodeInstantiator.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestMergeExcept.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestMergeIntersect.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestMergeUnion.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneDistinctAggregation.java
Labels: cla-signed

#3714 Replace x-forwarded support with Airlift version
  pom.xml
  presto-main/src/main/java/io/prestosql/dispatcher/CoordinatorLocation.java
  presto-main/src/main/java/io/prestosql/dispatcher/DispatcherConfig.java
  presto-main/src/main/java/io/prestosql/dispatcher/LocalCoordinatorLocation.java
  presto-main/src/main/java/io/prestosql/dispatcher/QueuedStatementResource.java
  presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
  presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
  presto-main/src/main/java/io/prestosql/server/ServletSecurityUtils.java
  presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
  presto-main/src/main/java/io/prestosql/server/protocol/Query.java
  presto-main/src/main/java/io/prestosql/server/security/AuthenticationFilter.java
  presto-main/src/main/java/io/prestosql/server/security/SecurityConfig.java
  presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java
  presto-main/src/test/java/io/prestosql/dispatcher/TestDispatcherConfig.java
  presto-main/src/test/java/io/prestosql/server/TestHttpRequestSessionContext.java
  presto-main/src/test/java/io/prestosql/server/TestQuerySessionSupplier.java
  presto-main/src/test/java/io/prestosql/server/TestServer.java
  presto-main/src/test/java/io/prestosql/server/security/TestSecurityConfig.java
  presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java
Labels: cla-signed

#3736 Set thread context class loader for EventListenerFactory
  presto-main/src/main/java/io/prestosql/eventlistener/EventListenerManager.java
Labels: cla-signed

#3739 Use JDK unmodifiable collections in SPI
  presto-spi/src/main/java/io/prestosql/spi/PageBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/QueryId.java
  presto-spi/src/main/java/io/prestosql/spi/block/AbstractMapBlock.java
  presto-spi/src/main/java/io/prestosql/spi/block/AbstractRowBlock.java
  presto-spi/src/main/java/io/prestosql/spi/block/AbstractSingleMapBlock.java
  presto-spi/src/main/java/io/prestosql/spi/block/AbstractSingleRowBlock.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorBucketNodeMap.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorTableMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorTablePartitioning.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorViewDefinition.java
  presto-spi/src/main/java/io/prestosql/spi/connector/DiscretePredicates.java
  presto-spi/src/main/java/io/prestosql/spi/connector/FixedSplitSource.java
  presto-spi/src/main/java/io/prestosql/spi/connector/InMemoryRecordSet.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ProjectionApplicationResult.java
  presto-spi/src/main/java/io/prestosql/spi/connector/RecordPageSource.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/TableInfo.java
  presto-spi/src/main/java/io/prestosql/spi/memory/MemoryPoolInfo.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/SortedRangeSet.java
  presto-spi/src/main/java/io/prestosql/spi/procedure/Procedure.java
  presto-spi/src/main/java/io/prestosql/spi/resourcegroups/SelectionCriteria.java
  presto-spi/src/main/java/io/prestosql/spi/security/ConnectorIdentity.java
  presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
  presto-spi/src/main/java/io/prestosql/spi/session/SessionConfigurationContext.java
  presto-spi/src/main/java/io/prestosql/spi/statistics/ComputedStatistics.java
  presto-spi/src/main/java/io/prestosql/spi/statistics/TableStatisticsMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/type/AbstractType.java
  presto-spi/src/main/java/io/prestosql/spi/type/DecimalType.java
  presto-spi/src/main/java/io/prestosql/spi/type/TypeSignature.java
Labels: cla-signed

#3748 Fix typo in list of functions and operators document
  presto-docs/src/main/sphinx/functions/list.rst
Labels: cla-signed

#3311 Add milliseconds to formatTime
  presto-cli/src/main/java/io/prestosql/cli/FormatUtils.java
  presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java
Labels: cla-signed

#3759 Compare datetime types with equals()
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/TypeHelper.java
  presto-orc/src/main/java/io/prestosql/orc/TupleDomainOrcPredicate.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorPageSink.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/storage/OrcStorageManager.java
  presto-record-decoder/src/main/java/io/prestosql/decoder/json/AbstractDateTimeJsonValueProvider.java
  presto-record-decoder/src/main/java/io/prestosql/decoder/json/ISO8601JsonFieldDecoder.java
Labels: cla-signed

#3760 Fix hash for -0
  presto-main/src/main/java/io/prestosql/type/DoubleOperators.java
  presto-main/src/main/java/io/prestosql/type/RealOperators.java
  presto-main/src/test/java/io/prestosql/type/TestDoubleOperators.java
  presto-main/src/test/java/io/prestosql/type/TestRealOperators.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#3734 Rename S3 host to bucket
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
Labels: cla-signed

#3724 Show distributed plan by default in EXPLAIN
  presto-docs/src/main/sphinx/sql/explain.rst
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedQueries.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ExplainRewrite.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#3622 Use global AWS SDK version for Kinesis
  pom.xml
  presto-kinesis/pom.xml
Labels: cla-signed

#3758 Fix visibility of methods in Server
  presto-main/src/main/java/io/prestosql/server/Server.java
Labels: cla-signed

#3397 Improve documentation for Hive directory listing caching
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#3621 Prevent OutputBufferMemoryManager from becoming negative
  presto-main/src/main/java/io/prestosql/execution/buffer/OutputBufferMemoryManager.java
Labels: cla-signed

#3761 Use Instant to track session start time
  presto-main/src/main/java/io/prestosql/FullConnectorSession.java
  presto-main/src/main/java/io/prestosql/Session.java
  presto-main/src/main/java/io/prestosql/SessionRepresentation.java
  presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
  presto-main/src/main/java/io/prestosql/testing/TestingConnectorSession.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryStateMachine.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsLegacy.java
  presto-main/src/test/java/io/prestosql/sql/TestExpressionInterpreter.java
  presto-main/src/test/java/io/prestosql/sql/gen/TestExpressionCompiler.java
  presto-main/src/test/java/io/prestosql/type/TestDateTimeOperators.java
  presto-main/src/test/java/io/prestosql/type/TestDateTimeOperatorsLegacy.java
  presto-main/src/test/java/io/prestosql/type/TestTimeBase.java
  presto-pinot/src/test/java/io/prestosql/pinot/TestPinotSplitManager.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorSession.java
  presto-spi/src/test/java/io/prestosql/spi/block/TestingSession.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#3756 Fix InMemoryNodeManager
  presto-main/src/main/java/io/prestosql/metadata/InMemoryNodeManager.java
Labels: cla-signed

#3750 Add large file test for Rubix
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
Labels: cla-signed

#3732 Add missing binding
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveHdfsModule.java
Labels: cla-signed

#3773 Add cache write test
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
Labels: cla-signed

#3778 Use warning for principal rules deprecation
  presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
Labels: cla-signed

#3779 Fix flaky Oracle connector test
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleIntegrationSmokeTest.java
Labels: cla-signed

#3787 Use Docker Hub for testcontainers' Ryuk
  presto-product-tests-launcher/pom.xml
  presto-product-tests-launcher/src/test/java/io/prestosql/tests/product/launcher/testcontainers/TestRyukImage.java
  presto-server-rpm/pom.xml
  presto-testing/src/main/resources/testcontainers.properties
Labels: cla-signed

#3785 Remove unused local variable in ExpressionAnalysis
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalysis.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
Labels: cla-signed

#3685 Add presto-ml doc
  presto-docs/src/main/sphinx/functions.rst
  presto-docs/src/main/sphinx/functions/list.rst
  presto-docs/src/main/sphinx/functions/ml.rst
Labels: cla-signed, docs

#3792 Rename tempto config file
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeHdp3.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/tempto/tempto-configuration-for-hive3.yaml
  presto-product-tests/conf/product-tests-config-hdp3.sh
Labels: cla-signed

#3803 Implement toString() for JDBC driver Array result
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoArray.java
Labels: cla-signed

#3702 Fix matching Hive bucket filenames without leading zeros
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#3804 Add pluggable CertificateAuthenticator
  presto-docs/src/main/sphinx/develop.rst
  presto-docs/src/main/sphinx/develop/certificate-authenticator.rst
  presto-main/src/main/java/io/prestosql/server/PluginManager.java
  presto-main/src/main/java/io/prestosql/server/Server.java
  presto-main/src/main/java/io/prestosql/server/security/CertificateAuthenticator.java
  presto-main/src/main/java/io/prestosql/server/security/CertificateAuthenticatorManager.java
  presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
  presto-spi/src/main/java/io/prestosql/spi/Plugin.java
  presto-spi/src/main/java/io/prestosql/spi/security/CertificateAuthenticator.java
  presto-spi/src/main/java/io/prestosql/spi/security/CertificateAuthenticatorFactory.java
Labels: cla-signed

#3801 Improved concurrency for Elasticsearch calls
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchConfig.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchConfig.java
Labels: cla-signed

#3755 Fix support for creating Hive external tables using CTAS
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveOutputTableHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/LocationService.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTable.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
Labels: cla-signed

#3797 Remove deprecated missingAttributeException usage
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/SemanticExceptions.java
Labels: cla-signed

#3807 Remove obsolete comment
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
Labels: cla-signed

#3808 Mark test class as single-threaded
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
Labels: cla-signed

#3809 Small fixups
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed

#3735 Add support for passthrough Elasticsearch queries
  presto-elasticsearch/pom.xml
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSourceProvider.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchSplitManager.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchTableHandle.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/PassthroughQueryPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#3818 Eliminate deprecated stream method usage
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ReorderJoins.java
Labels: cla-signed

#3817 Fix Launcher local startup failure
  presto-product-tests-launcher/pom.xml
  presto-testing/src/main/resources/testcontainers.properties
Labels: cla-signed

#3820 Don't start Rubix server by default on coordinator
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixModule.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixConfig.java
Labels: cla-signed

#3752 Add Java requirement to JDBC driver documentation
  presto-docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed

#3814 Use varchar for Elasticsearch passthrough query result
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSourceProvider.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/PassthroughQueryPageSource.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#3710 Add ISO date and time examples
  presto-docs/src/main/sphinx/functions/datetime.rst
Labels: cla-signed

#3826 Fix documentation beginQuery and cleanupQuery
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
Labels: cla-signed

#3823 Fix Rubix flaky tests
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCaching.java
Labels: cla-signed, test

#3795 Increase process numbers to 1000 from 500 in Oracle test
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
  presto-oracle/src/test/resources/spfileXE.ora
Labels: cla-signed

#3727 Remove Unused Code in TypeSignatureParser
  presto-main/src/main/java/io/prestosql/operator/TypeSignatureParser.java
Labels: cla-signed

#3825 Remove unused constants
  presto-main/src/test/java/io/prestosql/type/TestTimestampBase.java
Labels: cla-signed

#3837 Remove unused test dependency
  presto-hive/pom.xml
Labels: cla-signed

#3627 Prevent HMS from collecting stats when creating external tables
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/FailureAwareThriftMetastoreClient.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClient.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBasicTableStatistics.java
Labels: cla-signed

#3832 Fix bigquery.credentials-key property in BigQuery document
  presto-docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#3771 Add cache for delegation token in Hive thrift metastore
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
Labels: cla-signed

#3842 Remove obsolete TODO
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed

#3629 Allow SystemAccessControl to listen to events
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-main/src/main/java/io/prestosql/testing/TestingEventListenerManager.java
  presto-main/src/test/java/io/prestosql/execution/TestCommitTask.java
  presto-main/src/test/java/io/prestosql/execution/TestDeallocateTask.java
  presto-main/src/test/java/io/prestosql/execution/TestPrepareTask.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryStateMachine.java
  presto-main/src/test/java/io/prestosql/execution/TestStartTransactionTask.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#3847 Add headers in EXPLAIN docs
  presto-docs/src/main/sphinx/sql/explain.rst
Labels: cla-signed

#3860 Avoid repeated calls to ConnectorMetadata#getTableProperties()
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PropertyDerivations.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/StreamPropertyDerivations.java
Labels: cla-signed

#3863 Unwrap Rubix CachingFileSystem
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
Labels: cla-signed

#3859 Fix allow using aggregations in format()
  presto-main/src/main/java/io/prestosql/sql/analyzer/AggregationAnalyzer.java
  presto-main/src/test/java/io/prestosql/sql/query/TestFormat.java
  presto-parser/src/main/java/io/prestosql/sql/tree/DefaultTraversalVisitor.java
Labels: cla-signed

#3725 Handle the case where a partition column has null value
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSource.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplit.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Labels: cla-signed

#3862 Make TestRubixCaching tests more resilient
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
Labels: cla-signed

#3849 Fix localtime in legacy timestamp semantics
  presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctions.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsLegacy.java
Labels: cla-signed

#3870 Change enum visibility in tests
  presto-product-tests/src/main/java/io/prestosql/tests/hive/BucketingType.java
Labels: cla-signed

#3867 Cleanup TestHiveCreateExternalTable
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTable.java
Labels: cla-signed

#3875 Remove session from HdfsContext, remove cache enabled session property
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsEnvironment.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSessionProperties.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
Labels: cla-signed

#3876 Remove unnecessary json serialization and unused methods
  presto-main/src/main/java/io/prestosql/metadata/BoundVariables.java
Labels: cla-signed

#3887 Fix formatting error in release notes
  presto-docs/src/main/sphinx/release/release-334.rst
Labels: cla-signed

#3885 Add support for reduce_agg in window functions
  presto-main/src/main/java/io/prestosql/operator/WindowFunctionDefinition.java
  presto-main/src/main/java/io/prestosql/operator/window/AbstractWindowFunctionSupplier.java
  presto-main/src/main/java/io/prestosql/operator/window/AggregateWindowFunction.java
  presto-main/src/main/java/io/prestosql/operator/window/ReflectionWindowFunctionSupplier.java
  presto-main/src/main/java/io/prestosql/operator/window/WindowFunctionSupplier.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/test/java/io/prestosql/operator/TestWindowOperator.java
  presto-main/src/test/java/io/prestosql/sql/query/TestReduceAgg.java
Labels: cla-signed

#3890 Remove unused BETWEEN operator
  presto-main/src/main/java/io/prestosql/metadata/FunctionRegistry.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/metadata/OperatorNotFoundException.java
  presto-main/src/main/java/io/prestosql/operator/annotations/FunctionsParserHelper.java
  presto-main/src/main/java/io/prestosql/operator/scalar/annotations/OperatorValidator.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/gen/BetweenCodeGenerator.java
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionInterpreter.java
  presto-main/src/main/java/io/prestosql/type/BigintOperators.java
  presto-main/src/main/java/io/prestosql/type/BooleanOperators.java
  presto-main/src/main/java/io/prestosql/type/CharOperators.java
  presto-main/src/main/java/io/prestosql/type/DateOperators.java
  presto-main/src/main/java/io/prestosql/type/DecimalInequalityOperators.java
  presto-main/src/main/java/io/prestosql/type/DoubleOperators.java
  presto-main/src/main/java/io/prestosql/type/IntegerOperators.java
  presto-main/src/main/java/io/prestosql/type/IntervalDayTimeOperators.java
  presto-main/src/main/java/io/prestosql/type/IntervalYearMonthOperators.java
  presto-main/src/main/java/io/prestosql/type/IpAddressOperators.java
  presto-main/src/main/java/io/prestosql/type/RealOperators.java
  presto-main/src/main/java/io/prestosql/type/SmallintOperators.java
  presto-main/src/main/java/io/prestosql/type/TimeOperators.java
  presto-main/src/main/java/io/prestosql/type/TimeWithTimeZoneOperators.java
  presto-main/src/main/java/io/prestosql/type/TimestampOperators.java
  presto-main/src/main/java/io/prestosql/type/TimestampWithTimeZoneOperators.java
  presto-main/src/main/java/io/prestosql/type/TinyintOperators.java
  presto-main/src/main/java/io/prestosql/type/UnknownOperators.java
  presto-main/src/main/java/io/prestosql/type/UuidOperators.java
  presto-main/src/main/java/io/prestosql/type/VarbinaryOperators.java
  presto-main/src/main/java/io/prestosql/type/VarcharOperators.java
  presto-main/src/test/java/io/prestosql/operator/TestFilterAndProjectOperator.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/ObjectIdFunctions.java
  presto-spi/src/main/java/io/prestosql/spi/function/OperatorType.java
Labels: cla-signed
