Repository trinodb/trino, pull requests merged in 2020-11, with the labels that each got.

#5765 Refactor unused var in presto-mongodb
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoColumnHandle.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSink.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSinkProvider.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
Labels: cla-signed

#5763 Refactor unused var in presto-bigquery
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryClient.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryConnectorFactory.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryConnectorModule.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQuerySplitManager.java
Labels: cla-signed

#5774 Relax assertion
  presto-main/src/test/java/io/prestosql/operator/TestTableFinishOperator.java
Labels: cla-signed

#5768 Fix Hive applyProjection performance issue
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
Labels: cla-signed

#5743 Add char, varchar wellformedness checks
  presto-spi/src/main/java/io/prestosql/spi/type/CharType.java
  presto-spi/src/main/java/io/prestosql/spi/type/Slices.java
  presto-spi/src/main/java/io/prestosql/spi/type/VarcharType.java
Labels: cla-signed

#5796 Remove TestUninterruptably
  presto-product-tests/src/main/java/io/prestosql/tests/utils/TestUninterruptably.java
Labels: cla-signed

#5803 Log if LogTestDurationListener
  presto-testng-services/src/main/java/io/prestosql/testng/services/LogTestDurationListener.java
Labels: cla-signed

#5813 Fix flaky TestHttpRemoteTask#testDynamicFilters
  presto-main/src/test/java/io/prestosql/server/remotetask/TestHttpRemoteTask.java
Labels: cla-signed

#5717 Add ALTER TABLE SET AUTHORIZATION
  presto-docs/src/main/sphinx/sql/alter-table.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetastoreClosure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/alluxio/AlluxioHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/UnimplementedHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
  presto-main/src/main/java/io/prestosql/execution/SetTableAuthorizationTask.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/server/QueryExecutionFactoryModule.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/util/StatementUtils.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/AstVisitor.java
  presto-parser/src/main/java/io/prestosql/sql/tree/SetTableAuthorization.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestStatementBuilder.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSqlStandardAccessControlChecks.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#5811 Mark TestHiveStorageFormats.testCreatePartitionedTableAs as @Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed

#5806 Add SecurityContext#toString
  presto-main/src/main/java/io/prestosql/security/SecurityContext.java
  presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
Labels: cla-signed

#2674 Allow dynamic filtering with comparison operators
  presto-docs/src/main/sphinx/admin/dynamic-filtering.rst
  presto-main/src/main/java/io/prestosql/operator/JoinUtils.java
  presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
  presto-main/src/main/java/io/prestosql/sql/DynamicFilters.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFiltersCollector.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/JoinMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
  presto-main/src/test/java/io/prestosql/sql/planner/sanity/TestDynamicFiltersChecker.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
  presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java
Labels: cla-signed

#5713 Improve window frames further
  presto-main/src/main/java/io/prestosql/operator/window/WindowPartition.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
  presto-main/src/test/java/io/prestosql/sql/query/TestWindowFrameGroups.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/WindowFrame.java
Labels: cla-signed

#5807 Handle Elasticsearch indexes without properties
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearch6IntegrationSmokeTest.java
Labels: cla-signed

#5808 Upgrade coral to resolve catalog correctly for underlying tables
  pom.xml
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#5826 Properly enable LogTestDurationListener in GHA
  .github/workflows/ci.yml
Labels: cla-signed

#5822 Remove unused var in presto-kudu
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/properties/KuduTableProperties.java
Labels: cla-signed

#5829 Mark TestHiveBasicTableStatistics.testInsertBucketed as @Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBasicTableStatistics.java
Labels: cla-signed

#5835 Fix pattern in @Flaky annotation
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
Labels: cla-signed

#5598 Use Accumulo in Docker for unit tests
  presto-accumulo/pom.xml
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/AccumuloQueryRunner.java
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/MiniAccumuloConfigUtil.java
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloClient.java
  presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestingAccumuloServer.java
Labels: cla-signed

#5840 Add Hive view syntax smoke test
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#5773 Remove unused PruneUnreferencedOutputs#typeAnalyzer field
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/BasePlanTest.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestEliminateSorts.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestMergeWindows.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java
  presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestSetFlattening.java
Labels: cla-signed

#5769 Implement getRow for AbstractPrestoResultSet
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
Labels: cla-signed, jdbc

#5836 Fix method name
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#5849 Allow resetting system properties in session builder
  presto-main/src/main/java/io/prestosql/Session.java
Labels: cla-signed

#5762 kafka connector: optimize Kafka timestamp test case.
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationPushDown.java
Labels: cla-signed

#5850 Fix incorrect correlation mapping
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#5851 Use consistent NaN behavior for max functions
  presto-main/src/main/java/io/prestosql/operator/aggregation/AbstractMinMaxAggregationFunction.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/MaxNAggregationFunction.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/minmaxby/AbstractMinMaxBy.java
  presto-main/src/main/java/io/prestosql/operator/aggregation/minmaxby/MaxByNAggregationFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/AbstractGreatestLeast.java
  presto-main/src/main/java/io/prestosql/operator/scalar/ArrayMaxFunction.java
  presto-main/src/main/java/io/prestosql/util/MinMaxCompare.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/minmaxby/TestMinMaxByAggregation.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/minmaxby/TestMinMaxByNAggregation.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestMathFunctions.java
  presto-main/src/test/java/io/prestosql/type/TestArrayOperators.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTableStatistics.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#5858 Drop writing min/max statistics for TIMESTAMP columns for Hive tables
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/Statistics.java
Labels: cla-signed

#5867 Mark partitioning TestCsv tests as @Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestCsv.java
Labels: cla-signed

#5866 Fix Launcher failure when suite remaining time is negative
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
Labels: bug, test

#5841 Remove unused arg in TestGeometryUnionGeoAggregation#assertArrayAggAndGeometryUnion
  presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/aggregation/TestGeometryUnionGeoAggregation.java
Labels: cla-signed

#5843 Remove unused variables
  presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/AccumuloConnector.java
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
  presto-main/src/test/java/io/prestosql/operator/TestAggregationOperator.java
  presto-main/src/test/java/io/prestosql/operator/aggregation/minmaxby/TestMinMaxByAggregation.java
  presto-main/src/test/java/io/prestosql/operator/scalar/FunctionAssertions.java
  presto-ml/src/main/java/io/prestosql/plugin/ml/ModelUtils.java
  presto-orc/src/test/java/io/prestosql/orc/TestOrcLz4.java
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapConfig.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/TypeUtils.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/metadata/TestShardPredicate.java
  presto-spi/src/test/java/io/prestosql/spi/predicate/TestTupleDomain.java
  presto-tpcds/src/test/java/io/prestosql/plugin/tpcds/EstimateAssertion.java
Labels: cla-signed

#5862 Update to testcontainers released version
  pom.xml
Labels: cla-signed

#5882 Mark TestIcebergCreateTable as @Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergCreateTable.java
Labels: cla-signed

#5883 Add equals and hashCode to CatalogName in toolkit
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/CatalogName.java
Labels: cla-signed

#5887 Remove Iceberg README.md
  presto-iceberg/README.md
Labels: cla-signed

#5891 Use toImmutableList collector
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/StaticMetastoreLocator.java
Labels: cla-signed

#5893 Temporarily disable failing test
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#5782 Remove leftover directories during rpm uninstall
  presto-server-rpm/src/main/rpm/postremove
  presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Labels: cla-signed

#5704 Simplify 128 bit operations
  presto-spi/src/main/java/io/prestosql/spi/type/UnscaledDecimal128Arithmetic.java
Labels: cla-signed

#5751 Fix incorrect comment in Kafka.InternalField
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaInternalFieldManager.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaInternalFieldManager.java
Labels: cla-signed

#5896 Stop Suite execution when time limit exhausted
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
Labels: cla-signed

#5888 Make create table test rely on wider supported type
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#5894 Update airbase to 104
  pom.xml
Labels: cla-signed

#5870 Add support for limit pushdown in MongoDB
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoMetadata.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoTableHandle.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#5921 Use CentOS 8
  docker/Dockerfile
Labels: cla-signed

#4862 Add subnet based topology
  presto-main/src/main/java/io/prestosql/execution/scheduler/SubnetBasedTopology.java
  presto-main/src/main/java/io/prestosql/execution/scheduler/SubnetTopologyConfig.java
  presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelectorConfig.java
  presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelectorModule.java
  presto-main/src/test/java/io/prestosql/execution/scheduler/TestSubnetTopology.java
  presto-main/src/test/java/io/prestosql/execution/scheduler/TestSubnetTopologyConfig.java
  presto-spi/src/main/java/io/prestosql/spi/HostAddress.java
Labels: cla-signed

#5931 Cleanup styling for copy icon
  presto-docs/src/main/sphinx/conf.py
  presto-docs/src/main/sphinx/static/copy-icon.svg
  presto-docs/src/main/sphinx/static/presto.css
Labels: cla-signed

#5900 Add boolean to DataMappingSmokeTest
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/BaseTestOracleDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3638 Parallelize stats update
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestSemiTransactionalHiveMetastore.java
Labels: cla-signed

#5930 Make TypeSignature final and @Immutable
  presto-spi/src/main/java/io/prestosql/spi/type/NamedTypeSignature.java
  presto-spi/src/main/java/io/prestosql/spi/type/RowFieldName.java
  presto-spi/src/main/java/io/prestosql/spi/type/TypeSignature.java
  presto-spi/src/main/java/io/prestosql/spi/type/TypeSignatureParameter.java
Labels: cla-signed

#5926 Assume tests container is started immediately
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#5935 Improve logging when FlakyTestRetryAnalyzer not enabled
  presto-testng-services/src/main/java/io/prestosql/testng/services/FlakyTestRetryAnalyzer.java
Labels: cla-signed

#5936 Fix FlakyTestRetryAnalyzer in product tests
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#5939 Add toString for Event classes in SPI
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryCompletedEvent.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryCreatedEvent.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/SplitCompletedEvent.java
Labels: cla-signed

#5934 Type conversion cleanup in hive stats handling
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/Statistics.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestStatistics.java
Labels: cla-signed

#5937 Fix suite-3 definition
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/suite/suites/Suite3.java
Labels: cla-signed

#5794 Reuse immutable partition fields in Glue partition conversion
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/converter/GlueToPrestoConverter.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/util/Memoizers.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueToPrestoConverter.java
Labels: cla-signed

#5909 Return meaningful message when view stale
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#5907 Update to ZooKeeper 3.5.8
  pom.xml
  presto-pinot/pom.xml
Labels: cla-signed

#5948 Remove dependency on presto-tests from Druid, BigQuery
  presto-bigquery/pom.xml
  presto-druid/pom.xml
Labels: maintenance, test

#5949 Avoid readByte and appendByte in nulls to bits serde
  presto-spi/src/main/java/io/prestosql/spi/block/EncoderUtil.java
Labels: cla-signed

#5954 Rename session property to match session property names
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
Labels: cla-signed

#5957 Require Java 11.0.7
  README.md
  presto-docs/src/main/sphinx/installation/deployment.rst
  presto-main/src/main/java/io/prestosql/server/PrestoSystemRequirements.java
Labels: cla-signed

#5885 Cache hashcode for TypeSignature class
  presto-spi/src/main/java/io/prestosql/spi/type/TypeSignature.java
Labels: WIP, cla-signed

#4934 Allow configuring HDFS replication factor directly in hive.properties
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfigurationInitializer.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHdfsConfig.java
Labels: cla-signed

#5958 Clarify Java requirement
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed

#5820 Remove unused var in presto-product-tests
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/ContainerUtil.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#5594 Wait for and build split with dynamic filter in Kudu
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientConfig.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSessionProperties.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSplitManager.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/KuduQueryRunnerFactory.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationDynamicFilter.java
Labels: cla-signed

#5968 Use proper logging API to log exception
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentListener.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environments.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/StatisticsFetcher.java
Labels: cla-signed

#5945 Populate view owner groups for view access control
  presto-main/src/main/java/io/prestosql/execution/CreateMaterializedViewTask.java
  presto-main/src/main/java/io/prestosql/execution/CreateViewTask.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analyzer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/QueryExplainer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/TypeAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeInputRewrite.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeOutputRewrite.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ExplainRewrite.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowStatsRewrite.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/StatementRewrite.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
  presto-main/src/main/java/io/prestosql/testing/QueryRunner.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-main/src/main/java/io/prestosql/testing/TestingGroupProvider.java
  presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
  presto-testing/src/main/java/io/prestosql/testing/DistributedQueryRunner.java
  presto-testing/src/main/java/io/prestosql/testing/StandaloneQueryRunner.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/ThriftQueryRunner.java
Labels: cla-signed

#5964 Update Postgresql JDBC to 42.2.10
  pom.xml
  presto-postgresql/pom.xml
Labels: cla-signed

#5974 Mark shouldFailOnFirstSerializationError as @Flaky
  presto-tests/pom.xml
  presto-tests/src/test/java/io/prestosql/tests/TestQuerySerializationFailures.java
Labels: cla-signed

#5971 Fix retries for TestIcebergCreateTable
  presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergCreateTable.java
Labels: cla-signed

#5980 Test Hive VIEW with JOIN and subquery
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#5983 Adjust product test timeout
  .github/workflows/ci.yml
Labels: cla-signed

#5982 Use different table names to prevent a race when running in parallel
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#5984 TestPostgreSqlIntegrationSmokeTest small cleanup
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Labels: cla-signed

#5985 Add main method to MySQL query runner
  presto-mysql/pom.xml
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/MySqlQueryRunner.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlCaseInsensitiveMapping.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlTypeMapping.java
Labels: cla-signed, maintenance

#5989 Remove stats fetcher to test for hangs
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentListener.java
Labels: cla-signed

#5970 Dump Launcher threads when test about to exhaust run time limit
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
  presto-testng-services/src/main/java/io/prestosql/testng/services/LogTestDurationListener.java
Labels: cla-signed

#6000 Fix ATDQ.testDataMappingSmokeTest for MemSQL
  presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlDistributedQueries.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlDistributedQueries.java
Labels: cla-signed

#5996 Mark TestHiveCreateTable as @Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateTable.java
Labels: cla-signed

#5994 Do not push partial aggregations into TableScan
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushDistinctLimitIntoTableScan.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/Patterns.java
Labels: cla-signed

#5991 Record scheduled time in QueryCompletedEvent
  presto-main/src/main/java/io/prestosql/event/QueryMonitor.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryStatistics.java
  presto-tests/src/test/java/io/prestosql/execution/TestEventListenerBasic.java
  presto-tests/src/test/java/io/prestosql/execution/TestEventListenerWithSplits.java
Labels: cla-signed

#6001 Bump hive-apache to 3.1.2-5
  pom.xml
Labels: cla-signed

#6003 Use TEXTFILE format in TestHiveViews
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#6010 Remove redundant list item bullet
  presto-docs/src/main/sphinx/release/release-346.md
Labels: cla-signed, docs

#6014 Make RedshiftClientModule#getConnectionFactory static
  presto-redshift/src/main/java/io/prestosql/plugin/redshift/RedshiftClientModule.java
Labels: cla-signed

#5992 Stream container statistics
  presto-product-tests-launcher/pom.xml
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentListener.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/StatisticsFetcher.java
Labels: cla-signed

#5987 Enable unused variable error prone check
  pom.xml
  presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveFileSystemAbfsAccessKey.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/ViewReaderUtil.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-main/src/main/java/io/prestosql/type/UnknownType.java
  presto-main/src/test/java/io/prestosql/execution/buffer/TestBroadcastOutputBuffer.java
  presto-main/src/test/java/io/prestosql/operator/TestAnnotationEngineForScalars.java
  presto-main/src/test/java/io/prestosql/operator/TestGroupedTopNBuilder.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/type/UnscaledDecimal128Arithmetic.java
Labels: cla-signed

#6016 Make sure redirected table column types match source column types
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ApplyTableScanRedirection.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
Labels: cla-signed

#5872 Add scan physical size stats to query completed event
  presto-main/src/main/java/io/prestosql/event/QueryMonitor.java
  presto-main/src/main/java/io/prestosql/execution/Input.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
  presto-main/src/main/java/io/prestosql/sql/planner/InputExtractor.java
  presto-main/src/test/java/io/prestosql/execution/TestInput.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryStateMachine.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryInputMetadata.java
Labels: cla-signed

#6023 TestApplyTableScanRedirection cleanup
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ApplyTableScanRedirection.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
Labels: cla-signed

#5997 Use PT timeout on CI only
  .github/workflows/ci.yml
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#6020 Fix Launcher failure when suite remaining time is zero
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#6028 Get expected CLI version from resource file
  presto-product-tests/pom.xml
  presto-product-tests/src/main/java/io/prestosql/tests/cli/TestPrestoCli.java
  presto-product-tests/src/main/resources/presto-cli-version.txt
Labels: cla-signed

#6032 Add missing comma
  presto-docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed

#6034 Fix local maven build of presto-testng-services
  presto-testng-services/src/main/java/io/prestosql/testng/services/FlakyTestRetryAnalyzer.java
Labels: cla-signed

#6033 Replace assertUntilTimeout with assertEventually
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#6031 Make Presto web UI more accessible when executing tests
  presto-testing/src/main/java/io/prestosql/testing/DistributedQueryRunner.java
Labels: cla-signed

#6043 Attempt to fix TestIcebergCreateTable retries
  presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergCreateTable.java
Labels: cla-signed

#6045 Allow to control FlakyTestRetryAnalyzer with session property
  presto-testng-services/src/main/java/io/prestosql/testng/services/FlakyTestRetryAnalyzer.java
Labels: cla-signed

#6056 Remove createPostgreSqlQueryRunner overload
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/PostgreSqlQueryRunner.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Labels: cla-signed

#6053 Fix query runner leak in TestPrometheusIntegrationTests3
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationTests3.java
Labels: cla-signed

#6065 Add link to statistics page from Hive connector
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-docs/src/main/sphinx/optimizer/statistics.rst
Labels: cla-signed, docs

#6058 Remove PairLike class from Prometheus tests
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/PairLike.java
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusRecordSet.java
Labels: cla-signed, maintenance, test

#6061 Add product test for nested Hive views
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#6007 Allow predicate pushdown after aggregation pushdown
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcMetadata.java
Labels: cla-signed

#6086 Update JDBI version to 3.9.1
  pom.xml
Labels: cla-signed

#6089 Update JDBI to 3.17.0
  pom.xml
  presto-iceberg/pom.xml
Labels: cla-signed

#6064 Add 347 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-347.md
Labels: cla-signed, release-notes

#6068 Add explanation for calcite-core dependency exclusion
  pom.xml
Labels: cla-signed

#6078 Simplify loading columns into cache in CachingJdbcClient
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
Labels: cla-signed

#6099 Remove unused exception declaration
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationTests1.java
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationTests2.java
Labels: cla-signed

#6062 Document ldap.ignore-referrals config
  presto-docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed, docs

#6084 Make filterColumns to be coherent with other filter methods
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SystemTableAwareAccessControl.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataListing.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/security/InjectedConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlySystemAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#6096 Remove version-based condition from TestHiveBasicTableStatistics
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBasicTableStatistics.java
Labels: cla-signed

#6090 Ensure no operator info is ignored
  presto-main/src/main/java/io/prestosql/operator/OperatorStats.java
Labels: cla-signed

#6088 Fix container startup time measurements when start retried
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
Labels: cla-signed

#6110 Use Cache instead of LoadingCache
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
Labels: cla-signed

#6095 Separate tested behavior from mechanics in the test
  presto-main/src/test/java/io/prestosql/sql/planner/TestUnwrapCastInComparison.java
Labels: cla-signed, maintenance, test

#6107 Allow running multiple suites
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
Labels: cla-signed

#6114 Update operator id always
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
Labels: bug, cla-signed

#6067 Propagate more information from ConnectorSession to ConnectionFactory
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ConnectionFactory.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/DriverConnectionFactory.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcPageSink.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcRecordCursor.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/RetryingConnectionFactory.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareConnectionFactory.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestCachingJdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestRetryingConnectionFactory.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingDatabase.java
  presto-druid/src/main/java/io/prestosql/plugin/druid/DruidJdbcClient.java
  presto-druid/src/test/java/io/prestosql/plugin/druid/BaseDruidIntegrationSmokeTest.java
  presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClient.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlClient.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OraclePoolConnectionFactory.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixSplitManager.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlClient.java
  presto-redshift/src/main/java/io/prestosql/plugin/redshift/RedshiftClient.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerClient.java
Labels: cla-signed

#6122 SImplify benchmark block serde
  presto-main/src/test/java/io/prestosql/execution/buffer/BenchmarkBlockSerde.java
  presto-main/src/test/java/io/prestosql/execution/buffer/BenchmarkDataGenerator.java
Labels: cla-signed

#6123 Mark TestSyncPartitionMetadata as @Flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSyncPartitionMetadata.java
Labels: cla-signed

#6136 Use case sensitive alias in planner test
  presto-main/src/test/java/io/prestosql/sql/planner/TestUnwrapCastInComparison.java
Labels: cla-signed, test

#6125 Add convenience method for getting assignment during aggregation pushdown
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/AggregateFunctionRule.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementAvgDecimal.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementAvgFloatingPoint.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementCount.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementMinMax.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/ImplementSum.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/ImplementAvgBigint.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/ImplementAvgBigint.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/ImplementAvgBigint.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/ImplementSqlServerStddevPop.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/ImplementSqlServerStdev.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/ImplementSqlServerVariance.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/ImplementSqlServerVariancePop.java
Labels: cla-signed

#6091 Fix indeterminism in PlanNodeStats mergeability check
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/HashCollisionPlanNodeStats.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanNodeStats.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/WindowPlanNodeStats.java
Labels: cla-signed

#6129 Use DockerImageName in TestingMemSqlServer
  presto-memsql/pom.xml
  presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestingMemSqlServer.java
Labels: cla-signed, maintenance

#6074 Support writing TIMESTAMPTZ with JSON encoder
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/format/MillisecondsSinceEpochFormatter.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/format/SecondsSinceEpochFormatter.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestJsonEncoder.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestMillisecondsJsonDateTimeFormatter.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestSecondsJsonDateTimeFormatter.java
Labels: cla-signed

#6101 Disable cache refresh for bulk metastore calls
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
Labels: cla-signed

#6041 Simplify BlockEncodingSerde by merging TypeSerde into BlockEncodingSerde
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBlockEncodingSerde.java
  presto-main/src/main/java/io/prestosql/metadata/InternalBlockEncodingSerde.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-main/src/test/java/io/prestosql/metadata/TestInternalBlockEncodingSerde.java
  presto-spi/src/main/java/io/prestosql/spi/block/BlockEncodingSerde.java
  presto-spi/src/main/java/io/prestosql/spi/block/MapBlockEncoding.java
  presto-spi/src/main/java/io/prestosql/spi/block/SingleMapBlockEncoding.java
  presto-spi/src/main/java/io/prestosql/spi/type/TypeSerde.java
  presto-spi/src/test/java/io/prestosql/spi/block/TestingBlockEncodingSerde.java
  presto-spi/src/test/java/io/prestosql/spi/type/TestTypeSerde.java
Labels: cla-signed
