Repository trinodb/trino, pull requests merged in 2020-12, with the labels that each got.

#6116 Document insert overwrite limitation
  presto-docs/src/main/sphinx/migration/from-hive.rst
Labels: cla-signed

#6153 Mark TestEventListenerBasic.testPlanningFailure flaky
  presto-tests/src/test/java/io/prestosql/execution/TestEventListenerBasic.java
Labels: cla-signed

#6144 Supplement type mappings in JDBC connectors
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
  presto-druid/src/main/java/io/prestosql/plugin/druid/DruidJdbcClient.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#6119 Fix terminal width detection in the CLI
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-cli/src/main/java/io/prestosql/cli/ConsolePrinter.java
  presto-cli/src/main/java/io/prestosql/cli/InputReader.java
  presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java
  presto-cli/src/main/java/io/prestosql/cli/TerminalUtils.java
  presto-cli/src/test/java/io/prestosql/cli/TestInsecureQueryRunner.java
  presto-cli/src/test/java/io/prestosql/cli/TestQueryRunner.java
Labels: cla-signed

#6126 Improve serde performance for Int96 blocks
  presto-spi/src/main/java/io/prestosql/spi/block/Int96ArrayBlock.java
  presto-spi/src/main/java/io/prestosql/spi/block/Int96ArrayBlockBuilder.java
  presto-spi/src/main/java/io/prestosql/spi/block/Int96ArrayBlockEncoding.java
Labels: cla-signed

#6176 Reduce unexpected Integer object creation
  presto-main/src/main/java/io/prestosql/operator/LookupJoinPageBuilder.java
  presto-main/src/main/java/io/prestosql/operator/SortedPositionLinks.java
Labels: cla-signed

#6174 Remove extra stat call when opening Iceberg files
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSourceProvider.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplit.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed

#6165 Mark testArrayOfMapOfStruct and testDoubleNaNInfinity as @Flaky
  presto-hive/pom.xml
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/AbstractTestParquetReader.java
Labels: cla-signed

#6185 Ensure exactly single delivery of query completion event
  presto-main/src/main/java/io/prestosql/dispatcher/DispatchManager.java
  presto-main/src/main/java/io/prestosql/dispatcher/DispatchQuery.java
  presto-main/src/main/java/io/prestosql/dispatcher/FailedDispatchQuery.java
  presto-main/src/main/java/io/prestosql/dispatcher/FailedDispatchQueryFactory.java
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQuery.java
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQueryFactory.java
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
  presto-tests/src/test/java/io/prestosql/execution/TestEventListenerBasic.java
Labels: cla-signed

#6197 Remove deprecated isVarcharType and isCharType methods
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-spi/src/main/java/io/prestosql/spi/type/Chars.java
  presto-spi/src/main/java/io/prestosql/spi/type/Varchars.java
Labels: cla-signed

#6199 Update to ANTLR 4.9
  pom.xml
Labels: cla-signed

#3712 S3 streaming upload with multipart upload api
  presto-docs/src/main/sphinx/connector/hive-s3.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/HiveS3Config.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3ConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/MockAmazonS3.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestHiveS3Config.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#6121 Make JdbcTypeHandle.columnSize optional
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcTypeHandle.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingH2JdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingJdbcTypeHandle.java
  presto-druid/src/main/java/io/prestosql/plugin/druid/DruidJdbcClient.java
  presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClient.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/ImplementAvgBigint.java
  presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlClient.java
  presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/ImplementAvgBigint.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlClient.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/ImplementAvgBigint.java
  presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerClient.java
Labels: cla-signed

#6188 Accept Scope at ExpressionTestUtils.resolveFunctionCalls()
  presto-main/src/test/java/io/prestosql/sql/ExpressionTestUtils.java
Labels: cla-signed

#6219 Ensure query-created event is called before query-completed event
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQuery.java
  presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQueryFactory.java
Labels: cla-signed

#6212 Report malformed Presto JDBC URL better
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriverUri.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverUri.java
Labels: cla-signed, jdbc

#6225 Fix typo in PostgreSQL type mapping test
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#6231 Fix 'testCreateExternalTableWithFieldSeparator' flakiness
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#6224 Verify before getting element from a list
  presto-main/src/main/java/io/prestosql/metadata/SignatureBinder.java
Labels: cla-signed

#6229 Test no predicate pushdown in case of forced mapping to varchar
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed, enhancement, test

#6226 Limit number of threads created by TestSqlStageExecution
  presto-main/src/test/java/io/prestosql/execution/TestSqlStageExecution.java
Labels: cla-signed

#6227 Update @Flaky annotation
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed, maintenance, test

#6044 Add documentation for subnet based topology
  presto-docs/src/main/sphinx/admin/properties-node-scheduler.rst
Labels: cla-signed

#6237 Fix dynamic system tables for clusters with multiple coordinators
  presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
  presto-main/src/main/java/io/prestosql/connector/system/CoordinatorSystemTablesProvider.java
  presto-main/src/main/java/io/prestosql/connector/system/DelegatingSystemTablesProvider.java
Labels: cla-signed

#6213 Improve split generation for symlinked tables
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestHiveUtil.java
Labels: cla-signed

#6207 Verify ResultSetMetaData column type declaration against reference driver
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSetTimezone.java
Labels: cla-signed, jdbc, test

#307 Support TIMESTAMP WITH TIME ZONE as ZonedDateTime in JDBC
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriver.java
Labels: cla-signed, enhancement, jdbc

#6221 Remove imprecise conversion with Number in MaterializedResult
  presto-main/src/main/java/io/prestosql/testing/MaterializedResult.java
Labels: cla-signed, maintenance, test

#6203 Add aggregation pushdown test cases with unsupported functions
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/BaseMySqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
  presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Labels: cla-signed, test

#6245 Fix test case for INSERT with unsupported type
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: bug, cla-signed, test

#6244 Fix qdigest type braces in docs
  presto-docs/src/main/sphinx/functions/aggregate.rst
  presto-docs/src/main/sphinx/functions/qdigest.rst
Labels: bug, cla-signed, docs

#6259 Fix checkstyle in presto-testing
  presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Labels: cla-signed

#6186 Support GCS and Azure for Iceberg
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/InternalIcebergConnectorFactory.java
Labels: cla-signed

#6215 Improve reporting of multiple SQLExceptions in JdbcPageSink#finish
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcPageSink.java
Labels: cla-signed

#6169 Close terminal on JVM shutdown
  presto-cli/src/main/java/io/prestosql/cli/Console.java
  presto-cli/src/main/java/io/prestosql/cli/TerminalUtils.java
Labels: cla-signed

#6206 Fix failure in JDBC when TIME nanos overflow
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
Labels: cla-signed

#6249 Improve message when INSERT fails due to non-whitespace truncation
  presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/BaseTestOracleDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#6243 Test ResultSet.getString for a DATE
  presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
Labels: cla-signed, enhancement, test

#6265 Mark TestIcebergParquetSmoke as @Flaky
  presto-iceberg/pom.xml
  presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
Labels: cla-signed, maintenance, test

#6255 Add methods for defining session properties with validation
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/session/PropertyMetadataUtil.java
Labels: cla-signed

#6272 Mark TestParquetReader.testComplexNestedStructs as @Flaky
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/AbstractTestParquetReader.java
Labels: cla-signed, maintenance, test

#6261 Add legacy hive view translation property to config property table
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#6275 Clarify java 11.0.7 requirement in release notes
  presto-docs/src/main/sphinx/release/release-347.md
Labels: cla-signed

#6284 Remove legacy-generic-column-mapping JDBC config property
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcConfig.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestBaseJdbcConfig.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixConfig.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixConfig.java
Labels: cla-signed

#6268 Add server SSL debug sectn; edit debug for Presto
  presto-docs/src/main/sphinx/installation/deployment.rst
  presto-docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed, docs

#6296 Use Node as isDeleteTarget argument
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
  presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViewsLegacy.java
  presto-product-tests/src/main/resources/tempto-configuration.yaml
Labels: bug, cla-signed

#6297 Simplify assertions in Hive timestamp precision test
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed

#6300 Use String internally for prepared statement parameter conversion
  presto-jdbc/src/main/java/io/prestosql/jdbc/ObjectCasts.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
Labels: cla-signed, enhancement, jdbc

#6253 Deprecate EMRFS
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/S3FileSystemType.java
Labels: cla-signed

#6130 Use assertThatThrownBy in TestSetSessionTask
  presto-main/src/test/java/io/prestosql/execution/TestSetSessionTask.java
Labels: cla-signed

#6298 Mark testExpiredAccessToken test flaky
  presto-main/src/test/java/io/prestosql/server/security/oauth2/TestOAuth2WebUiAuthenticationFilter.java
Labels: cla-signed

#6301 Accept LocalDate as prepared statement parameter
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
Labels: cla-signed, enhancement, jdbc

#6277 Fix Aggregation Pushdown docs
  presto-docs/src/main/sphinx/functions/aggregate.rst
  presto-docs/src/main/sphinx/optimizer/pushdown.rst
Labels: bug, cla-signed, docs

#6327 Some quick clean ups for GroupedTopNRowNumberAccumulator
  presto-main/src/main/java/io/prestosql/operator/GroupedTopNRowNumberAccumulator.java
Labels: cla-signed

#6331 Disable testLargeIn on MemSQL
  presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlDistributedQueries.java
Labels: cla-signed

#6332 Add vararg constructor to EnvironmentProvider
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentProvider.java
Labels: cla-signed

#6228 Extract user and password from PostgreSQL jdbc url
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/PostgreSqlQueryRunner.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlDistributedQueries.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed, maintenance

#6319 Remove incorrect verify in JdbcMetadata
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
Labels: cla-signed

#6329 Get columns from table handle if available
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed, maintenance

#5884 Assert coercion behavior with Hive
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
Labels: cla-signed

#6336 Restore name normalization in JdbcMetadata.getColumnHandles
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
Labels: cla-signed

#6335 Use node reference comparison to dermine if table is delete target
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#6321 Refactor TypeCoercion.coerceTypeBase
  presto-main/src/main/java/io/prestosql/type/TypeCoercion.java
Labels: cla-signed

#6258 Add 348 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-348.md
Labels: cla-signed, release-notes

#6338 Remove EnvironmentContext use from HiveMetastoreClosure
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetastoreClosure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
Labels: cla-signed

#6342 Add jdbc api stats for table scan redirection
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/JdbcClientStats.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Labels: cla-signed

#6344 Use smaller table in testInsert and testCreateTableAsSelect
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#6346 Mark TestMemorySmoke#testCrossJoinDynamicFiltering as @Flaky
  presto-memory/pom.xml
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
Labels: cla-signed, maintenance, test

#6302 Validate connection-url format for JDBC connectors
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcConfig.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestBaseJdbcConfig.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJmxStats.java
  presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidJdbcPlugin.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlPlugin.java
  presto-redshift/src/test/java/io/prestosql/plugin/redshift/TestRedshiftPlugin.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerPlugin.java
Labels: cla-signed

#6230 Give Prometheus test classes meaningful names
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationMetrics.java
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationSchema.java
  presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationStatus.java
Labels: cla-signed, maintenance, test

#6340 Allow implementations of AbstractRowEncoder to support Structural type
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/AbstractRowEncoder.java
Labels: cla-signed

#6334 Add DataType for TIMESTAMP TZ, TIME TZ
  presto-testing/src/main/java/io/prestosql/testing/datatype/DataType.java
Labels: cla-signed, test

#6354 Fix typo: picoSecond -> picosecond
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamp/TimeWithTimeZoneToTimestampCast.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timestamptz/ToIso8601.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/AtTimeZone.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/AtTimeZoneWithOffset.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/DateAdd.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/DateTrunc.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/ExtractHour.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/ExtractMillisecond.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/ExtractMinute.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/ExtractSecond.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/TimeWithTimeZoneOperators.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/TimeWithTimeZoneToTimeCast.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/TimeWithTimeZoneToTimeWithTimeZoneCast.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/TimeWithTimeZoneToTimestampWithTimeZoneCast.java
  presto-main/src/main/java/io/prestosql/operator/scalar/timetz/TimeWithTimeZoneToVarcharCast.java
  presto-main/src/main/java/io/prestosql/type/DateTimes.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimeWithTimeZone.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimeWithTimeZoneType.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestamp.java
  presto-spi/src/main/java/io/prestosql/spi/type/LongTimestampWithTimeZone.java
  presto-spi/src/main/java/io/prestosql/spi/type/TimeWithTimeZoneTypes.java
Labels: cla-signed, maintenance

#6356 Update dataFormats supported by Kafka JSON encoder for temporal types
  presto-docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#6359 Use era agnostic year in temporal patterns used in testing
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/OracleDataTypes.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixSqlTypeMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-testing/src/main/java/io/prestosql/testing/datatype/DataType.java
Labels: cla-signed, test

#6357 Move EXISTS, .* and correlation tests to engine-only
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
  presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed, maintenance, test

#6366 Remove use of legacy mappings from PostgreSQL connector
  presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed, maintenance

#6367 Implement type mappings in H2 testing client
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingH2JdbcClient.java
Labels: cla-signed, maintenance, test

#6380 Tighten allowed characters for non-delimited identifiers
  presto-parser/src/main/java/io/prestosql/sql/tree/Identifier.java
Labels: cla-signed

#6378 Decrease the number of access control checks in StatementAnalyzer
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#6388 Add main method to Druid query runner
  presto-druid/pom.xml
  presto-druid/src/test/java/io/prestosql/plugin/druid/DruidQueryRunner.java
  presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidIntegrationSmokeTest.java
  presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidIntegrationSmokeTestLatest.java
Labels: cla-signed

#5865 Fix incorrect result when aggregating count BigQuery view
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQuerySplitManager.java
  presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
Labels: cla-signed

#6379 Update AWS SDK to 1.11.921
  pom.xml
Labels: cla-signed

#6398 Remove FixedCountRetryAnalyzer
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationPushDown.java
Labels: cla-signed, maintenance, test

#6410 Allow specifying entires in TestTable by columns
  presto-testing/src/main/java/io/prestosql/testing/sql/TestTable.java
Labels: cla-signed, enhancement, test

#6407 Embed --fail-at-end in MAVEN_TEST
  .github/workflows/ci.yml
Labels: cla-signed

#6411 Update Kafka Schema Registry to 5.5.2
  pom.xml
  presto-kafka/pom.xml
  presto-pinot/pom.xml
  presto-testing-kafka/src/main/java/io/prestosql/testing/kafka/TestingKafka.java
Labels: cla-signed

#6416 Pass SchemaProviders to SchemaRegistry
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/ConfluentModule.java
Labels: cla-signed

#6420 Mark testInsertIntoTable is flaky
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed

#6385 Add test with try and column with at sign
  presto-tests/src/test/java/io/prestosql/execution/TestTry.java
Labels: cla-signed

#6368 Avoid listing all indexes to check for existence
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Labels: cla-signed

#6406 Update testcontainers to 1.15.1
  pom.xml
Labels: cla-signed

#6422 Unify varbinary type mapping tests
  presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlTypeMapping.java
  presto-oracle/src/test/java/io/prestosql/plugin/oracle/AbstractTestOracleTypeMapping.java
  presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixTypeMapping.java
  presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
  presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerTypeMapping.java
Labels: cla-signed, maintenance, test

#6404 Implement dynamic filtering for joins using IS NOT DISTINCT FROM
  presto-main/src/main/java/io/prestosql/sql/DynamicFilters.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/JoinMatcher.java
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
  presto-main/src/test/java/io/prestosql/sql/planner/sanity/TestDynamicFiltersChecker.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
  presto-tests/pom.xml
  presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java
Labels: cla-signed

#6408 Minor code improvements in CachingJdbcClient
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
Labels: cla-signed

#6441 Use the updated extension in KafkaQueryRunner
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
Labels: cla-signed

#6445 Add release notes about ENV placeholders
  presto-docs/src/main/sphinx/release/release-328.rst
Labels: cla-signed, docs

#6432 Update dynamic filtering documentation for IS NOT DISTINCT FROM
  presto-docs/src/main/sphinx/admin/dynamic-filtering.rst
Labels: cla-signed, docs

#6453 Update airlift to 202
  pom.xml
Labels: cla-signed

#6456 Add 349 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-349.md
Labels: cla-signed, release-notes

#6460 Add 350 release notes
  presto-docs/src/main/sphinx/release.rst
  presto-docs/src/main/sphinx/release/release-349.md
  presto-docs/src/main/sphinx/release/release-350.md
Labels: cla-signed

#6470 Add star image
  .github/star.png
Labels: cla-signed
