Repository trinodb/trino, pull requests merged in 2020-02, with the labels that each got.

#2697 Increase logo size in UI
  presto-main/src/main/resources/webapp/assets/presto.css
Labels: cla-signed

#2702 Fix exception message
  pom.xml
  presto-spi/src/main/java/io/prestosql/spi/predicate/AllOrNoneValueSet.java
  presto-spi/src/test/java/io/prestosql/spi/predicate/TestAllOrNoneValueSet.java
Labels: cla-signed

#2575 Fix querying information schema with empty name as predicate
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
  presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaMetadata.java
  presto-tests/src/test/java/io/prestosql/tests/TestInformationSchemaConnector.java
Labels: cla-signed

#2669 Allow for CTAS table creation to external tables when write are enabled
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTable.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTableDisabled.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#2710 Rename canImpersonateUser to checkCanImpersonateUser
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/server/QuerySessionSupplier.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlySystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#2628 Add documentation for SQL LIKE
  presto-docs/src/main/sphinx/functions/comparison.rst
  presto-docs/src/main/sphinx/functions/string.rst
Labels: cla-signed

#2713 Remove unnecessary and invalid GuardedBy in ArbitraryOutputBuffer
  presto-main/src/main/java/io/prestosql/execution/buffer/ArbitraryOutputBuffer.java
Labels: cla-signed

#2726 Remove unused method
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
Labels: cla-signed

#2724 Extract HiveHdfsModule
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveHdfsModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveModule.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergModule.java
Labels: cla-signed

#2735 Remove unused method
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ReorderJoins.java
Labels: cla-signed

#2733 Implement PreparedStatement.setTimestamp with Calendar
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
Labels: cla-signed

#2576 Join minor cleanups
  presto-main/src/main/java/io/prestosql/operator/LookupJoinOperator.java
Labels: cla-signed

#2731 Update to Airbase 97
  pom.xml
Labels: cla-signed

#2633 Disable socket factory for pre JDK11
  presto-cli/src/main/java/io/prestosql/cli/QueryRunner.java
  presto-client/src/main/java/io/prestosql/client/OkHttpUtil.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriver.java
Labels: cla-signed

#2738 Implement DatabaseMetaData#getPrimaryKeys
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDatabaseMetaData.java
Labels: cla-signed

#2722 Fix CBO broadcast join reordering
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q03.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q10.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q19.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q37.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q42.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q47.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q52.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q53.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q54.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q55.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q57.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q63.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q65.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q71.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q82.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q84.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q89.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q07.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q08.plan.txt
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ReorderJoins.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestReorderJoins.java
Labels: cla-signed

#2685 Fix LocalDynamicFiltersCollector#getPredicate for multiple co-located joins
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilter.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFiltersCollector.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFilter.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
Labels: cla-signed, correctness

#2706 Allow procedures to have optional arguments with default values
  presto-main/src/main/java/io/prestosql/execution/CallTask.java
  presto-spi/src/main/java/io/prestosql/spi/procedure/Procedure.java
  presto-testing/src/main/java/io/prestosql/testing/TestingProcedures.java
  presto-tests/src/test/java/io/prestosql/tests/TestProcedureCall.java
  presto-tests/src/test/java/io/prestosql/tests/TestProcedureCreation.java
Labels: cla-signed

#2708 Replace AuthenticatedIdentity with Identity
  presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
  presto-main/src/main/java/io/prestosql/server/security/AuthenticationFilter.java
  presto-main/src/main/java/io/prestosql/server/security/Authenticator.java
  presto-main/src/main/java/io/prestosql/server/security/CertificateAuthenticator.java
  presto-main/src/main/java/io/prestosql/server/security/JsonWebTokenAuthenticator.java
  presto-main/src/main/java/io/prestosql/server/security/KerberosAuthenticator.java
  presto-main/src/main/java/io/prestosql/server/security/PasswordAuthenticator.java
  presto-main/src/test/java/io/prestosql/server/TestHttpRequestSessionContext.java
  presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
Labels: cla-signed

#2754 Close Connection in test
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
Labels: cla-signed

#2742 Fix flaky TestJdbcIntegrationSmokeTest tests
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcIntegrationSmokeTest.java
Labels: cla-signed

#2756 Fix escaping during URI creation in PrestoS3FileSystem
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
Labels: cla-signed

#2632 Add bogus row to support listing empty catalogs
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
Labels: cla-signed

#2615 Extract Aggregation's mask symbol in SymbolsExtractor
  presto-main/src/main/java/io/prestosql/sql/planner/SymbolsExtractor.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneAggregationSourceColumns.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/ValidateDependenciesChecker.java
Labels: cla-signed

#2752 Ensure hive table exists when running Hive procedures
  presto-hive/src/main/java/io/prestosql/plugin/hive/CreateEmptyPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/DropStatsProcedure.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#2766 Retry downloading dependencies
  .github/workflows/checks.yml
  .github/workflows/module-tests.yml
  .github/workflows/product-tests.yml
  bin/retry
Labels: cla-signed

#2764 Verify schema exists for USE statement
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDatabaseMetaData.java
  presto-main/src/main/java/io/prestosql/execution/UseTask.java
  presto-tests/src/test/java/io/prestosql/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#2765 Decrease memory usage for TestTopNRowNumberOperator
  presto-main/src/test/java/io/prestosql/operator/TestTopNRowNumberOperator.java
Labels: cla-signed

#2750 Minor changes for Hive view support
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveConfig.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive.properties
Labels: cla-signed

#2739 Update to Airlift 0.192
  pom.xml
Labels: cla-signed

#2751 Require running on Java 11
  presto-main/pom.xml
  presto-main/src/main/java/io/prestosql/server/PrestoSystemRequirements.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/run-presto.sh
  presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Labels: cla-signed

#2749 Cleanup calls to semanticException
  presto-main/src/main/java/io/prestosql/execution/CallTask.java
  presto-main/src/main/java/io/prestosql/execution/CommentTask.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/sql/planner/ExpressionInterpreter.java
  presto-main/src/main/java/io/prestosql/sql/planner/LiteralInterpreter.java
Labels: cla-signed

#2771 Fix reused table name across tests
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#2590 Simplify information schema code
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaTable.java
Labels: cla-signed

#2778 Retry more compilations
  .github/workflows/module-tests.yml
Labels: cla-signed

#2747 Keep tailing containers output in Launcher `env up`
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
Labels: cla-signed, ready to merge

#2772 Use JAX-RS HttpHeaders in HttpRequestSessionContext
  presto-main/src/main/java/io/prestosql/dispatcher/QueuedStatementResource.java
  presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
  presto-main/src/test/java/io/prestosql/server/MockHttpServletRequest.java
  presto-main/src/test/java/io/prestosql/server/TestHttpRequestSessionContext.java
  presto-main/src/test/java/io/prestosql/server/TestQuerySessionSupplier.java
Labels: cla-signed

#2701 Add limitation for alter schema usage
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#2762 Allow running ANALYZE skipping all column level statistics
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#2729 Add extension point for Glue metastore column statistics
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/DisabledGlueColumnStatisticsProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueColumnStatisticsProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/converter/GlueInputConverter.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed

#2781 Limit pushdown for Elasticsearch connector
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSource.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchTableHandle.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/client/ElasticsearchClient.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
Labels: cla-signed

#2795 Avoid variable within format pattern
  presto-main/src/main/java/io/prestosql/sql/planner/PlanFragmenter.java
Labels: cla-signed

#2714 Honor node-scheduler.include-coordinator in optimized local scheduling
  presto-main/src/main/java/io/prestosql/execution/scheduler/UniformNodeSelector.java
Labels: cla-signed

#2768 Validate session catalog in role commands
  presto-main/src/main/java/io/prestosql/execution/CreateRoleTask.java
  presto-main/src/main/java/io/prestosql/execution/DropRoleTask.java
  presto-main/src/main/java/io/prestosql/execution/GrantRolesTask.java
  presto-main/src/main/java/io/prestosql/execution/RevokeRolesTask.java
  presto-main/src/main/java/io/prestosql/execution/SetRoleTask.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataUtil.java
  presto-main/src/test/java/io/prestosql/execution/TestSetRoleTask.java
  presto-tests/src/test/java/io/prestosql/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#2788 Balance ArbitraryOutputBuffer distribution over clients
  presto-main/src/main/java/io/prestosql/execution/buffer/ArbitraryOutputBuffer.java
  presto-main/src/test/java/io/prestosql/execution/buffer/TestArbitraryOutputBuffer.java
Labels: cla-signed

#2718 Remove redundant joins
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveRedundantJoin.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestRemoveRedundantJoin.java
Labels: cla-signed

#2798 Add @Nullable annotations
  presto-main/src/main/java/io/prestosql/operator/ScanFilterAndProjectOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableScanOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableScanWorkProcessorOperator.java
Labels: cla-signed

#2804 Remove unneeded check
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed

#2803 Add physical_input_bytes to system.runtime.tasks
  presto-main/src/main/java/io/prestosql/connector/system/TaskSystemTable.java
  presto-product-tests/src/main/java/io/prestosql/tests/TestSystemConnector.java
  presto-product-tests/src/main/resources/sql-tests/testcases/system/selectInformationSchemaColumns.result
  presto-tests/src/test/java/io/prestosql/connector/system/TestSystemConnector.java
Labels: cla-signed

#2704 Add docs for Hive metastore caching
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#2777 Update GitHub actions badge
  README.md
Labels: cla-signed

#2809 Allow running Presto on Linux aarch64
  pom.xml
  presto-main/src/main/java/io/prestosql/server/PrestoSystemRequirements.java
Labels: cla-signed

#2812 Do not install HTTP event client in server
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
Labels: cla-signed

#2796 Move Hive procedures to separate package
  presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/DropStatsProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/HiveProcedureModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/Procedures.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/UnregisterPartitionProcedure.java
Labels: cla-signed

#2808 Move dependency to correct section
  presto-main/pom.xml
Labels: cla-signed

#2806 Run Glue tests
  .github/workflows/module-tests.yml
Labels: cla-signed

#2816 Specify glue metastore config in Glue section
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#2822 Remove unnecessary copies in StreamingAggregationOperator
  presto-main/src/main/java/io/prestosql/operator/StreamingAggregationOperator.java
Labels: cla-signed

#2815 Doc node.id value restriction
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed

#2819 Add parameternames to dependency management
  pom.xml
  presto-plugin-toolkit/pom.xml
  presto-thrift-testing-server/pom.xml
Labels: cla-signed

#2833 Enable TestAvroSchemaUrl#testPartitionedTableWithLongColumnType on Hive 3
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAvroSchemaUrl.java
Labels: cla-signed

#2836 Fix usage of Consumer<Void>
  presto-main/src/test/java/io/prestosql/memory/TestMemoryTracking.java
  presto-parquet/src/main/java/io/prestosql/parquet/reader/PrimitiveColumnReader.java
Labels: cla-signed

#2848 Fix Launcher `env up` command
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
Labels: cla-signed

#2849 Export kafka ports for running tests locally
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeKafka.java
Labels: cla-signed

#2779 Resolve some unchecked/rawtypes warnings
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHoleConnector.java
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHoleMetadata.java
  presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/ArrayDecoder.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaConsumerFactory.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/properties/KuduTableProperties.java
  presto-main/src/main/java/io/prestosql/cost/ComposableStatsCalculator.java
  presto-main/src/main/java/io/prestosql/operator/PagesIndex.java
  presto-main/src/main/java/io/prestosql/operator/PartitionedLookupSourceFactory.java
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
  presto-main/src/main/java/io/prestosql/sql/planner/EffectivePredicateExtractor.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
  presto-main/src/main/java/io/prestosql/testing/MaterializedResult.java
  presto-main/src/main/java/io/prestosql/testing/MaterializedRow.java
  presto-main/src/test/java/io/prestosql/block/ColumnarTestUtils.java
  presto-main/src/test/java/io/prestosql/block/TestRowBlock.java
  presto-main/src/test/java/io/prestosql/operator/BenchmarkPartitionedOutputOperator.java
  presto-main/src/test/java/io/prestosql/spiller/TestBinaryFileSpiller.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestEqualityInference.java
  presto-main/src/test/java/io/prestosql/tests/QueryTemplate.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorMetadata.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestAggregations.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
  presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Labels: cla-signed

#2839 Improve error message for invalid role catalog
  presto-main/src/main/java/io/prestosql/Session.java
Labels: cla-signed

#2707 Make the first characters of function description capitalized
  presto-docs/src/main/sphinx/develop/functions.rst
  presto-main/src/main/java/io/prestosql/operator/aggregation/ArbitraryAggregationFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/ArrayFilterFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/ArrayTransformFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/BitwiseFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/ConcatFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/DataSizeFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/Greatest.java
  presto-main/src/main/java/io/prestosql/operator/scalar/HyperLogLogFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/JoniRegexpFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/JoniRegexpReplaceLambdaFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/Least.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MapEntriesFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MapFromEntriesFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MapTransformKeysFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MapTransformValuesFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MapZipWithFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MathFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/MultimapFromEntriesFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/Re2JRegexpFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/Re2JRegexpReplaceLambdaFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/SessionFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/SplitToMapFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/SplitToMultimapFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/TryFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/TypeOfFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/UrlFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
  presto-main/src/main/java/io/prestosql/operator/scalar/WilsonInterval.java
  presto-main/src/main/java/io/prestosql/operator/scalar/WordStemFunction.java
  presto-main/src/main/java/io/prestosql/operator/scalar/ZipWithFunction.java
  presto-main/src/main/java/io/prestosql/type/UuidOperators.java
  presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkRoundFunction.java
  presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java
  presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/ObjectIdFunctions.java
  presto-product-tests/src/main/resources/sql-tests/testcases/binary_functions/checkBinaryFunctionsRegistered.result
  presto-product-tests/src/main/resources/sql-tests/testcases/catalog/showFunctions.result
  presto-product-tests/src/main/resources/sql-tests/testcases/horology_functions/checkHorologyFunctionsRegistered.result
  presto-product-tests/src/main/resources/sql-tests/testcases/math_functions/checkMathFunctionsRegistered.result
  presto-product-tests/src/main/resources/sql-tests/testcases/regex_functions/checkRegexFunctionsRegistered.result
  presto-product-tests/src/main/resources/sql-tests/testcases/string_functions/checkStringFunctionsRegistered.result
  presto-product-tests/src/main/resources/sql-tests/testcases/url_functions/checkUrlFunctionsRegistered.result
  presto-teradata-functions/src/main/java/io/prestosql/teradata/functions/TeradataStringFunctions.java
Labels: cla-signed

#2879 Revert "Wait for running queries issued during grace period to finish"
  presto-main/src/main/java/io/prestosql/server/GracefulShutdownHandler.java
Labels: cla-signed

#2709 Remove option to disable internal JWT
  presto-main/src/main/java/io/prestosql/server/InternalAuthenticationManager.java
  presto-main/src/main/java/io/prestosql/server/InternalCommunicationConfig.java
  presto-main/src/test/java/io/prestosql/server/TestInternalCommunicationConfig.java
Labels: cla-signed

#2712 Change JWT configuration properties to match naming convention
  presto-main/src/main/java/io/prestosql/server/security/JsonWebTokenConfig.java
  presto-main/src/test/java/io/prestosql/server/security/TestJsonWebTokenConfig.java
Labels: cla-signed

#2859 Extend SortExpressionExtractor for BETWEEN predicate
  presto-benchmark/src/test/java/io/prestosql/benchmark/BenchmarkInequalityJoin.java
  presto-main/src/main/java/io/prestosql/sql/planner/SortExpressionExtractor.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestSortExpressionExtractor.java
Labels: cla-signed

#2004 Add native parquet writer
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/ParquetTester.java
  presto-parquet/pom.xml
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ArrayColumnWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ColumnChunk.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ColumnWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/MapColumnWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/MessageTypeConverter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetCompressor.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetDataOutput.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetSchemaConverter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetTypeConverter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetTypeVisitor.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriterOptions.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriters.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/PrimitiveColumnWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/StructColumnWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/repdef/DefLevelIterable.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/repdef/DefLevelIterables.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/repdef/RepLevelIterable.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/repdef/RepLevelIterables.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/BigintValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/BooleanValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/CharValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/DateValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/DecimalValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/DoubleValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/IntegerValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/PrimitiveValueWriter.java
  presto-parquet/src/main/java/io/prestosql/parquet/writer/valuewriter/RealValueWriter.java
Labels: cla-signed, ready to merge

#2736 Informative message by limit matcher
  presto-main/src/test/java/io/prestosql/sql/planner/assertions/LimitMatcher.java
Labels: cla-signed

#2874 Cleanup S3 filesystem tests
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3select/S3SelectCsvRecordReader.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Labels: cla-signed

#2648 Wait for running queries issued during grace period to finish
  presto-main/src/main/java/io/prestosql/server/GracefulShutdownHandler.java
Labels: cla-signed

#2862 Avoid getPositionsSizeInBytes call in calculateCompactSize
  presto-spi/src/main/java/io/prestosql/spi/block/DictionaryBlock.java
Labels: cla-signed

#2612 Always compact pages in OrderBy operator
  presto-main/src/main/java/io/prestosql/operator/OrderByOperator.java
Labels: cla-signed

#2861 Resolve IS DISTINCT FROM operator only for join columns
  presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestSpatialJoins.java
  presto-main/src/main/java/io/prestosql/operator/SimplePagesHashStrategy.java
Labels: cla-signed

#2857 Remove obsolete product tests README.md content
  presto-product-tests/README.md
Labels: cla-signed

#2853 Remove redundant remote exchanges due to missing unaliasing
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q04.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q10.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q17.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q24_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q24_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q25.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q29.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q39_1.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q39_2.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q49.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q54.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q64.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q68.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q69.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q72.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q77.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q95.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q02.plan.txt
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpch/q18.plan.txt
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
Labels: cla-signed

#2828 Add Hive 3 metastore config for CSV support
  presto-docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#2896 Remove obsolete TODO notes
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#2829 Document query management properties
  presto-docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed

#2831 Document server and HTTP server log properties
  presto-docs/src/main/sphinx/admin/properties.rst
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed

#1870 Add missing support for bucket sort order in Glue
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/converter/GlueInputConverter.java
Labels: cla-signed

#2906 Add access control check for SHOW CRETAE TABLE and VIEW
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
Labels: cla-signed

#2899 Remove access control checkCanShowTablesMetadata
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlySystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#2920 Add sort asc/desc icons to table
  presto-main/src/main/resources/webapp/assets/presto.css
Labels: cla-signed

#2881 Update docker images version to 27
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
  presto-product-tests/conf/product-tests-defaults.sh
Labels: cla-signed

#2946 Request delegate credentials for Kerberos
  presto-client/src/main/java/io/prestosql/client/SpnegoHandler.java
Labels: cla-signed

#2917 Use JAXB for Base64 encoding in aws sdk with Java 9+
  pom.xml
  presto-hive/pom.xml
Labels: cla-signed

#2932 Add identity destroy to free up authenticator resources
  presto-main/src/main/java/io/prestosql/dispatcher/QueuedStatementResource.java
  presto-main/src/main/java/io/prestosql/server/security/AuthenticationFilter.java
  presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
Labels: cla-signed

#2922 Do not return coordinator in NodeSelector.allNodes() if include-coord…
  presto-main/src/main/java/io/prestosql/execution/scheduler/NodeScheduler.java
  presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelector.java
  presto-main/src/main/java/io/prestosql/execution/scheduler/UniformNodeSelector.java
Labels: cla-signed

#2931 Rename to Web UI
  presto-docs/src/main/sphinx/admin/web-interface.rst
Labels: cla-signed

#2334 Implement optional check that query has partition filter
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSessionProperties.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTableHandle.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/Optionals.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/PlanSanityChecker.java
  presto-main/src/main/java/io/prestosql/sql/planner/sanity/TableScanValidator.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/Constraint.java
Labels: cla-signed

#2947 Fix typo in docs
  presto-docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed, docs

#2949 Fail parsing dates beyond a representable range
  presto-main/src/main/java/io/prestosql/type/DateOperators.java
  presto-main/src/main/java/io/prestosql/util/DateTimeUtils.java
  presto-main/src/test/java/io/prestosql/type/TestDateTimeOperatorsBase.java
Labels: cla-signed

#2950 Refactor blackhole connector
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHoleMetadata.java
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHolePageSink.java
  presto-blackhole/src/test/java/io/prestosql/plugin/blackhole/TestBlackHoleMetadata.java
  presto-blackhole/src/test/java/io/prestosql/plugin/blackhole/TestBlackHoleSmoke.java
Labels: cla-signed

#2970 Memoize ATN visit states to avoid exponential backtracking
  presto-parser/src/main/java/io/prestosql/sql/parser/ErrorHandler.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParserErrorHandling.java
Labels: cla-signed

#2834 Use apply-site-xml-override from image
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdp3/apply-site-xml-override.sh
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdp3/hadoop-entrypoint.sh
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdp3/site-override.xslt
Labels: cla-signed

#2770 Implement JDBC PreparedStatement.getMetaData
  presto-client/src/main/java/io/prestosql/client/ClientTypeSignature.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
Labels: cla-signed

#2966 Elasticsearch name clash: omit conflicting keys.
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
Labels: cla-signed
