Repository trinodb/trino, pull requests merged in 2020-03, with the labels that each got.

#2926 Add show tables access control
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlySystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#2983 Report DNs on multiple matches
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java
Labels: cla-signed

#2826 Throw meaningful error when accessing ACID on Hive < 3
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#2985 Allow to pass additional JVM opts to tempto
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#2984 Use reentrant executor in CachingHiveMetastoreModule
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/ReentrantBoundedExecutor.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestReentrantBoundedExecutor.java
Labels: cla-signed

#2986 Improve log message for FileBasedAccessControl
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopConnectorFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/HiveSecurityModule.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControlModule.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorConnectorFactory.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/security/RaptorSecurityModule.java
Labels: cla-signed

#2991 Remove HiveQueryRunner factory overload taking security
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTable.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTableDisabled.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileBasedSecurity.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/TestParquetDecimalScaling.java
Labels: cla-signed, maintenance

#3000 Hide register_partition procedure behind toggle
  presto-docs/src/main/sphinx/connector/hive.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveConfig.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive.properties
Labels: RELEASE-BLOCKER, cla-signed

#2870 Format maps and lists with varbinary
  presto-cli/src/main/java/io/prestosql/cli/AlignedTablePrinter.java
  presto-cli/src/main/java/io/prestosql/cli/CsvPrinter.java
  presto-cli/src/test/java/io/prestosql/cli/TestAlignedTablePrinter.java
  presto-cli/src/test/java/io/prestosql/cli/TestCsvPrinter.java
Labels: cla-signed

#2898 Increase test timeout to consider full GC times
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveMetadata.java
  presto-main/src/test/java/io/prestosql/operator/TestWorkProcessor.java
  presto-main/src/test/java/io/prestosql/operator/TestWorkProcessorPipelineSourceOperator.java
Labels: cla-signed

#2924 Procedure system access control
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-main/src/main/java/io/prestosql/execution/CallTask.java
  presto-main/src/main/java/io/prestosql/metadata/QualifiedObjectName.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/test/java/io/prestosql/execution/TestCallTask.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/CatalogSchemaRoutineName.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/SchemaRoutineName.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#3021 Compile also with Java 13 on CI
  .github/workflows/checks.yml
Labels: cla-signed

#2011 Cache AWS Current Region Result
  presto-hive/src/main/java/io/prestosql/plugin/hive/aws/AwsCurrentRegionHolder.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3select/PrestoS3ClientFactory.java
Labels: cla-signed

#3026 Lowercase names passed to *RoutineName
  presto-spi/src/main/java/io/prestosql/spi/connector/CatalogSchemaRoutineName.java
  presto-spi/src/main/java/io/prestosql/spi/connector/SchemaRoutineName.java
Labels: cla-signed

#3028 Allow specifying rounding mode when encoding decimals
  presto-spi/src/main/java/io/prestosql/spi/type/Decimals.java
Labels: cla-signed

#3029 Make randomTableSuffix utility method public
  presto-testing/src/main/java/io/prestosql/testing/sql/TestTable.java
Labels: cla-signed

#2673 Add ALTER SCHEMA SET AUTHORIZATION syntax
  presto-docs/src/main/sphinx/connector/hive-security.rst
  presto-docs/src/main/sphinx/sql/alter-schema.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetastoreClosure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/UnimplementedHiveMetastore.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-main/src/main/java/io/prestosql/execution/SetSchemaAuthorizationTask.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/util/StatementUtils.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/AstVisitor.java
  presto-parser/src/main/java/io/prestosql/sql/tree/SetSchemaAuthorization.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestStatementBuilder.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedAccessControl.java
  presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
Labels: cla-signed

#3034 Improve InterfaceTestUtils
  presto-spi/src/test/java/io/prestosql/spi/testing/InterfaceTestUtils.java
  presto-spi/src/test/java/io/prestosql/spi/testing/TestInterfaceTestUtils.java
Labels: cla-signed

#3016 Bump aws-sdk to 1.11.697
  pom.xml
Labels: cla-signed

#3057 Restore ConnectorIdentity constructor parameter checks
  presto-spi/src/main/java/io/prestosql/spi/security/ConnectorIdentity.java
Labels: cla-signed

#3043 Remove unused transaction handle parameter
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConnector.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/TransactionalMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/DropStatsProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/UnregisterPartitionProcedure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/AccessControlMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/HiveSecurityModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardSecurityModule.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#3054 Test Hive connector without SOCKS
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-tls-kerberos/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdfs-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-cross-realm/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-wire-encryption/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-no-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hive-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-kms-hdfs-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-kms-hdfs-no-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-kerberos-hives/hive1.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-kerberos-hives/hive2.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-mixed-hives/hive1.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-mixed-hives/hive2.properties
Labels: cla-signed, maintenance, test

#3024 Add default value of Glue GetPartitions MaxResults
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed

#3060 Move readConfiguration to ConfigurationUtils
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/ConfigurationUtils.java
Labels: cla-signed

#3055 Pass ConnectorSession to getSplits in JDBC connector
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcSplitManager.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcRecordSetProvider.java
  presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingDatabase.java
Labels: cla-signed

#3059 Increase amount of available memory for tests
  pom.xml
Labels: cla-signed, maintenance, test

#3012 Inline access to guarded field
  presto-main/src/main/java/io/prestosql/server/GracefulShutdownHandler.java
Labels: cla-signed, maintenance

#3071 Introduce HiveMetastoreDecorator
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastoreDecorator.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastoreModule.java
Labels: cla-signed

#3073 Allow to set custom Hive module in tests
  presto-hive/src/main/java/io/prestosql/plugin/hive/testing/TestingHiveConnectorFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/testing/TestingHivePlugin.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
Labels: cla-signed

#3064 Flush remaining output pages before requesting next input page
  presto-main/src/main/java/io/prestosql/operator/StreamingAggregationOperator.java
  presto-main/src/test/java/io/prestosql/operator/TestStreamingAggregationOperator.java
Labels: cla-signed

#3065 Don't do partition filter check on analyze call
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#3068 Remove extra variable prefixes and suffixes
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetastoreClosure.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastore.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/AccessControlMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControlMetadata.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/UnimplementedHiveMetastore.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
  presto-main/src/main/java/io/prestosql/execution/GrantRolesTask.java
  presto-main/src/main/java/io/prestosql/execution/RevokeRolesTask.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/tree/Grant.java
  presto-parser/src/main/java/io/prestosql/sql/tree/GrantRoles.java
  presto-parser/src/main/java/io/prestosql/sql/tree/RevokeRoles.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#3062 Precompute probe row size estimate once
  presto-main/src/main/java/io/prestosql/operator/LookupJoinPageBuilder.java
Labels: cla-signed

#3074 Allocate as little memory as necessary for product tests framework
  presto-product-tests-launcher/pom.xml
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed, maintenance, test

#3078 Remove unused field
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveTestUtils.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
Labels: cla-signed

#3035 Remove unused validation messages from JDBC shading
  presto-jdbc/pom.xml
Labels: cla-signed

#3080 Improve StreamingAggregationOperator invariant comment
  presto-main/src/main/java/io/prestosql/operator/StreamingAggregationOperator.java
Labels: cla-signed

#3085 Use compute() to merge the operator stats into the operator summary
  presto-main/src/main/java/io/prestosql/operator/PipelineContext.java
Labels: cla-signed

#3076 Reuse dataSizeProperty, durationProperty
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSessionProperties.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSessionProperties.java
  presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/session/PropertyMetadataUtil.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorSessionProperties.java
Labels: cla-signed

#3083 Remove redundant comma in Kudu document
  presto-docs/src/main/sphinx/connector/kudu.rst
Labels: cla-signed

#2944 Fix UI redirect with proxy
  presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java
  presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java
Labels: RELEASE-BLOCKER, cla-signed

#2907 Document filter for aggregate functions
  presto-docs/src/main/sphinx/functions/aggregate.rst
Labels: cla-signed

#2838 Add note about tmp folder config for jvm
  presto-docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed

#3081 Do not create empty schemas in HiveQueryRunner
  presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestShowStats.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/TestParquetDecimalScaling.java
Labels: cla-signed

#3110 Provide Type to getColumnMasks
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControl.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
  presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
  presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
  presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Labels: cla-signed

#2682 Support column reordering in cross join
  presto-main/src/main/java/io/prestosql/operator/NestedLoopJoinOperator.java
  presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
  presto-main/src/test/java/io/prestosql/operator/TestNestedLoopJoinOperator.java
Labels: cla-signed, ready to merge

#3084 Use HiveCatalogName to export S3 statistics without name conflicts
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/HiveS3Module.java
Labels: cla-signed

#3120 Make assertion to be connector agnostic
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3118 Quiet fast install mvn
  .github/workflows/checks.yml
  .github/workflows/module-tests.yml
  .github/workflows/product-tests.yml
Labels: cla-signed

#3119 Refactor memory connector
  presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryMetadata.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemoryMetadata.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
Labels: cla-signed

#3123 Add access-control.properties file placeholder
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/access-control.properties
Labels: cla-signed

#3127 Allow public access to ParquetPageSourceFactory#createParquetPageSource
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
Labels: cla-signed

#3122 Extract hdp3 tests to separate suite
  .github/workflows/product-tests.yml
  presto-product-tests/bin/product-tests-suite-7-non-generic.sh
  presto-product-tests/bin/product-tests-suite-8-non-generic.sh
Labels: cla-signed

#3102 Use updatable page source when effectivePredicate is None due to dynamic filters
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
  presto-main/src/main/java/io/prestosql/operator/ScanFilterAndProjectOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableScanOperator.java
  presto-main/src/main/java/io/prestosql/split/PageSourceManager.java
  presto-spi/src/main/java/io/prestosql/spi/connector/EmptyPageSource.java
Labels: cla-signed

#3100 Refactor toCompactTupleDomain to reuse Domain#simplify
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/DiscreteValues.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
Labels: cla-signed

#3136 Fix expected error messages
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveSchema.java
Labels: cla-signed

#3126 Allow setting permissions for new directories
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsEnvironment.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHdfsConfig.java
Labels: cla-signed

#3137 Update to airbase 98
  pom.xml
Labels: cla-signed

#2679 Rubix integration
  pom.xml
  presto-hive/pom.xml
  presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixConfig.java
Labels: cla-signed

#3128 Support multiple event listener plugins
  presto-docs/src/main/sphinx/develop/event-listener.rst
  presto-main/src/main/java/io/prestosql/eventlistener/EventListenerConfig.java
  presto-main/src/main/java/io/prestosql/eventlistener/EventListenerManager.java
  presto-main/src/main/java/io/prestosql/eventlistener/EventListenerModule.java
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
  presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
  presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
  presto-main/src/main/java/io/prestosql/testing/TestingEventListenerManager.java
  presto-main/src/test/java/io/prestosql/eventlistener/TestEventListenerConfig.java
  presto-main/src/test/java/io/prestosql/execution/TaskTestUtils.java
Labels: cla-signed

#3096 Use testcontainers for kudu unit tests
  .github/workflows/module-tests.yml
  presto-kudu/bin/run_kudu_tests.sh
  presto-kudu/conf/docker-compose.yml
  presto-kudu/pom.xml
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/schema/NoSchemaEmulation.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/schema/SchemaEmulation.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/schema/SchemaEmulationByTableNameConvention.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/AbstractKuduIntegrationSmokeTest.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/KuduQueryRunnerFactory.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationDecimalColumns.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationHashPartitioning.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationIntegerColumns.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationRangePartitioning.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationSchemaNotExisting.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduSmokeTestWithDisabledInferSchema.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduSmokeTestWithEmptyInferSchema.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduSmokeTestWithStandardInferSchema.java
  presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestingKuduServer.java
Labels: cla-signed

#3140 Validate configuration in noop connector
  presto-noop/src/main/java/io/prestosql/plugin/noop/NoOpPlugin.java
Labels: cla-signed

#3148 Fix documentation for presto-server-rpm
  presto-server-rpm/README.md
Labels: cla-signed

#3151 Prefer variable over its value
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#3157 Add TupleDomain#simplify overload accepting threshold
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
  presto-spi/src/main/java/io/prestosql/spi/predicate/TupleDomain.java
Labels: cla-signed

#3156 Remove redundant Guice annotation
  presto-hive/src/main/java/io/prestosql/plugin/hive/ForHive.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java
Labels: cla-signed

#3155 Introduce common CatalogName
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopCatalogName.java
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopModule.java
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopProcessFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreModule.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/HiveS3Module.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/InternalIcebergConnectorFactory.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/CatalogName.java
Labels: cla-signed

#3160 Minor PPD cleanup
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#3139 Create group provider configuration for product tests
  presto-noop/src/main/java/io/prestosql/plugin/noop/NoOpPlugin.java
  presto-noop/src/test/java/io/prestosql/plugin/noop/TestNoOpPlugin.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/AbstractSinglenodeLdap.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdap.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdapBindDn.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdapReferrals.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/access-control.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/group-provider.properties
Labels: cla-signed

#2761 Fix reading from large Parquet files
  presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/HdfsParquetDataSource.java
Labels: cla-signed

#3164 Extract common configuration for Kerberos KMS
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentModule.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/KerberosKms.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeKerberosKmsHdfsImpersonation.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeKerberosKmsHdfsNoImpersonation.java
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/kerberos-kms/kms-core-site.xml
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-kms-hdfs-no-impersonation/kms-core-site.xml
Labels: cla-signed

#3158 Remove unused profiles in kudu
  presto-kudu/pom.xml
Labels: cla-signed

#3175 Optimize parquet gzip decompression
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
  presto-parquet/src/main/java/io/prestosql/parquet/ParquetCompressionUtils.java
Labels: cla-signed

#3177 Add `TEMPTO_CONFIG_FILES` support to the test container
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#3135 Remove unnecessary exclusion
  pom.xml
Labels: cla-signed

#3095 Cleanup table of contents for select documentation
  presto-docs/src/main/sphinx/sql/select.rst
Labels: cla-signed

#3190 Fix formatting in hive-hadoop2 POM
  presto-hive-hadoop2/pom.xml
Labels: cla-signed

#3185 Add anchor links for section headers
  presto-docs/src/main/sphinx/conf.py
  presto-docs/src/main/sphinx/themes/presto/static/presto.css_t
Labels: cla-signed

#2825 Return table metadata for translated Hive views
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Labels: cla-signed

#3200 Embed version once
  presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
  presto-main/src/test/java/io/prestosql/server/TestServer.java
Labels: cla-signed

#3199 Remove unused TEMPTO_EXTRA_CONFIG_FILE
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#3192 Ensure kafka splits do not overlap
  presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaRecordSet.java
  presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestMinimalFunctionality.java
Labels: cla-signed

#3197 Remove unused method
  presto-main/src/main/java/io/prestosql/execution/CommitTask.java
  presto-main/src/main/java/io/prestosql/execution/DataDefinitionTask.java
  presto-main/src/main/java/io/prestosql/execution/RollbackTask.java
  presto-main/src/main/java/io/prestosql/execution/StartTransactionTask.java
Labels: cla-signed

#3001 Fix reflective access
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduRecordCursor.java
Labels: cla-signed, maintenance

#3207 Upgrade tempto to 174
  pom.xml
Labels: cla-signed

#2743 Include filtered columns in EXPLAIN (TYPE IO)
  presto-docs/src/main/sphinx/sql/explain.rst
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-main/src/main/java/io/prestosql/sql/planner/planprinter/IoPlanPrinter.java
Labels: cla-signed

#3159 Disallow SHOW STATS for row filters and column masking
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestShowStats.java
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowStatsRewrite.java
  presto-main/src/test/java/io/prestosql/sql/query/TestColumnMask.java
  presto-main/src/test/java/io/prestosql/sql/query/TestRowFilter.java
Labels: cla-signed

#3208 Properly list all tables in memory connector
  presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryMetadata.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemoryMetadata.java
Labels: cla-signed

#3182 Run product tests with hive.fs.new-directory-permissions
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-impersonation/hive.properties
  presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hive-impersonation/hive.properties
Labels: cla-signed

#3210 Bump aws-sdk version
  pom.xml
Labels: cla-signed

#3214 Run predicate pushdown test without dynamic filtering too
  presto-main/src/test/java/io/prestosql/sql/planner/AbstractPredicatePushdownTest.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdown.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdownWithoutDynamicFilter.java
Labels: cla-signed

#2843 Add Project-off rule for CorrelatedJoinNode
  presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q09.plan.txt
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneCorrelatedJoinColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneCorrelatedJoinColumns.java
Labels: cla-signed

#3230 Fix logger argument order for event listener
  presto-main/src/main/java/io/prestosql/eventlistener/EventListenerManager.java
Labels: RELEASE-BLOCKER, bug, cla-signed

#3216 Use Slice methods to access byte array
  presto-main/src/main/java/io/prestosql/execution/buffer/PagesSerde.java
  presto-orc/src/main/java/io/prestosql/orc/OrcOutputBuffer.java
  presto-orc/src/main/java/io/prestosql/orc/stream/CompressedOrcChunkLoader.java
  presto-parquet/src/main/java/io/prestosql/parquet/ParquetCompressionUtils.java
Labels: cla-signed

#3209 Bump aircompressor version
  pom.xml
Labels: cla-signed

#3188 Add clientInfo and traceToken parameters to JDBC driver
  presto-docs/src/main/sphinx/installation/jdbc.rst
  presto-jdbc/src/main/java/io/prestosql/jdbc/ConnectionProperties.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoConnection.java
  presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriverUri.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
Labels: cla-signed

#3202 Remove unused dependencyManagement entries
  pom.xml
Labels: cla-signed

#3223 Update benchto version to 0.9
  presto-benchto-benchmarks/pom.xml
Labels: cla-signed

#3224 Use unique table names in tests
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#3231 Trim whitespace when loading configuration
  presto-main/src/main/java/io/prestosql/eventlistener/EventListenerManager.java
  presto-main/src/main/java/io/prestosql/execution/resourcegroups/InternalResourceGroupManager.java
  presto-main/src/main/java/io/prestosql/metadata/StaticCatalogStore.java
  presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
  presto-main/src/main/java/io/prestosql/security/GroupProviderManager.java
  presto-main/src/main/java/io/prestosql/server/SessionPropertyDefaults.java
  presto-main/src/main/java/io/prestosql/server/security/PasswordAuthenticatorManager.java
  presto-main/src/main/java/io/prestosql/util/PropertiesUtil.java
Labels: cla-signed

#3215 Remove usage of String.format in HTTP client hot path
  presto-main/src/main/java/io/prestosql/server/GenerateTraceTokenRequestFilter.java
Labels: cla-signed

#3236 Update maven to 3.6.3
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#3206 Stop at first LDAP match when distinguished name is not required
  presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java
  presto-product-tests/src/main/java/io/prestosql/tests/cli/TestPrestoLdapCli.java
  presto-product-tests/src/main/java/io/prestosql/tests/jdbc/TestLdapPrestoJdbc.java
Labels: cla-signed

#3234 Delete MongoDB document if exists in schema collection
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
  presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#3240 Remove redundant method argument
  presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#3241 Run selected PPD tests with dynamic filtering too
  presto-main/src/test/java/io/prestosql/sql/planner/AbstractPredicatePushdownTest.java
Labels: cla-signed

#3066 Add support for CREATE SCHEMA name AUTHORIZATION
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHoleMetadata.java
  presto-blackhole/src/test/java/io/prestosql/plugin/blackhole/TestBlackHoleMetadata.java
  presto-docs/src/main/sphinx/sql/create-schema.rst
  presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduMetadata.java
  presto-main/src/main/java/io/prestosql/execution/CreateSchemaTask.java
  presto-main/src/main/java/io/prestosql/metadata/Metadata.java
  presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
  presto-main/src/test/java/io/prestosql/metadata/AbstractMockMetadata.java
  presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryMetadata.java
  presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemoryMetadata.java
  presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
  presto-parser/src/main/java/io/prestosql/sql/tree/CreateSchema.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestStatementBuilder.java
  presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixMetadata.java
  presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorMetadata.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
Labels: cla-signed

#3217 Add dynamicFilterSplitsProcessed to OperatorStats
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedJoinQueries.java
  presto-main/src/main/java/io/prestosql/operator/OperatorContext.java
  presto-main/src/main/java/io/prestosql/operator/OperatorStats.java
  presto-main/src/main/java/io/prestosql/operator/ScanFilterAndProjectOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableScanOperator.java
  presto-main/src/main/java/io/prestosql/operator/TableScanWorkProcessorOperator.java
  presto-main/src/main/java/io/prestosql/operator/WorkProcessorPipelineSourceOperator.java
  presto-main/src/main/java/io/prestosql/operator/WorkProcessorSourceOperator.java
  presto-main/src/main/java/io/prestosql/operator/WorkProcessorSourceOperatorAdapter.java
  presto-main/src/test/java/io/prestosql/execution/TestQueryStats.java
  presto-main/src/test/java/io/prestosql/operator/TestOperatorStats.java
Labels: cla-signed

#3257 Fix predicate push-down accuracy
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
Labels: cla-signed

#3259 Show meaningful error when connector returns invalid table property
  presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
Labels: cla-signed

#3260 Use caching metastore in tests
  presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastoreModule.java
Labels: cla-signed

#3250 Fix SQL formatting for nested alias or sample
  presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
  presto-parser/src/test/java/io/prestosql/sql/parser/TestStatementBuilder.java
Labels: cla-signed

#3181 Add column-pruning rule for DeleteNode
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
  presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneDeleteSourceColumns.java
  presto-main/src/main/java/io/prestosql/sql/planner/plan/DeleteNode.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneDeleteSourceColumns.java
  presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#3262 Remove unused field
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
Labels: cla-signed

#3261 Run multinode product tests' worker on Java 11
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/Multinode.java
Labels: cla-signed

#3263 Log Java version during startup
  presto-main/src/main/java/io/prestosql/server/PrestoServer.java
Labels: cla-signed

#3248 Add logging in SqlFormatterUtil
  presto-main/src/main/java/io/prestosql/sql/SqlFormatterUtil.java
Labels: cla-signed

#3267 Ensure tests are run with appropriate QueryRunner
  presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/ElasticsearchQueryRunner.java
  presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/RaptorQueryRunner.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/TestThriftDistributedQueries.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/TestThriftDistributedQueriesIndexed.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/TestThriftIntegrationSmokeTest.java
  presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/ThriftQueryRunner.java
Labels: cla-signed

#3244 Avoid File.toString for getting file's path
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3ConfigurationInitializer.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/util/ConfigurationUtils.java
  presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverAuth.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/PathResolver.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
  presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Standard.java
  src/modernizer/violations.xml
Labels: cla-signed

#3275 Allow custom projection and relation in QueryBuilder
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
Labels: cla-signed

#3278 Use meaningful identifier in test
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#3255 Deprecate createPageSource overload
  presto-atop/src/main/java/io/prestosql/plugin/atop/AtopPageSourceProvider.java
  presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryPageSourceProvider.java
  presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHolePageSourceProvider.java
  presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSourceProvider.java
  presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
  presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
  presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSourceProvider.java
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPageSourceProvider.java
  presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSourceProvider.java
  presto-main/src/main/java/io/prestosql/connector/system/SystemPageSourceProvider.java
  presto-main/src/main/java/io/prestosql/split/PageSourceManager.java
  presto-main/src/main/java/io/prestosql/split/RecordPageSourceProvider.java
  presto-main/src/test/java/io/prestosql/execution/TestingPageSourceProvider.java
  presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryPageSourceProvider.java
  presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSourceProvider.java
  presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorPageSourceProvider.java
  presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorPageSourceProvider.java
  presto-tests/src/test/java/io/prestosql/execution/TestBeginQuery.java
  presto-thrift/src/main/java/io/prestosql/plugin/thrift/ThriftPageSourceProvider.java
  presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchPageSourceProvider.java
Labels: cla-signed

#3276 Kudu predicate pushdown cleanup
  presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
Labels: cla-signed

#3246 Record routines in query event
  presto-main/src/main/java/io/prestosql/dispatcher/FailedDispatchQuery.java
  presto-main/src/main/java/io/prestosql/event/QueryMonitor.java
  presto-main/src/main/java/io/prestosql/execution/CallTask.java
  presto-main/src/main/java/io/prestosql/execution/QueryInfo.java
  presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
  presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
  presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
  presto-main/src/test/java/io/prestosql/execution/MockManagedQueryExecution.java
  presto-main/src/test/java/io/prestosql/server/TestBasicQueryInfo.java
  presto-main/src/test/java/io/prestosql/server/TestQueryStateInfo.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/QueryMetadata.java
  presto-spi/src/main/java/io/prestosql/spi/eventlistener/RoutineInfo.java
  presto-tests/src/test/java/io/prestosql/execution/TestEventListener.java
Labels: cla-signed

#3282 Allow JDBC connectors to provide system tables
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
Labels: cla-signed

#3281 Extract createTableSql
  presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#3186 Add SqlBaseParser initializer hook and refreshable ATN caches
  presto-parser/src/main/java/io/prestosql/sql/parser/AntlrATNCacheFields.java
  presto-parser/src/main/java/io/prestosql/sql/parser/RefreshableSqlBaseParserInitializer.java
  presto-parser/src/main/java/io/prestosql/sql/parser/SqlParser.java
Labels: cla-signed

#3270 Remove result set from google sheets SplitInfo
  presto-google-sheets/src/main/java/io/prestosql/plugin/google/sheets/SheetsSplit.java
Labels: cla-signed

#3245 Fix query failure when DF allows join to become INNER (v2)
  presto-main/src/main/java/io/prestosql/sql/planner/plan/JoinNode.java
  presto-testing/src/main/java/io/prestosql/testing/AbstractTestJoinQueries.java
Labels: cla-signed

#3242 Test OUTER to INNER join normalization
  presto-main/src/test/java/io/prestosql/sql/planner/AbstractPredicatePushdownTest.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdown.java
  presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdownWithoutDynamicFilter.java
Labels: cla-signed

#3294 Prune cross joins more
  presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
Labels: cla-signed

#3296 Update GitHub Actions checkout to v2
  .github/workflows/checks.yml
  .github/workflows/module-tests.yml
  .github/workflows/product-tests.yml
Labels: cla-signed
