Repository trinodb/trino, pull requests merged in 2021-01, with the labels that each got.

#6491 Update documentation colors to match website
  docs/src/main/sphinx/conf.py
  docs/src/main/sphinx/static/trino.css
Labels: cla-signed

#6490 Add 351 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-351.md
Labels: cla-signed

#6462 Add rank() window operator test
  core/trino-main/src/test/java/io/trino/operator/TestWindowOperator.java
Labels: cla-signed

#6483 Add coercion test filtering rules for Hive 2.1
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveCoercion.java
Labels: cla-signed

#6431 Pass ParsedSchema to SchemaParser
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroSchemaParser.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryTableDescriptionSupplier.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/SchemaParser.java
Labels: cla-signed

#6457 Use dedicated modules for Kafka Schema Registry
  lib/trino-record-decoder/src/main/java/io/trino/decoder/DecoderModule.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/EncoderModule.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
Labels: cla-signed

#6458 Mark TestHivePartitionsTable as flaky due to "committing"
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHivePartitionsTable.java
Labels: cla-signed

#6465 Use the Redshift JDBC driver in the Redshift connector
  docs/src/main/sphinx/connector/redshift.rst
  plugin/trino-redshift/pom.xml
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java
Labels: cla-signed

#6467 Fix return type of array subscript
  core/trino-main/src/main/java/io/trino/operator/scalar/ArraySubscriptOperator.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
Labels: cla-signed

#6505 Fix documentation logo for menu on mobile
  docs/src/main/sphinx/static/trino.css
Labels: cla-signed

#6508 Update logo in README
  .github/homepage.png
  README.md
Labels: cla-signed

#6497 Simplify docker image configuration
  core/docker/Dockerfile
  core/docker/README.md
  core/docker/bin/run-trino
  core/docker/build-local.sh
  core/docker/build-remote.sh
  docs/src/main/sphinx/release/release-351.md
Labels: cla-signed

#4629 Add support for version function
  core/trino-main/src/main/java/io/trino/metadata/FunctionRegistry.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/operator/scalar/VersionFunction.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestVersionFunction.java
  docs/src/main/sphinx/functions.rst
  docs/src/main/sphinx/functions/list.rst
  docs/src/main/sphinx/functions/system.rst
  testing/trino-product-tests/src/main/java/io/trino/tests/TestFunctions.java
Labels: cla-signed, enhancement

#6512 Upgrade benchto to 0.14
  testing/trino-benchto-benchmarks/pom.xml
Labels: cla-signed

#6475 Allow JDBC connectors to control aggregation pushdown for individual tables
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadata.java
Labels: cla-signed

#6503 Expose AWS HTTP Client stats via JMX
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/aws/AbstractSdkMetricsCollector.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreStats.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystemMetricCollector.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystemStats.java
Labels: cla-signed

#6504 Mark Kafka Schema Registry flaky tests
  plugin/trino-kafka/pom.xml
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java
Labels: cla-signed

#6489 Use cause instead of suppressed for OperatorNotFound
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/OperatorNotFoundException.java
Labels: cla-signed

#6519 Update documentation for ALTER TABLE and CREATE TABLE
  docs/src/main/sphinx/sql/alter-table.rst
  docs/src/main/sphinx/sql/create-table.rst
Labels: cla-signed, docs

#6471 Get Data compression only for non-indexed SQL Server tables
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
Labels: cla-signed

#6428 Support JWK with certificate chain
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwkDecoder.java
  core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkService.java
Labels: cla-signed

#6531 Hive performance properties table replaces presto pr 5845
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#6540 Update to OkHttp 3.14.9
  client/trino-client/src/main/java/io/trino/client/OkHttpUtil.java
  client/trino-client/src/main/java/okhttp3/internal/tls/LegacyHostnameVerifier.java
  client/trino-jdbc/pom.xml
  pom.xml
Labels: cla-signed

#6536 Add partition count parameter to BenchmarkHashBuildAndJoin
  core/trino-main/src/test/java/io/trino/operator/BenchmarkHashBuildAndJoinOperators.java
Labels: cla-signed

#6535 Fix javadoc wording for applyTopN
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
Labels: cla-signed

#6537 Do not overwrite version of zt-exec in module
  testing/trino-product-tests/pom.xml
Labels: cla-signed

#6541 Remove outdated comment from TimestampType
  core/trino-spi/src/main/java/io/trino/spi/type/TimestampType.java
  core/trino-spi/src/main/java/io/trino/spi/type/TimestampWithTimeZoneType.java
Labels: cla-signed

#6545 Use READ_COMMITED + SNAPSHOT_ISOLATION (RCSI) level for SqlServer
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#6547 Fix missing backtick in Iceberg documentation
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed

#6548 Short-circuit TupleDomain overlaps
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
Labels: cla-signed

#6554 Migrate some occurances of fail() to assertThatThrownBy
  core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
  core/trino-main/src/test/java/io/trino/metadata/TestQualifiedTablePrefix.java
  core/trino-main/src/test/java/io/trino/operator/TestRowReferencePageManager.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestRange.java
  plugin/trino-atop/pom.xml
  plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopHang.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationSchemaNotExisting.java
  testing/trino-product-tests/src/main/java/io/trino/tests/jdbc/BaseLdapJdbcTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/jdbc/TestLdapTrinoJdbc.java
Labels: cla-signed, maintenance, test

#6523 Use testing docker images from GHCR
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
  docs/build
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestingAccumuloServer.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentDefaults.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HadoopKerberosKms.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigCdh5.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigHdp3.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeLdap.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/Multinode.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/MultinodeHiveCaching.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/MultinodeTls.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeHdp3.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeSparkIceberg.java
  testing/trino-product-tests/conf/product-tests-config-cdh5.sh
  testing/trino-product-tests/conf/product-tests-config-hdp3.sh
  testing/trino-product-tests/conf/product-tests-defaults.sh
Labels: cla-signed

#6525 Refactor TestHiveCoercion
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveCoercion.java
Labels: cla-signed

#6563 Inject SchemaRegistryClient via Provider
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
Labels: cla-signed

#6575 Use assertEventually in TestKafkaAvroReadsSmokeTest
  testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java
Labels: cla-signed

#6501 Improve audience support in OAuth2 authenticator
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Config.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/ScribeJavaOAuth2Client.java
  core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2Config.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilter.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraService.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TokenEndpointAuthMethod.java
Labels: cla-signed

#6578 Enable views in BigQuery tests
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
Labels: cla-signed

#6583 Fix TestBigQueryIntegrationSmokeTest.testShowCreateTable
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
Labels: cla-signed

#6572 Require Java 11.0.7 for building
  pom.xml
Labels: cla-signed

#6571 Remove unnecessary code after OkHttp upgrade
  client/trino-client/src/main/java/io/trino/client/JsonResponse.java
Labels: cla-signed

#6582 Allow parameterized prepared statements in SHOW STATS
  core/trino-main/src/test/java/io/trino/execution/TestParameterExtractor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
Labels: cla-signed

#6561 Update maven-shade-plugin to 3.2.4
  pom.xml
Labels: cla-signed

#6589 Prefer java functional interfaces over Guava
  core/trino-main/src/main/java/io/trino/sql/analyzer/Scope.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java
  core/trino-main/src/test/java/io/trino/memory/TestMemoryPools.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed

#6576 Add OAuth2 support to JDBC
  client/trino-client/pom.xml
  client/trino-client/src/main/java/io/trino/client/auth/external/DesktopBrowserRedirectHandler.java
  client/trino-client/src/main/java/io/trino/client/auth/external/ExternalAuthentication.java
  client/trino-client/src/main/java/io/trino/client/auth/external/ExternalAuthenticator.java
  client/trino-client/src/main/java/io/trino/client/auth/external/HttpTokenPoller.java
  client/trino-client/src/main/java/io/trino/client/auth/external/RedirectException.java
  client/trino-client/src/main/java/io/trino/client/auth/external/RedirectHandler.java
  client/trino-client/src/main/java/io/trino/client/auth/external/Token.java
  client/trino-client/src/main/java/io/trino/client/auth/external/TokenPollResult.java
  client/trino-client/src/main/java/io/trino/client/auth/external/TokenPoller.java
  client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthentication.java
  client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthenticator.java
  client/trino-client/src/test/java/io/trino/client/auth/external/TestHttpTokenPoller.java
  client/trino-jdbc/pom.xml
  client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcExternalAuthentication.java
Labels: cla-signed

#6579 Use long for {Primitive}BigArray#capacity
  lib/trino-array/src/main/java/io/trino/array/BooleanBigArray.java
  lib/trino-array/src/main/java/io/trino/array/ByteBigArray.java
  lib/trino-array/src/main/java/io/trino/array/DoubleBigArray.java
  lib/trino-array/src/main/java/io/trino/array/IntBigArray.java
  lib/trino-array/src/main/java/io/trino/array/LongBigArray.java
  lib/trino-array/src/main/java/io/trino/array/ObjectBigArray.java
  lib/trino-array/src/main/java/io/trino/array/ShortBigArray.java
Labels: cla-signed

#6584 Conditionally run BigQuery tests which require GCE access
  .github/workflows/ci.yml
  plugin/trino-bigquery/pom.xml
Labels: cla-signed

#6568 Fix example reference in resource groups doc
  docs/src/main/sphinx/admin/resource-groups.rst
Labels: cla-signed, docs

#6602 Rename test file to use Trino instead of Presto
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverImpersonateUser.java
Labels: cla-signed

#6027 Use eventual assertion with query stats
  core/trino-main/src/main/java/io/trino/testing/assertions/Assert.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java
Labels: cla-signed

#6601 Retry Hive queries that fail with 'Error committing write to Hive'
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/HiveProductTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestCsv.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveBasicTableStatistics.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveBucketedTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveCreateTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHivePartitionProcedures.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHivePartitionsTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveStorageFormats.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/utils/QueryExecutors.java
Labels: cla-signed

#6616 Use onHive() to access Hive query executor
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestAvroSchemaEvolution.java
Labels: cla-signed

#6593 Allow passing --session-user in the CLI
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  testing/trino-product-tests/src/main/java/io/trino/tests/cli/TestTrinoCli.java
Labels: cla-signed

#6629 Update error-prone to 2.5.1
  pom.xml
Labels: cla-signed

#6631 Remove obsolete conversion
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#6641 Enable UseEnumSwitch error-prone check
  core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
  core/trino-main/src/main/java/io/trino/sql/planner/SystemPartitioningHandle.java
  lib/trino-orc/src/main/java/io/trino/orc/OrcOutputBuffer.java
  lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePrincipal.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Module.java
  pom.xml
Labels: cla-signed

#6633 Update assertJ core to 3.18.1
  client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
  core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestWindowOperatorStats.java
  core/trino-parser/pom.xml
  pom.xml
  testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
Labels: cla-signed

#6539 Add property to allow fetching file sizes in Trino
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/AbstractTestIcebergSmoke.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
Labels: cla-signed

#6627 Update airbase to 106
  pom.xml
  testing/trino-benchto-benchmarks/pom.xml
  testing/trino-test-jdbc-compatibility-old-driver/pom.xml
Labels: cla-signed

#6651 Rename errorprone profile
  .github/workflows/ci.yml
  pom.xml
Labels: cla-signed

#6527 Remove use of test priorities and dependsOnMethods from Prometheus tests
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationMetrics.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationSchema.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java
Labels: cla-signed

#6600 Support Auth Servers with self-signed certificates
  core/trino-main/src/main/java/io/trino/server/security/oauth2/ScribeHttpClient.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/ScribeJavaOAuth2Client.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilter.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraService.java
Labels: cla-signed

#6683 Start JWK service in OAuth2 module
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
Labels: cla-signed

#6430 Add docs for data_compression table property in SQLServer
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#6675 Deprecate JdbcClient.supportsGroupingSets
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadata.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
Labels: cla-signed, maintenance

#6614 Detect and enable snapshot isolation if available for SqlServer
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerWithoutSnapshotIsolation.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java
Labels: cla-signed

#6692 Add geospatial plugin to start from default server main
  core/trino-server-main/etc/config.properties
Labels: cla-signed

#6705 Skip Kinesis decompression when kinesisCompressionCodec is UNCOMPRESSED
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisRecordSet.java
Labels: cla-signed

#6707 Document square bracket and quote example of json path
  docs/src/main/sphinx/functions/json.rst
Labels: cla-signed, docs

#6691 ThriftMetastoreUtil cleanup
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControlMetadata.java
Labels: cla-signed

#6698 Prefer ifPresent functional style in iterative rules
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EliminateCrossJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/ActualProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
Labels: cla-signed

#6709 Remove repeated error-prone check
  pom.xml
Labels: cla-signed

#6708 Document why covar_samp and covar_pop pushdowns are not implemented for SQL Server
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#6702 Change KdbTreeTree stack type back to Object
  plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/KdbTreeType.java
Labels: cla-signed

#6710 Add getTableTypes extension point to BaseJdbcClient
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#6716 Mark testOutputDuplicatesInsensitiveJoin as Flaky
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestJoinQueries.java
Labels: cla-signed

#6192 Support WINDOW clause
  core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestWindowClause.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExpressionVerifier.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/FunctionCallProvider.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/TreePrinter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/FunctionCall.java
  core/trino-parser/src/main/java/io/trino/sql/tree/QuerySpecification.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Window.java
  core/trino-parser/src/main/java/io/trino/sql/tree/WindowDefinition.java
  core/trino-parser/src/main/java/io/trino/sql/tree/WindowReference.java
  core/trino-parser/src/main/java/io/trino/sql/tree/WindowSpecification.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
  docs/src/main/sphinx/functions/window.rst
  docs/src/main/sphinx/sql/select.rst
  service/trino-verifier/src/main/java/io/trino/verifier/QueryRewriter.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#6722 Use correct container log path for Trino nodes
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/health-checks/trino-health-check.sh
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/run-presto.sh
Labels: cla-signed

#6673 Add pushdown for statistical aggregate functions to MySQL connector
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementStddevPop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementStddevSamp.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementVariancePop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementVarianceSamp.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlIntegrationSmokeTest.java
Labels: cla-signed, needs-docs

#6734 Add pattern for multi-variable aggregation functions
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/AggregateFunctionPatterns.java
Labels: cla-signed

#6328 Add a backup Coordinator to test multi coordinators
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
  testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestSystemConnector.java
Labels: cla-signed

#6743 Document statistical aggregation function pushdown for MySQL
  docs/src/main/sphinx/connector/mysql.rst
Labels: cla-signed

#6733 Do not install SystemAccessControl on workers in tests
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed

#6747 Do not apply redirection for delete table scans
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#6732 Add Hive view test for outer explode
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java
Labels: cla-signed

#6750 Add link to WINDOW clause documentation
  docs/src/main/sphinx/functions/window.rst
  docs/src/main/sphinx/sql/select.rst
Labels: cla-signed

#6742 Deprecate DataTypeTest
  testing/trino-testing/src/main/java/io/trino/testing/datatype/DataTypeTest.java
Labels: cla-signed

#6562 Enable OptionalEquality errorprone check
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
  pom.xml
Labels: cla-signed

#6530 Override Accumulo Docker entrypoint for Mac
  plugin/trino-accumulo/pom.xml
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestingAccumuloServer.java
Labels: cla-signed
