Repository trinodb/trino, pull requests merged in 2021-10, with the labels that each got.

#9454 Allow running on macOS ARM64
  core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
Labels: cla-signed

#9448 Store column comment when adding a new column in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#9453 Fix lack of idempotency in client protocol results
  core/trino-main/src/main/java/io/trino/server/protocol/QueryResultRows.java
  core/trino-main/src/test/java/io/trino/server/TestQueryResource.java
  core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultRows.java
Labels: bug, cla-signed, correctness

#9460 Fix time with time zone type client type format
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
Labels: cla-signed

#8012 Flatten AND and OR expressions
  core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
  core/trino-main/src/main/java/io/trino/sql/ExpressionUtils.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/gen/AndCodeGenerator.java
  core/trino-main/src/main/java/io/trino/sql/gen/OrCodeGenerator.java
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ExtractCommonPredicatesExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownNegationsExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveDuplicateConditions.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyFilterPredicate.java
  core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  core/trino-main/src/test/java/io/trino/sql/TestExpressionUtils.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExpressionVerifier.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantTableScanPredicate.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestSimplifyExpressions.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java
  core/trino-parser/src/main/java/io/trino/sql/TreePrinter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionRewriter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/LogicalExpression.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
Labels: cla-signed

#9463 Improve hashes for expressions without fields
  core/trino-parser/src/main/java/io/trino/sql/tree/CurrentCatalog.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CurrentPath.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CurrentSchema.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CurrentUser.java
Labels: cla-signed

#9456 Fix Hive DELETE bug due to colliding split files
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveSplit.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: bug, cla-signed

#9455 Remove usage of @Test(expectedExceptions...) from TestFileSingleStreamSpillerFactory
  core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpillerFactory.java
Labels: cla-signed

#9314 Move materialized view metadata info
  docs/src/main/sphinx/connector/system.rst
  docs/src/main/sphinx/sql/create-materialized-view.rst
Labels: cla-signed, docs

#9477 Use assertThatThrownBy in TestQueryResultRows
  core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultRows.java
Labels: cla-signed

#9431 Improve logic for reading page column indexes in parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TrinoColumnIndexStore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
Labels: cla-signed

#9481 Use assertThatThrownBy in TestSetPathTask
  core/trino-main/src/test/java/io/trino/execution/TestSetPathTask.java
Labels: cla-signed

#9480 Use assertThatThrownBy in TestQueryStateInfoResource
  core/trino-main/src/test/java/io/trino/server/TestQueryStateInfoResource.java
Labels: cla-signed

#9459 Quote identifiers when building Pinot query
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTablePqlExtractor.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/FilterToPinotSqlConverter.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/resources/reserved_keyword_realtimeSpec.json
  plugin/trino-pinot/src/test/resources/reserved_keyword_schema.json
Labels: cla-signed

#9469 Upgrade to Parquet 1.12.1
  pom.xml
Labels: cla-signed, tests:hive

#9157 Add created_by field to native Parquet writer metadata
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-hive/hive.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompression.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Labels: cla-signed, tests:hive

#9486 Add openjdk-devel package to arm64 image
  core/docker/arm64.dockerfile
Labels: cla-signed

#9483 Change width for materialized_views table documentation
  docs/src/main/sphinx/connector/system.rst
Labels: cla-signed, docs

#9494 Run suite-1 additionally on JDK 17
  .github/workflows/ci.yml
Labels: cla-signed, tests:hive, tests:all

#9461 Remove Flaky annotation from TestHiveStorageFormats#testInsertIntoTable, rely on QueryExecutors retry mechanism
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed

#9379 Refactor PartitioningExchanger
  core/trino-main/src/main/java/io/trino/operator/exchange/BroadcastExchanger.java
  core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchangeSource.java
  core/trino-main/src/main/java/io/trino/operator/exchange/PageReference.java
  core/trino-main/src/main/java/io/trino/operator/exchange/PartitioningExchanger.java
  core/trino-main/src/main/java/io/trino/operator/exchange/PassthroughExchanger.java
  core/trino-main/src/main/java/io/trino/operator/exchange/RandomExchanger.java
Labels: cla-signed

#9465 Fix isAdjustedToUTC when writing Parquet timestamp natively
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
Labels: cla-signed, tests:hive

#9502 Log container image name before start
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
Labels: cla-signed

#9513 Enable Error Prone check: StreamToString
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  pom.xml
Labels: cla-signed

#8895 Add header authenticator SPI
  core/trino-main/src/main/java/io/trino/server/PluginManager.java
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/server/security/HeaderAuthenticator.java
  core/trino-main/src/main/java/io/trino/server/security/HeaderAuthenticatorConfig.java
  core/trino-main/src/main/java/io/trino/server/security/HeaderAuthenticatorManager.java
  core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/server/security/TestHeaderAuthenticatorConfig.java
  core/trino-main/src/test/java/io/trino/server/security/TestHeaderAuthenticatorManager.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/Plugin.java
  core/trino-spi/src/main/java/io/trino/spi/security/HeaderAuthenticator.java
  core/trino-spi/src/main/java/io/trino/spi/security/HeaderAuthenticatorFactory.java
  docs/src/main/sphinx/develop.rst
  docs/src/main/sphinx/develop/header-authenticator.rst
  docs/src/main/sphinx/security/authentication-types.rst
  docs/src/main/sphinx/security/user-mapping.rst
Labels: cla-signed

#9524 Rename class to reflect it is abstract test class
  core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithOpaque.java
Labels: cla-signed

#9500 Use HDP3 for suite-1 with JDK 17
  .github/workflows/ci.yml
Labels: cla-signed

#9490 Expose AccessControlConfig in TestingTrinoServer bindings
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
Labels: cla-signed

#9516 Fix incorrect filtering on column name with dot in parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java
Labels: bug, cla-signed, correctness

#9813 Drop parens from ALTER TABLE SET PROPERTIES
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java
  docs/src/main/sphinx/sql/alter-table.rst
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#9745 Fix failure when validating pre-sorted input properties
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateLimitWithPresortedInput.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#9678 Use assertThatThrownBy in TestHiveConnectorTest
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
Labels: cla-signed
