Repository trinodb/trino, pull requests merged in 2021-04, with the labels that each got.

#7331 Ensure join pushdown does not prevent join reordering/flipping
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
Labels: cla-signed

#7476 Add HiveMaterializedViewMetadata
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveAlluxioMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#7479 Minor cleanups in StatementAnalyzer
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#7478 Rename JDBC JOIN pushdown config properties
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
Labels: cla-signed

#7471 Remove TransactionCachingJdbcClient
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/TransactionCachingJdbcClient.java
Labels: cla-signed

#7449 Make the synthetic table name more apparent
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
Labels: cla-signed

#7477 Create Duration explicitly
  client/trino-client/src/test/java/io/trino/client/TestServerInfo.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestQueryExecutor.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFileBasedNetworkTopology.java
  core/trino-main/src/test/java/io/trino/operator/TestOperatorAssertion.java
  core/trino-main/src/test/java/io/trino/server/TestBasicQueryInfo.java
  core/trino-main/src/test/java/io/trino/server/TestQueryStateInfo.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2Config.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestBaseJdbcConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/rubix/TestRubixConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMappingConfig.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleConfig.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusQueryRunner.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationSchema.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusSplit.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorConfig.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/TestStaticSelector.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestResourceGroupsDao.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java
  testing/trino-testng-services/src/main/java/io/trino/testng/services/LogTestDurationListener.java
  testing/trino-tests/src/test/java/io/trino/memory/TestClusterMemoryLeakDetector.java
Labels: cla-signed

#7482 Allow MockConnector to create/rename/drop schema
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockContainer.java
Labels: cla-signed

#7439 Add some ORC and Parquet properties
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#7268 List all possible values for hive.s3.upload-acl-type property
  docs/src/main/sphinx/connector/hive-s3.rst
Labels: cla-signed, docs

#7092 Reconcile with new HTTPS page and clarify
  docs/src/main/sphinx/admin/web-interface.rst
Labels: WIP, cla-signed, docs

#7498 Fix reference to outdated package
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestMetadataQueryOptimization.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleCaseInsensitiveMapping.java
Labels: cla-signed

#7499 Fix HttpRemoteTask node split count and queue space update order
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Labels: cla-signed

#7062 Add HTTPS, PEM, JKS pages; fix cross-refs thereto
  docs/src/main/sphinx/security.rst
  docs/src/main/sphinx/security/cli.rst
  docs/src/main/sphinx/security/inspect-jks.rst
  docs/src/main/sphinx/security/inspect-pem.rst
  docs/src/main/sphinx/security/ldap.rst
  docs/src/main/sphinx/security/server.rst
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#7493 Move IonSqlQueryBuilder to s3select package
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/IonSqlQueryBuilder.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectRecordCursorProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3select/TestIonSqlQueryBuilder.java
Labels: cla-signed

#7492 Move HiveHdfsModule binding to module list
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
Labels: cla-signed

#7282 Move token extraction to a seperate method
  core/trino-main/src/main/java/io/trino/server/security/AbstractBearerAuthenticator.java
Labels: cla-signed

#7397 Use class reference for AvroSerDe name
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
Labels: cla-signed

#7506 Simplify code in OAuth2CallbackResource
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2CallbackResource.java
Labels: cla-signed

#7512 Add missing brace in RunLengthEncodedBlock.toString
  core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
Labels: cla-signed

#7507 Create test table without CTAS
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java
Labels: cla-signed, tests:hive

#7458 Document JDBC parameters disableCompression, assumeLiteralNamesInMetadataCallsForNonConformingClients
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#7511 Fix Hive's file_modified_time value rendering
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveRecordCursor.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#7518 Improve message when _orc_acid_version not found or old
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#7494 Support TopN pushdown for text types in PostgreSQL
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed

#7485 Unify materialized view and view scope creation
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#7465 Record column lineage details
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Output.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/OutputColumn.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestOutput.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnDetail.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/OutputColumnMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryOutputMetadata.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#7519 Mark assertExpression and assertStatement as deprecated
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed

#7516 Add multiple authenticator information
  docs/src/main/sphinx/security.rst
  docs/src/main/sphinx/security/authentication-types.rst
  docs/src/main/sphinx/security/ldap.rst
  docs/src/main/sphinx/security/password-file.rst
  docs/src/main/sphinx/security/salesforce.rst
Labels: cla-signed, docs

#7504 Add Security overview
  docs/src/main/sphinx/security.rst
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed, docs

#7501 Add 355 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-355.md
Labels: cla-signed, release-notes

#7530 Add that dynamic filtering is default
  docs/src/main/sphinx/admin/dynamic-filtering.rst
Labels: cla-signed

#7532 Add missing functions by name
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#7474 Add method to list all objects matching a given prefix
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed

#7455 Fix join spill race condition
  core/trino-main/src/main/java/io/trino/operator/PartitionedLookupSourceFactory.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/TestHashJoinOperator.java
Labels: cla-signed

#7489 Require that materialized view has owner
  core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMaterializedViewDefinition.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: cla-signed

#7195 Add Trino client protocol documentation
  docs/src/main/sphinx/develop.rst
  docs/src/main/sphinx/develop/client-protocol.rst
  docs/src/main/sphinx/installation/cli.rst
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#7541 Fix logical merge conflict
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#7547 Add debug listing to troubleshoot flaky build
  .github/workflows/ci.yml
Labels: cla-signed

#7549 Allow to configure eventListener in DistributedQueryRunner
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed

#7523 Add option to get a row-index column from the Parquet reader
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Labels: cla-signed, tests:hive

#7568 Add kill switch for SQL Server transaction isolation
  plugin/trino-sqlserver/pom.xml
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClientModule.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerConfig.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConfig.java
Labels: cla-signed

#7573 Remove bogus option for unsupported-type-handling from docs
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#7562 Refer to table-scan-node-partitioning-min-bucket-to-task-ratio in doc
  docs/src/main/sphinx/admin/properties-optimizer.rst
Labels: cla-signed, docs

#7558 Format JdbcSortItem in EXPLAIN output
  core/trino-spi/src/main/java/io/trino/spi/connector/SortOrder.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcSortItem.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#7437 Collect build side before local dynamic filters are consumed
  core/trino-main/src/main/java/io/trino/operator/LookupJoinOperator.java
  core/trino-main/src/main/java/io/trino/operator/LookupJoinOperatorFactory.java
  core/trino-main/src/main/java/io/trino/operator/LookupJoinOperators.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkHashBuildAndJoinOperators.java
  core/trino-main/src/test/java/io/trino/operator/TestHashJoinOperator.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/HashBuildAndJoinBenchmark.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/HashBuildBenchmark.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/HashJoinBenchmark.java
Labels: cla-signed

#7576 Make JdbcMetadata::getSchemaTableName public
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
Labels: cla-signed

#7578 Ignore not existing logs when collecting log files
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
Labels: cla-signed

#7563 Push PARTIAL TopN into table scan
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushTopNIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNIntoTableScan.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed

#7564 Use .trino as hidden files prefix in file hive metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
Labels: cla-signed

#7351 Add a flag for HttpRemoteTask to avoid eager but unnecessary sendUpdate
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Labels: cla-signed

#7039 Use same user key when no impersonation is used
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedJdbcIdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcIdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/SingletonJdbcIdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialProviderModule.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
Labels: cla-signed

#7575 Extract OrderingScheme#toLocalProperties
  core/trino-main/src/main/java/io/trino/sql/planner/OrderingScheme.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
Labels: cla-signed

#7554 Upgrade Coral to 1.0.42
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
  pom.xml
Labels: cla-signed, tests:hive

#7586 Adjust pattern for matching sortItems in explain plan
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#7579 Validate ORC ACID version base on data file metadata as a fallback
  lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/Footer.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataReader.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/AcidInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
  plugin/trino-hive/src/test/resources/acid_version_validation/acid_version_hive_3/00000_0
  plugin/trino-hive/src/test/resources/acid_version_validation/no_orc_acid_version_in_metadata/00000_0
Labels: cla-signed

#7613 Disable Phoenix tests due to GHA setup issue
  .github/workflows/ci.yml
Labels: cla-signed

#7605 Update SPI docs
  docs/src/main/sphinx/develop/spi-overview.rst
Labels: cla-signed

#7610 Change test query to operate on BIGINT values
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueries.java
Labels: cla-signed

#7614 Mark TestHiveViews.testRichSqlSyntax as @Flaky
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java
Labels: cla-signed

#7616 Allow to customize JdbcIdentityCacheMapping for CredentialProvider
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedJdbcIdentityCacheMappingModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPlugin.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialProviderModule.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorFactory.java
Labels: cla-signed

#7617 Fractional number double test case
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
Labels: cla-signed

#7628 Fasten listing tables in BigQuery connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
Labels: cla-signed

#7629 Fix Join optimization rule
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReplaceRedundantJoinWithSource.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReplaceRedundantJoinWithSource.java
Labels: cla-signed

#7536 Add recommendations around language injection
  DEVELOPMENT.md
Labels: cla-signed

#7625 Update testcontainers to 1.15.3
  plugin/trino-accumulo/pom.xml
  pom.xml
  testing/trino-test-jdbc-compatibility-old-server/pom.xml
  testing/trino-test-jdbc-compatibility-old-server/src/test/java/io/trino/TestJdbcResultSetCompatibilityOldServer.java
Labels: cla-signed

#7513 Enhance view owner validation
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#7621 Use ACID semantics for whole partition deletes
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#7636 Simplify condition
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
Labels: cla-signed

#7622 Support Hive UPDATE with original files
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#7595 Speed up varcharToCharSaturatedFloorCast
  core/trino-main/src/main/java/io/trino/operator/scalar/CharacterStringCasts.java
Labels: cla-signed

#7643 Remove obsolete Oracle testing DataTypes
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/OracleDataTypes.java
Labels: cla-signed, maintenance

#4022 Add Soundex function
  core/trino-main/pom.xml
  core/trino-main/src/main/java/io/trino/operator/scalar/StringFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
  plugin/trino-accumulo/pom.xml
  plugin/trino-bigquery/pom.xml
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-pinot/pom.xml
  plugin/trino-prometheus/pom.xml
Labels: cla-signed, needs-docs

#7651 Use proper symbols for computing join stats for pushdown
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushJoinIntoTableScan.java
Labels: cla-signed

#7213 Planning time limit
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQuery.java
  core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQuery.java
  core/trino-main/src/main/java/io/trino/execution/DataDefinitionExecution.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
  core/trino-main/src/main/java/io/trino/execution/QueryStateTimer.java
  core/trino-main/src/main/java/io/trino/execution/QueryTracker.java
  core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  docs/src/main/sphinx/admin/properties-query-management.rst
  testing/trino-tests/src/test/java/io/trino/execution/TestQueryTracker.java
Labels: cla-signed, docs

#7676 Raise minimum PostgreSQL version to 9.6
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodePostgresql.java
Labels: cla-signed

#7669 Soundex improvements
  core/trino-main/src/main/java/io/trino/operator/scalar/StringFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
Labels: cla-signed

#7678 Add query info url template
  core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/server/ServerConfig.java
  core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
  core/trino-main/src/main/java/io/trino/server/protocol/QueryInfoUrlFactory.java
  core/trino-main/src/test/java/io/trino/server/TestServerConfig.java
Labels: cla-signed

#7700 set right default temporaryStagingDirectoryPath
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#7263 No predicate pushdown where boolean column
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
Labels: cla-signed

#7671 Enable Phoenix tests
  .github/workflows/ci.yml
Labels: cla-signed

#7565 Allow JDBC connector to invalidate statistics cache
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
Labels: cla-signed

#7690 Added new config property for JDBC extern auth token cache
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#7709 Add glossary to Trino
  docs/src/main/sphinx/appendix.rst
  docs/src/main/sphinx/appendix/glossary.rst
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#7584 Add minimal TLS/HTTPS section
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs

#7641 Add documentation for Elasticsearch password authentication
  docs/src/main/sphinx/connector/elasticsearch.rst
Labels: cla-signed, docs

#7679 New writer oriented rework of docs/README
  docs/README.md
Labels: cla-signed, docs

#7705 Handle race condition when files are deleted externally
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/docker/DockerFiles.java
Labels: cla-signed

#7712 Fix link to glossary
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#7717 Allow running HiveQueryRunner from IDE without any setup
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
Labels: cla-signed

#7724 Correct single-char typo
  docs/src/main/sphinx/security/authentication-types.rst
Labels: cla-signed, docs

#7715 Remove incorrect test
  core/trino-main/src/test/java/io/trino/sql/planner/plan/TestAssingments.java
Labels: cla-signed

#7726 Skip pushFilterIntoTableScan in AddExchanges when no Flter above TableScan
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
Labels: cla-signed

#7644 Saturated floor cast varchar to varchar
  core/trino-main/src/main/java/io/trino/operator/scalar/CharacterStringCasts.java
  core/trino-main/src/test/java/io/trino/type/TestCharacterStringCasts.java
  testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java
Labels: cla-signed

#7718 Add dropMaterializedView to TestingMetadata
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
Labels: cla-signed

#7725 Disable pushdown in AddExchanges when toggled off
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
Labels: cla-signed

#7546 Fix case sensitivity issue of MongoDB view
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#7740 Add link to function in list page
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#7735 Annotate sql parameter with @Language
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/BasePlanTest.java
Labels: cla-signed

#7747 Annotate test as @Flaky
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#7711 Fix population of schema for iceberg getMaterializedView
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#7746 Clean up window partition
  core/trino-main/src/main/java/io/trino/operator/window/Framing.java
  core/trino-main/src/main/java/io/trino/operator/window/GroupsFraming.java
  core/trino-main/src/main/java/io/trino/operator/window/RangeFraming.java
  core/trino-main/src/main/java/io/trino/operator/window/RowsFraming.java
  core/trino-main/src/main/java/io/trino/operator/window/WindowPartition.java
Labels: cla-signed

#7713 Add external/SSO authentication for CLI
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs

#7742 Add bitwise example
  docs/src/main/sphinx/functions/bitwise.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#6862 Document MATCH_RECOGNIZE
  docs/src/main/sphinx/sql.rst
  docs/src/main/sphinx/sql/match-recognize.rst
  docs/src/main/sphinx/sql/select.rst
Labels: cla-signed, docs

#7741 Refactor title and name for Kerberos authentication
  docs/src/main/sphinx/connector/hive-security.rst
  docs/src/main/sphinx/security.rst
  docs/src/main/sphinx/security/authentication-types.rst
  docs/src/main/sphinx/security/cli.rst
  docs/src/main/sphinx/security/kerberos.rst
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed, docs

#7642 Enable listing of Iceberg tables created by Spark
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/iceberg/TestSparkCompatibility.java
Labels: cla-signed

#7756 Relax assertion in JdbcRecordSetProvider
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordSetProvider.java
Labels: cla-signed

#7695 Merge materialized output pages
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
Labels: cla-signed

#7752 Expand flaky pattern for writing to HDFS
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/HiveProductTest.java
Labels: cla-signed

#7761 Add Product Test Launcher shortcut
  bin/ptl
Labels: cla-signed

#7609 Migrate Elasticsearch tests to use BaseConnectorTest
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearch6ConnectorTest.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearch7ConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueries.java
Labels: cla-signed

#7772 Add missing space in Hive view documentation
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#7766 Use getSession() in instead queryRunner.getDefaultSession
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveRoles.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/AbstractTestIcebergSmoke.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduIntegrationSmokeTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemorySmoke.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTransactionIsolationTest.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftIntegrationSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestIntegrationSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestKillQuery.java
  testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java
  testing/trino-tests/src/test/java/io/trino/memory/TestMemorySessionProperties.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
  testing/trino-tests/src/test/java/io/trino/tests/TestLateMaterializationQueries.java
Labels: cla-signed, maintenance

#7531 Add documentation for shared connector features, pushdown and reference updates to SQL Server connector
  docs/src/main/sphinx/connector/jdbc-type-mapping.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sqlserver.rst
  docs/src/main/sphinx/optimizer/pushdown.rst
  docs/src/main/sphinx/sql/select.rst
Labels: cla-signed, docs

#7765 Use PTL shortcut in ci
  .github/workflows/ci.yml
Labels: cla-signed

#7780 Deprecate Standard product tests environment extender
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
Labels: cla-signed

#7791 Remove extra brackets
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
Labels: cla-signed

#7796 Make the intention of max pivot+1 test clearer
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#7387 Replace fail+catch pattern with assertThatThrownBy in trino-blackhole
  plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
Labels: cla-signed

#7802 Inline constant in test
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#7803 Explicitly disable join pushdown in testJoinPushdownDisabled
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed

#7545 Code cosmetics performed on the class io.trino.plugin.kafka.KafkaRecordSet
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaRecordSet.java
Labels: cla-signed

#6337 Filter sys schema on MySQL
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
Labels: cla-signed

#7790 Fix iceberg SHOW TABLES with MVs
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#7706 Fix scopes joining
  core/trino-main/src/main/java/io/trino/server/security/oauth2/ScribeJavaOAuth2Client.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestDynamicCallbackOAuth2Service.java
Labels: cla-signed

#7811 Make PlanOptimizers stateless
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerStatsMBeanExporter.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerStatsRecorder.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizersFactory.java
  core/trino-main/src/main/java/io/trino/sql/planner/RuleStatsRecorder.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#7794 Add support for multi-column rows to EnforceSingleRowOperator
  core/trino-main/src/main/java/io/trino/operator/EnforceSingleRowOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
Labels: cla-signed

#7813 Fix section title levels for pushdown
  docs/src/main/sphinx/optimizer/pushdown.rst
Labels: cla-signed

#7793 Define type-only coercion for row type
  core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
Labels: cla-signed
