Repository trinodb/trino, pull requests merged in 2021-02, with the labels that each got.

#6669 Allow TestingTrinoClient to use forwarded https
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingTrinoClient.java
  testing/trino-testing/src/test/java/io/trino/testing/TestTestingTrinoClient.java
Labels: cla-signed

#6756 Remove deprecated JdbcClient#supportsGroupingSets
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Labels: cla-signed

#6770 Add distinct aggregation pushdown test cases
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlIntegrationSmokeTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
Labels: cla-signed, test

#6761 Prefer ImmutableMap to Map
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
Labels: cla-signed

#6809 Update SQL Server type mapping docs
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed

#6731 PostgreSQL statistical aggregate function pushdown
  docs/src/main/sphinx/connector/postgresql.rst
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCorr.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCovariancePop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCovarianceSamp.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementRegrIntercept.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementRegrSlope.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#6479 Change Trino to match Hive on column rename/drop/add
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHivePartitionSchemaEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestParquetSymlinkInputFormat.java
Labels: cla-signed

#6817 Fix errorprone compiler profile name
  DEVELOPMENT.md
Labels: cla-signed

#6795 Make `getColumnMetadata()` consistent with `tableMetadata.getColumns()` in Elasticsearch connector
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/BuiltinColumns.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ScanQueryPageSource.java
Labels: cla-signed

#6816 Rename aggregation pushdown test methods
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlIntegrationSmokeTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
Labels: cla-signed

#6812 Update aws sdk to 1.11.946
  pom.xml
Labels: cla-signed

#6811 Add missing plan-with-table-node-partitioning config property
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/FeaturesConfig.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
Labels: cla-signed

#6788 Get loaded blocks for probe join channels
  core/trino-main/src/main/java/io/trino/operator/JoinProbe.java
  core/trino-main/src/main/java/io/trino/operator/LookupJoinPageBuilder.java
  core/trino-main/src/test/java/io/trino/operator/TestHashJoinOperator.java
Labels: cla-signed

#6765 Fix isNotFullyPushedDown declaration to avoid call site warnings
  core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
Labels: cla-signed

#6786 Improve TestLateMaterializationQueries
  testing/trino-tests/src/test/java/io/trino/tests/TestLateMaterializationQueries.java
Labels: cla-signed

#6717 Fix writing Hive timestamps array/map/struct timestamps from Trino to Parquet
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/FieldSetterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveStorageFormats.java
Labels: cla-signed

#6684 Make open writers limit configurable in iceberg connector
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
Labels: cla-signed

#6823 Remove unused parameters and helpers
  core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java
  core/trino-main/src/main/java/io/trino/operator/scalar/SequenceFunction.java
Labels: cla-signed, maintenance

#6820 Add schema evolution checks in TestHiveTransactionalTable
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#6822 Add generated name sequencer to JdbcTableHandle
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTableHandle.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadata.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSetProvider.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Labels: cla-signed

#6827 Add benchmark for SortedRangeSet's getOrderedRanges
  core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
Labels: cla-signed, test

#3687 Add support for showing view definition in BigQuery
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
Labels: cla-signed

#6841 Fix planning failure with hidden columns in CTAS
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#6840 Fix typo in property name
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTableHandle.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSetProvider.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Labels: cla-signed

#6849 Ensure Hive record reader closed on failure
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/GenericHiveRecordCursorProvider.java
Labels: cla-signed

#6844 Add configuration for JWT subject field name
  core/trino-main/src/main/java/io/trino/server/security/AbstractBearerAuthenticator.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorConfig.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Config.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwtAuthenticatorConfig.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2Config.java
Labels: cla-signed

#6815 Use SchemaRegistryClient to register schemas in Product tests
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeKafka.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kafka/tempto-configuration.yaml
  testing/trino-product-tests/pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/utils/SchemaRegistryClientUtils.java
Labels: cla-signed

#6751 Add 352 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-352.md
Labels: cla-signed, release-notes

#6853 Disable metastore caching on workers
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreModule.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreQueries.java
Labels: cla-signed

#6838 Fix planning failure with hidden columns in CTE
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/query/TestWith.java
Labels: cla-signed

#6697 Rank test case for PushdownFilterIntoWindow
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushdownFilterIntoWindow.java
Labels: cla-signed, test

#6355 Add functions to_geojson and from_geojson
  docs/src/main/sphinx/functions/geospatial.rst
  lib/trino-geospatial-toolkit/pom.xml
  lib/trino-geospatial-toolkit/src/main/java/io/trino/geospatial/GeometryUtils.java
  plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoFunctions.java
  pom.xml
Labels: cla-signed

#6846 Update docs for property rename
  core/trino-server-main/etc/catalog/localfile.properties
  docs/src/main/sphinx/admin/properties-optimizer.rst
  docs/src/main/sphinx/connector/localfile.rst
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#6720 Add support for current_user() in Hive views
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViewsLegacy.java
Labels: cla-signed

#6876 Enable MissingCasesInEnumSwitch errorprone check
  client/trino-client/src/test/java/io/trino/client/TestFixJsonDataUtils.java
  core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
  core/trino-main/src/main/java/io/trino/metadata/OperatorNotFoundException.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
  core/trino-main/src/main/java/io/trino/operator/scalar/annotations/OperatorValidator.java
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/QueryExplainer.java
  core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/TransformQuantifiedComparisonApplyToCorrelatedJoin.java
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/TypeValidator.java
  core/trino-main/src/test/java/io/trino/sql/gen/TestExpressionCompiler.java
  core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
  lib/trino-orc/src/main/java/io/trino/orc/StripeReader.java
  lib/trino-orc/src/main/java/io/trino/orc/checkpoint/Checkpoints.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataWriter.java
  lib/trino-orc/src/main/java/io/trino/orc/stream/ValueStreams.java
  lib/trino-orc/src/main/java/io/trino/orc/writer/ColumnWriters.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/SerDeUtils.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseShardManager.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/ShardPredicate.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/OrcStorageManager.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/organization/ShardOrganizerUtil.java
  pom.xml
Labels: cla-signed, maintenance

#6882 Fix error message
  core/trino-parser/src/main/java/io/trino/sql/tree/AliasedRelation.java
Labels: cla-signed

#6888 Simplify ValueSet creation from collection of values
  core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
  core/trino-spi/src/main/java/io/trino/spi/predicate/ValueSet.java
Labels: cla-signed

#6825 Rank test case for PushdownLimitIntoWindow
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushdownLimitIntoWindow.java
Labels: cla-signed

#6892 Extract `getFrom` method from QueryBuilder
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/QueryBuilder.java
Labels: cla-signed

#6895 Fix union of two low-unbounded Domains
  core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java
Labels: cla-signed

#6904 Rename Launcher --without-presto to --without-trino
  core/trino-server-main/etc/catalog/hive.properties
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentOptions.java
Labels: cla-signed

#6911 Address TestTablesample flakiness
  testing/trino-tests/src/test/java/io/trino/tests/TestTablesample.java
Labels: cla-signed, maintenance, test

#6880 Minor cleanup in aggregation analysis
  core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#6921 Fix typo in doc
  docs/src/main/sphinx/connector/hive-security.rst
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed

#6922 Add Error Prone check: UnnecessaryCheckNotNull
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java
  lib/trino-orc/src/main/java/io/trino/orc/OrcReaderOptions.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryInsertTableHandle.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryOutputTableHandle.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemorySplit.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/TableInfo.java
  pom.xml
Labels: cla-signed

#6932 Skip maySkipOutputDuplicates in EXPLAIN unless meaningful
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
Labels: cla-signed

#6894 Fix building docker image on MacOS
  core/docker/build-local.sh
  core/docker/build-remote.sh
Labels: cla-signed

#6914 Disallow bucketing or sorting on hive partitioning columns
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
Labels: cla-signed

#6934 Match expectedConstraint strictly in TableScanMatcher
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/TableScanMatcher.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/Util.java
Labels: cla-signed

#6899 Add Error Prone check: PreconditionsInvalidPlaceholder
  core/trino-main/src/main/java/io/trino/operator/project/MergePages.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/Util.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/MetastoreUtil.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  pom.xml
Labels: cla-signed

#6943 Fix formatting
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleNodePartitioningProvider.java
Labels: cla-signed

#6913 Always show `SECURITY` clause in `SHOW CREATE VIEW`
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#6945 Fix whitespace within ci.yml
  .github/workflows/ci.yml
Labels: cla-signed

#6941 Use full commit SHA for third-party cleanup action
  .github/workflows/cleanup.yml
Labels: cla-signed

#6900 Add Error Prone check: ThrowIfUncheckedKnownChecked
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayToJsonCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MapToJsonCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/RowToJsonCast.java
  core/trino-main/src/main/java/io/trino/sql/gen/LambdaCapture.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisShardCheckpointer.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisTableDescriptionSupplier.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
  pom.xml
  service/trino-verifier/src/main/java/io/trino/verifier/VerifyCommand.java
Labels: cla-signed

#6806 Change documentation to reflect accurate SingleStore company name
  docs/src/main/sphinx/connector.rst
  docs/src/main/sphinx/connector/memsql.rst
Labels: cla-signed, docs

#6873 Add legal notices into new appendix
  docs/src/main/sphinx/appendix.rst
  docs/src/main/sphinx/appendix/from-hive.rst
  docs/src/main/sphinx/appendix/legal-notices.rst
  docs/src/main/sphinx/index.rst
  docs/src/main/sphinx/migration.rst
Labels: cla-signed, docs

#6949 Remove unnecessary dependency on parser
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#6944 Match regex for query retries just like Flaky annotation processor does
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/HiveProductTest.java
Labels: cla-signed

#6903 Fix TIME read function when JVM zone east of Greenwich
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
Labels: cla-signed

#6923 Add Error Prone check: MisusedWeekYear
  core/trino-main/src/main/java/io/trino/util/CompilerUtils.java
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopProcessFactory.java
  pom.xml
Labels: cla-signed

#6916 Handle AccessDeniedException in JdbcMetadata#listTableColumns
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
Labels: cla-signed

#6946 Remove API for unconditional port exposure
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/docker/ContainerUtil.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/testcontainers/PortBinder.java
Labels: cla-signed

#6866 Improve parallelism for writes to bucketed partitions
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveAlluxioMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveNodePartitioningProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionedBucketFunction.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitioningHandle.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketing.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketingV1.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketingV2.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePartitionedBucketFunction.java
Labels: cla-signed

#6964 Simplify createLongSequenceBlockWithNull
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePartitionedBucketFunction.java
Labels: cla-signed

#6961 Add Error Prone check: BadShiftAmount
  core/trino-spi/src/test/java/io/trino/spi/block/BenchmarkComputePosition.java
  pom.xml
Labels: cla-signed

#6930 Resolve SchemaReferences in ConfluentContentSchemaReader
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/kafka/schema_with_references.avsc
  testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java
Labels: cla-signed

#6940 Minor Cleanups for SchemaRegistry
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/SchemaRegistryClientPropertiesProvider.java
Labels: cla-signed

#6955 Enable IdentityBinaryExpression error-prone check
  core/trino-main/src/test/java/io/trino/type/TestBigintOperators.java
  core/trino-main/src/test/java/io/trino/type/TestDoubleOperators.java
  core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java
  pom.xml
Labels: cla-signed

#6979 Random cleanup and comments
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMapping.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlCaseInsensitiveMapping.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlCaseInsensitiveMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleCaseInsensitiveMapping.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
Labels: cla-signed

#6985 Fix logical merge conflict
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestRange.java
Labels: cla-signed

#6872 Report better message when no connection from driver
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
Labels: cla-signed

#6805 Add Hive view documentation
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#6971 Remove test case in TestSubnetTopology
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSubnetTopology.java
Labels: cla-signed

#6898 Add Error Prone check: ReturnValueIgnored
  core/trino-main/src/main/java/io/trino/execution/SqlTask.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/metadata/PolymorphicScalarFunctionBuilder.java
  core/trino-main/src/main/java/io/trino/operator/ValuesOperator.java
  core/trino-main/src/test/java/io/trino/execution/TestMemoryRevokingScheduler.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTask.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestAggregationFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/FunctionAssertions.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/BaseStrictSymbolsMatcher.java
  lib/trino-matching/src/test/java/io/trino/matching/TestMatcher.java
  pom.xml
  testing/trino-testing/src/main/java/io/trino/testing/PlanDeterminismChecker.java
Labels: cla-signed

#6983 Update 352 release notes
  docs/src/main/sphinx/release/release-352.md
Labels: cla-signed

#6925 Decorrelate subquery with left UNNEST and global aggregation
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DecorrelateLeftUnnestWithGlobalAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDecorrelateLeftUnnestWithGlobalAggregation.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
Labels: cla-signed

#6999 Verify that BaseConnectorTest contains all tests
  testing/trino-testing/src/test/java/io/trino/testing/TestBaseConnectorTest.java
Labels: cla-signed

#7006 Improve trino-product-tests docs
  testing/trino-product-tests/README.md
Labels: cla-signed

#7008 Fix host name in product tests readme
  testing/trino-product-tests/README.md
Labels: cla-signed

#6753 Fix case insensitive predicate pushdown for MySQL, MemSQL and SQL Server
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloDistributedQueries.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/PredicatePushdownController.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcCachingQueries.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/BaseCassandraDistributedQueries.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergDistributed.java
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorDistributedQueries.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
Labels: cla-signed

#5292 Update to Parquet 1.11.1
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/PrimitiveTypeMapBuilder.java
  pom.xml
Labels: cla-signed

#6703 Unresolve filter expression before printing
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#6987 Improve projection inlining
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestInlineProjections.java
Labels: cla-signed

#6178 Glue metastore statistics integration
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveErrorCode.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DisabledGlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/ForGlueColumnStatisticsRead.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/ForGlueColumnStatisticsWrite.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueInputConverter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueStatConverter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed

#6984 Enable LogTestDurationListener by default on CI
  .github/workflows/ci.yml
  testing/trino-testng-services/src/main/java/io/trino/testng/services/LogTestDurationListener.java
Labels: cla-signed

#6968 Add table descriptor and schema registry usage for Kafka connector
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#6959 Prune enforcedConstraint when pruning columns
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneTableScanColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableScanColumns.java
Labels: cla-signed

#6992 Fix S3 directory detection based on ContentType header
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystem.java
Labels: cla-signed

#7004 Add Error Prone check: GetClassOnAnnotation
  core/trino-main/src/main/java/io/trino/operator/annotations/ImplementationDependency.java
  pom.xml
Labels: cla-signed

#7021 Document safe apparently unsynchronized access
  core/trino-main/src/main/java/io/trino/metadata/DiscoveryNodeManager.java
Labels: cla-signed

#7025 Enable unconditional retries of selenium tests
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilter.java
Labels: cla-signed

#6938 Add groups to Security chapter's TOC
  docs/src/main/sphinx/security.rst
Labels: cla-signed, docs

#6926 Adding explicit reference to query history properties
  docs/src/main/sphinx/admin/web-interface.rst
Labels: cla-signed, docs

#7034 Use default value of REDISTRIBUTE_WRITES in TestInsert
  core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java
Labels: cla-signed

#7040 Fix Raptor query runner TPCH tables setup
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/RaptorQueryRunner.java
Labels: cla-signed, test

#7007 Make ConnectorAwareNodeManager#getWorkerNodes not include coordinator
  core/trino-main/src/main/java/io/trino/connector/ConnectorAwareNodeManager.java
  core/trino-main/src/main/java/io/trino/connector/ConnectorManager.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/TestingConnectorContext.java
  core/trino-main/src/test/java/io/trino/metadata/TestDiscoveryNodeManager.java
Labels: bug, cla-signed

#7050 Fix query in test so it is deterministic
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
Labels: cla-signed

#7038 Allow for overriding GlueColumnStatisticsProvider
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DisabledGlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed

#7061 Make BaseMySqlConnectorTest public
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
Labels: cla-signed

#7014 Fix bad parameter count in code generator
  core/trino-main/src/main/java/io/trino/sql/gen/BytecodeUtils.java
  testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
Labels: cla-signed

#7065 Append current node explicitly in ConnectorAwareNodeManager
  core/trino-main/src/main/java/io/trino/connector/ConnectorAwareNodeManager.java
Labels: bug, cla-signed

#7066 Upgrade to Airlift 203
  pom.xml
Labels: cla-signed

#7060 Remove TestMySqlDistributedQueries
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlDistributedQueries.java
Labels: cla-signed
