Repository trinodb/trino, pull requests merged in 2021-09, with the labels that each got.

#8728 Add documentation for additional Hive Views
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#9046 Add SQL support section to Elasticsearch
  docs/src/main/sphinx/connector/elasticsearch.rst
Labels: cla-signed, docs

#8948 Add SQL support section to Pinot connector
  docs/src/main/sphinx/connector/pinot.rst
Labels: cla-signed, docs

#9004 fix Stage state transitionToRunning on schedulingComplete()
  core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
Labels: cla-signed

#8718 Iceberg: remove useless todo list for residual expression
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed

#8881 Doc correct then term of window function
  docs/src/main/sphinx/admin/spill.rst
Labels: docs

#9076 Apply overrides from provided config when running SuiteDescribe
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteDescribe.java
Labels: cla-signed

#9077 Introduce RowPagesBuilder#getHashChannels method and use it in tests
  core/trino-main/src/test/java/io/trino/RowPagesBuilder.java
  core/trino-main/src/test/java/io/trino/operator/join/JoinTestUtils.java
  core/trino-main/src/test/java/io/trino/operator/join/TestHashJoinOperator.java
Labels: cla-signed

#7991 Add Hive target max file size
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
Labels: cla-signed

#9086 Skip unsupported type in BigQuery connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/Conversions.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
Labels: cla-signed

#8658 Accept that transaction is cancelled early in TestJdbcConnection
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
Labels: cla-signed

#9091 Make IdentityCacheMapping accept ConnectorSession
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedIdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/IdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/SingletonIdentityCacheMapping.java
Labels: cla-signed

#9071 Restore default system access control
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AccessControlModule.java
  core/trino-main/src/main/java/io/trino/security/DefaultSystemAccessControlName.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
  core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
  core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
  core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/DefaultSystemAccessControl.java
Labels: cla-signed

#9088 Document hive.target-max-file-size configuration
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#8986 Treat table as unbucketed if bucketed on unsupported data type
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketing.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
Labels: cla-signed, tests:hive

#9096 Allow using 1 as cassandra.speculative-execution.limit
  docs/src/main/sphinx/connector/cassandra.rst
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientConfig.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientModule.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraClientConfig.java
Labels: cla-signed

#9073 Use URLS_SELF_ISSUER value for oauth2.issuer
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java
Labels: cla-signed

#8997 Add SQL support section to TPC-DS connector
  docs/src/main/sphinx/connector/tpcds.rst
Labels: cla-signed, docs

#9062 Move and correct SQL support section
  docs/src/main/sphinx/connector/memory.rst
Labels: cla-signed, docs

#9122 Fix query failure when pushdown Infinity to BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java
Labels: bug, cla-signed

#9070 Fix locking of non-partitioned transactional tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveTransaction.java
Labels: cla-signed

#7990 Add config option to map TPCH doubles as SQL decimal
  core/trino-main/src/test/java/io/trino/execution/buffer/BenchmarkBlockSerde.java
  lib/trino-orc/src/test/java/io/trino/orc/BenchmarkColumnReaders.java
  plugin/trino-thrift-testing-server/src/main/java/io/trino/plugin/thrift/server/ThriftTpchService.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/DecimalTypeMapping.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchConnectorFactory.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchPageSourceProvider.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSet.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSetProvider.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchTables.java
  plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/TestTpchMetadata.java
  testing/trino-testing/src/main/java/io/trino/testing/tpch/IndexedTpchConnectorFactory.java
  testing/trino-testing/src/main/java/io/trino/testing/tpch/TpchIndexedData.java
Labels: cla-signed

#9102 Improve HashGenerator.getPartition performance
  core/trino-main/src/main/java/io/trino/operator/HashGenerator.java
Labels: cla-signed

#9052 Change date/time precision in BigQuery from 3 to 6
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryResultPageSource.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryType.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestTypeConversions.java
Labels: cla-signed

#9128 Retain commit's failure when rollback fails
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed, maintenance

#9138 Produce better hash for short decimal type
  core/trino-spi/src/main/java/io/trino/spi/type/ShortDecimalType.java
Labels: cla-signed

#9132 Allow for operators to define custom metrics
  core/trino-main/src/main/java/io/trino/operator/ScanFilterAndProjectOperator.java
  core/trino-main/src/main/java/io/trino/operator/TableScanWorkProcessorOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorOperatorAdapter.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorAdapter.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorOperatorAdapter.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
Labels: cla-signed

#9112 Improve Block#getLoadedBlock() and Page#getLoadedPage()
  core/trino-spi/src/main/java/io/trino/spi/Page.java
  core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
  core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleRowBlock.java
Labels: cla-signed

#8975 Add SQL support section to Kudu connector
  docs/src/main/sphinx/connector/kudu.rst
Labels: cla-signed, docs

#9064 Document setdigest type
  docs/src/main/sphinx/language/types.rst
Labels: cla-signed, docs

#9145 Document ARRAY type mapping in BigQuery connector
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#9152 Mark hive views testNestedGroupBy test as @Flaky
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Labels: cla-signed, tests:hive

#9148 Bump snappy-java version
  pom.xml
Labels: cla-signed

#9061 Minor formatting improvements for grammar
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
Labels: cla-signed

#9120 Retry when failed to communicate with Oracle after restart
  plugin/trino-oracle/pom.xml
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java
Labels: cla-signed, test

#9159 Add toString method to PropertyMetadata
  core/trino-spi/src/main/java/io/trino/spi/session/PropertyMetadata.java
Labels: cla-signed

#9144 Revise async and read-through for hive caching
  docs/src/main/sphinx/connector/hive-caching.rst
Labels: cla-signed, docs

#9065 Update Maven wrapper to 3.8.2
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#9100 Record JMX metrics for calls made to the Glue statistics API
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DisabledGlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreStats.java
Labels: cla-signed

#9181 Fix in clause handling of varchars in filter pushdown
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java
Labels: cla-signed

#9111 Remove totalPartitions from TaskContext
  core/trino-main/src/main/java/io/trino/execution/MemoryTrackingRemoteTaskFactory.java
  core/trino-main/src/main/java/io/trino/execution/RemoteTaskFactory.java
  core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
  core/trino-main/src/main/java/io/trino/execution/SqlTask.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskExecutionFactory.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/execution/TaskManager.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/FixedCountScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/FixedSourcePartitionedScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/ScaledWriterScheduler.java
  core/trino-main/src/main/java/io/trino/memory/QueryContext.java
  core/trino-main/src/main/java/io/trino/operator/TaskContext.java
  core/trino-main/src/main/java/io/trino/server/HttpRemoteTaskFactory.java
  core/trino-main/src/main/java/io/trino/server/TaskResource.java
  core/trino-main/src/main/java/io/trino/server/TaskUpdateRequest.java
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
  core/trino-main/src/main/java/io/trino/testing/TestingTaskContext.java
  core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
  core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlStageExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManager.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFixedCountScheduler.java
  core/trino-main/src/test/java/io/trino/memory/TestMemoryTracking.java
  core/trino-main/src/test/java/io/trino/memory/TestQueryContext.java
  core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/AbstractOperatorBenchmark.java
  testing/trino-benchmark/src/test/java/io/trino/benchmark/MemoryLocalQueryRunner.java
Labels: cla-signed

#9168 Move top level markdown files
  .github/CONTRIBUTING.md
  .github/DEVELOPMENT.md
  .github/SECURITY.md
  README.md
Labels: cla-signed

#9114 Update to Avro 1.10.2
  pom.xml
Labels: cla-signed, tests:hive

#9191 Correct connection string examples
  docs/src/main/sphinx/connector/hive-azure.rst
Labels: cla-signed, docs

#8927 Update to ANTLR 4.9.2 and Jdbi 3.21.0
  pom.xml
Labels: cla-signed

#9044 Fix connection URL example and link to Oracle docs
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed

#9153 Fix planning of recursive queries with duplicate outputs of partial plan
  core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRecursiveCte.java
Labels: cla-signed

#9127 Reorder parquet_use_column_index in HiveSessionProperties
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
Labels: cla-signed, maintenance

#9156 Extract OperatorStats#connectorMetrics
  core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
  core/trino-main/src/main/java/io/trino/operator/OperatorStats.java
  core/trino-main/src/main/java/io/trino/operator/ScanFilterAndProjectOperator.java
  core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java
  core/trino-main/src/main/java/io/trino/operator/TableScanWorkProcessorOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorAdapter.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryStats.java
  core/trino-main/src/test/java/io/trino/operator/TestOperatorStats.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorSourceOperatorAdapter.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
Labels: cla-signed

#9205 Upload test results as artifacts
  .github/workflows/ci.yml
Labels: cla-signed, tests:hive

#9198 Fix multiple flaky tests in TestPinotIntegrationSmokeTest
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java
Labels: cla-signed

#8990 Add SQL support section to Thrift connector
  docs/src/main/sphinx/connector/thrift.rst
Labels: cla-signed, docs

#8992 Add SQL support section to Phoenix connector
  docs/src/main/sphinx/connector/phoenix.rst
Labels: cla-signed, docs

#8791 Add Predicate and Column Projection Pushdown Section
  docs/src/main/sphinx/optimizer/pushdown.rst
Labels: cla-signed, docs

#9192 Add note about no Java 17 support
  docs/src/main/sphinx/security/internal-communication.rst
Labels: cla-signed, docs

#9161 Speed up construction of parquet predicate from dictionary
  core/trino-spi/src/main/java/io/trino/spi/predicate/Domain.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/ParquetDoubleStatistics.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/ParquetLongStatistics.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/ParquetRangeStatistics.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/ParquetSliceStatistics.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/ParquetTimestampStatistics.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
  lib/trino-parquet/src/test/java/io/trino/parquet/predicate/TestPredicateUtils.java
Labels: cla-signed

#9208 Document aggregate pushdown in Pinot connector
  docs/src/main/sphinx/connector/pinot.rst
Labels: cla-signed, docs

#9106 Specify schema for which partition filter check can be applied
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRequireQueryPartitionsFilter.java
Labels: cla-signed, tests:hive

#9201 Fix planning failure of INSERT when source table has hidden columns
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#9220 Prevent aggregation pushdown for textual types for MemSQL
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
Labels: cla-signed

#9224 Document bigquery.views-cache-ttl config properties
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
Labels: cla-signed, docs

#9183 Improve environment variable checks in Hive test scripts
  plugin/trino-hive-hadoop2/bin/common.sh
  plugin/trino-hive-hadoop2/bin/run_hive_abfs_access_key_tests.sh
  plugin/trino-hive-hadoop2/bin/run_hive_abfs_oauth_tests.sh
  plugin/trino-hive-hadoop2/bin/run_hive_adl_tests.sh
  plugin/trino-hive-hadoop2/bin/run_hive_s3_tests.sh
  plugin/trino-hive-hadoop2/bin/run_hive_wasb_tests.sh
Labels: cla-signed

#9188 Support Parquet nanosecond timestamp stored as INT64
  lib/trino-parquet/pom.xml
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampNanosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/MessageTypeConverter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TimestampNanosValueWriter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: enhancement, cla-signed, tests:hive

#9207 Fix TestSpatialPartitioningInternalAggregation
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSpatialPartitioningInternalAggregation.java
Labels: cla-signed

#9175 Fix size calculation for nested dictionary block
  core/trino-main/src/test/java/io/trino/block/TestDictionaryBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
Labels: cla-signed

#9223 Allow delegating determining of location for managed transactional tables to HMS
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/Storage.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestRecordingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestSemiTransactionalHiveMetastore.java
Labels: cla-signed

#9226 Clarify comment in BigQuery pom about test profiles
  plugin/trino-bigquery/pom.xml
Labels: cla-signed

#9225 Fix file path generation in configureTempto() method
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentContainers.java
Labels: cla-signed

#8934 Add SQL support section for Hive connector
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#9160 Cleanup parquet ColumnChunk and PageReader
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunk.java
Labels: cla-signed

#9231 Add GitHub Actions job to set milestone for merged PR
  .github/workflows/milestone.yml
Labels: cla-signed

#9235 Sanitize artifact names when uploading results in ci.yml
  .github/workflows/ci.yml
Labels: cla-signed

#9238 Execute ./mvnw -v before getting version in milestone job
  .github/workflows/milestone.yml
Labels: cla-signed

#9240 Make helper assert methods available to subclasses
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed

#6210 add option to configure s3 mappings provider
  docs/src/main/sphinx/connector/hive-s3.rst
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonUtils.java
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/FileBasedS3SecurityMappingsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/ForS3SecurityMapping.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Module.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingConfigurationProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingsParser.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/UriBasedS3SecurityMappingsProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMapping.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMappingConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMappingsParser.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestUriBasedS3SecurityMappingsProvider.java
Labels: cla-signed

#7903 Move bin/ptl to testing directory
  .github/workflows/ci.yml
  bin/ptl
  testing/bin/ptl
  testing/trino-product-tests/README.md
Labels: cla-signed

#9237 Fix failure when querying optimizer_rule_stats system table
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestSystemConnector.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#9247 fix typo
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed

#9190 Fix SET ROLE instruction for roles behavior change
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
Labels: cla-signed

#9252 Improve JDBC connector configuration documentation
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed

#9262 Document the way to show VM options in IntelliJ
  README.md
Labels: cla-signed, docs

#9195 Minor improvements to DEVELOPMENT
  .github/DEVELOPMENT.md
Labels: cla-signed

#8872 Only support single statement writes by default
  core/trino-main/src/main/java/io/trino/transaction/InMemoryTransactionManager.java
  core/trino-spi/src/main/java/io/trino/spi/connector/Connector.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnector.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleConnector.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraConnector.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnector.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnector.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorConnector.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed

#9245 Reset all PrimitiveColumnWriter fields when writer is reset
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#9233 Rename parse_presto_data_size function to parse_data_size
  core/trino-main/src/main/java/io/trino/operator/scalar/DataSizeFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestDataSizeFunctions.java
  docs/src/main/sphinx/functions/conversion.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed

#9265 Fix distinct aggregation input filtering when input mask has nulls
  core/trino-main/src/main/java/io/trino/operator/aggregation/GenericAccumulatorFactory.java
  core/trino-main/src/test/java/io/trino/operator/TestAggregationOperator.java
Labels: cla-signed

#9272 Fixed typo for Hive connector property
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#9251 Add write batch size to common properties fragment
  docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
Labels: cla-signed, docs

#9109 Fix too eager thread pruning in row pattern matching
  core/trino-main/src/main/java/io/trino/operator/WindowOperator.java
  core/trino-main/src/main/java/io/trino/operator/window/Partitioner.java
  core/trino-main/src/main/java/io/trino/operator/window/PatternRecognitionPartition.java
  core/trino-main/src/main/java/io/trino/operator/window/PatternRecognitionPartitioner.java
  core/trino-main/src/main/java/io/trino/operator/window/RegularWindowPartitioner.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/Captures.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/IntList.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/IntMultimap.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/IntStack.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/Matcher.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/ThreadEquivalence.java
  core/trino-main/src/main/java/io/trino/operator/window/pattern/LabelEvaluator.java
  core/trino-main/src/main/java/io/trino/operator/window/pattern/LogicalIndexNavigation.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/window/matcher/MatchAssert.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatching.java
Labels: bug, cla-signed, correctness

#9271 Report column position in SqlDataTypeTest.verifySelect
  testing/trino-testing/src/main/java/io/trino/testing/datatype/SqlDataTypeTest.java
Labels: cla-signed

#9284 Fix parameter name of denySetViewAuthorization
  core/trino-spi/src/main/java/io/trino/spi/security/AccessDeniedException.java
Labels: cla-signed

#9277 Mark hive table statistics testMixedHiveAndPrestoStatistics as @Flaky
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
Labels: cla-signed

#9276 Mark hive bucketed testBucketingWithUnsupportedDataTypes test as @Flaky
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
Labels: cla-signed

#9290 Add ref anchor for SQL support
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#9209 Define and link back to property types
  docs/src/main/sphinx/admin/properties-exchange.rst
  docs/src/main/sphinx/admin/properties-general.rst
  docs/src/main/sphinx/admin/properties-logging.rst
  docs/src/main/sphinx/admin/properties-memory-management.rst
  docs/src/main/sphinx/admin/properties-node-scheduler.rst
  docs/src/main/sphinx/admin/properties-optimizer.rst
  docs/src/main/sphinx/admin/properties-query-management.rst
  docs/src/main/sphinx/admin/properties-regexp-function.rst
  docs/src/main/sphinx/admin/properties-spilling.rst
  docs/src/main/sphinx/admin/properties-task.rst
  docs/src/main/sphinx/admin/properties-web-interface.rst
  docs/src/main/sphinx/admin/properties-write-partitioning.rst
  docs/src/main/sphinx/admin/properties-writer-scaling.rst
  docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed, docs

#9283 Recommend disabling "method always inverted" inspection
  .github/DEVELOPMENT.md
Labels: cla-signed, docs

#9292 Enforce PTL environment class naming
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/Configurations.java
Labels: cla-signed, test, maintenance

#8747 Support Iceberg UUID type
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/UuidColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/UuidValueWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTransforms.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
  testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java
Labels: enhancement, cla-signed, tests:hive

#9297 Contraint batchUpdatePartitionAsync request size when talking to AWS Glue
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed

#9299 Move ClickHouse tests to separate CI job
  .github/workflows/ci.yml
Labels: cla-signed, test

#9308 Minor changes to TupleDomainParquetPredicate
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
Labels: cla-signed

#9311 Document the metadata.cache-maximum-size config property for JDBC connectors
  docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
Labels: cla-signed, docs

#9310 Add info about metadata table for materialized views
  docs/src/main/sphinx/sql/create-materialized-view.rst
Labels: cla-signed, docs

#9267 Fix infinite loop in optimizer
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableScanPredicate.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyExpressions.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantTableScanPredicate.java
  core/trino-main/src/test/java/io/trino/sql/query/TestNestedLogicalBinaryExpression.java
Labels: cla-signed

#9216 Add 362 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-362.md
Labels: cla-signed, release-notes

#9268 Run milestone job in master branch push event
  .github/workflows/milestone.yml
Labels: cla-signed

#9318 Remove unnecessary condition in milestone job
  .github/workflows/milestone.yml
Labels: cla-signed

#9304 Test Iceberg split pruning when filtering on partition column
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#9306 Fix QueryRunner cleanup in TestQueryTracker
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-tests/src/test/java/io/trino/execution/TestQueryTracker.java
Labels: cla-signed, test

#9155 Test unpartitioned materialized Hive views
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMaterializedView.java
Labels: cla-signed, test

#9280 Validate time with time zone well-formedness
  core/trino-spi/src/main/java/io/trino/spi/type/SqlTimeWithTimeZone.java
Labels: cla-signed

#9329 Support datetimeoffset type in SQL Server
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
Labels: cla-signed

#9336 Mark TestMemoryConnectorTest.testCustomMetricsScanOnly as flaky
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
Labels: cla-signed

#9319 Fix SHOW ROLES where there are no roles to display
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#9322 Extract JDBC write-related configuration to separate class
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataSessionProperties.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteSessionProperties.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcWriteConfig.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClientModule.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
Labels: cla-signed

#9270 Improve memory for HashBuilderOperator unspill
  core/trino-main/src/main/java/io/trino/operator/join/HashBuilderOperator.java
Labels: cla-signed

#9335 Skip delegating isNull call if dictionary doesn't have nulls
  core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
Labels: cla-signed

#9339 Support reading variable time precision in MySQL
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
Labels: cla-signed

#9095 Extract a utility method to get MySQL connection properties
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
Labels: cla-signed

#9327 Avoid over-retaining memory in PartitioningExchanger
  core/trino-main/src/main/java/io/trino/operator/exchange/PartitioningExchanger.java
Labels: cla-signed

#9275 Fix unspill scheduling in join spill
  core/trino-main/src/main/java/io/trino/operator/join/HashBuilderOperator.java
  core/trino-main/src/main/java/io/trino/operator/join/LookupSourceFactory.java
  core/trino-main/src/main/java/io/trino/operator/join/PartitionedConsumption.java
  core/trino-main/src/main/java/io/trino/operator/join/PartitionedLookupSourceFactory.java
  core/trino-main/src/main/java/io/trino/operator/join/SpilledLookupSourceHandle.java
Labels: cla-signed

#9366 Do not run milestone workflow on forks
  .github/workflows/milestone.yml
Labels: cla-signed

#9365 Document datetimeoffset type support in SQL Server
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#9367 Use floorDiv and floorMod with LongTimestampWithTimeZone
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/TypeUtils.java
Labels: cla-signed

#9338 Fix predicate pushdown for Parquet decimal columns
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
  lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
Labels: cla-signed

#9369 Increase startup attempts from 1 to 3 in Kafka containers
  testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java
Labels: cla-signed, test

#9377 Run AbstractTestHive single-threaded
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveInMemoryMetastore.java
Labels: cla-signed, test

#9360 Add support for mocking procedures in mock connector
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  testing/trino-tests/src/test/java/io/trino/procedure/TestProcedure.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: cla-signed

#9375 Increase startup attempts from 1 to 3 in MongoDB container
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java
Labels: cla-signed, test

#9396 fix explain analyze statement do not show estimates
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#8821 Add HTTP/S query event logger
  core/trino-server/src/main/provisio/presto.xml
  plugin/trino-http-event-listener/pom.xml
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/ForHttpEventListener.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListener.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListenerConfig.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListenerEventType.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListenerFactory.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListenerPlugin.java
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpQueryListener.java
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpQueryListenerConfig.java
  plugin/trino-http-event-listener/src/test/resources/trino-httpquery-test.p12
  plugin/trino-http-event-listener/src/test/resources/trino-httpquery-test2.p12
  pom.xml
  testing/trino-server-dev/etc/config.properties
  testing/trino-server-dev/etc/event-listener.properties
Labels: cla-signed

#9409 Make sure EXPLAIN produces estimates
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#9395 Recommend disabling warnings about Guava's @Beta
  .github/DEVELOPMENT.md
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreWithQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkHiveFileFormat.java
Labels: cla-signed

#9412 Update web ui authentication info
  docs/src/main/sphinx/admin/properties-web-interface.rst
  docs/src/main/sphinx/admin/web-interface.rst
Labels: cla-signed, docs

#9422 Use test name as table name
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#9439 Ignore IOException in TestHttpQueryListener.teardown
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpQueryListener.java
Labels: cla-signed

#9420 Use closeAllSuppress in CreateAndInsertDataSetup
  testing/trino-testing/src/main/java/io/trino/testing/datatype/CreateAndInsertDataSetup.java
Labels: cla-signed

#9348 Document join-pushdown.enabled for JDBC connectors
  docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
Labels: cla-signed, docs

#8924 Update schedulingWeight property and add example
  docs/src/main/sphinx/admin/resource-groups.rst
  docs/src/main/sphinx/admin/schedule-weight-example.json
Labels: cla-signed, WIP, docs

#9427 Rename Presto references in OAuth2 success.html
  core/trino-main/src/main/resources/oauth2/success.html
Labels: cla-signed

#9206 Relax assertion in testBucketingWithUnsupportedDataTypes
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
Labels: cla-signed

#9446 Add non-full pages to benchmark data in Hive
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkFileFormatsUtils.java
Labels: cla-signed

#9437 Inline legacyColumnMapping method in Druid
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Labels: cla-signed

#9371 Fix bug when using ROUND(0.x, 0)
  core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestMathFunctions.java
Labels: bug, cla-signed, correctness

#9429 Increase DynamicFilterSourceOperator limits for gather exchange
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
Labels: cla-signed

#9425 Test Domain union when result is all values
  core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestDomain.java
Labels: cla-signed, test
