Repository trinodb/trino, pull requests merged in 2021-12, with the labels that each got.

#10123 Correct anchors for pushdown and type mapping
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/memsql.rst
Labels: cla-signed, docs

#10128 Stop using legacyToWriteMapping in MySQL connector
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
Labels: cla-signed

#10129 Stop using legacyToWriteMapping in SQL Server connector
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#10130 Stop using legacyToWriteMapping in Phoenix connector
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
Labels: cla-signed

#10131 Stop using legacyToWriteMapping in MemSQL connector
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
Labels: cla-signed

#10120 Fix deletion of ORC ACID table after running major compaction on it
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/AbstractHiveAcidWriters.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#10106 Fix DynamicFilter probe timeout
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed

#10100 Add sql server lock timeout for sqlserver tests
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java
Labels: cla-signed

#10135 Verify IcebergMetadata.transaction not overwritten
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#10139 Add option to start product tests in debug mode with suspend
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#9723 Implement ORDER BY and DISTINCT spilling for aggregation
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/operator/HashAggregationOperator.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorFactory.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorFactoryBinder.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/GenericAccumulatorFactory.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/GenericAccumulatorFactoryBinder.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/InternalAggregationFunction.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/LazyAccumulatorFactoryBinder.java
  core/trino-main/src/main/java/io/trino/operator/window/AggregateWindowFunction.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/TestAggregationOperator.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-spi/src/main/java/io/trino/spi/Page.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedSpilledQueries.java
  testing/trino-tests/src/test/java/io/trino/tests/TestSpilledAggregations.java
Labels: cla-signed

#10147 Fix flaky testParquetDictionaryPredicatePushdown
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
Labels: cla-signed

#10056 Implement flushing for partial TopNRankingOperator
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
  core/trino-main/src/main/java/io/trino/operator/GroupedTopNRowNumberBuilder.java
  core/trino-main/src/main/java/io/trino/operator/TopNRankingOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
  core/trino-main/src/test/java/io/trino/operator/TestTopNRankingOperator.java
Labels: cla-signed

#10149 Inline legacyToWriteMapping in Redshift connector
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
Labels: cla-signed

#9930 Support Iceberg UUIDs in ORC complex types
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#9819 Add Support for Connection URI to MongoDB Connector
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/pom.xml
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSplitManager.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdFunctions.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/WriteConcernType.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoDistributedQueries.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoPlugin.java
Labels: cla-signed

#10157 Extract static credentials config for BigQuery connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticBigQueryCredentialsSupplier.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticCredentialsConfig.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestStaticCredentialsConfig.java
Labels: cla-signed

#10140 Fix exception handling for Hive OPTIMIZE table procedure
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Labels: cla-signed

#10088 Adjust task_concurrency to number of physical cores
  core/trino-main/pom.xml
  core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
  core/trino-main/src/main/java/io/trino/util/MachineInfo.java
  core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
  pom.xml
Labels: cla-signed

#8987 Use Kerberos ticket cache if keytab is not provided
  client/trino-client/src/main/java/io/trino/client/auth/kerberos/LoginBasedSubjectProvider.java
Labels: cla-signed

#8982 Check if Kerberos config exists and is readable
  client/trino-client/src/main/java/io/trino/client/auth/kerberos/LoginBasedSubjectProvider.java
Labels: cla-signed

#9959 Handle Iceberg files with missing Field IDs
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg/spark-defaults.conf
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed

#10031 fix decoding IP based hostname
  core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelectorFactory.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelectorFactory.java
  core/trino-main/src/main/java/io/trino/metadata/InternalNode.java
  core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
Labels: cla-signed

#8806 Updates CLI to default protocol to HTTPS if port is 443
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/test/java/io/trino/cli/TestClientOptions.java
Labels: cla-signed

#10003 Avoid marking table to be inserted/deleted as input table
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#10154 Make testShowSchemasLikeWithEscape more resilient
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueries.java
Labels: cla-signed

#10142 Update schema of Iceberg $partitions table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSystemTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
Labels: cla-signed

#10162 Report classpath when Plugin class not found
  core/trino-main/src/main/java/io/trino/server/PluginManager.java
Labels: cla-signed

#10167 Migrate deprecated QueryAssert.assertThat method calls
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestCreateDropView.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestSqlCancel.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestInsertIntoCassandraTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestInvalidSelect.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveDeltaLakeTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestSqlStandardAccessControlChecks.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/BaseLdapJdbcTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestLdapTrinoJdbc.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/sqlserver/TestInvalidSelect.java
Labels: cla-signed, test, maintenance, tests:all

#10110 Describe support of CHAR/VARCHAR predicate pushdown
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/no-inequality-pushdown-text-type.fragment
  docs/src/main/sphinx/connector/no-pushdown-text-type.fragment
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sqlserver.rst
  docs/src/main/sphinx/language/types.rst
Labels: cla-signed, docs

#10104 Reword Phoenix connector decimal mapping docs
  docs/src/main/sphinx/connector/phoenix.rst
Labels: cla-signed, docs

#10175 Fix typo
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed

#9746 Support range predicate pushdown for string columns with collation in PostgreSQL connector
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlConfig.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlSessionProperties.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/PostgreSqlQueryRunner.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConfig.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
Labels: cla-signed

#10145 Add 365 release notes
  docs/src/main/sphinx/functions/ipaddress.rst
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-365.md
Labels: cla-signed

#8384 Add the trino namespace to the _meta properties in the Elasticsearch connector
  docs/src/main/sphinx/connector/elasticsearch.rst
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
Labels: cla-signed

#10109 Allow users to specify timeouts when connecting to Prometheus
  docs/src/main/sphinx/connector/prometheus.rst
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusClient.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorConfig.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusQueryRunner.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java
Labels: cla-signed

#10182 Remove unnecessary toString calls
  client/trino-client/src/main/java/io/trino/client/ClientTypeSignature.java
  core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
  core/trino-main/src/main/java/io/trino/sql/SqlPathElement.java
  core/trino-main/src/main/java/io/trino/sql/gen/CursorProcessorCompiler.java
  core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  core/trino-main/src/test/java/io/trino/cost/TestFilterStatsCalculator.java
  core/trino-main/src/test/java/io/trino/type/TestMapOperators.java
  core/trino-main/src/test/java/io/trino/type/TestMapOperatorsLegacy.java
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/PathElement.java
  core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java
  core/trino-spi/src/main/java/io/trino/spi/type/TypeSignature.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordCursor.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetDecimalScaling.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListener.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/AbstractResourceConfigurationManager.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/util/TableLocationUtils.java
Labels: cla-signed

#10189 Remove redundant functional predicate from Constraint in Hive $partitions
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionsSystemTableProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
Labels: cla-signed

#10195 Update 'Presto' to 'Trino' in WriteCompletedEvent
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/WriteCompletedEvent.java
Labels: cla-signed

#10173 Add support to redirect table reads from Hive to Iceberg
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/DefaultHiveTableRedirectionsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHiveIcebergRedirections.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-iceberg-redirections/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-iceberg-redirections/iceberg.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
Labels: enhancement, cla-signed, tests:hive

#10202 Fix tpch q08 product test requirements
  testing/trino-product-tests/src/main/resources/sql-tests/testcases/hive_tpch/q08.sql
Labels: cla-signed, tests:hive

#10204 Update Coral to 1.0.121
  pom.xml
Labels: cla-signed

#10210 Use lighter-weight query runner in test
  plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/TestSessionPropertyManagerInTransaction.java
Labels: cla-signed

#10172 Do not truncate while encoding values as varchar literal
  core/trino-main/src/main/java/io/trino/sql/planner/LiteralEncoder.java
Labels: cla-signed

#10213 Parametrize DistributedQueryRunner.Builder for easier subclassing
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunnerBuilder.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TpchQueryRunnerBuilder.java
Labels: cla-signed

#10207 Move testInsertIntoNotNullColumn to base connector test
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorSmokeTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed

#10201 Improve performance of selectDictionaryPositions
  core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageFilter.java
Labels: cla-signed

#10219 Remove outdated note from OAuth2 docs
  docs/src/main/sphinx/security/oauth2.rst
Labels: cla-signed

#9674 Separate GitHub Actions job to build documentation
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: cla-signed

#10184 Update hive insert overwrite documentation
  docs/src/main/sphinx/appendix/from-hive.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#10034 Add retries for the getTableDataCompression query in the SqlServerClient
  plugin/trino-sqlserver/pom.xml
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#10198 Improve NullableValue.toString
  core/trino-spi/src/main/java/io/trino/spi/predicate/NullableValue.java
Labels: cla-signed

#10192 Enforce Constraint.predicate's columns always known
  core/trino-main/src/test/java/io/trino/metadata/TestInformationSchemaMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/Constraint.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#10214 Fix partitioning in Iceberg on varbinary column
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed

#10236 Fix log messages which are not format strings
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcVendorCompatibility.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
  core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/spiller/FileSingleStreamSpillerFactory.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloTableManager.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/SortingFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveLocal.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/write/TestDataWritableWriter.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisShardCheckpointer.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestRecordAccess.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/s3config/TestS3TableConfigClient.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticator.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/ShardRecoveryManager.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#10247 Remove unnecessary toString() calls in logs
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListener.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/s3config/TestS3TableConfigClient.java
Labels: cla-signed

#9555 Extend UNNEST documentation with usage examples
  docs/src/main/sphinx/sql/select.rst
Labels: cla-signed, docs

#10246 Prevent lock contention in TypeOperators
  core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
Labels: cla-signed

#10250 Deprecate QueryExecutors.connectToPresto in product tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestImpersonation.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestGrantRevoke.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestRoles.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestSqlStandardAccessControlChecks.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/QueryExecutors.java
Labels: cla-signed

#10206 Add CREATE Privilege
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-spi/src/main/java/io/trino/spi/security/Privilege.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePrivilegeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControlMetadata.java
  testing/trino-tests/src/test/java/io/trino/execution/TestGrantOnSchema.java
  testing/trino-tests/src/test/java/io/trino/execution/TestGrantOnTable.java
  testing/trino-tests/src/test/java/io/trino/execution/TestRevokeOnSchema.java
  testing/trino-tests/src/test/java/io/trino/execution/TestRevokeOnTable.java
Labels: cla-signed, syntax-needs-review

#10249 Improve sheduling of min drivers per task
  core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
  core/trino-main/src/test/java/io/trino/execution/executor/TestTaskExecutor.java
Labels: cla-signed

#10115 Enable Maven cache in the CI workflow
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: cla-signed

#10217 Hide Hive redirections session property
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
Labels: cla-signed

#10270 Update TestTaskExecutor to use new TaskId constructor
  core/trino-main/src/test/java/io/trino/execution/executor/TestTaskExecutor.java
Labels: cla-signed

#10271 Remove log4j from ES connector
  plugin/trino-elasticsearch/pom.xml
Labels: cla-signed

#9972 Reclassify stack overflow error to be more specific
  core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
Labels: cla-signed

#10266 Deduplicate code in Parquet Reader
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/BinaryColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/BooleanColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/DoubleColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/FloatColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampMillisColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampNanosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/IntColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/LongColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/LongDecimalColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ShortDecimalColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimeMicrosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampMicrosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/UuidColumnReader.java
Labels: cla-signed

#10205 Add DENY privilege statement
  core/trino-main/src/main/java/io/trino/execution/DenyTask.java
  core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/security/AccessControl.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-main/src/main/java/io/trino/server/QueryExecutionFactoryModule.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
  core/trino-main/src/main/java/io/trino/util/StatementUtils.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorAccessControl.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Deny.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/security/AccessDeniedException.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
  testing/trino-tests/src/test/java/io/trino/execution/TestDenyOnSchema.java
  testing/trino-tests/src/test/java/io/trino/execution/TestDenyOnTable.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
  testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed, syntax-needs-review

#10268 TLS example should show port 8443
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#10267 Skip docs steps if there is change in other directory
  .github/workflows/docs.yml
Labels: cla-signed

#10212 Support Coral-based view translation with table redirects
  core/trino-main/src/main/java/io/trino/connector/ConnectorContextInstance.java
  core/trino-main/src/main/java/io/trino/connector/ConnectorManager.java
  core/trino-main/src/main/java/io/trino/connector/InternalMetadataProvider.java
  core/trino-main/src/main/java/io/trino/testing/TestingConnectorContext.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorContext.java
  core/trino-spi/src/main/java/io/trino/spi/connector/MetadataProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/CoralTableRedirectionResolver.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/CoralSemiTransactionalHiveMSCAdapter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-iceberg-redirections/hive.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Labels: enhancement, cla-signed, tests:hive

#10275 Simplify implementation of skipSingleValue in parquet reader
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/BinaryColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/BooleanColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/DoubleColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/FloatColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampMillisColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampNanosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/IntColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/LongColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/LongDecimalColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ShortDecimalColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimeMicrosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampMicrosColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/UuidColumnReader.java
Labels: cla-signed

#10279 Enforce log4j2 isn't used
  pom.xml
Labels: cla-signed

#10285 Fix dependency ban to append to existing rules
  pom.xml
Labels: cla-signed

#10153 Phoenix Connector: Handle parallel execution of scans explicitly in Trino
  docs/src/main/sphinx/connector/phoenix.rst
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClientModule.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixConfig.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixSessionProperties.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixSplitManager.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConfig.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixConfig.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixSessionProperties.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixSplitManager.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConfig.java
Labels: cla-signed

#10282 Don't fail the annotate workflow if there are no artifacts
  .github/workflows/annotate.yml
Labels: cla-signed

#10284 Add 366 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-366.md
Labels: cla-signed

#10295 Increase test timeout
  testing/trino-tests/src/test/java/io/trino/execution/TestQueryTracker.java
Labels: cla-signed

#10288 Disable distributed sort when failure recovery is enabled
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestFailureRecovery.java
Labels: cla-signed

#10304 Move query retry configs to QueryManagerConfig
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
Labels: cla-signed

#10293 NodePartitioningManager code cleanup
  core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
Labels: cla-signed

#9991 Use AccessControl functionality to filter columns from SELECT *…
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/security/ViewAccessControl.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFilterHideInacessibleColumnsSession.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFilterInaccessibleColumns.java
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed

#10289 Add high level comments for some scheduling components
  core/trino-main/src/main/java/io/trino/execution/SqlStage.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
Labels: cla-signed

#10299 Introduce a logout page for Oauth2 authentication
  core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiLogoutResource.java
  core/trino-main/src/main/resources/oauth2/logout.html
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
Labels: cla-signed

#9125 Add more Kerberos debugging JVM flags in docs
  docs/src/main/sphinx/security/cli.rst
Labels: cla-signed

#10325 Fix cleanup workflow not working for PRs from forks
  .github/workflows/cleanup.yml
Labels: cla-signed

#10321 Fix failure when selecting a constant and all fields from row
  core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSelectAll.java
Labels: cla-signed

#9352 Cache CanonicalizationAware hashcode
  core/trino-main/src/main/java/io/trino/sql/analyzer/CanonicalizationAware.java
Labels: cla-signed

#10335 Fix unsafe generated copy method in aggregation state compiler
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
Labels: cla-signed

#10307 Remove `skip_on_cdh` test group
  plugin/trino-hive-hadoop2/conf/hive-tests-config-cdh5.sh
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigCdh5.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAllDatatypesFromHiveConnector.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBasicTableStatistics.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompression.java
Labels: cla-signed, tests:hive

#10315 Document predicate pushdown in the Oracle connector
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed

#10344 Fix failure handling in ExchangeClientBuffer
  core/trino-main/src/main/java/io/trino/operator/DeduplicationExchangeClientBuffer.java
  core/trino-main/src/main/java/io/trino/operator/ExchangeClient.java
  core/trino-main/src/main/java/io/trino/operator/ExchangeClientBuffer.java
  core/trino-main/src/main/java/io/trino/operator/StreamingExchangeClientBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestDeduplicationExchangeClientBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestExchangeClient.java
  core/trino-main/src/test/java/io/trino/operator/TestStreamingExchangeClientBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestingExchangeClientBuffer.java
Labels: cla-signed

#10141 Fix/predicate skip nested row type
  core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java
  core/trino-main/src/test/java/io/trino/sql/query/TestComplexTypesWithNull.java
Labels: cla-signed

#10319 Capture column level dependencies for CTEs and sub-queries
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#10342 Add option to benchmark only selected methods
  testing/trino-testing-services/src/main/java/io/trino/jmh/Benchmarks.java
Labels: cla-signed

#10349 Report query for query assertion failures
  core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
  testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java
  testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java
Labels: cla-signed

#10196 Remove duplicate variable
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Labels: cla-signed

#10361 Fix intermediate type declaration
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxby/AbstractMinMaxBy.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#10352 Ensure files are not overwritten
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/RcFileFileWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java
Labels: cla-signed

#10353 Update comment about S3 FS ignoring overwrite
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed

#10364 Add SUPPORTS_UPDATE testing connector behavior
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed, test

#10351 Disable SET AUTHORIZATION when VIEW runs as DEFINER by default
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/execution/SetViewAuthorizationTask.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop-kerberos/config.properties
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#10365 Restore interface
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
Labels: cla-signed

#10265 Add jdbc metadata cache flush procedure
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/jdbc-procedures.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/CachingIdentifierMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/IdentifierMappingModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/procedure/FlushJdbcMetadataCacheProcedure.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcCachingConnectorSmokeTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableProperties.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcModule.java
Labels: cla-signed

#10310 Add tests for views in non default scheme
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Labels: cla-signed

#10374 Fix testTableCreation Hive test
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed

#10375 Cleanup schemas when test is finished
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Labels: cla-signed

#10358 Use SqlDataTypeTest in ClickHouse mapping test
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#10186 fix create view on exist table throw view exist exception
  core/trino-main/src/main/java/io/trino/execution/CreateViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateViewTask.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#10383 Relax assertions in failure recovery tests
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestFailureRecovery.java
Labels: cla-signed

#10386 Update to Airbase 115 [minimalist]
  core/trino-server-rpm/pom.xml
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-google-sheets/pom.xml
  plugin/trino-redis/pom.xml
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
  testing/trino-test-jdbc-compatibility-old-driver/pom.xml
Labels: cla-signed

#10377 Add 367 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-367.md
Labels: cla-signed, release-notes

#10396 Relax assertions in failure recovery tests
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestFailureRecovery.java
Labels: cla-signed

#10408 Fix ClassNotFoundException in StateCompiler
  core/trino-main/src/main/java/io/trino/operator/aggregation/state/StateCompiler.java
Labels: cla-signed

#10296 Use SqlDataTypeTest in MemSQL connector
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
Labels: cla-signed

#10233 Migrate Thrift connector tests to use BaseConnectorTest.
  plugin/trino-thrift/pom.xml
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftConnectorTest.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftDistributedQueries.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
Labels: cla-signed

#10424 Fix compilation error in TestThriftConnectorTest
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftConnectorTest.java
Labels: cla-signed

#10384 Add some test cases to BigQuery type mapping
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java
Labels: cla-signed

#10429 Add return type in LISTAGG documentation
  docs/src/main/sphinx/functions/aggregate.rst
Labels: cla-signed

#9113 Suppress warning in TrinoAzureConfigurationInitializer
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/azure/TrinoAzureConfigurationInitializer.java
Labels: cla-signed

#10434 Remove redundant code for empty files in createInternalHiveSplit
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
Labels: cla-signed

#10332 Fix TIME type handling in MemSQL
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
Labels: cla-signed

#10380 Fix incorrect date and timestamp <= 1582-10-14 in Oracle
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
Labels: cla-signed
