Repository trinodb/trino, pull requests merged in 2021-05, with the labels that each got.

#7816 Update Trino book badge in README
  README.md
Labels: cla-signed

#7632 Added the command `clear` used for clearing the trino CLI console.
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/Help.java
  client/trino-cli/src/main/java/io/trino/cli/InputParser.java
Labels: cla-signed

#7830 Fix information_schema query failures in BigQuery connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
Labels: cla-signed

#7762 Remove json annotations from ConnectorMaterializedViewDefinition
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMaterializedViewDefinition.java
Labels: cla-signed

#7829 Add support for CURRENT_CATALOG and CURRENT_SCHEMA
  core/trino-main/src/main/java/io/trino/operator/scalar/SessionFunctions.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DesugarCurrentCatalog.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DesugarCurrentSchema.java
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/SugarFreeChecker.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSessionFunctions.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CurrentCatalog.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CurrentSchema.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionRewriter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
  docs/src/main/sphinx/language/reserved.rst
Labels: cla-signed

#7423 Add retries on Elasticsearch 429 HTTP status
  .github/workflows/ci.yml
  docs/src/main/sphinx/connector/elasticsearch.rst
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchConfig.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/BackpressureRestClient.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/BackpressureRestHighLevelClient.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchNginxProxy.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchQueryRunner.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchBackpressure.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchConfig.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestPasswordAuthentication.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestingElasticsearchConnectorFactory.java
Labels: cla-signed

#7618 Analyze fresh materialized views
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
  core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
Labels: cla-signed

#7838 Add support for epoch millis exposed as String in elasticsearch
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/TimestampDecoder.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
Labels: cla-signed

#7831 Add exit command to the help text
  client/trino-cli/src/main/java/io/trino/cli/Help.java
Labels: cla-signed

#7846 Remove unused ctor parameter in PlanOptimizers
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  testing/trino-testing/pom.xml
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#7814 Fix incorrect and informal use of it's throughout
  docs/src/main/sphinx/connector/cassandra.rst
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/redis.rst
  docs/src/main/sphinx/develop/group-provider.rst
  docs/src/main/sphinx/functions/color.rst
  docs/src/main/sphinx/overview/concepts.rst
  docs/src/main/sphinx/security/salesforce.rst
Labels: cla-signed, docs

#7850 Add debug logging for plan transformations
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/IterativeOptimizer.java
  core/trino-main/src/test/java/io/trino/execution/TestPlannerWarnings.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestCanonicalize.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/BasePlanTest.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/TestIterativeOptimizer.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateSorts.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestMergeWindows.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestReorderWindows.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestSetFlattening.java
Labels: cla-signed

#3613 Add support for casting row to json with field name
  core/trino-main/src/main/java/io/trino/metadata/FunctionRegistry.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayToJsonCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MapToJsonCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/RowToJsonCast.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperatorsLegacy.java
  core/trino-main/src/test/java/io/trino/type/TestMapOperators.java
  core/trino-main/src/test/java/io/trino/type/TestMapOperatorsLegacy.java
  core/trino-main/src/test/java/io/trino/type/TestRowOperators.java
  core/trino-main/src/test/java/io/trino/type/TestRowOperatorsLegacy.java
  testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestAvroSchemaUrl.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed, syntax-needs-review

#7855 Configure list of optimizers via provider
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
Labels: cla-signed

#7858 Don't create local query runner
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java
Labels: cla-signed

#7859 Add .java-version for jenv
  .java-version
Labels: cla-signed

#7853 Add support for dropping column in MongoDB
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoDistributedQueries.java
Labels: cla-signed

#7876 Narrow modernizer exclusions
  core/trino-main/pom.xml
  plugin/trino-password-authenticators/pom.xml
Labels: cla-signed

#7877 Make AbstractCostBasedPlanTest#getSourcePath extendable
  testing/trino-benchto-benchmarks/src/test/java/io/trino/sql/planner/AbstractCostBasedPlanTest.java
Labels: cla-signed

#7878 Remove dead code in to_unixtime
  core/trino-main/src/main/java/io/trino/operator/scalar/timestamptz/ToUnixTime.java
Labels: cla-signed

#7704 Fix flaky TestExternalAuthenticator tests
  client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthenticator.java
Labels: cla-signed

#7888 Use method references instead of lambda
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/BasePlanTest.java
Labels: cla-signed

#7832 Simplify set operations involving empty sets
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EvaluateEmptyIntersect.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveEmptyExceptBranches.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveEmptyUnionBranches.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestEvaluateEmptyIntersect.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveEmptyExceptBranches.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveEmptyUnionBranches.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSetOperations.java
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q04.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q11.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q74.plan.txt
Labels: cla-signed

#7826 Document soundex function
  docs/src/main/sphinx/functions/list.rst
  docs/src/main/sphinx/functions/string.rst
Labels: cla-signed, docs

#7817 Add examples for bitwise right shift functions
  docs/src/main/sphinx/functions/bitwise.rst
Labels: cla-signed, docs

#7194 Fix timezone output in API results
  core/trino-main/src/main/java/io/trino/SessionRepresentation.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java
Labels: cla-signed

#7894 Upgrade to airlift 205
  pom.xml
Labels: cla-signed

#7434 Support aggregation pushdown in ClickHouse connector #7219
  docs/src/main/sphinx/connector/clickhouse.rst
  plugin/trino-clickhouse/pom.xml
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ImplementAvgBigint.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ImplementAvgDecimal.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed

#7892 Avoid null checks in ProcessWorkProcessor
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorUtils.java
Labels: cla-signed

#7896 Enforce ordering of dependency elements in POM files
  lib/trino-orc/pom.xml
  plugin/trino-bigquery/pom.xml
  plugin/trino-phoenix/pom.xml
  plugin/trino-phoenix5/pom.xml
  pom.xml
  testing/trino-test-jdbc-compatibility-old-driver/pom.xml
  testing/trino-test-jdbc-compatibility-old-server/pom.xml
Labels: cla-signed

#7902 Add a link to the tdigest_agg function from list.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed

#7904 Fix example for Iceberg metadata delete
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed

#7550 Code cosmetics io.trino.plugin.hive.util.Statistics#createColumnToComputedStatisticsMap
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestStatistics.java
Labels: cla-signed

#7908 Reuse Filter ID when pushing predicate into Table Scan
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
Labels: cla-signed

#7834 Add type mapping configuration section
  docs/src/main/sphinx/connector/jdbc-type-mapping.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
Labels: cla-signed, docs

#7881 Add PostgreSQL version requirement
  docs/src/main/sphinx/connector/postgresql.rst
Labels: cla-signed, docs

#7860 Add reference to to_base64url function in list.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#7736 Document for url function 'url_extract_protocol', added some examples.
  docs/src/main/sphinx/functions/url.rst
Labels: cla-signed, docs

#7899 Move write partitioning properties to new chapter
  docs/src/main/sphinx/admin/properties-write-partitioning.rst
  docs/src/main/sphinx/admin/properties-writer-scaling.rst
  docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed

#7921 Delete unnecessary text file
  lib/trino-orc/src/main/java/io/trino/orc/results.txt
Labels: cla-signed

#7920 Fix table headers in docs
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#7819 Cancel query when JDBC connection or statement is closed
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoPreparedStatement.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoStatement.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
Labels: cla-signed, jdbc

#7882 Desugar row dereference into row subscript
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/DesugarRowSubscriptRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DereferencePushdown.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DesugarRowSubscript.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EliminateCrossJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ExtractDereferencesFromFilterAboveScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferenceThroughFilter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferenceThroughJoin.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferenceThroughProject.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferenceThroughSemiJoin.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferenceThroughUnnest.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughAssignUniqueId.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughLimit.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughMarkDistinct.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughRowNumber.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughSort.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughTopN.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughTopNRanking.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferencesThroughWindow.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushLimitThroughProject.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionThroughJoin.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushTopNThroughProject.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/joins/JoinGraph.java
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/SugarFreeChecker.java
  core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayReduceFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestLambdaExpression.java
  core/trino-main/src/test/java/io/trino/sql/gen/TestExpressionCompiler.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDereferencePushDown.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestEqualityInference.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPartialTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestEliminateCrossJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestInlineProjections.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestJoinNodeFlattener.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDownDereferencesRules.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushLimitThroughProject.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionThroughJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNThroughProject.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReorderJoins.java
  core/trino-main/src/test/java/io/trino/type/TestRowOperators.java
  core/trino-spi/src/main/java/io/trino/spi/expression/FieldDereference.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestBingTileFunctions.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
Labels: cla-signed

#7923 Run iceberg tests on CDH5 and HDP3
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigCdh5.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigHdp3.java
  testing/trino-product-tests/conf/product-tests-config-cdh5.sh
  testing/trino-product-tests/conf/product-tests-config-hdp3.sh
Labels: cla-signed, tests:hive

#7924 Use airbase property to configure maven-release-plugin
  pom.xml
Labels: cla-signed

#7869 Added a fix for BQ connector to correctly treat single quote in query criteria
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryType.java
Labels: cla-signed

#6726 Make Kinesis update interval from S3 configurable
  docs/src/main/sphinx/connector/kinesis.rst
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisConfig.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestKinesisConfig.java
Labels: cla-signed

#7930 Minor ExpressionUtils cleanup
  core/trino-main/src/main/java/io/trino/sql/ExpressionUtils.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/SuiteTestRun.java
Labels: cla-signed

#7945 Upgrade sql server jdbc driver
  pom.xml
Labels: cla-signed

#7932 Upgrade provisio and trino-maven-plugin to allow building with JDK 16
  pom.xml
Labels: cla-signed

#7952 Run CI checks on JDK 16
  .github/workflows/ci.yml
Labels: cla-signed

#7863 Add support for multi-column subqueries in IN predicates and quantified comparisons
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q33.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q56.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q58.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q60.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q70.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q83.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q95.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpch/q20.plan.txt
Labels: cla-signed

#7940 Remove obsolete comment in S3TableConfigClient
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
Labels: cla-signed

#7941 Fix prepared grant with quotes
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java
Labels: cla-signed

#7950 Remove beta mention for API
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#7944 Bind version embedder to interface
  core/trino-main/src/main/java/io/trino/connector/ConnectorManager.java
  core/trino-main/src/main/java/io/trino/dispatcher/DispatchExecutor.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
Labels: cla-signed, maintenance

#7452 Use the KuduScanToken API to get tablets
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/properties/KuduTableProperties.java
Labels: cla-signed

#7956 Allow slicing QueryAssert's MaterializedResult
  core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
Labels: cla-signed, test

#7947 Clear pagesIndex in WindowOperator#close()
  core/trino-main/src/main/java/io/trino/operator/WindowOperator.java
Labels: cla-signed

#7949 Minor cleanup in Iceberg docs
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#7961 Remove redundant closeSpiller call (spiller is already empty)
  core/trino-main/src/main/java/io/trino/operator/WindowOperator.java
Labels: cla-signed

#7955 Add HiveMaterializedViewMetadataFactory
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/DefaultHiveMaterializedViewMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnector.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#7959 Merge PushPredicateIntoTableScan with simplifyOptimizer invocations
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
Labels: cla-signed

#7965 Minor rule cleanup
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableScanPredicate.java
Labels: cla-signed

#6681 Notify coordinator on obtaining token
  client/trino-client/src/main/java/io/trino/client/auth/external/ExternalAuthentication.java
  client/trino-client/src/main/java/io/trino/client/auth/external/HttpTokenPoller.java
  client/trino-client/src/main/java/io/trino/client/auth/external/TokenPoller.java
  client/trino-client/src/test/java/io/trino/client/auth/external/MockTokenPoller.java
  client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthentication.java
  client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthenticator.java
  client/trino-client/src/test/java/io/trino/client/auth/external/TestHttpTokenPoller.java
Labels: cla-signed

#7857 Add truncate transform tests for numeric types
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/AbstractTestIcebergSmoke.java
Labels: cla-signed, tests:hive

#7973 Rename legacy type mapping helper method
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed, maintenance

#7910 Add examples for bitwise logical operation functions
  docs/src/main/sphinx/functions/bitwise.rst
Labels: cla-signed, docs

#7982 Add target pseudo css for anchors
  docs/src/main/sphinx/static/trino.css
Labels: cla-signed

#7988 Improve MongoDB requirements
  docs/src/main/sphinx/connector/mongodb.rst
Labels: cla-signed, docs

#7984 Improve Cassandra requirements
  docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed, docs

#7733 Add principal-field documentation to Oauth
  docs/src/main/sphinx/security/oauth2.rst
Labels: WIP, cla-signed, docs

#7936 Reset JWK http clients default configuration
  core/trino-main/src/main/java/io/trino/server/InternalCommunicationModule.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
Labels: cla-signed

#7980 Deprecate TupleDomain.transform
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
Labels: cla-signed

#7977 Rename fraction to picosOfMilli for consistency
  core/trino-spi/src/main/java/io/trino/spi/type/LongTimestampWithTimeZoneType.java
Labels: cla-signed

#7978 Validate TableScanNode.enforcedConstraint
  core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java
Labels: cla-signed

#7745 Not take range partitions into account for Kudu bucketing
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduBucketFunction.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduBucketedSplitSource.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationGroupedExecution.java
Labels: cla-signed

#7995 Canonicalize date function call to cast
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/CanonicalizeExpressionRewriter.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestCanonicalizeExpressionRewriter.java
Labels: cla-signed

#7915 Map ClickHouse UUID to Trino UUID #7097
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#6668 Improve Iceberg connector documentation
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#7946 Improve SQL Server requirements
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#7987 Improve Kafka requirements
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#7989 Improve Redis requirements
  docs/src/main/sphinx/connector/redis.rst
Labels: cla-signed, docs

#7986 Add Oracle requirements
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#7985 Add MySQL requirements
  docs/src/main/sphinx/connector/mysql.rst
Labels: cla-signed, docs

#7927 Update dynamic filtering stats documentation
  docs/src/main/sphinx/admin/dynamic-filtering.rst
Labels: cla-signed, docs

#8001 Drop verify check
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/CanonicalizeExpressionRewriter.java
Labels: cla-signed

#8004 Mention that Redis Cluster is not supported
  docs/src/main/sphinx/connector/redis.rst
Labels: cla-signed, docs

#8008 Add Thrift port to requirements
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#8007 Fix handling of SNI for multiple TLS certificates
  pom.xml
Labels: cla-signed

#7998 Retry SQL Server SET READ_COMMITTED_SNAPSHOT failure
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java
Labels: cla-signed

#8002 Improve code comment about table scan redirection in PlanOptimizers
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
Labels: cla-signed

#7996 Remove incorrect assumption from a rule
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableScanPredicate.java
Labels: cla-signed

#7993 Migrate HiveIntegrationSmokeTest to ConnectorTest
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDistributedQueries.java
Labels: cla-signed, tests:hive

#7970 Make binding for Hive page source provider optional
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
Labels: cla-signed

#8018 Add missing @Test annotation
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed

#7966 Add 357 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-357.md
Labels: cla-signed, release-notes

#8037 Enable test sanitization in trino-parser
  core/trino-parser/pom.xml
Labels: cla-signed

#8044 Update documentation for cast of row to json
  docs/src/main/sphinx/functions/json.rst
Labels: cla-signed, docs

#7818 Remove usages of deprecated Files.create in core module
  core/trino-main/src/test/java/io/trino/spiller/TestBinaryFileSpiller.java
  core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpiller.java
  core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpillerFactory.java
Labels: cla-signed

#8016 Remove unused method argument
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
Labels: cla-signed

#8019 Fix assertProperForwardingMethodsAreCalled for interface with private methods
  core/trino-spi/src/test/java/io/trino/spi/testing/ForwardingInterfaceWithPrivateMethod.java
  core/trino-spi/src/test/java/io/trino/spi/testing/InterfaceTestUtils.java
  core/trino-spi/src/test/java/io/trino/spi/testing/InterfaceWithPrivateMethod.java
  core/trino-spi/src/test/java/io/trino/spi/testing/TestInterfaceTestUtils.java
Labels: cla-signed

#8041 Make test case more focused
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed

#8015 Remove ambiguous NAME imports
  core/trino-main/src/main/java/io/trino/sql/InterpretedFunctionInvoker.java
  core/trino-main/src/main/java/io/trino/sql/planner/DesugarTryExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/type/FunctionParametricType.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/BenchmarkGroupedTypedHistogram.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestHistogram.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestMapAggAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestMapUnionAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestMultimapAggAggregation.java
Labels: cla-signed

#7981 Add equals and hashCode to ConnectorMaterializedViewDefinition
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMaterializedViewDefinition.java
Labels: cla-signed

#7916 Minor updates to Write partitioning documentation
  docs/src/main/sphinx/admin/properties-write-partitioning.rst
Labels: cla-signed, docs

#8049 Fix error message on drop of non-existing MV
  core/trino-main/src/main/java/io/trino/execution/DropMaterializedViewTask.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#8043 Push FINAL TopN into Table Scan
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushTopNIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNIntoTableScan.java
Labels: cla-signed

#8058 Add deprecation notice to release notes
  docs/src/main/sphinx/release/release-357.md
Labels: cla-signed, docs

#8023 Handle repeated expressions in QueryPlanner.coerce()
  core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
  core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
Labels: cla-signed

#8059 Add test for EXPLAIN queries throwing Error throwables
  testing/trino-tests/src/test/java/io/trino/execution/TestErrorThrowableInQuery.java
Labels: cla-signed

#8042 Abolish taking over Presto JDBC driver
  client/trino-jdbc/src/main/java/com/facebook/presto/jdbc/PrestoDriver.java
  client/trino-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriver.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcExternalAuthentication.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
  testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
Labels: cla-signed, jdbc

#8057 Suppress verbose logging in BaseCaseInsensitiveMappingTest
  plugin/trino-base-jdbc/pom.xml
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseCaseInsensitiveMappingTest.java
Labels: cla-signed

#8066 Clean up runtime casts
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/TransactionalMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/UnregisterPartitionProcedure.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#8069 Revert "Refactor TypeCoercion.coerceTypeBase"
  core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
Labels: cla-signed

#8077 Remove deprecated APIs in ConnectorPageSourceProvider
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSourceProvider.java
  core/trino-main/src/main/java/io/trino/connector/system/SystemPageSourceProvider.java
  core/trino-main/src/main/java/io/trino/split/RecordPageSourceProvider.java
  core/trino-main/src/test/java/io/trino/execution/TestingPageSourceProvider.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorPageSourceProvider.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorPageSourceProvider.java
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopPageSourceProvider.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHolePageSourceProvider.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSourceProvider.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSourceProvider.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotPageSourceProvider.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorPageSourceProvider.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftPageSourceProvider.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchPageSourceProvider.java
  testing/trino-tests/src/test/java/io/trino/execution/TestBeginQuery.java
  testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java
Labels: cla-signed

#8000 Use and recommend -XX:-OmitStackTraceInFastThrow
  core/docker/default/etc/jvm.config
  core/trino-server-rpm/src/main/resources/dist/config/jvm.config
  docs/src/main/sphinx/installation/deployment.rst
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config
Labels: cla-signed

#8026 Allow SHOW STATS for query with LIMIT
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowStatsRewrite.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
Labels: cla-signed

#8079 Fix ordering scheme rewrite with duplicate sort items
  core/trino-main/src/main/java/io/trino/sql/planner/OrderingScheme.java
  core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
  core/trino-main/src/test/java/io/trino/sql/query/TestOrderedAggregation.java
Labels: cla-signed

#7974 Don't print resolved plan when no group references
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanAssert.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractQueryAssertionsTest.java
Labels: cla-signed

#8095 Support simple table statistics in memory connector
  plugin/trino-memory/pom.xml
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryTableStatistics.java
Labels: cla-signed, enhancement

#8082 Try to cancel PR build after merge
  .github/workflows/cleanup.yml
Labels: cla-signed

#8075 Fix warnings in Query class
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
Labels: cla-signed

#8092 Update SHOW STATS docs for query support
  docs/src/main/sphinx/sql/show-stats.rst
Labels: cla-signed, docs

#8123 Simplify predicate
  core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineTableScanNodePartitioning.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableScanColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDownDereferencesRules.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNIntoTableScan.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftProjectionPushdown.java
Labels: cla-signed

#8122 Build TableScanNode fluently in PlanBuilder
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed

#8013 Add example of function from_unixtime_nanos and update the link to fr…
  docs/src/main/sphinx/functions/datetime.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#7926 Adding documentation on min/max-drivers-per-task config
  docs/src/main/sphinx/admin/properties-task.rst
Labels: cla-signed, docs

#8117 Add connector test for materialized view
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/AbstractTestIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestIntegrationSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed

#8130 Include *-non-generic suites on PR builds v2
  .github/workflows/ci.yml
Labels: cla-signed

#8121 Define required tables when creating memory query runner
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/MemoryQueryRunner.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemorySmoke.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryTableStatistics.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryWorkerCrash.java
  testing/trino-tests/src/test/java/io/trino/execution/TestTry.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#8132 Revert "Supports authentication using multiple ldap.user-bind-pattern value"
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticator.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestLdapAuthenticator.java
Labels: cla-signed, tests:all, tests:hive

#8133 Print current plan when BeginTableWrite fails
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
Labels: cla-signed

#8064 Use eventual assertion in TestTestingPostgreSqlServer
  plugin/trino-postgresql/pom.xml
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestTestingPostgreSqlServer.java
Labels: cla-signed

#8145 Fix checkstyle
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
Labels: cla-signed

#8136 Ensure older workflow runs for a PR/commit are cancelled
  .github/workflows/ci.yml
  .github/workflows/cleanup.yml
Labels: WIP, cla-signed

#8149 Remove extra (redundant) grace period
  core/trino-main/src/main/java/io/trino/server/GracefulShutdownHandler.java
Labels: cla-signed
