Repository trinodb/trino, pull requests merged in 2021-07, with the labels that each got.

#8441 Fix offsite url on jwt page
  docs/src/main/sphinx/security/jwt.rst
Labels: cla-signed, docs

#8339 Fix ClickHouse table property documentation and examples
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed, docs

#8367 Simplify JMX connector's jmx.dump-tables example
  docs/src/main/sphinx/connector/jmx.rst
Labels: cla-signed, docs

#8417 Update comment about table statistics in ApplyTableScanRedirection
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
Labels: cla-signed

#8442 Replace deprecated installModuleIf with conditionalModule from airlift
  core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelectorModule.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopConnectorFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RemoteQueryCancellationModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialProviderModule.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchConnectorModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/authentication/HiveAuthenticationModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastoreModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/HiveSecurityModule.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaClientsModule.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorModule.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/security/KafkaSecurityModule.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/security/RaptorSecurityModule.java
Labels: cla-signed

#8443 Handle concurrent table drop in TableCommentSystemTable
  core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
Labels: cla-signed

#8446 Add current_groups function
  core/trino-main/src/main/java/io/trino/operator/scalar/SessionFunctions.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSessionFunctions.java
Labels: cla-signed

#8420 Add 359 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-359.md
Labels: cla-signed, docs, release-notes

#8459 Add missing method call delegation to HiveMaterializedViewMetadata
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Labels: cla-signed

#8460 Avoid task sendUpdate until callback clears current request
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Labels: cla-signed

#8475 Fix comment
  core/trino-main/src/main/java/io/trino/sql/planner/SortExpressionExtractor.java
Labels: cla-signed

#8448 Hive cannot read ORC ACID table updated by Trino twice
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveUpdatablePageSource.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplit.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/AbstractFileFormat.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#8476 Introduce SystemTableProvider
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionsSystemTableProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/PropertiesSystemTableProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/SystemTableHandler.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/SystemTableProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed

#8434 Add configurable insert_batch_size JDBC session property
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataSessionProperties.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
Labels: cla-signed

#8485 Fix README for Trino Verifier
  service/trino-verifier/README.md
Labels: cla-signed

#8408 Support materialized view storage table column casting
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
  core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
Labels: cla-signed

#8494 Move FastutilSetHelper to trino-plugin-toolkit
  core/trino-main/src/main/java/io/trino/sql/gen/InCodeGenerator.java
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  lib/trino-plugin-toolkit/pom.xml
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/FastutilSetHelper.java
  lib/trino-rcfile/pom.xml
Labels: cla-signed

#8436 Added a way to grant/revoke schema privileges from hive metadata
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java
Labels: cla-signed

#8487 Use a temporary table to verify if deletes are supported
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
Labels: cla-signed, tests:hive

#8498 Improve naming in tests
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed

#8480 Make OrcFileWriter number ACID rows correctly across multiple pages
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriter.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#8419 Add list of supported statements for PostgreSQL connector
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sql-support-others.fragment
Labels: cla-signed, docs

#8483 Reword and extend list of supported SQL statements
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed

#8510 Mark TestHiveStorageFormats#testCreateTableAs as flaky
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#8377 Add requirements for Thrift connector
  docs/src/main/sphinx/connector/thrift.rst
Labels: cla-signed, docs

#8425 Add list of supported statements for Iceberg connector
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#8467 Don't exclude tests in trino-tests module to only run on CI
  .github/workflows/ci.yml
  testing/trino-tests/pom.xml
Labels: cla-signed

#7801 Move UUID type to SPI module
  core/trino-main/src/main/java/io/trino/metadata/TypeRegistry.java
  core/trino-main/src/test/java/io/trino/type/TestUuidOperators.java
  core/trino-main/src/test/java/io/trino/type/TestUuidType.java
  core/trino-spi/src/main/java/io/trino/spi/type/UuidType.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingTrinoClient.java
Labels: cla-signed

#8512 Update documentation for enable-coordinator-dynamic-filters-distribution
  docs/src/main/sphinx/admin/dynamic-filtering.rst
Labels: cla-signed

#8539 Explain statistic bean conflicts in Elastic tests
  plugin/trino-elasticsearch/pom.xml
Labels: cla-signed

#8496 Allow bypassing temporary table during insert for jdbc-based connectors
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataSessionProperties.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
Labels: cla-signed

#8541 Use SystemTableProvider in SystemTableAwareAccessControl
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionsSystemTableProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/PropertiesSystemTableProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/SystemTableProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SystemTableAwareAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/SystemTables.java
Labels: cla-signed

#8528 Remove unnecessary locking
  core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
Labels: cla-signed

#8504 Wrap stream from HadoopInputFile to work around #5201
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/HdfsInputFile.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/AbstractTestIcebergConnectorTest.java
Labels: cla-signed

#8503 Simplify & clean up table handle lookup in DruidJdbcClient
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Labels: cla-signed

#8561 Fix broken link to BigQuery authentication section
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed

#8560 Add reusable SQL commands snippet to SQL Server doc
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed

#8563 Fix Cassandra documentation for supported partition types
  docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed, docs

#8318 Remove unnecessary jackson-dataformat-cbor dependency
  pom.xml
Labels: cla-signed

#8160 Clarify non-transactional delete is for partitioned tables only
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#8535 Fix pre-sorted input validation for constants
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateLimitWithPresortedInput.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestPartialTopNWithPresortedInput.java
  core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateLimitWithPresortedInput.java
Labels: bug, cla-signed

#8568 Fix flaky TestMySqlCaseInsensitiveMapping
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlCaseInsensitiveMapping.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
Labels: cla-signed

#8319 Update to aircompressor 0.19
  pom.xml
Labels: cla-signed

#8472 Add documentation for materialized views
  docs/src/main/sphinx/sql.rst
  docs/src/main/sphinx/sql/create-materialized-view.rst
  docs/src/main/sphinx/sql/drop-materialized-view.rst
  docs/src/main/sphinx/sql/refresh-materialized-view.rst
  docs/src/main/sphinx/sql/show-create-materialized-view.rst
Labels: cla-signed, docs

#8515 Add SQL statement support
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sql-support-others.fragment
  docs/src/main/sphinx/connector/sqlserver.rst
  docs/src/main/sphinx/language.rst
  docs/src/main/sphinx/language/sql-support.rst
Labels: cla-signed, docs

#8234 Set thread context class loader for all plugin factories
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
  core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/GroupProviderManager.java
  core/trino-main/src/main/java/io/trino/server/SessionPropertyDefaults.java
  core/trino-main/src/main/java/io/trino/server/security/CertificateAuthenticatorManager.java
  core/trino-main/src/main/java/io/trino/server/security/PasswordAuthenticatorManager.java
Labels: cla-signed

#8584 Add support for json type in MongoDB
  plugin/trino-mongodb/pom.xml
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/TypeUtils.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#8549 Add dbref field support for mongodb connector;
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Labels: cla-signed

#8585 Avoid using deprecated JsonFactory.disable method
  core/trino-main/src/main/java/io/trino/operator/scalar/JsonExtract.java
  core/trino-main/src/main/java/io/trino/operator/scalar/JsonFunctions.java
  core/trino-main/src/main/java/io/trino/operator/scalar/JsonOperators.java
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
  service/trino-proxy/src/main/java/io/trino/proxy/ProxyResource.java
Labels: cla-signed, maintenance

#8586 Mark view creator in metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#8597 More Iceberg bucketing tests
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java
Labels: cla-signed

#8610 Remove redundant override
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
Labels: cla-signed, maintenance

#8619 Make DiscreteSet in Domain public
  core/trino-spi/src/main/java/io/trino/spi/predicate/Domain.java
Labels: cla-signed

#8620 Implement getCompletedPositions in ParquetPageSource
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java
Labels: cla-signed

#8614 Restore code comment for Iceberg min/max in relation to file format
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#8624 Improve positionsArrayToSelectedPositions
  core/trino-main/src/main/java/io/trino/operator/project/PageFilter.java
Labels: cla-signed

#8628 Enable iceberg materialized view tests
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#8631 Fix typo
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#8621 Add views to SQL support for Iceberg connector
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#8630 Remove JdbcIdentity
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadataFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedIdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedJdbcIdentityCacheMappingModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/IdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcIdentity.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/SingletonIdentityCacheMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialPropertiesProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/DefaultCredentialPropertiesProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/EmptyCredentialProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/ExtraCredentialProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/StaticCredentialProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/CachingIdentifierMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/DefaultIdentifierMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/ForwardingIdentifierMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/IdentifierMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/RemoteTableNameCacheKey.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/RuleBasedIdentifierMapping.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/credential/TestExtraCredentialProvider.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixMetadata.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
Labels: cla-signed

#7640 updating hive.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#8579 Add JDBC URL parameter for MySQL
  docs/src/main/sphinx/connector/mysql.rst
Labels: cla-signed, docs

#8609 Rename 'insert.batch-size' configuration property into 'write.batch-size'
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataSessionProperties.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
Labels: cla-signed

#8646 Iceberg test cleanup
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, maintenance, test

#8600 Fix SHOW CREATE SCHEMA information_schema
  core/trino-main/src/main/java/io/trino/metadata/CatalogMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test

#8056 Remove deprecated TupleDomain.transform
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java
Labels: cla-signed

#8353 Clarify and extend user mapping topic
  docs/src/main/sphinx/security/user-mapping.rst
Labels: cla-signed, docs

#8449 Add functions by topic
  docs/src/main/sphinx/functions.rst
  docs/src/main/sphinx/functions/list-by-topic.rst
Labels: cla-signed, docs

#8438 Add certificate auth doc
  docs/src/main/sphinx/installation/cli.rst
  docs/src/main/sphinx/installation/jdbc.rst
  docs/src/main/sphinx/security.rst
  docs/src/main/sphinx/security/authentication-types.rst
  docs/src/main/sphinx/security/certificate.rst
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed, docs

#8370 Document internal TLS configuration
  docs/src/main/sphinx/security/internal-communication.rst
Labels: cla-signed, docs

#8622 Add details about materialized views in Iceberg
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#8601 Update JDBC connectors to reflect SQL DELETE support
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sql-delete-limitation.fragment
  docs/src/main/sphinx/connector/sqlserver.rst
  docs/src/main/sphinx/sql/delete.rst
Labels: cla-signed, docs

#8645 Remove incorrect useless code from Iceberg TableStatisticsMaker
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#8618 Add tests counting metastore accesses for Iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/CountingAccessFileHiveMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Labels: cla-signed

#8647 Fix reading Iceberg stats when table has nested fields
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/Partition.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#8661 Rename conversion method for consistency
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed, maintenance

#8670 Rename testCrossJoinInequalityWithCast tests
  core/trino-main/src/test/java/io/trino/sql/planner/TestDynamicFilter.java
Labels: cla-signed

#8464 added docs for date types and predicates supported in elastic
  docs/src/main/sphinx/connector/elasticsearch.rst
Labels: cla-signed, docs

#8688 Remove deprecated strictConfig usage
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  core/trino-main/src/test/java/io/trino/failuredetector/TestHeartbeatFailureDetector.java
  core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
  docs/src/main/sphinx/develop/example-http.rst
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloConnectorFactory.java
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopConnectorFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnectorFactory.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/credential/TestExtraCredentialProvider.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorFactory.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraConnectorFactory.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchConnectorFactory.java
  plugin/trino-example-http/src/main/java/io/trino/plugin/example/ExampleConnectorFactory.java
  plugin/trino-example-http/src/test/java/io/trino/plugin/example/ExampleHttpServer.java
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConnectorFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
  plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxConnectorFactory.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorFactory.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisConnectorFactory.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestingKinesisConnectorFactory.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduConnectorFactory.java
  plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileConnectorFactory.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryConnectorFactory.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnectorFactory.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/file/FileAuthenticatorFactory.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/file/FileGroupProviderFactory.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticatorFactory.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/salesforce/SalesforceAuthenticatorFactory.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixConnectorFactory.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixConnectorFactory.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnectorFactory.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorFactory.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusHttpServer.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorConnectorFactory.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/backup/TestHttpBackupStore.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorFactory.java
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/FileResourceGroupConfigurationManagerFactory.java
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManagerFactory.java
  plugin/trino-session-property-managers/src/main/java/io/trino/plugin/session/db/DbSessionPropertyManagerFactory.java
  plugin/trino-session-property-managers/src/main/java/io/trino/plugin/session/file/FileSessionPropertyManagerFactory.java
  plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/db/TestDbSessionPropertyManagerIntegration.java
  plugin/trino-thrift-testing-server/src/main/java/io/trino/plugin/thrift/server/ThriftTpchServer.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftConnectorFactory.java
  service/trino-proxy/src/main/java/io/trino/proxy/TrinoProxy.java
  service/trino-proxy/src/test/java/io/trino/proxy/TestProxyServer.java
  service/trino-verifier/src/main/java/io/trino/verifier/VerifyCommand.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/Commands.java
  testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/H2ResourceGroupConfigurationManagerFactory.java
Labels: cla-signed

#8689 Avoid redundant metastore calls for non-system Iceberg tables
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Labels: cla-signed

#8681 Fix incorrect pushdown of simplified domain in postgresql
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
Labels: cla-signed

#8527 Add comment about batch size property purpose and usage
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
Labels: cla-signed

#8676 Avoid re-checking Iceberg table existence
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Labels: cla-signed

#8554 Improve support for correlated subqueries with GROUP BY or LIMIT
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PlanNodeDecorrelator.java
  core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
Labels: cla-signed

#8678 Add docs for current_groups function
  docs/src/main/sphinx/functions/list-by-topic.rst
  docs/src/main/sphinx/functions/list.rst
  docs/src/main/sphinx/functions/session.rst
Labels: cla-signed

#8666 Add SQL support content to Druid connector
  docs/src/main/sphinx/connector/druid.rst
Labels: cla-signed, docs

#8664 Add SQL support content to MySQL connector
  docs/src/main/sphinx/connector/mysql.rst
Labels: cla-signed, docs

#8665 Add SQL support content to Oracle connector
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#8668 Add SQL support content to SingleStore connector
  docs/src/main/sphinx/connector/memsql.rst
Labels: cla-signed, docs

#8669 Add SQL support content to Redshift connector
  docs/src/main/sphinx/connector/redshift.rst
Labels: cla-signed, docs

#8667 Add SQL support content to ClickHouse connector
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed, docs

#8348 Document row pattern recognition in window
  docs/src/main/sphinx/sql.rst
  docs/src/main/sphinx/sql/match-recognize.rst
  docs/src/main/sphinx/sql/pattern-recognition-in-window.rst
  docs/src/main/sphinx/sql/select.rst
Labels: cla-signed

#8685 Remove Flaky annotation on tests expected to work
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergCreateTable.java
Labels: cla-signed

#8674 Test materialized views having column names
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#7769 Minor improvement to CLI output format documentation
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs, jdbc

#8572 Remove extra stat calls in coordinator for Iceberg write
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CommitTaskData.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
Labels: cla-signed

#8714 Allow assuming an AWS IAM Role in Elasticsearch connector
  docs/src/main/sphinx/connector/elasticsearch.rst
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/AwsSecurityConfig.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestAwsSecurityConfig.java
Labels: cla-signed

#8695 Increase chances of testLargeInFailureOnPartitionedColumns passing
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#8706 Test system.runtime.nodes explicitly
  testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestSystemConnector.java
Labels: cla-signed, test

#8654 Add .run directory to .gitignore
  .gitignore
Labels: cla-signed, maintenance

#8699 Test optimized Parquet writer in Hive product tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, test, tests:hive

#8686 Add 360 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-360.md
Labels: cla-signed, release-notes

#8726 Update ConnectorMetadata#listTables contract
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
Labels: cla-signed
