Repository trinodb/trino, pull requests merged in 2021-06, with the labels that each got.

#8148 Improve getMaterializedViewFreshness stub
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
Labels: cla-signed

#8155 Document getTableHandle, getView, getMaterializedView border cases
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
Labels: cla-signed

#8151 Avoid throwing exception for MVs in iceberg getTableHandle
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/AbstractTestIcebergConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#8162 Update Provisio Maven Plugin version
  pom.xml
Labels: cla-signed

#7606 Add table redirection support in SPI
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
  core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/RedirectionAwareTableHandle.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/SchemaTableName.java
  core/trino-spi/src/main/java/io/trino/spi/connector/TableColumnsMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-tests/src/test/java/io/trino/execution/TestTableRedirection.java
Labels: cla-signed

#8156 Update setup-java action to v2
  .github/workflows/ci.yml
Labels: cla-signed

#8108 Extract method to build copy table sql
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#8165 Avoid extra metadata call in iceberg getTableHandle
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#7696 Fix Thrift client method name to match code style
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/FailureAwareThriftMetastoreClient.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreClient.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
Labels: cla-signed

#8031 Edit requirements section of connectors
  docs/src/main/sphinx/connector/cassandra.rst
  docs/src/main/sphinx/connector/kafka.rst
  docs/src/main/sphinx/connector/mongodb.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#8164 Add 358 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-358.md
Labels: cla-signed, release-notes

#8166 Rename Hive connector "hive-hadoop2 to "hive"
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
  core/trino-server/src/main/provisio/presto.xml
  docs/src/main/sphinx/connector/hive-alluxio.rst
  docs/src/main/sphinx/connector/hive-caching.rst
  docs/src/main/sphinx/connector/hive.rst
  plugin/trino-hive-hadoop2/pom.xml
  plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/HiveHadoop2Plugin.java
  plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/HivePlugin.java
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHivePlugin.java
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreWithQueryRunner.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive_timestamp_nanos.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive_with_external_writes.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-cached/hive-coordinator.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-cached/hive-worker.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-tls-kerberos/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdfs-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-cross-realm/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-data-protection/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-wire-encryption/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-no-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hive-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-kms-hdfs-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-kms-hdfs-no-impersonation/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-hive/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-kerberos-hives/hive1.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-kerberos-hives/hive2.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-mixed-hives/hive1.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/two-mixed-hives/hive2.properties
  testing/trino-server-dev/etc/catalog/hive.properties
Labels: cla-signed

#8176 Add PageJoinerTransformation
  core/trino-main/src/main/java/io/trino/operator/join/DefaultPageJoiner.java
  core/trino-main/src/main/java/io/trino/operator/join/LookupJoinOperator.java
  core/trino-main/src/main/java/io/trino/operator/join/PageJoiner.java
  core/trino-main/src/main/java/io/trino/operator/join/SpillingJoinProcessor.java
Labels: cla-signed

#8102 Mention hashCode and equals as part of contract of ColumnHandle
  core/trino-spi/src/main/java/io/trino/spi/connector/ColumnHandle.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableHandle.java
Labels: cla-signed

#8119 Add product test launcher 'env describe' command
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/Launcher.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/docker/DockerFiles.java
Labels: cla-signed

#8159 add example of function murmur3 and update the link to it in list.rst
  docs/src/main/sphinx/functions/binary.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#8180 Remove dash as allowed character for environment
  docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#8169 Remove outdated compatible substitute for TrinoContainer
  testing/trino-test-jdbc-compatibility-old-server/src/test/java/io/trino/TestJdbcResultSetCompatibilityOldServer.java
Labels: cla-signed

#8181 Remove unused Hive allow-corrupt-writes config
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Labels: cla-signed

#8153 Avoid including hive views in iceberg SHOW TABLES
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataListing.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveMetadataListing.java
Labels: cla-signed

#8191 Update multiple event listeners to add config property
  docs/src/main/sphinx/develop/event-listener.rst
Labels: cla-signed, docs

#8109 Fix from_iso8601_timestamp_nanos examples
  docs/src/main/sphinx/functions/datetime.rst
Labels: cla-signed, docs

#7934 Add documentation for CURRENT_CATALOG and CURRENT_SCHEMA
  docs/src/main/sphinx/functions/session.rst
Labels: cla-signed, docs

#7912 Update documentation for parametric TIME WITH TIME ZONE #5316
  docs/src/main/sphinx/language/types.rst
Labels: cla-signed, docs

#8201 Fix wrong result due to column position mismatch in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryResultPageSource.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
Labels: cla-signed

#8138 Handle row ambiguous dereference as semantic error
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#8184 Fix ValidateLimitWithPresortedInput for multiple sorted inputs
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateLimitWithPresortedInput.java
  core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateLimitWithPresortedInput.java
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchConnectorTest.java
Labels: cla-signed

#8186 Remove unused deprecated methods
  core/trino-main/src/test/java/io/trino/operator/scalar/AbstractTestFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/FunctionAssertions.java
Labels: cla-signed

#8179 Print full thread dump when tests hang
  testing/trino-product-tests-launcher/pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteRun.java
  testing/trino-testing-services/pom.xml
  testing/trino-testing-services/src/main/java/io/trino/jvm/Threads.java
  testing/trino-testing-services/src/main/java/io/trino/testng/services/LogTestDurationListener.java
Labels: cla-signed, enhancement, test

#8210 Enhance join tests
  core/trino-main/src/test/java/io/trino/operator/join/TestHashJoinOperator.java
Labels: cla-signed

#8206 Make BenchmarkHiveFileFormats extendable
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkFileFormatsUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkHiveFileFormat.java
Labels: cla-signed

#8211 Extract JoinTestUtils
  core/trino-main/src/test/java/io/trino/operator/join/JoinTestUtils.java
  core/trino-main/src/test/java/io/trino/operator/join/TestHashJoinOperator.java
Labels: cla-signed

#8205 Fix formatting errors in role documentation
  docs/src/main/sphinx/sql/show-role-grants.rst
  docs/src/main/sphinx/sql/show-roles.rst
Labels: cla-signed, docs

#8203 Cleanup JsonCodec bindings in server module
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/test/java/io/trino/server/TestQueryResource.java
Labels: cla-signed

#8199 Add bing_tile_quadkey() to list.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#7799 Clarify metastore filtering and remove unnecessary code
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/MetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/file/TestFileHiveMetastoreConfig.java
Labels: cla-signed

#8196 Update table type validation in FileHiveMetastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
Labels: cla-signed

#8215 Update Phoenix 5 client to 5.1.2
  plugin/trino-phoenix5/pom.xml
Labels: cla-signed

#8224 Enable maven --strict-checksums on CI
  .github/workflows/ci.yml
Labels: cla-signed

#8228 Fix exception message
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
Labels: cla-signed

#8226 Fix getPartitionNamesByFilter for Glue metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, tests:all, tests:hive

#8230 Fix typo in method name
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkFileFormatsUtils.java
Labels: cla-signed

#8232 Remove unused assignment
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed

#7552 Convert oracle date/timestamp/timestamp with tz type tests to SqlDataTypeTest
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
Labels: cla-signed

#8238 Rename isTopNLimitGuaranteed to isTopNGuaranteed
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#8241 Use HiveMetastoreClosure in HiveMaterializedViewMetadataFactory
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/DefaultHiveMaterializedViewMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
Labels: cla-signed

#8212 Remove redunant limitation
  docs/src/main/sphinx/admin/dynamic-filtering.rst
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/connector/memory.rst
Labels: cla-signed, docs

#8246 Pass filter information to OperatorFactories
  core/trino-main/src/main/java/io/trino/operator/OperatorFactories.java
  core/trino-main/src/main/java/io/trino/operator/TrinoOperatorFactories.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/join/BenchmarkHashBuildAndJoinOperators.java
  core/trino-main/src/test/java/io/trino/operator/join/JoinTestUtils.java
  core/trino-main/src/test/java/io/trino/operator/join/TestHashJoinOperator.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/HashBuildAndJoinBenchmark.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/HashBuildBenchmark.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/HashJoinBenchmark.java
Labels: cla-signed

#8254 Remove obsolete Cli class
  pom.xml
  testing/trino-product-tests/pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/Cli.java
Labels: cla-signed

#8247 Validate ordinal based grouping expressions during analysis
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#8257 Keep Ldap product tests together
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite6NonGeneric.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java
Labels: cla-signed

#8265 Allow MATERIALIZED_VIEW in FileHiveMetastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
Labels: cla-signed

#8266 Increase testShowSchemasLikeWithEscape robustness
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueries.java
Labels: cla-signed

#8272 Use Trino instead of Presto in TestHiveTransactionalTable
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BucketingType.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TransactionalTableType.java
Labels: cla-signed, tests:hive

#8263 Validate no delete deltas for a non full ACID table
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
Labels: cla-signed

#8237 Retain more cached information upon insert
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
Labels: cla-signed

#8273 Update Tempto to 185
  pom.xml
Labels: cla-signed, tests:all

#8271 Fix property usage example issue in docs
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed

#8198 Document the oauth2 callback/redirect URL
  docs/src/main/sphinx/security/oauth2.rst
Labels: cla-signed, docs

#8275 Use shorter form of VARCHAR literal
  core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayExceptFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestZipFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestZipWithFunction.java
  core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/gen/TestExpressionCompiler.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/TestExpressionVerifier.java
  core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFormat.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRecursiveCte.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatching.java
  core/trino-main/src/test/java/io/trino/sql/query/TestShowQueries.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#8135 Set default time zone for the current session
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/SetTimeZoneTask.java
  core/trino-main/src/main/java/io/trino/server/QueryExecutionFactoryModule.java
  core/trino-main/src/main/java/io/trino/server/QuerySessionSupplier.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/util/StatementUtils.java
  core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/SetTimeZone.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  docs/src/main/sphinx/sql.rst
  docs/src/main/sphinx/sql/set-time-zone.rst
Labels: cla-signed

#8290 Test MySQL JDBC URL verification
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlJdbcConfig.java
Labels: cla-signed

#8282 Fixing typo in iceberg connector documentation
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed

#8304 Add Redshift requirements
  docs/src/main/sphinx/connector/redshift.rst
Labels: cla-signed, docs

#8288 Exclude snakeyaml from the build
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-pinot/pom.xml
Labels: cla-signed

#8303 Add assertEventually overload with retryDuration
  core/trino-main/src/main/java/io/trino/testing/assertions/Assert.java
Labels: cla-signed

#8295 Add support for generic parameters in `make_set_digest` function
  core/trino-main/src/main/java/io/trino/type/setdigest/BuildSetDigestAggregation.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSetDigestFunctions.java
Labels: cla-signed

#8316 Ignore VSCode config folder
  .gitignore
Labels: cla-signed

#8294 Remove usage of /v1/info for JDBC driver
  client/trino-jdbc/src/main/java/io/trino/jdbc/NonRegisteringTrinoDriver.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/QueryExecutor.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestQueryExecutor.java
Labels: cla-signed

#8204 Fixed #3605: Elastic searching for field with null and value not working correctly
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
Labels: cla-signed

#8281 Document luhn_check function
  docs/src/main/sphinx/functions/list.rst
  docs/src/main/sphinx/functions/string.rst
Labels: cla-signed, docs

#8324 Bump com.esri.geometry version
  pom.xml
Labels: cla-signed

#8308 Minor ExpressionInterpreter cleanup
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
Labels: cla-signed

#8309 Propagate runtime errors in ExpressionInterpreter
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
Labels: cla-signed

#8276 Encode unbounded varchar value without a CAST
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/planner/LiteralEncoder.java
  core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLiteralEncoder.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
Labels: cla-signed

#8083 Configure SSL for Hydra IdP in product tests
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HydraIdentityProvider.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeOauth2.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hydra-identity-provider/cert/generate.sh
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hydra-identity-provider/cert/localhost.conf
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hydra-identity-provider/cert/localhost.pem
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2/config.properties
Labels: cla-signed

#8293 Fixes #8158 - Multiple entries with same key for aliases in elasticsearch connector
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
Labels: cla-signed

#8320 Reset glue partition fetcher use getGetPartitionThreads
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
Labels: cla-signed

#8327 Fix system.metadata.table_comments for views and MVs
  core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#8142 Fix flaky TestJdbcConnection
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
Labels: cla-signed

#8315 Add requirements to Accumulo connector
  docs/src/main/sphinx/connector/accumulo.rst
Labels: cla-signed, docs

#8314 Add requirements to MemSQL connector
  docs/src/main/sphinx/connector/memsql.rst
Labels: cla-signed, docs

#8362 Refactor HiveMetadataFactory
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
Labels: cla-signed

#8338 Update to Parquet 1.12.0
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java
  pom.xml
Labels: cla-signed, tests:hive

#8363 Rename `arrayToPrestoType` method to `arrayToTrinoType`
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#7954 Add automatic internal communications HTTPS configuration
  core/trino-main/src/main/java/io/trino/server/InternalCommunicationModule.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
  pom.xml
Labels: WIP, cla-signed

#8134 Fix handling of multiple LDAP user bind patterns
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticator.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite6NonGeneric.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-bind-dn/password-authenticator.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-referrals/password-authenticator.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-without-ssl/password-authenticator.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap/password-authenticator.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/ImmutableLdapObjectDefinitions.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cli/TestTrinoLdapCli.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/BaseLdapJdbcTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestLdapTrinoJdbc.java
Labels: cla-signed

#8371 Capture column level dependency for Set Operators
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#8375 Restore non-cancellable DispatchQueryCreationFuture
  core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
Labels: cla-signed

#8336 Add tests for Hive views with unions
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
Labels: cla-signed

#8366 Add requirements for Kudu connector
  docs/src/main/sphinx/connector/kudu.rst
Labels: cla-signed, docs

#8389 Revert "Add tests for Hive views with unions"
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Labels: cla-signed

#8369 Basic result stability tests for $approx_set
  core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestApproximateSetGeneric.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericBoolean.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericDouble.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericInteger.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericIpAddress.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericLong.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericLongTimestamp.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericShortTimestamp.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericSmallint.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericTinyint.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericVarchar.java
Labels: cla-signed

#8382 Add requirements for ClickHouse connector
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed, docs

#8392 Add requirements for Druid connector
  docs/src/main/sphinx/connector/druid.rst
Labels: cla-signed, docs

#8213 Clarify metastore cache property
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#8351 Improve DistinctLimitOperator
  core/trino-main/src/main/java/io/trino/operator/DistinctLimitOperator.java
Labels: cla-signed

#8087 Add page for JWT authentication
  docs/src/main/sphinx/installation/cli.rst
  docs/src/main/sphinx/installation/jdbc.rst
  docs/src/main/sphinx/security.rst
  docs/src/main/sphinx/security/authentication-types.rst
  docs/src/main/sphinx/security/jwt.rst
Labels: cla-signed, docs

#8394 Reorder functions and operators list alphabetically
  docs/src/main/sphinx/functions.rst
Labels: cla-signed, docs

#8321 Create MongoDB index for _schema collection only if absent
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
Labels: cla-signed

#8406 Remove unused parameters
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#8378 Push topN to Phoenix unconditionally
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
Labels: cla-signed

#8060 Support TIMESTAMPS with precisions higher than 3 in MySQL
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
Labels: cla-signed

#8407 Remove unnecessary addRelationCoercion call
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#8280 Port 'geometry_nearest_points' UDF
  docs/src/main/sphinx/functions/geospatial.rst
  plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoFunctions.java
Labels: cla-signed

#8400 Add missing comma in documentation JSON
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#8397 Build Docker image for arm64
  .github/workflows/ci.yml
  core/docker/amd64.dockerfile
  core/docker/arm64.dockerfile
  core/docker/build-local.sh
  core/docker/build-remote.sh
  core/docker/container-test.sh
Labels: cla-signed

#8283 Externalised destination table cache expiry duration for BigQuery Connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
Labels: cla-signed

#8405 Record output column datatype in EventListener
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/OutputColumnMetadata.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#8416 Update SQL Server docker images to use the new repository
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java
  plugin/trino-sqlserver/src/test/resources/container-license-acceptance.txt
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeSqlserver.java
  testing/trino-product-tests/README.md
Labels: cla-signed

#8103 Raise minimum required Java version to 11.0.11
  README.md
  core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
  docs/src/main/sphinx/installation/deployment.rst
  pom.xml
Labels: cla-signed, tests:all, tests:hive

#8373 Reject CTAS with skip_header_line_count > 0
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCsvFileHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestTextFileHiveTable.java
Labels: cla-signed

#8147 Document lambda functions
  docs/src/main/sphinx/functions/lambda.rst
Labels: cla-signed, docs

#8214 Add requirements for Iceberg
  docs/src/main/sphinx/connector/iceberg.rst
Labels: WIP, cla-signed, docs

#8412 Reformat BigQuery connector requirements section
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#8423 Add requirements for Phoenix connector
  docs/src/main/sphinx/connector/phoenix.rst
Labels: cla-signed, docs

#8426 Fix title and link to book
  docs/src/main/sphinx/overview/concepts.rst
Labels: cla-signed, docs

#8390 Support CREATE and INSERT for skip_header_line_count=1
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/RecordFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/TextHeaderWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/TextRecordWriter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCsvFileHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestTextFileHiveTable.java
Labels: cla-signed, tests:hive

#8342 Migrate from assertThat to assertQueryFailure
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestAlterTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestInsertIntoCassandraTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestExternalHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestGrantRevoke.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveIgnoreAbsentPartitions.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMaterializedView.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePartitionProcedures.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePartitionsTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSchema.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestRoles.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestSparkCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaAvroWritesSmokeTest.java
Labels: cla-signed, tests:hive

#8424 Add requirements for Prometheus connector
  docs/src/main/sphinx/connector/prometheus.rst
Labels: cla-signed, docs

#8430 Avoid trailing spaces in q91 LIKE predicate
  testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q91.sql
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q91.plan.txt
  testing/trino-product-tests/src/main/resources/sql-tests/testcases/tpcds/q91.sql
Labels: cla-signed
