Repository trinodb/trino, pull requests merged in 2021-08, with the labels that each got.

#8735 Update error-prone to 2.8.0
  pom.xml
Labels: cla-signed

#8536 Iceberg: add new fields in files system table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/PageListBuilder.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSystemTables.java
Labels: cla-signed

#8705 Reject Glue and Alluxio metastores from Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetastoreModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
Labels: cla-signed

#8756 Disable oauth2 product tests
  .github/workflows/ci.yml
Labels: cla-signed

#6063 Added ability to have unique table location for each iceberg table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java
Labels: cla-signed

#8757 Test Iceberg and Hive table compatibility
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java
Labels: cla-signed, test

#8677 Use table name as cache key explicitly
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#8643 Extract common JDBC configurations into their own fragment
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
  docs/src/main/sphinx/connector/jdbc-type-mapping.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#8767 Remove note about connector-specific ANALYZE support
  docs/src/main/sphinx/sql/analyze.rst
Labels: cla-signed, docs

#8770 Update PostgreSQL driver to 42.2.23
  plugin/trino-postgresql/pom.xml
  pom.xml
Labels: cla-signed

#8768 Use FluentFuture in QueuedStatementResource
  core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
Labels: cla-signed

#8771 Add CI variable for Maven command
  .github/workflows/ci.yml
Labels: cla-signed

#8779 Resolve issue with OAuth2 product tests and reenable
  .github/workflows/ci.yml
Labels: cla-signed

#8790 Document non-transactional-insert property for applicable connectors
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/non-transactional-insert.fragment
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#8775 Update code not to use QueryAssert.containsExactly and use containsEx…
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestAlterTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/blackhole/TestBlackHoleConnector.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/functions/TestFunctions.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/functions/operators/TestComparison.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/functions/operators/TestLogical.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAllDatatypesFromHiveConnector.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSymlinkInputFormat.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCompression.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestExternalHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCaching.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercion.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePartitionsTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestInsertIntoHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestParquetSymlinkInputFormat.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestTextFileHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaPushdownSmokeTest.java
Labels: cla-signed

#8815 Pin selenium/standalone-chrome-debug docker image version
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/SeleniumChrome.java
Labels: cla-signed

#6433 fix session property casing typo
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
Labels: cla-signed

#8828 Add test for MongoDB ObjectId
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestObjectIdFunctions.java
Labels: cla-signed

#8629 Fix Cassandra Range pushdown
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed

#8835 Run Kafka and Pinot docker in Pinot query runner
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
Labels: maintenance

#8824 Get ObjectId from timestamp
  docs/src/main/sphinx/connector/mongodb.rst
  docs/src/main/sphinx/functions/list.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdFunctions.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestObjectIdFunctions.java
Labels: cla-signed

#8837 Avoid hard-coded http scheme for Pinot controller url
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
Labels: cla-signed

#8832 Enable mongodb.socket-keep-alive by default
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
Labels: cla-signed

#8825 Upgrade google-http-client and google-oauth-client version
  plugin/trino-google-sheets/pom.xml
Labels: cla-signed

#8810 Expose $properties table for views in Hive connector
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/PropertiesSystemTableProvider.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePropertiesTable.java
Labels: cla-signed, tests:hive

#8846 Add link for MongoDB objectid_timestamp in function list
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#8502 Add support for from_utc_timestamp in Hive views translation
  plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/CanonicalizeHiveTimezoneId.java
  plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/HivePlugin.java
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
Labels: cla-signed

#8850 Fix incorrect comment
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#8860 Fix assertions for old Hive versions in TestHiveViews for from_utc_timestamp
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
Labels: cla-signed, tests:hive

#8874 Add instructions for attaching a debugger to product tests
  testing/trino-product-tests/README.md
Labels: cla-signed

#8411 Added merge strategy to DEVELOPMENT.md
  DEVELOPMENT.md
Labels: cla-signed

#8859 Check table existence in Pinot connector
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotMetadata.java
Labels: cla-signed

#8876 Refactor table initialization in testFromUtcTimestamp
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
Labels: cla-signed, tests:hive

#8799 Document JDBC sessionUser parameter
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#8871 Add and update to consistent anchors
  docs/src/main/sphinx/connector/hive-alluxio.rst
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/installation/deployment.rst
  docs/src/main/sphinx/release/release-330.rst
Labels: cla-signed, docs

#8845 Properly delimit identifiers in DataType expression created from Type
  core/trino-main/src/main/java/io/trino/sql/analyzer/TypeSignatureTranslator.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestTypeSignatureTranslator.java
  core/trino-parser/src/main/java/io/trino/sql/ReservedIdentifiers.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
Labels: cla-signed

#8839 Glue analyze performance tweaks
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/RecordingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/alluxio/AlluxioHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DisabledGlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/UnimplementedHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/CountingAccessFileHiveMetastore.java
Labels: cla-signed

#6977 Iceberg: refactor IcebergMetadata to support multiple catalogs
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CatalogType.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/HiveTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java
Labels: cla-signed

#8753 Remove unnecessary config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg/iceberg.properties
Labels: cla-signed

#8890 Update Hive Glue properties documentation
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#5150 Support pushdown for date, tinyint and smallint types in Cassandra
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraTestingUtils.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed, WIP

#8863 Add ALTER TABLE limitation fragment
  docs/src/main/sphinx/connector/alter-table-limitation.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#8888 Make CredentialPropertiesProvider generic
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialPropertiesProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/DefaultCredentialPropertiesProvider.java
Labels: cla-signed

#8899 Fix handling of inserting into non-bucketed ACID tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed

#8910 Improve BlockUtil#countUsedPositions
  core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
Labels: cla-signed

#8909 Update error-prone to 2.8.1
  pom.xml
Labels: cla-signed

#8898 Allow mock connector to return data
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorEntities.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorHandleResolver.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorPageSource.java
  core/trino-main/src/test/java/io/trino/connector/TestMockConnectorPageSource.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: cla-signed

#8894 Add Hadoop native libraries for macOS aarch64
  pom.xml
Labels: cla-signed

#8914 Properly handle projection in MockConnector
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: cla-signed

#8913 Add test for Hive partitioning using string values with special chars
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestTablePartitioningWithSpecialChars.java
Labels: cla-signed, tests:hive

#8809 Only set default schema if default catalog is used
  core/trino-main/src/main/java/io/trino/server/QuerySessionSupplier.java
  core/trino-main/src/test/java/io/trino/server/TestQuerySessionSupplier.java
Labels: cla-signed

#8916 Add schema rename test to connector test suites
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcCachingConnectorSmokeTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlGlobalTransactionMyConnectorSmokeTest.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed

#8578 Move AggregateFunctionRewriter to plugin toolkit
  lib/trino-plugin-toolkit/pom.xml
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/expression/AggregateFunctionPatterns.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/expression/AggregateFunctionRewriter.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/expression/AggregateFunctionRule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementAvgDecimal.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementAvgFloatingPoint.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCorr.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCount.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCountAll.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCovariancePop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCovarianceSamp.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementMinMax.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementRegrIntercept.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementRegrSlope.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementStddevPop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementStddevSamp.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementSum.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementVariancePop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementVarianceSamp.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
  plugin/trino-clickhouse/pom.xml
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ImplementAvgBigint.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ImplementAvgDecimal.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/ImplementAvgBigint.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/ImplementAvgBigint.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-sqlserver/pom.xml
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementAvgBigint.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerStddevPop.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerStdev.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerVariance.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerVariancePop.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#8936 Fix MemSQL testRenameSchema failures
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlLatestConnectorSmokeTest.java
Labels: cla-signed

#8903 Clarify SHOW STATS and where to expect NULL values
  docs/src/main/sphinx/sql/show-stats.rst
Labels: cla-signed, docs

#8926 Add SQL support to Kafka connector
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#8869 Improve error message for DROP/RENAME TABLE on MV
  core/trino-main/src/main/java/io/trino/execution/DropMaterializedViewTask.java
  core/trino-main/src/main/java/io/trino/execution/DropTableTask.java
  core/trino-main/src/main/java/io/trino/execution/DropViewTask.java
  core/trino-main/src/main/java/io/trino/execution/RenameTableTask.java
  core/trino-main/src/main/java/io/trino/execution/RenameViewTask.java
  core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
  core/trino-main/src/test/java/io/trino/execution/TestDropMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameViewTask.java
Labels: cla-signed

#7373 Add asRawJson decoding option for complex elasticsearch fields
  docs/src/main/sphinx/connector/elasticsearch.rst
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/BuiltinColumns.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/DecoderDescriptor.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchColumnHandle.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchErrorCode.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchPageSourceProvider.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ScanQueryPageSource.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/IndexMetadata.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/DecoderType.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/RawJsonDecoder.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
Labels: cla-signed, docs

#8772 Minor test cleanup
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, test, maintenance

#8944 Fix typos in SQL statement support page
  docs/src/main/sphinx/language/sql-support.rst
Labels: cla-signed

#8923 Add SQL support section to BigQuery connector
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#8703 Rename ExtraCredentialsBasedJdbcIdentityCacheMappingModule
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedIdentityCacheMappingModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPlugin.java
Labels: cla-signed

#8942 [for CI] Add helper method for common UUID conversions
  core/trino-main/src/main/java/io/trino/type/UuidOperators.java
  core/trino-spi/src/main/java/io/trino/spi/type/UuidType.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#8951 Propagate exception when reading metadata fails
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/HiveTableOperations.java
Labels: cla-signed

#8945 Add SQL support section to Accumulo connector
  docs/src/main/sphinx/connector/accumulo.rst
Labels: cla-signed

#8995 Add SQL support section to Redis connector
  docs/src/main/sphinx/connector/redis.rst
Labels: cla-signed, docs

#8993 Add SQL support section to Prometheus connector
  docs/src/main/sphinx/connector/prometheus.rst
Labels: cla-signed, docs

#9017 Fix failing test due to missing comma
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Labels: cla-signed, tests:hive

#8947 Add SQL support section to Cassandra connector
  docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed, docs

#9011 Mock more functionalities in MockConnector
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
Labels: cla-signed

#9005 Fix query failure of predicate pushdown to BigQuery DATETIME type
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
Labels: bug, cla-signed

#9028 Fix row field names in JSON documentation
  docs/src/main/sphinx/functions/json.rst
Labels: cla-signed

#9034 Append semicolons in DESCRIBE OUTPUT example
  docs/src/main/sphinx/sql/describe-output.rst
Labels: docs

#9024 Remove bogus INVALID_COLUMN_NAME error code
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
Labels: cla-signed

#8822 Fix issue with querying Iceberg using a structural type predicate
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#9037 Do not set currentProbePositionProducedRow even if no row was appended
  core/trino-main/src/main/java/io/trino/operator/join/DefaultPageJoiner.java
Labels: cla-signed

#9038 Fix failure query casts varchar to shorter char
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#9020 Update airbase to 112
  core/trino-main/src/main/java/io/trino/operator/scalar/LuhnCheckFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
  core/trino-main/src/test/java/io/trino/metadata/TestInternalBlockEncodingSerde.java
  core/trino-server-main/pom.xml
  core/trino-server-main/src/test/java/io/trino/server/TestDummy.java
  plugin/trino-accumulo-iterators/pom.xml
  plugin/trino-accumulo-iterators/src/test/java/io/trino/server/TestDummy.java
  pom.xml
  testing/trino-product-tests/src/test/java/io/trino/server/TestDummy.java
  testing/trino-testing-kafka/pom.xml
  testing/trino-testing-kafka/src/test/java/io/trino/server/TestDummy.java
Labels: cla-signed

#9055 Fix flakiness in TestMemoryConnectorTest
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
Labels: cla-signed

#9042 Fix testMaterializedViewsMetadata flakiness due to lack of pruning
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#9063 Update to aircompressor 0.21
  pom.xml
Labels: cla-signed
