Repository trinodb/trino, pull requests merged in 2022-05, with the labels that each got.

#11423 Support renaming table in MongoDB
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorSmokeTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
Labels: cla-signed, docs

#12194 Fix date column in tpcds connector
  plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsRecordSet.java
  plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcds.java
Labels: cla-signed

#12212 Add properties required by Datastax Cassandra java driver v4
  docs/src/main/sphinx/connector/cassandra.rst
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientConfig.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraClientConfig.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/cassandra.properties
  testing/trino-server-dev/etc/catalog/cassandra.properties
Labels: cla-signed, docs

#12202 Remove redundant check when creating DistributedStagesScheduler
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
Labels: cla-signed

#12230 Use Random instead of UUID to generate randomized prefix for echange spooling
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java
Labels: cla-signed

#11550 Support table redirections from Hive to Delta Lake
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreWithTableRedirectionsTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedFileMetastoreWithTableRedirections.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/DefaultHiveTableRedirectionsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Labels: cla-signed, tests:hive

#12161 Add Iceberg support for ALTER TABLE ... SET PROPERTIES
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, docs

#12244 Correct comment in PlanMatchPattern
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java
Labels: cla-signed

#11749 Enable auto purge default catalog property
  docs/src/main/sphinx/connector/hive.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Labels: cla-signed, docs, tests:hive

#10614 Enable writer scaling by default
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/PlanSanityChecker.java
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateScaledWritersUsage.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-main/src/test/java/io/trino/metadata/CountingAccessMetadata.java
  core/trino-main/src/test/java/io/trino/operator/TestTableWriterOperator.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestingWriterTarget.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesScaledWriters.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestBeginTableWrite.java
  core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateScaledWritersUsage.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: enhancement, cla-signed, tests:hive, performance

#12236 Add push inequality filter expression below join rule
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushInequalityFilterExpressionBelowJoinRuleSet.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDynamicFilter.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushInequalityFilterExpressionBelowJoinRuleSet.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateCrossJoins.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
Labels: cla-signed

#12248 Fix SourceDistributionTaskSource#getMoreTasks
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestStageTaskSourceFactory.java
Labels: cla-signed

#12228 Limit maximum number of output partitions for filesystem exchange
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeConfig.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeErrorCode.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeManager.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/AbstractTestExchangeManager.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/TestFileSystemExchangeConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFaultTolerantExecutionConnectorTest.java
Labels: cla-signed, tests:hive

#12176 Add bulk insert support to SQL Server connector
  docs/src/main/sphinx/connector/sqlserver.rst
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClientModule.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerConfig.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerSessionProperties.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/SqlServerQueryRunner.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConfig.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Labels: cla-signed, docs

#12209 Don't delete files when commit to hive metastore fails
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java
Labels: cla-signed

#12171 Bump minio to version 7.1.4
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/MinioClient.java
Labels: cla-signed, maintenance, no-release-notes

#12255 Fix some spelling problems
  core/trino-main/src/main/java/io/trino/sql/planner/Partitioning.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
  core/trino-main/src/test/java/io/trino/cost/StatsCalculatorAssertion.java
  core/trino-main/src/test/java/io/trino/cost/TestExchangeStatsRule.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/AggregationMatcher.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/GroupIdMatcher.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneExchangeColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionThroughExchange.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
  core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateAggregationsWithDefaultValues.java
  core/trino-spi/src/main/java/io/trino/spi/connector/BasicRelationStatistics.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableCache.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableLoadingCache.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnIndexBuilder.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnIndexFilter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
Labels: cla-signed, tests:hive

#12252 Remove `HiveTableRedirectionsProvider` interface
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/DefaultHiveTableRedirectionsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableRedirectionsProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
Labels: cla-signed, maintenance, tests:hive, no-release-notes

#12235 Fix NPE assertions on JDK17 for MemSQL negative date test
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
Labels: cla-signed

#12221 Add configuration property for Hive view security mode
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/LegacyHiveViewReader.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Labels: cla-signed, docs, tests:hive

#12271 Allow for longer error messages in verifier query log
  service/trino-verifier/src/main/java/io/trino/verifier/VerifierQueryEventDao.java
Labels: cla-signed

#12272 Document hive.hive-views.run-as-invoker
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#11960 Add template for release notes
  docs/release-template.md
Labels: cla-signed, docs

#12184 Add Trino 380 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-380.md
Labels: cla-signed, release-notes, docs

#11885 Fix incorrect $bucket for mismatch bucket queries
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveAlluxioMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveNodePartitioningProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveSplit.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplit.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/AbstractFileFormat.java
Labels: cla-signed, tests:hive

#12204 Ensure first table matched rule in access control
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/resources/file-based-system-access-table-mixed-groups.json
  lib/trino-plugin-toolkit/src/test/resources/table-mixed-groups.json
Labels: bug, cla-signed

#12287 Change schema prefix in Iceberg Glue smoke test
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
Labels: cla-signed, no-release-notes

#12286 Fix wrong field path in Elasticsearch ROW type
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
Labels: cla-signed

#12274 Fix flaky failure recovery assertions
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed

#12262 Fix an issue in InlineProjections that may cause query failure when multiple column masks exist on a table
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java
  core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
Labels: cla-signed

#12290 Sort Trino workers in Web UI
  core/trino-main/src/main/resources/webapp/dist/workers.js
  core/trino-main/src/main/resources/webapp/src/components/WorkerList.jsx
Labels: cla-signed, ui

#12285 Use dfs command only in ABFS test
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAbfsSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHdfsSyncPartitionMetadata.java
Labels: cla-signed, tests:hive, no-release-notes

#12263 Add property for partition count for fault tolerant execution
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/cost/TaskCountEstimator.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RewriteSpatialPartitioningAggregation.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFaultTolerantExecutionConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
  testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
Labels: cla-signed, docs, tests:hive

#12231 Add properties, requirements, and best practices from FTE blog
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#12260 Fix SPI compatibility test to not use latest release
  core/trino-server-rpm/pom.xml
  core/trino-spi/pom.xml
  pom.xml
Labels: cla-signed

#12293 Fix documentation of approx_percentile functions
  docs/src/main/sphinx/functions/aggregate.rst
Labels: cla-signed, docs

#12216 Minor improvement to Redis
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisJedisManager.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/RedisQueryRunner.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisConnectorTest.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisDistributedHash.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisLatestConnectorTest.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestingRedisPlugin.java
Labels: cla-signed, maintenance, no-release-notes

#12229 Don't drop destination table when non-transactional insert fails
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcOutputTableHandle.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcOutputTableHandle.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixOutputTableHandle.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixOutputTableHandle.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: bug, cla-signed

#12123 Support loading of redis table description files by schedule
  docs/src/main/sphinx/connector/redis.rst
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorConfig.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableDescriptionSupplier.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisConnectorConfig.java
Labels: cla-signed, docs

#12269 Add base connector test to verify concurrent INSERT
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#11671 Add autosuggestion to cli
  client/trino-cli/pom.xml
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/InputReader.java
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs

#12326 Add UPDATE to list of supported Iceberg commands
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#12307 Minor cleanup in TestingOpenLdapServer
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestingOpenLdapServer.java
Labels: cla-signed

#12310 Fix LDAP Authenticator validation issues with ActiveDirectory service
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/ldap/JdkLdapClient.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/ldap/LdapClient.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticatorClient.java
Labels: cla-signed

#12199 Fix query planning failure on multiple subqueries due to IllegalStateException at ScopeAware.scopeAwareComparison()
  core/trino-main/src/main/java/io/trino/sql/planner/ScopeAware.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
Labels: cla-signed

#12313 Enable Error Prone check: DefaultCharset
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopProcessFactory.java
  plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestingAtopFactory.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/DruidQueryRunner.java
  plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileRecordCursor.java
  plugin/trino-ml/src/main/java/io/trino/plugin/ml/SvmClassifier.java
  plugin/trino-ml/src/main/java/io/trino/plugin/ml/SvmRegressor.java
  plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/statistics/TableStatisticsDataRepository.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/statistics/TableStatisticsDataRepository.java
  pom.xml
  service/trino-verifier/src/main/java/io/trino/verifier/JsonEventClient.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/SimpleLineBenchmarkResultWriter.java
  testing/trino-plugin-reader/src/main/java/io/trino/server/PluginReader.java
Labels: cla-signed, no-release-notes

#12251 Add -XX:+UnlockDiagnosticVMOptions and -XX:+UseAESCTRIntrinsics
  core/docker/default/etc/jvm.config
  core/trino-server-rpm/src/main/resources/dist/config/jvm.config
  docs/src/main/sphinx/installation/deployment.rst
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config
Labels: cla-signed, release-notes, docs, performance

#12339 Make Compiler failed message more user-friendly
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
Labels: cla-signed

#10717 Simplify nesting during elasticsearch query building
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchQueryBuilder.java
Labels: cla-signed

#11906 Fix Dev Guide references to new locations
  docs/src/main/sphinx/develop/client-protocol.rst
  docs/src/main/sphinx/develop/functions.rst
  docs/src/main/sphinx/develop/spi-overview.rst
Labels: cla-signed, docs

#12222 Use Cassandra driver v4 in product tests
  plugin/trino-cassandra/pom.xml
  pom.xml
  testing/trino-product-tests/pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/DataTypesTableDefinition.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/MultiColumnKeyTableDefinition.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestSelect.java
  testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
Labels: cla-signed, tests:hive

#12363 Remove bogus `@VisibleForTesting` annotation
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/InternalDeltaLakeConnectorFactory.java
Labels: cla-signed

#12350 Add builders for table function arguments
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/ArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/DescriptorArgument.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/DescriptorArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/ScalarArgument.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/ScalarArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/TableArgument.java
  core/trino-spi/src/main/java/io/trino/spi/ptf/TableArgumentSpecification.java
Labels: cla-signed

#12378 Fix some spelling problems
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergColumnHandle.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotColumnHandle.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTableBuilder.java
Labels: cla-signed, tests:hive, no-release-notes

#12389 Add cause exception message to JDBC query failure message
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoStatement.java
  service/trino-verifier/src/main/java/io/trino/verifier/Validator.java
Labels: cla-signed, jdbc

#12380 Add support for snapshot tables in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryInstanceCleaner.java
Labels: cla-signed

#12355 Clarify auto-suggestion documentation
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs, no-release-notes

#12273 Minor cleanup of WindowNode constructor
  core/trino-main/src/main/java/io/trino/sql/planner/plan/WindowNode.java
Labels: cla-signed

#12376 Use builderWithExpectedSize when size is known
  core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-main/src/main/java/io/trino/execution/ExecutionFailureInfo.java
  core/trino-main/src/main/java/io/trino/execution/buffer/ArbitraryOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/PartitionedOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/executor/MultilevelSplitQueue.java
  core/trino-main/src/main/java/io/trino/execution/executor/TaskHandle.java
  core/trino-main/src/test/java/io/trino/RowPageBuilder.java
  core/trino-main/src/test/java/io/trino/block/AbstractTestBlock.java
  core/trino-main/src/test/java/io/trino/execution/executor/SimulationTask.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordSet.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordSetProvider.java
Labels: cla-signed

#12418 Remove unused enum from SqlServerClient
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#12338 Document table function support
  docs/src/main/sphinx/develop.rst
  docs/src/main/sphinx/develop/table-functions.rst
  docs/src/main/sphinx/functions.rst
  docs/src/main/sphinx/functions/table.rst
  docs/src/main/sphinx/sql/select.rst
Labels: cla-signed, docs

#12277 Add Trino 381 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-381.md
Labels: cla-signed, release-notes, docs

#12395 Add AccessDeniedException overloadings with extraInfo
  core/trino-spi/src/main/java/io/trino/spi/security/AccessDeniedException.java
Labels: cla-signed

#12417 Improve PostgreSQL INSERT performance
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClientModule.java
Labels: cla-signed

#12411 Improve MySQL INSERT performance
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
Labels: cla-signed

#12384 Add missing Iceberg release note to 379
  docs/src/main/sphinx/release/release-379.md
Labels: cla-signed, release-notes, docs

#12420 Rearrange try/catch blocks in HiveMetastoreTableOperations
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java
Labels: cla-signed, no-release-notes

#12374 Update `Presto` to `Trino` in PostgreSql
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/TypeUtils.java
Labels: cla-signed

#12401 Fix failure when ACID table column name collides with ACID internal names
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#12451 Add support for table spec version 2 in Iceberg doc
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#12445 Update `Presto` to `Trino` in trino-verifier
  service/trino-verifier/pom.xml
  service/trino-verifier/src/main/java/io/trino/verifier/TrinoVerifier.java
  service/trino-verifier/src/main/java/io/trino/verifier/TrinoVerifierModule.java
  service/trino-verifier/src/main/java/io/trino/verifier/Validator.java
  service/trino-verifier/src/main/java/io/trino/verifier/VerifyCommand.java
Labels: cla-signed

#12257 Use gather over partitioned exchange for small join build side
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UseNonPartitionedJoinLookupSource.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestGetSourceTablesRowCount.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestUseNonPartitionedJoinLookupSource.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java
  docs/src/main/sphinx/admin/properties-optimizer.rst
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGetTableStatisticsOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
  testing/trino-tests/src/test/java/io/trino/tests/TestGetTableStatisticsOperations.java
Labels: cla-signed, docs

#12396 Enforce required argument order in aggregation annotation parser
  core/trino-main/src/main/java/io/trino/operator/aggregation/AggregationFromAnnotationsParser.java
  core/trino-main/src/test/java/io/trino/operator/TestAnnotationEngineForAggregates.java
Labels: cla-signed, no-release-notes

#12471 Change table name in Hive testMismatchedBucketWithBucketPredicate
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive

#12446 Update `Presto` to `Trino` in base-jdbc
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ColumnMapping.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcClientStats.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcQueryBuilder.java
Labels: cla-signed

#12460 Make SqlParser a test constant in AbstractTestQueryFramework
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed, no-release-notes

#12478 Free task descriptor memory for finished tasks
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantStageScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestTaskDescriptorStorage.java
Labels: cla-signed

#12382 Document Delta Lake support for GCS
  docs/src/main/sphinx/connector/delta-lake.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#12459 Remove @Flaky annotation and disable testNotAnalzyed for MySql 8
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseTestMySqlTableStatisticsTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTableStatisticsMySql8Histograms.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTableStatisticsMySql8IndexStatistics.java
Labels: cla-signed, test, no-release-notes

#12356 Enlarge font size on tables in docs
  docs/src/main/sphinx/static/trino.css
Labels: cla-signed, docs

#12438 Clarify use of expressions in UPDATE docs
  docs/src/main/sphinx/sql/update.rst
Labels: cla-signed, docs

#12387 Clean up documentation on secrets
  docs/src/main/sphinx/security/secrets.rst
Labels: cla-signed, docs

#11564 Improve SQL Server type mapping documentation
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs, no-release-notes

#12488 Fix invalid argument name reporting in PTF analysis
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed, no-release-notes

#12487 Simplify run-trino script
  core/docker/bin/run-trino
Labels: cla-signed, no-release-notes

#12421 Remove noisy exchange manager logging
  core/trino-main/src/main/java/io/trino/exchange/ExchangeManagerRegistry.java
Labels: cla-signed

#12505 Optimize log message in Redis and Kafka
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/file/FileTableDescriptionSupplier.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableDescriptionSupplier.java
Labels: cla-signed, no-release-notes

#12428 Support reading wildcard tables in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryErrorCode.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryUtil.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
Labels: cla-signed

#12259 Support updating Iceberg table partitioning
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPartitionEvolution.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, docs

#12476 Add argument-less builder methods for boolean values
  core/trino-spi/src/main/java/io/trino/spi/ptf/TableArgumentSpecification.java
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
Labels: cla-signed

#12515 Upgrade Coral dependency to v2.0.77
  pom.xml
Labels: cla-signed

#12483 Add concurrent adding columns (ALTER TABLE ADD COLUMN) test to BaseConnectorTest
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#12517 Remove redundant condition in test
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#12400 Extend WriteFunction with JDBC type information
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BooleanWriteFunction.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DoubleWriteFunction.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/LongWriteFunction.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/SliceWriteFunction.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/WriteFunction.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleClient.java
Labels: cla-signed

#12371 Support adding columns in Delta Lake (ALTER TABLE ADD COLUMN)
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Labels: cla-signed

#12343 Add ability to disable partitions caching in hive metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
Labels: cla-signed, tests:hive

#12472 Add docs on configuring Azure/GCS for exchange spooling
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs, tests:hive

#12539 Switch comments in example to match the correct block
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs, no-release-notes

#12549 Edit fault tolerant execution docs for style and readability
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#12527 Batch the metastore call used to retrieve the partitions by names
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
Labels: cla-signed, tests:hive

#12197 Improve Iceberg deletes when an entire file can be removed
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CommitTaskData.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/IcebergPositionDeletePageSink.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, performance

#12553 Fix link to Google documentation
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#12534 Add docs for hive partition caching property
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#12327 Document client timeout in query management properties
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#12331 Clarify when the shared secret is needed
  docs/src/main/sphinx/security/internal-communication.rst
Labels: cla-signed, docs

#12440 Add Trino 382 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-382.md
Labels: cla-signed, release-notes, docs

#12537 Ignore table already exist error in case of same query id for Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Labels: cla-signed

#12532 Record connectors used in delta lake test environments
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeDeltaLakeDatabricks.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeMinioDataLake.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeKerberizedHdfs.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLake.java
Labels: cla-signed, no-release-notes

#12540 Remove overrides of BaseFailureRecoveryTest#enableDynamicFiltering
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveFailureRecoveryTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed, tests:hive

#12563 Fix checkArgument message in `OrcWriter`
  lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java
Labels: cla-signed, tests:hive

#12536 Add IAM Role support for exchange spooling on S3
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
  plugin/trino-exchange-filesystem/pom.xml
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/ExchangeS3Config.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestExchangeS3Config.java
Labels: cla-signed, docs

#12351 Allow executing optimize procedure for Iceberg v2 table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergOptimizeHandle.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#10655 Document JSON_EXISTS, JSON_VALUE and JSON_QUERY functions
  docs/src/main/sphinx/functions/json.rst
  docs/src/main/sphinx/functions/list-by-topic.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#12574 Deny creating tables with column comment if unsupported
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed

#12490 Merge the ABFS product tests job with others
  .github/workflows/ci.yml
Labels: cla-signed

#12506 Remove HiveConfig from Iceberg module
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TranslateHiveViews.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalogFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
Labels: cla-signed, tests:hive, no-release-notes

#12582 Do not extract distinct operator when de-correlating global aggregation
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithoutProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithoutProjection.java
Labels: cla-signed

#12590 Upgrade Minio image to RELEASE.2022-05-26T05-48-41Z
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Minio.java
Labels: cla-signed, no-release-notes

#12597 Fix bounds check in MultiChannelGroupByHash and BigintGroupByHash
  core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
Labels: cla-signed, RELEASE-BLOCKER

#12594 Rely on noMoreOperators for dynamic filters collection
  core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/DynamicFilterSourceConsumer.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalDynamicFilterConsumer.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkDynamicFilterSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestDynamicFilterSourceOperator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFilterConsumer.java
Labels: cla-signed

#12610 Update docker-images to v59
  pom.xml
Labels: cla-signed

#12609 Change scope of methods in BaseDeltaLakeConnectorSmokeTest
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOptimizedWriterConnectorSmokeTest.java
Labels: cla-signed, test, maintenance, no-release-notes

#12613 Improve test coverage of BigintGroupByHash and MultiChannelGroupByHash
  core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
Labels: cla-signed

#12511 Batch delete requests for exchange spooling on S3 and Azure
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeFutures.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/AzureBlobFileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
Labels: cla-signed, tests:hive
