Repository trinodb/trino, pull requests merged in 2022-06, with the labels that each got.

#12641 Fix inaccurate references to prepared statement header
  docs/src/main/sphinx/develop/client-protocol.rst
Labels: cla-signed, docs

#12632 Fix typo in `StatementAnalyzer`
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#12565 Add Trino 383 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-383.md
Labels: cla-signed, release-notes, docs

#12651 Fix logical merge conflict in SPI compatibility test
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
Labels: cla-signed

#12670 Fix PositionsAppender#build for null Block
  core/trino-main/src/main/java/io/trino/operator/output/BytePositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/Int128PositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/Int96PositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/IntPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/LongPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/ShortPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/SlicePositionsAppender.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
Labels: cla-signed

#12650 Switch from deprecated md5 to murmur3_128 hashing in RowToRowCast
  core/trino-main/src/main/java/io/trino/operator/scalar/RowToRowCast.java
Labels: cla-signed

#12681 Fix potential failure or incorrect result of JSON_QUERY function
  core/trino-main/src/main/java/io/trino/operator/scalar/json/JsonQueryFunction.java
  core/trino-main/src/test/java/io/trino/sql/query/TestJsonQueryFunction.java
Labels: cla-signed

#12683 Run Delta Lake smoke tests against GCS
  .github/workflows/ci.yml
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/resources/io/trino/plugin/deltalake/hdp3.1-core-site.xml.gcs-template
Labels: cla-signed

#12414 Remove unused parameter in `MetadataManager`
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestingPlannerContext.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGetTableStatisticsOperations.java
  testing/trino-tests/src/test/java/io/trino/tests/TestGetTableStatisticsOperations.java
Labels: cla-signed

#12579 Attach weights to IcebergSplits
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
Labels: cla-signed

#12690 Refactor BACKWARD_INCOMPATIBLE_CHANGES definition
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
Labels: cla-signed, no-release-notes

#12642 Block update and delete operations from append only Delta Lake tables
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksDelete.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksUpdates.java
Labels: cla-signed, tests:hive

#12679 Minor refactoring in `IcebergPageSource`
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java
Labels: cla-signed

#12695 Fix error message for concurrent adding column in SQL Server
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Labels: cla-signed, no-release-notes

#12701 Run Delta Lake smoke tests against GCS
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
Labels: cla-signed

#12710 Remove Delta cloud tests from the test-failure-recovery CI job
  .github/workflows/ci.yml
Labels: cla-signed

#12455 Support creating tables with column comment in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
Labels: cla-signed, tests:hive

#12707 Fix Iceberg Glue materialized view test
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViewTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogMaterializedViewTest.java
Labels: cla-signed, no-release-notes

#12716 Adapt test to use DENY statement
  testing/trino-tests/src/test/java/io/trino/execution/TestDenyOnTable.java
Labels: cla-signed

#12482 Disallow creating views when schema doesn't exist in File HMS
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, tests:hive, no-release-notes

#10258 Support Iceberg time travel
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergReadVersionedTable.java
Labels: cla-signed

#12724 Enable Error Prone check: HidingField
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryTestView.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveMetastore.java
  pom.xml
Labels: cla-signed

#12606 Support timestamp type in MariaDB connector
  docs/src/main/sphinx/connector/mariadb.rst
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTypeMapping.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestingMariaDbServer.java
  pom.xml
Labels: cla-signed, docs, tests:hive

#12677 Document JSON value constructors
  docs/src/main/sphinx/functions/json.rst
Labels: cla-signed, docs

#12024 Expose JMX metrics for TrinoFileSystemCache
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TrinoFileSystemCache.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TrinoFileSystemCacheStats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestTrinoFileSystemCacheStats.java
Labels: cla-signed, tests:hive, no-release-notes

#12717 Prevent adding coercion to unknown
  core/trino-main/src/main/java/io/trino/sql/planner/Coercer.java
Labels: cla-signed, no-release-notes

#12721 Ensure single task reads single partition in write stage
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
Labels: cla-signed

#12705 Allow cancelling the query to cancel waiting for Hive lock
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed, tests:hive

#12437 Remove redundant call to 'String.format()'
  client/trino-client/src/main/java/io/trino/client/auth/external/CompositeRedirectHandler.java
Labels: cla-signed

#12567 Unbind hive config from iceberg and delta lake modules
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
Labels: cla-signed, tests:hive, no-release-notes

#12671 Don't truncate min/max for iceberg delete files
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
Labels: cla-signed

#12747 Add multinode product test environment backed by GCS
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeGcs.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/apply-gcs-config.sh
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/core-site-overrides-template.xml
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/delta.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/iceberg.properties
Labels: cla-signed

#12733 Improve hash quality in DeltaLakeBucketFunction
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeBucketFunction.java
Labels: cla-signed, no-release-notes

#12741 Return addresses in PhoenixSplit.getInfo()
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixSplit.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixSplit.java
Labels: cla-signed, no-release-notes

#12492 Disallow creating view if schema doesn't exist in Accumulo
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloClient.java
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
Labels: cla-signed

#12672 Allow implicit escape for _ but not % in JDBC metadata calls
  client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs, jdbc

#12719 Disallow null table version
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#12746 Move fault tolerant tests to separate module
  .github/workflows/ci.yml
  plugin/trino-delta-lake/pom.xml
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTaskFailureRecoveryTest.java
  plugin/trino-iceberg/pom.xml
  pom.xml
  testing/trino-faulttolerant-tests/pom.xml
  testing/trino-faulttolerant-tests/src/main/java/io/trino/tests/Dummy.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/BaseFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/delta/BaseDeltaFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/delta/TestDeltaTaskFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/BaseHiveFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionAggregations.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionJoinQueries.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionOrderByQueries.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionWindowQueries.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveQueryFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveTaskFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/BaseIcebergFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergQueryFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergTaskFailureRecoveryTest.java
Labels: cla-signed, tests:hive

#12646 Improve some default config values of fault-tolerant execution
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#12560 Bump Airbase to 126
  pom.xml
  testing/trino-tests/src/test/java/io/trino/tests/TestVerifyTrinoTestsTestSetup.java
Labels: cla-signed

#12412 Avoid no-op Iceberg table snapshot if DML doesn't change table state
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#12744 Document the Iceberg split weight property
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#12752 Remove redundant `@LegacyConfig` in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
Labels: cla-signed, no-release-notes

#12764 Update kafka smoke tests to use Confluent docker image version 7.1.1
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaLatestConnectorSmokeTest.java
Labels: cla-signed, no-release-notes

#12751 Add docs for delta parameters extracted from HiveConfig
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs, no-release-notes

#12780 Static import MetadataListing.listCatalogNames
  core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/jdbc/CatalogJdbcTable.java
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
Labels: cla-signed

#12720 Reject FOR TIMESTAMP AS OF ... with future temporal value
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#12645 Improve exchange spooling file listing speed
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeConfig.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeManager.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeStats.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/AzureBlobFileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/local/LocalFileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorageStats.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/TestFileSystemExchangeConfig.java
Labels: cla-signed

#12593 Add `iceberg.table-statistics-enabled` property in Iceberg doc
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#11905 Improve storage credential explanation
  docs/src/main/sphinx/connector/hive-azure.rst
Labels: cla-signed, docs

#12777 Set DB_CLOSE_DELAY for Raptor H2
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java
Labels: cla-signed

#12790 Fix Iceberg ignoring filter on $path
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#12402 Add checks for rename table and view
  core/trino-main/src/main/java/io/trino/execution/RenameTableTask.java
  core/trino-main/src/main/java/io/trino/execution/RenameViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameViewTask.java
Labels: cla-signed

#12813 Remove unused argument
  core/trino-spi/src/main/java/io/trino/spi/ptf/TableArgumentSpecification.java
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
Labels: cla-signed

#12621 Disallow reading Delta Lake tables if column mapping is not none
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Labels: cla-signed, tests:hive

#12825 Remove unused `Nonnull` annotation
  core/trino-main/src/main/java/io/trino/server/ProtocolConfig.java
Labels: cla-signed, no-release-notes

#12824 Fix check message in `TrimmedBasicQueryInfo`
  core/trino-main/src/main/java/io/trino/server/ui/TrimmedBasicQueryInfo.java
Labels: cla-signed, no-release-notes

#12816 Bump Iceberg to 0.13.2
  plugin/trino-iceberg/pom.xml
Labels: cla-signed

#12808 Use REQUIRED repetition level for MAP keys in parquet writer
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetSchemaConverter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java
Labels: cla-signed, tests:hive, no-release-notes

#12755 Attach weights to DeltaLakeSplits
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplit.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
Labels: cla-signed, docs

#12608 Upgrade mysql image to 8.0.29
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestingMySqlServer.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorMySqlConnectorTest.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsMysqlFlywayMigration.java
  plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/db/TestingMySqlContainer.java
  service/trino-verifier/src/test/java/io/trino/verifier/TestDatabaseEventClient.java
Labels: cla-signed

#12807 Reorganize Iceberg configuration properties in doc
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs, no-release-notes

#12820 implement target max file size for delta lake
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
Labels: cla-signed, docs

#12772 Remove Phoenix4 connector
  .github/workflows/ci.yml
  core/trino-server/src/main/provisio/trino.xml
  docs/src/main/sphinx/connector/phoenix.rst
  plugin/trino-phoenix/pom.xml
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/MetadataUtil.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClientModule.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixColumnProperties.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixConfig.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixConnector.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixConnectorFactory.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixErrorCode.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixMetadata.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixOutputTableHandle.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixPlugin.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixSessionProperties.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixSplit.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixSplitManager.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixTableProperties.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/SerializedPhoenixInputSplit.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/TypeUtils.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/PhoenixQueryRunner.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/PhoenixSqlExecutor.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/PhoenixTestTable.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConfig.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixPlugin.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixSplit.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestingPhoenixServer.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodePhoenix4.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite6NonGeneric.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/phoenix.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-phoenix4/phoenix.properties
Labels: cla-signed, docs

#12836 Expose Iceberg UUID filtering bug
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#12835 Merge unwrap cast in comparison optimizer rules
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapTimestampToDateCastInComparison.java
Labels: cla-signed

#12837 Move assertion back to the right test
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#12849 Remove outdated if branch in timezone test
  core/trino-main/src/test/java/io/trino/util/TestTimeZoneUtils.java
Labels: cla-signed

#12855 Fix reading timestamptz before epoch from Parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampMicrosColumnReader.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, tests:hive

#12830 Describe per-connector support for fault-tolerant execution
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#12845 Remove unused list prefix method from TrinoS3FileSystem
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#12867 Use unique schema names in tests
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive

#12869 Call tableCreated() after table creation is finished
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/OutputTableHandle.java
  core/trino-main/src/test/java/io/trino/operator/TestTableWriterOperator.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
Labels: cla-signed, ready to merge

#12354 Fix memory connector's renameView shadowing a table
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
Labels: cla-signed, ready to merge

#12814 Support `data_size` when analyzing in Delta Lake
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/DeltaLakeColumnStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
  plugin/trino-delta-lake/src/test/resources/statistics/extended_stats_with_data_size/_delta_log/_trino_meta/extended_stats.json
  plugin/trino-delta-lake/src/test/resources/statistics/extended_stats_without_data_size/_delta_log/_trino_meta/extended_stats.json
Labels: cla-signed, docs

#12859 Update docker-images to v61
  pom.xml
Labels: cla-signed

#12841 Require Java 11.0.15+
  core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
  docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#12801 Avoid using futures to collect DFs on workers
  core/trino-main/src/main/java/io/trino/sql/planner/LocalDynamicFilterConsumer.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFilterConsumer.java
Labels: cla-signed

#12880 Remove redundant not null check in `HttpRemoteTask`
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Labels: cla-signed

#12884 Refining the Redis types in doc
  docs/src/main/sphinx/connector/redis.rst
Labels: cla-signed, docs, no-release-notes

#12829 Ensure Iceberg test waits for dynamic filtering
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, test, no-release-notes

#11688 to_iso8601 with timezone incorrect during dst hour
  core/trino-main/src/main/java/io/trino/operator/scalar/timestamptz/ToIso8601.java
  core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
Labels: cla-signed

#12831 Add tests for AS OF syntax for tables with redirects
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java
Labels: cla-signed, no-release-notes

#12883 Check supported writer version when adding a column in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Labels: cla-signed, tests:hive

#12864 Smoke test timestamp values before epoch
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#12865 More test coverage for Iceberg partitioning transforms
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, test, no-release-notes

#12898 Expose query retry policy via query event listener
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryContext.java
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
Labels: cla-signed

#12757 Enable optimized Parquet writer by default in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatisticsLegacyWriter.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatisticsOptimizedWriter.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLegacyWriterConnectorSmokeTest.java
Labels: cla-signed

#12847 Store CLI history even if query starts with spaces
  client/trino-cli/src/main/java/io/trino/cli/InputReader.java
Labels: cla-signed

#12910 Support parameters in table function arguments
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
  docs/src/main/sphinx/functions/table.rst
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed, docs

#12915 Fix failure when inserting into Kudu table having row uuid column
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduInsertTableHandle.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
Labels: cla-signed

#12913 Add UUID ordering tests
  core/trino-main/src/test/java/io/trino/type/TestUuidType.java
Labels: cla-signed, test, no-release-notes

#12911 Abstain from passing UUID predicates to Iceberg library
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#12899 Implement testCreateTable and testDropTable in Kudu connector test
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#12839 Verify accuracy of doing a CTAS statement from a versioned table
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#12921 Implement INSERT tests in Kudu connector test
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
Labels: cla-signed, test, no-release-notes

#11982 Fix writing bloom filter for string columns in orc
  lib/trino-orc/src/main/java/io/trino/orc/writer/SliceDictionaryColumnWriter.java
  lib/trino-orc/src/test/java/io/trino/orc/TestSliceDictionaryColumnWriter.java
Labels: cla-signed, tests:hive

#12763 Update Airbase to version 127
  core/trino-main/src/test/java/io/trino/operator/aggregation/listagg/TestListaggAggregationFunction.java
  core/trino-main/src/test/java/io/trino/sql/query/TestListagg.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
  pom.xml
Labels: cla-signed, no-release-notes

#12840 Clarify limited write access in BigQuery docs
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#12933 Move TestAccumuloClient initialization out of constructor
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloClient.java
Labels: cla-signed, test, no-release-notes

#12688 Document that most config properties are set on all nodes
  docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed, docs

#12881 Add Trino 387 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-387.md
Labels: cla-signed, release-notes, docs

#12946 Add OpenSearch test for Elasticsearch connector test
  docs/src/main/sphinx/connector/elasticsearch.rst
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchOpenSearchConnectorTest.java
Labels: cla-signed, docs, no-release-notes

#12930 Retry deleting failed attempt output files
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed, tests:hive

#12955 Create schema and table if not exists in Phoenix server
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
Labels: cla-signed, test, no-release-notes

#12900 Add missing docs for iceberg/delta properties
  docs/src/main/sphinx/connector/delta-lake.rst
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#12753 Limit total size of dynamic filters collected
  core/trino-main/src/main/java/io/trino/execution/DynamicFilterConfig.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalDynamicFilterConsumer.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/DynamicFilterId.java
  core/trino-main/src/test/java/io/trino/execution/TestDynamicFilterConfig.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFilterConsumer.java
Labels: cla-signed, tests:hive

#12960 Cleanup TestDeltaLakeDropTableCompatibility
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDropTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/Engine.java
Labels: cla-signed, test, tests:hive, no-release-notes

#12932 Merge TestLegacySyntaxForIcebergSnapshotAccess into BaseIcebergConnectorTest
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestLegacySyntaxForIcebergSnapshotAccess.java
Labels: cla-signed

#12919 Reject SELECT after INSERT or other DML in Hive transaction
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, tests:hive

#12961 Add PluginClassLoader.toString()
  core/trino-main/src/main/java/io/trino/server/PluginClassLoader.java
Labels: cla-signed, no-release-notes

#12959 Fix query executor used in TestIcebergSparkDropTableCompatibility
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/Engine.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkDropTableCompatibility.java
Labels: cla-signed, tests:hive

#12675 Support reading Delta Lake tables having delta.columnMapping.mode=name
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeUpdatablePageSource.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeParquetFileStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatisticsLegacyWriter.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeWriter.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/BenchmarkExtendedStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/TestDeltaLakeFileStatistics.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Labels: cla-signed, tests:hive

#12978 Update airlift version to 217
  pom.xml
Labels: cla-signed

#12857 Write Int96 timestamps in optimized parquet writer for hive
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTimestampUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/Int96TimestampValueWriter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetSchemaConverter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetDecimalScaling.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestamp.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/write/TestDataWritableWriteSupport.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/write/TestDataWritableWriter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/write/TestMapredParquetOutputFormat.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompatibility.java
Labels: cla-signed, tests:hive

#12982 Update table headers to sentence case
  docs/src/main/sphinx/admin/resource-groups.rst
  docs/src/main/sphinx/connector/accumulo.rst
  docs/src/main/sphinx/connector/cassandra.rst
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/elasticsearch.rst
  docs/src/main/sphinx/connector/googlesheets.rst
  docs/src/main/sphinx/connector/hive-s3.rst
  docs/src/main/sphinx/connector/hive-security.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/connector/kafka.rst
  docs/src/main/sphinx/connector/kinesis.rst
  docs/src/main/sphinx/connector/kudu.rst
  docs/src/main/sphinx/connector/localfile.rst
  docs/src/main/sphinx/connector/mariadb.rst
  docs/src/main/sphinx/connector/mongodb.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/pinot.rst
  docs/src/main/sphinx/connector/prometheus.rst
  docs/src/main/sphinx/connector/redis.rst
  docs/src/main/sphinx/connector/thrift.rst
  docs/src/main/sphinx/security/built-in-system-access-control.rst
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#12089 Support reading ORC tinyint type in Iceberg
  lib/trino-orc/src/main/java/io/trino/orc/reader/ByteColumnReader.java
  lib/trino-orc/src/main/java/io/trino/orc/reader/ColumnReaders.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcConnectorTest.java
  plugin/trino-iceberg/src/test/resources/single-smallint-column.orc
  plugin/trino-iceberg/src/test/resources/single-tinyint-column.orc
Labels: cla-signed, tests:hive

#12591 Allow configuring schema for iceberg MV storage tables
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnector.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMaterializedViewAdditionalProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogMaterializedViewTest.java
Labels: cla-signed, docs

#11263 Upgrade Elasticsearch client and drop support for unsupported versions
  docs/src/main/sphinx/connector/elasticsearch.rst
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearch6ConnectorTest.java
Labels: cla-signed, docs

#12988 Fix testStorageSchemaProperty assertion for Glue metastore
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
Labels: cla-signed

#12967 Support use-exact-partitioning
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
  core/trino-main/src/main/java/io/trino/sql/planner/Partitioning.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/ActualProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java
Labels: cla-signed

#12997 Fix failures in TestIcebergGlueCatalogMaterializedViewTest
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
Labels: cla-signed

#12888 Fix flaky TestPositionsAppender.testConsecutiveBuilds
  core/trino-main/src/test/java/io/trino/block/BlockAssertions.java
Labels: cla-signed

#12998 Remove obsolete row filter and column mask methods
  core/trino-main/src/test/java/io/trino/security/TestInjectedConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/classloader/TestClassLoaderSafeWrappers.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestAllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestAllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/security/TestLegacyAccessControl.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/security/TestSqlStandardAccessControl.java
Labels: cla-signed, tests:hive

#13019 Add missing syntax in table functions docs
  docs/src/main/sphinx/functions/table.rst
Labels: cla-signed, docs, no-release-notes

#12704 Always optimize iceberg files when delete are present
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergOptimizeHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/DataFileWithDeleteFiles.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed

#13022 Fix compilation failure
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Labels: cla-signed

#13023 Document comment support in Delta Lake
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#13008 Rename class for Query pass-through in JDBC connectors
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ptf/Query.java
Labels: cla-signed

#12972 Set valid classloader for RollbackToSnapshotProcedure
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Labels: cla-signed, tests:hive

#12996 Upgrade Parquet version to 1.12.3
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java
  pom.xml
Labels: cla-signed, tests:hive

#12879 Fix reading Iceberg $partitions table after updating partition schema
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestStructLikeWrapperWithFieldIdToIndex.java
Labels: cla-signed

#13018 Update Thrift metastore config properties table
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#13003 Document max query in query management properties
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#13004 Add Trino 388 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-388.md
Labels: cla-signed, release-notes, docs

#13016 Enable debug logs for RetryDriver in tests
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed

#12822 Cleanup SlicePositionsAppender
  core/trino-main/src/main/java/io/trino/operator/output/SlicePositionsAppender.java
Labels: cla-signed, performance

#13049 Move pushdown test to `BaseRedisConnectorTest`
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/BaseRedisConnectorTest.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisConnectorTest.java
Labels: cla-signed

#12994 Fix formatting in EXPLAIN docs
  docs/src/main/sphinx/sql/explain.rst
Labels: cla-signed, docs
