Repository trinodb/trino, pull requests merged in 2022-04, with the labels that each got.

#11739 Put TLS before HTTPS
  docs/src/main/sphinx/admin/graceful-shutdown.rst
  docs/src/main/sphinx/installation/jdbc.rst
  docs/src/main/sphinx/security/certificate.rst
  docs/src/main/sphinx/security/cli.rst
  docs/src/main/sphinx/security/kerberos.rst
  docs/src/main/sphinx/security/ldap.rst
  docs/src/main/sphinx/security/overview.rst
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#11750 Implement skeleton for coordinator-only execute
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/TableExecuteHandle.java
  core/trino-main/src/main/java/io/trino/operator/SimpleTableExecuteOperator.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StreamPropertyDerivations.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/PlanNode.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/PlanVisitor.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/SimpleTableExecuteNode.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateDependenciesChecker.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/TableProcedureExecutionMode.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
Labels: cla-signed

#11751 Remove redundant override
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseTestMySqlTableStatisticsTest.java
Labels: cla-signed, test, maintenance, no-release-notes

#11752 Add MySQL automatic Join pushdown test
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlAutomaticJoinPushdown.java
Labels: cla-signed, test, no-release-notes

#10689 Silence QueryRunner startup logs in tests
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/AccumuloQueryRunner.java
  plugin/trino-bigquery/pom.xml
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
  plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/BlackHoleQueryRunner.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraQueryRunner.java
  plugin/trino-clickhouse/pom.xml
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
  plugin/trino-druid/pom.xml
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/DruidQueryRunner.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchExternalQueryRunner.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchQueryRunner.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/GeoQueryRunner.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/MemoryQueryRunner.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
  plugin/trino-mysql/pom.xml
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/MySqlQueryRunner.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/OracleQueryRunner.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/PhoenixQueryRunner.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
  plugin/trino-pinot/pom.xml
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/PostgreSqlQueryRunner.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusQueryRunner.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/RaptorQueryRunner.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/RedisQueryRunner.java
  plugin/trino-singlestore/pom.xml
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/SingleStoreQueryRunner.java
  plugin/trino-sqlserver/pom.xml
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/SqlServerQueryRunner.java
  plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TpcdsQueryRunner.java
  testing/trino-testing/pom.xml
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed

#11728 Simplify Delta Lake query runner
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java
Labels: cla-signed, maintenance, no-release-notes

#11488 Test access control functionality in the context of table redirections
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControlTableRedirection.java
Labels: cla-signed

#11742 Hyphenate spelling of subgroup
  docs/src/main/sphinx/admin/resource-groups.rst
  docs/src/main/sphinx/admin/session-property-managers.rst
  docs/src/main/sphinx/functions/array.rst
  docs/src/main/sphinx/release/release-0.197.rst
Labels: cla-signed, release-notes, docs

#11695 Add test for connector pushdown rules in Iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Labels: cla-signed, no-release-notes

#11617 TrinoHiveCatalog listTables should list all tables
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataListing.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveMetadataListing.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveViewsCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
Labels: cla-signed, tests:hive

#11754 Don't check input in trino-cli in batch mode
  client/trino-cli/src/main/java/io/trino/cli/Query.java
  client/trino-cli/src/main/java/io/trino/cli/StatusPrinter.java
Labels: cla-signed, no-release-notes

#9758 Print error when DateTimeZoneIndex init with failure for debug
  core/trino-main/src/main/java/io/trino/util/DateTimeZoneIndex.java
Labels: cla-signed

#11552 Add logos to Trino connector pages
  docs/src/main/sphinx/connector/accumulo.rst
  docs/src/main/sphinx/connector/bigquery.rst
  docs/src/main/sphinx/connector/cassandra.rst
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/elasticsearch.rst
  docs/src/main/sphinx/connector/googlesheets.rst
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/connector/kafka.rst
  docs/src/main/sphinx/connector/kinesis.rst
  docs/src/main/sphinx/connector/kudu.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mongodb.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/pinot.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/prometheus.rst
  docs/src/main/sphinx/connector/redis.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
  docs/src/main/sphinx/static/img/accumulo.png
  docs/src/main/sphinx/static/img/bigquery.png
  docs/src/main/sphinx/static/img/cassandra.png
  docs/src/main/sphinx/static/img/clickhouse.png
  docs/src/main/sphinx/static/img/druid.png
  docs/src/main/sphinx/static/img/elasticsearch.png
  docs/src/main/sphinx/static/img/google-sheets.png
  docs/src/main/sphinx/static/img/hive.png
  docs/src/main/sphinx/static/img/iceberg.png
  docs/src/main/sphinx/static/img/kafka.png
  docs/src/main/sphinx/static/img/kinesis.png
  docs/src/main/sphinx/static/img/kudu.png
  docs/src/main/sphinx/static/img/mongodb.png
  docs/src/main/sphinx/static/img/mysql.png
  docs/src/main/sphinx/static/img/oracle.png
  docs/src/main/sphinx/static/img/phoenix.png
  docs/src/main/sphinx/static/img/pinot.png
  docs/src/main/sphinx/static/img/postgresql.png
  docs/src/main/sphinx/static/img/prometheus.png
  docs/src/main/sphinx/static/img/redis.png
  docs/src/main/sphinx/static/img/redshift.png
  docs/src/main/sphinx/static/img/singlestore.png
  docs/src/main/sphinx/static/img/sqlserver.png
Labels: cla-signed, docs

#11789 Fix `retry_max_delay` session property definition
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs, no-release-notes

#11606 Support comments when building column definition in ClickHouse
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed

#11766 Move Glue tests to dedicated package in Iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/GlueMetastoreMethod.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalogTest.java
Labels: cla-signed, test, maintenance, no-release-notes

#11710 Fix calculation error in deepInstanceSize of BlockBuilderStatus
  core/trino-spi/src/main/java/io/trino/spi/block/BlockBuilderStatus.java
  core/trino-spi/src/main/java/io/trino/spi/block/PageBuilderStatus.java
Labels: cla-signed

#11775 Count task failures for whole query
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantStageScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFaultTolerantStageScheduler.java
Labels: cla-signed

#11758 Use same operator type for index join builders
  core/trino-main/src/main/java/io/trino/operator/index/IndexBuildDriverFactoryProvider.java
  core/trino-main/src/main/java/io/trino/operator/index/PageBufferOperator.java
  core/trino-main/src/main/java/io/trino/operator/index/PagesIndexBuilderOperator.java
  core/trino-main/src/test/java/io/trino/operator/join/TestHashJoinOperator.java
Labels: cla-signed

#11803 Increase default request concurrency for S3 based exchange
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/ExchangeS3Config.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/s3/TestExchangeS3Config.java
Labels: cla-signed

#11709 Allow configuration duration for completion of dynamic filters in Delta
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDynamicFiltering.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDynamicPartitionPruningTest.java
Labels: cla-signed, docs

#11809 fix typo in docs of kafka connector
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs, no-release-notes

#11804 reasonable time check year update
  core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
Labels: cla-signed, no-release-notes

#11793 More Parquet MetadataReader tests
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestMetadataReader.java
Labels: cla-signed, test, tests:hive, no-release-notes

#11819 Remove unused methods
  core/trino-main/src/main/java/io/trino/memory/MemoryPool.java
Labels: cla-signed

#11799 Increase Maven memory limit in CI jobs to avoid failures
  .github/workflows/ci.yml
Labels: cla-signed

#11818 Refactor TestMemoryManager.testOutOfMemoryKiller
  testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java
Labels: cla-signed, test, no-release-notes

#11786 Do not enforce memory limits for fault tolerant queries
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
  docs/src/main/sphinx/admin/properties-resource-management.rst
Labels: cla-signed, docs

#11187 Add CLI options table
  docs/src/main/sphinx/installation/cli.rst
  docs/src/main/sphinx/security/cli.rst
  docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed, docs

#11705 Edit `log.path` definition and remove default value
  docs/src/main/sphinx/admin/properties-logging.rst
Labels: cla-signed, docs, no-release-notes

#11834 Add link to dynamic filtering docs in Delta Lake connector
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#11836 Checkout with fetch-depth 0 in docs tests
  .github/workflows/docs.yml
Labels: cla-signed, no-release-notes

#11846 Remove unused system property from Kudu tests
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationSchemaNotExisting.java
Labels: cla-signed, no-release-notes

#11797 Update docker-images to v56
  pom.xml
Labels: cla-signed, no-release-notes

#11806 Document table statistics support in MySQL connector
  docs/src/main/sphinx/connector/mysql.rst
Labels: cla-signed, docs

#11805 Document aggregation pushdown in Oracle connector
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#10482 Add new use system truststore flag to JDBC driver and CLI
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
  client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
  client/trino-client/src/main/java/io/trino/client/OkHttpUtil.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
  docs/src/main/sphinx/installation/cli.rst
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs, jdbc

#11837 Fix LowCardinalityDictionaryWork in GroupByHash
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
Labels: cla-signed

#11832 Handle Iceberg data file missing null count stats
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergStatistics.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#11691 Add Trino 376 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-376.md
Labels: cla-signed, release-notes, WIP, docs

#11551 Translate CAST to connector expression
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
  core/trino-spi/src/main/java/io/trino/spi/expression/StandardFunctions.java
Labels: cla-signed

#11855 Avoid selecting unrelated schemas from the information_schema
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java
Labels: cla-signed, test, no-release-notes

#11696 Iceberg: Extended documentation for materialized view behavior
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#11236 Add support for ANSI SQL syntax in trim function
  core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/ResolvedFunctionCallRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
  core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
  core/trino-main/src/test/java/io/trino/sql/query/TestTrim.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionRewriter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Trim.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  docs/src/main/sphinx/language/reserved.rst
Labels: cla-signed, docs

#11649 Use request handler to set Glue catalog id
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProviderFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueCatalogIdRequestHandler.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalogFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
Labels: cla-signed, tests:hive

#11870 Fix SourceDistributionTaskSource
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestStageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestingSplitSource.java
Labels: cla-signed

#11879 Improve grammar and style in Iceberg connector docs
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#11881 Add docs for table statistics support in SQL Server connector
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#11887 Document table statistics support in PostgreSQL connector
  docs/src/main/sphinx/connector/postgresql.rst
Labels: cla-signed, docs

#11888 Document catalog property for orc bloom filters
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#11740 Allow some tasks waiting for node per stage before blocking scheduling
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantStageScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFaultTolerantStageScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestingTaskSourceFactory.java
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#11892 Fix Iceberg entry in release note 376
  docs/src/main/sphinx/release/release-376.md
Labels: release-notes, docs

#11869 Increase default value of hive.metastore.glue.max-connections from 5 to 30.
  docs/src/main/sphinx/connector/hive.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
Labels: docs, tests:hive

#11866 Remove unnecessary final modifier in StatsRecordingPlanOptimizer
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StatsRecordingPlanOptimizer.java
Labels: cla-signed, no-release-notes

#11865 Support partition pseudo-columns in BigQuery
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryFilterQueryBuilder.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryResultPageSource.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTableHandle.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryUtil.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
Labels: cla-signed, docs

#11584 Choose smaller input on build side of partitioned join
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineJoinDistributionType.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PlanNodeSearcher.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q23.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpch/q09.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpch/q13.plan.txt
Labels: cla-signed

#11852 Generate only valid codepoints in TestSliceDictionaryColumnWriter.testDirectConversion
  lib/trino-orc/src/test/java/io/trino/orc/TestSliceDictionaryColumnWriter.java
Labels: cla-signed, tests:hive, no-release-notes

#11916 Document MongoDB connector write access requirement
  docs/src/main/sphinx/connector/mongodb.rst
Labels: cla-signed, docs, no-release-notes

#11908 Move SelectedPortWaitStrategy to trino-testing-containers
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/MinioContainer.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/SelectedPortWaitStrategy.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/TestingHadoop.java
  testing/trino-product-tests-launcher/pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/docker/ContainerUtil.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HydraIdentityProvider.java
  testing/trino-testing-containers/pom.xml
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/wait/strategy/SelectedPortWaitStrategy.java
Labels: cla-signed, no-release-notes

#11930 Remove left over comment from MetadataManager
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
Labels: cla-signed

#11911 Increase timeout in container test
  core/docker/container-test.sh
Labels: cla-signed

#11898 Enable TestDeltaLakeAdlsConnectorSmokeTest
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
Labels: cla-signed, no-release-notes

#11928 Increase startup attempts to 3 in TestingPostgreSqlServer
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed, no-release-notes

#11927 Hide JsonType constructor
  core/trino-main/src/main/java/io/trino/type/JsonType.java
Labels: cla-signed, no-release-notes

#11917 Clarify that the CREATE MV WITH example is for Iceberg
  docs/src/main/sphinx/sql/create-materialized-view.rst
Labels: cla-signed, docs

#11913 Document ANSI-compliant trim function
  docs/src/main/sphinx/functions/string.rst
Labels: cla-signed, docs

#11922 Enable TestDeltaLakeAnalyze
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Labels: cla-signed

#11873 Support reading non-ISO date partition names in Hive
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Labels: cla-signed, tests:hive

#11933 Remove superseeded content about metadata tables
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs, no-release-notes

#11860 Add suggestion to use SHOW FUNCTION on functions toc page
  docs/src/main/sphinx/functions.rst
  docs/src/main/sphinx/sql/show-functions.rst
Labels: cla-signed, docs

#11859 Add Trino 377 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-377.md
Labels: cla-signed, release-notes, docs

#11925 Assert no other partitions in assertExpectedPartitions
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
Labels: cla-signed, test, tests:hive, no-release-notes

#11902 Improve IN list performance in ExpressionInterpreter
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
Labels: cla-signed

#11436 Refactor FutureStateChange implementation
  core/trino-main/src/main/java/io/trino/execution/FutureStateChange.java
Labels: cla-signed

#11969 Fix typo
  core/trino-main/src/main/java/io/trino/operator/ScanFilterAndProjectOperator.java
Labels: cla-signed

#11965 Disable spark caching for singlenode-spark-iceberg image
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg/spark-defaults.conf
Labels: cla-signed, no-release-notes

#11880 Support setting Iceberg table format version
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, docs

#11722 Verify that no non deprecated SPI is removed
  core/trino-spi/pom.xml
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
Labels: cla-signed

#11977 Fix README.md in trino-benchto-benchmarks resources/hive_metadata
  testing/trino-benchto-benchmarks/src/test/resources/hive_metadata/README.md
Labels: cla-signed

#11851 Skip Iceberg row filter when not needed
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Labels: cla-signed

#11972 Fix a typo in InvocationConvention.supportsInstanceFactory method name
  core/trino-main/src/main/java/io/trino/metadata/FunctionManager.java
  core/trino-main/src/main/java/io/trino/operator/annotations/ScalarImplementationDependency.java
  core/trino-spi/src/main/java/io/trino/spi/function/InvocationConvention.java
  core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java
  core/trino-spi/src/test/java/io/trino/spi/function/TestScalarFunctionAdapter.java
Labels: cla-signed, no-release-notes

#11877 Deprecate passing constraints to getTableStatistics
  core/trino-main/src/main/java/io/trino/cost/TableScanStatsRule.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsMetadata.java
  plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcdsMetadataStatistics.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java
  plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/TestTpchMetadata.java
Labels: cla-signed, tests:hive

#7630 Support Mixed Case Pinot Tables
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotErrorCode.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotModule.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableHandle.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTableBuilder.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/MockPinotClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotMetadata.java
  plugin/trino-pinot/src/test/resources/dup_table_lower_case_realtimeSpec.json
  plugin/trino-pinot/src/test/resources/dup_table_lower_case_schema.json
  plugin/trino-pinot/src/test/resources/dup_table_mixed_case_realtimeSpec.json
  plugin/trino-pinot/src/test/resources/dup_table_mixed_case_schema.json
  plugin/trino-pinot/src/test/resources/mixed_case_table_name_realtimeSpec.json
  plugin/trino-pinot/src/test/resources/mixed_case_table_name_schema.json
Labels: cla-signed

#11967 Clean up join pushdown docs for JDBC connectors
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/jdbc-case-insensitive-matching.fragment
  docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
  docs/src/main/sphinx/connector/join-pushdown-enabled-false.fragment
  docs/src/main/sphinx/connector/join-pushdown-enabled-true.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/no-inequality-pushdown-text-type.fragment
  docs/src/main/sphinx/connector/no-pushdown-text-type.fragment
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#11983 Properly export spiller stats
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
Labels: cla-signed

#11956 Speed up coercion to a single type for IN predicates
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
Labels: cla-signed

#11979 Pass explicit node type to LiteralInterpreter
  core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/planner/LiteralInterpreter.java
Labels: cla-signed, no-release-notes

#11963 Default exchange s3MaxErrorRetries to 10
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/ExchangeS3Config.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/s3/TestExchangeS3Config.java
Labels: cla-signed

#11944 Require internal shared secret is set when authentication is enabled
  core/trino-main/src/main/java/io/trino/server/InternalAuthenticationManager.java
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-http-proxy/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-https-proxy/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2/config.properties
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed

#11978 Fix session schema in testRenameTableAcrossSchema
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#11661 Add hidden $path column in Iceberg
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergColumnHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataColumn.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: enhancement, cla-signed, docs, tests:hive

#11991 Never include an empty include section in test matrix
  .github/bin/build-matrix-from-impacted.py
Labels: cla-signed, no-release-notes

#11988 Rename big_query group to large_query in product tests
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite1.java
  testing/trino-product-tests/README.md
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
  testing/trino-product-tests/src/main/resources/sql-tests/testcases/hive_tpch/q09.sql
  testing/trino-product-tests/src/main/resources/sql-tests/testcases/hive_tpch/q19.sql
  testing/trino-product-tests/src/main/resources/sql-tests/testcases/hive_tpch/q21.sql
Labels: cla-signed, tests:hive

#11985 Allow users to configure retry mode for S3
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/ExchangeS3Config.java
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/S3FileSystemExchangeStorage.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/s3/TestExchangeS3Config.java
Labels: cla-signed

#12000 Remove unused query queue test files
  core/trino-main/src/test/resources/queue_config.json
  core/trino-main/src/test/resources/queue_config_bad_cycle.json
  core/trino-main/src/test/resources/queue_config_bad_out_degree.json
  core/trino-main/src/test/resources/queue_config_bad_selfcycle.json
Labels: cla-signed, no-release-notes

#12003 Document alternative to using @Flaky annotation
  testing/trino-testing-services/src/main/java/io/trino/testng/services/Flaky.java
Labels: cla-signed, maintenance, no-release-notes

#11997 Prevent internal communications from starting queries
  core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
Labels: cla-signed

#12038 Fix indentation in SqlBase.g4
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
Labels: cla-signed, no-release-notes

#12027 Remove unused constructor parameter from CreateMaterializedViewTask
  core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
Labels: cla-signed, maintenance, no-release-notes

#12035 Move testDropSchemaExternalFiles to base class in Delta Lake
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
Labels: cla-signed, test, no-release-notes

#12022 Correct release notes entry in 377
  docs/src/main/sphinx/release/release-377.md
Labels: cla-signed, release-notes, docs

#12006 Simplify version logic in plugin/SPI compatibility check
  lib/trino-plugin-toolkit/pom.xml
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/SpiVersionHolder.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/Versions.java
  lib/trino-plugin-toolkit/src/main/resources/io/trino/plugin/base/trino-spi-compile-time-version.txt
Labels: cla-signed, maintenance, no-release-notes

#12042 Add links to github issues to TODOs in code
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/file/DeltaLakeFileMetastoreModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/glue/DeltaLakeGlueMetastoreTableFilterProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/thrift/DeltaLakeThriftMetastoreModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointBuilder.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3TransactionLogSynchronizer.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystem.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/wait/strategy/SelectedPortWaitStrategy.java
Labels: cla-signed

#12025 Update PostgreSQL JDBC driver
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  pom.xml
Labels: cla-signed, maintenance, no-release-notes

#12051 Add a comment to an interface method
  core/trino-main/src/main/java/io/trino/operator/GroupByHash.java
Labels: cla-signed

#11984 Improve Pages Index
  core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
Labels: cla-signed

#11946 Ignore views on information_schema.columns queries
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
Labels: cla-signed

#12048 Fix race condition in BinPackingNodeAllocator
  core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
Labels: cla-signed

#12060 Remove duplicate isIcebergTable method
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed

#11957 Minor refactoring in Redis connector
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisDataType.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisRecordCursor.java
Labels: cla-signed, no-release-notes

#11439 Add to_base32 and from_base32 varbinary functions
  core/trino-main/src/main/java/io/trino/operator/scalar/VarbinaryFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestVarbinaryFunctions.java
  docs/src/main/sphinx/functions/binary.rst
  docs/src/main/sphinx/functions/list-by-topic.rst
  docs/src/main/sphinx/functions/list.rst
Labels: enhancement, cla-signed, docs

#11899 Delay checking for user input in CLI client
  client/trino-cli/src/main/java/io/trino/cli/StatusPrinter.java
Labels: cla-signed

#11894 Allow to disable progress in CLI interactive mode
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
Labels: cla-signed

#12002 Add impersonation to related metastore calls
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
Labels: cla-signed, tests:hive

#11998 Support reading Iceberg S3 paths with double slashes
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed, tests:hive

#12056 Fix Delta Lake queries with predicates not expressible by tuple domain
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Labels: cla-signed

#12023 Remove obsolete TODO in getIcebergLiteralValue
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java
Labels: cla-signed, no-release-notes

#12054 Fix running TestTableScanNodePartitioning test on single CPU nodes
  core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanNodePartitioning.java
Labels: cla-signed

#12043 Produce RunLengthEncodedBlock in VariableWidthBlockBuilder when all values are null
  core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java
  core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockBuilder.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestVariableWidthBlockBuilder.java
Labels: cla-signed

#11976 Short circuit page source creation in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
Labels: cla-signed

#12071 Remove duplicate exception class
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
Labels: cla-signed, maintenance, no-release-notes

#12039 Override all public methods in AccessTrackingFileSystem
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystem.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestAccessTrackingFileSystem.java
Labels: cla-signed, no-release-notes

#11980 Show Iceberg table version in SHOW CREATE TABLE
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
Labels: cla-signed, docs, tests:hive

#12077 Fix typos
  core/trino-main/src/main/java/io/trino/operator/scalar/JoniRegexpFunctions.java
Labels: cla-signed

#12047 Add rule to push filter through count() aggregation
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughCountAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushFilterThroughCountAggregation.java
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/partitioned/q16.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/partitioned/q41.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/partitioned/q94.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/unpartitioned/q16.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/unpartitioned/q41.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/unpartitioned/q94.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpch/partitioned/q21.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpch/unpartitioned/q21.plan.txt
Labels: cla-signed

#11882 Add Windows instructions for running Trino CLI
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, WIP, docs

#12062 Ignore final keyword in SPI backward compability test
  core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java
Labels: cla-signed

#12083 Reset delay counter on task success only if past previous delay period
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantStageScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFaultTolerantStageScheduler.java
Labels: cla-signed

#12090 Eliminate useless build warning
  docs/pom.xml
Labels: cla-signed, docs, no-release-notes

#12066 Fix code comment in Druid and base JDBC client
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Labels: cla-signed, no-release-notes

#12078 Fix incorrect predicate precedence involving OR and split predicates
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#12044 Produce RunLengthEncodedBlock in RowBlockBuilder when all values are null
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractRowBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/RowBlockBuilder.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestRowBlockBuilder.java
Labels: cla-signed

#11981 Support LIMIT pushdown in Oracle connector
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
Labels: cla-signed

#11662 Apply snapshot isolation to all SQL Server connection when it is enabled
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClientModule.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerConnectionFactory.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerClient.java
Labels: cla-signed

#12103 Make the RewriteComparision constructor more explicit
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/RewriteComparison.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed, no-release-notes

#11741 Add user mapping configuration instruction
  docs/src/main/sphinx/security/user-mapping.rst
Labels: cla-signed, docs

#12091 Update org.yaml:snakeyaml dependency to 1.28
  plugin/trino-cassandra/pom.xml
  pom.xml
  testing/trino-product-tests-launcher/pom.xml
Labels: cla-signed

#11935 Deduplicate join output under union with aggregation
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/OptimizeDuplicateInsensitiveJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestOptimizeDuplicateInsensitiveJoins.java
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/partitioned/q75.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/unpartitioned/q75.plan.txt
Labels: cla-signed

#12085 Fix translation of regular expressions to connector expressions
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDistinctLimitIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDistinctLimitIntoTableScan.java
Labels: cla-signed, no-release-notes

#12052 DeltaLakeSplitManager small code cleanup
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
Labels: cla-signed, no-release-notes

#12114 Fix wrong entry for Delta Lake in release note 378
  docs/src/main/sphinx/release/release-378.md
Labels: cla-signed, release-notes, docs

#12116 Remove wrong note about Java 17
  docs/src/main/sphinx/security/internal-communication.rst
Labels: cla-signed, docs

#12081 Move testCharTrailingSpace to common test class
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
Labels: cla-signed, test, no-release-notes

#10046 Add MariaDB connector
  .github/workflows/ci.yml
  core/trino-server/src/main/provisio/trino.xml
  docs/src/main/sphinx/connector.rst
  docs/src/main/sphinx/connector/mariadb.rst
  plugin/trino-mariadb/pom.xml
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/ImplementAvgBigint.java
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClientModule.java
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbPlugin.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/MariaDbQueryRunner.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbCaseInsensitiveMapping.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbClient.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbLatestConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbPlugin.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTypeMapping.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestingMariaDbServer.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeMariadb.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/mariadb.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-mariadb/mariadb.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-mariadb/tempto-configuration.yaml
  testing/trino-product-tests/pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/mariadb/TestMariaDb.java
  testing/trino-server-dev/etc/catalog/mariadb.properties
  testing/trino-server-dev/etc/config.properties
Labels: enhancement, cla-signed, docs, tests:hive

#12131 Move Redis config comment to description
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorConfig.java
Labels: cla-signed, no-release-notes

#11475 Upgrade Pinot Connector to use 0.10.0 libraries
  docs/src/main/sphinx/connector/pinot.rst
  plugin/trino-pinot/pom.xml
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotTypeResolver.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotWithoutAuthenticationIntegrationSmokeTestLatestVersion.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
Labels: cla-signed, docs

#12075 Document CLI batch mode
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs

#12140 Fix wrong requireNonNull check in `ConnectorManager`
  core/trino-main/src/main/java/io/trino/connector/ConnectorManager.java
Labels: cla-signed

#12120 Remove DeltaLakeGlueMetastoreTableFilterProvider.isDeltaLakeTable
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/glue/DeltaLakeGlueMetastoreTableFilterProvider.java
Labels: cla-signed, no-release-notes

#12134 Move testDropTable to BaseConnectorTest
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes
