Repository trinodb/trino, pull requests merged in 2022-11, with the labels that each got.

#14813 Fix incorrect result due to different column order in equality delete filter in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/EqualityDeleteFilter.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed

#14139 Use arrays to initialize the member variables of MultilevelSplitQueue
  core/trino-main/src/main/java/io/trino/execution/executor/MultilevelSplitQueue.java
Labels: cla-signed, no-release-notes

#14851 Update picocli to 4.7.0
  pom.xml
Labels: cla-signed

#14855 Expose test containers' hostnames on custom networks
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/BaseTestContainer.java
Labels: cla-signed

#14627 Port OrcFileWriterFactory.createOrcDataSink to TrinoFileSystem
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSinkProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/SortingFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/HdfsOrcDataSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeleteDeltaPageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeleteDeltaPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeletedRows.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OriginalFilesUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveWriterFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOriginalFilesUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcDeleteDeltaPageSource.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcDeletedRows.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java
Labels: cla-signed, tests:hive

#14866 Fix typo
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
Labels: cla-signed

#14549 Split the Delta Lake product test suite per Databricks runtime
  .github/workflows/ci.yml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/SuiteDeltaLakeDatabricks.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks104.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks73.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks91.java
Labels: cla-signed

#14729 Add dataset cache to BigQuery connector
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/pom.xml
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClientFactory.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryMetadataCaching.java
Labels: cla-signed, docs

#14871 Preserve order for root for SINGLE distribution only
  core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#14804 Format Iceberg table operation commit on own line
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, no-release-notes

#14883 Fix Hive test table name collision
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#10728 Negate method invocation
  core/trino-main/src/main/java/io/trino/operator/SimplePagesHashStrategy.java
Labels: cla-signed

#14820 Add debugging to SourcePartitionedScheduler
  core/trino-main/src/main/java/io/trino/execution/scheduler/SourcePartitionedScheduler.java
Labels: cla-signed

#14890 Register state change listener only once
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
Labels: cla-signed

#14902 Add debug logging to PhasedExecutionSchedule
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
Labels: cla-signed

#14774 Document function rules for File-based Access Control
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#14771 Small test cleanup around schemas
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#14881 Set CI cache download timeout to enable retries
  .github/workflows/ci.yml
Labels: cla-signed

#14110 Add support for reading `DateTime(timezone)` from ClickHouse
  docs/src/main/sphinx/connector/clickhouse.rst
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
Labels: cla-signed, docs

#14896 Fix incorrect min/max with limit in window functions
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/MaxNAggregationFunction.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/MinMaxNState.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/MinMaxNStateFactory.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/MinNAggregationFunction.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/MinNStateFactory.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/minmaxn/TestTypedHeap.java
  core/trino-main/src/test/java/io/trino/sql/query/TestMinMaxNWindow.java
Labels: cla-signed

#14872 Allow empty values within partitioned fragment
  core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestIssue14317.java
Labels: cla-signed, tests:hive

#14769 Fix error message when creating table in non-existing schema
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestCreateTable.java
Labels: cla-signed, tests:hive, no-release-notes

#14905 Delta Lake: Remove useless method in `BaseDeltaLakeConnectorSmokeTest`
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Labels: no-release-notes

#14918 Fix typo in io/trino/server/protocol/Query.java
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
Labels: cla-signed

#14921 Extract QueryConfig from BaseJdbcConfig
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/QueryConfig.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestBaseJdbcConfig.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestQueryConfig.java
Labels: cla-signed

#14285 Don't show unsupported AUTHORIZATION ROLE in Hive schema
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedFileMetastoreWithTableRedirections.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/AccessControlMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControlMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControlMetadataMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileBasedSecurity.java
  plugin/trino-hive/src/test/resources/io/trino/plugin/hive/security.json
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveMetastore.java
Labels: cla-signed, tests:hive

#14926 Fix incorrect results when FTE and bulk INSERT is enabled in SQL Server
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Labels: cla-signed

#14932 Simplify assertion in testJoinPushdownDisabled
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed, no-release-notes

#14930 Improve error message
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordCursor.java
Labels: cla-signed, no-release-notes

#14940 Fix broken `TestSharedGlueMetastore.getExpectedHiveCreateSchema`
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
Labels: cla-signed, no-release-notes

#14946 Fix broken `TestDeltaLakeSharedGlueMetastoreWithTableRedirections.testShowSchemas`
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java
Labels: cla-signed, no-release-notes

#14867 Add test for insert which creates multiple small files
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive

#14708 Avoid repeatedly creating pruned QueryInfo when it's already pruned
  core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQuery.java
  core/trino-main/src/main/java/io/trino/execution/QueryInfo.java
  core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
  core/trino-main/src/test/java/io/trino/execution/MockManagedQueryExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
  core/trino-main/src/test/java/io/trino/server/TestBasicQueryInfo.java
  core/trino-main/src/test/java/io/trino/server/TestQueryStateInfo.java
Labels: cla-signed

#14887 Skip recording of buffer utilization until data is put into buffer
  core/trino-main/src/main/java/io/trino/execution/buffer/OutputBufferMemoryManager.java
Labels: cla-signed

#14965 Use assertThatThrownBy in TestFileBasedSystemAccessControl
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
Labels: cla-signed, no-release-notes

#14912 Implement CharType.getRange
  core/trino-main/src/test/java/io/trino/type/TestBoundedVarcharType.java
  core/trino-main/src/test/java/io/trino/type/TestCharType.java
  core/trino-spi/src/main/java/io/trino/spi/type/CharType.java
Labels: cla-signed, no-release-notes

#14910 Cache VarcharType.getRange
  core/trino-spi/src/main/java/io/trino/spi/type/VarcharType.java
Labels: cla-signed, no-release-notes

#14951 Use Guice binding CatalogName in connectors
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/jmx/ConnectorObjectNameGeneratorModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnectorFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/InternalDeltaLakeConnectorFactory.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchConnectorFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorConnectorFactory.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftConnectorFactory.java
Labels: cla-signed, tests:hive

#14966 Fix running TestInsert on single CPU nodes
  core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java
Labels: cla-signed

#14908 Use batch deletes in IcebergMetadata
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, performance, no-release-notes

#14935 Support result in LoggingInvocationHandler
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/LoggingInvocationHandler.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/util/TestLoggingInvocationHandler.java
Labels: cla-signed

#14976 Let `GlueIcebergUtil.getTableInput` populate the table type property
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed, no-release-notes

#14907 Report physical input data size in EXPLAIN ANALYZE
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/HashCollisionPlanNodeStats.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStats.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStatsSummarizer.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/WindowPlanNodeStats.java
  docs/src/main/sphinx/sql/explain-analyze.rst
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, docs, tests:hive

#14974 Decrease size of product-tests-launcher jar
  testing/trino-product-tests-launcher/pom.xml
Labels: cla-signed

#14949 Add failover to accessToken for OAuth2 with refresh token
  core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestJweTokenSerializer.java
Labels: cla-signed

#14873 Port OrcPageSourceFactory completely to TrinoFileSystem
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeleteDeltaPageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeleteDeltaPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeletedRows.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcDeleteDeltaPageSource.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcDeletedRows.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java
Labels: cla-signed, tests:hive

#14882 Restore Maven cache from default branch
  .github/workflows/ci.yml
Labels: cla-signed

#14632 Don't exclude server modules when checking impacted modules
  .github/workflows/ci.yml
Labels: cla-signed

#14792 Move benchmark macros to queries module
  testing/trino-benchmark-queries/src/main/resources/sql/presto/session_set_cbo_flags.sql
Labels: cla-signed

#14532 Add checkpoint for ORC UNION type
  lib/trino-orc/src/main/java/io/trino/orc/checkpoint/Checkpoints.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestReadUniontype.java
Labels: cla-signed, tests:hive

#14990 Update JMX metric name in documentation
  docs/src/main/sphinx/admin/jmx.rst
Labels: cla-signed, docs, no-release-notes

#14986 Fix failure when BigQuery row access policy return empty result
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStoragePageSource.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
Labels: cla-signed

#14913 Improve docs for system information functions
  docs/src/main/sphinx/functions/system.rst
Labels: cla-signed, docs

#14997 Execute DROP TABLE statement at end of test case
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/BaseTestDeltaLakeHdfsReads.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/BaseTestDeltaLakeMinioReads.java
Labels: cla-signed, tests:hive, no-release-notes

#15000 Specify simple collation in MongoDB filter to fix correctness issue
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
Labels: cla-signed

#14864 Add support for DELETE statement in MongoDB
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorSmokeTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
Labels: cla-signed, docs

#14816 Repackage Iceberg runtime exceptions into TrinoException during add/d…
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#14521 Standardize indefinite article for SQL
  core/trino-spi/src/main/java/io/trino/spi/function/InvocationConvention.java
  docs/README.md
  docs/src/main/sphinx/appendix/from-hive.rst
  docs/src/main/sphinx/connector/accumulo.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/develop/example-http.rst
  docs/src/main/sphinx/develop/functions.rst
  docs/src/main/sphinx/functions/json.rst
  docs/src/main/sphinx/overview/concepts.rst
  docs/src/main/sphinx/release/release-0.113.rst
  docs/src/main/sphinx/release/release-0.166.rst
  docs/src/main/sphinx/release/release-0.205.rst
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/util/DatabaseUtil.java
Labels: cla-signed, release-notes, docs, tests:hive

#15010 Set 'task.partitioned-writer-count' property to processor count in testExplicitPropertyMappings test
  core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
Labels: cla-signed

#14830 Do not create temporary staging path for CREATE TABLE statement
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveAlluxioMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveLocationService.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/LocationService.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
Labels: cla-signed, tests:hive

#15005 Reduce margin for START_OF_MODERN_ERA in delta lake stats
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Labels: cla-signed

#14848 Add Databricks 11.3 test environment to Delta Lake
  .github/workflows/ci.yml
  docs/src/main/sphinx/connector/delta-lake.rst
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks113.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks113.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTransactionLogCache.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Labels: cla-signed, docs, tests:hive

#14958 Fix ClassCastException in DomainTranslator
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
Labels: cla-signed

#15016 Remove ExchangeHandleResolver
  core/trino-main/src/main/java/io/trino/exchange/ExchangeManagerRegistry.java
  core/trino-main/src/main/java/io/trino/metadata/ExchangeHandleResolver.java
  core/trino-main/src/main/java/io/trino/metadata/HandleJsonModule.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/exchange/TestLazyExchangeDataSource.java
  core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
  core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
  core/trino-main/src/test/java/io/trino/execution/TestMemoryRevokingScheduler.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManager.java
  core/trino-main/src/test/java/io/trino/operator/TestDeduplicatingDirectExchangeBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java
  core/trino-main/src/test/java/io/trino/operator/TestExchangeOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestMergeOperator.java
  core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeManagerFactory.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeManagerFactory.java
Labels: cla-signed

#14567 Skip null checks for positions from blocks that have no nulls in aggr…
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
Labels: cla-signed

#14947 Make SQLServer deadlock query retries reusable
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed, no-release-notes

#15018 Reword docs to avoid mention of a/an SQL
  .github/DEVELOPMENT.md
  docs/README.md
  docs/src/main/sphinx/appendix/from-hive.rst
  docs/src/main/sphinx/connector/accumulo.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/connector/sqlserver.rst
  docs/src/main/sphinx/develop/connectors.rst
  docs/src/main/sphinx/develop/example-http.rst
  docs/src/main/sphinx/develop/functions.rst
  docs/src/main/sphinx/functions/json.rst
  docs/src/main/sphinx/overview/concepts.rst
  docs/src/main/sphinx/release/release-0.113.rst
  docs/src/main/sphinx/release/release-0.166.rst
  docs/src/main/sphinx/release/release-0.205.rst
Labels: cla-signed, release-notes, docs

#15038 Rename isMultipleWritersPerPartitionSupported to supportsMultipleWritersPerPartition
  core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableLayout.java
Labels: cla-signed

#15015 Eliminate duplicate random suffix generation code
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
  plugin/trino-bigquery/pom.xml
  plugin/trino-cassandra/pom.xml
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTable.java
  plugin/trino-clickhouse/pom.xml
  plugin/trino-druid/pom.xml
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-hive-hadoop2/pom.xml
  plugin/trino-mongodb/pom.xml
  plugin/trino-oracle/pom.xml
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/LdapUtil.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestingOpenLdapServer.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentContainers.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestCreateTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksDelete.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksPartitioningCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksUpdates.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDropTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeGcs.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTransactionLogCache.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAbfsSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCreateDropSchema.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePartitionSchemaEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/util/TemporaryHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestCreateDropSchema.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergCreateTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergFormatVersionCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergInsert.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergOptimize.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRenameTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkDropTableCompatibility.java
  testing/trino-testing-services/src/main/java/io/trino/testing/TestingNames.java
Labels: cla-signed, ready to merge, tests:hive, no-release-notes

#15039 Optimize Timestamp Formatting
  core/trino-spi/src/main/java/io/trino/spi/type/Timestamps.java
Labels: cla-signed

#15057 Reduce tests memory footprint
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
Labels: cla-signed, test, no-release-notes

#15060 Update io.trino.hadoop:hadoop-apache to 3.2.0-18
  pom.xml
Labels: cla-signed

#15013 Big query retries during create read session
  plugin/trino-bigquery/pom.xml
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryUtil.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
Labels: cla-signed

#14945 Support unwrap date to timestamp with time zone
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java
  core/trino-main/src/test/java/io/trino/sql/query/TestUnwrapCastInComparison.java
Labels: cla-signed

#14952 Documented differences between INTERVAL expression on Trino versus Hive
  docs/src/main/sphinx/appendix/from-hive.rst
Labels: cla-signed, docs

#15042 Rename config properties in Google Sheets
  docs/src/main/sphinx/connector/googlesheets.rst
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/SheetsQueryRunner.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsPlugin.java
Labels: cla-signed, docs

#14067 Remove deprecated getBucketNodeMap method
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorNodePartitioningProvider.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeNodePartitioningProvider.java
Labels: cla-signed

#15041 Fix retry_delay_scale_factor validation message
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
Labels: cla-signed

#15070 Fix incorrect import for Delta Lake optimize procedure
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
Labels: cla-signed, no-release-notes

#15061 Port ParquetFileWriter to use TrinoOutputFile
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeUpdatablePageSource.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/HdfsParquetDataSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestHdfsParquetDataSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
Labels: cla-signed, tests:hive

#14197 Filter out values from system.metadata tables using access control
  core/trino-main/src/main/java/io/trino/connector/system/AbstractPropertiesSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/AnalyzePropertiesSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/ColumnPropertiesSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewPropertiesSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/SchemaPropertiesSystemTable.java
  core/trino-main/src/main/java/io/trino/connector/system/TablePropertiesSystemTable.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#15077 Remove outdated SPI revapi exclusions
  core/trino-spi/pom.xml
Labels: no-release-notes

#14673 Only allow Hive ACID tables for Thrift metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/ForwardingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive

#15064 Update PR template to be engineer-focused
  .github/pull_request_template.md
Labels: cla-signed

#14209 Check catalog & schema access in USE statement
  core/trino-main/src/main/java/io/trino/execution/UseTask.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#14333 Limit prefixes calculation early when planning for information_schema…
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
Labels: cla-signed

#15076 Use hudi confiugration corresponding to the product test environment
  testing/trino-server-dev/etc/catalog/hudi.properties
Labels: cla-signed, hudi

#15090 Fix 'materalized' typo
  docs/src/main/sphinx/release/release-397.md
  docs/src/main/sphinx/sql/alter-materialized-view.rst
Labels: cla-signed, release-notes, ready to merge, docs

#14985 Document the DML operations support on GCS
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#15031 Drop orphaned test Glue databases left behind by Delta Lake Databricks product tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCleanUpGlueMetastore.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCompatibilityCleanUp.java
Labels: cla-signed, tests:hive

#15078 Exempt certain APIs from SPI backward compatibility check
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/Unstable.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnDetail.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnInfo.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/OutputColumnMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryCompletedEvent.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryContext.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryCreatedEvent.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryFailureInfo.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryIOMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryInputMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryOutputMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/RoutineInfo.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/SplitCompletedEvent.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/SplitFailureInfo.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/SplitStatistics.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageCpuDistribution.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageGcStatistics.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageOutputBufferUtilization.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/TableInfo.java
  core/trino-spi/src/main/java/io/trino/spi/metrics/Metrics.java
Labels: cla-signed, no-release-notes

#14904 Delta Lake: Improve error message related to storage layers which allow write collisions
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Labels: cla-signed

#15054 Fix set-milestone failure when latest milestone is closed
  .github/workflows/milestone.yml
Labels: cla-signed

#14962 Allow replacement string to substitute against original user in impersonation
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
  core/trino-main/src/test/resources/catalog_impersonation.json
  docs/src/main/sphinx/security/file-system-access-control.rst
  docs/src/main/sphinx/security/user-impersonation.json
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ImpersonationRule.java
Labels: cla-signed, docs

#15105 Provide better default for SUPPORTS_RENAME_MATERIALIZED_VIEW behavior
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Labels: cla-signed, test, no-release-notes

#15110 Fix syntax error in set-milestone workflow
  .github/workflows/milestone.yml
Labels: cla-signed, no-release-notes

#14454 Document additional credential providers for JDBC connectors
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/jdbc-authentication.fragment
  docs/src/main/sphinx/connector/mariadb.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#15118 Revert set-milestone workflow to known-working state
  .github/workflows/milestone.yml
Labels: cla-signed, no-release-notes

#15072 Use S3 batch deletes for Delta Lake vacuum procedure
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
Labels: cla-signed

#15119 Revert "Collect uncompressed data size for output statistics"
  core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerde.java
  core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingExchangeOutputBuffer.java
Labels: cla-signed

#15120 Fix set-milestone failure when latest milestone is closed
  .github/workflows/milestone.yml
Labels: cla-signed, no-release-notes

#15097 Improve insert row filter violation message grammar
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java
Labels: cla-signed, no-release-notes

#14961 Fix use of project ID in BigQuery connector
  .github/workflows/ci.yml
  plugin/trino-bigquery/README.md
  plugin/trino-bigquery/pom.xml
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClientFactory.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryWithDifferentProjectIdConnectorSmokeTest.java
Labels: cla-signed

#14861 Add guided walkthrough on configuring fault-tolerant execution
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
  docs/src/main/sphinx/installation.rst
  docs/src/main/sphinx/installation/query-resiliency.rst
Labels: cla-signed, docs

#14998 Suppress access denied exception when listing all tables/views in a Glue database
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, tests:hive

#15134 Fix param name in MockConnector listTables lambdas
  core/trino-main/src/test/java/io/trino/metadata/TestInformationSchemaMetadata.java
  testing/trino-tests/src/test/java/io/trino/connector/informationschema/BenchmarkInformationSchema.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMetadataManager.java
Labels: cla-signed, test, no-release-notes

#15140 Expose exchange manager from QueryRunner
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/QueryRunner.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/StandaloneQueryRunner.java
Labels: cla-signed

#15149 Remove unused method
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
Labels: cla-signed, tests:hive

#11645 Implement MySQL based event listener
  core/trino-server/src/main/provisio/trino.xml
  plugin/trino-mysql-event-listener/pom.xml
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListener.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerConfig.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerPlugin.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryEntity.java
  plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
  plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListenerConfig.java
  pom.xml
  testing/trino-server-dev/etc/config.properties
Labels: cla-signed

#15035 Hive Connector with Amazon S3 documentation updates
  docs/src/main/sphinx/connector/hive-s3.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#13948 Update MS SQL Server JDBC driver
  pom.xml
Labels: cla-signed

#15159 Fix flaky BigQuery testInsertSameValues
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
Labels: cla-signed

#15132 Populate a nulls fraction when NDV is known in TableScanStatsRule
  core/trino-main/src/main/java/io/trino/cost/TableScanStatsRule.java
  core/trino-main/src/test/java/io/trino/cost/StatsCalculatorAssertion.java
  core/trino-main/src/test/java/io/trino/cost/TestTableScanStatsRule.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseTestMySqlTableStatisticsTest.java
Labels: cla-signed

#15145 Set required env vars for build-pt CI job
  .github/workflows/ci.yml
  plugin/trino-delta-lake/README.md
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeDeltaLakeDatabricks.java
Labels: cla-signed

#14779 Add `register_table` procedure support for delta table
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDynamicFiltering.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLegacyCreateTableWithExistingLocation.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeReadTimestamps.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeRegisterTableProcedureWithFileMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestSplitPruning.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRegisterTableProcedureWithGlue.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake/delta.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-kerberized-hdfs/delta.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/BaseTestDeltaLakeHdfsReads.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/BaseTestDeltaLakeMinioReads.java
Labels: cla-signed, release-notes, docs, tests:hive

#14500 Add context appender to sql based connectors
  core/trino-main/src/main/java/io/trino/testing/TestingConnectorSession.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSinkProvider.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifierConfig.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/RemoteQueryModifier.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/RemoteQueryModifierModule.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifierConfig.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifierModule.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbClient.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlClient.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/CollationAwareQueryBuilder.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestRemoteQueryCommentLogging.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestRemoteQueryCommentLoggingDisabledByDefault.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerClient.java
Labels: cla-signed

#15066 Batch metastore calls in finishInsertIntoExistingPartitions
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed, tests:hive

#15185 Fix Hive Parquet test failure on certain Arm machines
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java
Labels: cla-signed, test, tests:hive, no-release-notes

#15189 Fix broken Delta Lake test about UPDATE partition columns
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
Labels: cla-signed, tests:hive

#15157 Run compilation check as a composite action
  .github/actions/compile-commit/action.yml
  .github/workflows/ci.yml
Labels: cla-signed

#15207 Add test for registering partitioned table in Delta Lake and Iceberg
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
Labels: cla-signed

#15188 Change enum BigQueryType to class
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryFilterQueryBuilder.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/Conversions.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestTypeConversions.java
Labels: cla-signed, no-release-notes

#15155 Fix race condition in Arbitrary/BroadcastOutputBuffer
  core/trino-main/src/main/java/io/trino/execution/buffer/ArbitraryOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/BroadcastOutputBuffer.java
Labels: cla-signed

#15209 Move JoinFilterFunctionCompiler constructor below fields
  core/trino-main/src/main/java/io/trino/sql/gen/JoinFilterFunctionCompiler.java
Labels: cla-signed, no-release-notes

#15203 Fix derivation of LocalExchange single stream property
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestWindowQueries.java
Labels: cla-signed

#15179 Remove unused field
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeAssignmentStats.java
Labels: cla-signed

#15116 Add code comment for StuckSplitTasksInterrupter race condition
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
Labels: cla-signed

#15198 Provide injection mechanism for the metastore in the Delta Lake connector
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnectorFactory.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/InternalDeltaLakeConnectorFactory.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeRegisterTableProcedureWithFileMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakePlugin.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestingDeltaLakeMetastoreModule.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRegisterTableProcedureWithGlue.java
Labels: cla-signed, no-release-notes

#15227 Remove MongoDB field from collections when dropping a column
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, tests:hive

#15059 Improve client JSON value adapters
  client/trino-client/src/main/java/io/trino/client/FixJsonDataUtils.java
  client/trino-client/src/main/java/io/trino/client/Row.java
Labels: cla-signed

#15245 Use correct secret names in the ok-to-test workflow
  .github/workflows/ok-to-test.yml
Labels: cla-signed

#15239 Remove redundant BaseMongoConnectorTest
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTempConnectorTest.java
Labels: cla-signed, no-release-notes

#15142 Improve error message for partitioning by nested field in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPartitionEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes

#15242 Embed Trino version in QueryInfo
  core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQuery.java
  core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQueryFactory.java
  core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQueryFactory.java
  core/trino-main/src/main/java/io/trino/execution/QueryInfo.java
  core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
  core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
  core/trino-main/src/test/java/io/trino/execution/MockManagedQueryExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestCallTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
  core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
  core/trino-main/src/test/java/io/trino/execution/TestResetSessionTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRollbackTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetPathTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetRoleTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetSessionTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
  core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
  core/trino-main/src/test/java/io/trino/server/TestBasicQueryInfo.java
  core/trino-main/src/test/java/io/trino/server/TestQueryStateInfo.java
Labels: cla-signed

#15115 Add query.max-run-time.hard-limit
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/TestSystemSessionProperties.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#15214 Fix DatabaseMetaData.getColumns nullability inconsistency
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
  core/trino-main/src/main/java/io/trino/connector/system/jdbc/ColumnJdbcTable.java
  testing/trino-product-tests/src/main/resources/io/trino/tests/product/jdbc/get_nation_columns.result
Labels: cla-signed, jdbc, tests:hive

#15243 Print Trino version to EXPLAIN ANALYZE VERBOSE
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-main/src/main/java/io/trino/operator/ExplainAnalyzeOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
  docs/src/main/sphinx/sql/explain-analyze.rst
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed, docs

#15257 Increase Parquet page max positions
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
Labels: cla-signed, tests:hive
