Repository trinodb/trino, pull requests merged in 2022-02, with the labels that each got.

#10764 Implement shallowEquals() for SampledRelation
  core/trino-parser/src/main/java/io/trino/sql/tree/SampledRelation.java
  testing/trino-tests/src/test/java/io/trino/tests/TestTablesample.java
Labels: cla-signed

#10579 Move cipher note from kerb to tls page
  docs/src/main/sphinx/security/kerberos.rst
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#10848 Replace presto.xml with trino.xml for provisio
  core/trino-server/src/main/provisio/trino.xml
Labels: cla-signed

#10871 Simplify interface for altering properties
  core/trino-main/src/main/java/io/trino/execution/SetPropertiesTask.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/security/AccessControl.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlyAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Labels: cla-signed, tests:hive

#10866 Migrate to UBI8 based Docker image
  core/docker/Dockerfile
  core/docker/arm64.dockerfile
  core/docker/build-local.sh
  core/docker/build-remote.sh
Labels: cla-signed

#10824 Supplement 366 release notes
  docs/src/main/sphinx/release/release-366.md
Labels: cla-signed, docs

#10870 Adjust testScanFilterAndProjectOperator
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
Labels: cla-signed, tests:hive

#10802 Fix Kudu tests to also run on MacOS
  plugin/trino-kudu/pom.xml
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestingKuduServer.java
Labels: cla-signed

#10865 Fix NPE when hiding Delta tables and Glue table lacks parameters
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueMetastoreTableFilterProvider.java
Labels: cla-signed, tests:hive

#10765 Use narrower modernizer exclusions
  core/trino-main/pom.xml
  core/trino-main/src/main/java/io/trino/testing/assertions/Assert.java
  plugin/trino-password-authenticators/pom.xml
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/jndi/JndiUtils.java
Labels: cla-signed

#10879 Remove redundant error-checking from bash script
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdp3/apply-hdp3-config.sh
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg/apply-hive-config-for-iceberg.sh
Labels: cla-signed

#10893 Fix BenchmarkGroupByHash.createVarcharPages values
  core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupByHash.java
Labels: cla-signed

#10880 Document various Iceberg compatibility tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveViewsCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#10587 Rename table layout classes, remove 'New'
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/TableLayout.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableLayout.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixMetadata.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorMetadata.java
Labels: cla-signed, tests:hive

#10867 Fix information_schema with IS NOT NULL predicate
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
  testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
Labels: cla-signed

#8819 Set higher open files limit in init script
  core/trino-server-rpm/src/main/resources/dist/etc/init.d/trino
  docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#10896 Improve Glue failure message when storage descriptor not set
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
Labels: cla-signed, tests:hive

#10712 Replace cache invalidation with TokenPoll.error
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchange.java
Labels: cla-signed

#10903 Cleanup Glue databases left behind by tests
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed, tests:hive

#10771 Add documentation for db resource group manager
  docs/src/main/sphinx/admin/resource-groups.rst
Labels: cla-signed, docs

#10602 Remove Block writePositionTo and BlockBuilder appendStructure
  core/trino-main/src/main/java/io/trino/operator/GroupByIdBlock.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/BlockBuilderCopier.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/arrayagg/SingleArrayAggregationState.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/SingleMultimapAggregationState.java
  core/trino-main/src/test/java/io/trino/block/AbstractTestBlock.java
  core/trino-main/src/test/java/io/trino/block/BlockAssertions.java
  core/trino-main/src/test/java/io/trino/block/TestArrayBlock.java
  core/trino-main/src/test/java/io/trino/block/TestBlockBuilder.java
  core/trino-main/src/test/java/io/trino/block/TestColumnarArray.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkUnnestOperator.java
  core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArrayFilter.java
  core/trino-main/src/test/java/io/trino/operator/unnest/TestingUnnesterUtil.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractMapBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractRowBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractSingleArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractSingleMapBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractSingleRowBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/AbstractVariableWidthBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/Block.java
  core/trino-spi/src/main/java/io/trino/spi/block/BlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int96ArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int96ArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/LazyBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/MapBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/RowBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleArrayBlockWriter.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleMapBlockWriter.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleRowBlockWriter.java
  core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
  core/trino-spi/src/main/java/io/trino/spi/type/MapType.java
  core/trino-spi/src/main/java/io/trino/spi/type/RowType.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestArrayBlockBuilder.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestReaderProjectionsAdapter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkProjectionPushdownHive.java
Labels: cla-signed, tests:hive

#10322 Load lazy blocks before using them in page filter/projection
  core/trino-main/src/main/java/io/trino/operator/project/InputChannels.java
  core/trino-main/src/main/java/io/trino/operator/project/PageFieldsToInputParametersRewriter.java
  core/trino-main/src/test/java/io/trino/operator/project/TestPageFieldsToInputParametersRewriter.java
  core/trino-spi/src/main/java/io/trino/spi/Page.java
  core/trino-spi/src/test/java/io/trino/spi/TestPage.java
Labels: cla-signed

#10919 Fix incorrect type mapping in ClickHouse documentation
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed, docs

#10917 Fix link and update wording
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#10907 Enable ClickHouse smoke tests except for Altinity 20.3.12
  plugin/trino-clickhouse/pom.xml
Labels: cla-signed

#10835 Document ALTER MATERIALIZED VIEW SET PROPERTIES
  docs/src/main/sphinx/connector/alter-mv-set-properties-unsupported.fragment
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/sql/alter-materialized-view.rst
Labels: cla-signed, docs

#10906 Enable testDataMappingSmokeTest in Phoenix 4 & 5
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#10868 Schedule dynamic filtering collecting task immediately
  core/trino-main/src/main/java/io/trino/execution/scheduler/FixedSourcePartitionedScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SourcePartitionedScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SourceScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionPolicy.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
  core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/policy/TestPhasedExecutionSchedule.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDynamicPartitionPruningTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergDynamicPartitionPruningTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
Labels: cla-signed, RELEASE-BLOCKER, tests:hive

#10920 Fix compile error due to missing constant
  core/trino-main/src/main/java/io/trino/type/DecimalCasts.java
  core/trino-main/src/main/java/io/trino/type/DecimalSaturatedFloorCasts.java
Labels: cla-signed

#10878 Extract io.trino.testing.containers into a separate module
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/containers/HiveMinioDataLake.java
  plugin/trino-mysql/pom.xml
  plugin/trino-sqlserver/pom.xml
  pom.xml
  testing/trino-testing-containers/pom.xml
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/BaseTestContainer.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/TestContainers.java
  testing/trino-testing-containers/src/test/java/io/trino/server/TestDummy.java
  testing/trino-testing/pom.xml
  testing/trino-tests/pom.xml
Labels: cla-signed, tests:hive

#10875 Remove manual creation of io.trino.metadata.Catalog in tests
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/TestingSession.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/connector/StaticConnectorFactory.java
  core/trino-main/src/test/java/io/trino/eventlistener/TestConnectorEventListener.java
  core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
  core/trino-main/src/test/java/io/trino/execution/TestCallTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestResetSessionTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetRoleTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetSessionTask.java
  core/trino-main/src/test/java/io/trino/metadata/TestInformationSchemaMetadata.java
  core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanNodePartitioning.java
  core/trino-main/src/test/java/io/trino/sql/query/TestShowQueries.java
  core/trino-main/src/test/java/io/trino/transaction/TestTransactionManager.java
  testing/trino-tests/src/test/java/io/trino/execution/TestConnectorEventListener.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java
  testing/trino-tests/src/test/java/io/trino/tests/TestLocalEngineOnlyQueries.java
  testing/trino-tests/src/test/java/io/trino/tests/TestProcedureCall.java
Labels: cla-signed

#10908 Improve docs for FileSystemAccessControl impersonation rule
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#10909 Stop automated removal of `tests:hive` label
  .github/workflows/labeler.yml
Labels: cla-signed

#10924 Increase timeout when testing Docker image
  core/docker/container-test.sh
Labels: cla-signed

#10926 Mark tests that write using Hive as flaky in TestHiveStorageFormats
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#10514 Document special tables exposed by Iceberg
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#10248 Add support for composite external auth redirect handler
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
  client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
  client/trino-client/src/main/java/io/trino/client/auth/external/CompositeRedirectHandler.java
  client/trino-client/src/main/java/io/trino/client/auth/external/ExternalRedirectStrategy.java
  client/trino-client/src/main/java/io/trino/client/auth/external/SystemOpenRedirectHandler.java
  client/trino-client/src/main/java/io/trino/client/auth/external/SystemOutPrintRedirectHandler.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
Labels: cla-signed, jdbc

#10449 Update externalAuthentication parameter for JDBC driver
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#10177 Update jline to 3.21.0
  client/trino-cli/pom.xml
  client/trino-cli/src/main/java/io/trino/cli/InputReader.java
Labels: cla-signed

#10800 Consolidate file-based authorization docs
  docs/src/main/sphinx/admin/graceful-shutdown.rst
  docs/src/main/sphinx/connector/hive-security.rst
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/release/release-330.rst
  docs/src/main/sphinx/release/release-337.rst
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#10793 Add Trino 370 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-370.md
Labels: cla-signed, release-notes, WIP, docs

#10911 Use autocommit context for testing metadata calls
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
Labels: cla-signed

#10816 Add pull request template
  .github/pull_request_template.md
Labels: cla-signed

#10913 Ignore invalid views when listing in Hive connector
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Labels: cla-signed, tests:hive

#10509 Run Error Prone without forking compiler
  .mvn/jvm.config
  pom.xml
Labels: cla-signed

#10912 Use IcebergFileFormat enum for better validation
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileFormat.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergWritableTableHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergOptimizeHandle.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java
Labels: cla-signed

#10935 Fix testConcurrentSchemaCreateAndDrop flakiness
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
Labels: cla-signed

#10937 Fix typo in `hideInaccesibleColumns`
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFilterHideInacessibleColumnsSession.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFilterInaccessibleColumns.java
Labels: cla-signed

#10945 Fix incorrect project version in trino-collect
  lib/trino-collect/pom.xml
Labels: cla-signed

#10948 Recover commentary about ReentrantBoundedExecutor use
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreModule.java
Labels: cla-signed, tests:hive

#10958 Simplify Metadata listTableColumns api
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
Labels: cla-signed

#10939 Authorize table parameters in CTAS and remove deprecated check methods
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  core/trino-main/src/main/java/io/trino/security/AccessControl.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlyAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Labels: cla-signed, tests:hive

#10944 Upgrade Error Prone to 2.11.0
  pom.xml
Labels: cla-signed

#10954 Avoid reflection and services lookup for JWT processing
  .mvn/modernizer/violations.xml
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
  core/trino-main/pom.xml
  core/trino-main/src/main/java/io/trino/server/InternalAuthenticationManager.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtUtil.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
  core/trino-main/src/main/java/io/trino/server/ui/FormWebUiAuthenticationFilter.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkDecoder.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestDynamicCallbackOAuth2Service.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
  service/trino-proxy/pom.xml
  service/trino-proxy/src/main/java/io/trino/proxy/JsonWebTokenHandler.java
Labels: cla-signed, jdbc

#10959 Index session catalog roles and properties using name instead of id
  core/trino-main/src/main/java/io/trino/Session.java
  core/trino-main/src/main/java/io/trino/SessionRepresentation.java
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/TestSession.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
  core/trino-main/src/test/java/io/trino/server/TestSessionPropertyDefaults.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingSessionContext.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed, tests:hive

#10963 Implement remaining TODOs from TIMESTAMP semantic fix
  client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectPushdown.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed, jdbc, tests:hive

#10714 Allow specifying role session name via S3 security mapping config
  docs/src/main/sphinx/connector/hive-s3.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMapping.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingConfigurationProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMapping.java
  plugin/trino-hive/src/test/resources/io/trino/plugin/hive/s3/security-mapping.json
Labels: cla-signed, docs, tests:hive

#10955 Remove line breaks in pull request template
  .github/pull_request_template.md
Labels: cla-signed

#10967 Fix out-of-date links in Cassandra connector doc
  docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed, docs

#10968 Leave only single startOAuth2Challenge method in OAuth2Service class
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java
  core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
Labels: cla-signed

#10815 Deny DML commands on Hive bucketed tables created by Spark
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Labels: cla-signed, tests:hive

#10977 Mark Iceberg testSelectInformationSchemaColumns as @Flaky
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#10978 Remove redundant use of Optional for target_max_file_size
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
Labels: cla-signed, tests:hive

#10989 Fix incorrect type mapping in Cassandra documentation
  docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed, docs

#10986 Remove reflective access from KuduRecordCursor
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduRecordCursor.java
Labels: cla-signed

#10993 Fix actions/labeler config to not remove manually added labels
  .github/workflows/labeler.yml
Labels: cla-signed

#11002 Stop ignoring children in TableDeleteNode.replaceChildren
  core/trino-main/src/main/java/io/trino/sql/planner/plan/TableDeleteNode.java
Labels: cla-signed

#10950 Ensure ExchangeClient is always properly closed
  core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
Labels: cla-signed

#11008 Fix duplicate headers in PR template
  .github/pull_request_template.md
Labels: cla-signed

#10998 Define session and catalog session properties
  docs/src/main/sphinx/admin/properties.rst
  docs/src/main/sphinx/sql/reset-session.rst
  docs/src/main/sphinx/sql/set-session.rst
  docs/src/main/sphinx/sql/show-session.rst
Labels: cla-signed, docs

#11024 Add comment on SpoolingExchangeOutputBuffer thread safety
  core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingExchangeOutputBuffer.java
Labels: cla-signed

#11025 Fix typo in Cassandra doc
  docs/src/main/sphinx/connector/cassandra.rst
Labels: cla-signed, docs

#11018 Fix wrong row values in column channel in tpcds queries q05, q14, q49, q76, q80
  testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q05.sql
  testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q14.sql
  testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q49.sql
  testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q76.sql
  testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q80.sql
Labels: cla-signed

#11029 Expose table properties in ClickHouse
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed

#10979 Delay removal of containers during Docker image tests
  core/docker/container-test.sh
Labels: cla-signed

#10702 Expose contains_nan in partitions metadata
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ManifestsTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSystemTables.java
Labels: cla-signed, docs

#10837 Handle split weights in SourceDistributionTaskSource
  core/trino-main/pom.xml
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestStageTaskSourceFactory.java
Labels: cla-signed

#11035 Fix metastore impersonation for Avro tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Labels: cla-signed, tests:hive

#11037 Improve negative date tests
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#11052 Syntax highlight release notes in pull request template
  .github/pull_request_template.md
Labels: cla-signed

#10996 Enable secrets in db resource group manager
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManagerFactory.java
Labels: cla-signed

#10914 Consider user groups in db resource groups manager
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/ResourceGroupsDao.java
  plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/SelectorRecord.java
  plugin/trino-resource-group-managers/src/main/resources/db/migration/mysql/V5__add_user_group_to_selectors.sql
  plugin/trino-resource-group-managers/src/main/resources/db/migration/oracle/V5__add_user_group_to_selectors.sql
  plugin/trino-resource-group-managers/src/main/resources/db/migration/postgresql/V5__add_user_group_to_selectors.sql
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/H2ResourceGroupsDao.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestResourceGroupsDao.java
  testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/H2TestUtil.java
  testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java
Labels: cla-signed

#11038 Migrate MongoDB tests to use BaseConnectorTest
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoDistributedQueries.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Labels: cla-signed

#11056 Minor cleanups to PR template
  .github/pull_request_template.md
Labels: cla-signed

#11047 Fix EvictableCache replace
  lib/trino-collect/src/main/java/io/trino/collect/cache/EvictableCache.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableCache.java
Labels: cla-signed

#11053 Add test for KuduClientConfig
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientConfig.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduClientConfig.java
Labels: cla-signed, maintenance

#10943 Add Trino 371 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-371.md
Labels: cla-signed, WIP, docs

#11084 Remove extraneous parens in single arg lambdas
  client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthentication.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeAssignmentStats.java
  core/trino-main/src/main/java/io/trino/metadata/FunctionResolver.java
  core/trino-main/src/main/java/io/trino/operator/DeduplicatingDirectExchangeBuffer.java
  core/trino-main/src/main/java/io/trino/operator/exchange/PageReference.java
  core/trino-main/src/main/java/io/trino/operator/exchange/PassthroughExchanger.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/CanonicalizeExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
  core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/type/DecimalCasts.java
  core/trino-main/src/main/java/io/trino/type/DecimalSaturatedFloorCasts.java
  core/trino-main/src/main/java/io/trino/type/DecimalToDecimalCasts.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestStageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/metadata/TestFunctionRegistry.java
  core/trino-main/src/test/java/io/trino/operator/TestHttpPageBufferClient.java
  core/trino-main/src/test/java/io/trino/server/TestDynamicFilterService.java
  core/trino-main/src/test/java/io/trino/server/security/TestHeaderAuthenticatorManager.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneCountAggregationOverScalar.java
  core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitWeightProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/HiveSecurityModule.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotQueryClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotClient.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseShardManager.java
  plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/statistics/TableStatisticsRecorder.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestTls.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCsv.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestJoinQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: tests:hive

#11073 Fix rendering of list in access control docs
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#11044 Fix race conditions in updating RemoteTaskStats
  core/trino-main/src/main/java/io/trino/server/remotetask/ContinuousTaskStatusFetcher.java
  core/trino-main/src/main/java/io/trino/server/remotetask/DynamicFiltersFetcher.java
  core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
Labels: cla-signed

#11055 Use long for representing date value in Accumulo
  plugin/trino-accumulo/pom.xml
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloRecordCursor.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/Field.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/AccumuloRowSerializer.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/LexicoderRowSerializer.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/StringRowSerializer.java
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/model/TestField.java
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/serializers/AbstractTestAccumuloRowSerializer.java
Labels: cla-signed

#11095 Enable `TestAltinityConnectorSmokeTest` in ClickHouse connector
  plugin/trino-clickhouse/pom.xml
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityConnectorSmokeTest.java
Labels: cla-signed

#11089 Make close on streaming S3 OutputStream idempotent
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#11088 Fix race condition in DirectExchangeClient
  core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java
Labels: cla-signed

#10997 Make Iceberg Dynamic Filter test more resilient
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#11068 Disable cache sharing when cache is disabled in JDBC connectors
  lib/trino-collect/src/main/java/io/trino/collect/cache/EmptyCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/EvictableCacheBuilder.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEmptyCache.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableCache.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableLoadingCache.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
Labels: cla-signed

#11061 Support incremental maven builds in PTL
  testing/trino-product-tests-launcher/bin/run-launcher
Labels: cla-signed

#11101 Disable ganglia metrics reporter for rubix
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/rubix/RubixInitializer.java
Labels: cla-signed, tests:hive

#11082 Add check for used Cassandra partition columns
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed

#11126 Replace Immutable(Map|Table).Builder.build() with buildOrThrow()
  .mvn/modernizer/violations.xml
  client/trino-jdbc/src/main/java/io/trino/jdbc/TypeConversions.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/operator/TestDeduplicatingDirectExchangeBuffer.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/FileSystemExchange.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/TestFileSystemExchangeConfig.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/containers/MinioStorage.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/s3/TestExchangeS3Config.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveQueryFailureRecoveryTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTaskFailureRecoveryTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestImpersonationCachingConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTaskFailureRecoveryTest.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/TestPinotAuthenticationTypeConfig.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/password/inline/TestPinotPasswordBrokerAuthenticationConfig.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/password/inline/TestPinotPasswordControllerAuthenticationConfig.java
  testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
Labels: cla-signed, jdbc, tests:hive

#11128 Update stale references to EvictableLoadingCache
  .mvn/modernizer/violations.xml
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonEvictableLoadingCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonEvictableLoadingCacheImpl.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonKeyEvictableLoadingCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonKeyEvictableLoadingCacheImpl.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/SafeCaches.java
Labels: cla-signed, maintenance

#11115 Merge TestJdbcIntegrationSmokeTest into TestJdbcConnectorTest
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcIntegrationSmokeTest.java
Labels: cla-signed, maintenance

#11133 Disable predicate pushdown on ARRAY(CHAR) type in Phoenix
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
Labels: cla-signed

#11097 Released memory retained by ExchangeSource
  core/trino-main/src/main/java/io/trino/operator/DeduplicatingDirectExchangeBuffer.java
  core/trino-main/src/main/java/io/trino/operator/ExchangeOperator.java
Labels: cla-signed

#11114 Migrate Kafka to use BaseConnectorTest
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaConnectorTest.java
Labels: cla-signed, maintenance

#11122 Support guessing BinData type as varbinary in MongoDB
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
Labels: cla-signed

#11144 Fix typo in ExpressionUtils
  core/trino-main/src/main/java/io/trino/sql/ExpressionUtils.java
Labels: cla-signed

#11145 Only mark dictionaries as compacted when they are not nested
  core/trino-spi/src/main/java/io/trino/spi/Page.java
  core/trino-spi/src/test/java/io/trino/spi/TestPage.java
Labels: cla-signed

#11142 Move Iceberg failure recovery test to separate job
  .github/workflows/ci.yml
  plugin/trino-iceberg/pom.xml
Labels: cla-signed

#11119 Define additional repos only in submodules using them
  plugin/trino-kafka/pom.xml
  plugin/trino-pinot/pom.xml
  pom.xml
  testing/trino-product-tests/pom.xml
Labels: cla-signed, tests:hive

#11078 Flexible TupleDomain.intersect type
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java
Labels: cla-signed

#11143 Add support for editing column comments on Iceberg tables
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
Labels: cla-signed

#11155 Test against PostgreSQL 10 since 9.x is now unsupported
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsPostgresqlFlywayMigration.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodePostgresql.java
Labels: cla-signed

#11081 rename AggregateFunction#inputs to arguments
  core/trino-spi/src/main/java/io/trino/spi/connector/AggregateFunction.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/aggregation/AggregateFunctionPatterns.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/BaseImplementAvgBigint.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementAvgDecimal.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementAvgFloatingPoint.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementCorr.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementCount.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementCountAll.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementCountDistinct.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementCovariancePop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementCovarianceSamp.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementMinMax.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementRegrIntercept.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementRegrSlope.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementStddevPop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementStddevSamp.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementSum.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementVariancePop.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementVarianceSamp.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementApproxDistinct.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementAvg.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementCountAll.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementCountDistinct.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementMinMax.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementSum.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerCountBig.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerCountBigAll.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerStddevPop.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerStdev.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerVariance.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerVariancePop.java
Labels: cla-signed

#10586 Add primary key to selectors table
  plugin/trino-resource-group-managers/src/main/resources/db/migration/mysql/V6__add_primary_key_to_selectors.sql
  plugin/trino-resource-group-managers/src/main/resources/db/migration/oracle/V6__add_primary_key_to_selectors.sql
  plugin/trino-resource-group-managers/src/main/resources/db/migration/postgresql/V6__add_primary_key_to_selectors.sql
Labels: cla-signed

#11040 Making TestCassandraConnectorTest more maintainable
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraTestingUtils.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTable.java
Labels: cla-signed

#10817 Document hive storage table properties
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#10973 #7656 Link format_datetime function in list.rst to actual docs
  docs/src/main/sphinx/functions/list-by-topic.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#11149 Add error message for Decimals utility methods
  core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java
Labels: cla-signed

#11168 Document why Iceberg table needs to be external in metastore
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractMetastoreTableOperations.java
Labels: cla-signed

#11154 Add exchange-manager properties to dev setup
  testing/trino-server-dev/etc/config.properties
  testing/trino-server-dev/etc/exchange-manager.properties
Labels: cla-signed

#11032 Update iceberg to 0.13.1
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/HistoryTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/MetricsWrapper.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractMetastoreTableOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestMetricsWrapper.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#11092 Handle missing StorageDescriptor in Hive Glue tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed, tests:hive

#11134 Fix metadata listing failure in case of concurrent table deletion in Phoenix
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
Labels: cla-signed

#11184 Use TestCassandraTable in testClusteringKeyOnlyPushdown to test
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed

#11186 Change wording in catalog session properties section
  docs/src/main/sphinx/sql/set-session.rst
Labels: cla-signed, docs

#10925 Allow configuration of read/connect timeout in LDAP client
  docs/src/main/sphinx/security/ldap.rst
  plugin/trino-password-authenticators/pom.xml
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/JdkLdapAuthenticatorClient.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapConfig.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestLdapAuthenticator.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestLdapAuthenticatorWithTimeouts.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestLdapConfig.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestingOpenLdapServer.java
Labels: cla-signed, docs

#10413 Add a healthcheck to the Docker container image
  core/docker/Dockerfile
  core/docker/bin/health-check
  core/docker/container-test.sh
Labels: cla-signed

#11192 Fix typo in hive table statistics config property
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#11197 Add stats rule for DistinctLimitNode
  core/trino-main/src/main/java/io/trino/cost/DistinctLimitStatsRule.java
  core/trino-main/src/main/java/io/trino/cost/StatsCalculatorModule.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
Labels: cla-signed, tests:hive

#11167 Remove unnecessary purgeData parameter of TrinoCatalog.dropTable
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoHiveCatalog.java
Labels: cla-signed

#11175 Bump bytecode dependency version to 1.4
  core/trino-main/src/main/java/io/trino/operator/scalar/MapTransformValuesFunction.java
  pom.xml
Labels: cla-signed

#11199 Fix TestHiveGlueMetastore#testGetDatabasesLogsStats
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed, tests:hive

#11091 Fix Iceberg statistics accumulation after schema evolution
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergStatistics.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSystemTables.java
Labels: cla-signed

#10264 Optimize null checking in DictionaryBlock
  core/trino-main/src/test/java/io/trino/block/AbstractTestBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Block.java
  core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
Labels: cla-signed

#11189 Document prepared statement compression properties.
  core/trino-main/src/main/java/io/trino/server/ProtocolConfig.java
  docs/src/main/sphinx/admin/properties-general.rst
Labels: cla-signed, docs

#11195 Fix CachingDirectoryLister when constructed with 0 cache TTL
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
Labels: cla-signed, tests:hive

#11104 Fix Iceberg dereference pushdown when column has a comment
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#10885 Remove legacy ORC writer identification
  lib/trino-orc/src/main/java/io/trino/orc/OrcWriterOptions.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataWriter.java
Labels: cla-signed, tests:hive

#11012 Add username and password section
  docs/src/main/sphinx/installation/cli.rst
Labels: cla-signed, docs

#11210 Simplify MySqlClient.toColumnMapping
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
Labels: cla-signed, maintenance

#11170 Add rule for unwrapping TIMESTAMP to DATE cast when comparing with DATE literal
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapTimestampToDateCastInComparison.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java
  core/trino-main/src/test/java/io/trino/sql/query/TestUnwrapCastInComparison.java
Labels: cla-signed

#11090 Allow reading Zstandard compressed Avro files
  pom.xml
Labels: cla-signed

#11231 Fix node cleanup for MemSQL tests
  .github/workflows/ci.yml
Labels: cla-signed

#11221 Bump antlr to 4.9.3
  pom.xml
Labels: cla-signed
