Repository trinodb/trino, pull requests merged in 2022-12, with the labels that each got.

#14971 Suppress permission denied when listing tables and views in Iceberg Glue
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed

#15263 Remove `mongodb.seeds` and `mongodb.credentials` config properties
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
Labels: cla-signed

#15270 Reclaim PagesSerde memory in Query
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
Labels: cla-signed, RELEASE-BLOCKER

#15266 Improve heuristic of using dictionary in project and filter
  core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageFilter.java
  core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageProjection.java
  core/trino-main/src/test/java/io/trino/operator/project/TestDictionaryAwarePageFilter.java
  core/trino-main/src/test/java/io/trino/operator/project/TestDictionaryAwarePageProjection.java
Labels: cla-signed

#15276 Make `legacyToWriteMapping` method static
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
Labels: cla-signed, no-release-notes

#15280 Remove redundant code
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java
Labels: cla-signed

#15296 Remove TODO comment from testDropAndAddColumnWithSameName in Hive
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive, no-release-notes

#15295 Load catalogs concurrently
  core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java
  core/trino-main/src/main/java/io/trino/connector/StaticCatalogManager.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
Labels: cla-signed, no-release-notes

#15290 Fix incorrect result when add/subtract interval with timestamptz
  core/trino-main/src/main/java/io/trino/operator/scalar/timestamptz/TimestampWithTimeZoneOperators.java
  core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestOperators.java
Labels: cla-signed

#15302 Remove unused testing DataType factories
  testing/trino-testing/src/main/java/io/trino/testing/datatype/DataType.java
Labels: cla-signed, test, no-release-notes

#15297 Mark testUnionDistinctViews as `@Flaky`
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/HadoopTestUtils.java
Labels: cla-signed, test, tests:hive, no-release-notes

#15089 Fix default values in task properties docs
  docs/src/main/sphinx/admin/properties-task.rst
Labels: cla-signed, docs

#14379 Add verification step for authorization docs
  docs/src/main/sphinx/security/file-system-access-control.rst
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed, docs

#14353 Add verification step for authentication docs
  docs/src/main/sphinx/security/overview.rst
  docs/src/main/sphinx/security/password-file.rst
Labels: cla-signed, docs

#15320 Close mongo cursor in MongoSession#getTableMetadataNames
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
Labels: cla-signed, no-release-notes

#15202 Do not pass default properties to access control checks
  core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
  core/trino-main/src/main/java/io/trino/execution/CreateSchemaTask.java
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#15322 Support setting read timeout in Google Sheets
  docs/src/main/sphinx/connector/googlesheets.rst
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestGoogleSheets.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java
Labels: cla-signed, docs

#15265 Link contributing guide
  .github/CONTRIBUTING.md
Labels: cla-signed

#15335 Disable reduced index pushdown for IndexJoin
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/IndexJoinOptimizer.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestIndexedQueries.java
Labels: cla-signed

#15348 Fix property derivations for PatternRecognitionNode
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatching.java
Labels: cla-signed

#15344 Inline configuration property value
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
  core/trino-main/src/main/java/io/trino/memory/NodeMemoryConfig.java
  core/trino-main/src/main/java/io/trino/server/security/KerberosConfig.java
Labels: cla-signed

#15307 Set output buffer overutilized when new pages are allowed
  core/trino-main/src/main/java/io/trino/execution/buffer/ArbitraryOutputBuffer.java
Labels: cla-signed

#15333 Remove hash collisions reporting
  core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/GroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/HashAggregationOperator.java
  core/trino-main/src/main/java/io/trino/operator/HashCollisionsCounter.java
  core/trino-main/src/main/java/io/trino/operator/HashCollisionsInfo.java
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/NoChannelGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/OperatorInfo.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/builder/HashAggregationBuilder.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/builder/SpillableHashAggregationBuilder.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/partial/SkipAggregationBuilder.java
  core/trino-main/src/main/java/io/trino/operator/join/BigintPagesHash.java
  core/trino-main/src/main/java/io/trino/operator/join/DefaultPagesHash.java
  core/trino-main/src/main/java/io/trino/operator/join/HashBuilderOperator.java
  core/trino-main/src/main/java/io/trino/operator/join/JoinHashSupplier.java
  core/trino-main/src/main/java/io/trino/operator/join/LookupSourceSupplier.java
  core/trino-main/src/main/java/io/trino/operator/join/PagesHash.java
  core/trino-main/src/main/java/io/trino/operator/join/unspilled/HashBuilderOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/HashCollisionPlanNodeStats.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/OperatorHashCollisionsStats.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStatsSummarizer.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TextRenderer.java
  core/trino-main/src/main/java/io/trino/util/HashCollisionsEstimator.java
  core/trino-main/src/test/java/io/trino/operator/CyclingGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
  core/trino-main/src/test/java/io/trino/util/HashCollisionsSimulator.java
  core/trino-main/src/test/java/io/trino/util/TestHashCollisionsEstimator.java
  docs/src/main/sphinx/admin/dynamic-filtering.rst
  docs/src/main/sphinx/sql/explain-analyze.rst
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed, docs

#15186 Multiply on disk column sizes of iceberg data files by 4 for column stats
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q19.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q24.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q27.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q29.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q30.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q31.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q57.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q72.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q83.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q19.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q24.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q27.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q29.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q30.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q31.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q57.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q72.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/partitioned/q05.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/partitioned/q07.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/partitioned/q08.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/unpartitioned/q05.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/unpartitioned/q07.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/unpartitioned/q08.plan.txt
Labels: cla-signed, tests:hive

#15196 Propagate table information when creating Connection for RecordCursor
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordCursor.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Labels: cla-signed

#15354 Remove unused throws Exception in TestPhoenixConnectorTest
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#15355 Update ldap.rst
  docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed, docs

#15356 Filter out empty distributions in EXPLAIN ANALYZE VERBOSE
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TextRenderer.java
  docs/src/main/sphinx/sql/explain-analyze.rst
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed, docs

#15197 Allow capturing authorization details in JdbcTableHandle
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTableHandle.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSetProvider.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableHandle.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Labels: cla-signed

#15360 Convert CREATE MV parser tests to `ParserAssert`
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed, test, no-release-notes

#15362 Remove unnecessary computation
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapDateTruncInComparison.java
Labels: cla-signed

#15342 Improve error message when `TrinoException` happened in `ExpressionCompiler`
  core/trino-main/src/main/java/io/trino/sql/gen/ExpressionCompiler.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalExecutionPlanner.java
Labels: cla-signed, no-release-notes

#15327 Test SET PATH support by clients
  client/trino-client/src/main/java/io/trino/client/StatementClientFactory.java
  client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
  core/trino-main/src/main/java/io/trino/Session.java
  core/trino-main/src/main/java/io/trino/testing/TestingSession.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
  testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
Labels: cla-signed, no-release-notes

#15336 Fix HTTP_Status on OAuth2 refresh token redirect
  core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
Labels: cla-signed

#15364 Fix recording of projection metrics
  core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
Labels: cla-signed

#15278 Fix dereference operations for union type in Hive Connector
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestReadUniontype.java
Labels: cla-signed, tests:hive

#15357 Cleanup PartitioningExchanger
  core/trino-main/src/main/java/io/trino/operator/exchange/PartitioningExchanger.java
Labels: cla-signed

#15370 Fix table name in TestDropTableTask
  core/trino-main/src/test/java/io/trino/execution/TestDropTableTask.java
Labels: cla-signed, no-release-notes

#15201 Decode paths as URIs in delta-lake connector
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/resources/databricks/uri/README.md
  plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000000.json
  plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000001.json
  plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000002.json
  plugin/trino-delta-lake/src/test/resources/databricks/uri/_delta_log/00000000000000000003.json
  plugin/trino-delta-lake/src/test/resources/databricks/uri/part=a%3Acolon/part-00000-ab613d48-052b-4de3-916a-ee0d89139446.c000.snappy.parquet
  plugin/trino-delta-lake/src/test/resources/databricks/uri/part=a%3Dequal/part-00000-d6a0dd7d-8416-436d-bb00-245452904a81.c000.snappy.parquet
  plugin/trino-delta-lake/src/test/resources/databricks/uri/part=a+plus/part-00000-4aecc0d9-dfbf-4180-91f1-4fd762dbc279.c000.snappy.parquet
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java
Labels: cla-signed, tests:hive

#15377 Remove unused method from AstBuilder
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
Labels: cla-signed, no-release-notes

#15079 Update to Iceberg 1.1.0
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroPageSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
  pom.xml
  testing/trino-faulttolerant-tests/pom.xml
  testing/trino-tests/pom.xml
Labels: cla-signed, no-release-notes

#8468 Document Top-N pushdown
  docs/src/main/sphinx/optimizer/pushdown.rst
Labels: cla-signed, docs

#15390 Remove unnecessary override for `getTableProperties` method
  core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-example-http/src/main/java/io/trino/plugin/example/ExampleMetadata.java
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java
  plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxMetadata.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaMetadata.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisMetadata.java
  plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileMetadata.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusMetadata.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftMetadata.java
  plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsMetadata.java
Labels: cla-signed, no-release-notes

#15401 Update sqlserver.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#15380 Disable preventive GC
  core/docker/default/etc/jvm.config
  core/trino-server-rpm/src/main/resources/dist/config/jvm.config
  docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#15369 Decide number of clients basing on average request size of client
  core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java
  core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
  core/trino-main/src/main/java/io/trino/operator/PageBufferClientStatus.java
  core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java
  core/trino-main/src/test/java/io/trino/operator/TestHttpPageBufferClient.java
Labels: cla-signed

#15395 Use enhanced switch statement
  lib/trino-geospatial-toolkit/src/main/java/io/trino/geospatial/serde/GeometrySerde.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, no-release-notes

#15382 Remove redundant scope parameter
  core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java
Labels: cla-signed

#15413 Add test create Atop connector
  plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopPlugin.java
Labels: cla-signed, no-release-notes

#15416 Add Delta Lake views docs
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#15408 Fix error in Iceberg predicate pushdown to Parquet files
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: bug, cla-signed, correctness

#15104 Add materialized view GRACE PERIOD syntax
  core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
  core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateMaterializedView.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed, no-release-notes

#15427 Upgrade tempto version to 190
  pom.xml
Labels: cla-signed, no-release-notes

#15352 Speed up `QualifiedName` constructor
  core/trino-parser/src/main/java/io/trino/sql/tree/QualifiedName.java
Labels: cla-signed

#15438 Support Glue database with empty location string
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
Labels: cla-signed, tests:hive, no-release-notes

#15400 Store NDV stats in Iceberg Puffin statistics file
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsWriter.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAnalyze.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestTableStatisticsWriter.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergFaultTolerantExecutionTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergQueryFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergTaskFailureRecoveryTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, docs, tests:hive

#15444 Shutdown yield executor
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
Labels: cla-signed

#15244 Optimize reading dictionary encoded parquet columns
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/TransformingValueDecoders.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoder.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BooleanColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ByteColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/DictionaryDecoder.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int96ColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/IntColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/LongColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ShortColumnAdapter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestamp.java
Labels: cla-signed, tests:hive, performance

#15447 Remove redundant RegisterTableProcedure field
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
Labels: cla-signed

#15398 RollbackToSnapshotProcedure code cleanup
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java
Labels: cla-signed, no-release-notes

#15421 Remove obsolete comment from Hudi S3 query runner
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
Labels: cla-signed, no-release-notes

#15442 Document raw_query table function in Elasticsearch connector
  docs/src/main/sphinx/connector/elasticsearch.rst
Labels: cla-signed, docs

#15458 Extract a method to create testing GlueHiveMetastore
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreViews.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingGlueMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRegisterTableProcedureWithGlue.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
Labels: cla-signed, tests:hive, no-release-notes

#15328 Test Delta Lake metadata handling when schema already exists
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateSchemaInternalRetry.java
Labels: cla-signed

#10561 retry to connect to hive metastore with new delegation token.
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java
Labels: cla-signed, tests:hive

#15437 Add test with predicate on top level and nested field
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#15463 Enforce no more than 126 task retries
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
Labels: cla-signed

#15469 Fix test configuration method duplicated logging
  testing/trino-testing-services/src/main/java/io/trino/testng/services/ProgressLoggingListener.java
Labels: cla-signed

#15462 Recreate thrift client during alternate calls
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
Labels: cla-signed, docs, tests:hive, no-release-notes

#15468 Use createTestingFileHiveMetastore method in tests
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingHiveMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataListing.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Labels: cla-signed, tests:hive, no-release-notes

#15479 Fix malformed test javadoc
  core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java
Labels: cla-signed, no-release-notes

#14972 Bigquery arrow support
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/pom.xml
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplit.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageArrowPageSource.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryTypeMapping.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowTypeMapping.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroTypeMapping.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
  pom.xml
Labels: cla-signed, docs

#15472 Remove TODO comment about predicates on struct type in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#15168 Adjust scheduler assignment queue for node
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeAssignmentStats.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeSchedulerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelector.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelectorFactory.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelector.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelectorFactory.java
  core/trino-main/src/test/java/io/trino/execution/BenchmarkNodeScheduler.java
  core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
  core/trino-main/src/test/java/io/trino/execution/TestNodeSchedulerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestUniformNodeSelector.java
  docs/src/main/sphinx/admin/properties-node-scheduler.rst
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBucketedQueryWithManySplits.java
  testing/trino-tests/src/test/java/io/trino/tests/TestJoinQueries.java
Labels: cla-signed, docs, tests:hive

#15486 Adjusting scheduler assignment queue clean up
  core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestUniformNodeSelector.java
Labels: cla-signed

#15341 Fix SET TIME ZONE LOCAL works appropriate
  core/trino-main/src/main/java/io/trino/execution/SetTimeZoneTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
Labels: cla-signed

#15484 Provide more verbose exception messages
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive, no-release-notes

#15471 Tune GC in tests to improve heap saturation
  pom.xml
Labels: cla-signed, test, no-release-notes

#15477 Add support for base64 encoded secrets in Google Sheets connector
  docs/src/main/sphinx/connector/googlesheets.rst
  plugin/trino-google-sheets/pom.xml
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java
Labels: cla-signed, docs

#15482 Migrate more code to TrinoFileSystem in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, no-release-notes

#15403 Remove query.max-run-time.hard-limit
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/TestSystemSessionProperties.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#15485 Use RoundingMode enum instead of deprecated BigDecimal constant
  client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalAverageAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestDecimalAverageAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestDecimalSumAggregation.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java
Labels: cla-signed, jdbc, tests:hive, no-release-notes

#15210 Run check-commits dispatcher only if PR branch has `compile-commit` job
  .github/workflows/ci.yml
Labels: cla-signed

#15500 Remove unused methods from BaseDeltaLakeConnectorSmokeTest
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Labels: cla-signed

#15474 Create a config param and session properties for setting Parquet's max read block row count
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderOptions.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeUpdatablePageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetReaderConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
Labels: cla-signed, tests:hive

#15470 Use `char(x)` representation for Hive `char` view columns
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
Labels: cla-signed, tests:hive

#15464 Add test for DROP TABLE IF EXISTS statement with non-existing object
  core/trino-main/src/test/java/io/trino/execution/TestDropTableTask.java
Labels: cla-signed, test, no-release-notes

#15495 Reduce Iceberg metrics reporting verbosity in logs
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoMetricsReporter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed

#15505 Update benchto to newest version
  pom.xml
Labels: cla-signed

#15503 Check procedure argument for NULL in RollbackToSnapshotProcedure
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Labels: cla-signed, tests:hive, no-release-notes

#15510 Simplify cache constructor
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
Labels: cla-signed, tests:hive

#15513 Add config property to disable new Redshift type mappings
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConfig.java
  plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConfig.java
Labels: cla-signed

#15449 Add missing CatalogVersion INSTANCE_SIZE constant
  core/trino-spi/src/main/java/io/trino/spi/connector/CatalogHandle.java
Labels: cla-signed

#15405 Describe join pushdowns prioritizing correctness over performance
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/mariadb.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/pinot.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/pushdown-correctness-behavior.fragment
  docs/src/main/sphinx/connector/redis.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#15518 Fix the behavior validation for CTAS test
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#15488 Use pattern matching for instanceof in iceberg connector
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroDataConversion.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergInputInfo.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetColumnIOConverter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
Labels: cla-signed, no-release-notes

#15523 Fix typos in Trino Kubernetes install docs
  docs/src/main/sphinx/installation/kubernetes.rst
Labels: docs

#15490 Add unit test for ThriftHiveMetastoreClient::alternativeCall
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java
Labels: cla-signed, tests:hive

#15529 Remove redundant testing code in LocalQueryRunner
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
Labels: cla-signed

#15531 Improve Hive test verify method
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#15539 Do not update the metastore when setting Iceberg table/column comment
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
Labels: cla-signed, no-release-notes

#15063 Add note to docs README on use of a/an SQL
  docs/README.md
Labels: cla-signed, docs

#15543 Do not pass default properties to CTAS access control check
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#15537 Add main method for Iceberg REST catalog query runner
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
Labels: cla-signed, no-release-notes

#15545 Remove deprecated randomTableSuffix use randomNameSuffix instead
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/delta/TestDeltaFaultTolerantExecutionTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergFaultTolerantExecutionTest.java
  testing/trino-testing/src/main/java/io/trino/testing/sql/TestTable.java
Labels: cla-signed, no-release-notes

#15139 Add Trino 405 release notes
  docs/src/main/sphinx/connector/kafka.rst
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-404.md
  docs/src/main/sphinx/release/release-405.md
Labels: cla-signed, release-notes, docs

#15542 Fix incorrect results with empty projections in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed

#15553 Remove unused throws IOException in BaseTrinoCatalogTest
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
Labels: cla-signed, no-release-notes

#15570 Cleanup TestTrinoS3FileSystemMinio
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemMinio.java
Labels: cla-signed, tests:hive
