Repository trinodb/trino, pull requests merged in 2022-03, with the labels that each got.

#11228 Don't exclude anything in test matrix if impacted modules list is empty
  .github/bin/build-matrix-from-impacted.py
  .github/workflows/ci.yml
Labels: cla-signed

#10898 Update SQL Server JDBC driver to 10.2.0
  docs/src/main/sphinx/connector/sqlserver.rst
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-sqlserver/sqlserver.properties
  testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
  testing/trino-server-dev/etc/catalog/sqlserver.properties
Labels: cla-signed, docs, tests:hive

#11233 Remove unnecessary block
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#11171 Make sure that quoted identifiers remain quoted in formatter
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed

#11249 Remove deprecated constructor from JdbcColumnHandle
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcColumnHandle.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcQueryBuilder.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcColumnHandle.java
Labels: cla-signed, maintenance

#11253 Do not fail on close() if test Kudu server is not initialized
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDecimalColumns.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationGroupedExecution.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationHashPartitioning.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationIntegerColumns.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationRangePartitioning.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationSchemaNotExisting.java
Labels: cla-signed

#11238 Add trim_array function
  core/trino-main/src/main/java/io/trino/metadata/FunctionRegistry.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayTrimFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayTrimFunction.java
  docs/src/main/sphinx/functions/array.rst
  docs/src/main/sphinx/functions/list-by-topic.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#11269 Drop table after verifying the behavior in testRenameTable
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, maintenance

#11198 Add missing query transition to RUNNING state with task-level retries
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed, tests:hive

#11284 Change to valid comment in code snippet
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#11258 Document hash partition count property
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#11094 Add Trino 372 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-372.md
Labels: cla-signed, WIP, docs

#11286 Extract optimizer configs into OptimizerConfig
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/cost/CostComparator.java
  core/trino-main/src/main/java/io/trino/cost/OptimizerConfig.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineJoinDistributionType.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EliminateCrossJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDynamicFilter.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFilterConsumer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPlanMatchingFramework.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineSemiJoinDistributionType.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReorderJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestUnionWithReplicatedJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestWindow.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFilterHideInacessibleColumnsSession.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDistributedJoinQueries.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergDynamicPartitionPruningTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/SqlConsecutiveJoinBenchmark.java
  testing/trino-benchto-benchmarks/src/test/java/io/trino/sql/planner/TestTpcdsCostBasedPlan.java
  testing/trino-benchto-benchmarks/src/test/java/io/trino/sql/planner/TestTpchCostBasedPlan.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestIntegrationSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestJoinQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
  testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDictionaryAggregation.java
  testing/trino-tests/src/test/java/io/trino/tests/TestLateMaterializationQueries.java
Labels: cla-signed, tests:hive

#11259 TRY should handle invalid value error in cast VACHAR as TIMESTAMP
  core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/VarcharToTimestampCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/timestamptz/VarcharToTimestampWithTimeZoneCast.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestTryFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java
  core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
Labels: cla-signed

#11255 Add S3 Http Proxy configuration support
  docs/src/main/sphinx/connector/hive-s3.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Config.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3ConfigurationInitializer.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3Protocol.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestHiveS3Config.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystem.java
Labels: cla-signed, docs, tests:hive

#11272 Allow configuring view expiration time in BigQuery
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/pom.xml
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
Labels: cla-signed, docs

#11313 Temporarily disable kudu tests from running in CI
  .github/workflows/ci.yml
Labels: cla-signed

#11319 Append random suffix to Oracle temp table
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
Labels: cla-signed

#11291 Skip test-docs job when PR contains release-notes label
  .github/workflows/docs.yml
Labels: cla-signed

#11026 Link to comparison operators page
  docs/src/main/sphinx/sql/show-catalogs.rst
  docs/src/main/sphinx/sql/show-columns.rst
  docs/src/main/sphinx/sql/show-functions.rst
  docs/src/main/sphinx/sql/show-schemas.rst
  docs/src/main/sphinx/sql/show-session.rst
  docs/src/main/sphinx/sql/show-tables.rst
Labels: cla-signed, docs

#11329 Fix broken url in rn372
  docs/src/main/sphinx/release/release-372.md
Labels: cla-signed

#11328 Fix revoke grant option for
  docs/src/main/sphinx/sql/revoke.rst
Labels: cla-signed, docs

#11312 Move OptimizerConfig to planner package
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/cost/CostComparator.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineJoinDistributionType.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EliminateCrossJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDynamicFilter.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFilterConsumer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPlanMatchingFramework.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineSemiJoinDistributionType.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReorderJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestUnionWithReplicatedJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestWindow.java
  core/trino-main/src/test/java/io/trino/sql/query/TestFilterHideInacessibleColumnsSession.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDistributedJoinQueries.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergDynamicPartitionPruningTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/SqlConsecutiveJoinBenchmark.java
  testing/trino-benchto-benchmarks/src/test/java/io/trino/sql/planner/TestTpcdsCostBasedPlan.java
  testing/trino-benchto-benchmarks/src/test/java/io/trino/sql/planner/TestTpchCostBasedPlan.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestIntegrationSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestJoinQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
  testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDictionaryAggregation.java
  testing/trino-tests/src/test/java/io/trino/tests/TestLateMaterializationQueries.java
Labels: cla-signed, tests:hive

#11163 Use proper SQL identifier semantics for CALL arguments
  core/trino-main/src/main/java/io/trino/connector/system/KillQueryProcedure.java
  core/trino-main/src/main/java/io/trino/execution/CallTask.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CallArgument.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  core/trino-spi/src/main/java/io/trino/spi/procedure/Procedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/procedure/FlushHiveMetastoreCacheProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/UnregisterPartitionProcedure.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/procedures/RangePartitionProcedures.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingProcedures.java
  testing/trino-tests/src/test/java/io/trino/tests/TestProcedureCall.java
  testing/trino-tests/src/test/java/io/trino/tests/TestProcedureCreation.java
Labels: cla-signed, tests:hive

#11320 Set hbase.client.retries.number as 15 in testing Phoenix server
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestingPhoenixServer.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
Labels: cla-signed

#11212 Convert exception when failed to get columns in Phoenix
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#11340 Improve ClickHouse type mapping tests
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#11331 Add extra information on memory pool leaks
  core/trino-main/src/main/java/io/trino/memory/MemoryPool.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#10965 Aggregation improvements
  core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
Labels: cla-signed

#11022 Document support for ALTER TABLE SET PROPERTIES
  docs/src/main/sphinx/sql/alter-table.rst
Labels: cla-signed, docs

#11357 Enable test for partitioned table in BigQuery
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
Labels: cla-signed, maintenance

#11354 Use assignments instead of variable name in Elasticsearch
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
Labels: cla-signed

#11351 Deny wrong null replacement of array type in Phoenix connector
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#11353 Enable aggregation spill only when all aggregations are spillable
  core/trino-main/src/main/java/io/trino/operator/HashAggregationOperator.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestAggregations.java
Labels: bug, cla-signed, correctness

#11333 Improve estimation of row count from partition samples
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/statistics/MetastoreHiveStatisticsProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/statistics/TestMetastoreHiveStatisticsProvider.java
Labels: cla-signed, tests:hive

#11362 Improve SingleStore(MemSql) type mapping tests
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
Labels: cla-signed

#11365 Set useNativeGit in git-commit-id-plugin
  pom.xml
Labels: cla-signed

#11375 Improve description and visiblity of the properties reference
  docs/src/main/sphinx/admin/properties.rst
  docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#11374 Replace references to "Presto" and "SEP" in Delta Lake connector
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeReadTimestamps.java
Labels: cla-signed

#11383 Extract query runner in Google Sheets connector
  plugin/trino-google-sheets/pom.xml
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/SheetsQueryRunner.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestGoogleSheets.java
  plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsPlugin.java
Labels: cla-signed, maintenance

#11378 Document PostgreSQL type mapping
  docs/src/main/sphinx/connector/postgresql.rst
Labels: cla-signed, docs

#11270 Add redirection awareness for SHOW GRANTS statement
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
Labels: cla-signed, tests:hive

#11023 Join intermediate tasks for small partitions
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestStageTaskSourceFactory.java
Labels: cla-signed

#11385 Improve PostgreSQL type mapping tests
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#11393 Remove unused import
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
Labels: cla-signed

#11395 Remove extra blank line
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
Labels: cla-signed

#11226 Add redirection awareness for RENAME COLUMN task
  core/trino-main/src/main/java/io/trino/execution/RenameColumnTask.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
Labels: cla-signed, tests:hive

#11240 Test translation of view with namesake column aliases which are differing in case
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Labels: cla-signed, tests:hive

#11229 Add documentation for Delta Lake connector
  docs/src/main/sphinx/connector.rst
  docs/src/main/sphinx/connector/delta-lake.rst
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/static/img/delta-lake.png
  docs/src/main/sphinx/static/trino.css
Labels: cla-signed, docs

#11290 Add Trino 373 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-373.md
Labels: cla-signed, release-notes, WIP, docs

#11382 Improve MySQL type mapping tests
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
Labels: cla-signed

#11392 Replace BigArrays with primitive ones in BigInt aggregation
  core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
Labels: cla-signed

#11399 Migrate most PostgreSQL type mapping tests to SqlDataTypeTest
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#11411 [ CI only] TMP stress test Delta on CI
  .github/workflows/ci.yml
Labels: cla-signed

#11409 Support creating and dropping schema in MongoDB
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorSmokeTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
Labels: cla-signed, docs

#11412 Improve Phoenix type mapping tests
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
Labels: cla-signed

#11014 Support GET method on user info endpoint (oauth)
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
Labels: cla-signed

#11421 Remove table existence check when dropping schema in Memory connector
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
Labels: cla-signed

#11424 Support table comment in MongoDB
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTable.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
Labels: cla-signed, docs

#11418 Ensure that underlying resources of the parquet reader are closed
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeUpdatablePageSource.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOptimizedWriterConnectorSmokeTest.java
Labels: cla-signed

#11426 Remove useless import in TableExecute
  core/trino-parser/src/main/java/io/trino/sql/tree/TableExecute.java
Labels: cla-signed

#11432 Fix flaky testJoinWithEmptyBuildSide
  core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
Labels: cla-signed

#11205 Add intro to Procedure in the Hive connector
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#11433 Fix TestHivePlans after logical merge conflict
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
Labels: cla-signed, test, tests:hive

#11429 Avoid using duplicated link names
  docs/src/main/sphinx/connector/jdbc-type-mapping.fragment
Labels: cla-signed, docs

#11366 Bump AWS SDK version to 1.12.172
  pom.xml
Labels: cla-signed

#11449 Bump postgresql driver to 42.3.3
  pom.xml
Labels: cla-signed

#11451 Bump Apache httpclient to 4.5.13 in Prometheus connector
  plugin/trino-prometheus/pom.xml
Labels: cla-signed

#11301 Update memsql plugin JDBC driver dependency
  docs/src/main/sphinx/connector/memsql.rst
  plugin/trino-memsql/pom.xml
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClientModule.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlPlugin.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestingMemSqlServer.java
  testing/trino-server-dev/etc/catalog/memsql.properties
Labels: cla-signed, docs

#11398 Retained block size improvements
  core/trino-main/src/main/java/io/trino/operator/GroupByIdBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/Block.java
  core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int96ArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/Int96ArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/LazyBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/MapBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/RowBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlockBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleArrayBlockWriter.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleMapBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleMapBlockWriter.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleRowBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/SingleRowBlockWriter.java
  core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockBuilder.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestBlockRetainedSizeBreakdown.java
Labels: cla-signed

#11465 Remove trino-delta-lake dependency on trino-hive-hadoop2
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingHiveConnectorFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingHivePlugin.java
Labels: cla-signed, tests:hive

#11462 Update Jedis client to 4.1.1
  plugin/trino-redis/pom.xml
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisRecordCursor.java
Labels: cla-signed

#11437 Remove incorrect development rule about alphabetizing code
  .github/DEVELOPMENT.md
Labels: cla-signed

#11440 Change return type of trim functions with char argument to varchar
  core/trino-main/src/main/java/io/trino/operator/scalar/StringFunctions.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
Labels: cla-signed

#11474 Add information for connection properties in SingleStore documentation
  docs/src/main/sphinx/connector/memsql.rst
Labels: cla-signed, docs

#11459 Deprecate 'memsql' connector name in MemSQL connector
  docs/src/main/sphinx/connector/memsql.rst
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlPlugin.java
  plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlPlugin.java
Labels: cla-signed, docs

#11453 Check table and view existence in Memory connector
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
Labels: cla-signed

#11457 Support column comments in MongoDB
  docs/src/main/sphinx/connector/mongodb.rst
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoColumnHandle.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java
Labels: cla-signed, docs

#11481 Run BigQuery instance cleaner test against case insensitive project
  plugin/trino-bigquery/pom.xml
Labels: cla-signed

#11480 Mark retry_policy session property as hidden
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
Labels: cla-signed

#11473 Fix flaky testMultiFileTableWithNaNValue test
  core/trino-main/src/main/java/io/trino/testing/assertions/Assert.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java
Labels: cla-signed

#11472 Implement JDBC method getImportedKeys with empty ResultSet
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java
Labels: cla-signed, jdbc

#10625 Fix JDBC Driver.getPropertyInfo() and validate allowed properties
  client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractConnectionProperty.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/NonRegisteringTrinoDriver.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java
Labels: cla-signed, jdbc

#11479 Improve isBlocked logic in DeduplicatingDirectExchangeBuffer
  core/trino-main/src/main/java/io/trino/operator/DeduplicatingDirectExchangeBuffer.java
Labels: cla-signed

#11443 Fix metadata caching with Hive ACID
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/AcidTransactionOwner.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/ForwardingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveTransaction.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java
Labels: cla-signed, tests:hive

#11316 Forbid usage of static inner test classes in TestNG
  plugin/trino-kudu/pom.xml
  testing/trino-testing-services/src/main/java/io/trino/testng/services/ReportInnerTestClasses.java
  testing/trino-testing-services/src/main/resources/META-INF/services/org.testng.ITestNGListener
Labels: cla-signed

#11500 Fix incorrect error message
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Labels: cla-signed

#11495 Update maven to 3.8.5
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#11470 Add documentation for Iceberg Glue catalog
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#11496 Shutdown server threads on server close
  core/trino-main/src/main/java/io/trino/execution/ClusterSizeMonitor.java
  core/trino-main/src/main/java/io/trino/metadata/DiscoveryNodeManager.java
Labels: cla-signed, no-release-notes

#11501 Development guide improvements
  .github/DEVELOPMENT.md
Labels: cla-signed, no-release-notes

#10169 Allow to specify the STS endpoint for hive connector on S3
  docs/src/main/sphinx/connector/hive-s3.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Config.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3ConfigurationInitializer.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestHiveS3Config.java
Labels: cla-signed, docs, tests:hive

#11497 Simplify node listing in FullNodeCapableNodeAllocatorService
  core/trino-main/src/main/java/io/trino/execution/scheduler/FullNodeCapableNodeAllocatorService.java
  core/trino-main/src/main/java/io/trino/metadata/InMemoryNodeManager.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFullNodeCapableNodeAllocator.java
Labels: cla-signed

#11490 Support UInt8, UInt16, UInt32 and UInt64 types in ClickHouse
  docs/src/main/sphinx/connector/clickhouse.rst
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed, docs

#11452 Ensure cached query results are discarded
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
Labels: cla-signed

#11509 Log query state when memory pool leaks detected in tests
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#11417 Add Trino 374 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-374.md
Labels: cla-signed, release-notes, docs

#11530 Add job to cancel docs job when PRs are closed or merged
  .github/workflows/cleanup.yml
Labels: cla-signed, maintenance, no-release-notes

#11485 Process parameters for CREATE SCHEMA
  core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: bug, cla-signed

#11508 Upgrade Alluxio client to 2.7.3
  pom.xml
Labels: cla-signed, tests:hive

#11537 Revert "Update maven to 3.8.5"
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed, maintenance, no-release-notes

#11287 Add client and source tags to resource group documentation
  docs/src/main/sphinx/admin/resource-groups.rst
  docs/src/main/sphinx/installation/jdbc.rst
Labels: cla-signed, docs

#11525 Improve singlestore timestamp precision mapping
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
Labels: cla-signed

#11444 Fix style in Kudu documentation
  docs/src/main/sphinx/connector/kudu.rst
Labels: cla-signed, docs

#11507 Fix formatting
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
Labels: cla-signed

#11563 Fix source file's license header
  core/trino-main/src/main/java/io/trino/cost/DistinctLimitStatsRule.java
Labels: cla-signed

#11557 Rename MemSQL to SingleStore
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClientModule.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreTypeMapping.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestingSingleStoreServer.java
Labels: cla-signed, maintenance, no-release-notes

#11556 Support predicate pushdown on boolean column in MongoDB
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java
Labels: cla-signed

#11468 Test Iceberg Glue API invocation counts
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/GlueMetastoreMethod.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGlueCatalogAccessOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataListing.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergProjectionPushdownPlans.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestMetadataQueryOptimization.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestingIcebergConnectorFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestingIcebergPlugin.java
Labels: cla-signed, tests:hive

#11405 Allow starting Elasticsearch container with VM options in query runner
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchExternalQueryRunner.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchQueryRunner.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearch7ConnectorTest.java
Labels: cla-signed, maintenance, no-release-notes

#11540 Move iceberg maven configuration out of profiles
  plugin/trino-iceberg/pom.xml
Labels: cla-signed, no-release-notes

#11573 Prevent usage of wrong cost calculator before/after AddExchanges
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
Labels: cla-signed

#11572 Extract adjustReplicatedJoinLocalExchangeCost and add TODO
  core/trino-main/src/main/java/io/trino/cost/CostCalculatorUsingExchanges.java
  core/trino-main/src/main/java/io/trino/cost/CostCalculatorWithEstimatedExchanges.java
Labels: cla-signed

#11511 Translate arithmetic to connector expression
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPartialTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java
  core/trino-spi/src/main/java/io/trino/spi/expression/StandardFunctions.java
Labels: cla-signed, tests:hive

#11604 Use potentially redirected target table name in SHOW CREATE TABLE
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
Labels: cla-signed, tests:hive

#11605 Check also for materialized views before dropping Iceberg namespace
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
Labels: cla-signed

#11548 Remove regex usage from Identifier validation
  core/trino-parser/src/main/java/io/trino/sql/tree/Identifier.java
Labels: cla-signed

#11553 Add support for WebIdentityTokenFileCredentialsProvider in exchange spooling
  plugin/trino-exchange/pom.xml
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/ExchangeS3Config.java
  plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/S3FileSystemExchangeStorage.java
  plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/s3/TestExchangeS3Config.java
Labels: cla-signed

#11595 Add Confluent Schema Registry to requirements section
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#11599 Make sure the non-implemented metadata method isn't called
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Labels: cla-signed, maintenance, tests:hive, no-release-notes

#11544 Translate all possible expression conjuncts into connector
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
Labels: enhancement, cla-signed, performance, no-release-notes

#11614 Add drop non empty schema tests
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithDisabledInferSchemaConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithEmptyInferSchemaConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithStandardInferSchemaConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#11562 Use safe cache for Delta Lake Transaction Log
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
Labels: cla-signed

#11389 Use shaded orc-core from trino-hive-apache
  lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java
  lib/trino-orc/src/test/java/io/trino/orc/TestCachingOrcDataSource.java
  lib/trino-orc/src/test/java/io/trino/orc/TestOrcBloomFilters.java
  lib/trino-orc/src/test/java/io/trino/orc/TestOrcReaderPositions.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/CompressionConfigUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/OrcFileRewriter.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/OrcFileWriter.java
  pom.xml
Labels: cla-signed, tests:hive, no-release-notes

#11628 Replace declared IOException with Exception in DeltaLake tests
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatistics.java
Labels: cla-signed, no-release-notes

#11469 Add estimates for filter nodes after an aggregation
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/cost/FilterProjectAggregationStatsRule.java
  core/trino-main/src/main/java/io/trino/cost/StatsCalculatorModule.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
  core/trino-main/src/test/java/io/trino/cost/TestFilterProjectAggregationStatsRule.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
  docs/src/main/sphinx/admin/properties-optimizer.rst
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q04.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q11.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q14.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q16.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q34.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q64.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q73.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q74.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q94.plan.txt
  testing/trino-benchto-benchmarks/src/test/resources/sql/presto/tpch/q18.plan.txt
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchDistributedStats.java
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchLocalStats.java
Labels: cla-signed, docs

#11621 Remove deprecated constructors from ColumnMetadata
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ColumnMetadata.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
Labels: cla-signed

#11633 Add access control to drop_extended_stats and vacuum in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/DropExtendedStatsProcedure.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Labels: cla-signed

#11049 Describe allow-* properties in Hive and Cassandra
  docs/src/main/sphinx/connector/cassandra.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs, no-release-notes

#11582 Fix JDBC case insensitive schema mapping documentation
  docs/src/main/sphinx/connector/jdbc-case-insensitive-matching.fragment
Labels: cla-signed, docs, no-release-notes

#11626 Remove redundant test cleanup
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed, test, no-release-notes

#11627 Remove redundant createIcebergQueryRunner overloads
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergDynamicPartitionPruningTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGlueCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, test, no-release-notes

#11616 Fix PostgreSQL deleting too much with complex predicates
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/QueryBuilder.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, tests:hive

#11607 Increase test coverage for Hive S3 streaming upload
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Labels: cla-signed, tests:hive

#11641 Fix code comment reference to a session property
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchDistributedStats.java
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchLocalStats.java
Labels: cla-signed

#11623 Add processed input bytes and rows to event listener QueryStatistics
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
Labels: cla-signed

#11592 Increase Hive metastore timeout in tests based on BaseTestHiveOnDataLake
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingMetastoreLocator.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
Labels: cla-signed, tests:hive

#11651 Add test class progress logging on CI
  testing/trino-testing-services/src/main/java/io/trino/testng/services/ProgressLoggingListener.java
Labels: cla-signed, no-release-notes

#11512 Avoid the usage of specific column names in Glue filter expression
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed, tests:hive

#11549 Add Delta dynamic filtering tests
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDynamicFiltering.java
Labels: cla-signed, test, no-release-notes

#11241 Fix reading Iceberg $manifests table when contains_nan is NULL
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ManifestsTable.java
Labels: cla-signed

#11618 Replace for instance with for example
  docs/src/main/sphinx/connector/elasticsearch.rst
  docs/src/main/sphinx/connector/prometheus.rst
  docs/src/main/sphinx/language/types.rst
Labels: cla-signed, docs

#11644 Return 0 instead of row count in Cassandra completed bytes
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java
Labels: cla-signed

#11680 Disable failing test in Kudu connector
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithDisabledInferSchemaConnectorTest.java
Labels: cla-signed, no-release-notes

#11539 Improve exception handling for `CREATE TABLE` task
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/NotADeltaLakeTableException.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergErrorCode.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/UnknownTableTypeException.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java
Labels: cla-signed, tests:hive

#11656 Clarify documentation of the Oracle connection-url string
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#11683 Fix a typo in BlockBuilder
  core/trino-spi/src/main/java/io/trino/spi/block/BlockBuilder.java
Labels: cla-signed

#11276 Add debug log to BigQuery ReadRowsHelper
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadRowsHelper.java
Labels: cla-signed, no-release-notes

#11681 Add missing support for LongTimeWithTimeZone in InMemoryRecordSet
  core/trino-spi/src/main/java/io/trino/spi/connector/InMemoryRecordSet.java
  core/trino-spi/src/main/java/io/trino/spi/type/LongTimeWithTimeZone.java
Labels: cla-signed

#11678 Fix flaky testWriteDifferentSizes
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Labels: cla-signed, tests:hive
