Repository trinodb/trino, pull requests merged in 2022-10, with the labels that each got.

#14309 Pre-size projection BlockBuilder to the exact size needed
  core/trino-main/src/main/java/io/trino/operator/project/GeneratedPageProjection.java
Labels: cla-signed, performance

#14416 Fix broken test-other-modules step in ci.yml
  .github/workflows/ci.yml
Labels: cla-signed, no-release-notes

#14421 Fix typos in HashGenerationOptimizer
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/HashGenerationOptimizer.java
Labels: cla-signed, no-release-notes

#14311 Address leftover comments for pinot timestamp type tests from PR #14244
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java
Labels: cla-signed

#14399 Improve Pinot broker query failure message
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java
Labels: cla-signed, no-release-notes

#14417 Avoid putting config object to field in BigQueryClientFactory
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClientFactory.java
Labels: cla-signed, no-release-notes

#14418 Support writing ARRAY and ROW types in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeUtils.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java
Labels: cla-signed

#14350 Remove limits on domain-compaction-threshold in clickhouse and phoenix
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/sqlserver.rst
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed, docs

#14410 Add type mapping section to Kudu connector
  docs/src/main/sphinx/connector/kudu.rst
Labels: cla-signed, docs

#14106 Improve type mapping docs for Pinot connector
  docs/src/main/sphinx/connector/pinot.rst
Labels: cla-signed, ready to merge, docs

#14397 Increase timeout for testStatsBasedRepartitionData in Iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#14351 Fix Hudi query runners
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java
Labels: cla-signed

#14403 Ensure Glue configuration isn't bound in Iceberg when Glue not in use
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
Labels: cla-signed, no-release-notes

#14437 Use helper for getting Stream from Iterable
  client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/StaticMetastoreConfig.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConfig.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryConfig.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorConfig.java
Labels: cla-signed, jdbc, tests:hive

#14153 Allow for extension of `delta.security` access controls
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeAccessControlMetadataFactory.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSecurityConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSecurityModule.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSecurityConfig.java
Labels: cla-signed

#14388 Remove deprecated legacy row to json cast
  core/trino-main/src/main/java/io/trino/FeaturesConfig.java
  core/trino-main/src/main/java/io/trino/metadata/SystemFunctionBundle.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayToJsonCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MapToJsonCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/RowToJsonCast.java
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperatorsLegacy.java
  core/trino-main/src/test/java/io/trino/type/TestMapOperatorsLegacy.java
  core/trino-main/src/test/java/io/trino/type/TestRowOperatorsLegacy.java
Labels: cla-signed

#14274 Clarify use of groups field for OAuth2
  docs/src/main/sphinx/security/oauth2.rst
Labels: cla-signed, docs

#14155 Review Kafka connector doc for grammar issues
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#13942 Add type mapping section to Prometheus connector
  docs/src/main/sphinx/connector/prometheus.rst
Labels: cla-signed, docs, no-release-notes

#14286 Fix escaping in metadata calls to SQL Server driver
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Labels: cla-signed

#12434 Document Parquet writer configuration properties
  docs/src/main/sphinx/connector/delta-lake.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#13752 Update type mapping for Iceberg connector
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#14380 Reduce overheads in SliceSerialization
  core/trino-main/src/main/java/io/trino/server/SliceSerialization.java
Labels: cla-signed

#14446 When access denied add cause
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#13052 Remove references to defunct presto-accumulo tools repository
  docs/src/main/sphinx/connector/accumulo.rst
Labels: cla-signed, docs, no-release-notes

#14398 Add option to force S3 region to connect to
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Config.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3ConfigurationInitializer.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestHiveS3Config.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#14443 Cache Iceberg stats within query scope
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
Labels: enhancement, cla-signed, performance

#14212 Make TrinoS3StagingOutputStream allocate its buffer lazily
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#14474 OperatorFactories: remove unnecessary modifiers
  core/trino-main/src/main/java/io/trino/operator/OperatorFactories.java
Labels: cla-signed

#14479 Remove redundant Optional::get in SqlFormatter
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
Labels: cla-signed

#14318 Simplify regexp to TrinoServer
  core/trino-server-main/src/main/java/io/trino/server/TrinoServer.java
Labels: cla-signed, no-release-notes

#14480 Document S3 region configuration property
  docs/src/main/sphinx/connector/hive-s3.rst
Labels: cla-signed, docs

#14473 Support writing timestamp type in BigQuery
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeUtils.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java
Labels: cla-signed, docs

#14469 Fix partitioning preference derivation for UnionNode
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#14221 Fix PTF support in TestingAccessControlManager
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
Labels: cla-signed

#14400 Expose stage buffer utilization distribution to event listener
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
  plugin/trino-http-event-listener/pom.xml
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
Labels: cla-signed

#14302 Handle expression FunctionCall OrderBy rewrites
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
Labels: cla-signed

#14488 Fix support for window aggregates from plugins
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestAccumulatorCompiler.java
Labels: cla-signed

#14133 Add helm chart documentation
  docs/src/main/sphinx/admin/properties-resource-management.rst
  docs/src/main/sphinx/conf.py
  docs/src/main/sphinx/installation.rst
  docs/src/main/sphinx/installation/containers.rst
  docs/src/main/sphinx/installation/kubernetes.rst
Labels: cla-signed, docs

#14477 Add Trino 399 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-399.md
Labels: cla-signed, release-notes, docs

#14511 Enable Delta Lake tests about partition ordering
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Labels: cla-signed, no-release-notes

#14512 Reuse `TypeOperators` instance from `TypeManager` in IcebergMetadataFactory
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
Labels: cla-signed

#14498 Use QueryResult#getOnlyValue in trino-product-tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestFunctions.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestSqlCancel.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAbfsSyncPartitionMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestComments.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompression.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePartitionProcedures.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergOptimize.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/util/IcebergTestUtils.java
Labels: cla-signed, tests:hive, no-release-notes

#14483 Fix session property documentation for writer scaling
  docs/src/main/sphinx/admin/properties-writer-scaling.rst
Labels: docs

#14466 Include dictionaryLookBack size in MultiChannelGroupByHash size
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
Labels: cla-signed

#14475 Don't keep mutable config instance on a field
  core/trino-main/src/main/java/io/trino/execution/warnings/DefaultWarningCollector.java
  core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/TestingWarningCollector.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/rubix/RubixModule.java
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListener.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisRecordSet.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisRecordSetProvider.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisTableDescriptionSupplier.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisJedisManager.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisRecordCursor.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisSplitManager.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableDescriptionSupplier.java
  service/trino-verifier/src/main/java/io/trino/verifier/Verifier.java
Labels: cla-signed, maintenance, tests:hive, no-release-notes

#14520 Remove redundant repetition in Iceberg docs
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#14522 Fix typo in Delta MetadataEntry field name
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java
Labels: cla-signed

#14490 Document `drop_extended_stats` procedure and `analyze` statement in Iceberg
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs, no-release-notes

#14513 Disallow writing to Delta Lake tables with generated columns
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes

#14180 Fix typo in TypeOperators
  core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
Labels: cla-signed, no-release-notes

#14524 Update RPM docs with a link to Helm docs
  docs/src/main/sphinx/installation/rpm.rst
Labels: cla-signed, docs, no-release-notes

#14191 Add checkCanGrantExecuteFunctionPrivilege to ConnectorAccessControl
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Labels: cla-signed, tests:hive

#13015 Add support for pinot proxy
  docs/src/main/sphinx/connector/pinot.rst
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcServerQueryClientConfig.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotProxyGrpcRequestBuilder.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConfig.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotGrpcServerQueryClientConfig.java
Labels: cla-signed, docs

#14177 Fix losing expose ports for connectors on local environments
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/TestContainers.java
Labels: cla-signed

#14536 Typo in authentication
  docs/src/main/sphinx/security/certificate.rst
Labels: docs

#14470 Add explicit check for modifying data in delta table with CDF enabled
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Labels: cla-signed, tests:hive

#14523 Cache short decimal type instances
  core/trino-spi/src/main/java/io/trino/spi/type/DecimalType.java
  core/trino-spi/src/main/java/io/trino/spi/type/ShortDecimalType.java
Labels: cla-signed, no-release-notes

#14386 Handle ThriftMetastore release lock failure which corrupts the Iceberg table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestIcebergHiveMetastoreTableOperationsReleaseLockFailure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestingIcebergHiveMetastoreCatalogModule.java
Labels: cla-signed, tests:hive

#14272 Call sp_rename as prepared statement
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Labels: cla-signed

#14548 Use `TimeZoneKey#getZoneId` directly in OracleClient
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
Labels: cla-signed, no-release-notes

#14395 Decrease a lock contention in PipelinedStageExecution
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
Labels: cla-signed

#14541 Always run all product tests on master
  .github/workflows/ci.yml
Labels: cla-signed

#14494 Support `TRUNCATE TABLE` statement in BigQuery
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
Labels: cla-signed, docs

#14555 Convert types to sealed classes where possible
  core/trino-spi/src/main/java/io/trino/spi/type/DecimalType.java
  core/trino-spi/src/main/java/io/trino/spi/type/LongTimeWithTimeZoneType.java
  core/trino-spi/src/main/java/io/trino/spi/type/LongTimestampWithTimeZoneType.java
  core/trino-spi/src/main/java/io/trino/spi/type/ShortTimeWithTimeZoneType.java
  core/trino-spi/src/main/java/io/trino/spi/type/ShortTimestampWithTimeZoneType.java
  core/trino-spi/src/main/java/io/trino/spi/type/TimeWithTimeZoneType.java
  core/trino-spi/src/main/java/io/trino/spi/type/TimestampWithTimeZoneType.java
Labels: cla-signed

#14518 Test setting S3 region explicitly
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/containers/HiveMinioDataLake.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3WrongRegionPicked.java
Labels: cla-signed, tests:hive

#14550 Simplify TimeZoneKey to ZoneId conversion
  core/trino-main/src/test/java/io/trino/operator/scalar/TestDateTimeFunctions.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTypeMapping.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTypeMapping.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreTypeMapping.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
Labels: cla-signed, no-release-notes

#14558 Rename `verifySupportsInsert` to `skipUnlessInsertsSupported` in Delta Lake
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Labels: cla-signed, no-release-notes

#14396 Print stage output buffer utilization in EXPLAIN ANALYZE VERBOSE
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/TestDistributedFaultTolerantEngineOnlyQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed

#14571 Add a maximum size to the Delta Lake metadata cache
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
Labels: cla-signed

#14559 Add AggregationNode.hasSingleGlobalAggregation
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DecorrelateInnerUnnestWithGlobalAggregation.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DecorrelateLeftUnnestWithGlobalAggregation.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveEmptyGlobalAggregation.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/QueryCardinalityUtil.java
  core/trino-main/src/main/java/io/trino/sql/planner/plan/AggregationNode.java
Labels: cla-signed

#13753 Add documentation for Hudi connector
  docs/src/main/sphinx/connector.rst
  docs/src/main/sphinx/connector/hudi.rst
  docs/src/main/sphinx/static/img/hudi.png
Labels: cla-signed, docs

#14600 Document delta.metadata.cache-size configuration property
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed

#14599 Document hive.max-partitions-for-eager-load configuration property
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed

#14556 Add Trino 400 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-400.md
Labels: cla-signed, release-notes, docs

#14604 Fix JSON serialization of QueryCompletedEvent
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
  plugin/trino-http-event-listener/pom.xml
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
Labels: cla-signed, RELEASE-BLOCKER

#14614 Use JDK 17 based image for Server IT
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
Labels: cla-signed

#14504 Avoid reading Iceberg column stats when they are not needed
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed

#14574 Track active requests in S3FileSystemExchangeStorage
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3AsyncClientWrapper.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorageStats.java
Labels: cla-signed

#14608 Add release notes entry for blocker issue
  docs/src/main/sphinx/release/release-400.md
Labels: cla-signed, release-notes, docs

#14624 Use correct variable for event name in CI
  .github/workflows/ci.yml
Labels: cla-signed

#14621 Obtain stage state after task is added to finished of flushing list
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
Labels: cla-signed

#14616 Fix merge(qdigest) function
  core/trino-main/src/main/java/io/trino/operator/aggregation/MergeQuantileDigestFunction.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#14626 Update Trino 400 release notes
  docs/src/main/sphinx/release/release-400.md
Labels: cla-signed, release-notes, docs

#14610 Add `ALTER TABLE` statement to Iceberg trailing slash test
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
Labels: cla-signed

#14612 Don't overwrite reader and writer versions during `COMMENT` and `ADD COLUMN` in Delta
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Labels: cla-signed, tests:hive

#13558 Document SQL Support for the Iceberg connector
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#14560 Remove deprecated constructors from JdbcTypeHandle
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTypeHandle.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
Labels: cla-signed, no-release-notes

#14630 Increase startup attempts to 3 for Pinot containers
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
Labels: cla-signed

#14596 Display buffer duration in EXPLAIN ANALYZE VERBOSE
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed

#14633 Add note about extra TDigestHistogram properties
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java
Labels: cla-signed

#14615 Fix flaky TestS3WrongRegionPicked.testS3WrongRegionSelection
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3WrongRegionPicked.java
Labels: cla-signed, tests:hive

#14506 Add link to Databricks type support in Delta Lake connector docs
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#12104 Add more tests for modulo pushdown in PostgreSQL
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
Labels: cla-signed, test, no-release-notes

#14525 Bump minio Docker image to `RELEASE.2022-10-05T14-58-27Z`
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java
Labels: cla-signed

#14647 Fix typo in access control docs
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed

#14642 Avoid trying to create directory twice
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Labels: cla-signed

#14643 Fix JdbcTableHandle.isSynthetic for expression-based pushdown
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTableHandle.java
Labels: cla-signed, no-release-notes

#14592 Clarify ConnectorMetadata listing when schema name not found
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
Labels: cla-signed, no-release-notes

#14644 Load value once after expiration in EvictableCache
  lib/trino-collect/src/main/java/io/trino/collect/cache/EvictableCache.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableCache.java
  lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableLoadingCache.java
Labels: cla-signed

#14385 Add details about explain plan generation
  docs/src/main/sphinx/sql/explain.rst
Labels: cla-signed, docs

#13608 Clean up optimization docs & add syntactic join ordering section
  docs/src/main/sphinx/optimizer/cost-based-optimizations.rst
Labels: cla-signed, docs

#14585 Fix analyze iceberg table with an uppercase column name
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#14640 Report operator blocked time distribution in EXPLAIN ANALYZE VERBOSE
  core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorOperatorAdapter.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorSourceOperatorAdapter.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed

#14635 Do not compare finished and all tasks sets eagerly
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
Labels: cla-signed

#14442 Add Azure to FTE exchange manager docs
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#13874 Add type mapping section to Accumulo connector
  docs/src/main/sphinx/connector/accumulo.rst
Labels: cla-signed, docs

#13830 Style edits for OIDC warning
  docs/src/main/sphinx/security/oauth2.rst
Labels: cla-signed, docs

#14084 Add decimal type handling fragment to appropriate connectors
  docs/src/main/sphinx/connector/decimal-type-handling.fragment
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/postgresql.rst
Labels: cla-signed, docs

#14665 Rename "Wall time distribution" to "Scheduled time distribution"
  core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Labels: cla-signed

#14577 Fix NPE when Glue Table parameters are null
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed

#13688 Compile all commits of a PR branch
  .github/workflows/ci.yml
  docs/build
Labels: cla-signed, docs, no-release-notes

#14542 Remove PlanMatchPattern join overloading by builder
  core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestAddDynamicFilterSource.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDereferencePushDown.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDynamicFilter.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPlanMatchingFramework.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPredicatePushdown.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPredicatePushdownWithoutDynamicFilter.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestQuantifiedComparison.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/JoinMatcher.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestEliminateCrossJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestOptimizeDuplicateInsensitiveJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneJoinChildrenColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneJoinColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushAggregationThroughOuterJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDownDereferencesRules.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushInequalityFilterExpressionBelowJoinRuleSet.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushLimitThroughOuterJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPartialAggregationThroughJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionThroughJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNThroughOuterJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReorderJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedDistinctAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedDistinctAggregationWithoutProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithoutProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGroupedAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGroupedAggregationWithoutProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedJoinToJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformFilteringSemiJoinToInnerJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformUncorrelatedSubqueryToJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestUseNonPartitionedJoinLookupSource.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateCrossJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestFullOuterJoinWithCoalesce.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestMergeWindows.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestUnaliasSymbolReferences.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestWindow.java
  core/trino-main/src/test/java/io/trino/sql/query/TestJoin.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSpatialJoinPlanning.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergProjectionPushdownPlans.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestJoinReorderingWithJoinPushdown.java
Labels: cla-signed, tests:hive

#14666 Compare set sizes in order to determine if stage is flushing
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
Labels: cla-signed

#14638 Expose stage buffer utilization distribution to event listener
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageOutputBufferUtilization.java
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
Labels: cla-signed

#14695 Ensure TestHiveMerge table names are unique
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java
Labels: cla-signed, tests:hive

#14678 Update Iceberg from 0.14.1 to 1.0.0
  pom.xml
Labels: cla-signed, no-release-notes

#14687 Don't run testTrinoPreservesReaderAndWriterVersions in Databricks 7.3
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes

#14707 Document exchange.s3.path-style-access configuration property
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#14660 Increase writer count in tests
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard-multinode/multinode-master-config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard-multinode/multinode-worker-config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard/config.properties
Labels: cla-signed, test, tests:hive, no-release-notes

#14668 Filter out fully acknowledged split assignments
  core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java
Labels: cla-signed

#7734 handle InvalidCodePointException and add a testcase
  core/trino-main/src/main/java/io/trino/operator/scalar/CharacterStringCasts.java
  core/trino-main/src/test/java/io/trino/type/TestCharacterStringCasts.java
Labels: cla-signed

#14716 Add shutdown method to ExchangeManager lifecycle
  core/trino-main/src/main/java/io/trino/exchange/ExchangeManagerRegistry.java
  core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeManager.java
Labels: cla-signed

#13713 Add table functions support to File-based access control
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AccessControlRules.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/CatalogFunctionAccessControlRule.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlRules.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FunctionAccessControlRule.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/resources/disallow-function-rule-combination-without-table.json
  lib/trino-plugin-toolkit/src/test/resources/disallow-function-rule-combination.json
  lib/trino-plugin-toolkit/src/test/resources/empty-functions-kind.json
  lib/trino-plugin-toolkit/src/test/resources/file-based-disallow-function-rule-combination-without-table.json
  lib/trino-plugin-toolkit/src/test/resources/file-based-disallow-function-rule-combination.json
  lib/trino-plugin-toolkit/src/test/resources/file-based-system-access-visibility.json
  lib/trino-plugin-toolkit/src/test/resources/file-based-system-no-access.json
  lib/trino-plugin-toolkit/src/test/resources/no-access.json
  lib/trino-plugin-toolkit/src/test/resources/visibility.json
  testing/trino-tests/src/test/java/io/trino/security/TestFunctionsInViewsWithFileBasedSystemAccessControl.java
  testing/trino-tests/src/test/resources/file-based-system-functions-access.json
Labels: cla-signed

#14625 Add Hive IBM Cloud Object Storage support
  docs/src/main/sphinx/connector/hive-cos.rst
  docs/src/main/sphinx/connector/hive.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/CosConfigurationInitializer.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/CosServiceConfigurationProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/HiveCosModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/HiveCosServiceConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/ServiceConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/TrinoCosFileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/cos/TestHiveCosServiceConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/cos/TestHiveCosServiceConfigurationProvider.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/cos/TestServiceConfig.java
Labels: cla-signed, docs, tests:hive

#14607 Add support for x-apigw-api-id request header in Glue
  docs/src/main/sphinx/connector/hive.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/ProxyApiRequestHandler.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
Labels: cla-signed, docs, tests:hive

#14426 Allow creating tables with avro.schema.literal
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/MetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestAvroSchemaEvolution.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaLiteral.java
Labels: cla-signed, tests:hive

#14463 Use table-level SerDe parameter for Avro partitions
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/MetastoreUtil.java
Labels: cla-signed, tests:hive

#14438 Remove redundant modifier strictfp on Java 17
  core/trino-main/src/main/java/io/trino/type/DoubleOperators.java
Labels: cla-signed, no-release-notes

#14731 Document MySQL and PostgreSQL support for fault tolerant execution
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#14036 Improve documentation for PostgreSQL predicate pushdown support
  docs/src/main/sphinx/connector/postgresql.rst
Labels: cla-signed, docs

#14551 Update RPM docs warning about support
  docs/src/main/sphinx/installation/rpm.rst
Labels: cla-signed, docs

#14671 Remove unsupported Hudi w/ Hive setup docs
  docs/src/main/sphinx/connector/hudi.rst
Labels: cla-signed, docs

#14297 Add verification step for HTTPS/TLS docs
  docs/src/main/sphinx/security/overview.rst
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#14723 Rename ForwardingConnection delegate method
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingConnection.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/LazyConnectionFactory.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseConnectionFactory.java
Labels: cla-signed, no-release-notes

#14728 Fail on unsupported schema property in Iceberg catalogs
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
Labels: cla-signed, no-release-notes

#14724 Remove unnecessary pattern matching in testShowCreateTable
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/BaseHudiConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#14572 Report HashBuilderOperator stat for join build-side in EXPLAIN ANALYZE
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStatsSummarizer.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TextRenderer.java
Labels: cla-signed

#14115 Add columns from input tables to table function returned relation type
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed, docs

#14646 Improve type mapping documentation for Kafka connector
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#14629 Add test to ensure consistency of generated column and CDF in Delta
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Labels: cla-signed, tests:hive

#14759 Fix milestone worfklow
  .github/workflows/milestone.yml
Labels: cla-signed

#14727 Append a slash to DeltaLake splits' path only when necessary
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Labels: cla-signed

#14744 Fix IDE warnings in trino caches
  lib/trino-collect/src/main/java/io/trino/collect/cache/ElementTypesAreNonnullByDefault.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/EmptyCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/EvictableCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/EvictableCacheBuilder.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonEvictableCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonKeyEvictableCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonKeyEvictableCacheImpl.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonKeyEvictableLoadingCache.java
  lib/trino-collect/src/main/java/io/trino/collect/cache/NonKeyEvictableLoadingCacheImpl.java
Labels: cla-signed, no-release-notes

#13225 Update Sphinx version
  docs/Dockerfile
  docs/build
  docs/requirements.in
  docs/requirements.txt
  docs/src/main/sphinx/conf.py
  docs/src/main/sphinx/docutils.conf
Labels: cla-signed, docs, no-release-notes

#14675 Add Trino 401 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-401.md
Labels: cla-signed, release-notes, docs

#14737 Upgrade Hudi 0.12.1 for the connector
  plugin/trino-hudi/pom.xml
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java
Labels: cla-signed, no-release-notes, hudi

#14778 Fix links in 401 release notes
  docs/src/main/sphinx/release/release-401.md
Labels: cla-signed

#14766 Document the DML operations support on GCS
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#14590 Add test for `vacuum` procedure with CDF table in Delta
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes
