Repository trinodb/trino, pull requests merged in 2022-01, with the labels that each got.

#10442 Update examples for FROM_UNIXTIME_NANOS
  docs/src/main/sphinx/functions/datetime.rst
Labels: cla-signed, docs

#10448 Add link to the trino-example-http connector source code
  docs/src/main/sphinx/develop/example-http.rst
Labels: cla-signed, docs

#10443 Increase docs-checks timeout to 45 minutes
  .github/workflows/docs.yml
Labels: cla-signed

#10439 Update iceberg catalog configuration for development
  testing/trino-server-dev/etc/catalog/iceberg.properties
Labels: cla-signed

#10241 Remove SerializedPage
  core/trino-main/src/main/java/io/trino/execution/buffer/ArbitraryOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/BroadcastOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/BufferResult.java
  core/trino-main/src/main/java/io/trino/execution/buffer/ClientBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/LazyOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/OutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/PageCodecMarker.java
  core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerde.java
  core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerdeUtil.java
  core/trino-main/src/main/java/io/trino/execution/buffer/PartitionedOutputBuffer.java
  core/trino-main/src/main/java/io/trino/execution/buffer/SerializedPage.java
  core/trino-main/src/main/java/io/trino/execution/buffer/SerializedPageReference.java
  core/trino-main/src/main/java/io/trino/operator/DeduplicationExchangeClientBuffer.java
  core/trino-main/src/main/java/io/trino/operator/ExchangeClient.java
  core/trino-main/src/main/java/io/trino/operator/ExchangeClientBuffer.java
  core/trino-main/src/main/java/io/trino/operator/ExchangeOperator.java
  core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
  core/trino-main/src/main/java/io/trino/operator/MergeOperator.java
  core/trino-main/src/main/java/io/trino/operator/StreamingExchangeClientBuffer.java
  core/trino-main/src/main/java/io/trino/operator/output/DefaultPagePartitioner.java
  core/trino-main/src/main/java/io/trino/operator/output/TaskOutputOperator.java
  core/trino-main/src/main/java/io/trino/server/PagesResponseWriter.java
  core/trino-main/src/main/java/io/trino/server/TaskResource.java
  core/trino-main/src/main/java/io/trino/server/protocol/Query.java
  core/trino-main/src/main/java/io/trino/spiller/FileSingleStreamSpiller.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManager.java
  core/trino-main/src/test/java/io/trino/execution/buffer/BenchmarkBlockSerde.java
  core/trino-main/src/test/java/io/trino/execution/buffer/BenchmarkPagesSerde.java
  core/trino-main/src/test/java/io/trino/execution/buffer/BufferTestUtils.java
  core/trino-main/src/test/java/io/trino/execution/buffer/TestBroadcastOutputBuffer.java
  core/trino-main/src/test/java/io/trino/execution/buffer/TestClientBuffer.java
  core/trino-main/src/test/java/io/trino/execution/buffer/TestPartitionedOutputBuffer.java
  core/trino-main/src/test/java/io/trino/execution/buffer/TestingPagesSerdeFactory.java
  core/trino-main/src/test/java/io/trino/operator/MockExchangeRequestProcessor.java
  core/trino-main/src/test/java/io/trino/operator/TestDeduplicationExchangeClientBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestExchangeClient.java
  core/trino-main/src/test/java/io/trino/operator/TestHttpPageBufferClient.java
  core/trino-main/src/test/java/io/trino/operator/TestStreamingExchangeClientBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestingExchangeClientBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestingExchangeHttpClientHandler.java
  core/trino-main/src/test/java/io/trino/operator/output/BenchmarkPartitionedOutputOperator.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPartitionedOutputOperator.java
  core/trino-main/src/test/java/io/trino/spiller/TestBinaryFileSpiller.java
  core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpiller.java
  core/trino-main/src/test/java/io/trino/spiller/TestSpillCipherPagesSerde.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
Labels: cla-signed

#10458 Remove unused code in Oracle type mapping test
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
Labels: cla-signed, maintenance

#10465 Bump mssql-jdbc driver version
  pom.xml
Labels: cla-signed

#10456 Migrate DataTypeTest to SqlDataTypeTest in MySQL
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
Labels: cla-signed

#10468 Specify MAVEN_INSTALL_OPTS in docs-checks job
  .github/workflows/docs.yml
Labels: cla-signed

#10382 Do not hold on to mutable config object
  core/trino-main/src/main/java/io/trino/cost/TaskCountEstimator.java
Labels: cla-signed

#10309 Test for Hive compatibility across file formats
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/HiveProductTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAllDatatypesFromHiveConnector.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#10478 Add query.max-total-memory-per-task docs
  docs/src/main/sphinx/admin/properties-memory-management.rst
Labels: cla-signed, docs

#10484 Remove beta disclaimer from BigQuery documentation
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#10483 Migrate simple DataTypeTest to SqlDataTypeTest in PostgreSQL
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
Labels: cla-signed

#10488 Revert "Test for Hive compatibility across file formats"
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/HiveProductTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAllDatatypesFromHiveConnector.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#10463 Describe string cast to JSON handling
  docs/src/main/sphinx/functions/json.rst
Labels: cla-signed, docs

#10495 Update MS SQL Server JDBC driver to Java 11 version
  pom.xml
Labels: cla-signed

#10493 Add support for file based security in the iceberg connector
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSecurityConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSecurityModule.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
Labels: cla-signed

#10459 Fix iceberg connector bug not returning external location with `show create table`
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
Labels: cla-signed

#10368 Add reusable smoke test coverage for concurrent UPDATE
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  testing/trino-testing/pom.xml
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#10403 Allow access to Postgres partitioned tables
  docs/src/main/sphinx/connector/postgresql.rst
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#10503 Update to Airbase 119
  core/trino-main/pom.xml
  core/trino-parser/pom.xml
  pom.xml
Labels: cla-signed

#10521 Run git commit id Maven plugin only once
  pom.xml
Labels: cla-signed

#10492 Clarify how decimal duration values are handled
  docs/src/main/sphinx/admin/properties.rst
Labels: cla-signed, docs

#10474 Update ClickHouse driver to 0.3.2-patch1
  plugin/trino-clickhouse/pom.xml
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseConnectionFactory.java
  pom.xml
Labels: cla-signed

#10529 Add test cases to Phoenix type mapping
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java
Labels: cla-signed

#10536 Add test cases to Phoenix5 type mapping
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
Labels: cla-signed

#10530 Use LocalDate and LocalDateTime on ClickHouse type mapping
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#9949 Fix worker OOM
  lib/trino-orc/src/main/java/io/trino/orc/reader/SliceDictionaryColumnReader.java
  lib/trino-orc/src/test/java/io/trino/orc/TestOrcReaderMemoryUsage.java
  lib/trino-orc/src/test/java/io/trino/orc/TestSliceDictionaryColumnReader.java
Labels: cla-signed

#10520 Differentiate failures in asyncRename
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Labels: cla-signed

#10540 Allow connector determine whether failure is recoverable
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed

#10472 Report connector provided read time as connector metric
  core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorSourceOperatorAdapter.java
  core/trino-spi/src/main/java/io/trino/spi/metrics/Timing.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/DurationTiming.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/metrics/TestMetrics.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#10547 Order connectors list alphabetically
  docs/src/main/sphinx/connector.rst
Labels: cla-signed, docs

#10526 Update to airlift 213
  plugin/trino-elasticsearch/pom.xml
  pom.xml
Labels: cla-signed

#10433 Add Trino 368 release notes
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-368.md
Labels: cla-signed, release-notes, docs

#10542 Set keep_alive_timeout as 10 seconds in ClickHouse testing server
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java
  plugin/trino-clickhouse/src/test/resources/custom.xml
Labels: cla-signed, maintenance

#10557 Remove unused code for LIMIT in BigQuery connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTableHandle.java
Labels: maintenance

#10497 Implement Iceberg OPTIMIZE
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnector.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergHandleResolver.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergOptimizeHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergProcedureHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergTableExecuteHandle.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergTableProcedureId.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/OptimizeTableProcedure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
Labels: cla-signed

#10563 Add tests:hive automatically
  .github/config/labeler-config.yml
  .github/workflows/labeler.yml
Labels: cla-signed

#10576 Display duration in most succinct time unit
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/DurationTiming.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/metrics/TestMetrics.java
Labels: cla-signed

#10571 Replace ExtendedSettableFuture with SettableFuture
  core/trino-main/src/main/java/io/trino/execution/buffer/LazyOutputBuffer.java
Labels: cla-signed

#10590 Upgrade benchto driver to version 0.17
  pom.xml
Labels: cla-signed

#10589 Fix flaky testClusterPools
  testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java
Labels: cla-signed

#10516 Improve null statistics handling in product tests
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/StatisticsFetcher.java
Labels: cla-signed

#10597 Add more memory assertions in TestHashAggregationOperator
  core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
Labels: cla-signed

#10498 Test for Hive compatibility across file formats
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/HiveProductTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAllDatatypesFromHiveConnector.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#10570 fix materialized views to allow duplicated source tables without breaking the metadata schema
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java
Labels: cla-signed

#10566 Http Event Listener retry for codes not in [200, 300) and expections, rertry delay calculation fix, better logging
  plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListener.java
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpQueryListener.java
Labels: cla-signed

#10601 Add map_string_as_varchar session property in ClickHouse
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseSessionProperties.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#10608 Error Prone tweaks
  pom.xml
Labels: cla-signed

#10525 Document table statistics property for Hive connector
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#10599 Fix UnsupportedOperationException in max_by and min_by aggregation
  core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxby/AbstractMinMaxBy.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/state/NullableBooleanStateSerializer.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/state/NullableDoubleStateSerializer.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/state/NullableLongStateSerializer.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#10634 Label PRs changing JDBC as such
  .github/config/labeler-config.yml
Labels: cla-signed

#9722 Remove usage of @test with exceptions in plugin tests
  plugin/trino-example-http/src/test/java/io/trino/plugin/example/TestExampleMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#10612 Document ClickHouse connector type mapping
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed, docs

#10611 Map ClickHouse IPv4 and IPv6 types to Trino IPADDRESS type
  docs/src/main/sphinx/connector/clickhouse.rst
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#10480 Add Iceberg $properties system table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableType.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#10605 Make scheduled stages order deterministic
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/policy/TestPhasedExecutionSchedule.java
Labels: cla-signed

#10639 Enable Error Prone check: DoubleBraceInitialization
  pom.xml
Labels: cla-signed

#10617 Implement EvictableCache.asMap()
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/cache/EvictableCache.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/cache/TestEvictableCache.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
Labels: cla-signed

#10609 Forbid fields/variables differing in case only
  core/trino-main/src/test/java/io/trino/operator/BenchmarkWindowOperator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/RcFileFileWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/RecordFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/MetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/StorageFormat.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveLocal.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/AbstractFileFormat.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/alluxio/TestProtoUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueInputConverter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueToTrinoConverter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestingMetastoreObjects.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestampMicros.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveUtil.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestCredentialPassthrough.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlGlobalTransactionMyConnectorSmokeTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsFlywayMigration.java
  pom.xml
Labels: cla-signed, tests:hive

#10643 Label PRs changing docs as such
  .github/config/labeler-config.yml
Labels: cla-signed

#10642 Fix incorrect type mapping docs for ClickHouse
  docs/src/main/sphinx/connector/clickhouse.rst
Labels: cla-signed, docs

#10594 Implement renameSchema for ClickHouse
  docs/src/main/sphinx/connector/clickhouse.rst
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed

#10640 Schedule coordinator stage after creating distributed stages scheduler
  core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
Labels: cla-signed

#10654 Abstain from overriding @BeforeClass init method
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestFailureRecovery.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
Labels: cla-signed

#10656 Properly handle aborted dependent stages in PhasedExecutionSchedule
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/policy/TestPhasedExecutionSchedule.java
Labels: cla-signed

#10401 Ensure HMS shared lock is dropped on query failure
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreStats.java
Labels: cla-signed, tests:hive

#10636 Rename parameter for setSchemaAuthorization
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, tests:hive

#10658 Remove misplaced comments
  core/trino-main/src/main/java/io/trino/sql/planner/LiteralEncoder.java
Labels: cla-signed

#10672 Deny writing unsupported dates in ClickHouse
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#9541 [Pinot connector] Add support for basic authentication
  docs/src/main/sphinx/connector/pinot.rst
  plugin/trino-pinot/pom.xml
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnectorFactory.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationModule.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationProvider.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationType.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotAuthenticationTypeConfig.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotBrokerAuthenticationProvider.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/PinotControllerAuthenticationProvider.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/none/PinotEmptyAuthenticationProvider.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/password/PinotPasswordAuthenticationProvider.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/password/inline/PinotPasswordBrokerAuthenticationConfig.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/password/inline/PinotPasswordControllerAuthenticationConfig.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/MockPinotClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotClient.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotWithoutAuthenticationIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestSecuredPinotIntegrationSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/TestPinotAuthenticationTypeConfig.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/none/TestPinotEmptyAuthenticationProvider.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/password/TestPinotPasswordAuthenticationProvider.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/password/inline/TestPinotPasswordBrokerAuthenticationConfig.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/auth/password/inline/TestPinotPasswordControllerAuthenticationConfig.java
  plugin/trino-pinot/src/test/resources/pinot-broker/pinot-broker-secured.conf
  plugin/trino-pinot/src/test/resources/pinot-controller/pinot-controller-secured.conf
Labels: cla-signed, docs

#10659 Rename failure recover test classes to match convention
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveFailureRecoveryTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFailureRecoveryTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMinioFailureRecoveryTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed, tests:hive

#9938 Support Metrics mode when creating/writing Iceberg tables
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
Labels: cla-signed

#10313 Replace deprecated Guava method createTempDir
  lib/trino-orc/src/test/java/io/trino/orc/BenchmarkColumnReaders.java
  lib/trino-orc/src/test/java/io/trino/orc/BenchmarkOrcDecimalReader.java
  lib/trino-orc/src/test/java/io/trino/orc/TempFile.java
  lib/trino-orc/src/test/java/io/trino/orc/TestStructColumnReader.java
  lib/trino-rcfile/src/test/java/io/trino/rcfile/RcFileTester.java
  plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopHang.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
  plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreWithQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateExternalTable.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateExternalTableDisabled.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/backup/AbstractTestBackupStore.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/backup/TestBackupManager.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/backup/TestFileBackupStore.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/backup/TestHttpBackupStore.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorSplitManager.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestShardCleaner.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestFileStorageService.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestOrcFileRewriter.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestRaptorStorageManager.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestShardEjector.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestShardRecovery.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestShardWriter.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/organization/TestShardCompactor.java
Labels: cla-signed

#10638 Map Oracle date to Trino timestamp(0) type
  docs/src/main/sphinx/connector/oracle.rst
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
Labels: cla-signed, docs

#10664 Fix flaky TestExchangeClient.testAddLocation
  core/trino-main/src/test/java/io/trino/operator/TestExchangeClient.java
Labels: cla-signed

#10683 Extract hive compatibility test
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#10694 Update testcontainers to 1.16.3
  pom.xml
Labels: cla-signed

#10673 Change AccessControl filterCatalogs to have a SecurityContext
  core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
  core/trino-main/src/main/java/io/trino/security/AccessControl.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
  core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
Labels: cla-signed

#10713 Reword Oracle pushdown support
  docs/src/main/sphinx/connector/oracle.rst
Labels: cla-signed, docs

#10668 Add basic TLS configuration info to JDBC connector docs
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#10716 Revert "Pipeline buffering and upload in S3 multi-upload"
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#10581 10007 test row filtering on null column
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorEntities.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java
Labels: cla-signed

#10619 Use force repartitioning for OPTIMIZE for iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#10725 Remove unused caches in BigQueryClient
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
Labels: cla-signed, docs

#10731 Guard against IO resource leak with streams
  core/trino-main/src/main/java/io/trino/server/ServerPluginsProvider.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkGeometryAggregations.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkSpatialJoin.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestBingTileFunctions.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSphericalGeoFunctions.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
Labels: cla-signed

#9906 Refactor Iceberg table statistics to be deterministic
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergStatistics.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTypes.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/Partition.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#10733 Disable testRenameSchema in ClickHouse
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorSmokeTest.java
Labels: cla-signed

#10645 Merge redundant hive cache tests classes
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreQueries.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreWithQueryRunner.java
Labels: cla-signed, tests:hive

#10667 Document partition table statistics for Hive connector
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#10618 Allow MockConnector to support table and schema properties
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: cla-signed

#10700 Use TupleDomain#intersect for List<TupleDomain> in DynamicFilterService
  core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java
Labels: cla-signed

#10744 Cleanup new symbol allocation logic
  core/trino-main/src/main/java/io/trino/sql/planner/SymbolAllocator.java
Labels: cla-signed

#10753 Simplify extensability of BaseHiveConnectorTest
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFaultTolerantExecutionConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePipelinedExecutionConnectorTest.java
Labels: cla-signed, tests:hive

#10729 Pipeline buffering and upload in S3 multi-upload
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
Labels: cla-signed, tests:hive

#10737 Catch overflow in decimal multiplication
  core/trino-main/src/main/java/io/trino/type/DecimalOperators.java
  core/trino-main/src/test/java/io/trino/type/TestDecimalOperators.java
Labels: cla-signed

#10735 Include base credentials for Glue IAM role
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: bug, cla-signed, tests:hive

#10722 Fix parquet data page offset calculation in parquet writer
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
Labels: cla-signed, tests:hive

#10647 Clarify that username is optional
  docs/src/main/sphinx/develop/client-protocol.rst
Labels: cla-signed, docs

#10660 Consider stage balancing only in UniformNodeSelector
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeSchedulerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelector.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelectorFactory.java
  core/trino-main/src/test/java/io/trino/execution/TestNodeSchedulerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java
Labels: cla-signed

#10762 Rename test class
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
Labels: tests:hive

#10738 Update to airlift 214
  pom.xml
Labels: cla-signed

#10553 Add Trino 369 release notes
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-369.md
Labels: cla-signed, release-notes, WIP, docs

#10780 Reuse view owner identity
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzerFactory.java
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  plugin/trino-ml/src/test/java/io/trino/plugin/ml/TestLearnAggregations.java
Labels: cla-signed

#10789 Revert "Reuse view owner identity"
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzerFactory.java
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  plugin/trino-ml/src/test/java/io/trino/plugin/ml/TestLearnAggregations.java
Labels: cla-signed

#10792 Edit hide-inaccessible-columns docs section
  docs/src/main/sphinx/security/overview.rst
Labels: cla-signed, docs

#10796 Change backticks to single quotes
  docs/src/main/sphinx/sql/alter-table.rst
Labels: cla-signed, docs

#10670 Add authorization check options to iceberg doc
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#10751 Support writing timestamp(0) as datetime type in ClickHouse
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#10331 Support DEFAULT in ALTER TABLE...SET PROPERTIES...
  core/trino-main/src/main/java/io/trino/execution/SetPropertiesTask.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/security/AccessControl.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-main/src/main/java/io/trino/sql/NodeUtils.java
  core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlyAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed, tests:hive

#10715 Document scheduling policy config property
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#10813 Close docker networks constructed in tests
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestingDruidServer.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchBackpressure.java
Labels: cla-signed

#10818 Update example of mongodb.connection-url
  docs/src/main/sphinx/connector/mongodb.rst
Labels: cla-signed, docs

#10613 Showcase incompatibilities between optimized parquet writer and hive
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompatibility.java
Labels: cla-signed, tests:hive

#10696 Fix GlueHiveMetastore#batchGetPartition to handle unprocessedKeys
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, tests:hive

#10739 Fix error in Iceberg partition evolution handling
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#10720 Validate literals in expression analyzer
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonFunctions.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/type/TestDateTimeOperators.java
  core/trino-main/src/test/java/io/trino/type/TestIntegerOperators.java
  core/trino-main/src/test/java/io/trino/type/TestIntervalDayTime.java
  core/trino-main/src/test/java/io/trino/type/TestIntervalYearMonth.java
  core/trino-main/src/test/java/io/trino/type/TestJsonOperators.java
  core/trino-main/src/test/java/io/trino/type/TestSmallintOperators.java
  core/trino-main/src/test/java/io/trino/type/TestTinyintOperators.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
  testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#10821 Remove development event listener to avoid log spam
  testing/trino-server-dev/etc/event-listener.properties
Labels: cla-signed

#10819 Relax Hive assertions to work with alternate metastores
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive

#10820 Add configuration to enable single statement writes in Hive
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnector.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Labels: cla-signed, tests:hive

#10665 Remove dangling TODO that links to a resolved issue
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
Labels: cla-signed

#10445 Add Java 17 as not supported
  docs/src/main/sphinx/installation/deployment.rst
Labels: cla-signed, docs

#10838 Cleanup CI jobs for modules
  .github/workflows/ci.yml
Labels: cla-signed

#10798 Deny DML commands within explicit transactions in Hive
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#10749 Fix incorrect date handling in Phoenix 4 & 5
  plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
  plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
Labels: cla-signed

#10858 Do not require registration of handle classes
  core/trino-main/src/main/java/io/trino/connector/ConnectorManager.java
  core/trino-main/src/main/java/io/trino/metadata/HandleResolver.java
  core/trino-main/src/main/java/io/trino/server/PluginManager.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
Labels: cla-signed

#10811 Fix Jwt & OAuth2 authenticators seperation issue
  core/trino-main/src/main/java/io/trino/server/security/jwt/ForJwt.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwkService.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwkSigningKeyResolver.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
Labels: cla-signed

#10575 Increase OrcReader#MAX_BATCH_SIZE to 8196
  lib/trino-orc/src/main/java/io/trino/orc/OrcReader.java
  lib/trino-orc/src/test/java/io/trino/orc/TestReadBloomFilter.java
Labels: cla-signed, tests:hive

#10832 Fully migrate TopNOperator to WorkProcessorOperator
  core/trino-main/src/main/java/io/trino/operator/TopNOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestTopNOperator.java
Labels: cla-signed
