Repository trinodb/trino, pull requests merged in 2023-01, with the labels that each got.

#15544 Update calls to deprecated iceberg Transform and Transforms 's API
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ManifestsTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestPartitionTransforms.java
Labels: cla-signed, no-release-notes

#15573 Compare with true literal appropriately
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed, no-release-notes

#15574 Migrate phased scheduler to Guava graphs
  core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/policy/TestPhasedExecutionSchedule.java
Labels: cla-signed, no-release-notes

#15578 Abort AWS operation retry in AbortedException
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectLineRecordReader.java
Labels: cla-signed, tests:hive

#15565 Move handling of internal retry error when schema already exist for Hive
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateSchemaInternalRetry.java
Labels: cla-signed, tests:hive

#15509 Log when query killed due to lack of task descriptor storage memory
  core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java
Labels: cla-signed

#15550 Add additional checks for authorization field in JdbcTableHandle
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed, no-release-notes

#15554 Account for memory usage of parquet column readers
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BooleanColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ByteColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/DictionaryDecoder.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int96ColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/IntColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/LongColumnAdapter.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ShortColumnAdapter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderBenchmark.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReader.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReaderFactory.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestInt96Timestamp.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderMemoryUsage.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java
Labels: cla-signed, tests:hive

#15498 Implement optimized decoder for RLE encoding in parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/IntBitUnpacker.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/IntBitUnpackers.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/RleBitPackingHybridDecoder.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/DictionaryDecoder.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkReadFixedWidthInt.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderUtils.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderUtilsBenchmarks.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/ApacheParquetIntUnpacker.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/BenchmarkRleBitPackingDecoder.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestBitUnpackers.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestRleBitPackingDecoderBenchmark.java
Labels: cla-signed, tests:hive, performance

#15589 Throw exception instead of returning it
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
Labels: cla-signed

#15602 Update testcontainers to 1.17.6
  pom.xml
Labels: cla-signed, test, no-release-notes

#15497 Move FailureRecovery tests to plugin modules
  .github/workflows/ci.yml
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcFailureRecoveryTest.java
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaTaskFailureRecoveryTest.java
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveFailureRecoveryTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveQueryFailureRecoveryTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTaskFailureRecoveryTest.java
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergQueryFailureRecoveryTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTaskFailureRecoveryTest.java
  plugin/trino-mongodb/pom.xml
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoFailureRecoveryTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoQueryFailureRecoveryTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTaskFailureRecoveryTest.java
  plugin/trino-mysql/pom.xml
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlFailureRecoveryTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlQueryFailureRecoveryTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTaskFailureRecoveryTest.java
  plugin/trino-postgresql/pom.xml
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/BasePostgresFailureRecoveryTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgresQueryFailureRecoveryTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgresTaskFailureRecoveryTest.java
  plugin/trino-sqlserver/pom.xml
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerFailureRecoveryTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerQueryFailureRecoveryTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerTaskFailureRecoveryTest.java
  testing/trino-faulttolerant-tests/pom.xml
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
  testing/trino-testing/src/main/java/io/trino/testing/ExtendedFailureRecoveryTest.java
Labels: cla-signed, tests:hive

#15611 Align extended stats config descriptions in Delta and Iceberg
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
Labels: cla-signed

#15601 Reduce HiveSplit size for ORC, Parquet and RCFile tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
Labels: cla-signed, tests:hive

#15595 Allow setting group provider in tests
  core/trino-main/src/main/java/io/trino/security/GroupProviderManager.java
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/QueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/TestingGroupProviderManager.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/StandaloneQueryRunner.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#15621 Fix typo in iceberg.rst
  docs/src/main/sphinx/connector/iceberg.rst
Labels: docs

#15607 Fix failure when subquery contains time travel
  core/trino-parser/src/main/java/io/trino/sql/tree/QueryPeriod.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed

#15608 Fix query failure for outer join with DFs in fault tolerant execution
  core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestJoinQueries.java
Labels: cla-signed

#15624 Increase memory requirement for tasks failed due to worker crash
  core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/ErrorCodes.java
  core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestExponentialGrowthPartitionMemoryEstimator.java
  core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
Labels: cla-signed

#15632 Adjust GC related settings for tests
  pom.xml
Labels: cla-signed

#15591 Support setting column types in PostgreSQL connector
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcClientStats.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/BaseHudiConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaConnectorTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/BaseRedisConnectorTest.java
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
  plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchConnectorTest.java
Labels: cla-signed, tests:hive

#15647 Fix redundant backquote from HTTP client documentation
  docs/src/main/sphinx/admin/properties-http-client.rst
Labels: cla-signed, docs, no-release-notes

#15640 Fix killing threads in Matcher
  core/trino-main/src/main/java/io/trino/operator/window/matcher/Matcher.java
  core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatching.java
Labels: cla-signed

#15635 Fix failure when analyzing table with no snapshots
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed

#15517 Fix failure when converting json stats to parquet in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Labels: cla-signed

#15642 Fix handling of unknown stats in ScalarStatsCalculator
  core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java
  core/trino-main/src/test/java/io/trino/cost/TestScalarStatsCalculator.java
Labels: cla-signed

#15428 Provide estimates for partial and final topN in TopNStatsRule
  core/trino-main/src/main/java/io/trino/cost/TopNStatsRule.java
  core/trino-main/src/test/java/io/trino/cost/TestTopNStatsRule.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
Labels: cla-signed, tests:hive

#15594 Propagate group information when analyzing row filter and column masks
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#15619 Mark filter() function as deterministic
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayFilterFunction.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestDeterminismEvaluator.java
Labels: cla-signed, no-release-notes

#15618 Remove deprecated checkCanCreateSchema
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Labels: cla-signed, tests:hive, no-release-notes

#15627 Increase number of partitions for bucketed processing in FTE
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningScheme.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningSchemeFactory.java
  core/trino-main/src/main/java/io/trino/sql/planner/MergePartitioningHandle.java
  core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
Labels: cla-signed

#15662 Fix memory accounting in GroupedLongDecimalWithOverflowAndLongState
  core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateFactory.java
Labels: cla-signed

#15675 Update airlift dependency to version 221
  pom.xml
Labels: cla-signed

#15655 Check `rollback_to_snapshot` accuracy when it does not do any changes
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, ready to merge, test, no-release-notes

#15658 Fix inconsistent pageSinkId column naming
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#15693 Avoid PrioritizeSplitRunner CPU user time overhead
  core/trino-main/src/main/java/io/trino/execution/executor/PrioritizedSplitRunner.java
Labels: cla-signed

#15699 Upgrade tempto version to 191
  pom.xml
Labels: cla-signed

#15674 Document ElasticSearch hosts being a list
  docs/src/main/sphinx/connector/elasticsearch.rst
Labels: cla-signed, docs

#15695 Fix outdated comment
  core/trino-main/src/main/java/io/trino/operator/Driver.java
Labels: cla-signed

#15691 Allow hyphen as a valid value for sanitization checks
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
Labels: cla-signed, no-release-notes

#15694 Give better name to S3 log synchronizer: S3 Native
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeS3Module.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
Labels: cla-signed

#15644 Update FTE docs to add HDFS as exchange type
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#15692 Apply sanitization checks only for entity specified in comment-format
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
Labels: cla-signed, no-release-notes

#15698 Fix failure with dynamic pattern in LIKE
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestLikeFunctions.java
Labels: cla-signed

#15169 Mark LocalProperty as sealed
  core/trino-spi/src/main/java/io/trino/spi/connector/LocalProperty.java
Labels: cla-signed

#15718 Use exact math for timestamp calculations
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/type/ShortTimestampEncoder.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/type/TrinoTimestampEncoderFactory.java
Labels: cla-signed

#15706 Fix reading parquet column indexes without nulls count
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
  lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java
Labels: bug, cla-signed, tests:hive

#15681 Support reading float as double in ORC and Parquet for Iceberg type change
  lib/trino-orc/src/main/java/io/trino/orc/reader/FloatColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/FloatColumnReader.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#15719 Extract case insensitive name mapping test in MongoDB
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoCaseInsensitiveMapping.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Labels: cla-signed, no-release-notes

#15725 Remove obsolete check in BigQuery connector
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
Labels: cla-signed, no-release-notes

#15653 Fix incorrect input columns passed to table function
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#15711 Make WorkProcessor#blocking always execute futureSupplier
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorUtils.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessor.java
Labels: cla-signed

#15710 Retry maven when building individual commits
  .github/actions/compile-commit/action.yml
Labels: cla-signed

#15735 Further cleanup of CachingHiveMetastore constructor
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
Labels: cla-signed, tests:hive

#15707 Improve error message when trying to drop partitioned columns in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#15678 Account for current and expanded tables in tryRehash
  core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/GroupByHashYieldAssertion.java
  core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
Labels: cla-signed

#15727 Fix wrong handling for NaN on partitioned columns in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive

#15728 Support reading FLOAT as a double in batched parquet reader
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/TransformingValueDecoders.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingColumnReader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java
Labels: cla-signed, tests:hive

#15739 Fix assignment of environment variable in compile-commit action
  .github/actions/compile-commit/action.yml
Labels: cla-signed, no-release-notes

#15648 Quote column name when setting column comment in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOraclePoolRemarksReportingConnectorSmokeTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#15576 Persist the Trino query ID into the snapshot summary
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalogConnectorTest.java
Labels: cla-signed

#15730 Check each commit code style
  .github/actions/compile-commit/action.yml
Labels: cla-signed, test, no-release-notes, dx

#15720 Use authentication error message from response body
  client/trino-client/src/main/java/io/trino/client/JsonResponse.java
  client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
Labels: cla-signed

#15465 Update docs for connector catalog examples-1
  docs/src/main/sphinx/connector/atop.rst
  docs/src/main/sphinx/connector/googlesheets.rst
  docs/src/main/sphinx/connector/thrift.rst
  docs/src/main/sphinx/connector/tpcds.rst
  docs/src/main/sphinx/connector/tpch.rst
Labels: cla-signed, docs, tests:hive

#15709 Run selected tests with Java 19
  .github/workflows/ci.yml
  core/trino-main/src/main/java/io/trino/dispatcher/DecoratingListeningExecutorService.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
  core/trino-main/src/test/java/io/trino/type/TestDecimalCasts.java
  core/trino-main/src/test/java/io/trino/type/TestMapOperators.java
  testing/trino-testing-services/src/main/java/io/trino/testng/services/ManageTestResources.java
Labels: cla-signed

#15684 Disallow legacy UPDATE/DELETE on Hive ACID tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive

#15673 Remove test timeouts from connector tests
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#15754 Update Joda to 2.12.2
  core/trino-spi/src/main/resources/io/trino/spi/type/zone-index.properties
  core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java
  pom.xml
Labels: cla-signed

#15758 Use Failsafe to retry instead iceberg's Tasks in iceberg connector
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
Labels: cla-signed, no-release-notes

#15759 Javadoc style fixes
  core/trino-main/src/main/java/io/trino/operator/DriverYieldSignal.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/ApproximateMostFrequentHistogram.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ColorFunctions.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/util/HeapTraversal.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExpectedValueProvider.java
  core/trino-spi/src/main/java/io/trino/spi/block/Block.java
  core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMergeSink.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/function/LongVariableConstraint.java
  core/trino-spi/src/main/java/io/trino/spi/function/Signature.java
  core/trino-spi/src/main/java/io/trino/spi/function/TypeVariableConstraint.java
  lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java
  lib/trino-orc/src/main/java/io/trino/orc/stream/LongInputStreamV2.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FilteredRowRangesIterator.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetSchemaConverter.java
  lib/trino-phoenix5-patched/src/main/java/org/apache/phoenix/shaded/org/apache/zookeeper/client/StaticHostProvider.java
  lib/trino-record-decoder/src/main/java/io/trino/decoder/csv/CsvRowDecoder.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/BaseImplementAvgBigint.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizer.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java
  plugin/trino-kudu/src/main/java/org/apache/kudu/client/KuduOperationApplier.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
Labels: cla-signed, tests:hive, no-release-notes

#15569 Account for DF limits per channel in DynamicFilterSourceOperator
  core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestDynamicFilterSourceOperator.java
  testing/trino-tests/src/test/java/io/trino/execution/AbstractTestCoordinatorDynamicFiltering.java
Labels: cla-signed

#15761 Separate BigQuery arrow test
  .github/workflows/ci.yml
Labels: cla-signed

#15783 Rename Iceberg JDBC catalog config class
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java
Labels: cla-signed, no-release-notes

#15799 Add missing synchronization
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java
Labels: cla-signed

#15764 Improve LookupSource memory accounting
  core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
  core/trino-main/src/main/java/io/trino/operator/PagesRTreeIndex.java
  core/trino-main/src/main/java/io/trino/operator/PagesSpatialIndexSupplier.java
  core/trino-main/src/main/java/io/trino/operator/SimplePagesHashStrategy.java
  core/trino-main/src/main/java/io/trino/operator/StreamingAggregationOperator.java
  core/trino-main/src/main/java/io/trino/operator/join/BigintPagesHash.java
  core/trino-main/src/main/java/io/trino/operator/join/DefaultPagesHash.java
  core/trino-main/src/main/java/io/trino/operator/join/JoinHashSupplier.java
  core/trino-main/src/main/java/io/trino/operator/join/JoinUtils.java
  core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java
  core/trino-main/src/test/java/io/trino/operator/TestPagesIndex.java
  core/trino-main/src/test/java/io/trino/operator/TestSimplePagesHashStrategy.java
  core/trino-main/src/test/java/io/trino/operator/join/TestPositionLinks.java
  core/trino-main/src/test/java/io/trino/sql/gen/TestJoinCompiler.java
Labels: cla-signed

#15796 Fix result when complex type contains user defined type in Cassandra
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed

#15767 Introduce CachingHiveMetastoreBuilder
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
Labels: cla-signed, tests:hive

#15804 Fix insert into BigQuery tables
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
Labels: cla-signed, RELEASE-BLOCKER

#15805 Wait until created tables become visible in Cassandra tests
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed, no-release-notes

#15686 Add metric to measure requests duration of HttpPageBufferClient
  core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java
  core/trino-main/src/main/java/io/trino/operator/DirectExchangeClientStatus.java
  core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
  core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java
Labels: cla-signed

#15530 Update docs for connector catalog examples-3
  docs/src/main/sphinx/connector/delta-lake.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/elasticsearch.rst
  docs/src/main/sphinx/connector/hudi.rst
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/connector/table-redirection.fragment
Labels: cla-signed, docs

#15599 Update docs for connector catalog examples-5
  docs/src/main/sphinx/connector/alter-table-limitation.fragment
  docs/src/main/sphinx/connector/mariadb.rst
  docs/src/main/sphinx/connector/memory.rst
  docs/src/main/sphinx/connector/mongodb.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/pinot.rst
Labels: cla-signed, docs

#15600 Update docs for connector catalog examples-6
  docs/src/main/sphinx/connector/memsql.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/prometheus.rst
  docs/src/main/sphinx/connector/redis.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#14768 Add description to keystore and truststore types
  docs/src/main/sphinx/client/cli.rst
Labels: cla-signed, docs

#15623 Add parquet.max-read-block-row-count property
  docs/src/main/sphinx/connector/delta-lake.rst
  docs/src/main/sphinx/connector/hive.rst
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#15225 Add column add/drop/rename events
  core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
  testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Labels: cla-signed

#15798 Make NestedLoopOutputIterator sealed
  core/trino-main/src/main/java/io/trino/operator/join/NestedLoopJoinOperator.java
Labels: cla-signed

#15815 Remove redundant if condition
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableExecutePartitioning.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableWriterPartitioning.java
Labels: cla-signed

#15776 Restrict user to drop a column that is used in older partition spec or void partition column in iceberg connector
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#15814 Update code using Map-of-Map
  core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/Indexer.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/LexicoderRowSerializer.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/StringRowSerializer.java
Labels: cla-signed, no-release-notes

#15760 Optimize null representation in encoded VariableBlockWidthBlock
  core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java
  core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockEncoding.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/BaseFaultTolerantExecutionTest.java
Labels: cla-signed, tests:hive, performance

#15824 Continue commits checks when one fails
  .github/workflows/ci.yml
Labels: cla-signed, test, maintenance, no-release-notes

#15818 Add CatalogHandle to ConnectorContext
  core/trino-main/src/main/java/io/trino/connector/ConnectorContextInstance.java
  core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorContext.java
Labels: cla-signed

#15800 Provide extra extension point for adding column in BaseJdbcClient
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed, no-release-notes

#14964 Add support for CHECK constraint in INSERT statement in engine and SPI
  core/trino-main/src/main/java/io/trino/connector/InternalMetadataProvider.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/DeterminismEvaluator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/sql/query/TestCheckConstraint.java
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableSchema.java
Labels: cla-signed, docs

#15831 Add anchors for linking purposes
  docs/src/main/sphinx/connector/hive-s3.rst
Labels: cla-signed, docs

#15835 Put dynamic filtering comment before right PredicatePushDown call
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
Labels: cla-signed

#15696 Reuse PagePositionAppenders between Drivers
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
  core/trino-main/src/main/java/io/trino/operator/TaskContext.java
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitionerPool.java
  core/trino-main/src/main/java/io/trino/operator/output/PartitionedOutputOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
  core/trino-main/src/test/java/io/trino/operator/output/BenchmarkPartitionedOutputOperator.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitionerPool.java
Labels: cla-signed, performance

#15625 Add Trino 406 release notes
  docs/src/main/sphinx/connector/iceberg.rst
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-406.md
Labels: cla-signed, release-notes, docs

#15852 Fix spelling in FTE docs
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#15851 Remove unsupported properties from MongoDB documentation
  docs/src/main/sphinx/connector/mongodb.rst
Labels: cla-signed, docs

#15350 Unified Materialized View Table Type in information_schema
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#15807 Add unregister_table procedure to Iceberg connector
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/UnregisterTableProcedure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConnectorSmokeTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/minio/MinioClient.java
Labels: cla-signed, docs, tests:hive

#15857 Fix 406 release note
  docs/src/main/sphinx/release/release-406.md
Labels: cla-signed, release-notes, docs, no-release-notes

#15841 `ParquetSchemaConverter` code cosmetics
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
Labels: cla-signed, tests:hive, no-release-notes

#15838 Disallow using of single-entry loader in bulk cache
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
Labels: cla-signed, tests:hive

#15703 Update to Jetty 10
  pom.xml
Labels: cla-signed, jdbc, tests:hive

#15825 Fix check-commits task names
  .github/workflows/ci.yml
Labels: cla-signed, test, maintenance, no-release-notes, dx

#15863 Remove outdated SPI revapi exclusions
  core/trino-spi/pom.xml
Labels: cla-signed, no-release-notes

#15855 Call purgeTable in Iceberg REST catalog
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#15866 Fix typo
  core/trino-main/src/test/java/io/trino/block/TestRowBlock.java
  lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes

#15862 Fix precision loss when coercing TIME to TIME TZ and fix abundant precision when coercing DATE to TIMESTAMP TZ
  core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
  core/trino-main/src/test/java/io/trino/type/TestTypeCoercion.java
Labels: cla-signed, correctness

#15875 Fix flaky spill tests
  testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java
  testing/trino-tests/src/test/java/io/trino/tests/TestDistributedSpilledQueries.java
Labels: cla-signed, no-release-notes

#15085 Do not suppress candidate tokens in the middle of a rule
  core/trino-parser/src/main/java/io/trino/sql/parser/ErrorHandler.java
  core/trino-parser/src/main/java/io/trino/sql/parser/SqlParser.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
Labels: cla-signed

#15876 Separate profile for Iceberg REST and JDBC catalog tests
  .github/workflows/ci.yml
  plugin/trino-iceberg/pom.xml
Labels: cla-signed, no-release-notes

#15886 Use enhanced switch expressions
  core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
Labels: cla-signed

#15871 Use optional binding for GlueHiveMetastoreFactory
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
Labels: cla-signed, tests:hive

#15864 Remove extra cache backreferences when loading part and part stats
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
Labels: cla-signed, tests:hive

#15721 Implement adaptive remote task request size
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskExecution.java
  core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
Labels: cla-signed

#15901 Remove deprecated FTE scheduler
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantQueryScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantStageScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/TaskSource.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/TaskSourceFactory.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestFaultTolerantStageScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestStageTaskSourceFactory.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestingExchange.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestingSplitSource.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestingTaskLifecycleListener.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestingTaskSourceFactory.java
Labels: cla-signed

#15889 Add support for changing column types in MongoDB connector
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Labels: cla-signed

#15902 Fix docs for LDAP truststore
  docs/src/main/sphinx/security/ldap.rst
Labels: cla-signed, docs

#15823 Use records for cache key in CachingJdbcClient
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
Labels: cla-signed, no-release-notes

#15906 Fix typo
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes

#15905 Remove unused FTE config property
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed, docs

#15896 Avoid saving cache in the build-test-matrix CI job
  .github/workflows/ci.yml
Labels: cla-signed

#15811 Cache metastore (table and partition) stats by default
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/IcebergFileMetastoreCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestingIcebergFileMetastoreCatalogModule.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestingIcebergHiveMetastoreCatalogModule.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestExternalHiveTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
Labels: cla-signed, tests:hive

#15899 Prevent division by 0
  core/trino-main/src/main/java/io/trino/operator/exchange/UniformPartitionRebalancer.java
Labels: cla-signed

#15910 `trino-delta-lake` Remove unused field
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
Labels: no-release-notes

#15880 Adjust the drop table logic for Delta Lake managed tables
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
Labels: cla-signed, no-release-notes
