Repository trinodb/trino, pull requests merged in 2023-10, with the labels that each got.

#19219 Remove some unused helper methods
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/BlockLocation.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketing.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
Labels: cla-signed, tests:hive, no-release-notes, hive

#19213 Allow register_table with s3:// when metadata uses s3a://
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
Labels: cla-signed, iceberg

#19180 Scale down databricks testing for the Delta Lake connector
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeActiveFilesCache.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCaseInsensitiveMapping.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckpointsCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakePartitioningCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeProceduresCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTimeTravelCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeUpdateCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
Labels: cla-signed, test, tests:hive, no-release-notes, delta-lake

#19220 Update ASM, zstd
  pom.xml
Labels: cla-signed, tests:hive

#19222 Remove testng from trino-teradata-functions test classpath
  plugin/trino-teradata-functions/pom.xml
  plugin/trino-teradata-functions/src/test/java/io/trino/plugin/teradata/functions/dateformat/TestDateFormatParser.java
Labels: cla-signed

#19228 Skip tracking TrinoOutputFile.location in tests
  lib/trino-filesystem/src/test/java/io/trino/filesystem/TrackingFileSystemFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
Labels: cla-signed, test, tests:hive, no-release-notes, iceberg

#19230 Fix test to be varchar length agnostic
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#18687 Document IN operator #18610
  docs/src/main/sphinx/functions/comparison.md
Labels: cla-signed, docs

#19221 Update release notes 427
  docs/src/main/sphinx/release/release-427.md
Labels: cla-signed, release-notes, docs

#19049 Create optimize fragment
  docs/src/main/sphinx/connector/delta-lake.md
  docs/src/main/sphinx/connector/hive.md
  docs/src/main/sphinx/connector/iceberg.md
  docs/src/main/sphinx/connector/optimize.fragment
Labels: cla-signed, docs

#19151 Corrected hash table length for distinct map keys
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/DistinctMapKeys.java
Labels: cla-signed, tests:hive

#19214 Remove TestNG from SPI
  core/trino-spi/pom.xml
  core/trino-spi/src/test/java/io/trino/spi/TestHostAddress.java
  core/trino-spi/src/test/java/io/trino/spi/TestPage.java
  core/trino-spi/src/test/java/io/trino/spi/TestStandardErrorCode.java
  core/trino-spi/src/test/java/io/trino/spi/TestTrinoException.java
  core/trino-spi/src/test/java/io/trino/spi/block/BlockTestUtils.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestArrayBlockBuilder.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestBlockRetainedSizeBreakdown.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestBlockUtil.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestDictionaryBlockEncoding.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestIntArrayList.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestLazyBlock.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestRowBlock.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestRowBlockBuilder.java
  core/trino-spi/src/test/java/io/trino/spi/block/TestVariableWidthBlockBuilder.java
  core/trino-spi/src/test/java/io/trino/spi/connector/TestConnectorViewDefinition.java
  core/trino-spi/src/test/java/io/trino/spi/exchange/TestExchangeId.java
  core/trino-spi/src/test/java/io/trino/spi/function/TestScalarFunctionAdapter.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestAllOrNoneValueSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestDomain.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestEquatableValueSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestRange.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java
  core/trino-spi/src/test/java/io/trino/spi/resourcegroups/TestResourceGroupId.java
  core/trino-spi/src/test/java/io/trino/spi/security/TestSelectedRole.java
  core/trino-spi/src/test/java/io/trino/spi/statistics/TestDoubleRange.java
  core/trino-spi/src/test/java/io/trino/spi/statistics/TestStatsUtil.java
  core/trino-spi/src/test/java/io/trino/spi/transaction/TestIsolationLevel.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestArrayType.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestChars.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestDecimals.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestInt128Math.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestLongDecimalType.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestLongTimestamp.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestMapType.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestRowType.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestSqlDecimal.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestSqlTimestampWithTimeZone.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java
  core/trino-spi/src/test/java/io/trino/spi/type/TestVarchars.java
Labels: cla-signed

#19241 Support tracing when connection pool is enabled in Oracle
  plugin/trino-oracle/pom.xml
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OraclePoolConnectionFactory.java
Labels: cla-signed

#19234 Restore test lost in migration
  testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java
Labels: cla-signed, test, no-release-notes

#19233 Fix silently ignored tests in TestLocalQueryAssertions
  testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java
Labels: cla-signed, test, no-release-notes

#19244 Print biggest splits when running out of TaskDescriptorStorage space
  core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestTaskDescriptorStorage.java
Labels: cla-signed

#19246 Make testMergeLarge more stable
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#19078 [pinot] Adding query option support for DynamicTable
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTable.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTableBuilder.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTablePqlExtractor.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
Labels: cla-signed

#18923 Fix deletes which trigger file rewrites in partitions with special characters
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java
Labels: bug, cla-signed, correctness, delta-lake

#19256 Extract TpcUtils class in product tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestParquet.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TpcTestUtils.java
Labels: cla-signed, tests:hive

#19255 Extract function Iceberg::getPartitionValues
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
Labels: cla-signed, iceberg

#19263 Add docs for update statements to JDBC connectors
  docs/src/main/sphinx/connector/ignite.md
  docs/src/main/sphinx/connector/mariadb.md
  docs/src/main/sphinx/connector/mysql.md
  docs/src/main/sphinx/connector/oracle.md
  docs/src/main/sphinx/connector/postgresql.md
  docs/src/main/sphinx/connector/redshift.md
  docs/src/main/sphinx/connector/singlestore.md
  docs/src/main/sphinx/connector/sqlserver.md
  docs/src/main/sphinx/release/release-427.md
Labels: cla-signed

#19262 Add Trino 428 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-428.md
Labels: cla-signed, release-notes, docs

#19173 Update file format docs for Iceberg
  docs/src/main/sphinx/connector/iceberg.md
Labels: cla-signed, docs

#19269 Improve parquet.small-file-threshold documentation
  docs/src/main/sphinx/connector/object-storage-file-formats.md
Labels: cla-signed, docs

#19265 Move logic for handling REFRESH MATERIALIZED VIEW memory allocation
  core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#19268 Use absolute URL for sitemap
  docs/src/main/sphinx/conf.py
Labels: cla-signed, docs

#19280 Remove unused checkCanGrantExecuteFunctionPrivilege method
  core/trino-main/src/main/java/io/trino/connector/ConnectorServices.java
  core/trino-main/src/main/java/io/trino/security/AccessControl.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
  core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
  core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/main/java/io/trino/tracing/TracingAccessControl.java
  core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
  core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlySystemAccessControl.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Labels: cla-signed, tests:hive, hive

#19283 Remove duplicate function security checks in ExpressionAnalyzer
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed

#19248 Don't set s3api create-bucket LocationConstraint configuration option for us-east-1 region
  .github/bin/s3/setup-empty-s3-bucket.sh
Labels: cla-signed

#19252 Ignore EntityNotFoundException when cleaning Glue in product tests
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java
Labels: cla-signed, tests:hive, no-release-notes

#19261 Improve speed of TestDruidTypeMapping.testTimestamp
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidTypeMapping.java
Labels: cla-signed

#19276 Update libthrift to 0.19.0
  pom.xml
Labels: cla-signed

#19274 Update GCS to 2.2.17
  pom.xml
Labels: cla-signed

#19293 Update calcite to 1.32.0
  plugin/trino-pinot/pom.xml
  pom.xml
Labels: cla-signed

#19297 Update google-oauth-client to 1.33.3
  plugin/trino-google-sheets/pom.xml
Labels: cla-signed

#19249 Handle camelCase naming in externally provided Avro Schemas
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroFileWriter.java
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroPagePositionDataWriter.java
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroTypeUtils.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroBase.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithAvroNativeTypeManagement.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataWriterWithoutTypeManager.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHiveFileUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHiveFileWriter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/avro/camelCaseSchema.avsc
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
Labels: cla-signed, tests:hive, hive

#19301 Convert to most succinct time unit before printing physical read time
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
Labels: cla-signed

#19295 Avoid extra file status call in orc reader
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemAccessOperations.java
Labels: cla-signed, tests:hive, hive

#19304 Use Int2IntArrayMap in TableToPartitionMapping
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableToPartitionMapping.java
Labels: cla-signed, tests:hive, hive

#19300 Switch to Hadoop3 GCS connector
  pom.xml
Labels: cla-signed

#19309 Extract trino-resource-group-managers from test-other-modules
  .github/workflows/ci.yml
Labels: cla-signed

#19310 Extract trino-google-sheets from test-other-modules
  .github/workflows/ci.yml
Labels: cla-signed

#19311 Remove unused flags from ParquetReaderOptions
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderOptions.java
Labels: cla-signed, tests:hive

#19312 Add a safety check for relationFilter application
  core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
Labels: cla-signed, no-release-notes

#19315 Remove deprecated FixedPageSource constructor
  core/trino-spi/src/main/java/io/trino/spi/connector/FixedPageSource.java
Labels: cla-signed, maintenance, no-release-notes

#19323 Update Jedis to 5.0.1
  plugin/trino-redis/pom.xml
Labels: cla-signed

#19325 Update jose-jwt to 9.36
  pom.xml
Labels: cla-signed

#13981 Support automatic type coercion in Iceberg table creation
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java
Labels: cla-signed, iceberg

#19328 Fix compilation issue
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, iceberg

#19317 Report stats for dynamic-filter only ScanFilter
  core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
Labels: cla-signed, tests:hive, hive

#19321 Update airlift to 236
  pom.xml
Labels: cla-signed

#19329 Switch ensureTestNamingConvention to run in JUnit to reduce test setups
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#19330 Update to Maven 3.9.5
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#19342 Upgrade ClickHouse JDBC driver to 0.5.0
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  pom.xml
Labels: cla-signed

#18753 Implement session logout in OAuth2Authenticator
  core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Client.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServerConfigProvider.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OidcDiscovery.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/StaticConfigurationProvider.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/StaticOAuth2ServerConfiguration.java
  core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
  core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiLogoutResource.java
  core/trino-main/src/main/java/io/trino/server/ui/OAuthIdTokenCookie.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestJweTokenSerializer.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithOpaque.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithRefreshTokens.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
  docs/src/main/sphinx/security/oauth2.md
Labels: cla-signed, docs

#19332 Update nimbus OIDC SDK to 11.2
  pom.xml
Labels: cla-signed

#19331 Update protobuf to 3.24.4
  pom.xml
Labels: cla-signed

#19224 Refactor create/insert base jdbc client
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: cla-signed

#19337 Revert "Switch ensureTestNamingConvention to run in JUnit to reduce test setups"
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#19354 Fix typo: tax_max_writer_count -> task_max_writer_count
  docs/src/main/sphinx/release/release-428.md
Labels: cla-signed

#19231 Add docs for MySQL timestamptz handling
  docs/src/main/sphinx/connector/mysql.md
Labels: cla-signed, docs

#19333 Import and update to grpc bom 1.58.0
  pom.xml
Labels: cla-signed

#19357 Add Trino 429 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-429.md
Labels: cla-signed, release-notes, docs

#19335 Update jjwt to 0.12.2
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/FileSigningKeyResolver.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwkSigningKeyResolver.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/ZstdCodec.java
  core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkDecoder.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestJweTokenSerializer.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithOpaque.java
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
  pom.xml
Labels: cla-signed, jdbc

#19381 Switch to JDK 21 for forward compatibility testing
  .github/workflows/ci.yml
Labels: cla-signed

#19341 Clarify UPDATE statement support for JDBC connectors
  docs/src/main/sphinx/connector/ignite.md
  docs/src/main/sphinx/connector/mariadb.md
  docs/src/main/sphinx/connector/mysql.md
  docs/src/main/sphinx/connector/oracle.md
  docs/src/main/sphinx/connector/postgresql.md
  docs/src/main/sphinx/connector/redshift.md
  docs/src/main/sphinx/connector/singlestore.md
  docs/src/main/sphinx/connector/sql-update-limitation.fragment
  docs/src/main/sphinx/connector/sqlserver.md
Labels: cla-signed, docs

#19386 Fix TestIcebergAbfsConnectorSmokeTest failure
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
Labels: cla-signed, iceberg

#17263 Add config to reject Iceberg queries without partition filter
  docs/src/main/sphinx/connector/iceberg.md
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Labels: cla-signed, docs, iceberg

#19388 Update BigQueryStorageAvroPageSource to SqlRow
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
Labels: cla-signed, bigquery

#19383 Reduce written data size in insert test using nation table
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#19393 Update airlift to 237
  pom.xml
Labels: cla-signed

#19394 Fix testPartitionFilterRequired for cloud test environment
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
Labels: cla-signed, iceberg

#19398 Replace test annotation for overriden test
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, bigquery

#19346 Apply PrefixObjectNameGeneratorModule in tests
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
Labels: cla-signed, test, no-release-notes

#19395 Simplify captures equals method
  lib/trino-matching/src/main/java/io/trino/matching/Captures.java
Labels: cla-signed

#19401 Run core/trino-main tests on JDK 21
  .github/workflows/ci.yml
Labels: cla-signed

#19338 Expose more stats for TaskDescriptorStorage
  core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java
Labels: cla-signed

#19349 Use bulk merging of metrics in PlanNodeStatsSummarizer
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/BasicOperatorStats.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStats.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStatsSummarizer.java
Labels: cla-signed

#19391 MySQL table stats code cleanup
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
Labels: cla-signed

#19303 Accelerate Iceberg when reading partition columns only
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProcessor.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
Labels: cla-signed, iceberg

#19406 Track INPUT_FILE_LAST_MODIFIED operations in TrackingFileSystemFactory
  lib/trino-filesystem/src/test/java/io/trino/filesystem/TrackingFileSystemFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
Labels: cla-signed, tests:hive, iceberg

#19389 Fix description of Delta Lake checkpoint intervals
  docs/src/main/sphinx/connector/delta-lake.md
Labels: cla-signed, docs

#19415 Remove deprecated task writer properties
  docs/src/main/sphinx/admin/properties-task.md
  docs/src/main/sphinx/admin/properties-writer-scaling.md
Labels: cla-signed, docs

#19102 Add support for timezone parameter to JDBC driver
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java
  client/trino-client/src/main/java/io/trino/client/uri/PropertyName.java
  client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
  docs/src/main/sphinx/client/jdbc.md
Labels: cla-signed, docs, jdbc

#19412 Add generic tests for filter after aggregation
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#19414 Refactor stage output data size estimation
  core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ByEagerParentOutputDataSizeEstimator.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BySmallStageOutputDataSizeEstimator.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ByTaskProgressOutputDataSizeEstimator.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/CompositeOutputDataSizeEstimator.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/OutputDataSizeEstimator.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/OutputDataSizeEstimatorFactory.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
Labels: cla-signed

#19355 Remove default implementation of withoutSmallFileThreshold
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, no-release-notes

#19421 Avoid redundantly doubled test setup
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Labels: cla-signed

#19422 Update okhttp to 4.12.0 and okio to 3.6.0
  pom.xml
Labels: cla-signed

#19411 Handle timeouts in Trino client when decoding response body
  client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
  client/trino-client/src/test/java/io/trino/client/TestRetry.java
Labels: cla-signed

#19425 Add fileModifiedTime in DeltaLakeSplit Object methods
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplit.java
Labels: cla-signed, delta-lake

#19368 Ensure that jdbc temp tables can be dropped if the insertions fail
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Labels: bug, cla-signed, jdbc

#19427 Fix RunningQueries metric to represent all running queries
  core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
Labels: cla-signed

#19435 Update redshift jdbc to 2.1.0.20
  plugin/trino-redshift/pom.xml
Labels: cla-signed

#19002 Fix join type for correlated subquery
  core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedScalarSubquery.java
  core/trino-main/src/test/java/io/trino/sql/query/TestCorrelatedAggregation.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
  testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/partitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/partitioned/q54.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/unpartitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/unpartitioned/q54.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/partitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/partitioned/q54.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/unpartitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/unpartitioned/q54.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q54.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q54.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg_small_files/parquet/unpartitioned/q09.plan.txt
  testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg_small_files/parquet/unpartitioned/q54.plan.txt
Labels: bug, cla-signed, correctness

#19436 Update jjwt and nimbus-jwt
  pom.xml
Labels: cla-signed

#19440 Clarify global aggregation in applyAggregation
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
Labels: cla-signed

#19217 Enforce Client capabilities when Session Authorization is not supported
  client/trino-client/src/main/java/io/trino/client/ClientCapabilities.java
  core/trino-main/src/main/java/io/trino/execution/ResetSessionAuthorizationTask.java
  core/trino-main/src/main/java/io/trino/execution/SetSessionAuthorizationTask.java
  testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
Labels: cla-signed

#19429 Fix correctness issue when query contains some not-equals in MongoDB
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java
Labels: bug, cla-signed, correctness, mongodb

#19443 Upgrade docker-images to version 87
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes

#19441 Update singlestore-jdbc-client to 1.2.0
  plugin/trino-singlestore/pom.xml
Labels: cla-signed

#19449 Do not allocate memory for all queries scanning system.* tables
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/NoMemoryAwarePartitionMemoryEstimator.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestNoMemoryAwarePartitionMemoryEstimator.java
Labels: cla-signed

#19387 Remove eliminating sort optimization
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateSorts.java
Labels: cla-signed, correctness

#19456 Avoid redundant calculation of columnsWithMinMaxStats
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
Labels: cla-signed, no-release-notes, delta-lake

#19460 Update function security documentation
  docs/src/main/sphinx/security/file-system-access-control.md
Labels: cla-signed, docs

#19462 Use assertEventually in BigQuery assertLabelForTable
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, bigquery

#19352 Update DEVELOPMENT.md: Git merge strategy
  .github/DEVELOPMENT.md
Labels: cla-signed

#19359 Add "test" environment tag to temporary S3 test buckets used by CI
  .github/bin/s3/setup-empty-s3-bucket.sh
Labels: cla-signed

#18451 Switch error code to TABLE_NOT_FOUND if all columns filtered out
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
Labels: cla-signed

#19448 Update Kafka & zookeeper clients
  pom.xml
Labels: cla-signed

#19467 Add missing JUnit lifecycle annotation
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryInstanceCleaner.java
Labels: cla-signed, bigquery

#19465 Add missing @Test annotation to overriden test for HiveGlueMetastore
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed, tests:hive, hive

#19466 Remove unnecessary test
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTableStatistics.java
Labels: cla-signed

#19167 Improve SQL language landing pages
  docs/src/main/sphinx/functions.md
  docs/src/main/sphinx/language.md
  docs/src/main/sphinx/language/comments.md
  docs/src/main/sphinx/sql.md
  docs/src/main/sphinx/sql/comment.md
  docs/src/main/sphinx/sql/select.md
Labels: cla-signed, release-notes, docs

#19237 Convert tables in docs to markdown source
  docs/src/main/sphinx/admin/event-listeners-http.md
  docs/src/main/sphinx/admin/fault-tolerant-execution.md
  docs/src/main/sphinx/admin/resource-groups.md
  docs/src/main/sphinx/client/cli.md
  docs/src/main/sphinx/client/jdbc.md
  docs/src/main/sphinx/functions/comparison.md
  docs/src/main/sphinx/functions/conversion.md
  docs/src/main/sphinx/functions/decimal.md
  docs/src/main/sphinx/functions/json.md
  docs/src/main/sphinx/installation/deployment.md
  docs/src/main/sphinx/installation/rpm.md
  docs/src/main/sphinx/security/built-in-system-access-control.md
  docs/src/main/sphinx/security/certificate.md
  docs/src/main/sphinx/security/file-system-access-control.md
  docs/src/main/sphinx/security/jwt.md
  docs/src/main/sphinx/security/oauth2.md
  docs/src/main/sphinx/sql/show-stats.md
Labels: cla-signed, docs

#18716 Update confluent to 7.4.1
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ClassLoaderSafeSchemaRegistryClient.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaAvroReadsSmokeTest.java
Labels: cla-signed, tests:hive

#19452 Don't pushdown like expression with escape in Ignite connector
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Labels: cla-signed

#19473 Add docs for table stats with MariaDB
  docs/src/main/sphinx/connector/mariadb.md
Labels: cla-signed, docs

#19428 Add Trino 430 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-430.md
Labels: cla-signed, release-notes, docs

#19476 Add revapi rules after 430 release
  core/trino-spi/pom.xml
Labels: cla-signed

#19390 Split metastore timeout config for connect and read
  docs/src/main/sphinx/connector/metastores.md
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/Transport.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingTokenAwareMetastoreClientFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMetastoreClientFactory.java
Labels: cla-signed, docs, tests:hive, iceberg, delta-lake, hive

#19413 Simplify how SQL injection is detected when using query.comment-format
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/logging/SessionInterpolatedValues.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
Labels: cla-signed

#19486 Correct release notes
  docs/src/main/sphinx/release/release-430.md
Labels: cla-signed, release-notes, docs

#19340 Clarify syntax for role grants
  docs/src/main/sphinx/sql/grant-roles.md
  docs/src/main/sphinx/sql/grant.md
  docs/src/main/sphinx/sql/revoke-roles.md
  docs/src/main/sphinx/sql/revoke.md
Labels: cla-signed, syntax-needs-review, docs

#19494 Remove dead code from test script
  testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
Labels: cla-signed

#19518 Expand docs for Hive schema evolution type conversions
  docs/src/main/sphinx/connector/hive.md
Labels: cla-signed, docs

#19434 Update Iceberg from 1.3.1 to 1.4.1
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
  plugin/trino-iceberg/src/main/java/org/apache/iceberg/parquet/TrinoParquetUtil.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestPartitionFields.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreCreateTableFailure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
Labels: cla-signed, no-release-notes, iceberg

#19015 Disallow null offset in lead/lag window functions
  core/trino-main/src/main/java/io/trino/operator/window/LagFunction.java
  core/trino-main/src/main/java/io/trino/operator/window/LeadFunction.java
  core/trino-main/src/test/java/io/trino/operator/window/TestLagFunction.java
  core/trino-main/src/test/java/io/trino/operator/window/TestLeadFunction.java
  core/trino-main/src/test/java/io/trino/sql/query/TestLag.java
  core/trino-main/src/test/java/io/trino/sql/query/TestLead.java
  docs/src/main/sphinx/functions/window.md
Labels: cla-signed, docs

#19502 Document the new JDBC legacyPreparedStatements flag
  docs/src/main/sphinx/client/jdbc.md
Labels: cla-signed, docs

#19521 Add inline SQL function support
  core/trino-main/src/main/java/io/trino/Session.java
  core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
  core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/FunctionBinder.java
  core/trino-main/src/main/java/io/trino/metadata/FunctionManager.java
  core/trino-main/src/main/java/io/trino/metadata/FunctionResolver.java
  core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java
  core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionProvider.java
  core/trino-main/src/main/java/io/trino/metadata/LanguageScalarFunctionData.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/QualifiedObjectName.java
  core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/WorkerLanguageFunctionProvider.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/main/java/io/trino/server/WorkerModule.java
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
  core/trino-main/src/main/java/io/trino/sql/PlannerContext.java
  core/trino-main/src/main/java/io/trino/sql/SqlPath.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanFragment.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
  core/trino-main/src/main/java/io/trino/sql/planner/RuntimeAdaptivePartitioningRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/main/java/io/trino/testing/QueryRunner.java
  core/trino-main/src/test/java/io/trino/cost/TestCostCalculator.java
  core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
  core/trino-main/src/test/java/io/trino/execution/BaseTestSqlTaskManager.java
  core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
  core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlStage.java
  core/trino-main/src/test/java/io/trino/execution/TestStageStateMachine.java
  core/trino-main/src/test/java/io/trino/execution/TestTaskExecutorStuckSplits.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestMultiSourcePartitionedScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestScaledWriterScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSchedulingUtils.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestExponentialGrowthPartitionMemoryEstimator.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestNoMemoryAwarePartitionMemoryEstimator.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/policy/PlanUtils.java
  core/trino-main/src/test/java/io/trino/server/TestDynamicFilterService.java
  core/trino-main/src/test/java/io/trino/server/TestQuerySessionSupplier.java
  core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
  core/trino-main/src/test/java/io/trino/sql/TestSqlPath.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPlanFragmentPartitionCount.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestTopologicalOrderSubPlanVisitor.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestingPlannerContext.java
  core/trino-spi/src/main/java/io/trino/spi/function/LanguageFunction.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/TestOverridePartitionCountRecursively.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/StandaloneQueryRunner.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
  testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Labels: cla-signed

#19525 Migrate Iceberg Catalog tests to JUnit
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestTrinoHiveCatalogWithFileMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
Labels: cla-signed, test, no-release-notes, iceberg

#19496 Add regression test for sort elimination
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateSorts.java
Labels: cla-signed

#18854 Add documentation for SQL routines
  docs/src/main/sphinx/admin/properties-sql-environment.md
  docs/src/main/sphinx/admin/properties.md
  docs/src/main/sphinx/connector/hive.md
  docs/src/main/sphinx/connector/memory.md
  docs/src/main/sphinx/index.md
  docs/src/main/sphinx/language/sql-support.md
  docs/src/main/sphinx/language/types.md
  docs/src/main/sphinx/routines.md
  docs/src/main/sphinx/routines/begin.md
  docs/src/main/sphinx/routines/case.md
  docs/src/main/sphinx/routines/declare.md
  docs/src/main/sphinx/routines/examples.md
  docs/src/main/sphinx/routines/function.md
  docs/src/main/sphinx/routines/if.md
  docs/src/main/sphinx/routines/introduction.md
  docs/src/main/sphinx/routines/iterate.md
  docs/src/main/sphinx/routines/leave.md
  docs/src/main/sphinx/routines/loop.md
  docs/src/main/sphinx/routines/repeat.md
  docs/src/main/sphinx/routines/return.md
  docs/src/main/sphinx/routines/set.md
  docs/src/main/sphinx/routines/while.md
  docs/src/main/sphinx/sql.md
  docs/src/main/sphinx/sql/create-function.md
  docs/src/main/sphinx/sql/drop-function.md
  docs/src/main/sphinx/sql/select.md
  docs/src/main/sphinx/sql/set-path.md
  docs/src/main/sphinx/sql/show-functions.md
Labels: cla-signed, docs

#19487 Increase split processing config parameters
  core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeSchedulerConfig.java
  core/trino-main/src/test/java/io/trino/execution/TestNodeSchedulerConfig.java
  core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java
  docs/src/main/sphinx/admin/properties-node-scheduler.md
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Labels: cla-signed, docs, tests:hive, hive

#17635 Normalize OR and IN expressions referencing the same symbol as IN
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/NormalizeOrExpressionRewriter.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestSimplifyExpressions.java
Labels: cla-signed

#19488 Add file-based access control for procedures
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AccessControlRules.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/CatalogProcedureAccessControlRule.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlModule.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlRules.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ProcedureAccessControlRule.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
  lib/trino-plugin-toolkit/src/test/resources/file-based-system-access-visibility.json
  lib/trino-plugin-toolkit/src/test/resources/visibility-with-json-pointer.json
  lib/trino-plugin-toolkit/src/test/resources/visibility.json
Labels: cla-signed

#19463 Retry updating the table statistics in the context of concurrent modifications
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConcurrentModificationGlueMetastore.java
Labels: cla-signed, tests:hive, hive

#18464 Use tempto `jdbc_jar` for Delta query executor
  testing/trino-product-tests-launcher/pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeDeltaLakeDatabricks.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/tempto-configuration.yaml
  testing/trino-product-tests/pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/DeltaQueryExecutors.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/QueryExecutors.java
  testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
Labels: cla-signed, tests:hive

#19528 Fix syntax in `PredicatePushDown#createDynamicFilters` arguments list
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#19509 Skip testing JDBC compatibility for versions 422-424
  testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
Labels: cla-signed

#19478 Preserve sourcePartition to Splits mapping in task descriptor
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ArbitraryDistributionSplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/HashDistributionSplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SingleDistributionSplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SplitsMapping.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptor.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptorStorage.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/SplitAssignerTester.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestArbitraryDistributionSplitAssigner.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestEventDrivenTaskSource.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestHashDistributionSplitAssigner.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestSingleDistributionSplitAssigner.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestSplitsMapping.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestTaskDescriptorStorage.java
Labels: cla-signed

#19530 Test access operations for `CREATE OR REPLACE TABLE` on Iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Labels: test, no-release-notes, iceberg

#19275 Cast char fields, if necessary, to varchar type in Hive view translations
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
  pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
Labels: cla-signed, tests:hive, hive

#19537 Move Delta snapshot loading to DeltaLakeMetadata
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java
Labels: cla-signed, delta-lake

#19542 Add example for routine storage config
  docs/src/main/sphinx/admin/properties-sql-environment.md
Labels: cla-signed, docs

#19497 Add Trino 431 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-431.md
Labels: cla-signed, release-notes, docs

#19543 Delete all objects before deleting s3 bucket used for ci
  .github/bin/s3/delete-s3-bucket.sh
Labels: cla-signed

#19038 Write min/max statistics with truncation for strings in parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetMetadataUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
Labels: cla-signed, tests:hive

#19550 Migrate JDBC driver tests to JUnit
  client/trino-jdbc/src/test/java/io/trino/jdbc/JdbcDriverIT.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestAbstractTrinoResultSet.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcExternalAuthentication.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcStatement.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcVendorCompatibility.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcWarnings.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestProgressMonitor.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverImpersonateUser.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java
Labels: cla-signed, jdbc
