Repository trinodb/trino, pull requests merged in 2023-02, with the labels that each got.

#15094 Allow Iceberg writes to use either append or fastAppend
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
Labels: cla-signed

#15897 Optimize DELTA_LENGTH_BYTE_ARRAY decoder in parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/SimpleSliceInputStream.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/DeltaLengthByteArrayDecoders.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkBinaryColumnReader.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestByteArrayValueDecoders.java
Labels: cla-signed, tests:hive, performance

#15914 Update docker-images to version 76
  pom.xml
Labels: cla-signed

#15909 Fix NPE when Glue table has no type
  .mvn/modernizer/violations.xml
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueToTrinoConverter.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java
Labels: cla-signed, tests:hive

#15579 Increase node scheduler config parameters
  core/trino-main/src/main/java/io/trino/execution/scheduler/NodeSchedulerConfig.java
  core/trino-main/src/test/java/io/trino/execution/TestNodeSchedulerConfig.java
  docs/src/main/sphinx/admin/properties-node-scheduler.rst
Labels: cla-signed, docs

#15924 Dependency benchto-driver was upgraded from 0.22 to 0.23
  pom.xml
Labels: cla-signed

#15870 Obtain and refresh sink instance handle asynchronously
  core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
  core/trino-main/src/main/java/io/trino/operator/DeduplicatingDirectExchangeBuffer.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestEventDrivenTaskSource.java
  core/trino-spi/src/main/java/io/trino/spi/exchange/Exchange.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/AbstractTestExchangeManager.java
Labels: cla-signed

#15922 Remove unused constants and methods from RaptorColumnHandle
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorColumnHandle.java
Labels: cla-signed, no-release-notes

#15929 Fix materialized view failure mode when base table gone
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#15939 Make titles of check commit jobs more readable
  .github/workflows/ci.yml
Labels: cla-signed

#15958 Update SQL Server connector document `database -> databaseName`
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#15948 Fix null projects handling in RowPositionsAppender
  core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
Labels: cla-signed

#15856 Add support for unregister_table procedure in Delta Lake
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/UnregisterTableProcedure.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeProceduresCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeCompatibility.java
Labels: cla-signed, docs, tests:hive

#15957 Add test case for renaming subset of fields in row types
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#15959 Remove unused OrcTypeToHiveTypeTranslator class
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeToHiveTypeTranslator.java
Labels: cla-signed, tests:hive, no-release-notes

#15940 Add `@FileExists` validation
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/ExchangeS3Config.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestExchangeS3Config.java
Labels: cla-signed, tests:hive, no-release-notes

#15949 Free PagePartitioner memory even if flush fails
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitionerPool.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitionerPool.java
Labels: cla-signed, no-release-notes

#15839 Use only PositionsAppender buffers in PagePartitioner
  core/trino-main/src/main/java/io/trino/operator/output/BytePositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/Int128PositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/Int96PositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/IntPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/LongPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
  core/trino-main/src/main/java/io/trino/operator/output/PositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderPageBuilder.java
  core/trino-main/src/main/java/io/trino/operator/output/RleAwarePositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/ShortPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/SlicePositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/TypedPositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
Labels: cla-signed, performance, no-release-notes

#15893 Suppress permission denied when listing materialized views in Iceberg Glue
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed

#15396 Support inserting into table having CHECK constraint in Delta Lake
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/main/antlr4/io/trino/plugin/deltalake/expression/SparkExpressionBase.g4
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/BooleanLiteral.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/CaseInsensitiveStream.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/ComparisonExpression.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/Identifier.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/Literal.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/LogicalExpression.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/LongLiteral.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/ParsingException.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpression.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionBuilder.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionConverter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionParser.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionTreeVisitor.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/StringLiteral.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressionParser.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressions.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Labels: cla-signed, tests:hive

#15985 Move parameterizing enums to the top of enclosing class
  core/trino-main/src/main/java/io/trino/sql/planner/plan/JoinNode.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ComparisonExpression.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Join.java
Labels: cla-signed, no-release-notes

#15702 Add version compatibility information
  docs/src/main/sphinx/client/cli.rst
  docs/src/main/sphinx/client/jdbc.rst
Labels: cla-signed, docs

#14020 Add release process section to DEVELOPMENT.md
  .github/DEVELOPMENT.md
Labels: cla-signed, docs

#15765 Improve HiveUtils name escaping
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveUtil.java
Labels: cla-signed, tests:hive

#15638 Update title of container docs to mention Docker
  docs/src/main/sphinx/installation/containers.rst
Labels: cla-signed, docs

#15969 Filter Iceberg position delete reads for ORC
  lib/trino-orc/src/main/java/io/trino/orc/OrcRecordReader.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Labels: cla-signed, tests:hive

#13814 Dev guide for WHERE predicate pushdown
  docs/src/main/sphinx/develop/connectors.rst
Labels: cla-signed, docs, no-release-notes

#15947 Limit concurrency of parallel FTE tests execution
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed, no-release-notes

#16001 Fix flakiness from random input in TestParquetReaderMemoryUsage
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderMemoryUsage.java
Labels: cla-signed, tests:hive

#15816 Downscale base connector tests
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseAutomaticJoinPushdownTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#15989 Decorrelate single-row values
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedSingleRowSubqueryToProject.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedSingleRowSubqueryToProject.java
  core/trino-main/src/test/java/io/trino/sql/query/TestMergeProjectWithValues.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSelectAll.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
Labels: cla-signed

#15996 Fix broken link in BigQuery documentation
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs, no-release-notes

#15984 Revert "Add column add/drop/rename events"
  core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
  testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Labels: cla-signed, correctness, RELEASE-BLOCKER

#14373 remove old Kerberos ticket after relogin to make Kudu authentication work correctly
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/authentication/KerberosAuthentication.java
Labels: cla-signed

#16000 Fix ConcurrentModificationException in parser error handler
  core/trino-parser/src/main/java/io/trino/sql/parser/ErrorHandler.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
Labels: bug, cla-signed

#15933 Fix SplitAssignment filtering
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Labels: cla-signed

#16017 Require 1+ retained node for isNotFullyPushedDown check
  core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java
Labels: cla-signed, test, no-release-notes

#15941 Update trino-maven-plugin to 12
  pom.xml
Labels: cla-signed

#16049 Use identifiable exit code for application configuration errors
  core/trino-main/src/main/java/io/trino/server/Server.java
Labels: cla-signed

#16014 Fix potential ambiguity while parsing queries involving table functions
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed

#15577 Merge developer guide formatting issues
  docs/src/main/sphinx/develop/supporting-merge.rst
Labels: cla-signed, docs

#16043 Pin protoc-jar-maven-plugin version
  plugin/trino-kafka/pom.xml
Labels: cla-signed

#14402 Add basic concept and glossary entries
  docs/src/main/sphinx/appendix.rst
  docs/src/main/sphinx/appendix/glossary.rst
  docs/src/main/sphinx/glossary.rst
  docs/src/main/sphinx/index.rst
  docs/src/main/sphinx/overview/concepts.rst
  docs/src/main/sphinx/security/tls.rst
Labels: cla-signed, docs

#16031 Fix potential deadlock in FTE scheduler
  core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionTest.java
  testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
Labels: cla-signed

#16028 Return NULL when zero date with convertToNull in Mysql
  plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
Labels: cla-signed

#15883 Improve VariableWidthBlock deserialization
  core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockEncoding.java
Labels: cla-signed

#15962 Fix log messages which are not format strings
  core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
Labels: cla-signed, tests:hive

#16069 Fix typo in PageBuilder
  core/trino-spi/src/main/java/io/trino/spi/PageBuilder.java
Labels: cla-signed, no-release-notes

#16058 Enforce non-empty returned relation type of table function
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java
Labels: cla-signed

#15986 Avoid unblocking more ExchangeOperators than necessary in exchange buffer
  core/trino-main/src/main/java/io/trino/operator/StreamingDirectExchangeBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestStreamingDirectExchangeBuffer.java
Labels: cla-signed, performance

#16062 Fix MemoryMetadata#streamTableColumnNames
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
Labels: bug, cla-signed

#16097 Add `@Flaky` annotation to TestHiveTableStatistics
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
Labels: cla-signed, tests:hive, no-release-notes

#16060 Introduce PluginInstaller
  core/trino-main/src/main/java/io/trino/server/PluginInstaller.java
  core/trino-main/src/main/java/io/trino/server/PluginManager.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
Labels: cla-signed

#15956 Refactor mock catalog init in BaseConnectorTest
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#16111 Remove assertion restricting hive.max-partitions-per-scan
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
Labels: cla-signed, tests:hive

#15874 Support `register_table` and `unregister_table` procedures in Iceberg JDBC catalog
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
Labels: cla-signed

#16108 Improve analyze error message in Delta Lake connector
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Labels: cla-signed, no-release-notes

#16117 Specify view limitations of REST and JDBC catalogs
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#16118 Fix wrong class name in `TestConstraintExtractor` comment
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java
Labels: cla-signed, no-release-notes

#16007 Add S3 connection ttl configuration to reduce http server exception
  docs/src/main/sphinx/connector/hive-s3.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Config.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3ConfigurationInitializer.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/TrinoS3ClientFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestHiveS3Config.java
Labels: cla-signed, docs, needs-docs, tests:hive, performance

#16055 Run id column mapping tests in OSS Delta Lake
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Labels: cla-signed, tests:hive, no-release-notes

#16121 Do not mark already closed connection as to be reused
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ReusableConnectionFactory.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestReusableConnectionFactory.java
Labels: cla-signed

#16086 Fix disabling cache in the setup action
  .github/actions/setup/action.yml
  .github/workflows/ci.yml
Labels: cla-signed

#16113 Apply hive.max-partitions-for-eager-load after applying predicate
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive

#16133 Use exit status code 100 for Trino start up crashes
  core/trino-main/src/main/java/io/trino/server/Server.java
Labels: cla-signed

#14869 Cleanup metadata file when `commitNewTable` fails for the Iceberg table
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/AbstractMetastoreTableOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreCreateTableFailure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCreateTableFailure.java
Labels: cla-signed, no-release-notes

#16054 Add openmetrics to Trino for exposing metrics
  core/trino-main/pom.xml
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
  pom.xml
Labels: cla-signed

#16143 Do not use materialized view in information schema
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#16139 Include test profile and jdk in CI artifact name
  .github/workflows/ci.yml
Labels: cla-signed

#16048 Fix output rendering for map aggregate functions
  docs/src/main/sphinx/functions/aggregate.rst
Labels: cla-signed, syntax-needs-review, docs

#15919 Add Trino 407 release notes
  docs/release-template.md
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-407.md
Labels: cla-signed, release-notes, docs

#16141 Fix RLE support for complex types with null element
  core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderFactory.java
  core/trino-main/src/main/java/io/trino/operator/output/RleAwarePositionsAppender.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
Labels: bug, cla-signed, performance

#16127 Fix delta lake CDF entries for MERGE queries
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java
Labels: cla-signed, tests:hive

#16157 Fix typo in 407 release notes
  docs/src/main/sphinx/release/release-407.md
Labels: cla-signed, release-notes, docs

#16154 Adjust delta lake product tests to collect statistics on write changes
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
Labels: cla-signed, tests:hive

#16168 Static import helper methods in DeltaLakeMetadata
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Labels: cla-signed, no-release-notes, delta-lake

#16145 Support writing NUMERIC and BIGNUMERIC types in BigQuery
  docs/src/main/sphinx/connector/bigquery.rst
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeUtils.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryTypeMapping.java
Labels: cla-signed, docs, bigquery

#16164 Replace usages of Hive TypeInfo
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaHiveTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveBucketAdapterRecordCursor.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveBucketFunction.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveBucketValidationRecordCursor.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCoercionRecordCursor.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionedBucketFunction.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueStatConverter.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectPushdown.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectRecordCursorProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/BaseCharTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/Category.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/CharTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/DecimalTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/ListTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/MapTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/PrimitiveCategory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/PrimitiveTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/StructTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/TypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/TypeInfoFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/TypeInfoUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/UnionTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/VarcharTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketing.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketingV1.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketingV2.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/SerdeConstants.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3select/TestS3SelectRecordCursor.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/type/TestTypeInfoUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveBucketing.java
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/HiveSchemaUtil.java
  pom.xml
Labels: cla-signed, tests:hive

#16176 Add AccessDeniedException.denySetViewComment
  core/trino-spi/src/main/java/io/trino/spi/security/AccessDeniedException.java
Labels: cla-signed

#16171 Remove unused name customization from HiveConnectorFactory
  plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/HivePlugin.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnectorFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorFactory.java
Labels: cla-signed, tests:hive

#15748 Add stale tracking action
  .github/workflows/stale.yml
Labels: cla-signed

#16175 Remove usages of HiveChar and HiveVarchar
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaHiveTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
Labels: cla-signed, tests:hive

#16180 Remove support for deprecated 'memsql' connector name
  docs/src/main/sphinx/connector.rst
  docs/src/main/sphinx/connector/memsql.rst
  plugin/trino-singlestore/pom.xml
  plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStorePlugin.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStorePlugin.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/singlestore.properties
  testing/trino-server-dev/etc/catalog/singlestore.properties
Labels: cla-signed

#16152 Disable remote preferred partitioning in case stats are absent
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableExecutePartitioning.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableWriterPartitioning.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyPreferredTableWriterPartitioning.java
Labels: cla-signed

#16173 Remove deprecated type methods from HiveUtil
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaHiveTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCoercionRecordCursor.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
Labels: cla-signed, tests:hive

#16089 Add page index filtering tests for nested parquet columns
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderRowRangesTest.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReader.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestFlatColumnReaderRowRanges.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestNestedColumnReaderRowRanges.java
Labels: cla-signed, tests:hive

#12208 Make CLI automatically switch from aligned to vertical format
  client/trino-cli/src/main/java/io/trino/cli/AutoTablePrinter.java
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/Query.java
  client/trino-cli/src/test/java/io/trino/cli/TestAutoTablePrinter.java
  docs/src/main/sphinx/client/cli.rst
Labels: cla-signed, docs

#15714 SqlServer Equal/Not Equal/In predicate support for case sensitive varchar columns
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Labels: cla-signed

#15071 Migrate more code to `TrinoFileSystem` in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/MetaDirStatisticsAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
Labels: cla-signed

#16131 Support creating a table with `change_data_feed_enabled` table property
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java
Labels: cla-signed, docs, tests:hive

#16196 Require driver class in Iceberg JDBC catalog
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcConnectionFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/iceberg.properties
Labels: cla-signed, docs, iceberg

#15762 Add support for Iceberg catalog warehouse property in REST
  docs/src/main/sphinx/connector/iceberg.rst
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
Labels: cla-signed, docs

#16211 Remove unnecessary override test in Phoenix connector
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#15669 Deprecate getting groups in Oauth2 authentication
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Config.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2Config.java
  docs/src/main/sphinx/security/oauth2.rst
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-http-proxy/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-https-proxy/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-refresh/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oidc-refresh/config.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oidc/config.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestExternalAuthorizerOAuth2.java
Labels: cla-signed, docs, tests:hive

#15633 Implement Hive parquet bloomfilter prune test
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestHiveParquetWithBloomFilters.java
Labels: cla-signed, tests:hive, stale

#16212 Add test for setting unsupported properties using ALTER TABLE in iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, no-release-notes, iceberg

#8323 Add Ignite connector
  .github/workflows/ci.yml
  core/trino-server/src/main/provisio/trino.xml
  docs/src/main/sphinx/connector.rst
  docs/src/main/sphinx/connector/ignite.rst
  docs/src/main/sphinx/static/img/ignite.png
  plugin/trino-ignite/pom.xml
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClientModule.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteJdbcMetadataFactory.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteOutputTableHandle.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgnitePlugin.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteTableProperties.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/ImplementAvgBigint.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/ImplementAvgDecimal.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/IgniteCreateAndInsertDataSetup.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/IgniteQueryRunner.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteCaseInsensitiveMapping.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgnitePlugin.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteTypeMapping.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestingIgniteContainer.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestingIgniteServer.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeIgnite.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteIgnite.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/ignite.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/ignite.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/tempto-configuration.yaml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/ignite/TestIgnite.java
  testing/trino-testing-services/src/main/java/io/trino/testing/SharedResource.java
Labels: enhancement, cla-signed, roadmap, docs, tests:hive

#16217 Use matching field names in QueryStatistics
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
Labels: cla-signed

#16204 Warn users if Docker arch does not match host arch
  testing/trino-testing-containers/pom.xml
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/PlatformChecks.java
  testing/trino-testing-containers/src/main/resources/testcontainers.properties
Labels: cla-signed

#16151 Add CLI options for history file and pager
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/InputReader.java
  client/trino-cli/src/main/java/io/trino/cli/Pager.java
  client/trino-cli/src/main/java/io/trino/cli/Query.java
  client/trino-cli/src/test/java/io/trino/cli/TestInsecureQueryRunner.java
  client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
  docs/src/main/sphinx/client/cli.rst
Labels: cla-signed, docs

#16228 Fix indent formatting in a printed plan
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
Labels: cla-signed

#15964 Annotate NodeRepresentation#appendDetails as a format method
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/NodeRepresentation.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
Labels: cla-signed

#16230 Assertion cleanup in TestThriftMetastoreUtil
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreUtil.java
Labels: cla-signed, tests:hive

#15951 Add config props for adaptive remote task req size
  docs/src/main/sphinx/admin/properties-query-management.rst
Labels: cla-signed, docs

#16093 Add additional catalog context to table function docs
  docs/src/main/sphinx/connector/bigquery.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/elasticsearch.rst
  docs/src/main/sphinx/connector/mariadb.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#16209 Add Trino 408 release notes
  docs/release-template.md
  docs/src/main/sphinx/release.rst
  docs/src/main/sphinx/release/release-408.md
Labels: cla-signed, release-notes, docs

#15868 Fix: use parent project id in BigQuery session
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
Labels: cla-signed, bigquery

#16208 Expose `delta.default-reader-version` and `delta.default-writer-version` delta lake configuration properties
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
Labels: cla-signed, docs, delta-lake

#16185 Join pushdown for case sensitive columns in SqlServer
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Labels: cla-signed

#16114 Fix BigQuery FTE leaving temporary tables behind
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/TemporaryTables.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnector.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadataFactory.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTransactionHandle.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTransactionManager.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/DefaultBigQueryMetadataFactory.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed

#15375 Remove distributed index join optimization
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed

#16231 Allow product tests' framework to use more memory
  testing/trino-product-tests-launcher/pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
Labels: cla-signed

#16255 Fix typo
  core/trino-spi/src/main/java/io/trino/spi/connector/ColumnSchema.java
Labels: cla-signed

#16220 Fix typo in QueryContext message
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryContext.java
Labels: cla-signed

#16270 Add deflate codec to Hive formats
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/compression/CompressionKind.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/FormatTestUtils.java
Labels: cla-signed, tests:hive

#16077 Fix failure when non-lowercase column exists in BigQuery query function
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed

#16169 Allow to override PluginManager
  core/trino-main/src/main/java/io/trino/server/PluginInstaller.java
  core/trino-main/src/main/java/io/trino/server/PluginManager.java
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
Labels: cla-signed

#16276 Do not try to pull image if it exists
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/PlatformChecks.java
Labels: cla-signed

#16260 Update TestingPhoenixServer using SharedResource
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
Labels: cla-signed, test

#16016 Check argument type before evaluating expression
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantDateTrunc.java
Labels: cla-signed, no-release-notes

#16279 Enable the ClickHouse testAddColumnConcurrently and testInsertRowConcurrently
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
Labels: cla-signed

#15995 Fix ANALYZE when Hive partition has non-canonical value
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Labels: cla-signed, tests:hive

#16274 Add Ignite jdbc config class to deny invalid connection URL
  plugin/trino-ignite/pom.xml
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClientModule.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteJdbcConfig.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteJdbcConfig.java
Labels: cla-signed

#16285 Enable testAddAndDropColumnName test for ClickHouse
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test

#16271 Add REGEX to storage formats and missing table properties
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/RegexFileWriterFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveClassNames.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestRegexTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
Labels: cla-signed, tests:hive

#15930 Fix testSetColumnTypes nested catch+verify
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#16294 Remove error closing TestingPhoenixServer
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
Labels: cla-signed

#16278 Update `labeler-config.yml` to add some connectors
  .github/config/labeler-config.yml
Labels: cla-signed, no-release-notes

#16259 Don't pull PT env images in build-pt job
  .github/workflows/ci.yml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/ConditionalPullPolicy.java
Labels: cla-signed

#16281 Add openmetrics to the testing server
  core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
Labels: cla-signed

#16120 Read spark generated statistics in hive connector
  docs/src/main/sphinx/connector/hive.rst
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreParameterParserUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftSparkMetastoreUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftSparkMetastoreUtil.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkHiveNoStatsFallback.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-hive-no-stats-fallback/hive.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-hive-no-stats-fallback/spark-defaults.conf
  testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Labels: cla-signed, docs, needs-docs, tests:hive, performance

#16300 Export variables used by the download script in check-commits action
  .github/actions/compile-commit/action.yml
Labels: cla-signed

#15637 Reorganize Hive connector and Hive security documentation
  docs/src/main/sphinx/connector/hive-security.rst
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#16304 Move `VACUUM` under `SQL support` section
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#16243 Document separator examples for csv files
  docs/src/main/sphinx/connector/hive.rst
Labels: cla-signed, docs

#16297 Fix jdbc ResultSet getBoolean throw ClassCastException
  client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
Labels: cla-signed, jdbc

#16261 Fix for ClickHouse sql injection by removing ability to have expression in table options
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
Labels: cla-signed
