Repository trinodb/trino, pull requests merged in 2023-12, with the labels that each got.

#17016 Remove support create table with location in Delta Lake connector
  docs/src/main/sphinx/connector/delta-lake.md
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLegacyCreateTableWithExistingLocation.java
Labels: cla-signed, docs, delta-lake

#19982 Make S3FileSystemFactory use configured AWS access keys for STS calls
  lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
Labels: cla-signed, tests:hive

#19993 Make method private
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: no-release-notes

#19995 Add queryState to debug info in EventDrivenFaultTolerantQueryScheduler
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed, no-release-notes

#19965 Fix removal of stats files in Iceberg orpan file cleanup
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#20002 Do not fail stage after already done
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#19994 Update Maven to 3.9.6
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#19539 Fix docs render for date_parse
  docs/src/main/sphinx/functions/datetime.md
Labels: cla-signed, docs

#20018 Cleanup JSON response from fetchers
  core/trino-main/src/main/java/io/trino/server/remotetask/ContinuousTaskStatusFetcher.java
  core/trino-main/src/main/java/io/trino/server/remotetask/DynamicFiltersFetcher.java
Labels: cla-signed

#19945 Ensure jq exists before executing the script
  core/docker/build.sh
Labels: cla-signed

#19976 Extract common logic for filtering row groups in parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetWriteValidation.java
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/RowGroupInfo.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Labels: cla-signed, tests:hive, hudi, iceberg, hive

#20022 Cleanup JSON response from TaskInfoFetcher
  core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
Labels: cla-signed

#20023 Cleanup outputTaskFailureListeners on query complete
  core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
Labels: cla-signed

#19968 Add `from_date_string` as example Trino routine
  docs/src/main/sphinx/routines/examples.md
Labels: cla-signed, docs

#20028 Avoid concatenation in checkArgument messages
  core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedQueryScheduler.java
  core/trino-main/src/main/java/io/trino/metadata/GlobalFunctionCatalog.java
  core/trino-main/src/main/java/io/trino/metadata/InternalFunctionBundle.java
  core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java
  core/trino-main/src/main/java/io/trino/operator/TaskContext.java
  core/trino-main/src/main/java/io/trino/operator/window/matcher/IrRowPatternToProgramRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithoutProjection.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedScalarSubquery.java
  core/trino-main/src/main/java/io/trino/sql/planner/rowpattern/LogicalIndexPointer.java
  core/trino-main/src/main/java/io/trino/util/StatementUtils.java
  core/trino-main/src/test/java/io/trino/block/BlockAssertions.java
  core/trino-parser/src/main/java/io/trino/sql/tree/FunctionCall.java
  core/trino-parser/src/main/java/io/trino/sql/tree/PlanSiblings.java
  core/trino-parser/src/main/java/io/trino/sql/tree/SkipTo.java
  core/trino-parser/src/main/java/io/trino/sql/tree/WindowOperation.java
  lib/trino-orc/src/main/java/io/trino/orc/reader/ColumnReaders.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/NestedColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatDefinitionLevelDecoder.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetTypeVisitor.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
  testing/trino-testing/src/main/java/io/trino/testing/statistics/StatsContext.java
Labels: cla-signed, tests:hive, mongodb

#20007 Fix potential infinite loop at IterativeOptimizer with Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, iceberg

#19978 Use concurrent hash map for tracking query memory
  core/trino-main/src/main/java/io/trino/memory/MemoryPool.java
  core/trino-main/src/main/java/io/trino/memory/QueryContext.java
Labels: cla-signed

#20038 Do not synch on getting memory pool since it's final
  core/trino-main/src/main/java/io/trino/memory/QueryContext.java
Labels: no-release-notes

#20039 Test checkpoint filtering on table with multiple partition fields
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java
Labels: cla-signed, delta-lake

#20036 Run trino-tests JUnit tests
  testing/trino-tests/pom.xml
  testing/trino-tests/src/test/java/io/trino/execution/TestExecutionJmxMetrics.java
  testing/trino-tests/src/test/java/io/trino/execution/TestRefreshMaterializedView.java
  testing/trino-tests/src/test/java/io/trino/tests/TestQueryPlanDeterminism.java
  testing/trino-tests/src/test/java/io/trino/tests/TestQuerySpillLimits.java
  testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
Labels: cla-signed

#19938 Mention SELinux in README Docker section
  README.md
Labels: cla-signed

#19940 Turn off SELinux in doc build container
  docs/build
Labels: cla-signed, docs

#20024 Add numeric integer to decimal coercion for hive tables
  docs/src/main/sphinx/connector/hive.md
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/DecimalCoercers.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDecimalCoercers.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Labels: cla-signed, docs, tests:hive, hive

#20052 Produce a more actionable error on wrong JDBC URL
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/TracingDataSource.java
Labels: cla-signed

#19998 Test code cleanup around testJoinPushdown
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed, test, no-release-notes

#20041 Rely only on table handle for stopping condition
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, iceberg

#20056 Upgrade GCS connector to 3.0.0
  lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsAccessTokenProvider.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsStorageFactory.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GoogleGcsConfigurationInitializer.java
  pom.xml
Labels: cla-signed

#20065 Support for 0 length dictionary copyRegion
  core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
Labels: cla-signed

#20073 Rename methods to correspond to the configuration setting
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
Labels: cla-signed, no-release-notes, delta-lake

#20079 Respect Glue partition column type with CSV
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
Labels: cla-signed, tests:hive, hive

#19500 Add date to varchar coercion for hive
  docs/src/main/sphinx/connector/hive.md
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/DateCoercer.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDateCoercer.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Labels: cla-signed, release-notes, docs, tests:hive, hive

#20076 Use correct HostnameVerifier when verify-hostnames set to true
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
Labels: cla-signed

#20084 Update AWS SDK v1 to 1.12.610
  pom.xml
Labels: cla-signed

#20061 Add example SQL routines for formatting bytes
  docs/src/main/sphinx/routines/examples.md
Labels: cla-signed, docs

#19810 Upgrade Hudi version to 0.14.0
  plugin/trino-hudi/pom.xml
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java
Labels: cla-signed, hudi

#20037 Remove product tests targeting Hive 2 or older
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMaterializedView.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTableInsert.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestReadUniontype.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestRoles.java
Labels: cla-signed, tests:hive

#20078 Add a config to toggle local scheduling of Mongo splits
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoServerDetailsProvider.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSplitManager.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/SessionBasedMongoServerDetailsProvider.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
Labels: cla-signed, mongodb

#19939 Speed up Materialized Views metadata access
  core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
  core/trino-main/src/main/java/io/trino/metadata/MaterializedViewDefinition.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
  core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
  core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
  core/trino-main/src/test/java/io/trino/execution/TestAddColumnTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCommentTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropColumnTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameColumnTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestRenameViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetColumnTypeTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSetPropertiesTask.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
  core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
  core/trino-main/src/test/java/io/trino/testing/TestTestingMetadata.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMaterializedViewDefinition.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
  testing/trino-tests/src/test/java/io/trino/execution/TestRefreshMaterializedView.java
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
  testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
Labels: cla-signed, tests:hive, iceberg, hive, bigquery

#20067 Replace TableToPartitionMapping with hiveColumnCoercion map
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveSplit.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableToPartitionMapping.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplit.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestTableToPartitionMapping.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java
Labels: cla-signed, tests:hive, hive

#20100 Fix incorrect LIKE for patterns with repeating substrings
  core/trino-main/src/main/java/io/trino/likematcher/FjsMatcher.java
  core/trino-main/src/test/java/io/trino/likematcher/TestLikeMatcher.java
Labels: cla-signed

#20105 Add docs for mongodb.allow-local-scheduling
  docs/src/main/sphinx/connector/mongodb.md
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
Labels: cla-signed, docs, mongodb

#18017 Add support for json_table
  core/trino-main/src/main/java/io/trino/metadata/FunctionManager.java
  core/trino-main/src/main/java/io/trino/metadata/GlobalFunctionCatalog.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/operator/TableFunctionOperator.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTable.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTableColumn.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTableOrdinalityColumn.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTablePlanCross.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTablePlanLeaf.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTablePlanNode.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTablePlanSingle.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTablePlanUnion.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTableQueryColumn.java
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTableValueColumn.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/Column.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/ExecutionPlanner.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/FragmentCross.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/FragmentLeaf.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/FragmentSingle.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/FragmentUnion.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/JsonTableProcessingFragment.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/OrdinalityColumn.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/QueryColumn.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/SequenceEvaluator.java
  core/trino-main/src/main/java/io/trino/operator/table/json/execution/ValueColumn.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/JsonPathAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/ResolvedFunctionCallRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
  core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
  core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
  core/trino-main/src/test/java/io/trino/metadata/TestGlobalFunctionCatalog.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/planner/JsonTablePlanComparator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestJsonTable.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestingPlannerContext.java
  core/trino-main/src/test/java/io/trino/sql/query/TestJsonTable.java
  core/trino-main/src/test/java/io/trino/type/TestJsonPath2016TypeSerialization.java
  core/trino-parser/src/main/java/io/trino/sql/jsonpath/PathParser.java
  core/trino-parser/src/test/java/io/trino/sql/jsonpath/TestPathParser.java
  core/trino-spi/src/main/java/io/trino/spi/StandardErrorCode.java
Labels: cla-signed

#20108 Add docs for elasticsearch.tls.verify-hostnames
  docs/src/main/sphinx/connector/elasticsearch.md
Labels: cla-signed, docs

#20107 Revert "Allow differentiating materialized views from tables efficiently"
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTable.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#20000 Add Trino 435 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-435.md
Labels: cla-signed, release-notes, docs

#20106 Minor cleanup in Kudu connector
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/TypeHelper.java
Labels: cla-signed

#20095 Speed-up bigquery tests
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, bigquery

#20097 Use default stats column filter for the retrieval of active files in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
Labels: cla-signed, delta-lake

#20119 Disable failing bigquery test
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, bigquery

#20122 Fix serialization failure when invoking json_table
  core/trino-main/src/main/java/io/trino/operator/table/json/JsonTable.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#20104 Disallow changing the location of a table in CREATE OR REPLACE statement
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#19806 Flush PagePartitioner dictionaries before release
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
  core/trino-main/src/main/java/io/trino/operator/output/PartitionedOutputOperator.java
  core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderPageBuilder.java
  core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPartitionedOutputOperator.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppenderPageBuilder.java
Labels: cla-signed

#19524 Ensure "nessie.commit.id table" property is set when updating the table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperations.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed, tests:hive, iceberg

#20127 Make logPaths and listeners final
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
Labels: cla-signed

#20121 Process only files smaller than the threshold for OPTIMIZE
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Labels: cla-signed, delta-lake

#20136 Log finalQueryInfo when FTE scheduler stalled
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#20135 Increase GCLocker retries for Maven
  .mvn/jvm.config
Labels: cla-signed, no-release-notes

#20134 Fix table listing concurrency in FileHiveMetastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
Labels: cla-signed, tests:hive, no-release-notes, hive

#20137 Increase timeout for TestWindow.testManyFunctionsWithSameWindow
  core/trino-main/src/test/java/io/trino/sql/query/TestWindow.java
Labels: cla-signed

#19944 Adjust BigQuery CI profile
  .github/workflows/ci.yml
  plugin/trino-bigquery/pom.xml
Labels: cla-signed, bigquery

#20124 Minor refactoring of the bin-packing allocator's candidate logic
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
Labels: cla-signed

#20141 Update requirement to Oracle 19
  docs/src/main/sphinx/connector/oracle.md
Labels: cla-signed, docs

#20144 Reduce repetitions of testCreateFileRetry
  lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java
Labels: cla-signed, tests:hive

#20140 Convert PTL tests to JUnit
  testing/trino-product-tests-launcher/pom.xml
  testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestInvocations.java
  testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestOptionsPrinter.java
  testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/env/TestConfigurations.java
  testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/local/TestManuallyJdbcOauth2.java
  testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/util/TestConsoleTable.java
Labels: cla-signed

#20163 Fix Flaky BaseHiveConnectorTest.testMultipleWritersWithSkewedData
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive, hive

#20053 Add an example for listagg with filter
  docs/src/main/sphinx/functions/aggregate.md
Labels: cla-signed, docs

#20060 Add example SQL routines for charts
  docs/src/main/sphinx/routines/examples.md
Labels: cla-signed, docs

#20169 Add comment why disabling pushdown on MariaDB REAL type
  plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
Labels: cla-signed, no-release-notes

#20174 Expand catalog routine docs
  docs/src/main/sphinx/routines/introduction.md
Labels: cla-signed, docs

#20162 Document filtering during aggregation for listagg
  docs/src/main/sphinx/functions/aggregate.md
Labels: cla-signed, docs

#20176 Randomize identifiers in BaseSqlServerConnectorTest
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Labels: cla-signed, maintenance, no-release-notes

#20183 Fix page partitioner output bytes on release handling
  core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
  core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java
Labels: bug, cla-signed

#20187 Remove redundant air.test.parallel property
  plugin/trino-cassandra/pom.xml
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-pinot/pom.xml
  plugin/trino-sqlserver/pom.xml
Labels: cla-signed

#20181 Fix dereference in SQL routine
  core/trino-main/src/main/java/io/trino/sql/gen/DereferenceCodeGenerator.java
  core/trino-main/src/main/java/io/trino/sql/relational/ConstantExpression.java
  core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/gen/TestInCodeGenerator.java
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#20196 Fix TestAccessControl execution
  testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Labels: cla-signed, test, no-release-notes

#20195 Add tracing for query start
  core/trino-main/src/main/java/io/trino/execution/SqlQueryManager.java
Labels: cla-signed

#20170 Factor out common code in TestUniformNodeSelector
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestUniformNodeSelector.java
Labels: cla-signed

#20208 Warn about unexpected task updates
  core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
Labels: cla-signed

#20063 Add example SQL routines for formatting topn results
  docs/src/main/sphinx/routines/examples.md
Labels: cla-signed, docs

#20194 Add tracing for SplitManager.getSplits
  core/trino-main/src/main/java/io/trino/split/SplitManager.java
Labels: cla-signed, no-release-notes

#20185 Hide FTE tests configs
  core/trino-main/src/main/java/io/trino/execution/FailureInjectionConfig.java
Labels: cla-signed, no-release-notes

#20177 Fix placement of precision parameter of WITH TIME ZONE types
  client/trino-client/src/main/java/io/trino/client/ClientTypeSignature.java
  client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
Labels: cla-signed, jdbc

#19813 Throw IndexOutOfBoundsException in MemoryInputStream
  lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryInputStream.java
  lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
  lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsTrinoInputStream.java
Labels: bug, cla-signed, tests:hive

#20202 Catch exception in sendUpdate
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Labels: cla-signed

#20205 Restore lifecycle annotations in tests
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTypeMapping.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFlushMetadataCacheProcedure.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeReadTimestamps.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedHiveMetastoreWithViews.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestSplitPruning.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeConcurrentModificationGlueMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRenameToWithGlueMetastore.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidTypeMapping.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchBackpressure.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConcurrentModificationGlueMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreWithQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3FileSystemAccessOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGetTableStatisticsOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataListing.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergReadVersionedTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergReadVersionedTableByTemporal.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogSkipArchive.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDecimalColumns.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTypeMapping.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoCaseInsensitiveMapping.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreTypeMapping.java
  testing/trino-tests/src/test/java/io/trino/connector/informationschema/TestInformationSchemaConnector.java
  testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestKillQuery.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
  testing/trino-tests/src/test/java/io/trino/execution/TestQueryTracker.java
  testing/trino-tests/src/test/java/io/trino/execution/TestRefreshMaterializedView.java
  testing/trino-tests/src/test/java/io/trino/tests/TestGetTableStatisticsOperations.java
  testing/trino-tests/src/test/java/io/trino/tests/TestProcedureCall.java
Labels: cla-signed, tests:hive, iceberg, delta-lake, hive, mongodb

#20214 Adjust logging level to debug
  core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
Labels: cla-signed

#20217 Update JLine to 3.25.0
  client/trino-cli/pom.xml
Labels: cla-signed

#19627 Fix SQL Server DATETIMEOFFSET for old dates
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
Labels: cla-signed

#20216 Only log null spooling stats in FTE mode
  core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
  core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
Labels: cla-signed

#20223 Fix failing test on master
  core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPredicatePushdownWithoutDynamicFilter.java
Labels: cla-signed

#20189 Use explicit values for MaxResults in all Glue APIs
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, tests:hive, hive

#20243 Add Delta table read version to connectorInfo
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeInputInfo.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
Labels: cla-signed, delta-lake

#20240 Fix case in RN section header
  docs/src/main/sphinx/release/release-434.md
Labels: cla-signed, release-notes, docs

#20224 Refactor IcebergSplitSource to reduce per split operations
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed, iceberg
