Repository trinodb/trino, pull requests merged in 2023-06, with the labels that each got.

#17723 Retry Hive view tests on HS2 failure
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
Labels: cla-signed, tests:hive

#17724 Update to Tempto 196
  pom.xml
Labels: cla-signed

#17726 Remove deprecated google Base64 class usage
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticBigQueryCredentialsSupplier.java
Labels: cla-signed, bigquery

#17715 Bump Iceberg from 1.2.1 to 1.3.0
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
Labels: cla-signed, iceberg

#17728 Fix 411 release notes for incorrect issue verbiage, removed repeated phrases
  docs/src/main/sphinx/release/release-411.md
Labels: cla-signed, release-notes, docs

#17718 Remove obsolete comment and code from `IcebergAvroPageSource`
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroPageSource.java
Labels: cla-signed, no-release-notes, iceberg

#16879 require a space in front of timezone if there is no time information in casting string to timestamp
  client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
  core/trino-main/src/main/java/io/trino/type/DateTimes.java
  core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
Labels: cla-signed, jdbc

#17730 Iceberg connector copy edits and format improvements
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#17741 Remove unnecessary dependency in Hudi connector
  plugin/trino-hudi/pom.xml
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/timeline/TimelineLayout.java
Labels: cla-signed, hudi

#17739 Fix CI job for trino-filesystem-s3
  .github/workflows/ci.yml
Labels: cla-signed

#17737 Increase max possible value for write.batch-size
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcWriteConfig.java
Labels: cla-signed

#17688 Replace GroupIdBlock with int[]
  core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/DistinctLimitOperator.java
  core/trino-main/src/main/java/io/trino/operator/GroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/GroupByHashPageIndexer.java
  core/trino-main/src/main/java/io/trino/operator/GroupByIdBlock.java
  core/trino-main/src/main/java/io/trino/operator/GroupedTopNRankAccumulator.java
  core/trino-main/src/main/java/io/trino/operator/GroupedTopNRankBuilder.java
  core/trino-main/src/main/java/io/trino/operator/GroupedTopNRowNumberAccumulator.java
  core/trino-main/src/main/java/io/trino/operator/GroupedTopNRowNumberBuilder.java
  core/trino-main/src/main/java/io/trino/operator/MarkDistinctHash.java
  core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/NoChannelGroupByHash.java
  core/trino-main/src/main/java/io/trino/operator/RowNumberOperator.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/AggregationMask.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/DistinctAccumulatorFactory.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/GroupedAccumulator.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/GroupedAggregator.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/partial/SkipAggregationBuilder.java
  core/trino-main/src/main/java/io/trino/operator/index/UnloadedIndexKeyRecordSet.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupByHashOnSimulatedData.java
  core/trino-main/src/test/java/io/trino/operator/CyclingGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/TestCyclingGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/AggregationTestUtils.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/BenchmarkDecimalAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/BenchmarkGroupedTypedHistogram.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestArrayAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestHistogram.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/groupby/AggregationTestInput.java
  core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSpatialPartitioningInternalAggregation.java
Labels: cla-signed

#17754 Update AWS SDK v2 to 2.20.78
  pom.xml
Labels: cla-signed

#17767 Remove redundant type casting in RestCatalogTestUtils
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/RestCatalogTestUtils.java
Labels: cla-signed, iceberg

#17769 Use config default for determine_partition_count_for_write_enabled
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
Labels: cla-signed, no-release-notes

#17756 Oracle turns off auto commit to drop temporary table
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
Labels: cla-signed

#17642 Refer ${project.version} instead of hardcoded version in trino-test-jdbc-compatibility-old-driver pom.xml
  testing/trino-test-jdbc-compatibility-old-driver/pom.xml
Labels: cla-signed

#17594 Correct code example for CLI auth with env variable
  docs/src/main/sphinx/client/cli.rst
Labels: cla-signed, docs

#17755 Update testcontainers to 1.18.3
  pom.xml
Labels: cla-signed

#17772 Remove outdated SPI revapi exclusions
  core/trino-spi/pom.xml
Labels: cla-signed, no-release-notes

#17777 Add support for any_value aggregation function
  core/trino-main/src/main/java/io/trino/operator/aggregation/ArbitraryAggregationFunction.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestAnyValueAggregation.java
Labels: cla-signed, needs-docs

#17800 Fix flaky testCommentColumn in BigQuery
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, no-release-notes, bigquery

#17798 Remove unused method from BigQueryPseudoColumn
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java
Labels: cla-signed, no-release-notes, bigquery

#17782 Fix tests for underestimating size of partitioned Glue hive tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Labels: cla-signed, tests:hive, hive

#17802 Update speculative flag for running tasks
  core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#17790 Only schedule FTE task if it received non-replicated splits
  core/trino-main/src/main/java/io/trino/execution/scheduler/ArbitraryDistributionSplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/HashDistributionSplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SingleDistributionSplitAssigner.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/SplitAssigner.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestEventDrivenTaskSource.java
Labels: cla-signed

#17805 Create `test` schema explicitly in TestMongoConnectorTest
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Labels: cla-signed, no-release-notes

#17686 Improve details in SHOW STATS documentation
  docs/src/main/sphinx/language/types.rst
  docs/src/main/sphinx/sql/show-stats.rst
Labels: cla-signed, docs

#17658 Add documentation for SET PATH
  docs/src/main/sphinx/sql.md
  docs/src/main/sphinx/sql/set-path.rst
Labels: cla-signed, docs

#17801 Ban javax.annotation dependency
  plugin/trino-bigquery/pom.xml
  plugin/trino-exchange-filesystem/pom.xml
  plugin/trino-pinot/pom.xml
  pom.xml
  testing/trino-benchto-benchmarks/pom.xml
Labels: cla-signed, bigquery

#17807 Remove redundant migration to table format version `2`
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, no-release-notes

#17814 Create `test` schema only if not exists in TestMongoConnectorTest
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Labels: cla-signed, no-release-notes, mongodb

#17810 Retry test on TestAvroSchemaUrl
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
Labels: tests:hive, no-release-notes

#17799 Remove unused code from MongoDB
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoIndex.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
Labels: cla-signed, no-release-notes, mongodb

#17824 Revert "Remove unnecessary separate CI job for Redshift"
  .github/workflows/ci.yml
Labels: cla-signed

#17811 Import checkArgument statically
  core/trino-spi/src/main/java/io/trino/spi/function/table/Descriptor.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/DescriptorArgument.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableFunctionAnalysis.java
Labels: cla-signed

#17826 Fix invalid workflow file for ok-to-test
  .github/workflows/ok-to-test.yml
Labels: cla-signed, no-release-notes

#17821 Document bigquery.rpc-proxy.enabled
  docs/src/main/sphinx/connector/bigquery.rst
Labels: cla-signed, docs

#17832 Implement tail char test for Phoenix
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#17818 Reduce Spark log in Iceberg product tests
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIceberg.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergJdbcCatalog.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergRest.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/spark/log4j2.properties
Labels: cla-signed

#17833 Fix Phoenix create test table with remote executor error
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#17830 Fix deprecation warning for license checker plugin
  core/trino-server-rpm/pom.xml
Labels: cla-signed

#17664 Use ResolvedFunction#isDeterministic
  core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/relational/optimizer/ExpressionOptimizer.java
Labels: cla-signed

#17838 Reduce Spark log in Delta Lake OSS product tests
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
Labels: cla-signed, no-release-notes

#17845 Add OperatorContext to WorkProcessorSourceOperatorFactory.create
  core/trino-main/src/main/java/io/trino/operator/ScanFilterAndProjectOperator.java
  core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorAdapter.java
  core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorFactory.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorSourceOperatorAdapter.java
Labels: cla-signed

#17846 Extract pure createSplitSource and drop visitScanAndFilter
  core/trino-main/src/main/java/io/trino/sql/planner/SplitSourceFactory.java
Labels: cla-signed

#17857 fix JSON formatting issue in file-based access control docs
  docs/src/main/sphinx/security/file-system-access-control.rst
Labels: cla-signed, docs

#17856 Relocate javax classes in trino-jdbc
  .github/workflows/ci.yml
  client/trino-jdbc/pom.xml
  service/trino-verifier/pom.xml
Labels: cla-signed, jdbc

#17844 Support RLE DictionaryBlock.dictionary in UnnestingPositionsAppender
  core/trino-main/src/main/java/io/trino/operator/output/RleAwarePositionsAppender.java
  core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java
Labels: cla-signed

#17834 Round targetPartitionSizeInBytes to a multiple of minTargetPartitionSizeInBytes
  core/trino-main/src/main/java/io/trino/execution/scheduler/ArbitraryDistributionSplitAssigner.java
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestArbitraryDistributionSplitAssigner.java
Labels: cla-signed

#17788 Disallow the usage of invalid object names in HMS
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Labels: cla-signed, tests:hive, no-release-notes, hive

#17871 Fix Iceberg scheduling failure due to dynamic filters
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
Labels: cla-signed, iceberg

#17872 Place `Updating data` section on the same level as `Procedures` section
  docs/src/main/sphinx/connector/delta-lake.rst
Labels: cla-signed, docs

#17835 Add docs for any_value aggregation function
  docs/src/main/sphinx/functions/aggregate.rst
  docs/src/main/sphinx/functions/list-by-topic.rst
  docs/src/main/sphinx/functions/list.rst
Labels: cla-signed, docs

#17874 Add support for RENAME COLUMN in MongoDB
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Labels: cla-signed, mongodb

#17656 Use uppercase for web ui authentication types in docs
  docs/src/main/sphinx/admin/properties-web-interface.rst
  docs/src/main/sphinx/admin/web-interface.rst
Labels: cla-signed, docs

#16634 Allow forcing delta lake to recalculate all statistics
  docs/src/main/sphinx/connector/delta-lake.rst
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AnalyzeHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeAnalyzeProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Labels: cla-signed, docs, delta-lake

#17877 Fix filterDataMappingSmokeTestData in ClickHouse
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed, no-release-notes

#17860 Mark Oracle FailureRecovery tests as flaky
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleFailureRecoveryTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Labels: cla-signed

#17870 Skip unsupported tests in BaseBigQueryFailureRecoveryTest
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java
Labels: cla-signed, no-release-notes, bigquery

#17896 Remove unused method
  core/trino-main/src/main/java/io/trino/operator/Driver.java
Labels: cla-signed

#17778 Update myst-parser version for docs
  docs/build
  docs/requirements.in
  docs/requirements.txt
Labels: cla-signed, docs

#17901 Fix HudiMetadata.getTableMetadata for views
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
Labels: cla-signed, RELEASE-BLOCKER, hudi

#17864 Add info about docs container
  docs/README.md
Labels: cla-signed, docs

#17911 Fix kubernetes doc typos
  docs/src/main/sphinx/installation/kubernetes.rst
Labels: cla-signed

#17908 Fix typo
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/HiveFileIterator.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixPageSourceProvider.java
Labels: cla-signed, tests:hive, no-release-notes, hive

#17918 Pass and use provided OutputStream in every Launcher command
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/LauncherModule.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentList.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentUp.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/Launcher.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/LauncherCommand.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteDescribe.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteList.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteRun.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentFactory.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentProvider.java
  testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestInvocations.java
Labels: cla-signed

#17876 Enforce limit on FTE max partition count
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
Labels: cla-signed

#17904 Test accuracy of reading from Delta tables restored to previous version
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTimeTravelCompatibility.java
Labels: cla-signed, tests:hive, no-release-notes, delta-lake

#17903 Make expected failure message self-explanatory
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
Labels: cla-signed, test, delta-lake

#17789 Rename variable
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
Labels: cla-signed, tests:hive, no-release-notes, iceberg, delta-lake, hive

#17935 Fix typo in config 'exchange.source-concurrent-readers' doc
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#17497 Add `catalogVersion` into `QueryInputMetadata` & `QueryOutputMetadata`
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
  core/trino-main/src/main/java/io/trino/execution/Input.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/Output.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/InputExtractor.java
  core/trino-main/src/test/java/io/trino/execution/TestInput.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestOutput.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryInputMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryOutputMetadata.java
  plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
Labels: cla-signed

#17926 Modify projection pushdown config description
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
Labels: cla-signed, iceberg, delta-lake

#17936 Fix build-pt not to download containers when custom JDK used
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/jdk/TarDownloadingJdkProvider.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/util/DirectoryUtils.java
Labels: cla-signed, no-release-notes

#17905 Don't retry table metadata read when fails with ValidationException
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#17930 Add test for S3 and Glue metastore
  .github/workflows/ci.yml
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
  plugin/trino-hive/pom.xml
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/S3Assert.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java
Labels: cla-signed, tests:hive, no-release-notes, iceberg, delta-lake, hive

#17941 Update error-prone to 2.20.0
  pom.xml
Labels: cla-signed

#17943 Prevent accidental image pulls in getDockerArchitectureInfo
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/ConditionalPullPolicy.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/TestContainers.java
Labels: cla-signed, no-release-notes

#17952 Externalize configuration of testing AWS resources
  .github/workflows/ci.yml
Labels: cla-signed, test, no-release-notes

#17949 Add another failure pattern in SQL Server concurrent modification test
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Labels: cla-signed, no-release-notes

#17951 Remove redundant property in git-commit-id-maven-plugin
  pom.xml
Labels: cla-signed

#17957 Skip detailed project pushdown tests with CTAS not supported
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes

#17938 Update redlinerpm-maven-plugin to 2.1.8
  core/trino-server-rpm/pom.xml
Labels: cla-signed

#17965 Fix CI runs from forks
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
Labels: cla-signed

#17968 Clean up maven-shade-plugin configurations
  client/trino-jdbc/pom.xml
  lib/trino-phoenix5-patched/pom.xml
  pom.xml
Labels: cla-signed, jdbc

#17958 Avoid creating Hive tables with double slashed location
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
Labels: cla-signed, tests:hive, iceberg, delta-lake, hive

#17975 Reduce string concatenation in ProtocolHeaders
  client/trino-client/src/main/java/io/trino/client/ProtocolHeaders.java
Labels: cla-signed

#17978 Revert optimization to reorder columns in parquet writer
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
  lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
Labels: cla-signed, correctness, RELEASE-BLOCKER, tests:hive

#17981 Change MinIO bucket names not to look like S3's
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemMinio.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHiveHudiRedirections.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHudi.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToHudi.java
Labels: cla-signed, tests:hive, no-release-notes, delta-lake, hive

#17854 Disable Jackson default JSON processing limits
  .mvn/modernizer/violations.xml
  client/trino-cli/src/main/java/io/trino/cli/JsonPrinter.java
  core/trino-main/src/main/java/io/trino/operator/scalar/JsonExtract.java
  core/trino-main/src/main/java/io/trino/operator/scalar/JsonFunctions.java
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonExtract.java
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonDeserializer.java
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonTypeUtil.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonUtils.java
  lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/util/TestJsonUtils.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusQueryResponseParse.java
  service/trino-proxy/pom.xml
  service/trino-proxy/src/main/java/io/trino/proxy/ProxyResource.java
  service/trino-verifier/pom.xml
  service/trino-verifier/src/main/java/io/trino/verifier/JsonEventClient.java
  testing/trino-benchmark/pom.xml
  testing/trino-benchmark/src/main/java/io/trino/benchmark/JsonBenchmarkResultWriter.java
  testing/trino-benchmark/src/main/java/io/trino/benchmark/OdsBenchmarkResultWriter.java
Labels: cla-signed, tests:hive, iceberg

#17924 Add workaround for Kafka Confluent Schema Registry error on startup
  docs/src/main/sphinx/connector/kafka.rst
Labels: cla-signed, docs

#17989 Update AWS SDK v2 to 2.20.89
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/ByteBufferAsyncRequestBody.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
  pom.xml
Labels: cla-signed

#17927 Improve feedback from CI runs with all secrets
  .github/actions/update-check/action.yml
  .github/workflows/ci.yml
Labels: cla-signed

#17993 Remove build module dependency
  plugin/trino-hudi/pom.xml
Labels: cla-signed, hudi

#17987 Remove unused setup in TestAnalyzer
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed, test, no-release-notes

#18019 Fix broken release process
  testing/trino-test-jdbc-compatibility-old-driver/pom.xml
Labels: cla-signed, RELEASE-BLOCKER

#18009 Fix syntax error in update checks action
  .github/actions/update-check/action.yml
Labels: cla-signed

#17869 Update to Hadoop 3.3.5
  pom.xml
Labels: cla-signed, tests:hive, tests:all, tests:all-product

#18007 Update AWS SDK v1 to 1.12.493
  pom.xml
Labels: cla-signed

#18037 Add missing return in BigQueryStorageAvroPageSource
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
Labels: cla-signed, bigquery

#17995 Use Block#bytesCompare for comparisions with strings
  core/trino-main/src/test/java/io/trino/sql/gen/BenchmarkPageProcessor.java
  core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
  core/trino-spi/src/main/java/io/trino/spi/type/VarcharType.java
Labels: cla-signed

#18043 Drop unused `consecutive` method
  core/trino-main/src/main/java/io/trino/operator/aggregation/partial/SkipAggregationBuilder.java
Labels: cla-signed

#16308 Add support for appending queries in sql based connectors
  docs/src/main/sphinx/connector/clickhouse.rst
  docs/src/main/sphinx/connector/druid.rst
  docs/src/main/sphinx/connector/ignite.rst
  docs/src/main/sphinx/connector/mysql.rst
  docs/src/main/sphinx/connector/oracle.rst
  docs/src/main/sphinx/connector/phoenix.rst
  docs/src/main/sphinx/connector/postgresql.rst
  docs/src/main/sphinx/connector/query-comment-format.fragment
  docs/src/main/sphinx/connector/redshift.rst
  docs/src/main/sphinx/connector/singlestore.rst
  docs/src/main/sphinx/connector/sqlserver.rst
Labels: cla-signed, docs

#18034 Replace TypedSet with new BlockSet
  core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/MultimapAggregationFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayDistinctFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayExceptFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayIntersectFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ArrayUnionFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/BlockSet.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MapConcatFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MapToMapCast.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
  core/trino-main/src/main/java/io/trino/operator/scalar/MultimapFromEntriesFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArrayDistinct.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestBlockSet.java
  core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
Labels: cla-signed

#18048 Add missing return in BigQueryQueryPageSource
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
Labels: cla-signed, bigquery

#18049 Fix error message in SqlTimestampWithTimeZone
  core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestampWithTimeZone.java
Labels: cla-signed

#18042 Add product test for reading parquet files with reordered data
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestParquetFileWithReorderedColumns.java
  testing/trino-product-tests/src/main/resources/parquet/reordered_columns.parquet
Labels: cla-signed, tests:hive

#17988 Disallow aggregation function as `UNNEST` parameter
  core/trino-main/src/main/java/io/trino/metadata/InternalFunctionBundle.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Labels: cla-signed

#18058 Allow setting catalog in Kafka query runner
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunnerBuilder.java
Labels: cla-signed

#18059 Update maven to 3.9.3
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#18029 Clarify need for exchange manager configuration
  docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Labels: cla-signed, docs

#18061 Prevent window operator from failing when it's aborted
  core/trino-main/src/main/java/io/trino/operator/WindowInfo.java
  core/trino-main/src/test/java/io/trino/operator/TestWindowOperator.java
Labels: cla-signed, release-notes

#18051 Add Avro to "File formats" in Iceberg documentation
  docs/src/main/sphinx/connector/iceberg.rst
Labels: cla-signed, docs

#18079 Enable Error Prone check: BadComparable
  pom.xml
Labels: cla-signed

#18076 Display Hive partition projection column properties
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/aws/athena/PartitionProjectionService.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive, hive

#18083 Remove unused code from MongoDB ObjectIdType
  plugin/trino-mongodb/pom.xml
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdType.java
Labels: cla-signed, mongodb

#18086 Simplify the creation of HiveQueryRunner
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
Labels: cla-signed, tests:hive, hive

#18077 Enable Error Prone check: GetClassOnEnum
  pom.xml
Labels: cla-signed

#17816 Fix concat_ws with array type don't support length exceed 254
  core/trino-main/src/main/java/io/trino/operator/scalar/ConcatFunction.java
  core/trino-main/src/main/java/io/trino/operator/scalar/ConcatWsFunction.java
  core/trino-main/src/test/java/io/trino/operator/scalar/TestConcatWsFunction.java
Labels: cla-signed
