Repository trinodb/trino, pull requests merged in 2024-03, with the labels that each got.

#18133 Simplify DeltaLakeMetadata with new model class
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTable.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
Labels: cla-signed, no-release-notes, delta-lake

#20799 Improve docs for HTTP client config with Thrift metastore
  docs/src/main/sphinx/connector/metastores.md
Labels: cla-signed, docs

#20860 Allow to define multiple retry strategies for JDBC connection
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingConnectionFactory.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingConnectionFactoryModule.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestRetryingConnectionFactory.java
  plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java
Labels: cla-signed

#20777 Revert "Add RetryMode to ConnectorTableFunction.analyze"
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ConnectorTableFunction.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorTableFunction.java
Labels: cla-signed

#17953 Support subqueries in UNNEST
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/query/TestUnnest.java
Labels: cla-signed, stale

#20891 Allow loading of dynamic agents
  core/docker/default/etc/jvm.config
  core/trino-server-rpm/src/main/resources/dist/config/jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config
Labels: cla-signed, no-release-notes

#20906 Fix failure when check constraint is null
  core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
  core/trino-main/src/test/java/io/trino/sql/query/TestCheckConstraint.java
Labels: cla-signed

#20908 Cleanup tests in Iceberg
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java
Labels: cla-signed, iceberg

#20851 Enable caching of checkpoint files in Delta lake filesystem cache
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/cache/DeltaLakeCacheKeyProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/MetaDirStatisticsAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/README.md
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/_change_data/key=1/20240229_130951_00002_i2yuq_2aac203a-2fdd-48bf-a6b2-771cde32519e
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/_change_data/key=2/20240229_130951_00002_i2yuq_472d047f-25dd-4aef-81ba-330e644c8157
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/_delta_log/00000000000000000000.json
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/_delta_log/00000000000000000001.json
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/_delta_log/_trino_meta/extended_stats.json
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/key=1/20240229_130949_00001_i2yuq_2756a3ae-09f1-4832-bbc0-c2425c7ccee2
  plugin/trino-delta-lake/src/test/resources/trino/cdc_table/key=2/20240229_130951_00002_i2yuq_3a1f6f82-fe21-4c1f-a304-e573a33c9b66
Labels: cla-signed, delta-lake

#20910 Clean up planning of json expressions
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
Labels: cla-signed

#20800 Use write api
  lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java
  lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputStream.java
  lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
  lib/trino-filesystem/src/test/java/io/trino/filesystem/local/TestLocalFileSystem.java
  lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemHdfs.java
  lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemLocal.java
Labels: cla-signed, tests:hive

#20912 Update protocol when adding timestamp column in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
Labels: cla-signed, delta-lake

#20652 Wrap potentially conditional expressions with IF in PreAggregateCaseAggregations
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPreAggregateCaseAggregations.java
  core/trino-main/src/test/java/io/trino/sql/query/TestPreAggregateCaseAggregations.java
Labels: cla-signed, correctness

#20877 Remove Data Lake Storage v1 tests
  .github/workflows/ci.yml
  lib/trino-filesystem-azure/pom.xml
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
  lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
  lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemBlob.java
Labels: cla-signed, test, tests:hive, no-release-notes

#20923 Fix docs for hive-security.md
  docs/src/main/sphinx/connector/hive-security.md
Labels: cla-signed, docs

#20901 Enable by default checkpoint filtering in Delta Lake
  docs/src/main/sphinx/connector/delta-lake.md
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java
Labels: cla-signed, docs, delta-lake

#20934 Fix typo
  plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
Labels: cla-signed, no-release-notes

#20810 Enable JMX metrics for resource groups by default
  core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
  docs/src/main/sphinx/admin/resource-groups.md
  plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java
  plugin/trino-resource-group-managers/src/test/resources/resource_groups_config.json
Labels: cla-signed, docs

#20844 Fix temporal predicates in MVs
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
Labels: cla-signed, iceberg

#20670 Fix assert in HttpPageBufferClient
  core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
Labels: cla-signed, no-release-notes, stale

#20942 Update JVM config for JOL agent support
  docs/src/main/sphinx/installation/deployment.md
Labels: cla-signed, docs

#20948 Enable dynamic JOL agent load for tests
  pom.xml
Labels: cla-signed

#20935 Update airbase to 151
  pom.xml
Labels: cla-signed

#20945 Use createOrOverwrite to create transaction log files on s3
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
Labels: delta-lake

#20953 Remove unnecessary test
  testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Labels: cla-signed

#20480 Add getter for properties to HiveMaterializedViewMetadata
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
Labels: cla-signed, tests:hive, hive, stale

#20937 Allow parallel test execution in BCT
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergParquetFaultTolerantExecutionConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed, test, no-release-notes, iceberg

#20954 Move getLatestMetadataLocation to IcebergUtil
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
Labels: cla-signed, iceberg

#20840 Ignore nested delta directories for Hive ACID
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AcidTables.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestAcidTables.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveAcidUtils.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Labels: cla-signed, tests:hive, hive

#17909 Add Snowflake connector
  .github/workflows/ci.yml
  core/trino-server/src/main/provisio/trino.xml
  docs/src/main/sphinx/connector.md
  docs/src/main/sphinx/connector/snowflake.md
  docs/src/main/sphinx/static/img/snowflake.png
  plugin/trino-snowflake/pom.xml
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClientModule.java
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeConfig.java
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakePlugin.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/SnowflakeQueryRunner.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeClient.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConfig.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakePlugin.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeTypeMapping.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestingSnowflakeServer.java
  pom.xml
  testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeSnowflake.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteSnowflake.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/snowflake.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-snowflake/jvm.config
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-snowflake/snowflake.properties
  testing/trino-product-tests/src/main/java/io/trino/tests/product/snowflake/TestSnowflake.java
Labels: cla-signed, docs, tests:hive

#20966 Update airlift to 241
  pom.xml
Labels: cla-signed, no-release-notes

#20917 Fix 'Multiple entries with same key' error with dynamic filters
  core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
Labels: bug, cla-signed

#20967 Enable Azure native file system tests
  .github/workflows/ci.yml
Labels: cla-signed

#20971 Specify schema name in testNativeQuerySelectUnsupportedType
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed, no-release-notes

#20969 Downgrade modernizer to 2.7.0
  pom.xml
Labels: cla-signed

#20974 Mark test single-threaded
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDistinctLimitIntoTableScan.java
Labels: cla-signed, test, no-release-notes

#20979 Use aggregation function matcher in tests
  core/trino-main/src/test/java/io/trino/cost/TestAggregationStatsRule.java
  core/trino-main/src/test/java/io/trino/cost/TestFilterProjectAggregationStatsRule.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestAddIntermediateAggregations.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDecorrelateInnerUnnestWithGlobalAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDecorrelateLeftUnnestWithGlobalAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestExpressionRewriteRuleSet.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestImplementFilteredAggregations.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMergeLimitWithDistinct.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationToMarkDistinct.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestOptimizeDuplicateInsensitiveJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneAggregationColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneAggregationSourceColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneCountAggregationOverScalar.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneDistinctAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneOrderByInAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableWriterSourceColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushAggregationThroughOuterJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushFilterThroughCountAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPartialAggregationThroughJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveAggregationInSemiJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantEnforceSingleRowNode.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantLimit.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantSort.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantTopN.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestSingleDistinctAggregationToGroupBy.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithoutProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGroupedAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGroupedAggregationWithoutProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
  core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestAnonymizeJsonRepresentation.java
  core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestJsonRepresentation.java
  plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestRewriteSpatialPartitioningAggregation.java
Labels: cla-signed

#20984 Resize Snowflake image for docs
  docs/src/main/sphinx/static/img/snowflake.png
Labels: cla-signed, docs

#20985 Specify schema name in testInsertInPresenceOfNotSupportedColumn
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed

#20988 Remove okhttp from Pinot connector
  plugin/trino-pinot/pom.xml
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/password/PinotPasswordAuthenticationProvider.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
Labels: cla-signed, no-release-notes

#20989 Suppress index not found when listing OpenSearch columns
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/OpenSearchMetadata.java
Labels: cla-signed, no-release-notes

#20872 Make fs cache sections consistent
  docs/src/main/sphinx/connector/hive.md
  docs/src/main/sphinx/connector/iceberg.md
Labels: cla-signed, docs

#20950 Move Thrift metastore authentication docs
  docs/src/main/sphinx/connector/hive-security.md
  docs/src/main/sphinx/object-storage/metastores.md
Labels: cla-signed, docs

#20928 Move Hive file system docs to legacy
  docs/src/main/sphinx/connector/delta-lake.md
  docs/src/main/sphinx/connector/hive.md
  docs/src/main/sphinx/object-storage.md
  docs/src/main/sphinx/object-storage/legacy-azure.md
  docs/src/main/sphinx/object-storage/legacy-cos.md
  docs/src/main/sphinx/object-storage/legacy-gcs.md
  docs/src/main/sphinx/object-storage/legacy-s3.md
  docs/src/main/sphinx/redirects.txt
  docs/src/main/sphinx/release/release-401.md
Labels: cla-signed, release-notes, docs

#20797 Add Trino 440 release notes
  docs/release-template.md
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-440.md
Labels: cla-signed, release-notes, docs

#20970 Update to airlift 241 and Jetty 12.0.7
  client/trino-jdbc/pom.xml
  core/trino-main/pom.xml
  lib/trino-plugin-toolkit/pom.xml
  plugin/trino-elasticsearch/pom.xml
  plugin/trino-example-http/pom.xml
  plugin/trino-example-jdbc/pom.xml
  plugin/trino-google-sheets/pom.xml
  plugin/trino-hive/pom.xml
  plugin/trino-iceberg/pom.xml
  plugin/trino-opensearch/pom.xml
  plugin/trino-prometheus/pom.xml
  plugin/trino-raptor-legacy/pom.xml
  pom.xml
  service/trino-proxy/pom.xml
Labels: cla-signed, jdbc, tests:hive, iceberg, hive

#20997 Fix static project version assertion
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
Labels: cla-signed, no-release-notes

#20963 Fix incorrect result when filtering clustering key in Cassandra
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionResult.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed

#20151 Disable file creation when Partition does not exist #20133
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
Labels: cla-signed, hudi

#21008 Delta Lake: Read mandatory current version starting from table's read version
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java
Labels: cla-signed, delta-lake

#21015 Move docs for Hive authorization
  docs/src/main/sphinx/connector/hive-security.md
  docs/src/main/sphinx/connector/hive.md
  docs/src/main/sphinx/release/release-0.152.md
Labels: cla-signed, release-notes, docs

#21011 Remove docs for unsupported Azure storage
  docs/src/main/sphinx/object-storage/legacy-azure.md
Labels: cla-signed, docs

#21004 Update libraries-bom to 26.34.0
  pom.xml
Labels: cla-signed

#21022 Use JdbcTelemetry in TracingDataSource
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/TracingDataSource.java
Labels: cla-signed, no-release-notes

#21023 Fix failure with special datetime functions in aggregation queries
  core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
  core/trino-main/src/test/java/io/trino/sql/query/TestAggregation.java
Labels: cla-signed

#21025 Remove redundant TransactionLogTail.loadNewTail
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestTransactionLogTail.java
Labels: cla-signed, no-release-notes, delta-lake

#21003 Update airbase to 152
  plugin/trino-accumulo/pom.xml
  pom.xml
Labels: cla-signed, no-release-notes

#21031 Upload test results on Snowflake test failures
  .github/workflows/ci.yml
  testing/trino-tests/pom.xml
  testing/trino-tests/src/test/java/io/trino/tests/ci/TestCiWorkflow.java
Labels: cla-signed

#21033 Remove unused dependencies from Snowflake
  plugin/trino-snowflake/pom.xml
Labels: cla-signed, no-release-notes

#21040 Import OpenSearchErrorCode statically
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
Labels: cla-signed, no-release-notes

#20916 Change testCreateExternalTableWithInaccessibleSchemaLocation to integration test
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergCreateTable.java
Labels: cla-signed, tests:hive, no-release-notes, iceberg

#21039 Use ORC protobuf from Apache ORC
  lib/trino-orc/pom.xml
  lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataReader.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataWriter.java
  lib/trino-orc/src/test/java/io/trino/orc/TestOrcBloomFilters.java
  lib/trino-orc/src/test/java/io/trino/orc/metadata/TestOrcMetadataReader.java
  pom.xml
Labels: cla-signed, tests:hive

#21038 Update to Alluxio 311
  pom.xml
Labels: cla-signed

#20943 Support backwards compatible reads for unnanotated repeated primitive fields in Parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReaderFactory.java
  lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReader.java
  lib/trino-parquet/src/test/resources/parquet_repeated_primitives/int/old-repeated-int.parquet
  lib/trino-parquet/src/test/resources/parquet_repeated_primitives/string/old-repeated-string.parquet
Labels: cla-signed, tests:hive, hive

#20947 Handle NaN and infinite values in Aggregation Window Function
  core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/AverageAggregations.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/CountAggregation.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/CountColumn.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/CountIfAggregation.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/DoubleSumAggregation.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/LongSumAggregation.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/RealAverageAggregation.java
  core/trino-main/src/main/java/io/trino/operator/aggregation/WindowAccumulator.java
  core/trino-main/src/main/java/io/trino/operator/window/AggregateWindowFunction.java
  core/trino-main/src/test/java/io/trino/operator/TestRealAverageAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestAggregationFunction.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestDoubleAverageAggregation.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestDoubleSumAggregation.java
  core/trino-main/src/test/java/io/trino/operator/window/AbstractTestWindowFunction.java
  core/trino-main/src/test/java/io/trino/operator/window/TestAggregateWindowFunction.java
  core/trino-main/src/test/java/io/trino/operator/window/WindowAssertions.java
Labels: bug, cla-signed, correctness

#21041 Fix failure when listing tables in Elasticsearch and OpenSearch
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
  plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java
Labels: cla-signed

#21058 Add Trino 441 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-441.md
Labels: cla-signed, release-notes, docs

#21059 Make Opensearch deployment type configurable
  docs/src/main/sphinx/connector/opensearch.md
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/AwsSecurityConfig.java
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/AwsRequestSigner.java
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
  plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/TestAwsSecurityConfig.java
Labels: cla-signed, docs

#21063 Cleanup usages of Guice Key
  core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnectorFactory.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnectorFactory.java
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiConnectorFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnectorFactory.java
  service/trino-verifier/src/main/java/io/trino/verifier/VerifyCommand.java
Labels: cla-signed, tests:hive, hudi, iceberg, delta-lake, hive

#21070 Reduce redundant TrinoInputFile.length call in Delta Lake
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/TrinoParquetDataSource.java
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Labels: cla-signed, tests:hive, no-release-notes, hudi, iceberg, delta-lake, hive

#21057 Fix $file_modified_time time-based synchronization
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Labels: cla-signed, tests:hive, no-release-notes, hive

#21030 Fix reading Delta Lake files with encoded characters on Azure
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/resources/deltalake/uri/README.md
  plugin/trino-delta-lake/src/test/resources/deltalake/uri/_delta_log/00000000000000000006.json
  plugin/trino-delta-lake/src/test/resources/deltalake/uri/part=a%2Fforwardslash/part-00000-1cfba6d9-7cde-4d70-8b44-590dd2f3667d.c000.snappy.parquet
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java
Labels: cla-signed, tests:hive, delta-lake

#21080 Move installation of module parameter to top level
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiConnectorFactory.java
Labels: cla-signed, hudi

#21079 Require all methods implemented for ForwardingFileIo
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/fileio/TestForwardingFileIo.java
Labels: cla-signed, no-release-notes, iceberg

#21054 Isolate testSelectInformationSchemaColumns for SQL Server
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Labels: cla-signed, no-release-notes

#21074 Preseve fileStatisticsDomain across getNextBatch calls
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
Labels: bug, cla-signed, release-notes, RELEASE-BLOCKER

#21082 Use text blocks in WindowAssertions
  core/trino-main/src/test/java/io/trino/operator/window/WindowAssertions.java
Labels: cla-signed

#21062 Remove owner from materialized views metadata table in documentation
  docs/src/main/sphinx/connector/system.md
Labels: cla-signed, docs

#21086 Improve performance of TestDomainTranslator
  core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
Labels: cla-signed

#21088 Add Trino 442 release notes
  docs/release-template.md
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-440.md
  docs/src/main/sphinx/release/release-442.md
Labels: cla-signed, release-notes, docs

#21073 Fix usage of split length instead of file length in parquet
  lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingInputFile.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/TrinoParquetDataSource.java
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Labels: bug, cla-signed, RELEASE-BLOCKER, tests:hive, hudi, iceberg, delta-lake, hive

#21077 Update various dependencies
  pom.xml
Labels: cla-signed

#21094 Isolate testSelectInformationSchemaTables for SQL Server
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Labels: cla-signed, no-release-notes

#21095 Isolate testSelectInformationSchemaColumns for Ignite
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Labels: cla-signed, no-release-notes

#21090 Fix typo
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
Labels: cla-signed, iceberg

#21091 Update docker-images version to 92
  pom.xml
Labels: cla-signed, no-release-notes

#20492 Delta Lake: Add `partitionValues` information to the `remove` transaction log entries
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeResult.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeScannedDataFile.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/RemoveFileEntry.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java
Labels: cla-signed, delta-lake

#21097 Using builder create DriverConnectionFactory in Snowflake
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClientModule.java
Labels: cla-signed

#21084 Log number of live query runner instances
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed, test

#21076 Unify Iceberg registration behaviour for table location
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
Labels: cla-signed, iceberg

#21110 Fix sql-standard AC failure when table gone
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Labels: cla-signed, tests:hive, hive

#21105 Drop explicit check for file existence while creating GCS blobs
  lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java
  lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputStream.java
  lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
Labels: cla-signed, tests:hive

#21034 Bump Iceberg and Nessie versions
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperations.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
  plugin/trino-iceberg/src/test/java/org/apache/iceberg/jdbc/TestingTrinoIcebergJdbcUtil.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
Labels: cla-signed, iceberg

#20281 Throwing a TrinoException instead of ArithmeticException on sum aggregation of decimals
  core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java
  core/trino-main/src/main/java/io/trino/operator/scalar/DataSizeFunctions.java
  core/trino-main/src/test/java/io/trino/operator/aggregation/TestDecimalSumAggregation.java
  core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java
Labels: cla-signed, release-notes, docs, jdbc, tests:hive, hudi, iceberg, delta-lake, hive, bigquery, mongodb

#21123 Remove isEffectivelyLiteral
  core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
  core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java
  core/trino-main/src/main/java/io/trino/sql/ir/IrUtils.java
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/IrExpressionInterpreter.java
  core/trino-main/src/main/java/io/trino/sql/planner/PartialTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/CanonicalizeExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/CanonicalizeExpressions.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EliminateCrossJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushJoinIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushMergeWriterUpdateIntoConnector.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionThroughJoin.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantDateTrunc.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyCountOverConstant.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapDateTruncInComparison.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/joins/JoinGraph.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestPartialTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestCanonicalizeExpressionRewriter.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestCanonicalizeExpressions.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestEliminateCrossJoins.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestInlineProjections.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestJoinNodeFlattener.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushMergeWriterUpdateIntoConnector.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionThroughJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReorderJoins.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
Labels: cla-signed, tests:hive, iceberg, hive

#21122 Synchronize listing tables in file metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
Labels: cla-signed, tests:hive, no-release-notes, hive

#21071 Support FlatHashStrategy with 100_000+ columns
  core/trino-main/src/main/java/io/trino/operator/FlatHashStrategyCompiler.java
  core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategy.java
  core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategyCompiler.java
Labels: cla-signed, tests:hive, delta-lake, hive

#21133 Remove unused argument from IrUtils.combinePredicates
  core/trino-main/src/main/java/io/trino/sql/ir/IrUtils.java
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ExtractCommonPredicatesExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownNegationsExpressionRewriter.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveDuplicateConditions.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyExpressions.java
Labels: cla-signed, no-release-notes

#21107 Fix printing locked monitors in TestHangMonitor
  testing/trino-testing-services/src/main/java/io/trino/jvm/Threads.java
Labels: cla-signed, test

#21101 Remove unused fields in split simulation
  core/trino-main/src/test/java/io/trino/execution/executor/timesharing/SimulationSplit.java
  core/trino-main/src/test/java/io/trino/execution/executor/timesharing/SimulationTask.java
Labels: cla-signed, test

#21137 Fix comment location
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/delta.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/hive.properties
Labels: cla-signed, no-release-notes

#21139 Add test for symlink tables using line-based input formats
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderFactory.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestTextfileSymlinkInputFormat.java
Labels: cla-signed, tests:hive

#21144 Extend assertions in testAlterTableRenameColumnToLongName
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#21136 Specify Locale for DecimalFormat
  core/trino-main/src/main/java/io/trino/type/DoubleOperators.java
  core/trino-main/src/main/java/io/trino/type/RealOperators.java
Labels: cla-signed

#21158 Disable testSelectInformationSchemaColumns in Snowflake
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21155 Update airlift to 243 and airbase to 153
  client/trino-jdbc/pom.xml
  lib/trino-cache/src/test/java/io/trino/cache/MoreFutures.java
  pom.xml
  testing/trino-product-tests/pom.xml
Labels: cla-signed, jdbc, tests:hive

#21141 Improve SortedRangeSet hash quality
  core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java
Labels: cla-signed

#21171 Cleanups
  core/trino-main/src/main/java/io/trino/execution/SqlTask.java
Labels: cla-signed

#21168 Hive `sync_partition_metadata`: Alter partition when the synced path differs only in case
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
Labels: cla-signed, tests:hive, hive

#21125 Isolate column operation tests in Ignite
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Labels: cla-signed

#21181 Use switch case expressions for processing by Block type
  core/trino-main/src/main/java/io/trino/operator/JoinDomainBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
  core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
Labels: cla-signed

#21126 Throw TrinoException when varchar size not present in Redshift
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftErrorCode.java
Labels: cla-signed

#21185 Disable rename column in Phoenix connector
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Labels: cla-signed

#21186 Remove depercated dep in phoenix client
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
Labels: cla-signed

#21188 Explicitly handle LazyBlock in switch expressions
  core/trino-main/src/main/java/io/trino/operator/JoinDomainBuilder.java
  core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
  core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
Labels: cla-signed

#21145 Delete also blobs ending in slash when deleting directory contents
  lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
  lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
  lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
Labels: cla-signed, tests:hive

#20814 Support automatic type coercion in Delta table creation
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
Labels: cla-signed, delta-lake

#21187 Allow a custom header name for authorization in Prometheus
  docs/src/main/sphinx/connector/prometheus.md
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusClient.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorConfig.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java
Labels: cla-signed, docs

#21184 Add SystemSecurityMetadata interface method for drop column's not null
  core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
  testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Labels: cla-signed

#21178 Add Trino 443 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-443.md
Labels: cla-signed, release-notes, docs

#21194 Use enhanced instanceof
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
  core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
  core/trino-main/src/main/java/io/trino/cost/CachingCostProvider.java
  core/trino-main/src/main/java/io/trino/cost/CachingStatsProvider.java
  core/trino-main/src/main/java/io/trino/cost/ComposableStatsCalculator.java
  core/trino-main/src/main/java/io/trino/cost/FilterProjectAggregationStatsRule.java
  core/trino-main/src/main/java/io/trino/cost/PlanNodeStatsEstimate.java
  core/trino-main/src/main/java/io/trino/cost/RemoteSourceStatsRule.java
  core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java
  core/trino-main/src/main/java/io/trino/cost/SimpleFilterProjectSemiJoinStatsRule.java
  core/trino-main/src/main/java/io/trino/cost/StatsNormalizer.java
  core/trino-main/src/main/java/io/trino/execution/StateMachine.java
  core/trino-main/src/main/java/io/trino/json/PathEvaluationUtil.java
  core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java
  core/trino-main/src/main/java/io/trino/json/PathPredicateEvaluationVisitor.java
  core/trino-main/src/main/java/io/trino/json/ir/SqlJsonLiteralConverter.java
  core/trino-main/src/main/java/io/trino/metadata/Catalog.java
  core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
  core/trino-main/src/main/java/io/trino/operator/Driver.java
  core/trino-main/src/main/java/io/trino/sql/gen/InCodeGenerator.java
  core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DereferencePushdown.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java
Labels: cla-signed

#21197 Wrap IR IN value list in brackets
  core/trino-main/src/main/java/io/trino/sql/ir/ExpressionFormatter.java
Labels: cla-signed, no-release-notes

#21148 Add support for `avg` aggregation pushdown on `bigint` type in Snowflake
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/ImplementAvgBigint.java
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21202 Enable LIMIT pushdown test in Snowflake
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21208 Fix memory connector testCreateTableInNonDefaultSchema
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
Labels: cla-signed, test, no-release-notes

#21211 Do not throw from cache removal listener
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ReusableConnectionFactory.java
Labels: cla-signed, no-release-notes

#21213 Use separate directory for raptor data
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/RaptorQueryRunner.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorMySqlConnectorTest.java
Labels: cla-signed

#21206 Update tpch to 1.4
  core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkDynamicFilterSourceOperator.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupedTopNRankBuilder.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupedTopNRowNumberBuilder.java
  core/trino-main/src/test/java/io/trino/operator/BenchmarkTopNOperator.java
  core/trino-main/src/test/java/io/trino/operator/spiller/BenchmarkBinaryFileSpiller.java
  core/trino-main/src/test/java/io/trino/sql/gen/BenchmarkPageProcessor.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSetProvider.java
  pom.xml
Labels: cla-signed, tests:hive, no-release-notes, hive

#21220 Fix jdbc write config variable typo
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java
Labels: cla-signed

#20484 Run testTimestampInsertCompatibility only in OSS Delta
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java
Labels: cla-signed, tests:hive

#21219 Support topN for Snowflake connector
  plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21229 Drop test table in test testAlterTableAddLongColumnName and testAlter…
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#21225 Add missing documentation table headers
  docs/src/main/sphinx/object-storage/file-system-gcs.md
  docs/src/main/sphinx/object-storage/file-system-s3.md
Labels: cla-signed, docs

#21248 Isolate testKeyspaceNameAmbiguity Cassandra test
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed, no-release-notes

#21214 Add pushdown docs for Snowflake
  docs/src/main/sphinx/connector/snowflake.md
Labels: cla-signed, docs

#21238 Get table comments from RDBMS in bulk
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcClientStats.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Labels: cla-signed

#21255 Remove redundant clone method
  core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
  core/trino-main/src/main/java/io/trino/execution/resourcegroups/ResourceUsage.java
Labels: cla-signed, no-release-notes

#21256 Limit maven memory on CI
  .github/workflows/ci.yml
Labels: cla-signed, no-release-notes

#21127 Add RemoteLogTracingEvent to allow tracing the event happen or not
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/RemoteLogTracingEvent.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#21263 Fix error-prone violation in trino-server-rpm
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
Labels: cla-signed

#21165 Describe rule matching selector
  docs/src/main/sphinx/admin/resource-groups.md
Labels: cla-signed, docs

#21257 Increase Elasticsearch container startup timeout to 5 minutes
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
Labels: cla-signed

#21275 Fix requirement for renaming tables in Delta Lake documentation
  docs/src/main/sphinx/connector/delta-lake.md
Labels: cla-signed, docs

#21277 Enable Snowflake testInsertIntoNotNullColumn test
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21253 Fix incorrect partition pushdown when no partitionSpec exists in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: bug, cla-signed, iceberg

#21282 Fix Snowflake test name typo
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21278 Enable Snowflake testAddNotNullColumn test
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed

#21201 Run maven-checks with 23-ea
  .github/workflows/ci.yml
Labels: cla-signed

#21291 Remove erroneous text
  docs/src/main/sphinx/release/release-443.md
Labels: cla-signed, release-notes, docs

#21288 Fix 443 release notes
  docs/src/main/sphinx/release/release-443.md
Labels: cla-signed, release-notes, docs
