Repository trinodb/trino, pull requests merged in 2024-05, with the labels that each got.

#21769 Move config files to resources in Kinesis
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestKinesisTableDescriptionSupplier.java
  plugin/trino-kinesis/src/test/resources/etc/catalog/kinesis.properties
  plugin/trino-kinesis/src/test/resources/etc/kinesis/testtable.json
Labels: cla-signed

#21781 Add builder to MetadataEntry in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java
Labels: cla-signed, delta-lake

#21753 Add Trino 446 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-446.md
Labels: cla-signed, release-notes, docs

#21675 Require JDK 22.0.0 to build and run Trino
  .github/workflows/ci.yml
  .java-version
  .mvn/jvm.config
  README.md
  core/docker/default/etc/jvm.config
  core/trino-server-main/src/main/java/io/trino/server/TrinoServer.java
  core/trino-server-rpm/src/main/resources/dist/config/jvm.config
  core/trino-server-rpm/src/main/rpm/preinstall
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
  docs/src/main/sphinx/admin/resource-groups.md
  docs/src/main/sphinx/functions/conversion.md
  docs/src/main/sphinx/functions/regexp.md
  docs/src/main/sphinx/installation/deployment.md
  docs/src/main/sphinx/security/tls.md
  pom.xml
Labels: cla-signed, docs, jdbc, hudi, iceberg, delta-lake, hive

#21782 Update to Hadoop 3.3.5-2
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/sequence/TestSequenceFileReaderWriter.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderWriter.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/RcFileTester.java
  pom.xml
Labels: cla-signed

#21790 Make logging about container.log to be less verbose
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
Labels: cla-signed

#21801 Avoid over retaining memory for strings in parquet writer
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/BinaryValueWriter.java
Labels: cla-signed

#21761 Gather partial TopN results
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/GatherPartialTopN.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestGatherPartialTopN.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestPartialTopNWithPresortedInput.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Labels: cla-signed, performance, hive

#21806 Fix typo
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticator.java
  plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/ldap/LdapAuthenticatorConfig.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestLdapAuthenticator.java
  plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestLdapAuthenticatorConfig.java
Labels: cla-signed

#21805 Switch to JNI/FFM terminal provider
  client/trino-cli/pom.xml
Labels: cla-signed

#21807 Update JLine to 3.26.1
  client/trino-cli/pom.xml
  testing/trino-product-tests/src/main/java/io/trino/tests/product/cli/TrinoCliProcess.java
Labels: cla-signed

#21752 Limit product tests Trino nodes memory
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
Labels: cla-signed

#21812 Update provisio to 1.0.25
  pom.xml
Labels: cla-signed, no-release-notes

#21524 Check variable gracePeriod not null
  core/trino-main/src/main/java/io/trino/metadata/MaterializedViewDefinition.java
Labels: cla-signed, stale

#21639 Add support for TopNRankingStatsRule
  core/trino-main/src/main/java/io/trino/cost/StatsCalculatorModule.java
  core/trino-main/src/main/java/io/trino/cost/TopNRankingStatsRule.java
  core/trino-main/src/test/java/io/trino/cost/TestTopNRankingStatsRule.java
Labels: cla-signed

#21822 Finer grained cache missing control in caching hive metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
Labels: cla-signed, performance, hive

#21819 Fix typo in PredicatePushDown comment
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
Labels: cla-signed

#21713 Export metrics from BinPackingNodeAllocatorService
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
Labels: cla-signed

#21827 Fix message in ConnectorSplit.getInfo
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplit.java
Labels: cla-signed

#21818 Fix some of jsonwebtoken deprecated api
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
  core/trino-main/src/main/java/io/trino/server/InternalAuthenticationManager.java
  core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
  core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
  core/trino-main/src/main/java/io/trino/server/ui/FormWebUiAuthenticationFilter.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkDecoder.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java
  core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithRefreshTokens.java
  core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
Labels: cla-signed, jdbc, iceberg

#21831 Fix instance size for list and map types on Hive
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/ListTypeInfo.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/MapTypeInfo.java
Labels: cla-signed, hive

#21829 Update Coral to fix translation for views with EXISTS
  pom.xml
Labels: cla-signed

#21832 Define outputTimestamp for reproducible build
  pom.xml
Labels: cla-signed

#21834 Remove nested operators stats method
  core/trino-main/src/main/java/io/trino/operator/DriverContext.java
  core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
  core/trino-main/src/test/java/io/trino/memory/TestMemoryTracking.java
  core/trino-main/src/test/java/io/trino/operator/TestExchangeOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestMergeOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorOperatorAdapter.java
  core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorSourceOperatorAdapter.java
Labels: cla-signed, no-release-notes

#21422 Use boolean or aggregation in correlated exists
  core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughBoolOrAggregation.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformExistsApplyToCorrelatedJoin.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/JoinMatcher.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushFilterThroughBoolOrAggregation.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformExistsApplyToCorrelatedJoin.java
  core/trino-main/src/test/java/io/trino/sql/query/TestCorrelatedAggregation.java
  core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
Labels: cla-signed, release-notes

#21569 Update to Phoenix 5.2.0 and HBase 2.5
  docs/src/main/sphinx/connector/phoenix.md
  lib/trino-phoenix5-patched/pom.xml
  lib/trino-phoenix5-patched/src/main/java/org/apache/phoenix/shaded/org/apache/zookeeper/client/StaticHostProvider.java
  lib/trino-phoenix5-patched/src/test/java/org/apache/phoenix/TestDummy.java
  plugin/trino-phoenix5/pom.xml
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixSplitManager.java
  pom.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodePhoenix5.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/phoenix/TestPhoenix.java
Labels: cla-signed, docs

#21826 Update to shaded Hadoop UserGroupInformation
  lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsOutputFile.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/HdfsEnvironment.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/TrinoFileSystemCache.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/CachingKerberosHadoopAuthentication.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/DirectHdfsAuthentication.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/GenericExceptionAction.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/HdfsAuthentication.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/ImpersonatingHdfsAuthentication.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/KerberosHadoopAuthentication.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/NoHdfsAuthentication.java
  lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/UserGroupInformationUtils.java
  pom.xml
Labels: cla-signed

#21845 Use Json Snowflake result format in Iceberg Snowflake catalog
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/TrinoIcebergSnowflakeCatalogFactory.java
Labels: cla-signed, iceberg

#21849 Fix "the the" in docs
  docs/src/main/sphinx/object-storage/metastores.md
  docs/src/main/sphinx/security/inspect-jks.md
  docs/src/main/sphinx/sql/select.md
Labels: cla-signed, docs

#21851 Update Java version to 22 in docs CI
  .github/workflows/docs.yml
Labels: cla-signed

#21848 Avoid using string concat for logger in Hudi
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
Labels: cla-signed, hudi

#21858 Fix test naming in TransformCorrelatedGlobalAggregationWithProjection
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java
Labels: cla-signed

#21856 Fix typo in CoordinatorModule
  core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
Labels: cla-signed

#21854 Document optimizer session properties
  docs/src/main/sphinx/admin/properties-optimizer.md
Labels: cla-signed, docs

#21841 Allow complex expression rewrites with double and real constant
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/RewriteExactNumericConstant.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
Labels: cla-signed

#21853 Update airlift, drift, parquet, picocli
  pom.xml
Labels: cla-signed, no-release-notes, iceberg, delta-lake, hive

#21863 Fix format of ProxyOptionsConfigurer and avoid using deprecated JdkSslContext constructor in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ProxyOptionsConfigurer.java
Labels: cla-signed, bigquery

#21865 Increase testManyFunctionsWithSameWindow timeout
  core/trino-main/src/test/java/io/trino/sql/query/TestWindow.java
Labels: cla-signed, test, no-release-notes

#21873 Add Trino 447 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-447.md
Labels: cla-signed, release-notes, docs

#21883 Fix failure when reading non-alphanumeric column names
  core/trino-main/src/main/java/io/trino/sql/planner/Symbol.java
  core/trino-main/src/main/java/io/trino/sql/planner/SymbolAllocator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestSymbolAllocator.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#21891 Fix broken column name test in BigQuery
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java
Labels: cla-signed, bigquery

#21893 Add catalog session property doc
  docs/src/main/sphinx/connector/hive.md
Labels: cla-signed, docs

#21899 Add docs for Avro as supported format
  docs/src/main/sphinx/connector/iceberg.md
Labels: cla-signed, docs

#21887 Handle constraintExpressions in table scan redirection
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
Labels: cla-signed

#21890 Change getTableMeta alternative for HttpThrift metastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/HttpThriftMetastoreClientFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java
Labels: cla-signed, hive

#21915 Throw TrinoException in case of problems with snapshot delete
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, iceberg

#21908 Fix thread leak in v2 GlueHiveMetastore
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, no-release-notes, hive

#21910 Avoid primitive boxing for equals
  client/trino-client/src/main/java/io/trino/client/ErrorInfo.java
  core/trino-main/src/main/java/io/trino/execution/StageId.java
  core/trino-main/src/main/java/io/trino/execution/buffer/BufferResult.java
  core/trino-main/src/main/java/io/trino/execution/buffer/OutputBufferInfo.java
  core/trino-main/src/main/java/io/trino/operator/window/FrameInfo.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/BooleanLiteral.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateCatalog.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateFunction.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateMaterializedView.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateSchema.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateTableAsSelect.java
  core/trino-parser/src/main/java/io/trino/sql/tree/CreateView.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Except.java
  core/trino-parser/src/main/java/io/trino/sql/tree/FunctionCall.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Grant.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Intersect.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Parameter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/RenameMaterializedView.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Revoke.java
  core/trino-parser/src/main/java/io/trino/sql/tree/SetColumnType.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Union.java
  core/trino-parser/src/main/java/io/trino/sql/tree/With.java
  core/trino-spi/src/main/java/io/trino/spi/ErrorCode.java
  core/trino-spi/src/main/java/io/trino/spi/HostAddress.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ColumnMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/expression/FieldDereference.java
  core/trino-spi/src/main/java/io/trino/spi/function/Signature.java
  core/trino-spi/src/main/java/io/trino/spi/security/PrivilegeInfo.java
  core/trino-spi/src/main/java/io/trino/spi/type/CharType.java
  core/trino-spi/src/main/java/io/trino/spi/type/SqlDate.java
  core/trino-spi/src/main/java/io/trino/spi/type/TimeZoneKey.java
  core/trino-spi/src/main/java/io/trino/spi/type/VarcharType.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchSplit.java
  pom.xml
Labels: cla-signed, performance, no-release-notes

#21927 Avoid primitive boxing for equals
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PreferredProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java
  core/trino-main/src/main/java/io/trino/type/SqlIntervalDayTime.java
  core/trino-main/src/main/java/io/trino/type/SqlIntervalYearMonth.java
  core/trino-main/src/test/java/io/trino/sql/planner/assertions/AggregationFunctionMatcher.java
  lib/trino-orc/src/main/java/io/trino/orc/DiskRange.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/ColumnStatistics.java
  lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/StringStatistics.java
  lib/trino-parquet/src/main/java/io/trino/parquet/ChunkKey.java
  lib/trino-parquet/src/main/java/io/trino/parquet/DiskRange.java
  lib/trino-record-decoder/src/test/java/io/trino/decoder/DecoderTestColumnHandle.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/AccumuloColumnConstraint.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/AccumuloColumnHandle.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/AccumuloTableHandle.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplit.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartition.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/BooleanLiteral.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveColumnHandle.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePrivilegeInfo.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaColumnHandle.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisColumnHandle.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduColumnHandle.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduTableHandle.java
  plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileColumnHandle.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorColumnHandle.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorTableHandle.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/ShardMetadata.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/TableMetadata.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/ShardRecoveryManager.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/systemtables/ValueBuffer.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/util/PrioritizedFifoExecutor.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisColumnHandle.java
  plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsSplit.java
  pom.xml
  testing/trino-testing/src/main/java/io/trino/testing/tpch/TpchScaledTable.java
Labels: cla-signed, delta-lake, hive, bigquery

#21811 Ensure column type is always string for CSV partitioned tables
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
Labels: cla-signed, hive

#21896 Fix missing QueryCompletedEvent race condition
  core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQuery.java
  testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Labels: cla-signed

#21562 Move HiveMetastore to field in TestDeltaLakeConnectorTest
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
Labels: cla-signed, delta-lake, stale-ignore

#21924 Fix potential resource leak in TestScaledWriterScheduler
  core/trino-main/src/test/java/io/trino/execution/scheduler/TestScaledWriterScheduler.java
Labels: cla-signed, test, no-release-notes

#21926 Respect hive.metastore-stats-cache-ttl in Glue v2
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/InMemoryGlueCache.java
Labels: cla-signed, no-release-notes, hive

#21949 Fix typo in Hudi connector documentation
  docs/src/main/sphinx/connector/hudi.md
Labels: docs

#21951 Do not exclude protobuf for trino-exchange-filesystem
  plugin/trino-exchange-filesystem/pom.xml
Labels: cla-signed

#21758 Include all properties in InternalNode equals
  core/trino-main/src/main/java/io/trino/metadata/InternalNode.java
Labels: cla-signed, no-release-notes

#21959 Fix FS exchange manager thread leak
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeManager.java
Labels: cla-signed, no-release-notes

#21950 Allow to wait for more than one DF in Kudu
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduSplitManager.java
Labels: cla-signed

#21955 Fix failure when translating $try_cast to/from connector expression
  core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
  core/trino-spi/src/main/java/io/trino/spi/expression/StandardFunctions.java
Labels: cla-signed

#21953 Decrease max error duration from 5m to 1m
  core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
  core/trino-main/src/main/java/io/trino/operator/DirectExchangeClientConfig.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
  core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClientConfig.java
  docs/src/main/sphinx/admin/fault-tolerant-execution.md
  docs/src/main/sphinx/admin/properties-query-management.md
Labels: cla-signed, docs

#21954 Fix Glue metastore deadlock when getting statistics
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/ExecutorUtil.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, RELEASE-BLOCKER, hive

#21964 Set thread context class loader in Glue threads
  .mvn/modernizer/violations.xml
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, no-release-notes, hive

#21971 Bring back IS DISTINCT FROM join pushdown testing
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
Labels: cla-signed, no-release-notes

#21909 Separate schemas in BaseSharedMetastoreTest
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
Labels: cla-signed, iceberg

#21973 Fix Alluxio CacheManager leak on coordinator
  lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioCoordinatorFileSystemCache.java
Labels: cla-signed

#21977 Improve default bucket count in FTE
  core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
Labels: cla-signed

#21587 Fixed integer overflow for merged ORC diskRange
  lib/trino-orc/src/main/java/io/trino/orc/OrcDataSourceUtils.java
Labels: cla-signed, stale

#21983 fixing typo in Big Query Connector docs - "bigquery.view-materialization-with-filter"
  docs/src/main/sphinx/connector/bigquery.md
Labels: docs

#21984 Add Trino 448 release notes
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-448.md
Labels: cla-signed, release-notes, docs

#21980 Close thrift metastore client in tests
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFlushMetadataCacheProcedure.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingThriftHiveMetastoreBuilder.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestBridgingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHttpMetastoreClient.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestUnityMetastore.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
  testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Labels: cla-signed, test, no-release-notes, iceberg, delta-lake, hive

#21982 Fix Azure http client leak in Azure filesystem
  lib/trino-filesystem-azure/pom.xml
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
  lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
Labels: cla-signed, no-release-notes, delta-lake

#21994 Cache maven in maven-checks on JDK 22
  .github/workflows/ci.yml
Labels: cla-signed, no-release-notes

#21996 Close Nessie client
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
Labels: cla-signed, iceberg

#21981 Suppress single table errors during metadata listing
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadataListing.java
Labels: cla-signed, hive

#22003 Reuse temp variables in Row Constructor code
  core/trino-main/src/main/java/io/trino/sql/gen/RowConstructorCodeGenerator.java
Labels: cla-signed

#21987 Allow filesystem caching on coordinator unconditionally
  lib/trino-filesystem-cache-alluxio/pom.xml
  lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioCoordinatorFileSystemCache.java
  lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemCacheModule.java
  lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java
  lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/AllowFilesystemCacheOnCoordinator.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
Labels: cla-signed, iceberg, delta-lake

#22009 Revert "Limit product tests Trino nodes memory"
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
Labels: cla-signed

#22000 Account for local exchanges in getDefaultBucketCount
  core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
  core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchange.java
  core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
Labels: cla-signed, no-release-notes

#21502 Add support for the custom hive catalog to support Hive3
  docs/src/main/sphinx/object-storage/metastores.md
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/HttpThriftMetastoreClientFactory.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCustomCatalogConnectorSmokeTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestHiveMetastoreCatalogs.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingTokenAwareMetastoreClientFactory.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMetastoreClientFactory.java
Labels: cla-signed, docs, iceberg, hive, bigquery

#22008 Improve error message for invalid range bounds
  core/trino-spi/src/main/java/io/trino/spi/predicate/Range.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestRange.java
Labels: cla-signed

#22012 Fix milestone workflow
  .github/workflows/milestone.yml
Labels: cla-signed

#22017 Convert CassandraType to record
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraColumnHandle.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypes.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java
Labels: cla-signed

#22016 Minor cleanup in Elasticsearch connector
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/IndexMetadata.java
Labels: cla-signed

#22014 Minor cleanup in Pinot session properties
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSessionProperties.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotSplitManager.java
Labels: cla-signed

#22023 Avoid redundant tail slash check in TrinoRestCatalog
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
Labels: cla-signed, iceberg

#22018 Fix indentation
  plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorSmokeTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/BaseCassandraConnectorSmokeTest.java
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidConnectorTest.java
  plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidLatestConnectorSmokeTest.java
  plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorSmokeTest.java
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/BaseHudiConnectorSmokeTest.java
  plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergVendingRestCatalogConnectorSmokeTest.java
  plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaConnectorTest.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaLatestConnectorSmokeTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
  plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorSmokeTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
  plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
  plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorSmokeTest.java
  plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java
  plugin/trino-redis/src/test/java/io/trino/plugin/redis/BaseRedisConnectorTest.java
  plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
  plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreLatestConnectorSmokeTest.java
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorSmokeTest.java
  plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftConnectorTest.java
  testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchConnectorTest.java
Labels: cla-signed, hudi, iceberg, delta-lake, hive, bigquery, mongodb

#22025 Avoid unnecessary unboxing in SnapshotsTable
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SnapshotsTable.java
Labels: cla-signed, iceberg

#20993 Add `$partitions` system table to Delta Lake Connector
  docs/src/main/sphinx/connector/delta-lake.md
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableType.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/util/PageListBuilder.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreWithTableRedirectionsTest.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableName.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
Labels: cla-signed, docs, delta-lake

#22024 Replace TimeStat.BlockTimer ignored with unnamed variable
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
  lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsFileSystem.java
  lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsInputFile.java
  lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsOutputFile.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcApiStats.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/AwsApiCallStats.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreApiStats.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/backup/BackupOperationStats.java
Labels: cla-signed, no-release-notes, hive

#22030 Throw TrinoException in dropNamespace when REST error
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
Labels: cla-signed, iceberg

#22034 Fix test comment typo
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java
  plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
Labels: cla-signed, test, no-release-notes, iceberg, delta-lake

#22037 Increase the default page size for listing BigQuery schemas and tables
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
Labels: cla-signed, bigquery

#22038 Specify RoundingMode explicitly in OrcMetrics
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/OrcMetrics.java
Labels: cla-signed, iceberg

#21532 Remove deprecated method getTableHandle from spi
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
  core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/CatalogMetadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
  core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/metadata/TestInformationSchemaMetadata.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
  plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopMetadata.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
  plugin/trino-example-http/src/main/java/io/trino/plugin/example/ExampleMetadata.java
  plugin/trino-example-http/src/test/java/io/trino/plugin/example/TestExampleMetadata.java
  plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java
  plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
  plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxMetadata.java
  plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxMetadata.java
  plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxSplitManager.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaMetadata.java
  plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisMetadata.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestKinesisTableDescriptionSupplier.java
  plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/s3config/TestS3TableConfigClient.java
  plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
  plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileMetadata.java
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
  plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
  plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/OpenSearchMetadata.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotMetadata.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusMetadata.java
  plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorConnector.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorMetadata.java
  plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorSplitManager.java
  plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftMetadata.java
  plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsMetadata.java
  plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcdsMetadataStatistics.java
  plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java
  plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/TestTpchMetadata.java
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
  testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java
  testing/trino-testing/src/main/java/io/trino/testing/tpch/TpchIndexedData.java
Labels: cla-signed, hudi, iceberg, delta-lake, hive, bigquery, mongodb

#22031 Unimplement deprecated fastutil method
  core/trino-main/src/main/java/io/trino/operator/join/SortedPositionLinks.java
Labels: cla-signed

#22033 Improve speed when bigquery.case-insensitive-name-matching is enabled
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
Labels: cla-signed, bigquery

#22044 Use storage API in BigQueryMetadata.finishInsert
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/DefaultBigQueryMetadataFactory.java
Labels: cla-signed, bigquery

#22051 Remove unused UriInfo argument
  core/trino-main/src/main/java/io/trino/server/ui/LoginResource.java
Labels: cla-signed, no-release-notes

#21900 Add configurable retry policy for S3 client
  docs/src/main/sphinx/object-storage/file-system-s3.md
  lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
  lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
  lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java
Labels: cla-signed, docs

#22061 Remove redundant testng exclusion from trino-thrift-testing-server
  plugin/trino-thrift-testing-server/pom.xml
Labels: cla-signed

#22052 Provide roleSessionName for Glue metastore assume role credentials
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
Labels: cla-signed, hive

#22048 Fix GlueContext when catalog ID is present
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueContext.java
Labels: cla-signed, hive

#22053 Remove testng-specific configuration
  plugin/trino-hive/pom.xml
  pom.xml
Labels: cla-signed, test, no-release-notes, hive

#22062 Remove REST, JDBC, Nessie from some tests in TestIcebergSparkCompatibility
  testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Labels: cla-signed

#22059 Use Supplier to list datasets in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
Labels: cla-signed, bigquery

#22063 Replace deprecated QueryAssert.assertThat with Assertions.assertThat
  testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestKerberosConstrainedDelegationJdbc.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/snowflake/TestSnowflake.java
Labels: cla-signed

#22070 Throw TrinoException in case of not found catalog
  core/trino-main/src/main/java/io/trino/connector/StaticCatalogManager.java
Labels: cla-signed

#22069 Validate unsupported configuration options for Glue v2
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
Labels: cla-signed, no-release-notes, hive

#22058 Avoid using deprecated method in IcebergMetadata
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, iceberg

#22065 Throw TrinoException for Glue external failures
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Labels: cla-signed, iceberg

#22077 Remove unused members of InformationSchemaMetadata
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
Labels: cla-signed

#22080 Isolate selected tests from TestCassandraConnectorTest
  plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Labels: cla-signed

#19818 Iceberg View Rest Catalog support
  client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
  core/trino-main/src/main/java/io/trino/metadata/Metadata.java
  core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
  core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
  core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergErrorCode.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/RestCatalogTestUtils.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergVendingRestCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/IcebergRestCatalogBackendContainer.java
  testing/trino-tests/src/test/java/io/trino/connector/informationschema/TestInformationSchemaConnector.java
Labels: cla-signed, docs, jdbc, iceberg, delta-lake, hive

#22001 Improve Snowflake Iceberg catalog docs
  docs/src/main/sphinx/connector/iceberg.md
  docs/src/main/sphinx/object-storage/metastores.md
Labels: cla-signed, docs

#21876 Document query passthrough to Snowflake
  docs/src/main/sphinx/connector/snowflake.md
Labels: cla-signed, docs

#22078 Import the right Preconditions class
  lib/trino-filesystem-gcs/pom.xml
  lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystem.java
  lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsUtils.java
  pom.xml
Labels: cla-signed, no-release-notes

#22088 Use hive.metastore of JVM options in DeltaLakeExternalQueryRunnerMain
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
Labels: cla-signed, delta-lake

#22090 Inform about ignored cache config options with Glue v2
  docs/src/main/sphinx/release/release-448.md
Labels: cla-signed, release-notes, docs, no-release-notes

#22067 Use mayFail in PreAggregateCaseAggregations
  core/trino-main/src/main/java/io/trino/sql/ir/IrExpressions.java
  core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java
Labels: bug, cla-signed

#22093 Fix typo in hive connectors documentation
  docs/src/main/sphinx/connector/hive.md
Labels: cla-signed, docs

#22064 Throw TrinoException for not supported CSV
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvDeserializerFactory.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/csv/TestCsvFormat.java
Labels: cla-signed

#22094 Remove unused methods from DockerContainer
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
Labels: cla-signed

#22095 Add estimatedMemoryReservationDistribution to stage task statistic in…
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageTaskStatistics.java
Labels: cla-signed

#22072 Fix Iceberg value for varbinary
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#21234 Upgrade Pinot Libraries to 1.1.0
  docs/src/main/sphinx/connector/pinot.md
  plugin/trino-pinot/pom.xml
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotLegacyDataFetcher.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotExpressionRewriter.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotSqlFormatter.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotTransformFunctionTypeResolver.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotLatestNoGrpcConnectorSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
  plugin/trino-pinot/src/test/resources/too_many_broker_rows_realtimeSpec.json
Labels: cla-signed, docs, no-release-notes, stale-ignore

#22109 Avoid flakiness in test when dropping potentially inexistent table
  plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java
Labels: cla-signed, test

#22111 Update docker-images version to 95
  pom.xml
Labels: cla-signed

#22125 Fix ArrayType indeterminateOperator with a DictionaryBlock
  core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
Labels: cla-signed

#22112 Update maven-wrapper to 3.3.2
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  pom.xml
Labels: cla-signed, no-release-notes

#22132 Throw TrinoException for invalid Iceberg sort field
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SortFieldUtils.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#22127 Remove unused dependencies from Hudi
  plugin/trino-hudi/pom.xml
Labels: cla-signed, hudi

#22113 Revert "Avoid flakiness in test when dropping table"
  plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java
Labels: cla-signed

#22110 Update nessie to 0.83.2
  plugin/trino-iceberg/pom.xml
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
Labels: cla-signed, iceberg

#22134 Avoid using some deprecated methods of Parquet
  lib/trino-parquet/src/main/java/io/trino/parquet/metadata/ColumnChunkMetadata.java
  lib/trino-parquet/src/main/java/io/trino/parquet/metadata/IntColumnChunkMetadata.java
  lib/trino-parquet/src/main/java/io/trino/parquet/metadata/LongColumnChunkMetadata.java
  lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TrinoValuesWriterFactory.java
Labels: cla-signed

#22140 Update docker-images version to 96
  pom.xml
Labels: cla-signed

#22139 Update Maven to 3.9.7
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed, no-release-notes

#22141 Remove unused method from TransactionLogAccess in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
Labels: cla-signed, delta-lake

#22145 Unwrap short error message
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#22150 Verify deletion vector checksum in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/DeletionVectors.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
Labels: cla-signed, delta-lake

#22073 Improve performance of SortedRangeSet discrete union
  core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
  core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java
Labels: cla-signed

#22144 Add support for vacuumProtocolCheck feature in Delta Lake
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
Labels: cla-signed, delta-lake

#22146 Implement streamRelationColumns in Cassandra
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
Labels: cla-signed

#22155 Implement streamRelationComments in Cassandra
  plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
Labels: cla-signed

#22160 Fail when multiple JVM args matching
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
  core/trino-main/src/test/java/io/trino/server/TestTrinoSystemRequirements.java
Labels: cla-signed, no-release-notes

#22161 Add junit-extensions to modules missing it
  lib/trino-filesystem-cache-alluxio/pom.xml
  plugin/trino-opa/pom.xml
  testing/trino-tests/pom.xml
  testing/trino-tests/src/test/java/io/trino/tests/TestTestSetup.java
Labels: cla-signed, test, no-release-notes

#22158 Simple event listener exposing data via HTTP
  plugin/trino-http-server-event-listener/pom.xml
  plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListener.java
  plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerConfig.java
  plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerFactory.java
  plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerPlugin.java
  plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerEventListener.java
  pom.xml
Labels: cla-signed

#22164 Simplify JVM flag checking logic
  core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
Labels: cla-signed, no-release-notes

#22154 Convert query runner to builder in ClickHouse
  plugin/trino-clickhouse/pom.xml
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityLatestConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseLatestConnectorSmokeTest.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseLatestTypeMapping.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
Labels: cla-signed

#21840 Enable pushdown of a few aggregation functions for ClickHouse Connector
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed, docs
