Repository trinodb/trino, pull requests merged in 2024-08, with the labels that each got.

#22904 Update airlift to 254
  core/trino-main/src/main/java/io/trino/operator/DirectExchangeClientFactory.java
  core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
  core/trino-main/src/test/java/io/trino/operator/TestMergeOperator.java
  pom.xml
  testing/trino-testing/pom.xml
Labels: cla-signed

#22903 Fix username defaulting to user.name property
  client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
  client/trino-client/src/test/java/io/trino/client/uri/TestTrinoUri.java
  client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
Labels: cla-signed, jdbc

#22577 Use hive.parquet.time-zone when reading INT64 timestamps in hive
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetUtil.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestamp.java
Labels: cla-signed, hudi, iceberg, delta-lake, hive

#22918 Update airlift to 255
  pom.xml
Labels: cla-signed

#22900 Add docs for Preview Web UI
  docs/src/main/sphinx/admin.md
  docs/src/main/sphinx/admin/preview-web-interface.md
  docs/src/main/sphinx/admin/properties-web-interface.md
Labels: cla-signed, docs

#22925 Update airlift to 256
  pom.xml
Labels: cla-signed

#22893 Treat Hive schema errors as EXTERNAL
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/HiveFormatUtils.java
  lib/trino-hive-formats/src/main/java/io/trino/hive/formats/HiveFormatsErrorCode.java
  lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestHiveFormatUtils.java
Labels: cla-signed, hive

#22911 Prevent too many concurrent query completed notifications
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerConfig.java
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
  core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerConfig.java
  core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerManager.java
  docs/src/main/sphinx/develop/event-listener.md
Labels: cla-signed, release-notes, docs

#22939 Use parseError() to throw ParsingException in AstBuilder.visitDateTimeType()
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
Labels: cla-signed

#22924 don't pass serialization lib to coral
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/CoralSemiTransactionalHiveMSCAdapter.java
Labels: hive

#22942 Remove no longer needed optimization
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
Labels: cla-signed

#22950 Revert "Remove no longer needed optimization"
  core/trino-main/src/main/java/io/trino/util/JsonUtil.java
Labels: cla-signed

#22948 Add support for execute procedure in BigQuery connector
  docs/src/main/sphinx/connector/bigquery.md
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnector.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/procedure/ExecuteProcedure.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, docs, bigquery

#22933 Disable flaky testDeleteRowsConcurrently in Iceberg JDBC catalog
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
Labels: cla-signed, iceberg

#22964 Use delta-kernel for Base85Codec
  plugin/trino-delta-lake/pom.xml
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/Base85Codec.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/DeletionVectors.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/delete/TestBase85Codec.java
Labels: cla-signed, delta-lake

#22959 Add missing predicate rewrites for Redshift
  plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
Labels: cla-signed

#22958 Extract Ldap as an EnvironmentExtender
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentModule.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/OpenLdap.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/OpenLdapReferral.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractEnvSinglenodeLdap.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeLdap.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeLdapAndFile.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeLdapBindDn.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeLdapInsecure.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeLdapReferrals.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-and-file/password-authenticator.properties
Labels: cla-signed

#22969 Simplify testJoinDynamicFilteringBlockProbeSide tests
  plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
  plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
  plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoDynamicFiltering.java
Labels: cla-signed, mongodb

#22633 Use SecretsResolver from Airlift
  core/trino-main/src/main/java/io/trino/connector/CatalogStoreManager.java
  core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
  core/trino-main/src/main/java/io/trino/exchange/ExchangeManagerRegistry.java
  core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
  core/trino-main/src/main/java/io/trino/security/GroupProviderManager.java
  core/trino-main/src/main/java/io/trino/server/Server.java
  core/trino-main/src/main/java/io/trino/server/SessionPropertyDefaults.java
  core/trino-main/src/main/java/io/trino/server/security/CertificateAuthenticatorManager.java
  core/trino-main/src/main/java/io/trino/server/security/HeaderAuthenticatorManager.java
  core/trino-main/src/main/java/io/trino/server/security/PasswordAuthenticatorManager.java
  core/trino-main/src/main/java/io/trino/testing/PlanTester.java
  core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingEventListenerManager.java
  core/trino-main/src/main/java/io/trino/testing/TestingGroupProviderManager.java
  core/trino-main/src/test/java/io/trino/connector/TestCatalogStoreManager.java
  core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
  core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerManager.java
  core/trino-main/src/test/java/io/trino/exchange/TestLazyExchangeDataSource.java
  core/trino-main/src/test/java/io/trino/execution/BaseTestSqlTaskManager.java
  core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
  core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
  core/trino-main/src/test/java/io/trino/execution/TestCallTask.java
  core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
  core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
  core/trino-main/src/test/java/io/trino/execution/TestMemoryRevokingScheduler.java
  core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
  core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTask.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManagerRaceWithCatalogPrune.java
  core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
  core/trino-main/src/test/java/io/trino/execution/TestTaskExecutorStuckSplits.java
  core/trino-main/src/test/java/io/trino/operator/TestDeduplicatingDirectExchangeBuffer.java
  core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java
  core/trino-main/src/test/java/io/trino/operator/TestExchangeOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestMergeOperator.java
  core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
  core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
  core/trino-main/src/test/java/io/trino/security/TestGroupProviderManager.java
  core/trino-main/src/test/java/io/trino/server/TestSessionPropertyDefaults.java
  core/trino-main/src/test/java/io/trino/server/security/TestHeaderAuthenticatorManager.java
  core/trino-main/src/test/java/io/trino/server/security/TestPasswordAuthenticatorManager.java
  core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
  core/trino-server/src/main/provisio/trino.xml
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeSecretsProvider.java
  testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/authenticator.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/catalog/postgresql.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/config-master.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/config-worker.properties
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/generateSecrets.sh
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/password.db
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/secrets.toml
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-secrets-provider/tempto-configuration.yaml
  testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/secrets.toml
Labels: cla-signed

#22618 Add support for euclidean and cosine distance pushdown to pgvector
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java
Labels: cla-signed, docs

#22980 Use delta-kernel for RoaringBitmapArray
  plugin/trino-delta-lake/src/main/java/io/delta/kernel/internal/deletionvectors/RoaringBitmapArrays.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/DeletionVectors.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/PositionDeleteFilter.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/delete/TestDeletionVectors.java
Labels: cla-signed, delta-lake

#22981 Use SecretsResolver for SystemAccessControl
  core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
Labels: cla-signed

#22979 Populate split offset in Iceberg OPTIMIZE procedure
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, iceberg

#22988 Set task_min_writer_count as 1 in testOptimizePopulateSplitOffsets
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, iceberg

#22985 Airbase 163 and Airlift 260
  pom.xml
Labels: cla-signed

#22990 Add StageTaskStatistics#getSplitDistribution
  core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
  core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageTaskStatistics.java
Labels: cla-signed

#22991 Configure SecretsResolver in RPM
  core/trino-server-rpm/README.md
  core/trino-server-rpm/src/main/resources/dist/config/secrets.toml
  core/trino-server-rpm/src/main/resources/dist/etc/init.d/trino
  core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
Labels: cla-signed

#22971 Add optimization for Delta v2 checkpoint read
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
Labels: cla-signed, delta-lake

#22963 Remove usage of TrinoException from GcsStorageFactory
  lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsStorageFactory.java
Labels: cla-signed

#23001 Remove unnecessary reassignment in ComparisonStatsCalculator
  core/trino-main/src/main/java/io/trino/cost/ComparisonStatsCalculator.java
Labels: cla-signed

#23010 Update maven plugins
  pom.xml
Labels: cla-signed

#22936 Remove query.low-memory-killer.delay
  core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
  core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
  core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
  testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java
Labels: cla-signed

#23015 Rewrite `-dot_product` to pgvector `<#>` operator in PostgreSQL
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteDotProductFunction.java
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java
Labels: cla-signed

#23020 Various cleanups
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#23021 Increase timeout for diagnostics loggin of stalled scheduler
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed

#23017 Convert DeltaLakeColumnHandle to record
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeBucketFunction.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSource.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplit.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/PositionDeleteFilter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunction.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeComputedStatistics.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeJsonFileStatistics.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/statistics/DeltaLakeParquetFileStatistics.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeProjectionPushdownPlans.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/BenchmarkExtendedStatistics.java
Labels: cla-signed, delta-lake

#22557 Add copyOf check in Analyzer
  core/trino-main/src/main/java/io/trino/sql/analyzer/Analyzer.java
Labels: cla-signed, stale

#23023 Fix binding of FileBasedNetworkTopology
  core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelectorModule.java
Labels: cla-signed

#23033 Support tinyint/smallint to integer type coercion in Iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#23007 Remove event-listener.max-concurrent-query-completed-events
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerConfig.java
  core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
  core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerConfig.java
  core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerManager.java
  docs/src/main/sphinx/develop/event-listener.md
Labels: cla-signed, docs

#22987 Add temporary escape hatch to allow unsafe pushdowns
  core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
  core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
  core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
Labels: cla-signed

#23055 Abbreviate 451 date for consistency
  docs/src/main/sphinx/release/release-451.md
Labels: cla-signed, release-notes, docs

#23051 Fix package and file name in OpenLineage
  plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java
  plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerConfig.java
  plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerModule.java
  plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/console/OpenLineageConsoleTransport.java
  plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransport.java
  plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransportConfig.java
  plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListenerConfig.java
  plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/http/TestOpenLineageHttpTransportConfig.java
Labels: cla-signed

#23049 Use ORDER BY tuple() by default in ClickHouse MergeTree
  docs/src/main/sphinx/connector/clickhouse.md
  plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
  plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
Labels: cla-signed, docs

#23056 Fix labeler config for Web UI module
  .github/config/labeler-config.yml
Labels: cla-signed

#23057 Enhance documentation for `delta.checkpoint-filtering.enabled` setting
  docs/src/main/sphinx/connector/delta-lake.md
Labels: cla-signed, docs

#23058 Increase weight of splits with delete files in iceberg
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
Labels: cla-signed, iceberg

#23011 Increase retries in BigQueryQueryRunner
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
Labels: cla-signed, bigquery

#23008 Throw TrinoException when Iceberg commit fails
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Labels: cla-signed, iceberg

#23099 Disable `testRegisterTableWithDroppedTable` in Polaris
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
Labels: cla-signed, iceberg

#23098 Fix memory tracking for varchar grouped aggregations
  core/trino-main/src/main/java/io/trino/operator/aggregation/state/StateCompiler.java
Labels: cla-signed

#23073 Improve grammar and style
  docs/src/main/sphinx/connector/delta-lake.md
Labels: cla-signed, docs

#22368 Add session properties for prometheus connector
  docs/src/main/sphinx/connector/prometheus.md
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnector.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusModule.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusSessionProperties.java
  plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusSplitManager.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegration.java
  plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusSplit.java
Labels: cla-signed, docs

#23116 Fix logic obtaining workers memory in FTE execution
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ExponentialGrowthPartitionMemoryEstimator.java
  core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
  testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionCoordinatorExcludedTest.java
Labels: cla-signed, RELEASE-BLOCKER

#22914 Add missing TaskExecutorResource to jmx
  core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
Labels: cla-signed

#23088 Throw TrinoException on AWS errors in GlueHiveMetastore.updateTable
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Labels: cla-signed, hive

#23136 Improve docs for built-in table functions
  docs/src/main/sphinx/functions/table.md
Labels: cla-signed, docs

#23050 Fix handling of duplicate column names in parquet reader
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java
  lib/trino-parquet/src/main/java/io/trino/parquet/metadata/PrunedBlockMetadata.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
Labels: bug, cla-signed, hive

#23027 Update Maven to 3.9.9
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#23138 Keep last parameters when updating Glue in Delta
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/glue/v1/DeltaLakeGlueV1MetastoreTableOperations.java
Labels: cla-signed, delta-lake

#23089 Make docker image name in PostgreSQL query runner configurable
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/PostgreSqlQueryRunner.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
Labels: cla-signed

#23144 Make web-ui module builds reproducible
  core/trino-web-ui/src/main/resources/webapp-preview/package.json
  core/trino-web-ui/src/main/resources/webapp/src/package.json
Labels: cla-signed, ui

#23094 Add legacy to native migration guides
  docs/src/main/sphinx/object-storage/legacy-azure.md
  docs/src/main/sphinx/object-storage/legacy-gcs.md
  docs/src/main/sphinx/object-storage/legacy-s3.md
Labels: cla-signed, docs

#23071 Allow configuring endpoint for Azure FS
  docs/src/main/sphinx/object-storage/file-system-azure.md
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemConfig.java
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureLocation.java
  lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemConfig.java
  lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureLocation.java
Labels: cla-signed, docs

#23146 Update iceberg to 1.6.1
  pom.xml
Labels: cla-signed

#23039 Use exponential backoff retry strategy for glue client
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueClientUtil.java
Labels: cla-signed, hive

#23090 Use RemoteTableName in JdbcOutputTableHandle
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcOutputTableHandle.java
  plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RemoteTableName.java
  plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcOutputTableHandle.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
  plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteOutputTableHandle.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeSink.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
  plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixOutputTableHandle.java
  plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Labels: cla-signed

#23150 Expose disableIfBranchMatches as maven config
  pom.xml
Labels: cla-signed

#23142 List delete files in Iceberg's $files metadata table
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Labels: cla-signed, iceberg

#23156 Update Azure SDK to 1.2.27
  lib/trino-filesystem-azure/pom.xml
  lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
  lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
  pom.xml
Labels: cla-signed

#23159 Update google cloud SDK & parquet library
  pom.xml
Labels: cla-signed

#23162 Add caution for MySQL library upgrade
  pom.xml
Labels: cla-signed

#23165 Fix failure when rewriting distance functions in PostgreSQL
  plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java
  plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java
Labels: cla-signed

#23167 Disable testTableSampleBernoulli in BigQuery
  plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
  plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Labels: cla-signed, bigquery

#22529 Add support AWS-KMS on S3 for FTE
  plugin/trino-exchange-filesystem/pom.xml
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/ExchangeS3Config.java
  plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/containers/MinioStorage.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestExchangeS3Config.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestS3FileSystemExchangeManagerSseKms.java
  plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestS3FileSystemExchangeManagerSseS3.java
  plugin/trino-exchange-filesystem/src/test/resources/kms/config.yml
  plugin/trino-exchange-filesystem/src/test/resources/kms/kms.crt
  plugin/trino-exchange-filesystem/src/test/resources/kms/kms.key
  plugin/trino-exchange-filesystem/src/test/resources/minio/kms_client.crt
  plugin/trino-exchange-filesystem/src/test/resources/minio/kms_client.key
  plugin/trino-exchange-filesystem/src/test/resources/readme.txt
  testing/trino-testing-containers/src/main/java/io/trino/testing/containers/KeyManagementServer.java
Labels: cla-signed

#23166 Remove redundant cast
  core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java
  core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
  core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
  core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PlanNodeDecorrelator.java
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
  plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/EstimateAssertion.java
Labels: cla-signed, hive

#23070 Keep most recent task failure in failures history
  core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Labels: cla-signed, no-release-notes

#23176 Edit file formats properties
  docs/src/main/sphinx/connector/delta-lake.md
  docs/src/main/sphinx/connector/hive.md
  docs/src/main/sphinx/connector/hudi.md
  docs/src/main/sphinx/connector/iceberg.md
  docs/src/main/sphinx/object-storage/file-formats.md
  docs/src/main/sphinx/release/release-396.md
Labels: cla-signed, release-notes, docs

#23096 Add Trino 455 release notes
  docs/src/main/sphinx/admin.md
  docs/src/main/sphinx/release.md
  docs/src/main/sphinx/release/release-455.md
Labels: cla-signed, release-notes, docs

#22755 Add compatibility note to S3 file system page
  docs/src/main/sphinx/admin/fault-tolerant-execution.md
  docs/src/main/sphinx/object-storage/file-system-s3.md
Labels: cla-signed, docs

#22448 Migrate identity column to integration tests in Delta
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
  plugin/trino-delta-lake/src/test/resources/databricks133/identity_columns_table_feature/README.md
  plugin/trino-delta-lake/src/test/resources/databricks133/identity_columns_table_feature/_delta_log/00000000000000000000.json
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeIdentityColumnCompatibility.java
Labels: cla-signed, delta-lake, stale-ignore

#23047 Add support for creating Delta tables with deletion vectors
  docs/src/main/sphinx/connector/delta-lake.md
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
  plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
  plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Labels: cla-signed, docs, delta-lake

#23189 Use new Reproducible Builds badge
  README.md
Labels: cla-signed

#23190 Fix regression on disabled HTTP/2 negotiation
  client/trino-client/src/main/java/io/trino/client/uri/HttpClientFactory.java
Labels: cla-signed

#23191 Fix broken test of SHOW CREATE TABLE in Databricks
  testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
Labels: cla-signed

#23198 Update airbase to 171 and airlift to 262
  pom.xml
Labels: cla-signed

#23194 Increase hive.metastore-cache-maximum-size to 20000
  docs/src/main/sphinx/object-storage/metastores.md
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
  plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
Labels: cla-signed, docs, performance, hive

#23060 Pass credential when creating SessionContext in REST metastore
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
Labels: cla-signed, iceberg

#23004 Add support for replacing tables in BlackHole
  plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
  plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleMetadata.java
  plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
Labels: cla-signed

#23202 Disable testRegisterTableWithDroppedTable in Polaris
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
Labels: cla-signed, iceberg

#23204 Don't run CI for markdown file changes
  .github/workflows/ci.yml
Labels: cla-signed

#23210 Update pinot to 1.2.0
  plugin/trino-pinot/pom.xml
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotModule.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java
  plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotExpressionRewriter.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/MetadataUtil.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorSmokeTest.java
  plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
Labels: cla-signed
