Repository trinodb/trino, pull requests merged in 2025-07, with the labels that each got.

#26121 Create Alluxio client once
  lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemFactory.java
  lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemModule.java
Labels: cla-signed

#26124 Fix typo in StaticTokenAwareMetastoreClientFactory
  plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/StaticTokenAwareMetastoreClientFactory.java
Labels: cla-signed, hive

#26126 Update dependencies
  pom.xml
Labels: cla-signed

#26015 Make queued and buffered rows configurable in cli
  client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
  client/trino-cli/src/main/java/io/trino/cli/Console.java
  client/trino-cli/src/main/java/io/trino/cli/OutputHandler.java
  client/trino-cli/src/main/java/io/trino/cli/Query.java
  client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
  client/trino-cli/src/test/java/io/trino/cli/TestClientOptions.java
  client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
Labels: cla-signed

#26127 Add explicitly cast for merge tests in `BaseConnectorSmokeTest`
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
Labels: cla-signed

#26131 Fix error assertion message for snowflake null
  plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Labels: cla-signed, snowflake

#26140 Use `RunLengthEncodedBlock` for null column appends
  plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java
Labels: cla-signed, memory

#26141 Do not set spiller to empty in SpillableHashAggregationBuilder
  core/trino-main/src/main/java/io/trino/operator/aggregation/builder/SpillableHashAggregationBuilder.java
Labels: cla-signed

#26144 Update ErrorProne rules
  pom.xml
Labels: cla-signed

#26165 Update dependencies
  pom.xml
Labels: cla-signed

#26171 Fix NPE due to NULL default column values
  core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
  core/trino-main/src/test/java/io/trino/util/TestColumnDefaultOptions.java
Labels: cla-signed

#26184 Fix reading variant null values in Delta Lake
  lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java
  plugin/trino-delta-lake/src/test/resources/databricks154/test_variant_null/README.md
  plugin/trino-delta-lake/src/test/resources/databricks154/test_variant_null/_delta_log/00000000000000000000.json
  plugin/trino-delta-lake/src/test/resources/databricks154/test_variant_null/_delta_log/00000000000000000001.json
  plugin/trino-delta-lake/src/test/resources/databricks154/test_variant_null/part-00000-370c7cfb-47f7-4c81-81bd-3ecd7b5b4c41-c000.snappy.parquet
  plugin/trino-delta-lake/src/test/resources/databricks154/test_variant_null/part-00000-3dae12c4-61bc-4177-bd36-2c936db81e90-c000.snappy.parquet
Labels: cla-signed, delta-lake

#26198 Include additional client failure information in the exception
  client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
  client/trino-client/src/test/java/io/trino/client/TestRetry.java
Labels: cla-signed

#26174 Using explicit cast on bigint columns in row level update tests
  testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Labels: cla-signed

#26211 Update Maven to 3.9.11
  .mvn/wrapper/maven-wrapper.properties
Labels: cla-signed

#26200 Remove `@Experimental` annotation
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/Experimental.java
  core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
  core/trino-spi/src/main/java/io/trino/spi/block/ValueBlock.java
  core/trino-spi/src/main/java/io/trino/spi/connector/CatalogHandle.java
  core/trino-spi/src/main/java/io/trino/spi/connector/Connector.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplitManager.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableSchema.java
  core/trino-spi/src/main/java/io/trino/spi/connector/RelationColumnsMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/connector/RelationCommentMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/exchange/Exchange.java
  core/trino-spi/src/main/java/io/trino/spi/function/AggregationFunctionMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/function/AggregationImplementation.java
  core/trino-spi/src/main/java/io/trino/spi/function/BoundSignature.java
  core/trino-spi/src/main/java/io/trino/spi/function/FunctionDependencies.java
  core/trino-spi/src/main/java/io/trino/spi/function/FunctionDependencyDeclaration.java
  core/trino-spi/src/main/java/io/trino/spi/function/FunctionId.java
  core/trino-spi/src/main/java/io/trino/spi/function/FunctionMetadata.java
  core/trino-spi/src/main/java/io/trino/spi/function/FunctionNullability.java
  core/trino-spi/src/main/java/io/trino/spi/function/FunctionProvider.java
  core/trino-spi/src/main/java/io/trino/spi/function/LongVariableConstraint.java
  core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionImplementation.java
  core/trino-spi/src/main/java/io/trino/spi/function/SchemaFunctionName.java
  core/trino-spi/src/main/java/io/trino/spi/function/Signature.java
  core/trino-spi/src/main/java/io/trino/spi/function/TypeVariableConstraint.java
  core/trino-spi/src/main/java/io/trino/spi/function/WindowFunctionSupplier.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/AbstractConnectorTableFunction.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/Argument.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ConnectorTableFunction.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ConnectorTableFunctionHandle.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/Descriptor.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/DescriptorArgument.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/DescriptorArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/NameAndPosition.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ReturnTypeSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ScalarArgument.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/ScalarArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableArgument.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableArgumentSpecification.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableFunctionAnalysis.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableFunctionProcessorProvider.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableFunctionProcessorState.java
  core/trino-spi/src/main/java/io/trino/spi/function/table/TableFunctionSplitProcessor.java
  core/trino-spi/src/main/java/io/trino/spi/spool/SpooledLocation.java
  core/trino-spi/src/main/java/io/trino/spi/spool/SpooledSegmentHandle.java
  core/trino-spi/src/main/java/io/trino/spi/spool/SpoolingContext.java
  core/trino-spi/src/main/java/io/trino/spi/spool/SpoolingManagerContext.java
  core/trino-spi/src/main/java/io/trino/spi/spool/SpoolingManagerFactory.java
  core/trino-spi/src/main/java/io/trino/spi/statistics/ColumnStatisticMetadata.java
Labels: cla-signed

#26132 Add support for `max.request.size` and `batch.size` configuration for Kafka Event Listener
  docs/src/main/sphinx/admin/event-listeners-kafka.md
  plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListenerConfig.java
  plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/producer/BaseKafkaProducerFactory.java
  plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaEventListenerConfig.java
Labels: cla-signed, docs

#26222 Remove deprecated ConnectorPageSource.getNextPage
  core/trino-main/src/test/java/io/trino/connector/MockConnectorPageSource.java
  core/trino-spi/pom.xml
  core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorPageSource.java
  core/trino-spi/src/main/java/io/trino/spi/connector/EmptyPageSource.java
  core/trino-spi/src/main/java/io/trino/spi/connector/FixedPageSource.java
  core/trino-spi/src/main/java/io/trino/spi/connector/RecordPageSource.java
Labels: cla-signed

#26221 Document s3.cross-region-access config property
  docs/src/main/sphinx/object-storage/file-system-s3.md
Labels: cla-signed, docs

#26218 Replace sigv4-enabled with security in Iceberg
  docs/src/main/sphinx/object-storage/metastores.md
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SigV4AwsProperties.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SigV4SecurityModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergS3TablesConnectorSmokeTest.java
Labels: cla-signed, docs, iceberg

#26143 Update Iceberg to 1.9.2
  pom.xml
Labels: cla-signed

#26233 Add America/Coyhaique time zone
  core/trino-spi/src/main/resources/io/trino/spi/type/zone-index.properties
  core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java
Labels: cla-signed

#26234 Convert trino-main test classes to record
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorColumnHandle.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorInsertTableHandle.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorOutputTableHandle.java
  core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java
  core/trino-main/src/test/java/io/trino/execution/TestSqlTaskExecution.java
  core/trino-main/src/test/java/io/trino/execution/TestingFailureInjector.java
  core/trino-main/src/test/java/io/trino/operator/GroupByHashYieldAssertion.java
  core/trino-main/src/test/java/io/trino/operator/TestDistinctLimitOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestMarkDistinctOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestRowNumberOperator.java
  core/trino-main/src/test/java/io/trino/operator/TestTopNRankingOperator.java
  core/trino-main/src/test/java/io/trino/server/TestSliceSerialization.java
  core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
  core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java
  core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationsToSubqueries.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableScanColumns.java
  core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushJoinIntoTableScan.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesScaledWriters.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java
  core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestRemoveEmptyUnionBranches.java
  testing/trino-tests/src/test/java/io/trino/execution/TestTableRedirection.java
Labels: cla-signed

#26203 Respect Parquet Logical type when reading statistics
  lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
  lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
  lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java
Labels: bug, cla-signed, correctness

#26248 Do not inline tail, small pages if inilining is disabled
  core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
Labels: cla-signed

#26244 Remove unused S3 dependency from Hive
  plugin/trino-hive/pom.xml
Labels: cla-signed, hive

#26068 Update docker image to UBI 10
  core/docker/Dockerfile
Labels: cla-signed, stale

#26268 Implement `toString` method in InformationSchemaTableHandle and InformationSchemaColumnHandle
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaColumnHandle.java
  core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTableHandle.java
Labels: cla-signed

#26266 Convert QueryEntity to record in MySQL event listener
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryEntity.java
  plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/RecordAndAnnotatedConstructorMapper.java
Labels: cla-signed

#26136 Add support for write operations (INSERT/UPDATE/DELETE/MERGE) with branch
  core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
  core/trino-main/src/main/java/io/trino/metadata/TableVersion.java
  core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
  core/trino-main/src/test/java/io/trino/connector/MockConnector.java
  core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
  core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
  core/trino-main/src/test/java/io/trino/sql/query/TestBranching.java
  core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
  core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
  core/trino-parser/src/main/java/io/trino/sql/tree/Table.java
  core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
  core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Labels: cla-signed

#26277 Update Snowflake JDBC driver to 3.25.1
  pom.xml
Labels: cla-signed

#26278 Convert to record in Thrift connector
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftColumnHandle.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftConnectorSplit.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftIndexHandle.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftIndexPageSource.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftMetadata.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftPageSource.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftSplitManager.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftTableHandle.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftTableMetadata.java
  plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/util/TupleDomainConversion.java
  plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftProjectionPushdown.java
Labels: cla-signed

#26273 Remove unnecessary usage of SimplePagesHashStrategy
  core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
  core/trino-main/src/test/java/io/trino/sql/gen/TestJoinCompiler.java
Labels: cla-signed

#26279 Use icebergScanExecutor for reading manifests in optimize and expire_snapshots
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Labels: cla-signed, iceberg

#26288 Add TestLakehousePlugin
  plugin/trino-lakehouse/src/test/java/io/trino/plugin/lakehouse/TestLakehousePlugin.java
Labels: cla-signed

#26230 Improve file delete performance for expire_snapshots
  docs/src/main/sphinx/connector/iceberg.md
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ForIcebergFileDelete.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergExecutorModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperationsProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperationsProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperationsProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcTableOperationsProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperationsProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/SnowflakeIcebergTableOperationsProvider.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/TrinoSnowflakeCatalog.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIoFactory.java
  plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
  plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/TrinoIcebergSnowflakeCatalogFactory.java
  plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/TrinoIcebergSnowflakeCatalogFileIOFactory.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestAbstractIcebergTableOperations.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestTrinoHiveCatalogWithFileMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogSkipArchive.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
  plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/util/EqualityDeleteUtils.java
  plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
  plugin/trino-lakehouse/src/main/java/io/trino/plugin/lakehouse/LakehouseIcebergModule.java
Labels: cla-signed, docs, performance, iceberg

#25554 Add query details page to the Preview Web UI
  core/trino-web-ui/src/main/resources/webapp-preview/package-lock.json
  core/trino-web-ui/src/main/resources/webapp-preview/package.json
  core/trino-web-ui/src/main/resources/webapp-preview/src/App.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/api/webapp/api.ts
  core/trino-web-ui/src/main/resources/webapp-preview/src/components/CodeBlock.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/components/Layout.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryDetails.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryListItem.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryOverview.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryProgressBar.tsx
  core/trino-web-ui/src/main/resources/webapp-preview/src/constant.ts
  core/trino-web-ui/src/main/resources/webapp-preview/src/utils/utils.ts
Labels: cla-signed, ui

#26293 Make EmptyFieldStrategy as a common enum
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroSchemaConverter.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryConfig.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSessionProperties.java
  plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/EmptyFieldStrategy.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroSchemaConverter.java
  plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestConfluentSchemaRegistryConfig.java
Labels: cla-signed, kafka

#26128 Include Trino user header in graceful shutdown docs
  docs/src/main/sphinx/admin/graceful-shutdown.md
Labels: cla-signed, docs
